radareorg/radare2

libr/anal/arch/hexagon/hexagon_anal.c, libr/anal/p/anal_hexagon.c, libr/asm/arch/hexagon/hexagon.h, libr/asm/arch/hexagon/hexagon_disas.c, libr/asm/p/asm_hexagon.c
For reference:
The problem was discussed here: https://github.com/radare/radare2/issues/12352
Script for generation of the files can be found here: https://github.com/radareorg/r2hexagon
Tests: https://github.com/radare/radare2-regressions/pull/1931
=> Fix hexagon jumps second try

libr/io/p/io_self.c
Instead, recursively going through the regions while focusing
on main addresses and grabbing pages states informations.
=> Simplification of the io_self plugin for mac proposal.

libr/cons/dietline.c
* Simulate escape sequences in r_line_readchar_win
* Fix some bugs on Windows
* Some refactoring
+ Better UTF-8 support in Vi mode
=>  Merge Windows and Unix readline implementation

libr/cons/dietline.c
=> Fix crash in r_line_readchar_win

libr/core/cmd_anal.c
=> Fix afvn outside of Function

libr/main/radare2.c
=> Fixes ##14834 fix = breaking term config

libr/util/json_indent.c
=> Fixes #14534: Ignore non-printable and non json chars

libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_core.h, libr/main/radiff2.c
=> Fixes #14845: Use unicode settings in radiff2

shlr/gdb/src/gdbclient/responses.c
Fix #14872 
@roboman2444 could you test if this fixes your problem?
=> WIP: Remove recursive handle_stop_reason call

libr/cons/dietline.c, libr/core/visual.c
Things where random stuff was being inserted in visual:
* offset
* f
* d
* ;
* ,
=> Fixes #14896: Enable and disable mouse based on requirement (visual & panel)

libr/core/cfile.c, libr/core/visual.c, libr/io/p/io_gdb.c, libr/io/p/io_mach.c, libr/io/p/io_ptrace.c, libr/io/p/io_r2k.c, libr/io/p/io_r2web.c, libr/io/p/io_w32dbg.c, libr/io/p/io_winedbg.c, libr/main/radare2.c
* Useful for r2frida to automatically run .=!i*
=> Add support for io-plugin initialization via null system command =!

libr/anal/cc.c, libr/anal/meta.c, libr/bin/p/bin_dyldcache.c, libr/config/config.c, libr/core/cbin.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/cmd_help.c, libr/core/cmd_print.c, libr/core/cmd_type.c, libr/core/panels.c, libr/core/rtr_http.c, libr/core/vmenus.c, libr/flag/tags.c, libr/include/r_util/r_str.h, libr/include/r_util/r_table.h, libr/io/plugin.c, libr/main/r2agent.c, libr/util/str.c, libr/util/str_trim.c, libr/util/syscmd.c, libr/util/table.c
* r_str_split_list() rewritten to support nth limit
r2 -qq -c 'aac;aflt size/gt/200,addr/cols/name/nbbs,nbbs/sort/inc' /bin/ls
=> Implement 'cols' RTable.query to filter by column names ##print

libr/core/task.c, libr/include/r_core.h
Not using a predicate here is theoretically wrong.
=> Add Predicate for Task Dispatch

libr/include/r_cons.h, libr/util/print.c
Used the same colors and block character, after change:
=> Used block character for p= and p== graphs

libr/cons/cons.c, libr/cons/dietline.c
* Removed the unnecessary empty line
* get cur line working fine when autocompletion is for second arg. Command completion is still buggy. Still looking at it.
=> Fix autocompletion popup

libr/core/disasm.c
https://github.com/kazarmy/radare2-regressions/commit/931f497da7efc2e19267f79a1a3660e04b9f9707
=> asm.bb.line: Also show bblines between bb and non-bb

libr/core/cmd_debug.c, libr/debug/meson.build, libr/debug/p/native/windows/windows_message.c, libr/debug/p/native/windows/windows_message.h
=> Fix #14154 - Implement Windows message breakpoints

libr/debug/p/native/xnu/xnu_debug.c, libr/debug/p/native/xnu/xnu_debug.h
For platforms supporting the libproc api.
=> On Darwin, expose process path ##debug

libr/core/panels.c
Now it's all cool cos I fixed a very very ugly visual bug in the panels mode (menu)
=> R2CON2019 Panels mode menu kept wiggling around

libr/core/panels.c
Removing all the panels from the menu does not work properly and now it's fixed with this.
=> Fix panels removing all the layouts

libr/util/sys.c
We are set to configure not to read data.
=> ASLR check setting fix on FreeBSD ##util

libr/bin/format/wasm/wasm.c
This PR contains two small fixes for WASM support.  I ran the regression test suite and didn't see any regressions with these patches applied.
=> Wasm bug fixes

libr/bin/p/bin_dex.c
Fix issue  https://github.com/radare/radare2/issues/14904
=> Fix Android DEX Adler checksum outputing in info

binr/r2pm/r2pm
The `${2%${2#?}}` construct is based on https://serverfault.com/questions/249395/shell-check-if-variable-begins-with/252406#252406.
=> R2PM_TGZ: If 2nd param starts with /, assume it's root dir of archive

libr/anal/fcn.c, libr/anal/p/anal_x86_cs.c, libr/core/canal.c, libr/core/cmd_anal.c
e io.cache=1
e anal.nopskip=true
wx 9090909090909090c3
af
pd 13
afi
=> Fix nopskip (its not fixed at all. just random typing here and there)

libr/bin/bin.c, libr/bin/bobj.c, libr/bin/format/mach0/mach0.c, libr/bin/p/bin_dex.c, libr/bin/p/bin_elf.inc, libr/bin/p/bin_pe.c, libr/bin/p/bin_pe64.c, libr/core/cbin.c, libr/include/r_bin.h
=> Fix named/raw Formats in RBinField

libr/anal/d/types-linux.sdb.txt
=> Fix #15022: add cxa_throw as noreturn

.builds/freebsd.yml
=> Fix FreeBSD SourceHut build

libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_search.c, libr/include/r_core.h
Fix #15074 
Additional tests: https://github.com/radareorg/radare2-regressions/pull/1954
I can't guarantee for no breakage except what is tested by r2r.
=> Refactor Search to use less Global State

binr/r2agent/meson.build, binr/rabin2/meson.build, binr/radare2/meson.build, binr/radiff2/meson.build, binr/rafind2/meson.build, binr/ragg2/meson.build, binr/rahash2/meson.build, binr/rarun2/meson.build, binr/rasm2/meson.build, binr/rax2/meson.build, meson.build, meson_options.txt, sys/meson.py
For non-root installs and side-by-side builds.
=> Set rpath if non-Windows Meson shared build

libr/anal/rtti.c, libr/anal/rtti_msvc.c, libr/bin/bin.c, libr/bin/demangle.c, libr/bin/mangling/demangler.c, libr/bin/mangling/microsoft_demangle.c, libr/include/r_anal.h, libr/include/r_bin.h
=> Fix #5446 - Implement msvc RTTI demangling

libr/bin/bfile.c, libr/core/cconfig.c, libr/core/cfile.c, libr/core/cmd_open.c
This is in a "better than nothing" stage.
Currently rebasing only cur bin:
* Functions (and bbs)
* Flags
* Meta items (comments, etc)
* Refs / XRefs
=> Rebase things when reopening file in debugger mode

libr/bin/format/nes/nes_specs.h, libr/bin/p/bin_nes.c
=> add NES ROM mirroring

libr/util/str.c
=> Fix use-after-free bugs in r_str_replace*

libr/util/table.c
=> Fix #15070: Use block chars for ascii print table

libr/debug/p/native/xnu/xnu_debug.c
Storing max protection data for this purpose.
=> Using unused map debug field on macOS ##debug

libr/core/panels.c, libr/debug/p/debug_native.c
While at it fixing little code mistake about freeing const address.
=> Implementing debug info per pid on NetBSD ##debug

libr/anal/p/anal_x86_cs.c
cleaner fix is WIP.
This one should work for now
=> hotfix for #14851

libr/core/cmd_flag.c, libr/util/spaces.c
* Also trim new flag space names
=> Fix #15147 - Fix spaces renaming

libr/core/cmd_cmp.c
=> Implement cj command

libr/anal/p/anal_6502.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_avr.c, libr/anal/p/anal_h8300.c
=> anal_{arm_cs,avr,6502,h8300}: update sf/of use

libr/anal/esil.c, libr/anal/p/anal_6502.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_avr.c, libr/anal/p/anal_h8300.c, libr/anal/p/anal_pic.c, libr/anal/p/anal_sh.c, libr/anal/p/anal_v810.c, libr/anal/p/anal_v850.c, libr/anal/p/anal_x86_cs.c
Just like we already do for $c and $b
=> Add a parameter to $s and $o

.appveyor.yml
It was updated from the Inno Setup 5.0 in https://github.com/appveyor/ci/issues/2948
Lets check if it works.
=> Use Inno Setup 6.0 for Windows builds

libr/core/canal.c
https://github.com/radareorg/radare2-regressions/commit/c281ac9c1af545c517f11951b49a653ccd9b2d38
Fixes https://github.com/radareorg/radare2/pull/15141#issuecomment-536556946.
=> Don't propagate noret to fcn if fcn jmps outside itself

libr/core/panels.c
Doing the other way around and casting for proper calls.
=> Fix const address freeing ##panels

libr/bin/mangling/microsoft_demangle.c
* Fix infinite loop
* Fix demangling templates with special names
* Fix not using type modifier for member function access code
=> Fixes for MSVC demangling

libr/bin/mangling/microsoft_demangle.c, libr/bin/pdb/pdb.c
* Fix double-free
* Fix command injection
* Fix retrieving return based operator
=> More fixes for MSVC demangling

libr/lang/p/pipe.c
=> Fix #15224 - Print child output in pipe lang plugin on windows

libr/cons/dietline.c
Inverse page up and page down in the autocompletion popup.
=> Fix #15222

libr/bin/bin.c, libr/core/cbin.c, libr/include/r_util/r_table.h, libr/util/print.c, libr/util/table.c
Integrated with:
* is
* ia
* iS
* ir
* iz
=> WIP WIP: Fix #15132: Integrate table to I based commands

libr/bin/bin.c
* obj->obj_size is 64 bits
* offset is unsigned
=> Fix formatting for r_bin_list_archs

libr/core/cmd_anal.c
```
:> afoj
{"address":"0x00013adc"}
:> afdj
{"name":"fcn.00013adc"}
```
=> Json output for afo and afd

libr/anal/fcn.c
https://github.com/radareorg/radare2-regressions/commit/ff5127a694eaf21ca382612d4155c9008db27eca
For https://github.com/radareorg/radare2/pull/15208#issuecomment-539059124.
=> WIP: Add jumptable support for main() in bins/elf/ls.odd

libr/asm/arch/8051/8051_ass.c
8051 natively uses an '@' prefix for indirect access, which is
a bit awkward is r2, so it should also support the bracket syntax:
xrl a, @r0
xrl a, [r0]
Additionally, I refactored the argument tokenization so that it's all done
up-front, making everything easier to work with, saving about 800 LOC.
=> add additional [indirect] access syntax for 8051

libr/flag/flag.c, libr/util/buf.c, shlr/mpc/mpc.c
Fix a null dereference in flag.c and initialize some variables.
=> Minor code fixes

libr/anal/anal.c, libr/anal/fcn.c, libr/anal/p/anal_java.c, libr/core/blaze.c, libr/core/canal.c, libr/core/cbin.c, libr/core/cmd_anal.c, libr/include/r_anal.h
=> Make RAnalFunction.cc come from RAnal String Pool ##anal

libr/cons/utf8.c, libr/include/r_cons.h
* Also boolify r_cons_is_utf8()
=> Also use LANG env var to check for UTF-8 output support

libr/main/r2agent.c
=> Fix possible command overflow #r2agent

libr/util/buf_ref.c
r2r PR: https://github.com/radareorg/radare2-regressions/pull/1985
=> buf_ref: make sure the reference buffer does not exceed the parent size

libr/anal/fcn.c
=> Rename set_meta_min_if_needed() to set_meta_if_needed()

libr/io/p/io_ptrace.c
This reverts commit 0f430b587163d2ecb5fe783108261a63cd45f92e.
@XVilka
=> Fix ptrace io plugin open

libr/bin/bfile.c, libr/bin/bin.c, libr/bin/bobj.c, libr/bin/dwarf.c, libr/core/cbin.c, libr/core/cfile.c, libr/core/cmd_info.c, libr/core/cmd_open.c, libr/include/r_bin.h
* introduce r_bin_open_buf
* fix r_bin_file_delete to use bf->id and not fd. This was used
inconsistently and the function was just wrong.
* rewrite r_bin_reload to just reuse the existing bf->buf
* fix some memory leaks
=> A bit of refactoring in RBin

libr/anal/var.c
R2R: https://github.com/radareorg/radare2-regressions/pull/2000
=> Select default var type based on its size

libr/anal/p/anal_arm_cs.c
Also fixed remaining ARM str post-indexing problems w/ register offsets in https://github.com/radareorg/radare2/pull/15298 Forgot to fix it last time.
=> Merged ESIL parsing for ARM str instructions of all sizes.

libr/anal/esil_dfg.c, libr/core/esil_data_flow.c, libr/include/r_anal.h, libr/util/rbtree.c
It already works, but I'd like to do a bit more cleanup before merge.
=> Improve registers handling in ESIL dfg ##esil

DEVELOPERS.md
=> Fix links to Doxygen documentation

libr/core/cmd_debug.c
This also solves an issue with drrj in windows since the code relied on iter->p to know if a comma should be prepended, but windows always has it initialized so it was always prepended - invalidating the JSON.
Before: 
`[,{"reg":"rax","value":"0x0","ref":" 0"}, ...`
After:
`[{"reg":"rax","value":"0x0","ref":" 0"}, ...`
=> Use pj api in drrj

libr/core/cmd_anal.c
This is helpful for generating and matching types when using zignatures.
=> Insert arguments into types SDB on function analysis ##anal

libr/core/cmd_debug.c, libr/reg/value.c
Just some refactoring in preparation of the addition of ymm registers.
=> Refactor `drm`

sys/meson.py, sys/sanitize.sh
As per https://github.com/radareorg/radare2/pull/15405#issuecomment-549237315 and also as a reminder that there are other sanitizers besides **A**ddress**San**itizer.
=> Rename "asan" to "sanitize"

libr/core/cconfig.c, libr/core/rtr.c, libr/include/r_th.h, libr/main/radare2.c, libr/util/thread.c
=> CPU affinity API introduction ##r_util

libr/debug/p/native/windows/windows_debug.c
* Fix error when continuing after attaching to process
* Get threads correct EIP
* Fix some memory corruptions and small refactor
=> Fixes for Windows debugging

libr/core/cmd_anal.c, libr/include/r_anal.h
=> Initial implementation of afvf - show bp-relative stackvars ##anal

libr/anal/jmptbl.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/disasm.c
* Fix default case flag name
before:
after:
=> Improve switch-statements in disassembly ##disasm

libr/core/cmd_print.c, libr/include/r_util.h, libr/include/r_util/r_protobuf.h, libr/util/Makefile, libr/util/meson.build, libr/util/protobuf.c
=> Fix #14661 - Raw protobuf support

libr/util/str_constpool.c
Test: https://github.com/radareorg/radare2-regressions/pull/2010
=> Use HtPP for RStrConstPool

libr/core/cmd_zign.c
Part 1:
This allows the 'zg' command to auto generate zignspaces from function
names by utilising the ':' convention used in zignatures. Now when 'zg' is
run if any funtion names are in the format ZIGNSPACE:FUNCTION, the
zignspace will be extracted, created and the function applied under its
scope.
=> WIP: add auto zignspace generation for the zg command

libr/include/r_flag.h
=> Fix comment about RFlag.ht_name

libr/core/cmd_open.c
=> Use PJ in oj

libr/core/disasm.c
https://github.com/radareorg/radare2-regressions/commit/e1d6be48cf6c01f5ac7b1e4c2af509cdb1f10101
For #14682.
=> pd: Don't abort string printing on initial null if bin.str.enc != guess

libr/bin/meson.build, libr/bin/p/Makefile, libr/bin/p/bin_prg.c, libr/bin/p/prg.mk, libr/include/r_bin.h, libr/meson.build, plugins.def.cfg
Test: https://github.com/radareorg/radare2-regressions/pull/2014
=> Add C64 PRG Bin Plugin

shlr/gdb/include/libgdbr.h, shlr/gdb/src/gdbclient/core.c, shlr/gdb/src/libgdbr.c, shlr/gdb/src/packet.c
Reg writing fixes to get gdbr reverse stepping to work and more improvements to breaking for Cutter.
=> Libgdbr reg writing fixes and read_reg breaking

libr/core/cbin.c
* No more hacky base64
* iz != izz, before izz was iz+izz
=> Fix #15392  - Use pj in the izj and izzj commands ##bin

libr/core/disasm.c, libr/include/r_util/r_utf8.h, libr/util/utf8.c
https://github.com/radareorg/radare2-regressions/commit/f259e4ee99d4c9a009aa216b75ff07c74d018269
For #14682 and https://github.com/radareorg/radare2/pull/15450#issuecomment-552970915.
=> Recognize Unicode BOMs

libr/core/cconfig.c, libr/core/disasm.c, libr/include/r_util/r_str.h, libr/include/r_util/r_utf32.h, libr/util/str.c, libr/util/utf32.c, libr/util/utf8.c
https://github.com/radareorg/radare2-regressions/commit/84a46684b379ed761f8702e3bb8ceb4e8dd976f5
=> Support UTF32-BE decoding

libr/socket/socket.c, shlr/gdb/src/gdbclient/core.c, shlr/gdb/src/libgdbr.c
Socket's connect didn't actually wait for a timeout and gdbr_connect left ports open which causes connect to fail after a couple of retries.
=> gdbr and socket fixes

doc/windows.md
=> Fix #15451 - Update Windows compilation documentation

libr/include/r_util/r_rbtree.h
Same behavior, just a bit more readable and less code duplication.
=> Minor Refactoring and Comments for RBTree

shlr/gdb/src/gdbclient/xml.c
Since r2 doesn't support set/get to large/vector registers (it will still work when printing gdb's registers with dr/drt or restoring the registers with reverse stepping), there's a possible issue that the user will get lots of prints of "r_reg_[get/set]_value: Bit size 128 not supported" when running various debug commands that use those functions. This fix simply moves those registers away from gpr to avoid those prints while still being able to view/restore the registers.
=> Add parsing of arm/arm64 register features and fix possible issue with unidentified >64bit registers

libr/debug/p/debug_windbg.c, shlr/windbg/iob_pipe.c, shlr/windbg/kd.c, shlr/windbg/transport.c, shlr/windbg/windbg.c, shlr/windbg/windbg.h, sys/rebuild.sh
=> Allow breaking for WinDbg ##debug

libr/core/agraph.c, libr/core/cmd.c, libr/core/cmd_log.c, libr/core/cmd_open.c, libr/core/core.c, libr/core/panels.c, libr/core/task.c, libr/core/visual.c, libr/core/vmenus.c, libr/include/r_core.h, libr/main/radare2.c
Basically just pulling everything task-related from RCore into a struct.
=> Partially decouple Tasks from RCore

libr/asm/arch/tms320/c55x_plus/decode_funcs.c
To reproduce: `r2 -e asm.arch=tms320 -e asm.cpu=c55x+ -c "wx 07cc; pd 1" -`
Test: https://github.com/radareorg/radare2-regressions/pull/2024
=> Fix a Double Free in tms320/c55x+

shlr/windbg/windbg.c, shlr/windbg/windbg.h
Especially the debugger callback signature.
=> windbg module build fix proposal ##windbg

.appveyor.yml
To get more updated libraries for the checks
=> Python and VS updates for Windows/clang

shlr/spp/p/spp.h, shlr/spp/r_api.c, shlr/spp/r_api.h
=> Fix spp warning in windows

.github/workflows/coverity-scan.yml
=> Coverity Scan GitHub Action

libr/core/panels.c
reproduce:
tT and q then r2 crashes so fixed it.
=> Fix a bug of the tab

libr/core/cmd_anal.c
Moved the information in the help messages
=> Removed deprecation messages

libr/anal/p/anal_6502.c, test/new/db/esil/6502
=> Fix N and V results in 6502 BIT ESIL (Fix #15547)

libr/anal/fcn.c, libr/anal/var.c, libr/core/canal.c, test/new/db/anal/arm, test/new/db/anal/x86_32, test/new/db/anal/x86_64, test/new/db/anal/xtensa, test/new/db/cmd/cmd_att, test/new/db/cmd/cmd_pd, test/new/db/cmd/cmd_pd2, test/new/db/cmd/types
Before:
After:
----
Also, is there a way to merge 2 variables? For example in the second image var_18h and var_18h_3 are the same
=> Fixes for argument/variables analysis

libr/core/cmd_debug.c, libr/core/cmd_open.c
`oo` - Not all of the data was rebased after reopening the original file and there was a warning message from set_baddr which isn't needed here. Switched to __rebase_everything instead of the old methods that were used.
`doc` - straightforward way to exit debug with everything taken care of
=> Fix 'oo' rebasing when leaving debug and add 'doc' to exit debug

test/new/r2r-v/r2r.v
For https://github.com/radareorg/radare2/pull/15616#discussion_r357161503.
=> r2r.v: Move threads into r2r

libr/core/core.c, libr/debug/debug.c, libr/include/r_debug.h, libr/include/r_util/r_event.h
=> Added an event to signal the end of the debug session ##debug

shlr/Makefile, shlr/meson.build
Fixes #15614 and updates tree-sitter to release 0.16.1
=> Compile tree-sitter with std=c99 flag

.travis.yml, libr/config/config.c, libr/core/cfile.c, libr/include/r_config.h, libr/main/rabin2.c
=> Pass R2_CONFIG file to ! commands

libr/debug/p/debug_native.c
Solving r_debug_handle_signals build warning issue.
=> Refactor signal handling for FreeBSD ##r_debug

libr/core/cmd_open.c
The FD was kept open and ptrace was prevented from opening it with the error "Could not execvp: Text file busy".
closes #15650
=> Fix native debug not working with files that were opened as RW

test/new/db/anal/m68k, test/new/db/cmd/cmd_afcl, test/new/db/cmd/cmd_i, test/new/db/cmd/cmd_project, test/new/db/esil/arm_64, test/new/db/tools/rafind2, test/new/db/tools/rarun2, test/new/db/tools/rasm2
=> Fix some FX Tests

libr/cons/dietline.c
reproduce:
V!
g
tab
select any candidate from widget
crash
this fixes it
=> fix some crash of widget

doc/debug-internals.md, libr/debug/Makefile, libr/debug/meson.build, libr/debug/p/debug_native.c, libr/debug/p/native.mk, libr/debug/p/native/bsd/bsd_debug.c, libr/debug/p/native/bsd/bsd_debug.h
Separate pure BSD calls into its separate compilation unit.
=> Debug, BSD systems refactoring ##r_debug

libr/config/config.c, libr/core/cconfig.c, libr/core/cmd_seek.c
For https://github.com/radareorg/radare2/pull/15500#issuecomment-558248872.
=> When setting non-bool config var, set false/true if r_str_is_false()/_is_true()

.travis.yml
Lets see if it works (though [ARM64 didn't](https://github.com/radareorg/radare2/pull/15393)).
For more information see [Build your open source projects on IBM Power and IBM Z CPU architecture](https://blog.travis-ci.com/2019-11-12-multi-cpu-architecture-ibm-power-ibm-z) blog post from Travis CI.
=> Try to test with PowerPC and SystemZ

libr/core/cmd_open.c, libr/include/r_util/r_str.h, libr/util/str.c
=> Fix debug and 'o' not being able to open paths with spaces #debug

libr/bin/filter.c
WIP since no tests yet.
Output of izz for the #15719 binary:
```
[0x0000020a]> izz
[Strings]
nth paddr      vaddr      len size section type    string
―――――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000100 0x00000100 160 161  header  ascii   SEGA GENESIS    (C)SEGA 1995.MARCART. BRADESCO                                  CART. BRADESCO                                  GM 00000001-00W`J               
6   0x00007974 0x00007974 24  25   text    ascii   AT&FV0B0+FCLASS=1;+FF=1\r
7   0x00007ad9 0x00007ad9 15  16   text    ascii   NMEMORIA CHEIA.
8   0x00007ae9 0x00007ae9 13  14   text    ascii   SEM PORTADORA
9   0x00007af7 0x00007af7 27  28   text    ascii   INICIANDO TESTE AGUARDE !!!
10  0x00007b13 0x00007b13 13  14   text    ascii   LINHA OCUPADA
11  0x00007b21 0x00007b21 …
```
=> WIP: Fix #15719: Reduce false negatives in 'U' strfilter

libr/core/panels.c
v -> tt -> q emits an infinite loop. this fixes it.
=> Fix infinite loop

libr/bin/pdb/pdb.c, test/new/db/formats/pdb
Fix all PDB tests
Closes https://github.com/radareorg/radare2/issues/15670
=> Fix wrong filtering of equals sign on PDB enum define

libr/bin/pdb/pdb_downloader.c, libr/debug/p/debug_native.c
=> Fix #15734 - Automatically download PDB file if pdb.autoload=1

libr/core/panels.c
It was buggy like each panel that had shown the decompilers output had not even properly scrolled and now it does with this.
=> All the available decompilers outputs will be properly shown

libr/core/cbin.c
https://github.com/radareorg/radare2/pull/15752
rewrite this pull request by pj api.
If it can be merge , I will try to rewrite other function with generate json str by the pj api
=> Fix gen json dwarf with pj api

libr/bp/bp.c, libr/bp/bp_io.c, libr/core/cconfig.c, libr/core/cmd_debug.c, libr/core/core.c, libr/include/r_bind.h, libr/include/r_bp.h, test/new/db/archos/linux-x64/dbg_bps, test/new/db/archos/linux-x64/dbg_seginfo
Based on the comments at #15750, history doesn't show up there anymore.
=> Refactor breakpoint validation

libr/io/p/io_w32dbg.c
This fixes situations that if a read contained even a byte inside invalid memory, the entire read would fail
=> Fix reading on invalid process memory ##windows

libr/bin/bfile.c, libr/core/cmd_info.c, test/new/db/cmd/cmd_i
https://github.com/radareorg/radare2/commit/5e78c0a55251412b48169387cb01e8306459e028#diff-5f23cf851d424110d88a88e94a5b38a4
=> Fix izzzj json

libr/bin/bfile.c, test/new/db/cmd/cmd_i
For https://github.com/radareorg/radare2/pull/15739/files#r362674966.
=> izzzj: Add izzj attributes

libr/bin/bfile.c, libr/core/cmd_info.c, test/new/db/cmd/cmd_i
For https://github.com/radareorg/radare2/pull/15739/files#r362675099.
=> izzzj: Use pj api

libr/debug/debug.c
Breakpoints were left in disassembly after a signal/break and there are probably other wait exit reasons that may lead to it that are less common.
=> Always unset bps after continue and step hard ##debug

libr/include/r_lib.h, libr/include/r_util/r_rbtree.h, libr/include/r_util/r_table.h
Here is a small PR that fixes function prototypes.
=> C prototypes fixed

libr/config/config.c, libr/core/cconfig.c, libr/core/vmenus.c, libr/include/r_config.h, test/new/db/cmd/cmd_env
This PR essentially reverts https://github.com/radareorg/radare2/pull/15681/files but it introduces a SETBPREF which has a default callback that can "boolify" r2 vars when necessary.
=> Fix config vars

libr/anal/fcn.c
=> Fix a null deref in fcn_recurse ##anal

libr/core/cmd_anal.c, test/new/db/cmd/types
Fixes https://github.com/radareorg/radare2/issues/15819.
=> Fix afs not working without rettype ##anal

libr/anal/jmptbl.c
=> Fix incorrect jump table size #13812

libr/core/cmd_magic.c, libr/core/cmd_print.c
=> Fix #15764: Implemented PMJ

libr/io/p/io_malloc.c
Fix is to update the offset once the read is done
=> Fix #15789: Increment offset for reads as well

libr/core/cmd_write.c
it's implemented here: https://github.com/radareorg/radare2/blob/master/libr/core/cmd_write.c#L1578
=> Add undocumented waF command to help

test/src/r2r.v
=> r2r.v: Use shorter syntax

libr/anal/anal.c, libr/anal/function.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_anal.h, test/unit/test_anal_block.c, test/unit/test_anal_block_invars.inl, test/unit/test_anal_function.c
=> Remove unused Function Tree and Fix Relocate

test/src/Makefile, test/src/r2r.v
Also, upgrade to the latest V.
=> r2r.v: Use new split_nth

libr/anal/arch/gb/meta_gb_cmt.c
I extended the analysis table for the Gameboy hardware to include information on sound and to display mnemonics that are typically used.
I have not used C in quite a while so I hope everything is OK. Feedback welcome! (I also just started with radare, so everything is still new and I have to learn to find my way around.)
The formatting seems to be inconsistent now, as I used the format hook as described, but the code was not formatted properly in the first place. Let me know how to go about that.
=> Improvements on Gameboy hardware information

libr/bin/format/le/le.c, libr/bin/p/bin_le.c
I fixed a couple of bugs with a LE malformed file.
I attach the testcase triggering those issues.
Please note that there might be other similar bugs around because this code trust the LE header, which might be invalid in fact
[rabin2_le_crash.zip](https://github.com/radareorg/radare2/files/4111930/rabin2_le_crash.zip)
=> fixed some out of bounds and null pointers in LE

.github/labeler.yml
=> Add r2r auto-label for tests

.github/PULL_REQUEST_TEMPLATE.md
This Pull Request is adding a [GitHub Pull Request Template](https://help.github.com/en/github/building-a-strong-community/about-issue-and-pull-request-templates#pull-request-templates) to the radare2 repository. Sometimes, pull-requests sent to the repository do not contain descriptions of the problems they are trying to solve, the solution they wrote or the features they implemented. By following this **mandatory** template, we not only encourage contributors to follow our [guidelines](../DEVELOPERS.md), add testsת and update the radare2 book -- but we **require** them to do so.
This template is easy to follow and all contributors should follow it before sending PRs.
**Test plan**
- Verify that everything explained …
=> Add GitHub template for new pull requests

libr/main/ragg2.c
- [ x] I've read the [guidelines for contributing](../DEVELOPERS.md) to this repository
- [ x] I made sure to follow the project's [coding style](../DEVELOPERS.md#code-style)
- [ x] I've added tests that prove my fix is effective or that my feature works (if possible)
- [ x] I've updated the documentation and the [radare2 book](../../radare2book) with the relevant information (if needed)
Using goto anchor where possible and fixing few potential leaks.
...
**Test plan**
...
...
=> Few code simplifications ##egg

test/new/db/cmd/cmd_pd
Adding regression tests to address issue 15870, grepping pd results multiple times. For example, `pd 20 ~ 40 ~ eax`
**Test plan**
This PR is solely for the purpose of creating new tests fr `pd`. I've included a test of how `pd x ~&a,b` _should_ work, and also how `pd x ~ a ~ b` _should not_ work, although the latter test may be insufficient? Please check. Test test, I ran `node node_modules/node-r2r/bin/r2r.js -i db/cmd/cmd_pd` from `/radare2/test/new/`
closes #15870
=> Tests for concatenated greps in `pd`

test/new/db/anal/java, test/new/db/formats/mach0/create, test/new/db/tools/r2, test/new/db/tools/rasm2
As per https://github.com/radareorg/radare2/pull/15923#discussion_r375790266, the new r2r.v will only accept `BROKEN=1` with no extra characters.
**Test plan**
Use `git grep "BROKEN=1."` to check whether there are any extra characters.
Issue in description.
=> Use only BROKEN=1 in tests

test/src/Makefile
Should fix this recent error in https://travis-ci.com/radareorg/radare2/jobs/285069815:
**Test plan**
Travis is green.
=> Fix unit tests by upgrading V

test/new/db/cmd/cmd_i, test/new/db/formats/elf/main, test/new/db/tools/rasm2
Continues the work in efbc2c7345eb6aa8816d65547eb01d1df9c126a0 for CMDS and EXPECT.
**Test plan**
Travis and AppVeyor are green. Can use `git grep "\(CMDS\|EXPECT\|EXPECT_ERR\)='.*'"` on bash to discover other tests that use single-line '..' for CMDS, EXPECT and EXPECT_ERR.
=> Convert some tests to use CMDS/EXPECT without enclosing quotes

libr/asm/p/asm_x86_nz.c
Add x86 neg instruction to x86.nz for 32 and 64 bit x86 architecture
...
**Test plan**
...
Closes #15633  
...
=> Add neg to x86.nz

libr/core/cmd_search.c
- /wj without input did not return '[]'
- added string to test case
=> Fix #15851 /wj without arg produce '\n'

test/src/r2r.v
**Test plan**
Run `./r2r -j 1 tools /r2` with a80802c60853e19864043e765c9207ae38497b8c and check that the number of successes is 7 and the total is 13. 
=> r2r.v: Fix Success: 0 when running cmd tests

test/new/db/asm/x86_32
Update test due to PR #15945 
...
**Test plan**
...
...
=> Update neg eax test

test/new/db/asm/x86_32
Tests for issue #15946 
...
**Test plan**
...
...
=> Add tests for assemble/disassemble not al

libr/core/agraph.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, test/new/db/cmd/cmd_aea
=> Fix aeab and add V (values) in aea outputs ##anal

libr/core/cmd_debug.c
=> cmd_debug add_bp sig fix ##debug

libr/bin/p/bin_xnu_kernelcache.c
- [ x] I've read the [guidelines for contributing](../DEVELOPERS.md) to this repository
- [ x] I made sure to follow the project's [coding style](../DEVELOPERS.md#code-style)
...
=> Memory leak fix for kernel cache module.

test/src/r2r.v
Seen with `./r2r -j 1 tools /r2` on 2fad5ae3c7ebb6794f30ec41a70654573b451b3c:
:scream: :scream: :scream:
This pr fixes the above and keeps everything consistent and sane (i.e. Total: 13). Yes I know it breaks CTRL&#8209;C but the above is more problematic and enotime right now to figure out how to make CTRL&#8209;C work.
**Test plan**
Do `./r2r -j 1 tools /r2` 5 times and make sure it's `Total: 13` every time. Do it again according to levels of patience and risk tolerance.
=> r2r.v: Fix wg race

test/new/db/cmd/types
Added test for type uint64_t
Closes #15590 
...
=> Add test for type uint64_t

libr/anal/block.c, libr/core/cmd_anal.c, libr/include/r_anal.h
=> Cleanup some RAnalBlock Members

test/src/r2r.v
r2r.v was discarding empty lines in test EXPECT blocks. This pr fixes that.
**Test plan**
All tests in cmd/cmd_pd and cmd/cmd_pf2 should work with r2r.v except the ONE_STREAM tests.
=> r2r.v: Slurp empty lines as well

libr/bin/format/le/le.c
- [-] I've updated the documentation and the [radare2 book](../../radare2book) with the relevant information (if needed)
...
**Test plan**
...
...
=> Fix UB, oobread, infinite loop and other bugs in the LE parser

libr/core/canal.c, libr/core/cbin.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/core/visual.c
=> Fix last covs

test/new/db/cmd/cmd_pd, test/new/db/cmd/cmd_pf2, test/new/db/cmd/feat_foreach, test/new/db/tools/r2, test/new/db/tools/r2r
As per https://github.com/radareorg/radare2/pull/15974#issuecomment-586337327. Also, added some tests in tools/r2r since r2r.v encountered some difficulties.
**Test plan**
=> Convert ONE_STREAM tests to EXPECT_ERR

test/unit/test_rbtree.c
Running tests with ASAN revelead a mem leak, this simply fixes it.
**Test plan**
Just run tests with ASAN, you should not see any mem leak.
=> Fix memory leak in test_rbtree

libr/core/cmd_search.c
'patters' -> 'patterns'
Fixing a very small/minor typo to make sure the user interface keeps being clean.
...
**Test plan**
...
...
=> Fixing typo in command documentation of /m

.appveyor.yml, libr/asm/meson.build, libr/bin/meson.build, libr/cons/cons.c, libr/core/cconfig.c, libr/egg/meson.build, libr/flag/meson.build, libr/include/r_cons.h, libr/search/meson.build, libr/util/meson.build, shlr/meson.build
This pr reverts #15535 since it is no longer necessary due to #15979.
**Test plan**
=> Revert #15535 (scr.onestream)

libr/anal/block.c, test/src/Makefile, test/src/r2r.v, test/unit/Makefile, test/unit/test_contrbtree.c
=> Handle return code in r2r.v and fix crashing unit test

binr/rax2/rax2.c, libr/main/radare2.c, libr/main/rax2.c
=> WIP: Noglobals r2

test/new/db/cmd/cmd_pd, test/new/db/tools/r2r, test/src/r2r.v
This pr is to prevent surprise when unbreaking a test with a BROKEN comment. 
**Test plan**
r2r.v is OK (instead of FX) with the included "BROKEN=0 with comment" test.
=> r2r.v, BROKEN=0: Check only first char

libr/anal/meta.c, libr/core/cmd_eval.c
…isasm
...
**Test plan**
...
...
=> Improve ecH (ecH-* dels them all, ecH- doesnt segfault, ecH list) ##disasm

libr/core/cbin.c, libr/main/rabin2.c
=> WIP: Kill all globals in rabin2.c

test/src/r2r.v
Before:
After:
**Test plan**
Eyeball the output of `./r2r -j 1 tools /r2`.
=> r2r.v: Add color to BR and FX of cmd tests

shlr/sdb/Makefile
- ht_pp.h includes ht_inc.h however ht_inc.h has not been soft linked to include directory
- related to radareorg/radare2-extras#220
**Test plan**
Verify ht_inc.h has been soft linked in include directory
...
=> sdb header file dependency for external plugin i.e. pyc

.travis.yml, sys/debian.sh, travis-extract-var.sh, travis-script
=> Build debian package in CI ##build

.appveyor.yml
=> Try to publish AppVeyour builds

.github/workflows/ccpp.yml, .github/workflows/coverity-scan.yml
=> Small fixes for GitHub Actions

test/src/Makefile
vpm seems to be down:
so this pr tries to fix:
by installing radare.r2 manually if so.
**Test plan**
Builds that use V (e.g. Travis) should be green.
=> Fix builds by installing radare.r2 manually

libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/debug/dreg.c, test/new/db/anal/arm, test/new/db/anal/x86_64
Fix ar= and dr=
- increase string width to accomodate register name larger than 4 char 
- fix flag type register value not printed and simplify the printing logic                                                                                      
- update r_debug_reg_list() to accept '=' char
- Add test for ar=
**Test plan**
- eyeball result of ar= or dr=
=> Fix show register value in column

libr/util/syscmd.c
- [ x] I've read the [guidelines for contributing](../DEVELOPERS.md) to this repository
- [x ] I made sure to follow the project's [coding style](../DEVELOPERS.md#code-style)
=> Memory leak fix proposal in syscmd_join ##util

.travis.yml, travis-script
=> Try to fix the macOS build

libr/bin/bfile.c, libr/bin/format/pe/pe.c, libr/bin/format/pe/pe.h, libr/bin/p/bin_pe.c, libr/bin/p/bin_pe.inc, libr/bin/p/bin_pe64.c, libr/core/cmd_info.c, libr/include/r_bin.h, libr/main/radare2.c, test/new/db/formats/pe/authentihash
* Add r_bin_file_compute_hashes
* Add r_bin_file_set_hashes
* Refactor `it` `itj` commands
* Introduce `hashes` method to RBinPlugin
I refactor the `r_bin_file` hashes functionality as suggested @ret2libc in my previous PR #15987
=> Refactor RBin file hashes

.appveyor.yml, test/src/Makefile
As a good Internet citizen, we should strive to eliminate unnecessary data transfers as much as possible. This pr is part of the effort, specifically focusing on `git clone`.
**Test plan**
=> Use git clone --depth 1 as much as possible in builds

libr/core/cmd_anal.c, test/new/db/cmd/cmd_aes
Observed from gdb that r_reg_set_value() for PC register is called twice during 'aes'
* remove another set PC register in initializeEsil()
* remove unnecessary call to initializeEsil() in r_core_esil_step()
**Test plan**
* Use gdb and observed that r_reg_set_value() for PC register is called once during 'aes'
* New esil test case should not fail
=> Code cleanup for r_core_esil_step()

.travis.yml
Regarding f6ea22f83b6716beae0773233532abdffe47e390, seen while in the radare2 root dir:
I don't think Travis handles syntax errors gracefully so I'm using `compgen` instead [as shown here](https://stackoverflow.com/questions/2937407/test-whether-a-glob-has-any-matches-in-bash/34195247#34195247). Afaik [Travis does use bash to run scripts](https://docs.travis-ci.com/user/job-lifecycle/#how-does-this-work-or-why-you-should-not-use-exit-in-build-steps).
**Test plan**
Travis should be green.
=> Unstick Travis by using compgen instead

test/new/db/anal/x86_64, test/new/db/cmd/cmd_i, test/new/db/cmd/cmd_search, test/new/db/formats/pe/create, test/new/db/formats/vsf/rambo2-rom, test/new/db/formats/vsf/rhps-norom, test/new/db/formats/vsf/rhps-rom, test/new/db/io/baddr, test/new/notworking_db/darwin-x64/me, test/new/notworking_db/darwin-x64/shell_uname
Continues the work in efbc2c7345eb6aa8816d65547eb01d1df9c126a0 by removing all `ARGS=`. Bash command used:
```bash
REGEX='ARGS=[[:blank:]]*$' bash -c 'git grep -l "$REGEX" | xargs -n 1 sed -i "/$REGEX/d"'
```
**Test plan**
=> Remove ARGS= from tests

libr/anal/meta.c, libr/anal/op.c, libr/anal/sign.c, libr/anal/type.c, libr/anal/var.c, libr/core/agraph.c, libr/core/anal_tp.c, libr/core/canal.c
=> Fix sdb API usage to avoid extra strdup()

libr/core/cmd_anal.c
=> Fix memleak in cmd_anal_aaft()

libr/core/anal_tp.c
=> Fix memleak in get_src_regname()

libr/cons/dietline.c, libr/cons/line.c, libr/core/core.c, libr/include/r_cons.h
=> Fix #15359 - Enable key.f# keys to be used in the shell ##cons

.github/PULL_REQUEST_TEMPLATE.md
There's a bug that turns the relative URL `../DEVELOPERS.md` into https://github.com/radareorg/radare2/DEVELOPERS.md (results in "Not Found" error) during and after pr submission. This pr fixes that by using absolute URLs.
**Test plan**
Go to any closed/merged PR that has the pull request template and try to click on the first 2 links.
=> Use absolute URLs in pull request template

test/README.md
Might be unclear that `new` is a directory name.
**Test plan**
Do A/B testing.
=> Highlight that 'new' is a directory name in test docs

test/new/db/anal/sh
=> Adds test for issue #15842

libr/core/cmd_anal.c, libr/core/yank.c, libr/debug/dreg.c, libr/include/r_io.h, libr/io/map.c
The function is just renamed to be reused and we have no tests for it, but it may fall into an infinite loop
...
**Test plan**
...
...
=> Fix #10696 - Kill r_io_map_add_next_available

.appveyor.yml
Apparently AppVeyor's troubles:
started with this commit: 98f057d77ca3fea1d23c9d95dbc8cbc0a2a3b36f (well it's probably the only commit that can possibly run interference). Checking https://raw.githubusercontent.com/probonopd/uploadtool/master/upload.sh reveals that it can use `continuous` as a tag name (didn't confirm it does so though) and thus this pr is the attempt at a fix for AppVeyor.
Tbh idk why the AppVeyor error message occurs. GitHub sees the `continuous` tag from both the AppVeyor and Travis builds and then it barfs?
**Test plan**
Unfortunately the only way to test this is to merge it into master and see whether it fixes AppVeyor.
=> Greenify AppVeyor on master by using different tag name

libr/magic/funcs.c
=> Fix a segfault in libmagic when error string > 4096

libr/main/rax2.c
=> Remove stray pancake activity ;)

libr/core/cmd_flag.c
So users are aware that `fd` has expansions as shown in https://github.com/radareorg/radare2/issues/16033#issuecomment-590062607.
**Test plan**
Consistency check with other commands that have expansions.
=> Add [?] to fd help entry

libr/core/cmd_debug.c
Use RTable in r_core_debug_rr. This applies to drr/arr and drrj/arrj
**Test plan**
Eyeball result between PR and master
=> Use RTable in r_core_debug_rr

libr/core/cmd_debug.c
r_core_debug_rr use RTable in PR #16066. This PR is for using RString instead of RBuffer and minor cleanup
**Test plan**
Eyeball result of PR and master
=> Enhance r_core_debug_rr 

test/new/package.json
=> Upgrade node-r2r to 0.3.1 to fix the <<EOF -i issue

libr/anal/flirt.c, libr/core/agraph.c, libr/core/anal_tp.c, libr/core/canal.c, libr/core/cbin.c, libr/core/cio.c, libr/core/cmd.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/vmenus.c, libr/debug/p/debug_native.c, libr/debug/p/native/w32.c, libr/include/r_core.h, libr/io/fd.c, libr/socket/socket.c, libr/util/file.c, libr/util/sys.c
=> Do not use the elvis operator for bool expressions

libr/core/cbin.c
=> Fix build after last commit

libr/bin/format/le/le.c
- [] I've added tests that prove my fix is effective or that my feature works (if possible)
- [] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
=> Memory leak fix proposal into the LE parser.

libr/cons/dietline.c, libr/cons/editor.c, libr/cons/input.c, libr/core/agraph.c, libr/core/cmd.c, libr/core/cmd_api.c, libr/core/cmd_help.c, libr/core/cmd_log.c, libr/core/core.c, libr/core/panels.c, libr/core/rtr.c, libr/core/rtr_shell.c, libr/core/visual.c, libr/core/vmenus.c, libr/core/vmenus_graph.c, libr/core/vmenus_zigns.c, libr/fs/shell.c, libr/io/p/io_self.c, libr/lang/lang.c, libr/main/rabin2.c, libr/main/ragg2.c, libr/socket/run.c
=> Fix fgets() usage

libr/config/hold.c
=> Fix memory leak in r_config_hold_num_free()

libr/core/cmd_anal.c
=> Fix some anal cmd handlers

libr/reg/profile.c, test/unit/test_reg.c
* Add test for r_reg_set_name() and r_reg_get_name()
* Add test for r_reg_set_profile_string()
* Add test for r_reg_setv() and r_reg_getv()
=> Create RReg test unit

libr/anal/flirt.c
The loader was reading the additional v10 header when `version >= 9`, which means it would read it for v9 as well, effectively shifting the rest of the parsing by 2 bytes. The rest are minor leak and style fixed.
**Test plan**
Run `zfd sdk0.12.14.sig` on this file: https://github.com/misson20000/nn-types/blob/master/sig/sdk0.12.14.sig
=> Fix FLIRT v9 loading and some related issues

.travis.yml
=> Fix Travis YAML warnings

test/Makefile, test/new/db/extras/cmd/yara
Add a test for commit [8da191d](https://github.com/radareorg/radare2-extras/commit/8da191d171c09ce2b461d7520966e0c804097a7e)
**Test plan**
yara in extras can be tested with: `make yara`
=> Add test for yara in extras

libr/bin/format/elf/elf.c
=> Fix #16096 - Fix C warnings in the ELF parser

test/new/package.json
=> Upgrade to node-r2r-0.4.0

libr/egg/egg_lang.c
=> Fix #16093 - support syscall redefinition

libr/debug/p/native/linux/linux_debug.h
=> Fix debugger build on Linux/s390x ##debug

libr/util/strbuf.c
=> Make r_strbuf_fini() safer

libr/core/cbin.c, libr/core/cmd.c, libr/core/cmd_debug.c
=> Fix last coverity issues

test/new/db/tools/rasm2
With 75f6f28bb0226b4bd2af9f8f20b2d82202903343, the `rasm2 bswap x64 #8095` test in tools/rasm2 should be officially unbroken.
**Test plan**
=> Unbreak ".." test

libr/anal/p/anal_arm_cs.c
=> Fix memleak in anal_mask() method of arm_cs plugin

libr/core/cmd_anal.c
=> Fix memory leak in core_anal_bytes()

libr/anal/meta.c, libr/core/cmd_eval.c
=> C urly ec hj command

test/new/db/cmd/shell
There are some duplicate tests in cmd/shell. This pr removes them.
**Test plan**
=> Remove dupe tests in cmd/shell

test/src/Makefile
...
**Test plan**
...
https://github.com/vlang/v/issues/3927
=> Update V for the testsuite

libr/reg/reg.c, test/unit/test_reg.c
Added test for r_reg_get_value() and r_reg_set_value() for gpr and flags register
=> Add test for r_reg_get_value() and r_reg_set_value()

libr/asm/p/asm_or1k.c, libr/core/cmd_open.c, libr/core/visual.c, libr/include/r_core.h, libr/include/r_util/r_table.h, libr/util/table.c, test/new/db/cmd/cmd_open
=> Fix UAF in om=

libr/bin/format/pe/pe.c
=> PE: print the unsupported hash type

libr/core/core.c, test/new/db/cmd/cmd_open
=> Fix double free in oc (Fix #16163)

.github/labeler.yml
Add .github/workflows auto-labeler infrastructure
=> Add .github/workflows auto-labeler infrastructure

test/unit/test_reg.c
Added more test for xmm registers
=> Add r_reg_get() and r_reg_get_pack() test for xmm registers

libr/core/cmd_anal.c
=> Implement aeb command to emulate a basic block

libr/reg/value.c
* Add warning if packbits larger than 64bit
* Fix out of bound checking to consider max packed_size
**Test plan**
Test added in PR #16171 should pass
=> Enhance r_reg_get_pack() and r_reg_set_pack()

test/new/package.json
There have been some fixes for node-r2r since 0.4.0.
**Test plan**
=> Upgrade to node-r2r 0.4.1

libr/bin/format/pe/pe.c, libr/hash/hash.c
So sha256 and probably other authentihashes work
Only tested with a sha256-hashed PE
**Test plan**
...
...
=> Strip minuses from the hash names

libr/core/cmd.c, libr/core/cmd_anal.c, libr/core/cmd_api.c, libr/core/cmd_macro.c, test/new/db/anal/x86_64, test/new/db/archos/darwin-x64/cmd_i, test/new/db/archos/linux-x64/cmd_i, test/new/db/archos/linux-x64/dbg_bps, test/new/db/cmd/cmd_i, test/new/db/cmd/cmd_macros, test/new/db/cmd/cmd_pd, test/new/db/cmd/cmd_pd2, test/new/db/cmd/cmd_pf, test/new/db/cmd/cmd_pf2, test/new/db/cmd/cmd_pf_elf, test/new/db/cmd/cmd_print, test/new/db/cmd/cmd_px, test/new/db/cmd/cmd_seek, test/new/db/cmd/feat_variables, test/new/db/cmd/write, test/new/db/esil/ppc_32, test/new/db/esil/x86_64, test/new/db/formats/mangling/bin
This is a change to ease the implementation of the new parser. Right now the way commands are parsed inside a macro and outside of it is very different. For example, `?e Hello,World)` outside of a macro would print the string `Hello,World)`. However, when you are inside the definition of a macro, the character `)` is the end of the macro body and `,` is the separator between commands. This difference is an inconsistency that changes how you write r2 commands based on what you are doing and it also complicates a lot the parser because arguments and commands inside the macro body should be parsed in a completely different way than what happens outside of a macro body.
For these reasons, I think it's better to just use `;` as …
=> Change macro syntax to use `;` instead of `,`

libr/core/canal.c
=> Fix one memleak

libr/anal/fcn.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/include/r_anal.h, libr/include/r_flag.h
Now we check flagspaces instead of comparing the string with "sym.imp.*", and that's an improvement.
**Test plan**
Current tests already cover this case.
...
=> Enhance the way imports are processed in r_anal_function_get_signature ##types

test/src/Makefile, test/src/r2r.v
=> Update to the latest V which may work on OpenBSD and NetBSD

libr/core/cmd_anal.c, libr/reg/reg.c, libr/reg/value.c, test/new/db/cmd/cmd_pd
=> Hide 128reg warnings and use rgb: instead of # in pal test

libr/crypto/p/crypto_serpent.c
The error check after `calloc` checked the wrong variable (copy paste most likely). Check the newly allocated variable instead of duplicating the previous check.
**Test plan**
...
...
=> Fix check for failed allocation

libr/core/vmenus.c
=> Visual bit editor now shows bits up and down ##visual

libr/bin/format/pe/pe.c
=> Fix PE endian and alignment issues spotted by ASAN ##bin

libr/anal/fcn.c, libr/anal/flirt.c, libr/anal/function.c, libr/anal/sign.c, libr/anal/xrefs.c, libr/core/agraph.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_seek.c, libr/core/cmd_zign.c, libr/core/core.c, libr/core/visual.c, libr/core/vmenus.c, libr/core/vmenus_graph.c, libr/include/r_anal.h
=> Initial r_anal_fcn_* purge

libr/anal/p/anal_ppc_cs.c, libr/bin/format/dmp/dmp64.c, libr/core/cmd_write.c, libr/debug/dreg.c, libr/debug/p/debug_native.c, libr/include/r_vector.h, libr/io/p/io_debug.c, shlr/grub/fs/hfsplus.c, shlr/grub/fs/jfs.c, shlr/grub/fs/xfs.c, shlr/grub/include/grub/charset.h, shlr/grub/include/grub/hfs.h, shlr/grub/include/grub/types.h, shlr/grub/partmap/sun.c, shlr/grub/partmap/sunpc.c, test/unit/test_anal_function.c, test/unit/test_buf.c
@abcSup Can you elaborate whether the `vtop()` function should be used anywhere? It is currently dead code.
=> Fix all Warnings for GCC 9

libr/include/r_util/r_ctypes.h, libr/util/ctype.c
This is important for r2ghidra
=> Add R_TYPE_TYPEDEF to RTypeKind

shlr/w32dbg_wrap/src/w32dbg_wrap.c
=> Fix small memory leak if allocation fails

libr/core/cmd_type.c
=> Use the proper API to find function in `tl` ##types

libr/anal/bb.c
=> Optimize r_anal_get_bbaddr() to make graph navigation faster ##graph

libr/core/linux_heap_glibc.c
- This PR detect glibc version during runtime to set `dbg.glibc.tcache` profile. The issue was identified due to test failure on Travis https://github.com/radareorg/radare2/pull/16247#issuecomment-600650852
- This partially address #16250 since I still retain the profile as this heap parsing is specific to glibc.
**Test plan**
- No idea how I could create a test that detect glibc version during runtime
=> Detect glibc version and set dbg.glibc.tcache accordingly

libr/core/cmd_type.c, libr/include/r_core.h, libr/util/ctype.c, test/new/db/cmd/types
=> Fix #16241 - Optimize 'tl', r_core_link_stroff and r_type_link_at (0.01s vs 3s) ##types

libr/asm/p/asm_arm_cs.c, libr/asm/p/asm_m68k_cs.c, libr/include/r_util/r_str.h, libr/util/str.c
=> Remove r_str_rmch and simplify r_str_replace_char* ##util

libr/main/radiff2.c, test/new/db/tools/radiff2
-qu options still print out strings, this fix makes it not print string out.
**Test plan**
...
closes #16190
...
=> Fix print string in radiff -qu

sys/build.sh, sys/install.sh
Fixes https://github.com/radareorg/radare2/issues/9240
=> sys/install.sh uses always /usr/local + rpath now ##build

.travis.yml, travis-script
=> Run sys/static in the Debian task ##build

libr/core/disasm.c, test/new/db/esil/x86_64
=> Do not newline after showing switch cases

test/src/r2r.v
This pr should fix
**Test plan**
All builds involving r2r.v are green.
=> Fix build by adding and removing underscores in r2r.v

libr/core/cmd_search.c
This pr should fix the following ([link](https://ci.appveyor.com/project/radareorg/radare2/builds/31616240/job/2j2t4qyi5f2sa01l#L11507)):
**Test plan**
=> Do fix for /F tests on Windows

libr/parse/p/parse_x86_pseudo.c
=> Code cleanup in parse.x86_pseudo

libr/core/visual.c
There is already an identical condition, with an identical body.
The condition on line 1600 and 1620 are identical (and the bodies of the `else if` is also identical), so remove one of the conditions since the other is dead code.
https://github.com/radareorg/radare2/blob/e3a7093a57a3551ce4d5d0864827ee86a1f29d3b/libr/core/visual.c#L1600-L1602
https://github.com/radareorg/radare2/blob/e3a7093a57a3551ce4d5d0864827ee86a1f29d3b/libr/core/visual.c#L1620-L1622
...
**Test plan**
...
...
=> Remove redundant condition

libr/bin/format/ne/ne.c
- [*] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [*] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
=> NE relocations mem leak fix proposal.

test/new/db/json/json1, test/new/db/json/json4
This pr unbreaks some json tests for wider coverage.
**Test plan**
Travis and AppVeyor are green, and stay green without non-deterministic wickedness.
=> Unbreak /wj and tfj json tests

libr/bin/p/bin_write_elf.inc
=> Fix #16265 - Segfault in rabin2 -O e/123 with ELF binaries

libr/core/cmd.c
`cmd_r2cmd()` was missing an if-else branch for when the user inputs `r2 <some binary>`
closes #16251
=> Fixed #16251

test/new/db/json/json4
This pr unbreaks the remaining broken json tests for wider coverage. ~~The size of 31 should not overwhelm any buffers.~~
**Test plan**
Travis and AppVeyor are green, and stay green without non-deterministic redness.
=> Unbreak pDJ and pdJ json tests

libr/core/cmd.c, libr/core/cmd_help.c, libr/core/cmd_print.c, test/new/db/cmd/cmd_search, test/src/Makefile
=> Use @{} instead of @() and fix this modifier ##core

libr/bin/p/bin_dex.c
=> Minor cleanup in the dex parser

libr/config/hold.c, libr/core/cmd.c, libr/core/r2-shell-parser-cmds.inc, shlr/Makefile, shlr/meson.build, test/new/db/anal/arm, test/new/db/anal/x86_64, test/new/db/cmd/cmd_afn, test/new/db/cmd/cmd_eval, test/new/db/cmd/cmd_macros, test/new/db/cmd/cmd_open, test/new/db/cmd/cmd_pd, test/new/db/cmd/cmd_ps, test/new/db/cmd/cmd_repeats, test/new/db/cmd/feat_arroba, test/new/db/cmd/feat_input, test/new/db/tools/radiff2
Improvements to new parser. It adds support for the new macro syntax (with `;`), it correctly prints `~?` and it makes sure "comments" are ignored when evaluating command substitutions (this is a bit fuzzy as a thing, but existing code relies on that).
=> Improve ts

libr/core/cmd_anal.c, test/new/db/anal/x86_32
=> Fix ao~bytes and add test ##anal

test/new/db/extras/cmd/yara
Previous test was not deterministic depending the version of yara.
**Test plan**
New test should be passing for all versions of yara.
=> Update yara test

libr/core/linux_heap_glibc.c, test/new/db/archos/linux-x64/dbg_dmh, test/new/db/cmd/cmd_dmh
- Added new test for dmh/dmha that does not depend on runtime
- Depends on radareorg/radare2-testbins#10
**Test plan**
- Result have been compared with gdb-gef
=> Test dmha/dmh for glibc x64

libr/core/agraph.c, libr/core/panels.c
It's a single line that I copied. Tested it's fixing the issue. Think it's enough
=> Fix cursor visibility after leaving visual graph

test/new/db/archos/linux-x64/dbg_dmh
Should fix
**Test plan**
Travis for Linux VMs are green.
=> Fix dmh/dmha test

libr/core/cbin.c
=> Use pj in ilj ##json

libr/core/core.c
...
**Test plan**
run r2 command `in 0`, `oc 0`, `in 0`
closes https://github.com/radareorg/radare2/issues/16303
...
=> fix c->table_query double free

test/new/db/tools/r2r, test/new/package.json
Node-r2r 0.5.0 adds a new feature (radareorg/node-r2r#26).
**Test plan**
Travis and AppVeyor are green with the new tests.
=> Upgrade to node-r2r 0.5.0 and add relevant tests

libr/anal/sign.c
...
**Test plan**
```
$ r2 /usr/bin/ls
$ aaa
$ s main
$ zaf
$ zj
```
#16237
=> Use pj in zj

.travis.yml
=> Build *.deb packages only for master branch

libr/anal/fcn.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_core.h
=> Fix #16308 - Early return in `af` to avoid re-analysing ##anal

.travis.yml
Add a condition to #16320 and hopefully it would work.
**Test plan**
The Debian build isn't done for this pr but is done for master.
...
=> Complete #16320

binr/r2r/r2r.c, libr/core/linux_heap_glibc.c, libr/include/r_core.h, libr/include/r_getopt.h, libr/include/r_main.h, libr/include/r_socket.h, libr/main/main.c, libr/main/r2agent.c, libr/main/rabin2.c, libr/main/radare2.c, libr/main/radiff2.c, libr/main/rafind2.c, libr/main/ragg2.c, libr/main/rahash2.c, libr/main/rarun2.c, libr/main/rasm2.c, libr/main/rax2.c, libr/main/version.c, libr/socket/run.c, libr/util/getopt.c
=> Always use r_getopt, do not depend on libc (not just on windows) ##core

libr/core/cmd_anal.c, test/new/db/cmd/cmd_afb
=> Add opaddr field in ab/abj output ##anal

libr/util/str.c
This function cost me 2 hours of my life.
=> Make r_str_split_duplist() thread-safe

binr/r2r/load.c, binr/r2r/r2r.c, binr/r2r/run.c, libr/bin/bfile.c, libr/core/cbin.c, libr/core/cmd_info.c, libr/core/cmd_print.c, libr/debug/dreg.c, libr/util/thread.c, test/new/db/anal/x86_64, test/new/db/cmd/cmd_afcl, test/new/db/cmd/cmd_agC, test/new/db/cmd/cmd_open, test/new/db/cmd/cmd_pdr, test/new/db/cmd/cmd_pf2, test/new/db/cmd/cmd_rop, test/new/db/io/many, test/new/db/io/zip
=> Even more R2R

libr/anal/meta.c
=> Fixed null deref in Cvs command parsing

libr/core/agraph.c, libr/core/core.c, libr/core/visual.c, libr/include/r_anal.h
Because #9421 is irrelevant, i removed the macro FCN_OLD.
**Test plan**
#9421 (Maybe)
=> remove FCN_OLD in analysis code

binr/r2r/load.c
=> r2r: handle CRLF in readline()

libr/anal/fcn.c, libr/core/cconfig.c, libr/core/cmd.c, libr/core/cmd_open.c, libr/include/r_anal.h, test/new/db/anal/x86_64
is_retpoline() only works with cachedg
...
**Test plan**
...
...
=> Implement anal.jmp.retpoline support ##anal

libr/core/cmd_type.c
Use proper help message tools instead of cmd0.
**Test plan**
...
...
=> Implement proper tp help menu ##types

libr/bin/format/objc/mach0_classes.c, libr/core/panels.c
=> Fix memory leak reported by coverity in mach0

test/new/db/cmd/cmd_open, test/new/db/io/many, test/new/db/tools/r2r
This pr unbreaks the `FILE=<<EOF` tests so that they are not forgotten and to test them with the new r2r.c.
**Test plan**
...
=> Uncomment/unbreak FILE=<<EOF tests

libr/core/visual.c, libr/core/vmenus.c, libr/include/r_core.h
Based on micro-task issue: #12604
So far very rough draft of Vb for anal classes, rn it looks only like this, I've added anal classes under Vba
```
[0x00001120]> ac ClassA;ac ClassB;ac ClassC;
[0x00001120]> acl
ClassA
ClassB
ClassC
[0x00001120]> Vba
[hjkl_/Cfm]> anal classes:
>> 00 ClassA                                                                                                                         
-  01 ClassB                                                                                                                         
-  02 ClassC  
```
=> [WIP] Add anal classes to "Vb"

libr/core/panels.c
Updated the panels copyright date, nothing special or interesting.
Did not fully read the style guide as I doubt it is required for a date change :)
Will read it for future commits
=> Updated Copyright to 2020

libr/main/radare2.c, libr/util/donut.c, libr/util/protobuf.c, libr/util/range.c, man/radare2.1
=> Add r2 -NN to not load plugins ##core

libr/core/cmd_type.c, test/new/db/cmd/types
See the issue
**Test plan**
See the test
#13677
=> Fix #13677 - Add txt command and make txf accept an argument ##types

libr/util/buf.c
While LGTM says it's a "unsigned compare to 0", I notice the return type is signed and can be -1 but r is unsigned.
**Test plan**
...
...
=> Fix a potential bug from LGTM

test/new/db/cmd/cmd_open, test/new/db/cmd/cmd_pd_bugs, test/new/db/cmd/cmd_search_hit, test/new/db/formats/mach0/fatmach0
The arm64 logs show some issues in the tests, so im fixing them here
https://api.travis-ci.com/v3/job/314549204/log.txt
**Test plan**
wait for travis
not yet, but at some point the whole suite will run in ppc and arm64 💪
=> Fix some tests for ARM64 and PPC ##tests

libr/core/cmd.c, libr/core/cmd_print.c, test/new/db/cmd/cmd_search
see the issue for more details
**Test plan**
i added tests. nothing to explain
its obvious by reading the commit message
=> Fix #16394 - Make pm [file] work again ##print

libr/core/cbin.c
=> Empty structs are now supported in r2, no need for this hack

.appveyor.yml
=> Run AppVeyor tests only for 2 jobs

.appveyor.yml
This tries to fix some errors we see often enough in AppVeyor (e.g. https://ci.appveyor.com/project/radareorg/radare2/builds/31977704). See https://help.appveyor.com/discussions/problems/1272-fatal-reference-is-not-a-tree-sha-on-git-checkout .
**Test plan**
Well.. we have to try it for a bit.
=> Try to fix spurious errors in AppVeyor

libr/bin/format/elf/elf.c, libr/bin/format/mach0/mach0.c
=> Fix #16266 - Fix two warnings

libr/bin/format/elf/elf.c
Pointless comparison of ut16 to 0.
**Test plan**
...
...
=> Fix a LGTM alert

.github/workflows/ci.yaml, .github/workflows/pr.yaml
Instead of using a full matrix, just add the builds we care about
=> Add GitHub actions for push to master as well

libr/include/r_util/r_graph.h, libr/include/r_util/r_name.h, libr/include/r_util/r_stack.h, libr/main/rasm2.c, libr/util/bitmap.c, libr/util/flist.c, libr/util/graph.c, libr/util/log.c, libr/util/mem.c, libr/util/name.c, libr/util/print.c, libr/util/rbtree.c, libr/util/seven.c, libr/util/signal.c, libr/util/spaces.c, libr/util/stack.c, libr/util/vector.c
Boolify some functions, remove some unneded spaces, etcetc
**Test plan**
wait for travis
no issues fixed, just cleanup
=> Some random cleanups in RUtil

test/new/db/anal/x86_32, test/new/db/cmd/cmd_open, test/new/db/cmd/cmd_pd, test/new/db/cmd/cmd_search, test/new/db/cmd/cmd_search_hit, test/new/db/cmd/feat_grep, test/new/db/esil/esil, test/new/notworking_db/darwin-x64/dbg_di, test/new/notworking_db/darwin-x64/dbg_oo, test/new/notworking_db/darwin-x64/me, test/new/notworking_db/darwin-x64/shell_uname
This pr formats some tests missed by #16417 and #16150.
The conversion commands have been changed to use `find` instead of `grep -z` just in case there exists some multi-byte char in the tests (that is not UTF-8) that has a 00 embedded in it.
For #16417:
```bash
find test/new -type f -execdir perl -0777 -i -pe 's/((?:EXPECT=<<EOF\s*?\n(?:(?!EOF).*\n)*?EOF\n)|(?:EXPECT=.*\n))((?!RUN).*\n)*?((?:CMDS=<<EOF\s*?\n(?:(?!EOF).*\n)*?EOF\n)|(?:CMDS=.*\n))/$3$1$2/g' '{}' \;
```
For #16150:
```bash
find test/new -type f -execdir perl -0777 -i -pe 's/CMDS=<<EOF\s*\n(.+?)\nEOF/CMDS=$1/g' '{}' \;
```
**Test plan**
...
=> Format some missed tests

README.md, test/Makefile, test/README.md
=> Remove r2r.js remnants

libr/core/libs.c
The dir.plugins can contain any path it is worth checking for each of the hardcoded paths first.
**Test plan**
...
issue #16281
=> Better fix for #16281

libr/anal/p/anal_ws.c
Yet another LGTM alert.
**Test plan**
...
...
=> Pass argument by pointer

.travis.yml
=> Remove some travis builds as there are already GH actions

.github/labeler.yml
=> Update GitHub autolabeler

sys/meson.py
=> Make msbuild quieter

libr/include/r_util/pj.h, libr/util/pj.c
This won't do much, but still better this way.
=> Remove one level of indirection from PJ

libr/bin/format/elf/elf.c, test/new/db/formats/elf/main
=> Endbr main

.github/workflows/ci.yaml, .github/workflows/newshell.yml
Split the workflow in a separate file
=> Run newshell tests when PR is newshell-*

libr/core/cmd_info.c
=> Add rust lang support to iD command

libr/bin/p/bin_dex.c
class_id and type_id are ut16.
**Test plan**
...
...
=> Fix 2 LGTM alerts

shlr/mpc/mpc.c
%li instead of %i
**Test plan**
...
...
=> Fix wrong format for long

libr/bin/format/elf/elf.c
=> Fix #16495 - Broken build

libr/anal/fcn.c, libr/anal/jmptbl.c, libr/include/r_anal.h
Most calls to try_walkthrough_jmptbl pass ut64 to jmptbl_size. It should be defined ut64. And a call that passes int should be fixed.
**Test plan**
...
...
=> Fix inconsistence of definition and call

libr/core/cmd_open.c, libr/io/p/io_ptrace.c, test/new/db/archos/linux-x64/dbg_oo
For a ptrace io connection, this pr ignores a process-not-found error when closing the connection (since it assumes that the process has been killed earlier somehow), and treats the error as if everything is normal.
**Test plan**
Closes #16283.
=> Fix #16283 - Continue as normal even if detachee is not found

test/Makefile, test/new/db/extras/cmd/swf
Previous test file does not exist and binary path was updated. "-L" is not a valid parameter for r2r.
=> Update swf test and path

libr/io/p/io_debug.c, libr/io/p/io_ptrace.c
see the issue
**Test plan**
we dont test debugger in bsd targets
fix #16432
=> Fix #16432 - openbsd fork+attach EBUSY issue ##debug

libr/cons/cons.c
see the issue
...
**Test plan**
see the issue
...
see the issue
...
=> Fix #15978 - segfault when using r2pipe webserver + local visual

libr/bin/format/pe/pe.c
=> Fix double free and uaf in pe parser

libr/bin/bfile.c, libr/bin/bin.c, libr/bin/format/mach0/mach0.c, libr/bin/p/bin_dex.c, libr/egg/p/egg_exec.c
=> WIP: Fix segfaults in fuzzed bins

.travis.yml, sys/emscripten.sh
=> Fix 16407 - Publish the emscripten builds

libr/bin/format/coff/coff_specs.h, libr/bin/p/bin_coff.c, test/new/db/formats/coff
1. Mark sections symbols
2. Mark absolute symbols
3. Set paddr = UT64_MAX for imports
**Test plan**
...
...
=> Improve COFF symbol info

libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/core.c
=> Fix asserts when trying to use a unexistant or wrong analysis plugin ##anal

libr/core/canal.c, test/new/db/anal/arm, test/new/db/io/baddr
...
**Test plan**
...
Closes #15260
=> If possible use symbol name instead of entry name for function name

libr/asm/asm.c, libr/bin/format/mach0/mach0.c, libr/bin/p/bin_dyldcache.c, libr/core/cmd_print.c, libr/core/linux_heap_glibc.c, libr/core/p/core_java.c, libr/core/visual.c, libr/include/r_io.h, libr/include/r_util/r_print.h, libr/socket/run.c, libr/util/print.c, shlr/mpc/mpc.c, sys/clang-format-diff.py
Start solving lgtm's warning. Some file don't respect coding style, so there is a big diff.
**Test plan**
Rerun lgtm
**Work on issues**
#16493
=> Fix various lgtm warning

binr/r2agent/r2agent.c, binr/radiff2/radiff2.c, binr/ragg2/ragg2.c, binr/rahash2/rahash2.c, binr/rarun2/rarun2.c
argv: char ** -> const char **
```
rahash2.c: In function ‘main’:
rahash2.c:6:30: warning: passing argument 2 of ‘r_main_rahash2’ from incompatible pointer type [-Wincompatible-pointer-types]
6 |  return r_main_rahash2(argc, argv);
|                              ^~~~
|                              |
|                              char **
In file included from rahash2.c:3:
/home/liumeo/github/radare2/libr/..//libr/include/r_main.h:26:49: note: expected ‘const char **’ but argument is of type ‘char **’
26 | R_API int r_main_rahash2(int argc, const char **argv);
|                                    ~~~~~~~~~~~~~^~~~
```
**Test plan**
...
...
=> Fix some GCC 9.3.0 warnings

libr/anal/p/anal_tricore.c
=> Fix tricore build on Windows

libr/bin/format/pe/pe.c, libr/util/pkcs7.c
=> Fix crash (null dereference) in PKCS7

libr/bin/format/elf/elf.c
* r2 bins/fuzzed/elf1
* Ref #16464
...
**Test plan**
...
...
=> Fix heap overflow in the relocs ELF parser ##bin

libr/bin/format/mach0/mach0.c
=> Fix infinite loop in macho commands parser

DEVELOPERS.md, libr/bin/format/le/le_specs.h, libr/util/protobuf.c
Thanks to @sanguinawer for finding this bug!
=> Fix R_PACKED() macro usage

libr/bin/format/elf/elf.c
=> Fix the last bins/fuzz crash in ELF parser

libr/core/canal.c, libr/include/r_io.h, libr/io/io.c
=> Infinite aav

libr/anal/vtable.c, libr/bin/format/elf/elf.c
=> Fix infinite vtables

libr/anal/p/anal_6502.c, libr/anal/p/anal_6502_cs.c, libr/anal/p/anal_8051.c, libr/anal/p/anal_amd29k.c, libr/anal/p/anal_arc.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_arm_gnu.c, libr/anal/p/anal_avr.c, libr/anal/p/anal_bf.c, libr/anal/p/anal_cris.c, libr/anal/p/anal_dalvik.c, libr/anal/p/anal_gb.c, libr/anal/p/anal_h8300.c, libr/anal/p/anal_hexagon.c, libr/anal/p/anal_i4004.c, libr/anal/p/anal_m680x_cs.c, libr/anal/p/anal_m68k_cs.c, libr/anal/p/anal_mcore.c, libr/anal/p/anal_mips_gnu.c, libr/anal/p/anal_null.c, libr/anal/p/anal_pic.c, libr/anal/p/anal_ppc_cs.c, libr/anal/p/anal_ppc_gnu.c, libr/anal/p/anal_sh.c, libr/anal/p/anal_sparc_cs.c, libr/anal/p/anal_sparc_gnu.c, libr/anal/p/anal_sysz.c, libr/anal/p/anal_v810.c, libr/anal/p/anal_z80.c, libr/include/r_anal.h
=> Proper setreg callback for anal plugins

test/README.md
=> Fix path in test/README

libr/core/blaze.c
Eliminate some re-calculations.
**Test plan**
...
...
=> Minor optimization for blaze.c

libr/util/protobuf.c
I've fixed the issue of using bitfields with old or weird compilers. This commit increase the compatibility of the code with compilers.
...
**Test plan**
Already there.
...
Closes #16564
...
=> Fix #16564 - no more bitfields.

libr/asm/p/asm_x86_nz.c, test/db/asm/x86_64, test/db/tools/rasm2
This pr adds some tests and removes some unused MOV C7 code from the x86_64 assembler.
**Test plan**
...
=> x86_64: Add some tests and remove some unused MOV C7 code

libr/asm/arch/8051/8051_ass.h, libr/asm/arch/dalvik/opcode.h, libr/asm/arch/snes/snes_op_table.h, libr/bin/format/dex/dex.h, libr/bin/format/mz/mz.h, libr/bin/format/p9/p9bin.h, libr/bin/format/zimg/zimg.h, libr/debug/p/native/linux/linux_coredump.h, libr/debug/p/native/linux/linux_debug.h, libr/debug/p/native/procfs.h
Skipped non-trival or never-modified header files.
**Test plan**
...
...
=> Add some missing header guards

configure, configure.acr
=> After release version bump to 4.5.0-git

libr/core/vmenus.c
The cmd was moved to file scope together with printCmds at 4924d1ff1eb30cc6c198049d865810a99d09afa6, causing some "local variable hides a global variable" warnings.
**Test plan**
...
...
=> Fix some LGTM alerts

libr/core/cmd.c, libr/core/cmd_print.c
Some memory leaks found by address sanitizers.
**Test plan**
...
...
=> Fix some memory leaks.

libr/asm/arch/hexagon/hexagon.h, libr/asm/arch/hexagon/hexagon_insn.h, libr/fs/types.h, libr/hash/sha1.h
=> Add some header guards

libr/core/blaze.c
* update base before increasing cur
* define cur and base together and close to usage
* constify op and move to block scope
**Test plan**
...
...
=> Test overflow in blaze.c

libr/include/r_types.h, test/unit/test_util.c
=> Initial generic reference counting ##util

libr/core/agraph.c, libr/core/cbin.c, libr/core/cfile.c, libr/core/cio.c, libr/core/cmd.c, libr/core/cmd_anal.c, libr/core/cmd_print.c, libr/core/cmd_search.c, libr/core/cmd_seek.c, libr/core/cmd_type.c, libr/core/cmd_write.c, libr/core/core.c, libr/core/disasm.c, libr/core/p/core_java.c, libr/core/panels.c, libr/core/visual.c, libr/core/visual_tabs.inc, libr/core/vmarks.c, libr/core/vmenus.c, libr/core/vmenus_graph.c, libr/core/vmenus_zigns.c, libr/core/yank.c, libr/main/radare2.c
Replaces all 0/1 passed as 3rd argument to r_core_seek with false/true.
=> r_core_seek accepts a boolean as 3rd argument

libr/core/cbin.c
A segmentation fault I met when using Cutter on rpi4.
**Test plan**
Buy an rpi4 and build r2.
```sh
rabin2 -Vj /bin/bunzip2
```
Get a segmentation fault.
Apply this change and rebuild.
No segmentation fault (at least here).
...
=> Fix a segfault of rabin2 on rpi4

test/db/tools/rabin2
for #16452, otherwise it's almost impossible to guess what is going on.
=> Make rabin2 prefix Test more explicit for debugging #16452

libr/core/cmd.c, libr/core/r2-shell-parser-cmds.inc, shlr/Makefile, shlr/meson.build, test/db/cmd/metadata, test/db/cmd/sugar
This should mostly fix all tests for newshell.
=> Fix cmd_substitution in grep_specifier ##newshell

libr/core/visual.c
Reduce duplicate code. Replace R_FREE that sets a dying variable null.
**Test plan**
...
...
=> Refactor printformat

libr/include/r_vector.h, test/unit/test_vector.c
The upper bound was more wrong and confusing than actually helpful, also used nowhere until now.
Lower bound is quite helpful for RVector and I will need it for variable accesses.
**Test plan**
run the unit tests
=> Remove r_pvector_upper_bound() and add r_vector_lower_bound()

libr/main/rax2.c
Local variable hides a parameter of the same name.
**Test plan**
...
...
=> Suppress 4 LGTM alerts

libr/anal/function.c, libr/anal/var.c, libr/core/anal_tp.c, libr/core/cmd_anal.c, libr/core/cmd_open.c, libr/core/cmd_type.c, libr/core/disasm.c, libr/core/vmenus.c, libr/include/r_anal.h, libr/include/r_parse.h, libr/parse/p/parse_mips_pseudo.c, test/unit/meson.build, test/unit/test_anal_var.c
=> Refactor Variable Accesses out of SDB

libr/bin/mangling/microsoft_demangle.c, libr/core/cbin.c, libr/core/visual.c
One for dead code after goto. The other seems a LGTM issue because it doesn't notice the case in braces. As a result, nothing to fix but only suppress.
**Test plan**
No changes in compiled microsoft_demangle.o.
...
=> Suppress 2 LGTM alerts

libr/core/cmd_info.c
Add a check before using the pointer.
**Test plan**
...
...
=> Fix null pointer dereference found by Infer

shlr/java/class.c
There's an alert at snprintf, meanwhile it should be += I think.
Change i to ut32 to fix another 2 alerts.
**Test plan**
...
...
=> Fix a bug and some alerts in class.c

libr/core/cmd.c
=> Fix warning when building without treesitter

libr/core/cmd_debug.c
=> Honor cfg.debug in arp/drp ##debug

shlr/grub/fs/reiserfs.c
=> Do not redefine assert in reiserfs.c

Makefile
=> Improved make pkgcfg

libr/anal/vtable.c
=> Check r_io_read_at return value in VTable ##anal

libr/asm/asm.c, libr/include/r_asm.h, libr/main/rasm2.c
=> Rasm clean

libr/anal/reflines.c
=> Improve the anal reflines to support true/false lines if needed ##disasm

libr/core/libs.c, libr/core/p/core_a2f.c, libr/include/r_types.h
=> Some random fixes here and there

DEVELOPERS.md, doc/ida.md, shlr/Makefile
=> Update some links

binr/r2r/load.c, binr/r2r/r2r.c, libr/core/cmd_debug.c, libr/core/cmd_write.c, libr/util/table.c
Mostly a bunch of calls to free().
I'm pretty new to heap memory management in C so I might've screwed something up, but I *think* this should fix all the coverity issues from issue #16613. Please review :)
**Test plan**
coverity
Closes: #16613
=> fix unfixed covs (resource leaks, null ptr deref)

libr/core/core.c, libr/include/r_core.h
=> Allow RCore.editor to create files if they doesnt exist ##core

libr/core/cconfig.c, libr/core/disasm.c
=> Asm.bytes.right

libr/fs/shell.c
Fix 2 warnings I imported #16626
**Test plan**
...
...
=> Suppress pointer type mismatch warning

libr/core/cmd.c, shlr/radare2-shell-parser/corpus/simple_commands.txt, shlr/radare2-shell-parser/src/scanner.c
This adds support for `>?` help_command in `cfg.newshell`.
**Test plan**
```
> e cfg.newshell=true
> >?
```
you should see the usual help for the redirect operator.
Relates to https://github.com/radareorg/radare2/issues/16688
=> Add support for >? help_command

libr/bin/bfile.c, libr/util/sys.c
=> Hide filehashsize warning under bin.verbose

libr/debug/p/debug_native.c, libr/debug/p/native/maps/windows_maps.c, libr/debug/p/native/windows/windows_debug.c, libr/io/p/io_debug.c, libr/io/p/io_w32dbg.c, shlr/w32dbg_wrap/include/w32dbg_wrap.h, shlr/w32dbg_wrap/src/w32dbg_wrap.c
* Fix #15937 - Fix debuggee hanging when attaching to it
* Fix 'dm' not working for attached processes
* Fix debuggee crashing when opening a file dialog
* Unify RIOW32Dbg and w32dbg_wrap_instance under W32DbgWInst
* Don't signal threads on select, only on continue
**Test plan**
1. Open notepad
2. `radare2 -c "o pidof://notepad; 2dc" -`
3. Make sure that process isn't hanged
Closes #15937
=> Fixes for windows debugger

libr/util/sandbox.c
...
**Test plan**
...
Closes #16531
=> Fix #16531 - Fix binary file opening permisson in sandbox ##windows

.appveyor.yml
The AppVeyor builds are broken with regard to Capstone and apparently the only thing that has changed is the Meson version.
**Test plan**
AppVeyor is green.
...
=> Fix AppVeyor build by fixing Meson version

libr/include/r_util/r_strbuf.h, libr/util/strbuf.c, test/unit/test_strbuf.c
=> Implement r_strbuf_setptr API ##util

libr/core/cmd.c, libr/core/windows_heap.c, libr/debug/p/native/windows/windows_debug.c, test/unit/test_list.c, test/unit/test_table.c
without this r2 doesnt build on some compilers
**Test plan**
see r2frida travis or try any random old bsd
nope
=> Avoid the use of 'for (int' constructions ##build

libr/bin/format/pe/pe.c, test/db/formats/mdmp, test/db/formats/pe/export_names
**Test plan**
Tests pass
Closes #16702
=> Fix #16702 - Fix PE exports ordinals

libr/include/r_util/r_file.h, libr/main/rabin2.c, libr/util/chmod.c, libr/util/file.c
=> Boolify some RUtil.file APIs

libr/bin/format/elf/elf.c, libr/bin/format/elf/elf.h, libr/bin/p/bin_elf.inc, libr/core/cmd.c, libr/core/cmd_api.c
=> Fix some coverities

libr/anal/pin.c, libr/include/r_io.h, libr/include/r_types.h, libr/io/p/io_default.c
This PR does nothing, just aesthetics for now
...
**Test plan**
...
...
=> Fix regression loading large files (>2GB) on 32bit systems ##io

libr/bin/format/pe/pe.c
...
**Test plan**
...
Closes #16739
=> Fix #16739 - Fix getting import entries from single directory

libr/bin/format/pe/pe.c
...
**Test plan**
...
Closes #16737
=> Fix #16737 - Fix overly agressive PE section fixing

libr/bin/bfile.c, test/db/cmd/cmd_i
~~Sorry forgot about utf8 when testing `bin.str.enc`.~~ This pr fixes `bin.str.enc=utf8` so that all-ASCII strings are designated `ascii`.
(04f11f38b11a71a77ce830d316164a6d439025fa does mean that `string_scan_range()` treats `bin.str.enc=ascii` and `bin.str.enc=utf8` the same. One day `ascii`, `latin1` and `utf8` should be treated differently.)
**Test plan**
...
=> bin.str.enc=utf8: Assume ASCII first 🇺🇸 + add some more tests

libr/cons/cons.c
This pr fixes some remaining issues of #16747 ... 6b9abba592589e570dbb53769bed35b079437623 fixes the click/mouse wheel issue reported in https://github.com/radareorg/radare2/pull/16747#issuecomment-622304023 and https://github.com/radareorg/radare2/pull/16747#issuecomment-622301387 ... 56e3cc138cca641680a219aec38c0b358488ae5f fixes an issue with alacritty since it declares xterm compatibility but r2 complains that `stty` is nowhere to be found.
6b9abba592589e570dbb53769bed35b079437623 is somewhat improper (a more proper fix would be to save and restore settings) but it doesn't require changing the innards of `r_cons_enable_mouse()` and it parallels the `I.mouse = 0;` statement of `r_cons_new()`.
**Test plan**
Tested with …
=> Fix some remaining issues of #16747

libr/anal/esil.c, libr/anal/esil_cfg.c, libr/include/r_anal.h
=> Use HtPP for esil ops

libr/bin/format/pe/pe.c, libr/include/r_endian.h
```
radare2 -qq /mnt/c/Windows/System32/ucrtbased.dll 
1.11s user 0.03s system 98% cpu 1.153 total
```
```
radare2 -qq /mnt/c/Windows/System32/ucrtbased.dll 
0.39s user 0.02s system 96% cpu 0.420 total
```
**Test plan**
Tests pass
=> PE: Getting exports speedup

libr/cons/dietline.c
=> Fix #11808 - Fix -0 mode on Windows

libr/bin/bin.c, libr/bin/format/pe/pe.c, libr/bin/format/pe/pe.h, libr/bin/p/bin_pe.inc, libr/core/cbin.c, libr/include/r_bin.h, test/db/cmd/cmd_i, test/db/formats/pe/pe64
This fixes having to use afc=ms to set the correct cc to 64bit PE files
**Test plan**
Tests pass
Maybe #14737
=> Add default_cc to RBinInfo

libr/cons/cons.c
This pr prevents flicker in Visual mode on mintty when holding down PgUp/PgDn. Also continues https://github.com/radareorg/radare2/pull/16769#issuecomment-624151310 and cleans up the code.
**Test plan**
Expand the mintty terminal window to full size, run `r2 --`, go to Visual mode (`V`) and hold down the PgDn key. The display should not flicker.
I use the mintty from git bash.
...
=> Prevent flicker in Visual mode on mintty when holding down PgUp/PgDn

libr/include/r_util/r_intervaltree.h, libr/util/intervaltree.c, test/unit/test_intervaltree.c
See the individual commit names for descriptions.
Do not squash when merging!
=> RIntervalTree Changes from Meta Refactoring

libr/anal/function.c, libr/anal/var.c
=> Fix memleaks in r_anal_function_set_var() and r_anal_function_free()

libr/anal/var.c, libr/core/anal_tp.c, libr/include/r_util/r_ctypes.h, libr/util/utype.c, test/db/anal/x86_64, test/db/cmd/types
=> Match args name/types from function definition ##anal

libr/anal/p/anal_arm_cs.c
=> Fix #16805 - Fix undefined behaviour in RAnalPlugin<arm.cs>.op()

Doxyfile
Significantly improve Doxygen build times by excluding third-party sources and removing antiquated `CREATE_SUBDIRS` option which additionally causes problems with tools that work on Doxygen's XML output.
**Test plan**
Execute Doxygen in the root: `doxygen`, and view the output in Firefox, for example: `firefox doc/doxygen/html/index.html`.
=> Exclude dependencies and tests from documentation

libr/anal/p/anal_pyc.c, libr/asm/arch/pyc/opcode.c, libr/asm/arch/pyc/opcode_arg_fmt.c, libr/asm/arch/pyc/pyc_dis.c, libr/bin/format/pyc/marshal.c, libr/bin/p/bin_pyc.c
=> Fix Pyc issues from infer and coverity

libr/include/r_util/r_big.h, libr/util/big.c
* Check returned pointer from `calloc`
**Test plan**
...
**Related issues**
https://github.com/radareorg/radare2/issues/16130#issuecomment-628579351
=> Fix bignum issues from facebook infer

test/db/tools/rasign2
Add more tests to rasign2
**Test plan**
These are the tests :)
Nothing yet, #9336 can be closed once I get FLIRT added to rasign2.
=> add more rasign2 tests

libr/asm/arch/pyc/opcode.c, libr/bin/format/pyc/marshal.c, libr/bin/p/bin_pyc.c
* Lack of type casting
**Test plan**
...
https://github.com/radareorg/radare2/issues/16837
=> Fix #16837 - RBin.pyc code warnings

libr/util/utype.c
Only reproducible with asan
**Test plan**
...
=> Fix 31bit shift UB on a signed 32bit variable

DEVELOPERS.md, libr/core/cconfig.c, libr/main/radare2.c, libr/util/assert.c, libr/util/lib.c, man/radare2.1
=> Be consistent and make all env vars start with `R2_`

libr/cons/dietline.c, libr/core/core.c, libr/util/str.c
str.c:2043:8: runtime error: addition of unsigned offset to 0x00010c7de67f overflowed to 0x00010c7de67e
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior str.c:2043:8 in
...
**Test plan**
...
...
=> Fix an oobread when pressing the backspace in the r2 shell

.appveyor.yml, shlr/meson.build
~~Meson 0.54.2 just came out a few days ago and I honestly am not looking forward to doing `'arch' / 'AArch64' / 'AArch64...'` etc. etc.~~
Apparently Meson's `static_library()` doesn't like Windows absolute paths (for some Windows configurations). This pr fixes that by using only relative paths.
**Test plan**
...
=> Unpin AppVeyor's Meson

libr/debug/trace.c, libr/include/r_debug.h
`radare2 -qq -c "aa;aac;aar;?t aaft" /bin/busybox`: 18.41s vs 18.15s 
...
**Test plan**
...
...
=> Use HtPP for accessing dbg trace entries

libr/core/cmd_write.c, test/db/cmd/cmd_wop
When using the function **r_io_write_at** the buffer is not updated properly and the output of the command ps was to correct. It was changed to a call to the **r_core_write_at** function.
**Test plan**
Tests have been updated with the **s:** prefix to specify that argument is a string.
=> Update woE and woD functions

shlr/gdb/src/gdbclient/xml.c
Currently, `shlr/gdb` only accepts bitsize that is a multiple of 8 and ignores `type` info when `group` info is available, which fails to recognize `type="code_ptr"` as the `PC` alias. These issues prevent `r2` from connecting to a OpenOCD gdbserver with the following xml target description:
```
<!DOCTYPE target SYSTEM "gdb-target.dtd">
<target version="1.0">
<feature name="org.gnu.gdb.arm.m-profile">
<reg name="r0" bitsize="32" regnum="0" save-restore="yes" type="int" group="general"/>
<reg name="r1" bitsize="32" regnum="1" save-restore="yes" type="int" group="general"/>
<reg name="r2" bitsize="32" regnum="2" save-restore="yes" type="int" group="general"/>
<reg name="r3" bitsize="32" regnum="3" save-restore="yes" …
```
=> Fix incorrect offset and type when parsing target description from OpenOCD gdbserver

libr/anal/p/anal_riscv.c
=> Fix RISC-V ESIL for jal and jalr

libr/bin/d/elf64, libr/bin/format/elf/elf.c, libr/util/format.c, test/db/cmd/cmd_pf_elf, test/db/cmd/print
This pr is the elf64 version of #16978 and completes the TODO there.
**Test plan**
...
=> elf64 pf.elf_header: w -> N2 for phnum, shnum, shstrndx, ehsize, phentsize and shentsize

libr/cons/dietline.c
Fixes line wrapping causing prompt to descend every keypress
=> Fix prompt bug on Windows

binr/r2r/r2r.c, libr/cons/cons.c, libr/include/r_cons.h, libr/util/sandbox.c, libr/util/sys.c
This pr fixes the following:
**Test plan**
On the Windows command line:
```
> chcp
> r2 -
> chcp
```
Before and after active code page should be the same.
...
=> r_cons: Save and restore the active code page on Windows

libr/core/cmd_anal.c, libr/core/cmd_mount.c, libr/core/cmd_open.c
=> Fix leaks detected by coverity.

libr/asm/arch/gb/gbasm.c, test/db/asm/gb
**<\!-- Filling this template is stupid -->**
...
**Test plan**
...
...
=> Fix #16995, #16994 and some other stuff ##asm

binr/r2r/r2r.c
This pr does the following:
Windows before (`git diff`):
Windows after:
----
Linux before (`diff`):
Linux after:
----
In other words, this pr removes the diff header (since there's no information there) and thus shortens the output, and also colorizes the `@@` line to differentiate it.
**Test plan**
Eyeball the difference?
...
=> r2r: Remove diff header and colorize @@ line

libr/anal/anal.c, libr/anal/class.c, libr/anal/sign.c, libr/config/config.c, libr/core/cmd.c, libr/core/cmd_anal.c, libr/core/cmd_meta.c, libr/core/cmd_type.c, libr/core/vmenus.c, libr/debug/dsignal.c, libr/flag/zones.c, libr/include/sdb/sdb.h, libr/io/p_cache.c, libr/syscall/syscall.c, shlr/sdb/src/diff.c, shlr/sdb/src/disk.c, shlr/sdb/src/main.c, shlr/sdb/src/query.c, shlr/sdb/src/sdb.c, shlr/sdb/src/sdb.h
now SdbForeachCallback returns bool so its consistent with the rest of functions and usages. WIll fix the uses inside r2 later
**Test plan**
just wait for travis to finish
none
=> Update SDB with boolified SdbForeachCallback

CODEOWNERS
=> Replace radare with trufae in CODEOWNERS

libr/core/panels.c
- [✔] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [✔] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [] I've added tests that prove my fix is effective or that my feature works (if possible)
- [] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
...
There was a glitch in "Show all decompilers" panel and now it's been fixed with this.
**Test plan**
...
press v and go to the panels mode then press " and pick Show all decompilers mode and watch  
...
=> Fix a minor glitch

libr/anal/block.c, test/unit/test_anal_block.c
=> Fix crash in r_anal_block_chop_noreturn

libr/anal/class.c, libr/anal/pin.c, libr/asm/arch/pyc/pyc_dis.c, libr/parse/code.c, shlr/java/class.c, shlr/tcc/tccgen.c
There was a "function not used" warning related to pyc_dis and then a bunch of warnings because of recent changes to Sdb callback.
**Test plan**
Check the log of CI to see if those warnings are still there or not.
=> Fix compiler warnings

libr/meson.build, meson.build
=> Fix R2_INCDIR on Windows

binr/r2r/r2r.c, libr/anal/sign.c, libr/anal/var.c, libr/asm/arch/wasm/wasm.c, libr/bin/format/elf/elf.c, libr/bin/format/mach0/mach0.c, libr/bin/format/pyc/marshal.c, libr/bin/pdb/pdb_downloader.c, libr/core/anal_tp.c, libr/main/radare2.c, libr/main/rasign2.c, libr/socket/socket_http.c
This PR fixes all the coverities reported for the last 4 weeks, mainly addressing memory leaks
**Test plan**
Wait for travis/review the changes
none in here, but 15 in coverity scan
=> Fix all the coverities detected last month

libr/bin/dwarf.c, libr/include/r_bin.h, libr/include/r_bin_dwarf.h
I am fixing parsing for DWARF 4 and 5 line information and going to add any extra changes introduced by the versions (especially 5, because it did a lot of changes).
I also did small refactorings, like moving the function prototypes out of the r_bin.h and moved it to the r_bin_dwarf.h etc.
=> DWARF 4 and 5 line parsing additions ##bin

libr/core/cmd_anal.c, libr/core/cmd_meta.c
=> Fix NULL deref and heap-buffer-overflow

binr/r2r/r2r.c, binr/rahash2/rahash2.c, libr/asm/p/asm_arm_as.c, libr/asm/p/asm_x86_as.c, libr/asm/p/asm_x86_nasm.c, libr/bin/bin.c, libr/bin/dbginfo.c, libr/bin/p/bin_dbginfo_dex.c, libr/bin/p/bin_dbginfo_elf.c, libr/bin/p/bin_dbginfo_elf64.c, libr/cons/Makefile, libr/cons/cons.c, libr/cons/cpipe.c, libr/cons/dietline.c, libr/cons/input.c, libr/cons/meson.build, libr/core/core.c, libr/debug/dsession.c, libr/debug/p/native/linux/linux_debug.c, libr/fs/shell.c, libr/include/r_bin.h, libr/include/r_cons.h, libr/io/p/io_default.c, libr/lang/p/pipe.c, libr/main/radare2.c, libr/main/radiff2.c, libr/main/rahash2.c
Current master is spitting out more than 10K warnings combining the standard ones from gcc with the ones from clang. 9K of them introduced this month. I'll start to submit PRs to fix them by types
**Test plan**
just build r2
no issues
=> Check for return values in about ~50 method calls

libr/anal/sign.c, libr/bin/format/pe/pe.c, libr/bin/p/bin_dex.c
This PR fixes a bunch of memory leaks and uninitialized variable usage in dex and pe
**Test plan**
Wait for the CI
None
=> Fix memory leaks in RBin reported by Coverity

libr/anal/var.c
\
...
**Test plan**
* Get the file.gb from #17062 and commit it into testbins /fuzzed
https://github.com/radareorg/radare2/issues/17062
=> Fix #17062 - segfault analyzing gameboy rom

test/db/cmd/feat_grep
=> Add broken test for multiple chained greps

libr/bin/format/mach0/mach0.c
The binary in the testbins repo makes r2 take forever to load and eventually run out of memory or crash. fixing this bug results in a null deref when deintializing the rbinobject. this pr fixes both bugs.
The 3rd commit fixes a null deref when loading machos without segments
**Test plan**
See https://github.com/radareorg/radare2-testbins/pull/28
One from clusterfuzz
=> Macho dos (dont squash this PR)

test/db/cmd/cmd_af
=> Add test for #4315 - Using af with anal.calls

libr/anal/p/anal_arm_cs.c, test/db/esil/arm_16, test/db/esil/arm_32
- [*] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [*] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [*] I've added tests that prove my fix is effective or that my feature works (if possible)
Fixed BLS instruction in ESIL
Fixed ADC and ADCS instruction in ESIL
Fixed LSL/LSLS and LSR/LSRS instruction in ESIL
Added tests for the above
Fixed tests for STRLS for ARM32
...
**Test plan**
Tests for the above instructions have been updated accordingly
...
Probably :)
...
=> Add ESIL flag update for LSL, LSR, ADC + correction on ADDS + test added

binr/r2r/r2r.c
Diff output is the same as #17066 except that a stray `{+`, `[-`, `+}` or `-]` in the test output does not break the diff.
Btw, an example of `--word-diff=porcelain` output is as follows:
**Test plan**
Mess around with tests and check that the diffchar output is the same as for #17066.
...
=> r2r: For diffchar, use --word-diff=porcelain instead

libr/anal/var.c
**Test plan**
Tests pass
Fixes #17093
=> Fix #17093 - Fix uaf in var accesses

libr/bin/bin.c, libr/core/cconfig.c, test/db/cmd/cmd_i
This pr resets strings whenever bin.str.enc changes so that they reflect the current binary string encoding.
**Test plan**
...
=> Reset strings whenever bin.str.enc changes

libr/main/radiff2.c
This fixes a simple leak in radiff2 running on windows.
**Test plan**
Current tests should be sufficient. 
None
=> fix leak in radiff2 on windows

libr/core/panels.c
- [✔ ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ ✔] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
The recursive menu did not work properly like the picture.
...
**Test plan**
You can easily repro this by just going to, for example, Settings menu -> Color settings.
Now the menu properly works like below with this PR.
...
...
=> Fix a bug in the menu

libr/core/visual.c
=> Add missing help message for V&

libr/core/cmd_debug.c, test/db/archos/linux-x64/dbg_dmi
* Add 'dmia'
* Accept more print modes in 'dmi'
* Don't call rabin2 to load info
=> Add command to load all info for lib ##debug

libr/bin/dwarf.c
Fixing potential null deref, uninitialized variable and missing break statement in dwarf.c
=> DWARF - coverity fixes

libr/bin/p/bin_pe64.c
not checking return code
**Test plan**
nope
none
=> Fix the last 2 covs on pe64

libr/bin/format/mach0/mach0.c, libr/core/linux_heap_jemalloc.c, libr/core/panels.c
This pr fixes the issues found by coverity some days ago
**Test plan**
wait for the ci
5 from coverity
=> Fix CID 1408682 1429931 1429932 1429933 1429934

libr/main/rabin2.c, libr/main/radare2.c, libr/main/radiff2.c, libr/main/rafind2.c, libr/main/ragg2.c, libr/main/rahash2.c, test/db/tools/r2, test/db/tools/rabin2, test/db/tools/radiff2, test/db/tools/rafind2, test/db/tools/ragg2, test/db/tools/rahash2
...
**Test plan**
...
Closes #17100
=> Bail early if path string is an empty string

test/db/esil/arm_16
Added test for this thumb issue that is now fixed
**Test plan**
theres a test and an issue describing it in detail
yep the #6741
=> Add test for #6741 - to verify thumb load instruction analysis

libr/io/p/io_self.c, libr/util/thread.c
update thread wrapper and implementing basic io_self plugin
- [x ] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ x] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
...
**Test plan**
...
...
=> haiku further porting ##libr

libr/util/file.c, libr/util/sandbox.c
* Use r_return
* Read procfiles once
...
**Test plan**
...
...
=> Improve code quality of file and sandbox ##util

libr/cons/hud.c
Draft of a possible solution. I will push an other implementation with a buffer.
**Test plan**
see #17122
close #17122
=> Fix buffer overflow #17122

libr/asm/p/asm_arm_as.c, libr/core/core.c, libr/main/radare2.c
```
```
**Test plan**
some in coverity
=> Fix all the covs (memleaks) reported the 15th of this month

README.md
Old badges show outdated (2 months ago) information. Update the link to refer to the latest commit.
**Test plan**
...
...
=> Update *bsd badges

.appveyor.yml, .builds/freebsd.yml, .builds/openbsd.yml, .github/workflows/ci.yaml, .github/workflows/pr.yaml, libr/lang/p/pipe.c, test/db/cmd/cmd_pipe, test/scripts/get-funcs.py
This pr fixes a `. <script>` (aka #!pipe) problem on Windows where the commands received were erroneously printed out after the script had executed. Also, adds an r2pipe.py test. 
**Test plan**
...
=> #!pipe: Fix stray command output on Windows and add r2pipe.py test

libr/bin/p/bin_dex.c, test/db/formats/dex
...
**Test plan**
radare2 -A test/bins/fuzzed/clusterfuzz-testcase-minimized-ia_fuzz-5643065568526336.dms
#17125
=> Fix #17125 - Invalid DEX section size calculation issue ##bin

libr/bin/p/bin_dex.c, libr/include/r_socket.h, libr/io/p/io_debug.c, libr/main/radare2.c, libr/main/ragg2.c, libr/socket/run.c, libr/util/file.c, libr/util/sandbox.c
* CIDs: 1293553 1408695 1430058 1430059 1430060
1430061 1430062 1430063 1430064 1430065 1430067
...
**Test plan**
...
...
=> Fix covs from 2020-06-29

.github/workflows/codeql-analysis.yml
GitHub integrated Semmle/CodeQL right into the interface, it might be handier to use it, see
https://help.github.com/en/github/finding-security-vulnerabilities-and-errors-in-your-code/managing-alerts-from-code-scanning
See also https://developer.github.com/v3/code-scanning/
=> Migrate to GitHub CodeQL

libr/bin/pdb/pdb.c, libr/include/r_pdb.h
This adds a function to read PDBs from a buffer, which is useful when using libr as a library.
(Also includes minor style fixes.)
**Test plan**
Tested by using it from `init_pdb_parser`.
=> Add function for reading PDB from buffer ##bin

libr/bin/p/bin_elf.inc, test/db/formats/elf/elf-relarm
Use the patch of @ret2libc(#9825) and add regression test.
**Test plan**
```
run the test suite
```
close #9825
=> Add reloc convert ppc

libr/core/visual.c
**Test plan**
```
$ r2 /bin/ls
o malloc://1024
V # see title
:s 0 # see title changed
```
this issue was spotted after the opn/opp/opr PR
=> Display file associated to the current in the visual title ##visual

libr/bin/p/bin_elf.inc
Use the boolean values set while iterating over the symbols to avoid checking twice for the same stuff
**Test plan**
Will make loading elfs with lots of symbols a bit faster (not much), but save some unnecessary loops
nope
=> Minor optimization in the language detection code in ELF ##bin

libr/include/r_cons.h, libr/io/p/io_self.c, libr/socket/run.c
enabled only on 64 bits unsupported on 32 bits with large files.
missing cfmakeraw function on this platform for socket et cons.
...
**Test plan**
=> Support self:// for Solaris ##io

libr/bin/format/elf/elf.c, libr/bin/format/elf/elf.h, test/db/cmd/cmd_i, test/db/tools/r2r, test/db/tools/rabin2
Add missing ELF dynamic tag entries to be parsed.
=> Add missing ELF DT entries ##bin

shlr/Makefile, shlr/meson.build
=> Update capstone git commits for v4 and next branches

libr/anal/anal.c, libr/include/r_anal.h
A lot of these members directly correspond to a config var, so this makes them easier to understand.
The removed ones should not break anything since they were all unused.
=> Document some RAnal members and remove some unused ones

binr/r2r/r2r.c
This pr replaces the colors used in r2r diffs with bright [diff-so-fancy colors](https://github.com/so-fancy/diff-so-fancy/blob/eef379ee43f860306310ba0843302c0077a4908b/lib/DiffHighlight.pm#L14-L21), because after replacement I find the diffs to be easier and more pleasant to read, especially if background is red.
Before-and-afters:
Before (Windows):
After (Windows):
Before (Linux):
After (Linux):
**Test plan**
Eyeball the difference?
...
=> Use diff-so-fancy colors in r2r diffs

libr/core/cmd_project.c, libr/core/project.c, libr/include/r_core.h
=> Rename r_core_project_save_rdb to r_core_project_save_script

.github/workflows/centos6.yml, libr/include/r_bin.h, libr/include/r_bin_dwarf.h
...
**Test plan**
...
Closes #17222
=> Centos forward decl rbin

libr/bin/format/dex/dex.c, libr/bin/format/elf/elf.c, libr/bin/format/mach0/mach0.c, libr/bin/format/pyc/marshal.c, libr/include/r_vector.h, libr/util/vector.c
=> Various fixes based on fuzz bins for rabin2

libr/bin/p/bin_dex.c
...
**Test plan**
...
Closes #17221
=> Fix #17221 - DoS when loading a corrupted DEX ##bin

README.md
The radare2book with a shorter domain name and with a fresh look was recently made available at [book.rada.re](https://book.rada.re) 
This Pull Request aims to replace the link to the radare2book with the new one.
**Test plan**
None
None
=> Update readme: Add link to the new radare2book

libr/core/cmd_anal.c
=> Fix #17108 - Add JSON output for variable xrefs

.github/workflows/debianold.yml
Install r2pipe.py in Debian Jessie nightly job since some tests require it.
See also https://github.com/radareorg/radare2/issues/17227
=> Install r2pipe.py for Debian Jessie CI job

libr/core/linux_heap_glibc.c, libr/debug/debug.c, libr/include/r_debug.h, libr/include/r_heap_glibc.h, test/db/archos/linux-x64/dbg_dmht
This change is needed to parse correctly the tcache struct (at the moment for `dmht`), discussed in https://github.com/radareorg/radare2/issues/17205
**Test plan**
The test are linked and explained in the issue
**Issues**
Close #17205
=> Fix tcache parsing

libr/bin/format/pe/pe.c, test/db/formats/pe/pe
=> Fix #17186 - Fix unaligned PE section paddr

libr/bin/format/elf/elf.c, libr/bin/p/bin_elf.c, libr/bin/p/bin_elf.inc, libr/core/cbin.c
A little cleanup in the ELF parser code
**Test plan**
wait for the ci
This code is stripped from the elf-relocs pr
=> Cleanup the ELF code a bit

libr/util/thread.c
=> solaris/illumos support thread name api as linux ##thread

test/db/cmd/cmd_search
my pr in testbins changed a magic file to make r2's magic and libmagic(gnu) behave in the same way for this specific test. 
**Test plan**
run that dtest
master is redd
=> Fix magic test in sync with the change in testbins

libr/bin/p/bin_coff.c
=> COFF: don't create a map if there are no imported symbols ##bin

doc/indent-example.c
example files should be correct. also i think doc/ needs A LOT of cleanup
**Test plan**
just read and chk, also i think we are missing a bunch of syntax things like multiline ternary operator expressions, enums, R_API, R_IPI, relative includes, etc.. feel free to suggest more changes or commit in here
I prefer to read a .c file than a long md explaining how should i write a C file, ther'es no issue for that, but i think this example must be extended a lot
=> Fix issues in the indent-example file :facepalm:

libr/anal/type_dwarf.c
Improved error handling in case base types and typedefs are missing any of the necessary attributes (name), right now they are being ignored.
=> FIX - DWARF type parsing - Improving error handling for missing attributes

libr/anal/fcn.c, libr/anal/p/anal_arm_cs.c, libr/anal/var.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_anal.h, libr/parse/p/parse_arm_pseudo.c, libr/parse/p/parse_mips_pseudo.c, libr/parse/p/parse_x86_pseudo.c, test/db/anal/arm, test/db/anal/vars, test/db/cmd/cmd_pd, test/db/cmd/types
* Fix r_core_anal_esil for functions
* Add test
**Test plan**
Tests pass
Fixes #10729
=> Detect stack vars accesses with misc regs with 'aaef' ##anal

CONTRIBUTING.md
This just adds a section to CONTRIBUTING.md teaching how to rebase. I'm also put in JeisonWi's link to a git guide.
=> Add rebasing instructions

binr/r2r/r2r.c
The motivations for this pr are twofold:
1. Turn the following char diff and its ilk into something more pleasant to look at:
1. Drop the dependency on `git diff` for diffcharing.
<ins>Update (diff after)</ins>
**Test plan**
Testing has been done on the following testfile:
```
NAME=1
FILE=-
CMDS=<<EOF
wz abcde
ps
EOF
EXPECT=<<EOF
abdde
EOF
RUN
NAME=2
FILE=-
CMDS=<<EOF
wz abcde
ps
EOF
EXPECT=<<EOF
aaaaa
EOF
RUN
NAME=3
FILE=-
CMDS=<<EOF
wz abcde
ps
EOF
EXPECT=<<EOF
eeeee
EOF
RUN
NAME=4
FILE=-
CMDS=<<EOF
wz abcde
ps
EOF
EXPECT=<<EOF
bcdea
EOF
RUN
NAME=5
FILE=-
CMDS=<<EOF
wz abc\ndef\ngh
ps
EOF
EXPECT=<<EOF
abd
gh
def
EOF
RUN
NAME=6
FILE=-
CMDS=<<EOF
wz abc\ndef\ngh
ps
EOF
EXPECT=<<EOF
abdjghidef
EOF
RUN
NAME=7
FILE=- …
```
=> r2r: Use Needleman-Wunsch to diffchar

test/db/anal/arm
Closes https://github.com/radareorg/radare2/issues/15588
=> Add test for arm analysis

configure, configure.acr
=> Bump version number to 4.6.0-git

libr/anal/fcn.c, test/db/anal/sparc
**Test plan**
Tests pass
Closes #17298
=> Fix #17298 - Analize bb with branch delayed instruction head ##anal

binr/r2r/r2r.c, libr/include/r_diff.h, libr/io/io_plugin.c, libr/util/udiff.c
As per https://github.com/radareorg/radare2/pull/17248#issuecomment-656574412.
**Test plan**
...
=> Move r2r diffchar code into r_util

libr/cons/cons.c, libr/cons/input.c
* Use shift key to allow for text selection
=> Fix selecting text on Windows ##cons

libr/core/disasm.c, test/db/formats/coff
=> Don't print reloc addend if it is 0

libr/bin/p/bin_elf.inc, libr/core/anal_objc.c
=> Fix null deref in aao

libr/bin/p/bin_coff.c
Symbol objects are stored in HtUP.
...
**Test plan**
...
...
=> Fix double free bug in COFF plugin ##bin

libr/bin/p/bin_coff.c, test/db/formats/coff
=> Fix REL32 relocs in COFF ##bin

libr/core/project.c
I have moved the remove project file, remove notesfile and rmove ROP parts of the r_core_project_delete function into inline functions and I have renamed the functions that use camelCase
=> Refactor projects code into separate snake_case functions ##projects

libr/core/cconfig.c, libr/core/cmd_print.c, test/db/cmd/cmd_print
[Example](https://github.com/radareorg/radare2/compare/master...kazarmy:prc-honor-io.unalloc.ch-scr.color=0?expand=1#diff-8d4ae0f0641439928790561fd63ece2b) in test.
**Test plan**
...
=> prc: Honor io.unalloc.ch when scr.color=0

libr/asm/Makefile, libr/bin/p/bin_dex.c, libr/core/Makefile, libr/core/anal_objc.c, libr/core/cbin.c, libr/core/cmd_flag.c, libr/core/fortune.c, libr/core/visual.c, libr/core/vmarks.c, libr/include/r_core.h, libr/include/r_types_base.h, libr/lang/p/spp.c, libr/lang/p/spp_r2.inc, libr/main/radare2.c, libr/util/buf.c
=> Fix latest COVs, few indents and remove some dead code here and there and remove few globals

binr/r2pm/r2pm
=> Fix missing grep glitch in r2pm

.github/workflows/release.yml
This should be included in the release-4.5.0 branch as well.
=> Install ldid2 as well, to sign packages for cydia ##build

libr/core/cmd_print.c, libr/util/format.c, test/db/cmd/cmd_pf
print unsigned 128 bit variables
**Test plan**
tests are there
someone aske for it
=> Implement pfQ to print/format 128bit unsigned values ##print

binr/blob/Makefile, sys/static.sh
=> Fix sys/static.sh after 2d160f250918609fa8f399a33f003cedaa85d888

test/db/cmd/cmd_interpret
The old syntax doesnt work. this test proves the new syntax doesnt breaks
**Test plan**
i just wrote a test
change introduced in 765f2b6bd4098b8e90e46a45c174a71099bc0d56
=> Add tests for “$foo=#!pipe“

binr/r2pm/r2pm
There is at least 1 r2pm package that clones itself into a \<package\>.git folder. This pr allows cleaning of those kind of packages.
**Test plan**
`r2pm -c r2ghidra-dec`
...
=> r2pm: Support cleaning of package cloned to <package>.git ##tools

libr/core/cmd_meta.c
=> Fix CCa help string order

CONTRIBUTING.md
=> Add commit message rules in the CONTRIBUTING file

libr/include/r_io.h, libr/include/r_util/r_itv.h, libr/io/io.c, libr/io/io_map.c, test/unit/test_io.c
* Always add new map to skyline
----
**Test plan**
Tests pass
Closes #14024
=> Fix O(n) in r_io_map_get() ##io

libr/asm/p/asm_arm_hacks.inc, test/db/asm/arm_64
Pretty similar and complementary to #17279
**Test plan**
...
Closes #17369
=> Fix #17369 - Support Branch Target Identification instruction ##asm

test/db/extras/cmd/yara
Yara uses flags to keep track of results: [263](https://github.com/radareorg/radare2-extras/pull/263). Test have been updated for that.
**Test plan**
Tests updated.
=> Update test for yara flags

libr/bin/format/pe/pe.c, test/db/formats/pe/hello_world
=> Fix main detection for debug PE bins ##bin

libr/anal/op.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_arm_hacks.inc, libr/core/cmd_search.c, libr/include/r_anal.h, test/db/anal/arm64
An op family that will collect all CPU security features under it.
**Test plan**
...
Closing #17378
=> Introduce R_ANAL_OP_FAMILY_SECURITY ##anal

libr/include/r_types.h, libr/util/sandbox.c
using priv api to remove few privileges to the current process.
=> Support sandbox on solaris/illumos ##port

libr/anal/rtti_itanium.c
=> Fix pre-c99 build

libr/anal/fcn.c, libr/anal/jmptbl.c
=> Fix heap-buffer-overflow in try_walkthrough_casetbl()

libr/main/rasign2.c, man/rasign2.1, test/db/tools/rasign2
Adds spaces to r asign2 via the `-s` flag.
```
rasign2 -s spacename -r /bin/ls |grep 'main g '
generated zignatures: 12
za spacename:main g cc=147 nbbs=226 edges=355 ebbs=8 bbsum=4859
```
**Test plan**
This is a very minor update and just uses `r_core` to do all the work. Please check that my help menu entry makes sense and does not need correction. Suggestions for something better are more then welcome.
...
=> Add zignature spaces to ##rasign2

libr/anal/fcn.c
=> Remove unused variable

libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_print.c, libr/core/disasm.c, libr/include/r_core.h, libr/io/p/io_w32.c, libr/parse/filter.c, libr/util/file.c, libr/util/sandbox.c, test/db/anal/mips, test/db/cmd/cmd_aea, test/db/cmd/cmd_pde
Emulates and disassembles instructions following code execution
=> Implement `pde` to disassemble following code execution ##disasm

.github/workflows/static.yml, libr/Makefile, libr/do-ar-sh, libr/magic/Makefile, shlr/Makefile, sys/cydia/deb_hand.mak, sys/debian/deb_hand.mak, sys/maemo/deb_hand.mak, sys/meson-sdk.sh, sys/static.sh
=> Fix #3929 - Enable LTO in sys/static.sh ##build

libr/anal/class.c, libr/anal/rtti_itanium.c, libr/core/cmd_anal.c
Recent coverity fixes, for some reason gmail dropped all scan defect emails into spam, so I haven't noticed them for some while.
=> coverity fixes ##anal

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/db/cmd/cmd_zignature
This PR adds the `zbr` command. This command finds the `n` closest matching functions to the provided signature. Example:
```
[0x00401b20]> aa
[0x00401b20]> zo ./libc.sdb
[0x00401b20]> zbr sym.__libc_malloc 10
0.94873  0.89800 B  0.99946 G   sym.malloc
0.65245  0.40600 B  0.89891 G   sym._mid_memalign
0.59470  0.38600 B  0.80341 G   sym._IO_flush_all_lockp
0.59200  0.28200 B  0.90201 G   sym._IO_file_underflow
0.57802  0.30400 B  0.85204 G   sym.__libc_realloc
0.57094  0.35200 B  0.78988 G   sym.__calloc
0.56785  0.34000 B  0.79570 G   sym._IO_un_link.part.0
0.56358  0.36200 B  0.76516 G   sym._IO_cleanup
0.56064  0.26000 B  0.86127 G …
```
=> Add best match reverse search ##signatures

libr/util/thread.c, sys/static.sh
Imported from the DragonFlyBSD ports repository: https://github.com/DragonFlyBSD/DeltaPorts/tree/master/ports/devel/radare2/dragonfly
See also https://github.com/radareorg/radare2/issues/10137
cc @devnexen
=> Some DragonFlyBSD build fixes ##port

binr/r2pm/r2pm
This pr reverts #17357, #17411 and #17442 as per  https://github.com/radareorg/radare2/pull/17357#issuecomment-666164765 and https://github.com/radareorg/radare2/pull/17442#issuecomment-673539719, and to simplify the r2pm cleaning code.
**Test plan**
`r2pm -ci r2dec` / `r2ghidra-dec` / `retdec-r2plugin` still works.
...
=> r2pm: Simplify cleaning code

binr/r2pm/r2pm
Before:
After:
Also, other r2pm dirs don't have a trailing slash.
**Test plan**
A double slash should not appear in the output of `r2pm -ci r2dec`.
...
=> r2pm: Remove trailing slash from R2PM_GITDIR

test/db/anal/mips
This file is compiled by the loongson compiler.
Make the file name clearer after renaming
...
**Test plan**
...
...
=> rename  test file ‘mips64r2-busybox’ to 'mips64r2-busybox-loongson'

meson.build, sys/create_r2.bat, sys/create_r2.sh, test/db/tools/r2
This pr recreates r2.bat on Windows under Meson that went missing, probably after #17424. Also enables the r2 tests, and creates a symlink to radare2 on non-Windows Meson.
**Test plan**
All builds should be green.
...
=> meson install: Create shortcut/symlink to radare2

test/db/cmd/cmd_rop, test/db/cmd/cmd_search
Important for running tests on non-x86 architectures.
**Test plan**
Everything is green.
=> Fix #17458 - fix wrongly written tests

test/db/tools/r2
As suggested by https://github.com/radareorg/radare2/pull/17463#issuecomment-675352870. Also eliminates repetition.
**Test plan**
...
=> Do r2 shortcut test

libr/anal/dwarf_process.c, test/db/cmd/dwarf
I've added tests for function information integration for different languages (Ada, Pascal)
=> Add DWARF tests for Ada and Freepascal ##anal

binr/r2r/load.c
Before
After
This pr removes the false positive warning.
**Test plan**
Remove line 118 from
https://github.com/radareorg/radare2/blob/489538e02b68c4e4a3ab64f280e563db97e6c49d/test/db/tools/r2#L111-L122 and run `r2r -i db/tools/r2`. Output should be like the "after" output above.
----
Remove line 177 from https://github.com/radareorg/radare2/blob/489538e02b68c4e4a3ab64f280e563db97e6c49d/test/db/tools/r2#L171-L177 and run `r2r -i db/tools/r2`. Output should still contain the warning in the "before" output above.
...
=> r2r: Set cmd test to NULL on load failure

libr/reg/reg.c
Add length check to r_reg_get_name_idx()
**Test plan**
...
https://github.com/radareorg/radare2/issues/17518
=> Add length check to r_reg_get_name_idx()

libr/core/vmenus.c
(N/A)
N/A
before, dN to change the function signature would not work if you are in cursor mode, this fixes it
...
**Test plan**
nope
...
nope
...
=> allow dN to work in cursor mode

libr/io/io.c, libr/io/io_private.h
=> Fix warning not addressed in cef191cde31cbef1da12562cda91e629eabdde93

test/unit/meson.build, test/unit/test_idpool.c
=> Add tests for idpool

libr/anal/dwarf_process.c
Fixes the following (https://travis-ci.com/github/radareorg/radare2/jobs/377445325#L2921-L2961):
**Test plan**
The test above in the asan build is fixed. All non-asan builds are green.
...
=> parse_dwarf_location: Guard against possible OOB read

libr/bin/format/pe/pe.c
**Test plan**
Tests pass
Fixes #9202
=> Fix #9202 - Make main detection for 32bit PE debug build more generic

libr/core/cconfig.c, libr/main/rabin2.c
=> Rename bin.demanglecmd to cmd.demangle ##config

libr/anal/dwarf_process.c, libr/bin/dwarf.c
Fixes of few leaks found by coverity or me with valgrind.
=> Fix resource leaks in dwarf.c and dwarf_process.c

libr/anal/var.c, libr/core/canal.c
=> Fix some cc assertions

.gitignore
`make symstall` creates this symlink
=> Add `libr/include/sdb` to .gitignore

libr/debug/p/debug_native.c, libr/debug/p/native/windows/windows_debug.c
* Also log the TEB address on thread start
=> Expose TEB address as a flag on Windows ##debug

libr/bin/dwarf.c
This pr fixes the following (https://travis-ci.com/github/radareorg/radare2/jobs/379363625#L2949):
**Test plan**
All asan tests that are XX only due to what's causing the above assertion are fixed. All non-asan builds are green.
...
=> Propagate parse_ext_opcode() error

test/unit/meson.build, test/unit/test_idpool.c, test/unit/test_idstorage.c
=> Add tests for r_id_storage

libr/io/p/io_windbg.c
=> Fix wrong calling convention in io_windbg.c

.github/workflows/ci.yml
=> Allow to test windows build with "*windows*" PRs ##build

libr/anal/var.c, test/db/cmd/cmd_afvd
=> Fix `afvd` using wrong var offsets

libr/anal/esil.c, libr/anal/p/anal_arm_cs.c, test/unit/test_idpool.c, test/unit/test_idstorage.c
Fixes some warnings like:
```
../libr/anal/esil.c: In function ‘esil_signed_mod’:                                                                                                                                           
../libr/anal/esil.c:1545:46: warning: pointer targets in passing argument 3 of ‘r_anal_esil_get_parm’ differ in signedness [-Wpointer-sign]                                                   
1545 |  if (src && r_anal_esil_get_parm (esil, src, &s)) {                                                                               
../libr/anal/p/anal_arm_cs.c: In function ‘shifted_reg64_append’:
../libr/anal/p/anal_arm_cs.c:862:6: warning: assignment discards ‘const’ qualifier from pointer target type …
```
=> Fix a bunch of warnings

libr/core/cmd_anal.c, test/db/cmd/cmd_eval
When [some files](https://github.com/junchao-loongson/test-bin/blob/master/cc1-nogp) have multiple entries and no loc._gp,calculation error in GP
In [this files](https://github.com/junchao-loongson/test-bin/blob/master/cc1-nogp) 
pd 10 @ 0x1213185e8
0x1213185e8      .qword 0x000000012011f0e0 ; entry.init0   ; [23] -rw- section size 288 named .init_array
0x1213185f0      .qword 0x000000012011b980 ; entry.init1
0x1213185f8      .qword 0x000000012011b9c8 ; entry.init2
0x121318600      .qword 0x000000012011ba10 ; entry.init3
0x121318608      .qword 0x000000012011bc00 ; entry.init4
0x121318610      .qword 0x000000012011bd10 ; entry.init5
0x121318618      .qword 0x000000012011bd68 ; entry.init6
0x121318620      .qword 0x000000012011bdb0 ; entry.init7 …
=> Fix GP calculation when there are multiple entries ##anal

libr/anal/fcn.c, libr/anal/var.c, libr/include/r_anal.h, test/db/anal/x86_32, test/db/anal/x86_64
Fixes new function not having any variables and old function keeping ghost vars
**Test plan**
Tests pass
=> Takeover variables when splitting functions ##anal

libr/anal/p/anal_mips_cs.c
Add ESIL support for DSRA instruction in anal_mips_cs.c
Fix the translation error of MIPS SRA instruction to ESIL 
**Test plan**
I will add the test
...
=> Fix the translation error of MIPS SRA instruction to ESIL ##anal

libr/cons/dietline.c
=> Fix #17492 - EOF when alt+e is pressed on Linux systems ##cons

libr/util/sandbox.c, test/db/cmd/feat_redirect
=> Fix #17581 - Fix append to file on Windows

libr/cons/input.c, libr/include/r_socket.h, libr/socket/socket.c, libr/socket/socket_http.c, libr/socket/socket_http_server.c, libr/socket/socket_rap_client.c, test/db/io/http
=> Fix #17506 - r2 http://example.org works again ##io

libr/debug/p/debug_windbg.c
=> Fix step over for windbg plugin

libr/core/cmd_anal.c, test/db/cmd/cmd_ao
=> Implement aof comment to filter esil expression using the DFG API ##esil

libr/anal/dwarf_process.c, libr/anal/type.c, libr/anal/type_pdb.c, libr/include/r_anal.h, test/unit/test_anal_types.c
Initializing the kind-specific stuff fits better directly into the new function, especially the `r_vector_new` calls.
=> Minor RAnalBaseType new/free refactoring

doc/fortunes.fun
=> DOOM all the things!

libr/anal/p/anal_mips_cs.c, test/db/esil/mips_32
- Increase the overflow detection of the add、addi、dadd instruction
- Use the new syntax to implement symbolic expansion  
**test**
- I will add a test for overflow detection
...
=> Improve mips.cs esil ##anal

libr/core/project.c
=> Fix all the projects tests failing with asserts

libr/asm/p/asm_x86_as.c
=> x86.as is only suposed to work on x86, add env var for custom use ##asm

libr/socket/r2pipe.c
=> Avoid close(-1) in r2pipe

libr/bin/bin.c
...
**Test plan**
```
$ r2 -
> iA
Segmentation fault
```
it should not segfault
...
=> Fix crash when running iA while head_flag is not defined

libr/cons/cons.c, libr/core/cmd_help.c
DO NOT SQUASH
there's a w32api for that
**Test plan**
requires humans
none registered, this api was not used anywhere
=> Implement RCons.setTitle() for Windows and add ?et command ##cons

libr/anal/dwarf_process.c, libr/include/r_util/r_strbuf.h, libr/util/strbuf.c, test/unit/test_strbuf.c
Filling this template is exponsive.
For nice one-line init+setf
**Test plan**
run the test
=> Add r_strbuf_initf() ##util

libr/cons/cons.c, libr/core/cmd_print.c, libr/core/disasm.c, libr/include/r_cons.h, test/db/cmd/cmd_pdj
**Test plan**
whats in the screenshot
none, but been a complain for about 2 years ago from different people, it was easier to fix than fill the issue template
=> Parse ansi->html properly in pdJ ##disasm

libr/anal/cc.c, libr/anal/dwarf_process.c, libr/core/cmd_anal.c, libr/include/r_anal.h, libr/include/r_reg.h, libr/reg/profile.c, libr/reg/reg.c, test/db/cmd/cmd_ara
**Known Bugs**
* No way to set default calling convention
* Add (`e anal.cc=reg`) .. overrides the info from types (func.main.cc=amd64)
* Not yet used as fallback. will do a separate pr for this
* Invalid profiles break the regstate and result in runtime assert. Fix will be submited in a separate PR
* using a space before the ( results in no error, but not registers (`tcc eax failure (eax)`). Will submit a fix in another PR
...
**Test plan**
...
...
=> Implement arcc command and get_cc_from_regprofile ##types

libr/core/cmd_type.c, libr/util/file.c, test/db/cmd/shell
=> Implement touch command ##shell

libr/include/r_socket.h, libr/socket/socket.c
See issue.
**Test plan**
See issue.
Closes  #17638
=> Fix #17638 - set protocol to TCP in HTTP server ##remote

libr/anal/function.c, libr/anal/labels.c, libr/core/cmd_flag.c, libr/core/core.c, libr/core/disasm.c, libr/include/r_anal.h, libr/parse/filter.c, test/db/cmd/cmd_flags, test/unit/test_anal_function.c
Filling this template is cool and good.
What the title says. I wanted to refactor this before implementing labels into r2db.
**Test plan**
run the tests
=> Refactor Labels out of SDB ##anal

libr/anal/cc.c, libr/core/cmd_type.c, libr/include/r_anal.h, test/db/cmd/cmd_tcc
=> Fix spacing bugs when parsing the calling convention signatures

libr/core/cmd_anal.c
Fix issues like https://github.com/radareorg/radare2/runs/1122620100?check_suite_focus=true#step:13:1961 .
This hopefully makes asan build green again.
=> Correctly check whether esil_str is available

libr/core/disasm.c
e asm.hint.pos=0 or -1
**Before**
**After**
**Test plan**
...
...
=> Fix glitch when asm.hint.pos < 1 in visual ARM ##disasm

libr/anal/anal.c, libr/core/cmd_anal.c, libr/include/r_anal.h
Let's see whether CI will be green but this doesn't seem to be used anywhere anymore.
=> Kill RAnal.sdb_fcnsign

libr/core/cmd_type.c, test/db/cmd/cmd_tcc
=> Implement tcc-* commmand to unload all calling conventions ##anal

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/unit/meson.build, test/unit/test_sign.c
I need a proper getter in the api for this to write tests for r2db. Also the name `r_sign_anal_additem` seemed kind of random to me.
**Test plan**
run the tests
=> Rename r_sign_anal_additem to r_sign_add_item and add r_sign_get_item ##signatures

.github/workflows/ci.yml, test/db/archos/linux-x64/http, test/scripts/test-webserver.sh
This pr tests the r2 webserver (`=h`) on Linux.
**Test plan**
...
=> Test =h on Linux

libr/bin/mangling/microsoft_demangle.c, test/db/formats/mangling/mangling
* Demangle __clrcall calling convention
* Transform a giant macro to a function for sanity sake
* Add tests
**Test plan**
Tests pass
=> Support demangling MSVC managed pointer types ##bin

libr/anal/anal.c, libr/core/cmd_anal.c, libr/include/r_anal.h, test/db/cmd/cmd_aii
Again, needed for testing r2db.
**Test plan**
Run the tests
=> Add Global Import API

libr/bin/pdb/pdb.c, libr/core/cmd_print.c, libr/include/r_util/r_time.h, libr/include/sdb, libr/util/format.c, libr/util/time.c
1- fix possible overflow
2- fix possible overflow
3- fix the usage of asctime
**Test plan**
Run the test suite and watch lgtm result
Work #16493
=> Fix 3 lgtm warnings

libr/core/agraph.c
=> Fix scrolling with L in mini graph mode ##visual

libr/core/cmd_flag.c, libr/include/r_util/r_table.h, libr/util/sys.c, libr/util/table.c, test/db/cmd/tables
=> Support head, tail, page, bool, added tests for RTable ##util

libr/include/r_parse.h, libr/parse/p/parse_v850_pseudo.c, libr/parse/p/v850_pseudo.mk, plugins.def.cfg, test/db/anal/v850
=> Implement the v850.pseudo RParser plugin ##disasm

test/scripts/test-webserver.sh
=> Fix race condition in http server test

libr/parse/meson.build
parse_v850_pseudo was introduced in https://github.com/radareorg/radare2/pull/17687/ but it was not added to meson build.
**Test plan**
It should remove a XX test in meson build.
...
=> Add parse_v850_pseudo to meson build

libr/util/sys.c, test/db/anal/v850, test/db/archos/linux-x64/http
This test is not working well it seems. Let's disable it until a proper fix.
=> Mark http test as broken until properly fixed

test/db/archos/darwin-x64/http
See https://github.com/radareorg/radare2/runs/1165639439#step:13:685
=> Mark =h test on darwin as broken, it fails for now

test/db/archos/darwin-x64/http, test/db/archos/linux-x64/http, test/scripts/test-webserver.sh
The pr tries to add more certainty to the `=h` tests.
**Test plan**
The `=h` tests pass and stay passed.
...
=> Unbreak =h tests

libr/anal/anal.c, libr/include/r_anal.h
Filling this template is yrotadnam
see title.
**Test plan**
call `r_anal_purge()`.
=> Purge Pins on r_anal_purge ##anal

libr/core/cmd_info.c, libr/include/r_io.h, libr/io/p/io_default.c, test/db/archos/darwin-x64/cmd_i, test/db/archos/linux-x64/cmd_i, test/db/cmd/cmd_i, test/db/cmd/cmd_open, test/db/cmd/feat_grep, test/db/formats/elf/elf-riscv64, test/db/formats/smd
Filling this template is cool and good.
This was originally introduced in https://github.com/radareorg/radare2/commit/ae367b65be but currently has no place where it's written so it's entirely useless.
=> Kill RIODesc.obsz ##io

Makefile, meson.build
This partially reverts commit 2a0d8fbe5926a50588c81833e73d403b04cff139
Fixes #17672
=> Revert "r2sdb: Install executable"

shlr/lz4/README.md, shlr/lz4/lz4.c, shlr/lz4/lz4.h
Update `shlr/lz4` to the latest 1.9.3 version as part of the efforts to compile with TinyCC: https://github.com/radareorg/radare2/pull/17295
https://github.com/lz4/lz4/commit/293713a4fa085d73f396200d2387631b045c118e
**Test plan**
Everything green.
=> Update shlr/lz4 to 1.9.3 293713a4fa085d73f396200d2387631b045c118e

binr/r2r/run.c
This should fix a nasty issue with r2r, where tests never terminated.
That was caused by the jq process waiting indefinitely for input from
fd0, because the other end of the pipe was never closed.
Indeed r2r_subprocess_start forks and closes known unnecessary opened fd
in the child process, however it does not consider also all the other
file descriptors that could have been created by other threads
simultaneously. As fd are per-process and not per-thread, file
descriptors created by other threads while doing e.g. pipe to spawn a
separate jq process will clutter other threads (and following jq
processes) as well. If two jq processes happen to keep a fd to the other
end of the pipe for the fd0 of the other jq process, none of them
terminates, thus they never close those spurious file …
=>       Prevent multiple threads from opening new files at the same time ##r2r

libr/main/rafind2.c
Escaping the file path was wrong on windows
For https://github.com/radareorg/radare2/pull/17723
**Test plan**
Tests pass
=> Fix rafind2 -m/-i/-E on Windows

libr/anal/p/anal_6502.c, libr/anal/p/anal_6502_cs.c, libr/anal/p/anal_8051.c, libr/anal/p/anal_h8300.c, libr/anal/p/anal_hexagon.c, libr/anal/p/anal_pic.c, libr/anal/p/anal_pyc.c, libr/anal/p/anal_riscv.c, libr/anal/p/anal_riscv_cs.c, libr/anal/p/anal_sparc_gnu.c, libr/anal/p/anal_tricore.c, libr/anal/p/anal_v810.c, libr/anal/p/anal_v850.c, libr/anal/p/anal_wasm.c, libr/debug/p/debug_bf.c, libr/debug/p/debug_esil.c, test/db/anal/tricore
=> Add remaining =A0 in regprofiles for calling convention ##anal

libr/asm/p/asm_bf.c
The assembler was using a buffer stored on the stack to store data of the assembled instruction. Because of that, any instruction bigger than the size of that buffer (32 bytes) would corrupt the stack.
**Test plan**
1. Open any brainfuck file in write mode
2. Use `wa out [ptr], 1000` or any other command that will assemble and write an instruction bigger than ~50 bytes 
Closes #17746
=> Fix buffer overflow in brainfuck assembler

libr/debug/p/debug_native.c
=> Fix eprinf -> eprintf

README.md
Its just right there in the readme, and its a not what we want people to read
**Test plan**
Make a PCR
None
=> r2learn is not really maintained or recommended for learning

libr/core/disasm.c
I've added the raw bytes along the type (invalid), size and offset fields to pdj.
**Test plan**
Manually generate a binary with an invalid opcode
closes #10389
=> Show raw bytes in pdj when invalid

libr/libs.mk
tcc and some private CIs are broken because of this 😢  since August
...
**Test plan**
...
...
=> Fix build race condition introduced in 0ba897f5c9f7dbc65bd812798531bed538447f42

libr/anal/p/anal_mips_gnu.c
...
**Test plan**
I'll add test files later.
...
=> Improve mips.gnu esil ##anal

libr/anal/p/anal_arm_cs.c, test/db/anal/arm64
=> blr on arm64 is an RCALL, not an UCALL ##anal

libr/bin/format/elf/elf.c, test/db/formats/elf/v850
=> Set v850 disassembler when opening v800 ELF files ##bin

libr/core/cmd_help.c
=> Fix and improve ?e? help message

libr/anal/p/anal_v850.c, test/db/anal/v850
=> Add initial function prelude support for v850 ##anal

libr/core/cmd_search.c, libr/core/core.c, libr/include/r_util/r_str.h, libr/util/str.c
=> Speedup r2pipe when using r2 -0, scr.prompt=0 doesnt log ##r2pipe

libr/debug/p/debug_windbg.c, libr/io/p/io_debug.c, libr/io/p/io_w32dbg.c, libr/io/p/io_windbg.c, libr/socket/socket.c
=> Fix some warnings in WinDBG plugin

libr/core/cmd_print.c
Fixes the following asan crash (https://github.com/radareorg/radare2/runs/1252432124#step:13:502):
**Test plan**
The asan build is fixed regarding the above test. All other builds are green.
...
=> Fix pxd asan crash

test/db/cmd/cmd_aae, test/db/formats/mz/cdogs
This pr sets a higher timeout on some tests due to slow asan r2 binaries.
**Test plan**
All builds are green, including the asan build.
...
=> Set higher timeout for asan tests that timeout

libr/anal/cc.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_mips_gnu.c, libr/anal/rtti_itanium.c, libr/anal/sign.c, libr/anal/type.c, libr/bin/pdb/pdb.c, libr/core/canal.c, libr/core/casm.c, libr/core/cbin.c, libr/core/cmd_anal.c, libr/core/cmd_print.c, libr/core/cmd_search_rop.c, libr/core/cmd_type.c
Import fixes from https://github.com/radareorg/radare2/pull/17529
**Test plan**
All green
=> Fixes for format string

.travis.yml, libr/asm/p/asm_x86_as.c
This test failed because there was no x86 cross assembler in the default environment.
Just install it and set the environment variable.
**Test plan**
My travis test https://travis-ci.com/github/eagleoflqj/radare2/jobs/401713104#L1055 db/tools/rasm2 passed.
...
=> Fix travis arm64 db/tools/rasm2
