libr/debug/p/native/linux/linux_debug.c
libr/io/p/io_ptrace.c

This issue is a result of running PT_ATTACH on a forked PID when you're only supposed to PT_ATTACH remote pids. linux_set_options probably always worked for you when testing in fork mode but it wouldn't work in remote attachment since you have to attach first + there's was error handling there.
When using fork_and_ptraceme_for_linux the child sets himself up to be traced for you.
I used GETSIGINFO to check the attachment status since it doesn't have any consequences(same result even if you run it multiple times) and always works on an attached process.
Also went ahead and cleaned up the code around the changes.
closes #14506

Fixed ptrace 'Operation not permitted'

---

libr/anal/p/anal_arm_cs.c

Should fix https://github.com/radareorg/radare2/issues/15275
Related r2r test: https://github.com/radareorg/radare2-regressions/pull/1987

Implement ESIL for arm64 UBFX ##anal

---

libr/util/regex/regcomp.c

Example: /e /(\x77\x30\x30\x74){2}/ searches for "w00tw00t"

Add support for hex escaped litterals in regular expressions

---

libr/debug/debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_debug.h

Tested with a multi threaded binary on Ubuntu, everything seems to work well.
With these changes, all 'select' implementation should properly resync after switching threads using `dpt=` without having to run `ds` as was previously required.

Fixed dpt= on linux by adding support for thread switching

---

libr/core/cbin.c

Related issue: https://github.com/radareorg/cutter/issues/1765
`time radare2 -A -qq -Q libcrackme.so`
Before:
```
real	1m49,847s
user	1m19,119s
sys	0m30,339s
```
After:
```
real	0m37,498s
user	0m36,761s
sys	0m0,715s
```
But `r_core_anal_cc_init()` still spends some cpu time on switching between 16/32 bits. Data caching can give ~5% analysis speedup (for the given binary).

Avoid reloading of cc sdb

---

libr/core/cmd_print.c

Fixes #15237 
``` 
[0x00000000]> pvzj @0x080485ac
[{"value":542976859,"string":"[+] Running program with username : %s"}]
```

fix pvzj output.

---

libr/bin/bfile.c
libr/bin/bin.c
libr/bin/i/private.h

* remove file_sz field from r_bin_file_new_from_buffer and r_bin_file_xtr_load_buffer
* remove all the messy buffer size handling and just rely on r_buf_size

Simplify r_bin_open_io function

---

libr/asm/arch/arm/armass.c

Fix #15302.
The `arm_assemble` function returns zero on error, but `thumb_assemble` returns -1. The condition prior to this patch masked all encoding errors from assembling thumb ops. This will propagate the errors from `thumb_assemble` so assembling bad instructions like 'bl 0x101' appropriately issues an error (i.e. from `rasm2`).
I intend to commit a regression test to [radare2-regressions](/radareorg/radare2-regressions) shortly.

#15302 [rasm2/armass] Correctly propagate errors from thumb_assemble

---

libr/debug/p/debug_native.c

Fixes Issue #15304 caused by PR #14730 by guarding the body of `linux_map_thp` against the absence of the `MADV_HUGEPAGE` macro. For older kernels without THP support, this function will simply fail.
One might also think to  check THP support by kernel version (e.g. by checking `LINUX_VERSION_CODE >= KERNEL_VERSION(2, 6, 38)` but this would not work for modern kernels which were explicitly configured without the `CONFIG_TRANSPARENT_HUGEPAGE` option. 
In all practical cases `MADV_HUGEPAGE` is likely to be a macro so I belive further checks are unnecessary, though if such a necessity were discovered one might like to build this check into `configure`.

#15304 Fix radare2 build for kernels without THP support

---

libr/io/p/io_self.c

Here it is more an additional 'safety blanket' as sysctl
call would fail once reached then end of the address mapping
anyway.

Setting the upper address limit for OpenBSD ##io_self

---

libr/anal/p/anal_arm_cs.c

fixed #15295 str part for ARM32. Post-indexed store fixed.

WIP: Fix Post-indexed memory access for ARM 

---

.travis.yml
libr/cons/utf8.c

Should fix rabin2 tests, though breakage might get worse before it gets better.

For utf-8 locale, check LC_ALL, LC_CTYPE and LANG in sequence instead

---

libr/debug/p/native/linux/linux_debug.c

In linux_attach_single_pid there is a check to avoid calling PT_ATTACH
multiple times on an already traced pid, which is an operation that
should be done only one time. The old code supposedly tried to set the
options only the first time you attach to a process, however when
debugging a process through the io_ptrace plugin, the process uses
TRACEME and the code never set the options of ptrace to intercept the
process before dying, amongst other things.
This patch tries to address the issue by using a boolean in RDebug that
keep tracks of whether the options were set or not for the process being
debugged.

Fix the way linux debugging options are set

---

libr/debug/debug.c
libr/debug/p/debug_gdb.c
shlr/gdb/src/gdbclient/core.c

Prior to these fixes, running step/continue and their variation would switch back to the original pid.

Fixed opcodes not being associated with the current thread in gdbr

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c

Added break functionality to around waitpid since there's no normal way to replace waitpid with a timeout-able function without using WHOHANG + sleep which isn't ideal. This change was required by cutter to suspend debug tasks that were ran with `&`.
dpk just called pid 0 so I went ahead and fixed it. Regarding `/* XXX: not for threads? signal is for a whole process!! */` - you have tkill for that, I would suggest restoring this functionality in a future PR for debugging.

Added a way to break while in linux_dbg_wait and fixed dpk

---

libr/core/cmd_debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/include/r_util/r_mem.h
libr/reg/value.c

This adds the functionality to set xmm registers with the `drm` command. Right now it is not possible to set the whole register at a time for that we would need to have some bignum support to handle the input. 
```
[0x004000b0]> drm xmm0 1 64 = 0x0001020304050607
[0x004000b0]> drm xmm0 0 64 = 0x08090a0b0c0d0e0f
[0x004000b0]> drm~:0
xmm0 = 0x000102030405060708090a0b0c0d0e0f
```

Add support for setting xmm registers on linux

---

libr/debug/meson.build
libr/debug/p/native/windows/windows_debug.c
libr/debug/p/native/windows/windows_debug.h
libr/include/r_io.h
libr/io/meson.build
libr/io/p/io_debug.c
libr/io/p/io_w32dbg.c
shlr/meson.build
shlr/w32dbg_wrap/include/w32dbg_wrap.h
shlr/w32dbg_wrap/meson.build
shlr/w32dbg_wrap/src/w32dbg_wrap.c

Basically the same as ptrace_wrap, but in windows, only receiving debug events is limited to the thread that started the debug session.

Implement w32dbg_wrap

---

libr/debug/p/debug_native.c
libr/debug/p/native/windows/windows_debug.c
libr/io/p/io_w32dbg.c

Previously `!=pid <pid>` attempted to OpenProcess even though the main pid is already opened by __open and the fact that re-opening the main pid wouldn't do anything. This way it attaches to new threads when called by r_debug_select.

Fix issues in windows thread switching

---

sys/asan.sh

As per the [instructions](https://clang.llvm.org/docs/AddressSanitizer.html#usage) (and as recommended [here](https://stackoverflow.com/a/40215639) and [here](https://groups.google.com/d/msg/address-sanitizer/SD590XDinfQ/NMUPj_G0BgAJ)).

sys/asan.sh: Use -fsanitize=... instead of -lasan when linking

---

sys/meson.py

This makes calling `r2.bat` from the path (or should be anywhere else) "just work" as long as radare2 is in the same directory.
This produces an `r2.bat` like:
```bat
@"%~dp0\radare2" %*
```

Make the generated r2.bat use bat path_relative syntax instead of hardcoding

---

libr/util/print.c

```
[0x00404324]> f=
...
0x004028f0 |――█████████████████――――――|  section..text
0x00402910 |――█――――――――――――――――――――――|  main
0x00404324 |――――█――――――――――――――――――――|  entry0
...
```
fixes  #15294

Add utf-8 support in r_print_rangebar

---

libr/core/cmd_debug.c

This adds support for printing xmm registers as packed floats and doubles.
The `d` was taken already so I am using `drmf` and `drml` right now. (better cmd name feedback appreciated).
A problem I see right now is that I got two pretty identical inner loops, and I am unsure about where to put a function to refactor them out. maybe into `debug_native.c` or stay in `cmd_debug.c` ?
And also maybe not `memcpy`ing but doing a `r_reg_get_pack_double` etc?
```
r2 -d radare2-regressions/bins/elf/allxmm -c "16ds; drmf" 
Process with PID 22572 started...
xmm0  = 1.100000 2.200000 3.300000 4.400000
xmm1  = 5.500000 6.600000 7.700000 8.800000
xmm2  = 0.300000 1.300000 2.300000 3.300000
xmm3  = 0.400000 1.400000 2.400000 3.400000
xmm4  = 0.500000 1.500000 2.500000 3.500000
xmm5  = 0.600000 1.600000 …
```

Add support for printing xmm* as packed floats and doubles

---

libr/debug/debug.c
libr/debug/p/native/windows/windows_debug.c

Previously, breaking would only work during 'dc' because it was pushed in debug.c specifically for continue. This change moves the responsibility of pushing/popping w32_break_process_wrapper to
windows_debug.c instead to support breaking calls to w32_dbg_wait from anywhere.

Fixed w32dbg breaking issues 

---

libr/debug/p/native/linux/linux_debug.c

`print_fpu` only accepts one parameter.

fix linux x86 build

---

libr/debug/debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/windows/windows_debug.c
shlr/w32dbg_wrap/include/w32dbg_wrap.h

Currently, the debugger has to switch threads to handle each event but it never returns to the thread that the user originally ran continue on. This results in a pretty confusing and annoying debugging experience. Plus, breaking the current task suspends execution twice because DebugBreakProcess' breakpoint is triggered once you continue, forcing you to run continue twice each time you break.
These changes handle break's behavior to avoid bothering the user and set R_DEBUG_REASON_[NEW_TID, EXIT_TID, NEW_LIB, EXIT_LIB] as events that don't require switching to the effected thread.
@GustavoLCR

Avoid switching threads for irrelevant events in windows ##debug

---

sys/asan.sh
sys/meson.py

Also, the [manual](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html#available-checks) says that `-fsanitize=undefined` implies `-fsanitize=signed-integer-overflow` (confirmed with gcc 9.2.1).

Sync default sanitizer list of sys/asan.sh and sys/meson.py

---

doc/yara.md

I recently ran into a closed issue with r2 and yara integration.
[Issue 12751](https://github.com/radareorg/radare2/issues/12751) discusses some ambiguity with the yara documentation.
This PR aims to clarify installation of yara with r2pm.

12751-Clarifying yara-to-r2 integration documentation.

---

libr/core/cfile.c

closes #15399 
Solves the gdbserver issue and fixes errors that might derive from forgetting `dL` or setting the wrong debug handler.

Automatically set the debug plugin when opening debug uris

---

libr/core/canal.c

Makes radare2 analyse functions that are defined as LOOS or HIOS symbol types e.g. memset from glibc@2.27.

Analyse HIOS and LOOS symbol types by default.

---

libr/anal/anal.c
libr/anal/fcn.c
libr/core/canal.c
libr/include/r_anal.h

Fixes the following leak:
```
$ r2 bins/elf/analysis/ls-alxchk 
[0x00005e24]> s main; aF
[0x00003bd0]> q
...
Direct leak of 16 byte(s) in 1 object(s) allocated from:
#0 0x7fa5815d4ca8 in __interceptor_malloc (/lib64/libasan.so.5+0x10dca8)
#1 0x7fa57df8c06e in fcn_recurse ../libr/anal/fcn.c:1017
#2 0x7fa57df90005 in r_anal_fcn_bb ../libr/anal/fcn.c:1404
#3 0x7fa57df8de3f in fcn_recurse ../libr/anal/fcn.c:1190
#4 0x7fa57df90005 in r_anal_fcn_bb ../libr/anal/fcn.c:1404
#5 0x7fa57df8de3f in fcn_recurse ../libr/anal/fcn.c:1190
#6 0x7fa57df90005 in r_anal_fcn_bb ../libr/anal/fcn.c:1404
#7 0x7fa57df8de3f in fcn_recurse ../libr/anal/fcn.c:1190
#8 0x7fa57df90005 in r_anal_fcn_bb ../libr/anal/fcn.c:1404
#9 0x7fa57df8de3f in fcn_recurse ../libr/anal/fcn.c:1190
#10 0x7fa57df90005 in r_anal_fcn_bb …
```

Fix leaddrs leak

---

libr/core/cmd_flag.c
libr/core/vmenus.c
libr/flag/flag.c
libr/include/r_flag.h

To be consistent with `r_flag_item_set_realname()`, etc. The RFlag arg was completely unused.

Refactor r_flag_color() to r_flag_item_set_color()

---

libr/util/list.c

Since pointers are passed-by-value, setting `list` to NULL using `R_FREE` actually has no effect in the calling function, and can mislead code readers.

Use free() instead of R_FREE() in r_list_free()

---

doc/macos.md

Avoid ambiguous signing certificates on macOS.
If a user manually installed a new code signing certificate into the
login keychain as documented, the install script will fail to sign r2 
because the `sys/macos-cert.sh` script generates a new certificate in
the System keychain. This results in the following error when signing:
```
org.radare.radare2: ambiguous (matches "org.radare.radare2" in /Users/user/Library/Keychains/login.keychain-db and "org.radare.radare2" in /Library/Keychains/System.keychain)
```
To be constistent with `sys/macos-cert.sh`, change manual certificate
generation steps to install to System keychain instead of login
keychain.
Mention that code signing certificate generation is automated by the
install script before listing the manual steps to generate a new
code …

Improve macOS installation documentation

---

doc/macos.md

I tried to clean up my r2 install on macOS 10.15.1 before building the latest version it from master.
The old r2 install was installed using [radare2-4.0.0.pkg](https://radare.mikelloc.com/get/4.0.0/radare2-4.0.0.pkg).
The command to uninstall in the docs did not execute properly, but succeeds with the following changes:
- Provide a proper package ID to get rid of the following error: `No receipt for 'radare2.pkg' found at '/'.`
- Prepend a `/` for each returned path by the `pkgutil` command, to make it an absolute path instead of a relative one.
- Avoid invoking the `sudo` command for each file, which speeds up the command significantly.

Fix broken pkg uninstall command on macOS

---

libr/include/sflib/darwin-arm-64/ios-syscalls.txt

`__exit` was listed twice with same number (1), and fork was missing.
Reference:
https://github.com/apple/darwin-xnu/blob/a449c6a3b8014d9406c2ddbdc81795da24aa7443/bsd/kern/syscalls.master

Fix typo in ios-syscalls.txt

---

libr/util/sys.c

After rebasing #15433 I noticed that #15322 broke signal handlers, making interrupt during continue exit r2 completely. The for loop's iterator was initialized with the first member of sig[]
instead of 0, jumping to uninitialized memory and setting up random values until a zero was found.

Fix r_sys_sigaction undefined behavior

---

libr/core/cfile.c
shlr/gdb/src/gdbclient/core.c

R2 will hang while waiting for any resolvable port to respond(even if it's not actually gdbserver, which is okay since you're verifying gdbserver's handshake), this takes a long while since read_packet has a high number of retries and the entire connection process is attempted twice in r_core_file_open. This is currently also an issue in [1874](https://github.com/radareorg/cutter/pull/1874) since it freezes cutter without any way to suspend the task.
Testing:
Start a valid tcp server with `nc -l -p 12345`, connect using `e cfg.debug=true; o+ gdb://127.0.0.1:12345` and attempt to break during the first/second connection attempt.

Add breaking to gdbr connect to avoid waiting on invalid connections

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/p/bin_mach0.c
libr/bin/p/bin_mach064.c

Add initial support for parsing and patching Mach-O relocs. It supports only the arch / reloc type combinations i've been able to test, but at least it's a starting point.
As i ported the patching code from ELF plugin, the way it works it's more or less the same. So to enable relocs patching, the binary should be opened like this:
```
r2 -e io.cache=true /path/to/binary
```
Fixes https://github.com/radareorg/radare2/issues/15279

Add support for Mach-O external relocs ##bin

---

libr/include/r_th.h
libr/util/thread_lock.c

r_th_lock_check only returns the refcount which isn't enough to know if the current thread is holding the mutex when a recursive mutex is enabled. This is useful in places like [gdbr's read registers](https://github.com/radareorg/radare2/blob/master/shlr/gdb/src/gdbclient/core.c#L671) that might be called recursively.

Add r_th_lock_tryenter

---

libr/anal/var.c

The output of `afvsj` shows offsets of sp-based variables as strings.
This fix changes the offset to be shown as a number, just like sp-based arguments and bp-based variables.

Emit sp-based var offset as a number

---

libr/asm/p/asm_x86_nz.c

The x86 assembler wasn't setting the first operand on mov instructions from memory with an offset correctly. This fixes that. See #15459 for more details.

Fix for #15459

---

libr/core/canal.c

`d05e816 `: The current block in graphviz output is highlighted even when `graph.gv.current` is `false`. Added a logical check to fix it.
`f5e3f60 `: else if blocks are off by one indentation level

Fixes to graphviz related code

---

libr/debug/p/debug_gdb.c
libr/reg/reg.c
shlr/gdb/include/gdbclient/commands.h
shlr/gdb/src/arch.c
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/xml.c

Writing registers with gdbr worked with single registers because reg_next_diff started at delta 0 and only had to run the diff once for the single register that was changed. When running reverse stepping/continue multiple registers are changed at once so r_reg_next_diff would fail every time due to incorrect offset calculation. The new r_reg_next_diff also supports diff'ing different register sizes to restore all registers correctly.
The endianity swapping part from reg_write isn't needed since the arena is the return value of 'g' which is already in the correct target byte order (see: https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#read-registers-packet).
Also, fixed and improved r_reg_next_diff which is currently only used by qnx and gdb but could be adopted in windbg(and …

Added correct parsing for all gdb registers and fixed writing multiple registers in gdbr for reverse stepping

---

.github/workflows/ccpp.yml

Lets see how it goes
Documentation on syntax is here https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
See also [template repositores](https://github.com/actions) and [Awesome Actions list](https://github.com/sdras/awesome-actions)
Feel free to extend.

Inital GitHub Actions

---

libr/cons/cons.c

anal.timeout is calculated by r_sys_now() + timeout value in seconds. Since r_sys_now() provides the current time in the format [44 bit seconds][20 bit micro seconds], the timeout value must be shifted 20 bits to the left (as done in r_sys_now) instead of multiplying by 1000000. Besides, timeout is a signed integer so even "short" timeout values like 1h (3600 seconds) result in an integer overflow when multiplied by 1000000. This causes unexpected behavior.

Fix anal.timeout calculation in r_cons_break_timeout

---

libr/search/rsa-find.c

Updated code to find larger keys within the 256 bytes buffer given as parameter. Tested with [#2020](https://github.com/radareorg/radare2-regressions/pull/2020).

Update RSA key search to find larger keys

---

libr/anal/d/cc-x86-32.sdb.txt

R2R: https://github.com/radareorg/radare2-regressions/pull/2025

Fix #15498 - Fix stdcall stack calling convention

---

libr/core/canal.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/core.c
libr/core/task.c
libr/include/r_core.h

This removes automatic scheduling from `r_cons_is_breaked()` and makes it explicit.
This means most commands will just block everything for now when run in a task, but by **carefully** adding yields, they can be made concurrent again while keeping everything safe.

Make Task Scheduling Explicit

---

.github/workflows/labeler.yml

With https://github.com/actions/labeler/issues/12 being an issue, the action's labeler is useless for PRs that come from a fork.
This one runs on a cron timer instead and doesn't suffer from the same issue.

Switch labeler to periodic-labeler

---

libr/cons/grep.c

Line range is exclusive so setting end to -1 results in last line being skipped.
After the changes doing `foo~:n..` shows all the lines starting with n until end.
Minor side effect is that `~:0..0` shows full range instead of empty. If it's necessary to support interpreting `n..0` as empty range the values stored in parsed grep description can be offset by one. That would make the code less obvious in my opinion.
Tests in radareorg/radare2-regressions#2030

Include last line when greping using foo~n..

---

libr/io/p/io_gdb.c
libr/io/p/io_mach.c
libr/io/p/io_ptrace.c
libr/io/p/io_w32.c
libr/io/p/io_windbg.c
libr/io/p/io_winedbg.c

`opt->sz` is initialized with `r_buf_size` at `r_bin_open_io` using an io buffer if `r_bin_open_io` can't open a file buffer. Since the debuggers returned unsigned values on lseek(used by io buffers to determine size) to opt->sz which is signed, opt->sz would overflow and contain a negative value, causing r_bin_open_buf to fail.
Went ahead and modified SEEK_END values for all debuggers even though this should only affect remote debuggers. ST64_MAX should be enough.
Note: gdbserver worked before the changes if it was on the same machine, tested with gdbserver on a different machine and wingdb.

Fix overflow that broke remote debugger reopening

---

libr/debug/p/native/linux/linux_debug.c

Didn't notice that the last PR broke previously undefined behavior(also available in Windows) of showing all processes with `dp 0`/when not debugging. This was used by Cutter's debug attach window.

Show all processes for pid 0 using dp and dpl

---

.appveyor.yml
libr/asm/meson.build
libr/bin/meson.build
libr/cons/cons.c
libr/core/cconfig.c
libr/egg/meson.build
libr/flag/meson.build
libr/include/r_cons.h
libr/search/meson.build
libr/util/meson.build
shlr/meson.build

Attempted workaround for failed build in https://ci.appveyor.com/project/radareorg/radare2/builds/29154687 ([failed test](https://ci.appveyor.com/project/radareorg/radare2/builds/29154687/job/vh1aixjlkvke5ni8#L14453)). Example of expected order is [here](https://github.com/kazarmy/radare2-regressions/blob/6cb2fd1901422297bc26ef0bf7d38a4ba7b0ddb8/new/db/cmd/cmd_pd#L1057-L1063).

ONE_STREAM_HACK & scr.onestream: Force expected ONE_STREAM order if necessary

---

libr/core/cmd_seek.c

One more seek history bug missed in previous PR.
Test was added in last commit of radareorg/radare2-regressions#2028 .
Lesson test everything, features that are not tested will not work.

Fix sj current position marker after buffer wrapping.

---

libr/anal/anal.c
libr/anal/fcn.c
libr/bin/bobj.c
libr/include/r_util/r_rbtree.h
libr/util/rbtree.c
libr/util/spaces.c

This makes stuff like `r_rbtree_cont_free()` easier to write.
I also reordered some args to make more sense. Now the user pointer for a callback always follows the callback itself.
Tests: https://github.com/radareorg/radare2-regressions/pull/2032

Add user Pointer to RBNodeFree

---

libr/io/p/io_debug.c

Execvp may hang until a signal is received on some systems(reproduced in arch linux) in case the file can't be executed specifically because of a broken symlink or a different arch(32bit on 64bit without support for example) instead of just failing.
This issue was encountered by @ITAYC0HEN, it seems to be solved with this fix. I couldn't replicate it on Ubuntu so I tested by adding a long sleep before execvp.

Add breaking to `ood` in linux to avoid execvp freezing ##debug

---

libr/debug/p/debug_gdb.c
shlr/gdb/include/gdbclient/commands.h
shlr/gdb/include/gdbclient/xml.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/xml.c

Most servers/clients should have xml support by now so it should behave like `dp` in any other debugger. ThreadsInfo is used as a fallback.
vFile is the only way to get detailed pid info unfortunately.

Added `dp` processes info support to gdbr ##debug

---

libr/util/ctype.c

Fix r_type_del() for typedefs (Fix #15337) ##anal

---

libr/asm/asm.c

Using `<=` instead of `<` just in case `tokens_size` ever becomes UINT_MAX, since UINT_MAX * 2 overflows to UINT_MAX.
------
This can be tested using the following:
```
$ cat poc.py
f = open("poc.asm", "w")
f.write("nop" + ";" * (2 ** 31 + 16))
f.close()
$ python poc.py
$ r2 -c 'waf poc.asm' -q -
```
Tested it by replacing `size_t` with `unsigned short`, casting in the proper places and doing strategic eprintf tracing.

Fix signed integer overflow in r_asm_massemble

---

libr/core/cmd_debug.c
libr/core/cmd_open.c
libr/include/r_core.h

This is mainly relevant for gdb and windbg but I have only tested with gdb since I am not sure how to extract a windows kernel binary from my qemu image to make sure this works with windbg. Should work though since windbg returns what seems to be a valid baddr.
This could also be used to overlay a different binary over the analyzed binary with a given baddr.
Please try to merge this before the coming release so we could use it in Cutter.

Added oodf\doof to enable rebasing for remote debug ##debug

---

libr/debug/p/native/linux/linux_debug.c
libr/include/r_debug.h

Previously, forked children would instantly die if the fork was stepped over using a breakpoint that would be accessible to the child process.
This change causes the debug to stop after forking even when trace_fork isn't set but this behavior matches native windows debug. I think that it's more logical to interpret "trace fork" as "apply ptrace tracing" and not just "handle the event" which should be mandatory.

Fixed an issue with detached child breakpoint inheretence ##debug

---

libr/core/cmd.c

Probably the fix to #15543. Tested on 4GB VM.

Fix crash on oom when command line is too long

---

test/new/db/cmd/cmd_pd
test/new/db/cmd/cmd_pf2
test/new/db/cmd/feat_foreach
test/new/db/tools/r2

Clone of radareorg/radare2-regressions#2037, which apparently is frozen in Archiveland ＦＯＲＥＶＥＲ．

Use ONE_STREAM=1 instead and assume it sets scr.onestream

---

libr/core/core.c

The warning:
WARNING: r_core_anal_hasrefs_to_depth: assertion 'core && value != UT64_MAX'
failed (line 2062)
This way registers like 'orax' will simply have an empty reference like before, just without an annoying warning when there really is nothing to telescope.
{"reg":"orax","value":"0xffffffffffffffff","ref":""}
That warning is constantly printed in Cutter since drrj happens with every step for the Registers Reference Widget. I don't see a reason to keep it.

Silence drr warning on UT64_MAX registers ##debug

---

libr/anal/p/anal_or1k.c
libr/asm/arch/or1k/or1k_disas.c
libr/asm/arch/or1k/or1k_disas.h
libr/asm/p/asm_or1k.c

As in certain build configurations it conflicts with the Capstone’s symbol of the same name, raising errors in the linking phase.
this is a quick fix, 'cause i'm not familiar with this arch.
the ideal solution would be not to rely on globals at all.

Rename  or1k `insns` global

---

libr/bin/format/mach0/mach064_is_kernelcache.c

In this way 64-bit SEP kernels aren’t wrongly detected as XNU kernel caches.

Add PIE flag check in kernelcache detection ##bin

---

libr/bin/meson.build
libr/bin/p/Makefile
libr/bin/p/bin_xtr_sep64.c
libr/bin/p/xtr_sep64.mk
libr/include/r_bin.h
libr/meson.build
plugins.android.cfg
plugins.bin.cfg
plugins.def.cfg
plugins.emscripten.cfg
plugins.ios-store.cfg
plugins.ios.cfg
plugins.nogpl.cfg
plugins.static.cfg
plugins.static.nogpl.cfg
plugins.tiny.cfg

Supports only 64-bit SEP firmwares.
It's based on a single sample, i'm glad to make it more generic if someone has more samples to share.
test with `rabin2 -x sep-firmware.n841.RELEASE.im4p-dec`

Add 64-bit iOS SEP xtr plugin ##bin

---

libr/debug/p/debug_gdb.c
shlr/gdb/src/gdbclient/core.c

RDebugPid not being initialized with NULL resulted in a free on an invalid pointer after gdbr_threads_list failed(since there were no threads to report for a dead pid).

Fixed gdbr warnings and a dpt crash after debug was over ##debug

---

libr/core/cmd_debug.c
libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c

The plugin would try work with an old version of desc, that was already freed by r_io_close_all after closing the session, and crash. 
I set debug_gdb's global 'desc' to NULL in detach as a temporary solution since I want this to be ready for release. In the future, we should convert to **desc to keep an updated copy of the pointer or think of a more clever idea since the code will look really messy and become error prone if the user has to handle double derefrences to access struct members.
Run 'oodf gdb://ip:port'->'doc' multiple times and see that r2 doesn't crash and that the session opened by oodf works(run ds, dc, drr)

Fix gdb reopen and `doc`

---

libr/anal/anal.c
libr/anal/cc.c
libr/core/anal_tp.c
test/unit/test_buf.c

Callers should be able to handle NULLs
(a new PR, sorry... this should enable the ASAN tests because of the `asan-*` branch name)

Function r_anal_cc_arg should just return NULL when nothing is available

---

libr/debug/p/native/windows/windows_debug.c
libr/debug/p/native/windows/windows_debug.h
libr/debug/pid.c

`dp=` fixes for windows - same idea as the linux dp= fix.
PPID in `dp/j` - added ppid info parsing to gdb, windbg and linux in previous commits. Very useful after attaching to a child process with `dp` if you want to easily find the way back.
```
[0x7fc722535b1c]> dp
* 37011 ppid:37009 uid:1000 s /home/yossi/workspace/tests/main
- 37012 ppid:37011 uid:1000 S /home/yossi/workspace/tests/main
[0x7fc722535b1c]> dpj
[{"current":true,"ppid":37009,"pid":37011,"uid":1000,"status":"s","path":"/home/yossi/workspace/tests/main"},{"current":false,"ppid":37011,"pid":37012,"uid":1000,"status":"S","path":"/home/yossi/workspace/tests/main"}
```
```
[0x7ffd65295ac4]> dp
Selected: 17140 13108
* 17140 ppid:10536 uid:2 s C:\workspace\cutter\radare2\dest\bin\ConsoleApplication1.exe
- 17564 ppid:17140 uid:2 s …
```

Add ppid to dp and fix dp= for windows

---

sys/meson.py

Blindfix for #15653. Blind since msbuild is achingly slow on local machine. Hopefully will hog AppVeyor only once.

Fix #15653: Silence MSVC XP deprecation warning

---

sys/meson.py

So that there is no need to update the code when VS 2021 comes around. Also, I think it's safe to assume that:
1. Microsoft will not reinstate XP support, ever.
1. There's no good reason to compile r2 using VS 2015 and below, instead of VS 2017.

sys/meson.py: Use == 'vs2017' instead

---

libr/debug/p/debug_native.c

Separate windows, linux and *bsd/apple since they have vastly different logic and the ifdef jungle implementation was too confusing. 
Tested in Linux and Windows, just in case but there aren't any code changes.
@devnexen Didn't really change anything but I would appreciate it if you could check that it's still ok in BSD. Also, we should start moving bsd to native/bsd/debug_bsd to make debug_native more easily maintainable.

Refactor debug native's wait function ##debug

---

libr/bin/p/bin_pe64.c

The format is reused for printing and internal type representation, breaking the JSON by making the value field in ihj empty since "llx" isn't a valid type

Revert pe coverity fixes to fix ihj

---

libr/core/cmd_open.c

Tested with linux native, gdb and windows native.
Previously, windows rebase didn't rebase most things properly once debug was closed.

Improve debug rebasing and fix partial windows rebase #debug

---

libr/core/task.c
libr/include/r_th.h
libr/util/thread_lock.c
shlr/gdb/include/libgdbr.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/libgdbr.c

As reported by helgrind.
RThreadLock.refs was broken beyond and only used in one place, so I removed it.

Fix some Race Conditions

---

libr/anal/var.c
libr/debug/p/debug_gdb.c
libr/util/thread_lock.c
shlr/gdb/src/gdbclient/core.c

7d19556001153e04d7f03afbaf9a4b416810b3f2 changed var behavior and it broke rebasing in gdb.
~With this change rebase reanalyzes the variables since the remote targets don't necessarily have the same registers as the originally analyzed code.~ Fixed the crash for now, reanalyzing loses type information so I reverted. We need a better solution based on deltas instead of names.
Thanks @GustavoLCR for the help 👍

Fix gdbr regressions ##debug

---

shlr/gdb/src/gdbclient/core.c

gdbr lock depth wasn't handled in a mutex and there were two points where a function would exit in a way that breaks the lock count

Fix gdbr race conditions ##debug

---

libr/include/r_util/r_rbtree.h
libr/util/rbtree.c
test/unit/test_rbtree.c

For `r_rbtree_upper_bound()`,  "the smallest node that is greater than data" would mean "**smallest** node that is **outside** of the set given by the upper bound". For me, "**greatest** node that is **inside** the set given by the upper bound" makes more sense and is also much more useful next to the lower bound function.
The function was used nowhere before and had no tests, so that semantics change should be fine.
I also adjusted `r_rbtree_upper_bound_backward()` to go along with this meaning and removed `lower_bound_backward` and `upper_bound_forward` because they are complicated and I can't imagine a single use case for them right now. These functions also are not used anywhere except tests.

Change Semantics of r_rbtree_upper_bound() and simplify Iter Fcns

---

libr/bp/bp_io.c
libr/core/cmd_debug.c

Previously, disabled breakpoints were restored and then hit during execution. The debug logic ignored them and continued but that's an unnecessary slow down. To achieve this type of behavior the user should use tracepoints.
ref #1967

Prevent the restoration of disabled breakpoints ##debug

---

libr/core/cfile.c
libr/core/cmd_open.c
libr/debug/debug.c
libr/include/r_debug.h

Windows breakpoint rebasing issue - bp->delta is calculated with the dbg->bp->baddr at the time of breakpoint creation, which may not reflect the correct baddr and break the rebase.
Windows debug reopen issue - attach_new_process was called(and failed if we already detached) instead of regular attach because the saved pid and tid in core->dbg weren't reset before calling r_debug_select in a new session. Made sure this won't be a problem when using dp= after dp- either.

Fix windows breakpoint rebasing and debug reopening ##debug

---

libr/core/vmenus.c

To get rid of this `fur` warning

Fix Field Seek in Visual Menus

---

libr/core/cbin.c

I found here are a bug in rabin2 generate json, when I use rabin2 -j -g to analyize a file, sometime I would get a invalid json.
For example , your can use rabin2 -j -g configure . ( configure it's a file under this repo root path ), and you would get this json:
```
{"sections":[]
,"segments":[]
,"entries":[]
,"initfini":[]
,"main":false,"imports":[],"classes":[],"symbols":[{}],"strings":[]false,"info":{"arch":"","baddr":0,"binsz":21691,"bintype":"","bits":64,"canary":false,"class":"","compiled":"","compiler":"","crypto":false,"dbg_file":"","endian":"little","havecode":false,"guid":"","intrp":"","laddr":0,"lang":"","linenum":false,"lsyms":false,"machine":"","maxopsz":16,"minopsz":1,"nx":false,"os":"","pcalign":0,"pic":false,"relocs":false,"rpath":"","sanitiz":false,"static":true,"stripped" …
```

Fix json generate bug

---

libr/anal/var.c
libr/core/cmd_open.c
libr/include/r_anal.h

After starting debug the register deltas weren't mapped to the same registers in remote and native debug. This made wrong registers appear as vars in native debug and no registers were shown in remote gdb since the remote's list is much shorter than r2 reg lists.
Rebasing before the fix:
```
┌ 101: int main (int argc, char **argv, char **envp);
│           ; arg int argc @ rdi
│           ; arg char **argv @ rsi
┌ 101: int main (int argc, char **argv, char **envp);
│           ; arg int argc @ cf
│           ; arg char **argv @ rip
```
Rebasing in remote gdb before the fix:
```
┌ 101: int main (int argc, char **argv, char **envp);
│           ; arg int argc @ rdi
│           ; arg char **argv @ rsi
┌ 101: int main (int argc, char **argv, char **envp);
│           ; 
│           ; 
```
Now …

Fix var rebasing ##debug

---

libr/core/cbin.c
test/new/db/cmd/cmd_i

Fix for empty strings seen in https://github.com/radareorg/radare2/pull/15727#issue-357668117.

izz: Fix printing of string with backslash if str.escbslash=false

---

libr/debug/p/native/windows/windows_debug.c

b was true for all of the child processes so the parent's handle was used to get the path of each child instead of opening a new handle for the given pid in __build_debug_pid.
Previous output:
```
* 19328 ppid:1316 uid:2 s C:\workspace\radare2\build\priv_install_dir\bin\radare2.exe
- 10372 ppid:19328 uid:2 s C:\workspace\radare2\build\priv_install_dir\bin\radare2.exe
```
After fix:
```
* 19328 ppid:1316 uid:2 s C:\workspace\radare2\build\priv_install_dir\bin\radare2.exe
- 10372 ppid:19328 uid:2 s C:\Windows\System32\conhost.exe
```

Fix windows dp showing the parent's path for all processes

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_debug.h

Shows the module, offset and function name instead of showing the executable's
path for all threads.
```
* 33225 s /home/yossi/workspace/tests/main (0x5585485d2cc5) in main+0x95
- 33226 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f64539da9d0)
- 33227 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f64539da9d0)
```

Add location in file to linux dpt output ##debug

---

libr/debug/p/debug_native.c
libr/debug/p/native/drx.c

Instead of unsetting breakpoints they were set again without removing the previous drx values, which also caused the "Invalid DRX length (0) must be 1, 2, 4, 8 bytes" error because of the wrong len values.
Also, when resetting twice, del failed since there weren't any hw registers to delete, which prompted the "hw breakpoints not yet supported" error by the fallback bp restore function.
ref [#1975](https://github.com/radareorg/cutter/pull/1975)

Fix hardware bp restoring and fix hwbp repeating errors ##debug

---

libr/bp/bp.c
libr/bp/bp_io.c
libr/core/cmd_debug.c
libr/core/core.c
libr/debug/debug.c
libr/include/r_bp.h

This way it is possible to set breakpoints before starting debug through 'db' and the user will be notified when a breakpoint points to an invalid map.
ref [#1975](https://github.com/radareorg/cutter/pull/1975)

Validate bp addr on rebase and restore instead of preventing creation

---

libr/core/cmd_debug.c
shlr/gdb/src/gdbclient/xml.c

`drt` didn't print most registers due to the arch size restriction.
Gdbr - Some xmm registers were printed as fpu and bnd registers were shown in all drt categories since they were marked as flags, moved to seg since we don't have a more appropriate section.

Improve gdb dynamic register creation and fix drt ##debug

---

libr/bp/bp.c
libr/core/cmd_debug.c
test/new/db/archos/linux-x64/dbg_bps

* Lack of cleanup in r_bp_del_all causing use after free in other dbi
commands
* Copy paste error turning dbix into dbx
* Add dbi- command
* Allow dbi commands to operate with index 0

Fix double free in r_bp_del_index and other breakpoint index bugs

---

libr/bin/filter.c

sdb_fmt(PFMT64x, 0) is undefined behavior if int is 32 bits, because the integer constant 0 is an int and vsnprintf will try to read a long long off the stack, resulting in overflow.

Pass 64-bit sdb_fmt parameters as 64-bit

---

libr/util/str.c
test/new/db/cmd/write

r_str_unescape: Support all izz esc seqs

---

libr/debug/p/native/bsd/bsd_debug.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/pid.c

Same as #15744 which added code location data for linux debug. Instead of formatting the path string for each debug plugin, the path is based on the program counter if it was provided in pid info.
There is no point in showing the binary's path in `dpt` for each thread anyways, the user should use `dp` for that.
Windows:
```
* 12620 r IMAGE    ConsoleApplication1.exe | .text (0x13e1307) in fcn.00411307+0x0
- 29012 r IMAGE    ntdll.dll | .text (0x7ffd65299214)
- 28832 r IMAGE    ntdll.dll | .text (0x7ffd65299214)
- 23364 r IMAGE    ntdll.dll | .text (0x7ffd65299214)
```
Linux:
```
* 33225 s /home/yossi/workspace/tests/main (0x5585485d2cc5) in main+0x95
- 33226 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f64539da9d0)
- 33227 s /lib/x86_64-linux-gnu/libc-2.27.so (0x7f64539da9d0)
```
Gdbr is a …

Added detailed location info to dpt using pc instead of path ##debug

---

libr/core/cbin.c
libr/include/r_util/pj.h
libr/util/pj.c

`"N/A"` makes no sense in json

Add null to pj and use for relocs

---

libr/core/cmd_debug.c

More intuitive that way since it's a the debug version of the command

Enable cfg.debug before running oodf in doof ##debug

---

libr/core/cmd_open.c

closes #15791 
Had this happen while remote debugging a firmware image without sections

Fix crash caused by rebasing a file without sections ##debug

---

libr/core/disasm.c
test/new/db/cmd/cmd_pd2

https://github.com/radareorg/radare2/commit/2c44b263dc935714a9fcad06dbd0c54eb3bf4dda#diff-bc8bf85d0cb3d8909bef69fb94c6b1aa

asm.symbol: Fix flag name when disasm from non-flag addr with no anal

---

libr/core/cmd_debug.c
libr/include/r_reg.h
libr/reg/profile.c

We are planning to add documentation on register hover to Cutter's register widget((Mainly for FPU regs), this change enables it.
The profile comment command was moved from drC to drcp.

Add register comment support and drC/j to view them

---

libr/core/disasm.c

Currently, when `e asm.flags.real` is enabled, radare2 will print a comment with the full name of the flag because it thinks that the flag wasn't printed. This Pull Request make sure that r2 will know that the flag was printed by its real name.
**Before** ( notice the `sym.imp.KERNEL32.dll_LoadResource` prints)
```
0x004014fd      call dword [FindResourceW]          ; sym.imp.KERNEL32.dll_FindResourceW
; 0x403028 ; HRSRC FindResourceW(HMODULE hModule, LPCWSTR lpName, LPCWSTR lpType)
0x00401503      mov esi, eax
0x00401505      push esi                            ; HRSRC hResInfo
0x00401506      push 0                              ; HMODULE hModule
0x00401508      call dword [LoadResource]           ; sym.imp.KERNEL32.dll_LoadResource
; 0x40302c ; HGLOBAL LoadResource(HMODULE hModule, …
```

Hide flag comments when realname is shown

---

test/src/r2r.v

Doing this because results suggest it's faster than `-j <num_of_cores>` even for the full non-native asm test set, and that a producer-consumer setup appears doable in V but very complicated.
Might hit OS limits for _X_ number of tests.

r2r.v, -j 0: Allocate 1 job per test

---

libr/bin/bin.c

opt->sz is not used anyway in r_bin_open_buf, so there's no need to
check its value or compute it.

Remove opt->sz checks and operations in r_bin_open_buf

---

libr/io/p/io_gdb.c
shlr/gdb/src/common.c

This feature only works with server implementations that have ReverseStep and ReverseContinue enabled, such as mozilla's [rr](https://github.com/mozilla/rr)(used to test this feature). The official gdbserver doesn't support it. `=!rd` was added so that external tools will be able to check support.
ref #8966, don't close it though since these commands only work for special gdbservers.

Added reverse step and continue support to gdbr ##debug

---

libr/anal/sign.c
libr/core/cmd_anal.c
libr/core/cmd_zign.c
libr/include/r_anal.h
libr/include/r_sign.h
test/new/db/cmd/cmd_zignature

This is still WIP - don't merge yet, there are unnecessary comments and prints.
PR status:
Example: `types: main.ret=int, main.args=2, main.arg.0="int,argc", main.arg.1="char **,argv"`
Edit: Closes #15372

Apply types on matching zignature data ##signatures

---

libr/anal/sign.c

Fix error: `for` loop initial declarations are only allowed in C99 mode

C89 Fixup for r_sign_fcn_types function

---

test/new/db/cmd/cmd_pd
test/new/db/cmd/cmd_pd2
test/new/db/cmd/cmd_pdr

Done using `--to-eof` by radare/node-r2r#12.

Convert cmd_pd* tests from <<KEYWORD to <<EOF

---

libr/util/list.c

`r_list_set_n` is used to replace `n`'th element in a given list. If one element in the list is empty, the iteration will be terminated and no chance to compare tailing indexes.
(see related issue: https://github.com/radareorg/radare2/issues/15815)
Thus, I changed this function to allow an `empty` list object. and compare the `data` just before `free`.

WIP: Fix r_list_set_n() to allow empty element

---

libr/core/anal_tp.c
libr/core/cbin.c
test/new/db/cmd/cmd_pd
test/new/db/cmd/comments
test/new/db/cmd/metadata

After discussions, this PR will make sure that real name isn't shown for strings.
This will return the good old `
```
mov ebx, str.Think_you_can_make_it
```
instead of 
```
mov ebx, "Think you can make it????!!!!>>?"
```
which was added recently in the realname PR.

Remove realname from strings

---

libr/util/lib.c

* dot can be null
* Using R2_VERSION_MAJOR/MINOR is wrong because they will be continuously updated and we want to check for exactly 4.2.0
* The version check logic itself was wrong

Check version for pkgname correctly

---

libr/core/canal.c

Make 0 fcnsize warning more meaningful and verbose-only (Fix #15091)

---

libr/asm/arch/arm/armass64.c
libr/asm/d/arm.sdb.txt
test/new/db/asm/arm_64

Resolving #15855. Add both instructions, updated unit test and opcode description

Add cbnz and cbz instruction for arm64 assembler

---

libr/core/cmd.c
libr/include/r_core.h
shlr/Makefile
shlr/meson.build

Still improving the grammar in radare2-shell-parser.
I refactored a bit the code in cmd.c.
The grammar is able to parse most commands (simple commands like `pd 10`, commands with temporary changes like `pd 10 @ 0xdeadbeef @a:x86`, iterators like `pd 10 @@b`, `@@@s`, grep commands with `~`, repeat commands with a number in front of the command, interpret commands with a dot in front of it, command substitution, pipe, redirection, quoted arguments, etc.)
The integration with r2, however, is still incomplete. Only simple commands, temporary seeks, interpret commands and redirection are supported for now. I will add the other things soon enough.
By the way, to test the new command parser you should:
- compile r2 with: `meson -Duse_treesitter=true build; ninja -C build;`
- run r2 with …

Update radare2-shell-parser and improve tree-sitter related code in cmd.c

---

libr/asm/arch/arm/armass64.c
test/new/db/asm/arm_64

Fix #15873 
- Mov should be able to handle 8 bit immediate value
- While at it make sure that both destination and source register are the same
- Added test case

Arm64 assembler mov immediate word fix

---

test/src/r2r.v

Otherwise the following test in `tools/rahash2`, which should fail since current r2r.v doesn't support '...' tests yet:
```
NAME=rahash2 -D base64 -s "YWRtaW4="
FILE=-
CMDS=!rahash2 -D base64 -s "YWRtaW4="
EXPECT='admin'
RUN
```
actually succeeds.

r2r.v: Allow '=' in keyword argument

---

libr/anal/p/anal_arm_cs.c
test/new/db/esil/arm_64

- fix #15265 
- ESIL for bic with 32 and 64 bit register
- ESIL test case for 32 and 64 bit register

Added arm64 ESIL for bic 

---

libr/reg/value.c

No adjustments are necessary when bounds checking the byte offset of a flag register against the arena's size. Previously, we had an off-by-one that prevented flag registers in the last byte of the arena from being read, as reported in #12949.
Please let me know whether a test case is warranted to prevent regressions.

Fix bounds check for flag registers in last byte of arena (#12949)

---

libr/main/rasm2.c

Add the missing return flag inversion so reading from stdin and a regular
file both return zero on success.

rasm2: treat reading from stdin the same as reading from a file

---

libr/bin/format/le/le.c

we forgot to free the bin object leaking it if we bail out, plus improved the r_bin_le_free to actually free the root object

fixing memory leaks

---

libr/core/cmd.c
test/new/db/tools/r2
test/new/scripts/no-nl-at-eof.r2

There is no output when running `radare2 -i <script> -NQ -` when the script is a single-liner with no newline at the end. This pr fixes that.
**Test plan**
See test.
Issue in description. The `-N` is not relevant here.

Fix radare2 -i -Q output when script has no nl at eof

---

libr/anal/p/anal_arm_cs.c

see #15915 for test plan
`disp` is `int`, which does not fit `PFMT64x`

Fix a format string in arm (Fix #15915)

---

libr/core/cmd_anal.c

Currently, `anj` did not show the "realname" entry of a flag. This makes it harder to access this information in places which rely on `anj`, like Cutter.
This pull request adds "realname" to the JSON output.
**Test plan**
Before:
```
[0x004015f5]> anj~{}
[
{
"name": "sym.imp.KERNEL32.dll_GlobalFindAtomA",
"type": "flag",
"offset": 4206660
}
]
```
After:
```
[0x004015f5]> anj~{}
[
{
"name": "sym.imp.KERNEL32.dll_GlobalFindAtomA",
"realname": "GlobalFindAtomA",
"type": "flag",
"offset": 4206660
}
]
```
1. Open a binary in radare2 before the change
2. Use `anj` on instruction using a flag with a real-name. e.g a call to an imported function in PE
3. Execute `anj~{}` and see that realname isn't available
4. Update radare2 to …

Add realname to anj

---

libr/main/radare2.c
test/new/db/tools/r2

Currently, `radare2 -i <script> -Q <binary>` will drop into a hidden prompt with no console echo if `<script>` is missing. This causes automated scripts to hang. This pr fixes this by terminating radare2 instead. 
**Test plan**
See test.
Issue in description.

Terminate on missing script when doing radare2 -i -Q

---

libr/include/r_anal.h

This was a leftover from the non-overlapping anal-block poc.

Fix Comment about RAnal.bb_tree

---

libr/anal/p/anal_arm_cs.c

On ARM 32-bit I noticed that the conditionally executed push/pop instructions with reglists are not properly handled in esil.
```
$ r2 malloc://1024 -c "e asm.arch=arm; e asm.bits=32; wx 03002de903002d0904002d05; pd 3; e asm.esil=1; pd 3"
0x00000000      03002de9       push {r0, r1}
0x00000004      03002d09       pusheq {r0, r1}
0x00000008      04002d05       streq r0, [sp, -4]!
0x00000000      03002de9       8,sp,-=,r1,r0,2,sp,=[*]
0x00000004      03002d09       8,sp,-=,r1,r0,2,sp,=[*],}
0x00000008      04002d05       zf,?{,r0,0x4,sp,-,0xffffffff,&,=[4],4,sp,-,sp,=,}
```
As you can see the esil for the `pusheq` instruction contains the closing bracket `,}` (i.e., the postfix string), but not the opening esil `zf,?{`
With …

fixed esil for arm push/pop with conditional

---

meson.build
meson_options.txt
test/unit/meson.build

This enables the unit tests to be built and run directly as part of the meson project.
It is disabled by default an can be enabled with the `build_tests` option.
**Test plan**
* run meson with `-Dbuild_tests=true` or reconfigure an existing build dir like `meson configure -Dbuild_tests=true`
* `ninja test`
* You should get something like this:
```
[florian@florian-laptop build]$ ninja test
[0/1] Running all tests.
1/34 addr_interval                           OK       0.02 s 
2/34 anal_block                              OK       0.02 s 
3/34 anal_function                           OK       0.02 s 
4/34 base64                                  OK       0.02 s 
5/34 bin                                     OK       0.03 s 
6/34 bitmap …
```

Add Unit Tests to Meson

---

test/new/db/cmd/cmd_i
test/new/package.json

Upgrade to node-r2r 0.3.0 needed to support removal of deprecated `'...'` constructs from tests, especially the json tests. Some examples are provided in the included `cmd_i` testfile conversion.
**Test plan**
Issue in description.
----
One day there might be a way in V to prettify tests, e.g. changing
```
EXPECT/EXPECT_ERR=<<EOF
EOF
```
to 
```
EXPECT/EXPECT_ERR=
```
and
```
CMDS=<<EOF
<cmd>
EOF
```
to 
```
CMDS=<cmd>
```
but not
```
EXPECT/EXPECT_ERR=<<EOF
<single-line output>
EOF
```
to
```
EXPECT/EXPECT_ERR=<single-line output>
```
since that changes output columns.

Upgrade node-r2r to 0.3.0

---

libr/bin/p/bin_dex.c
test/new/db/formats/dex

It honors segments in DEX files by adding header, code, and data segments similar to the sections.
**Test plan**
```
$ r2 /tmp/classes.dex
[0x0034b3c8]> iSS
[Segments]
nth paddr           size vaddr          vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000      0x70 0x00000000      0x70 -r-- header
1   0x00344188  0x676c70 0x00344188  0x676c70 -r-x code
2   0x00aac3f1   0x29007 0x00aac3f1   0x29007 -r-- data
[0x0034b3c8]> iS
[Sections]
nth paddr           size vaddr          vsize perm name
―――――――――――――――――――――――――――――――――――――――――――――――――――――――
0   0x00000000      0x70 0x00000000      0x70 -r-- header
1   0x00000070  0x344118 0x00000070  0x344118 -r-- constpool
2   0x00344188  0x676c70 …
```

Honor segments in DEX files

---

libr/core/cmd_type.c
test/new/db/cmd/cmd_tcc

```
$ r2 /bin/ls
[0x000067d0]> tccj                                                                                                                                                                            
This is not a valid calling convention name                                                    
WARNING: pj_s: assertion 'j && k' failed (line 176)                                            
["rax amd64 (rdi, rsi, rdx, rcx, r8, r9, xmm0, xmm1, xmm2, xmm3, xmm4);","rax ms (rcx, rdx, r8, r9, stack);"]
[0x000067d0]> tccl
This is not a valid calling convention name
rax amd64 (rdi, rsi, rdx, rcx, r8, r9, xmm0, xmm1, xmm2, xmm3, xmm4);
rax ms (rcx, rdx, r8, r9, stack);
(null)
[0x000067d0]> tcc*
This is not a valid calling …
```

Fix tccj, tccl, tcc* output errors

---

libr/core/cmd_debug.c
test/new/db/archos/linux-x64/dbg_bps

Currently the user has to enable `dbg.hwbp` to set hardware breakpoints with `db`, we should have a documented command in `db?` as well.
**Test plan**
* Run `dbH <addr>` and see that it shows up correctly in `db`
* Try invalid `dbH` params
* See that `db <addr>` and `dbw <addr>` still work

Add 'dbH' to set hardware breakpoints

---

libr/core/cmd_search.c

- /j without argument returns empty result
- /j with space and without argument return stray new line
```
$> r2 /bin/ls
-- Execute commands on a temporary offset by appending '@ offset' to your command.
[0x000067d0]> /j<---- no space and no argument
[]
[0x000067d0]> /j <---- space and no argument
Invalid keyword
[0x000067d0]>
```
After patch 
```
$> r2 /bin/ls
-- The stripping process is not deep enough
[0x000067d0]> /j
Invalid keyword
[0x000067d0]> /j 
Invalid keyword
[0x000067d0]>
```
...
**Test plan**
...
...

Fix /j in r2 when there is no input argument

---

libr/core/cmd_anal.c

Add missing afis info in afi?.
Fix afis? output when it is not used within a function.
```
[0x00000000]> afi?
Usage: afi[jlp*]   <addr>
| afi              show information of the function
| afii[-][import]  show/add/delete imports used in function
| afi.             show function name in current offset
| afi*             function, variables and arguments
| afij             function info in json format
| afil             verbose function info
| afip             show whether the function is pure or not
| afis             show function stats (opcode, meta)
[0x00000000]> afis?
Usage: afis[ft]
afis           enumerate unique opcodes in function
afisa[fo]      enumerate all the meta of all the functions
afisf          enumerate …
```

Add missing afis info in afi? and fix afis?

---

libr/anal/bb.c
libr/core/agraph.c
libr/core/cmd_print.c
libr/include/r_anal.h

These members were only used for printing graph and pdr. Also they caused a uaf when a basic block is removed since they keep pointers to basic blocks, see test plan.
**Test plan**
**Before:** `r2 -Qc "s main; af; agf; afb- 0x8048643; agf" megabeets_0x1` (can be any bin, just remove a basic block between two agf calls)
causes:
```
==68045== Invalid read of size 4
==68045==    at 0x5BB9E25: get_bb_body (agraph.c:2176)
==68045==    by 0x5BBA6F6: get_bbnodes (agraph.c:2343)
==68045==    by 0x5BBADD2: reload_nodes (agraph.c:2483)
==68045==    by 0x5BBD23C: agraph_reload_nodes (agraph.c:3162)
==68045==    by 0x5BBDBDF: check_changes (agraph.c:3357)
==68045==    by 0x5BBDF74: agraph_print (agraph.c:3417)
==68045==    by 0x5BBE6B6: agraph_refresh (agraph.c:3554) …
```

Remove prev, jumpbb and failbb from RAnalBlock ##anal

---

libr/core/cmd.c
shlr/Makefile
shlr/meson.build

This PR adds support for command substitution in the new shell parser implemented with tree-sitter. We agreed on allowing command substitutions (backticks and `$( ... )`) only where an argument is expected. The expansion of the inner command can at most generate new arguments, but it cannot change the structure of the command (e.g. `pd $("?e 10;pd 10")` will not execute two times the `pd` command, but it will be interpreted as `pd "10;pd 10").
**Test plan**
After setting `e cfg.newshell=true` you can try things like:
```
> pd $(?e 10)
> om `?e 4` 0x1000$(?e 00 $(?v 100)) 0x5555
> pd 10 @ $(afl~main[0]:2)
```
**Additional information**
As usual, this is far from complete. I need to improve how arguments are handled and there …

Use state struct and start handling cmd_substition_arg in tree-sitter

---

libr/core/cmd.c
shlr/Makefile
shlr/meson.build

This PR adds support for redirect to alias (e.g. `om* > $myalias`) in new parser and fix grep with multiple words (e.g. `pd 10~xor~eax`)
**Test plan**
Some of the regression tests use these features, so they should now pass with the new parser.

new parser: fix multiple words in grep and add support for > $alias

---

libr/anal/p/anal_x86_cs.c
test/new/db/anal/x86_16
test/new/db/anal/x86_32
test/new/db/anal/x86_64

Fix for aoj on x86 to handle instructions with hidden operand
- Add hidden_op()
- Added operands info for pushf, popf, pushfd, popfd, pushfq, popfq
- Add test for aoj pushf
**Test plan**
Added test cases
closes #13908
...

Fix #13908 - x86 aoj for instruction with hidden operand ##asm

---

libr/bin/bobj.c
libr/bin/format/mach0/mach0_specs.h
libr/bin/p/bin_dyldcache.c

Add logic to parse unmapped local symbols.
Every macho image present in the dyldcache has all the metadata about its local symbols stripped away from the corresponding macho header. Instead, this information is present as dyldcache-specific metadata stored in unmapped parts of the cache file.
This PR, for every loaded image, takes care of adding the local symbols which are missing.
**Bonus**
Fix a potential use-after-free caused by `r_bin_object_set_items`, by rebuilding class-related hash tables after replacing the class list.

Parse dyldcache local symbols ##bin

---

libr/core/cmd_eval.c
test/new/db/cmd/cmd_ec

PR is simply to output an error on invalid color selection with `ecHi`. It's the same thing `ecHw` does, but `ecHi` was not outputting it.
Also pulled the `free` up above the print since it was duplicated code that only really needed to be called once.
...
**Test plan**
Just type `ecHi blerg` and note that there's now an error about the color.
...
...

Echi bad color

---

libr/anal/cc.c
libr/anal/var.c

Fix compilation warnings introduced by me in my previous pull request for Swift calling convention:
```
var.c: In function ‘r_anal_extract_rarg’:                                                                        
var.c:733:37: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]
#define STR_EQUAL(s1, s2) s1 && s2 && !strcmp (s1, s2)
^
var.c:837:46: note: in expansion of macro ‘STR_EQUAL’                                                            
if (is_reg_in_src (regname, anal, op) || STR_EQUAL (opdreg, regname)) {
^~~~~~~~~
var.c:733:37: warning: suggest parentheses around ‘&&’ within ‘||’ [-Wparentheses]                                                    #define STR_EQUAL(s1, s2) s1 && s2 && !strcmp …
```

Fix compilation warnings

---

test/new/db/cmd/cmd_pd
test/new/db/tools/r2r
test/src/r2r.v

1. Broken only-on-EXPECT_ERR tests are now marked BR instead of FX.
1. Both EXPECT_ERR and stderr are space-trimmed.
**Test plan**
r2r.v is OK on all tools/r2r and cmd/cmd_pd tests.

r2r.v: Fix EXPECT_ERR handling

---

libr/anal/p/anal_ppc_cs.c
test/new/db/anal/ppc
test/new/db/esil/ppc_32

This solves incorrect ESIL generated for PPC load/store with update instructions. According to PPC documentation, the memory register is updated with the computed effective address; however, the generated ESIL code just increments the memory register by the size of the load/store.
**Test plan**
Added testcase db/esil/ppc_32 to verify ESIL for lwzu and stwu instructions.
closes #15970

Fix incorrect PPC ESIL and add testcase (#15970)

---

libr/bin/format/elf/elf.c
test/new/db/formats/elf/symbols

This bin (`elf/switch-hello-world.elf` in testbins) has a `.dynstr` section of size 1 with only one zero byte and a symbol in `.dynsym` whose name refers to `.dynstr + 0`.
The `sym[k].st_name + 2 > strtab_section->sh_size` check (I assume +2 meant 1 readable char + 1 null byte, but why not allow empty strings with just the null byte?) would reject this and break out of the entire symbol loading loop, so no symbols would be loaded.
**Test plan**
`r2 -c "is" elf/switch-hello-world.elf`
Before: no symbols, after: symbols \0/

Fix ELF symbols for names just before the end of strtab ##bin

---

libr/core/cmd.c
shlr/Makefile
shlr/meson.build

This PR adds support for the repeat_command (e.g. `2pd 10`) and it adds support for the "concatenation" rule defined in updated radare2-shell-parser, which is a single argument without any space, but that may be composed of quoted parts, command substitution, and other identifiers (e.g. in `?e 100$(?e 123)`, `100$(?e 123)` is a concatenation, because it is composed by a arg_identifier part (the first part) and a cmd_substitution_arg (the second part)). It also fixes issues when handling system_commands (e.g. `!rahash2 ....`), where arguments were not correctly split.
**Test plan**
Still work in progress, but the number of tests in the travis job should decrease.
To test, as usual, you can compile with `meson …

Add repeat_command, concatenation and fix system_command

---

libr/bin/bfile.c
libr/bin/format/pe/pe.c
libr/bin/format/pe/pe.h
libr/bin/format/pe/pe_specs.h
libr/bin/p/bin_pe.inc
libr/core/cmd_info.c
libr/include/r_bin.h
libr/include/r_util/r_pkcs7.h
libr/main/radare2.c
libr/util/pkcs7.c
test/new/db/formats/pe/authentihash

Add Authentihash and Authentihash check support for Portable Executable. Currently, the Authentihash information are stored in the `pe` sdb.
**Missing steps**
Imo, Authentihash information should be displayed at somewhere specific to the file format. For now, `it` seems to generate general hashes (md5, sha1, sha256). Adding Authentihash into the command will complicate the code (checking if `rclass == pe`, get authentihash with `sdb_querys`, output directly) while the existing code is using a `RList` of `RBinHash`, which makes me wonder if there is a cleaner way to do this. For Authentihash check, I thought about adding it into `RBinInfo`, but that makes the structure less general, so I am looking forward to some feedbacks. …

Add Certificate Table parsing and Authentihash support for PE

---

libr/core/cmd_eval.c
libr/io/io.c
test/new/db/cmd/cmd_env

Right now if you do `env     AAAA     =    BBBB` it will consider all the spaces, which I think is not right. Commands should not consider spaces, unless explicitly told so (e.g. in the new parser you can do things like `env "    AAAAAA    " = "    BBB"` if yoou really want to include spaces).
**Test plan**
There is a test in the changes, but you can also just do `env    AAA    =   BBB; env AAA` and check that `BBB` is the result.

Random fixes2

---

test/new/db/anal/sparc

#15563
Basic Sparc regressions tests.
Note: relates to [https://github.com/radareorg/radare2/issues/15602#issue-534934335](url) as I took two Sparc binaries from there.
Inspired by regressions tests found in anal/x86_32

Add initial sparc regression tests (#15602)

---

libr/flag/flag.c
test/unit/test_flags.c

This fixes a case where `r_flag_get_at()`/`fd` would return NULL/print nothing when there was a flag in a non-selected flagspace at exactly the query addr.
**Test plan**
```r2 -Qc "fs x; f test.x @ 0x42; fs y; f test.y @ 0x0; fd @ 0x42" -```
Before: nothing
After: `test.y + 66`

Fix Spaces Interference in r_flag_get_at()

---

libr/core/cmd_flag.c
test/new/db/cmd/cmd_flags
test/new/db/json/json2

This pull reuqests adds support for realname in the different `fd` subcommands. Now, if `asm.flags.real` is enabled, `fd` and `fd.` will show the flag's realname. In addition, `fdj` and `fd.j` are now showing `realname` if available.
In addition, this PR ports the json printing to the `pj` object.
**Test plan**
1. Open a binary and seek to an address with realname.
2. Use `fd` and see the flag is printed
3. Run `fdj` and see a list of all flags, including the relanme of each
4. Run `fd.j` and see that it works and shows the realname in addition to name
5. Enable `asm.flags.real`
6. Run `fd` and `fd.` and see that realname is displayed.
closes #16026

Support real names in "fd" command

---

libr/include/r_util/r_table.h
libr/util/table.c
test/unit/test_table.c

For any case where the new columns were not a bijection of the old ones, it would either leak (when columns were removed) or cause a double free later (when columns were duplicated). This fixes it and makes way more efficient as a nice side effect.
**Test plan**
Run the following examples with valgrind or asan:
`f,name/cols`
`f,name/cols/name`

Make r_table_columns() faster, leak- and double free free

---

libr/core/disasm.c

In some cases I noticed `str` is not correctly terminated, so when it is
later used in `pk_js`, that function reads a very long string, outside
of the memory bounds of the original buffer.
**Test plan**
I was able to trigger this while analyzing `cmake` and taking the function with the most bbs and doing `agfj function_name`.

Fix read stack-based buffer overflow when using str with pk_js

---

libr/bin/format/pe/pe.c

- [ X] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [ X] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [X ] I've added tests that prove my fix is effective or that my feature works (if possible)
- [X ] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
First off, I apologize for no tests atm. I can add later but it will take more time than the patch.
I noticed that `r2` will crash when loading a PE file with
Authenticode digest algorithm other than SHA-1 or MD5. I traced
it …

Fix segfault in Authenticode hash check (#16042)

---

libr/util/table.c
test/unit/test_table.c

Fix r_table_sort will seg fault if column type is NULL
* Do not sort if column type is NULL
* Rename argument to 'dec' (decreasing) to reflect existing output
* Add test
**Test plan**
* r_table_sort does not seg fault if column type is NULL

Fix r_table_sort if column type is NULL

---

libr/util/table.c
test/unit/test_table.c

r_table sort will not sort after the first call
- Force sorting of rows in the event of consecutive sort
- Remove global Gdec and use r_list_reverse for sort in decreasing order
Add test for r_table_tostring and r_table_sort
**Test plan**
Sort the same column in a table in decreasing order and followed by increasing order

Fix consecutive call to r_table_sort 

---

libr/core/canal.c

`minbound` and `maxbound` fields should be unsigned integers in `afij`. So use `pj_kn` instead of `pj_ki` to print.

Fix address representation minbound maxbound in afij

---

libr/bin/format/nxo/nxo.c
libr/bin/format/nxo/nxo.h
libr/bin/p/bin_nro.c
libr/bin/p/bin_nso.c
test/new/db/formats/nro
test/new/db/formats/nso

`readLE32()` didn't load explicitly as LE and these two functions are redundant too.

Minor Fixes and Tests for NSO/NRO

---

libr/core/cmd_anal.c
shlr/tcc/tcc.h
shlr/tcc/tccpp.c
test/new/db/cmd/types

Merging this Pull Request would allow setting function names containing dots in function signatures.
Current state of this PR is:
The current issue (addressed by the second milestone) now is that functions with dots don't get the function type and arguments correctly.
~~In order to fix this, we might need some kind of structure that annotates where the dots were replaced by underscores in the function name, so it can find the proper keys in SDB when querying it.~~. 
Fix functions not getting right arguments in a **new** issue and PR.
**Test plan**
Include a test that asserts if adding dots in the function name of a signature works as intended.
Closes https://github.com/radareorg/radare2/issues/15954

Implement function names with dots in signatures ##anal

---

libr/core/project.c

This tiny patch fixes a bug with how *projects* interact with *flagspaces*. With the `functions` flagspace specifically.
Normally, all flags are saved in the project `rc`-file under their respective flagspace, eg:
fs symbols
f ssl_sprintf_buf 1 0x6e727574 
f sprintf 1 0x80990556 
fs functions
f fcn.1c6f8 314 0x80c1c6f8 
fs strings
f str.SSL_Debug__secure_sock_clr_ctx__version____d 46 0x80c32f6e 
So there's that. However, since the `# functions` rc section comes **before** `# flags` section, and uses the `f` command too, an unintended (I believe) side-effect occurs: **`fcn.1234` flags migrate from `fs functions` to `fs *`** during save-exit-start-load cycle.
Consequences are subtle.
* User can get the impression that saving&reloading a project *loses functions*, by observing `functions` …

Preserve "functions" flagspace when saving projects

---

libr/bin/format/elf/elf.c

Previously when loading symbols from ELF file code was checking for duplicate symbols in two list by comparing every element in one list with every element in second list resulting in worst case O(n^2) complexity. Just opening a large file could easily take 10-15 minutes or more.
...
**Test plan**
Just having a large executable isn't enough (self extracting archive will not work) it needs to have many symbols in multiple lists.
I was locally testing using Blender executable from my distro which was ~70MB and had ~100k symbols in each list. Before changes it took ~15 minutes just to open it `r2 /usr/bin/blender` without any additional commands.  After changes it opened in a few seconds.
...
...

Replace O(n2) ELF symbol matching with hashmaps

---

libr/anal/meta.c
libr/cons/rgb.c
test/unit/meson.build
test/unit/test_cons.c

This fixes the broken color themes in Cutter and some read beyond the given string.
**Test plan**
* Use Cutter
* Run the added unit tests
Fix #16060

Fix r_cons_rgb_parse() harder

---

libr/core/cmd_anal.c
test/new/db/cmd/cmd_afv

**Test plan**
`r2 -c "afvr-*" -`

Fix null-deref on afv[rbs]-* without function

---

libr/util/table.c

Related to PR #16066. RTable could not handle ansi escape code in string
Before
Fix r_table_tostring that contain ansi escape
* Consider string may consist ansi
* Adjust alignment if there is ansi escape code 
* scr.color=0 is not affected
After
**Test plan**
Eyeball output from PR and master

Fix r_table_tostring for string with ansi escape code

---

libr/core/cmd_anal.c
test/new/db/cmd/cmd_afn

Before, when you renamed a function, you would get something like this:
The `fcn...` flag is useless at this point and you would have to manually delete it.
This pr automatically renames it, but only if the matching flag is in the "functions" namespace. Otherwise we might rename flags that could have another purpose, like for symbols. In such a case, a new flag is created.
I think that the entire flag setting code for functions should be refactored, maybe using REvent, but this patch is simple and clear and helps us define the desired behavior in the form of tests.
**Test plan**
see screenshot

Rename the Function Flag on afn

---

libr/include/r_io.h

This avoids warnings when writing a plugin in C++.

Make Strings in RIOPlugin const char *

---

shlr/windbg/windbg.c

`sizeof(rr)` gives pointer size.
But `windbg_read_reg()` and `r_debug_windbg_reg_read()` still look broken.

Fix bug in windbg_read_reg()

---

libr/core/cmd_anal.c
test/new/db/cmd/cmd_afn

`afn` would segfault if there is no flag at the function address
**Test plan**
run the test

Fix a null-deref in afn

---

libr/anal/p/anal_ppc_cs.c
test/new/db/esil/ppc_32

Unlike other analysis plugins, the PPC analysis (`libr/anal/p/anal_ppc_cs.c`) doesn't have a separate `analop_esil` function; instead, ESIL is unconditionally generated in the main `analop` function. Instead of refactoring the code and extracting out a separate `analop_esil` function, this PR just fixes the linked issue by discarding the generated ESIL (via a call to `r_strbuf_fini`) only if the corresponding mask bit isn't set.
**Test plan**
Added test case to db/esil/ppc_32 to verify ESIL statements longer than 30 characters are printed
closes #16102

Fix long PPC ESIL (#16102)

---

libr/core/disasm.c

My recent fix (#16102) uncovered a memory leak; `r_anal_op_fini` isn't called after printing disassembly.
**Test plan**
Ran radare2 under valgrind both before and after fix; before fix, there was one extra leaked block corresponding to the longer ESIL statement that required allocation for an `RStrBuf`.
closes #16113

Cleanup RAnalOp after disassembly (#16113)

---

libr/anal/p/anal_x86_cs.c

Although capstone3 does not provide a lot of features provided by capstone4, we should at least still be able to compile radare2 against capstone3, which may be shipped with some distros. Moreover, the access field was already protected with an `#if CS_MAJOR >= 4` few lines below.

Fix compilation with capstone3

---

libr/anal/flirt.c
libr/include/r_anal.h

Remove RAnalFunction.locs

---

libr/anal/fcn.c
libr/include/r_anal.h

This `cmdtail` us an ugly hack, we should move away from it. Since there aren't too many places where it is used, this shouldn't be too hard.
`r_anal_case()` was one of the places, but it has been dead code since 2018: adaf135dc66d3004237aed9b857da65d62e77190

Deprecate cmdtail and kill r_anal_case()

---

libr/core/cfile.c
libr/core/cmd_open.c
libr/debug/p/native/linux/linux_debug.c
test/new/db/archos/linux-x64/dbg_oo

This PR focuses on the Linux native debugger.
1. In `ood`, `r_core_file_reopen_debug` sends a kill signal to the current child process/debuggee, but it is stopped so it does not terminate. As a result, calling the next `r_debug_continue` would receive the child killed signal instead of continuing the new process.
2. r2 will attach to the process every time `cfg.debug` is set to true due to its callback. If `ood` is used during an active debug session and the process terminated, calling `r_config_set_i (core->config, "cfg.debug", true)` before `r_core_file_reopen` will attach to the terminated process pid again and cause `PT_ATTACH failed`.
3. When the process terminated, it does not free the `dbg->threads`, using `ood; dc` …

Fix file reopen in debug mode ood/doo

---

libr/bin/mangling/microsoft_demangle.c

Memory fix on error path on win mangled named handling ##bin

---

test/new/db/cmd/cmd_project

All the tests were concurrently writing to the same filenames, which is how the non-deterministic breakage occurred.

Fix some Projects Tests

---

libr/anal/block.c
libr/anal/p/anal_java.c
libr/anal/switch.c
libr/include/r_anal.h
test/unit/test_anal_block.c

Previous declaration was
```RAnalSwitchOp *r_anal_switch_op_new(ut64 addr, ut64 min_val, ut64 max_val);```
but with the definition
```RAnalSwitchOp *r_anal_switch_op_new(ut64 addr, ut64 min_val, ut64 def_val)```
and `def_val` was just ignored and everything set to `min_val` 🤯

Fix r_anal_switch_op_new() args

---

libr/asm/p/asm_tricore.c

Before, Cpu type was default to Rider-B when disassembling an instruction via rasm2
We have the option -c for cpu type that we can use for Tricore variant ISA.
Added support to get the cpu type argument for Tricore arch.
...
**Test plan**
...
#15912 
...

Support for Tricore cpu type argument

---

libr/anal/fcn.c
test/new/db/cmd/types

afs was not showing return type and arguments for preloaded functions that start with sym.imp. This Pull Request fixes this.
**Test plan**
Write a test that shows the output of afs on a preloaded function signature, like sym.imp.puts.
...

Fix afs not showing signatures correctly with preloaded sdb types ##types

---

test/unit/test_debug.c

Add test to verify size and offset of user_fpregs_struct field for linux x64

Add test to verify fpu and xmm register size and offset for linux x64 

---

libr/core/cmd.c
test/new/db/cmd/feat_grep
test/new/db/tools/radiff2

Grep specifiers (the part after `~`) can accept a lot of characters.
However, some of those have a special meaning in some contexts and they
should be parsed for better consistency.
For example, `(` and `)` can have particular meanings inside a macro
definition and it's important to allow escaping to differentiate:
`(foo; pd~hello))` -> parsing error, there are 2 closing parenthesis
`(foo; pd~hello\))` -> user wants to grep for string 'hello)'
**Test plan**
Check whether r2r tests pass and play a bit with grep commands.

Introduce escaping in grep specifiers

---

libr/core/cmd_debug.c

- A negative RRegType is a hack used in linux_reg_read() to print fpu/xmm registers. This is not required for `drm` since it uses r_debug_reg_list() to print 
https://github.com/radareorg/radare2/blob/c1c54be39e3dc61367d5d08ab87bf11623fe8355/libr/debug/p/native/linux/linux_debug.c#L978-L986
- This hack is still required for `drf`
**Test plan**
Existing drm test in should not fail

Fix RRegisterType sign for drm command

---

libr/core/cmd.c

Fixes compilation when `-Duse_treesitter=true` is used.
closes https://github.com/radareorg/radare2/issues/16196

Fix compilation with tree-sitter support

---

libr/io/p/io_gzip.c
libr/io/p/io_malloc.c
libr/io/p/io_mmap.c

Returning -1 in a function with bool as return type is the same as returning
true. This is not the intended behaviour when e.g. allocation fails.
If allocation fails, the functions should return false to indicate error. However, returning -1 in a boolean function is the same as returning true (since everything that is non-zero is true).
...
**Test plan**
...
...

Fix wrong return value in error path

---

libr/core/cconfig.c

Changed _architecgture_ in the last line to _architecture_.

Fixed a minor spelling mistake in the output of e??anal in cconfig.c

---

libr/core/cmd_debug.c

* `drx` before 
```
[0x7fcc122ba100]> dr?~drx
| drx[?]                 Show all debug registers
| drx idx addr len perm  Modify hardware breakpoint
| drx-number             Clear hardware breakpoint
[0x7fcc122ba100]> drx?
Usage: drx   Hardware breakpoints commands
| drx                                      List all (x86?) hardware breakpoints
| drx <number> <address> <length> <perms>  Modify hardware breakpoint
| drx-<number>                             Clear hardware breakpoint
[0x7fcc122ba100]> 
```
* `drx` after 
```
[0x7f33d7dc8100]> dr?~drx
| drx[?]               Show debug registers
[0x7f33d7dc8100]> drx?
Usage: drx   Hardware breakpoints commands
| drx                                      List all (x86?) hardware …
```

Clean drx/drt/drp help message

---

libr/anal/p/anal_x86_cs.c
libr/core/cmd.c
libr/core/cmd_debug.c
libr/core/cmd_search_rop.c
libr/debug/dreg.c
libr/reg/reg.c
test/new/db/cmd/cmd_repeats
test/unit/test_reg.c

* Several register profiles use `@` for register type indirection
```
$ grep -IR "xmm@" libr/* | grep xmm0
libr/anal/p/anal_x86_cs.c:               "xmm@fpu    xmm0  .64 160  4\n"
libr/debug/p/native/reg/windows-x86.h:"xmm@gpr  xmm0    .128    364     0\n"
libr/debug/p/native/linux/reg/linux-x64.h:"xmm@fpu    xmm0    .128      160 16\n"
```
* This PR implement register type indirection in r_reg_get_list() using type mask
* Remove forced type indirection search from r_debug_reg_list() and `@@@r`  
**Test plan**
* Added unit test for register type indirection should pass
* Added @@@r test should pass

Make r_reg_get_list() search harder 

---

libr/util/table.c

Returning without calling `va_end()` after `va_start()` has been called is undefined behaviour. 
...
**Test plan**
...
...

Add missing calls to va_end()

---

libr/core/cfile.c
libr/core/cmd_open.c
test/new/db/archos/linux-x64/dbg_aslr

PR #16131 broke debug rebase by changing the order in which cfg.debug was set, causing r_core_file_reopen to treat the debugee as a regular file and skip the baseaddr calculation.
Working on improving `rb` to add rebase tests.
**Test plan**
Execute `ood` and see that xrefs, breakpoints, functions, vars and flags are properly rebased.
closes #16159

Fix debug rebase regressions

---

libr/socket/socket.c

PR #16073 exposed that the linux implementation of r_socket_is_connected returned -1 from recv with errno set to EAGAIN. This broke gdbr and probably other remote capabilities since r_socket_connect would fail. I switched the implementation to getsockopt which is more reliable instead of playing with non blocking settings.
Windows doesn't have this issue.
**Test plan**
Connect to gdbserver with `oodf gdb://ip:port` and see that it didn't fail.

Fix socket connection issue

---

libr/core/cmd_anal.c
test/new/db/anal/x86_32

Segmentation fault when `adf` is used without analysis
**Test plan**
- Should not seg fault when using `adf` without analysis
Closes #16215

Fix segfault in adf 

---

libr/anal/sign.c
libr/core/cmd_zign.c

issues in here:
* array of types contain strings that are not types
* contains quotes
* doesnt uses PJ
```
"types": [
"func.main.ret=int",
"func.main.args=2",
"func.main.arg.0=\"int,argc\"",
"func.main.arg.1=\"char **,argv\""
],
```

Fix #16231 - zj incorrect json

---

libr/core/linux_heap_glibc.c
test/new/db/archos/linux-x64/cmd_dmh

- `dmh` was broken because it uses a hardcoded offset from dbg.glibc.fc_offset
- This PR use tcache chunk size to find the next chunk
- Please do not close yet. There are several other places that uses fc_offset that I would like to fix in this PR
```
$ grep -IR fc_offset libr/*
libr/core/cconfig.c:    SETI ("dbg.glibc.fc_offset", 0x00240, "First chunk offset from brk_start");
libr/core/cconfig.c:    SETI ("dbg.glibc.fc_offset", 0x148, "First chunk offset from brk_start");
libr/core/linux_heap_glibc.c:           const int fc_offset = r_config_get_i (core->config, "dbg.glibc.fc_offset");
libr/core/linux_heap_glibc.c:           initial_brk = ( (brk_start >> 12) << 12 ) + fc_offset;
libr/core/linux_heap_glibc.c:   const int …
```

Fix chunk listing with tcache

---

libr/core/cmd_info.c

- [x ] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
So I've noticed some weird input on id? and idp? commands (id? give incomplete output and idp? gives nothing) so I had a look into cmd_info.c, looked into the state machine and it didn't make sense, because the handling of ? there should print something else, but it didn't even get executed.
Then I noticed that there is handling of commands that have '?' in them right before the state machine starts, problem is that command only uses "help_msg_i" array and id... command info is inside "help_msg_id", second problem was it takes only last char that it appends to the 'i', so "idp?" would result in search for commands …

Idea for fixing id? and idp? etc commands

---

test/unit/minunit.h

Many of the minunit macros used in unit tests were using the arguments multiple time, thus in case the argument of the macro is not a variable but a function call, the function would be called two times.
**Test plan**
Existing tests should still work.

Fix minunit.h to compute macro arguments just one time

---

.github/workflows/coverity-scan.yml

Makes the coverity scan neither download of the Coverity Build Tool nor
execute any of the following steps for forked repositories, avoiding
sending GitHub alerts to those repo owners.
- [N/A] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [N/A] I've added tests that prove my fix is effective or that my feature works (if possible), **but I tested it on forked repo.**
- [N/A] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
Forked radare2 repo owners receive e-mails from the execution of the coverity GitHub action, because those repositories can't download …

Fix coverity-scan GitHub Action for forked repos

---

libr/core/cmd_zign.c
libr/include/r_util/pj.h
libr/util/pj.c

not sure if it will be better to print raw data as an array of numbers like [2,34,32,159,..] and just keep that string function as is, with null terminated strings only.
another option would be to have another api for non-null terminated strings

Add pj_r api to print raw data

---

libr/core/cmd_magic.c

PR related to #16264
Simple example with global counting.
```
[0x0000000]> /m
-- 0 8e6fe4
0x0051345 [5 matches found]
```

Add first version of /m search with hits

---

libr/core/cmd_anal.c
test/new/db/cmd/cmd_an

Avoids some of the problems with command injection.
For "an" command implementation use r2 api functions directly instead of building a command string and evaluating it using r2 shell.
Reduces problems with command injection.
**Test plan**
* run "an name" on an instruction where referenced address has no flag -> create flag
* run "an name" on an instruction where referenced address has  flag -> rename flag
* run "an name" on function call instruction -> rename function
...
...

Don't use r2 shell commands to implemnt an.

---

libr/main/radare2.c

This enables multiline scripts in `-c`. Before, it kind of worked, but sometimes did weird stuff (see example below)
**Test plan**
Run r2 with the following multiline arg:
```
r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc "
e asm.bits=64
wx ff2572962100   
af             
pdf~jmp[0]
afi~size[1]" malloc://1024
```
Result before (wrong):
```
\ 0x00000000
size: 6
```
Result after (right):
```
\
6
```

Use r_core_cmd_lines() for -c

---

test/new/db/cmd/cmd_pd_bytes
test/new/db/cmd/metadata

- `asm.linesup` has been removed in 932ba399785d3e488aed2eeb92ee0b0d2c9a9d3c
- This PR remove any several `asm.linesup` configuration in test

Remove asm.linesup in test

---

libr/core/rtr.c

The segmentation fault was caused when the user inputs `=+`, which calls the `r_core_rtr_add(..)` function in `../libr/core/rtc.c`. 
Since the host and port weren't specified, the `port` variable was set to `"80"`.
`r_str_trim (port)` was called later in the function, which was causing the segmentation fault. To be specific, `r_str_trim(...)` calls `r_str_trim_head(...)` which calls `memmove(...)` which was causing the segmentation fault.
I'm not really sure why it is causing a crash yet, but moving the r_str_trim to a more relevant if-else branch solved the problem.
**Test plan**
...
closes #16214

Fixes #16214

---

libr/core/cconfig.c
libr/core/linux_heap_glibc.c
libr/include/r_heap_glibc.h
test/new/db/archos/linux-x64/dbg_dmh

Related to PR #16239, `dmht` does not show freed tcache chunk  due to wrong tcache size and definition. 
...
**Test plan**
- Result has been compared with gdb-gef
- Pass added test

Fix dmht for glibc caused by wrong tcache offset and definition

---

binr/r2r/load.c
binr/r2r/r2r.c
binr/r2r/run.c
libr/main/rabin2.c
test/new/db/tools/r2
test/new/db/tools/r2r
test/new/db/tools/rabin2
test/new/db/tools/ragg2
test/new/db/tools/rahash2
test/new/db/tools/rasm2
test/new/db/tools/rax2

see commit descriptions for info.
r2r-c reads a string specified without `<<EOF` syntax like `EXPECT_ERR=Missing file.` as `"Missing file."` without a trailing newline while r2r.js doesn't seem to care at all. So I had to change these to use `<<EOF` instead.

R2R in C Enhancements

---

libr/core/disasm.c

Reproducer:
```
r2 -N -Qc 'e scr.interactive=1; e scr.null=1; Vprdfq' ../bins/mach0/arm-or-thumb
```
In fact, this is part of this test:
https://github.com/radareorg/radare2/blob/master/test/new/db/anal/arm#L173-L176
I have no clue how this can be successful in current r2rs.

Fix a null deref in ds_print_relocs()

---

libr/core/cmd_info.c
libr/include/r_util/r_str.h
libr/util/str.c
test/new/db/archos/darwin-x64/cmd_i
test/new/db/archos/linux-x64/cmd_i

This test was a bit hard to fix. It seems like r2r.js and v check r2's output only after interpreting it as utf-8, effectively cleaning up broken encoding to a certain degree. This meant here that the bytes in `db/archos/*-x64/cmd_i` did not actually match the bytes outputted by r2.
I think it makes more sense for r2 to only output valid utf-8, so if something is broken in the filename, it should escape it. But if it's valid utf-8, we still want to print it normally, which is what `r_str_escape_utf8_keep_printable()` does here.

Escape broken UTF-8 in Filename

---

libr/core/cmd_type.c

* Change a condition returning always true even when it shouldn't
* Correct typos in tc help
Segmentation fault when using `tc struct`. The expected command looks like `tc struct.foo`.
**Test plan**
`tc struct` should not triggers a segmentation fault.
Closes #16336.

Fix #16336 - Correct a segfault

---

libr/anal/p/anal_arm_cs.c

Tweak the esil expression for arm64 LDR in a way that makes the local variable access detection work.
This fixes an issue with detection of local variable usages.
Disasm before:
```
str wzr, [sp + var_c40h]
ldr x8, [sp, 0x3a8]
```
Disasm after:
```
str wzr, [sp + var_c40h]
ldr x8, [sp + var_c08h]
```
The reason is very unfortunate. Apparently the `extract_arg()` function in var.c assumes a specific structure of the ESIL code (https://github.com/radareorg/radare2/blob/master/libr/anal/var.c#L655).
Therefore, this pull request just tweaks the ESIL code of the LDR variant of interest in order to conform the ESIL expression to the expected structure, even if it was already mathematically correct.
Generated ESIL before:
``` …
```

Tweak arm64 ldr ESIL for var access ##anal

---

binr/r2r/r2r.c

Implement automatic test directory for r2r

---

libr/anal/p/anal_6502.c

While running tests with ASAN enabled, there was a read OOB when running `-A` on a rom. `_6502_op` should check `len` before accessing `data` to be sure there are enough bytes in the data array.

Fix a read out-of-bounds error by checking if there is enough data

---

binr/r2r/run.c

This was the cause that some tests got stuck.

Drop empty args in r2r

---

libr/core/vmenus.c

I've noticed a segfault due StackOverflow because of a recursion https://github.com/radareorg/radare2/blob/master/libr/core/vmenus.c#L1138 
I was digging around it and then saw that Pancake already hot-fixed part of this 9 days ago, but only the part for classes, the methods and fields still had the segfaulting recursion, so I've mimicked the fix for now.
To replicate, just open a binary that has an object and a some methods to them, then just
```
Vbc
// pick a class to show methods
// grep anything that matches nothing, for example:
/asdasdas 
```

hotfix of recursion stack overflow in Vbc/

---

libr/include/r_util/r_str.h
libr/util/str.c
test/unit/test_str.c

This is needed because Windows processes do not receive an array of arguments like on unix but only a single string which is then split by the called program. So to call a subprocess which should get exactly the argv we want, this formatter is needed.
Reference:
http://daviddeley.com/autohotkey/parameters/parameters.htm#WINCRULES
https://docs.microsoft.com/en-us/cpp/cpp/main-function-command-line-args?redirectedfrom=MSDN&view=vs-2019#parsing-c-command-line-arguments
**Test plan**
run the tests

Add Windows argv Formatting

---

libr/core/cmd_type.c

Commands `tp` and `tpx` were not prepared to accept types like "char *". This Pull Request changes that behavior.
**Test plan**
Write a test using the `tp` command with `char *` as the first argument.
Closes https://github.com/radareorg/radare2/issues/16195.

Fix tp and tpx to accept types with spaces ##types

---

libr/anal/flirt.c
libr/io/p/io_default.c
libr/io/p/io_ihex.c
libr/io/p/io_mmap.c
libr/io/p/io_sparse.c
libr/io/p/io_zip.c
libr/util/buf.c

This allows to use r_buf_read/r_buf_write to read/write sequentially but
at the same time having random reads/writes in the buffer if needed,
without the need to save/restore the seek every time.
Sometimes you may want to use the sequential API like `r_buf_read`/`r_buf_write` but you may also need to read/write in random places (e.g. in bin_dex.c). This makes sure that the read_at/write_at APIs restore the original seek after reading/writing data.
**Test plan**
Everything should still work as usual.

r_buffer: do not move seek when using _at APIs

---

libr/core/cmd.c
libr/core/cmd_type.c
libr/reg/arena.c
test/unit/test_str.c

Some code still uses pointers to mess with strings where we can use generic r_util apis.
**Test plan**
we have no tests for this in test/unit
none

 Use r_str_trim_head_ro instead of hacky while loops

---

libr/bin/bin.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_pe.inc
libr/core/vmenus.c
libr/include/r_util/r_buf.h
libr/util/buf.c
libr/util/buf_bytes.c
libr/util/buf_file.c
libr/util/buf_io.c
libr/util/buf_mmap.c
libr/util/buf_ref.c
libr/util/buf_sparse.c

* Fix two memleaks in the dex parser
Loading DEX files is slow for several reasons, most of them described, with their proposed solutions in https://github.com/radareorg/radare2/issues/16387
This PR just make RBuffer.data() cache the contents to avoid having to re-read, alloc and copy everytime this is called, which in the case of DEX is a lot of times. I know its a bad practice to use this API, and even more when used with the IO backend. but there are at least 3 bin plugins using it right now and i think it's worth the simple fix.
As I said, it will be good to add a new API `r_buf_data_cache` and use it with this behaviour to avoid surprises in the case the backend changes the data and the frontend can't be updated …

Do not use r_buf_data in DEX results in 1.5x faster parsing (22s vs 33s) ##bin

---

libr/core/canal.c
test/new/db/anal/mips
test/new/db/formats/elf/helloworld-gcc-elf

run af on each UJMP/UCALL spotted when doing esil emulation to find out the register value
**Test plan**
see the test
fixes #16423

Fix #16413 - Analyze code refs spotted with aae ##anal

---

libr/util/lib.c

read the issue
**Test plan**
install a plugin for 4.3.0 and use r2 4.3.1 and get no warnings
the #13626
...

Fix #13626 - Only check for major and minor version numbers when loading plugins #core

---

libr/cons/grep.c
libr/util/json_indent.c

see the issue
**Test plan**
see the issue
see the issue

Fix #16233 - ~{} works on colorized JSONs ##json

---

libr/core/libs.c

see the issue
**Test plan**
complicated and boring to test in the CI
yes

Fix #16281 - Do not load system-wide plugins twice ##core

---

libr/core/disasm.c
test/new/db/cmd/cmd_pd

This pull request will fix a problem in which the printed function signature did not honor the config `asm.flags.real`. 
In the following examples, notice how the name of the function changes from `sym.beet` to `beet` before and after the fix when `asm.flags.real` enabled.
**Before:**
```
[0x08048585]> e asm.flags.real=true
[0x08048585]> 
[0x08048585]> pdf
; CALL XREF from main @ 0x8048637
;-- eip:
╭ 112: sym.beet (char *src);
│           ; var char *s2 @ ebp-0x92
│           ; var int32_t var_8eh @ ebp-0x8e
│           ; var int32_t var_8ah @ ebp-0x8a
│           ; var char *dest @ ebp-0x88
│           ; arg char *src @ ebp+0x8
│           0x08048585      55             push ebp
│           0x08048586      89e5 …
```

Show realnames on function's signature when enabled

---

libr/bin/p/bin_elf.inc
libr/bin/p/bin_mach0.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/core/cmd_open.c
libr/core/cmd_search.c
libr/core/linux_heap_glibc.c
libr/core/visual.c
libr/include/r_io.h
libr/include/r_vector.h
libr/io/desc.c
libr/io/io.c
libr/io/map.c

Replace the SdbList of RIO.maps by an RPVector for better cache-friendliness in #14024.
Of course this does not change the `O(n^2)` complexity in that test but at least removes the linked list overhead. There are many other places where this list is linearly iterated, so using a vector is a good choice.
RVector instead of RPVector would be even better, but then the pointers wouldn't be stable anymore.
**Test plan**
Run the `db/formats/pe/65535sects` test.
Before: 26s
After: 15s
**Related issues**
#14024

Use RPVector for io->maps

---

libr/main/rasm2.c

the memmove was using strlen(x) when it was copying from x+2
**Test plan**
wait for travis+asan
yep the #16436

Fix #16436 - OOBREAD in argv with rasm2 -E

---

binr/r2r/load.c
binr/r2r/r2r.c
binr/r2r/r2r.h
binr/r2r/run.c
libr/include/r_util/r_file.h
libr/util/file.c
test/Makefile

Usage: `r2r -F bins/fuzzed @fuzz` or `make fuzz-tests` in `test/`
Unfortunately it is currently necessary to manually pass the path to the tests since we only search for `db` and going from db to the fuzz tests automatically would be `../bins/fuzzed` which seems very dirty to me.
There are still many segfaulting files there so this should be fixed before going in the CI.

Run Fuzz Tests with r2r

---

libr/bin/p/bin_dyldcache.c

This allows to open dyld cache files from iOS 13.4 for which apparently the accelerator info are missing.
What’s lost when this info is missing is the ability to efficiently detect which single library depends on which other libs when performing the filtering.
That means that for iOS 13.4 library caches, the user has to manually specify all the dependencies in the filter.

Make dyldcache accelerator info optional ##bin

---

libr/core/cmd.c
libr/core/cmd_open.c

This oneliner still segfaults:
$ r2 -c "ocm'@@@f:sym*" /bin/ls
Fix crash because the core is recreated and all the references are broken, so anything that can call ocm' can lead to a crash. which is really painful to do. but will improve overall stability
**Test plan**
* ocm'@@@i
* ocm'@@@S
* ocm'@@@b
do we want tests for those?
#16305
...

Fix #16305 - UAF in @@@{r,i,s,S,b} as well as add some help for `oc`

---

.github/workflows/pr.yaml
.travis.yml

It may be useful from time to time to see the results of Travis jobs in PRs too.
These are the rules:
- if the branch name starts with `s390x-`, the S390X travis job is run
- if the branch name starts with `wasm-`, the WASM travis job is run
- if the branch name starts with `ppc64-`, the PPC64 travis job is run
- if the branch name starts with `arm64-`, the ARM64 travis job is run

Allow to run travis jobs if special branch names are used

---

binr/rafind2/rafind2.c
libr/core/cmd_write.c
test/new/db/cmd/cmd_wfs

wfs listens in the given port to read N bytes, then it writes them in the current offset
the old wfs is now named wfx
**Test plan**
we need to run multiple r2 and comunicate them, or do some nc and task magics. not in the mood now
the #14371

Fix #14371 - Make wfs paired with wts, rename wfs to wfx ##io

---

libr/core/cio.c
libr/core/cmd_write.c
libr/include/r_core.h
test/new/db/cmd/write

just read the
**Test plan**
modifying in disk files is a bit tricky and boring, not going to add tests now for this we have more unit tests to add before this imho
the #16210  one

Fix #16210 - Show error message and update help for `we` ##io

---

binr/r2r/load.c
binr/r2r/r2r.c
binr/r2r/r2r.h

The final nail in r2r.js' coffin.
Fixes https://github.com/radareorg/radare2/issues/15662

Add interactive mode to r2r

---

libr/bin/format/elf/elf.c
test/new/db/formats/elf/reloc

I start working on the dynamic section, the ir command found all the relocations. I don't know why the pd 15 command doesn't use all the relocs (new/db/formats/elf/reloc). I used readelf to test the relocation. Maybe later we could move the struct dynamic_relocation_section in the struct ELFOBJ?
**Test plan**
```
ir
```
#12732

When computing relocations, use DYNAMIC segment if available

---

libr/bin/format/coff/coff_specs.h
libr/bin/p/bin_coff.c
test/new/db/formats/coff

1. Now plugin fills symbol visibility info (`bind` field) based on its class value.
2. Fixed imports detection logic (symbol is marked as imported if its section number value is 0).
3. Fixed function detection logic. Now plugin uses symbols's derived type value for this.

Fix COFF symbols/imports info

---

libr/core/cbin.c

A small fix to remove a debug message printed on `ii`
Before:
```
[0x08048370]> ii
nth: 1, strcmp
nth: 2, strcpy
nth: 3, puts
nth: 4, __gmon_start__
nth: 5, __libc_start_main
[Imports]
nth vaddr      bind   type   lib name
―――――――――――――――――――――――――――――――――――――
1   0x08048320 GLOBAL FUNC       strcmp
2   0x08048330 GLOBAL FUNC       strcpy
3   0x08048340 GLOBAL FUNC       puts
4   0x00000000 WEAK   NOTYPE     __gmon_start__
5   0x08048350 GLOBAL FUNC       __libc_start_main
```
After:
```
[0x08048370]> ii
[Imports]
nth vaddr      bind   type   lib name
―――――――――――――――――――――――――――――――――――――
1   0x08048320 GLOBAL FUNC       strcmp
2   0x08048330 GLOBAL FUNC       strcpy
3   0x08048340 GLOBAL FUNC       puts
4   0x00000000 WEAK …
```

Remove debug leftovers in cbin

---

libr/util/str.c

Do not print additional newline in `-v` output.
Before this PR it added one more newline:
```
radare2 on  fix-version-nl took 7s 
[i] ℤ r2 -v                                                                                                                                                                                                                        18:24:11 
radare2 4.4.0-git 26469 @ linux-x86-64 git.4.3.1-256-g871b68bb8
commit: 871b68bb8c9031c9df42f2fdb1b2cd528628476f build: 2020-04-09__18:16:32
radare2 on  fix-version-nl 
```
Obviously, it's unnecessary

Remove unnecessary newline in version

---

libr/core/cmd_search.c

The condition im removing here doesnt make any sense and this issue is affecting r2frida and native debugger as well
**Test plan**
cant write test because -m is broken ,the phisical files are always bound to 0, we can no longer map files outside that address, so unless we do a modified malloc that covers all memory or gets mapped in a higher address
the #16327

Fix #16327 - Search in range with io.va=false ##search

---

libr/core/cmd_anal.c

running aaaa on the fuzzed bin described in the issue results in esil assert. this patch fixes it
**Test plan**
read the description. its probably something listed in the fuzzed tests failing
read the issue title

Fix #15165 - Assert in empty esil string for ARC emulation

---

libr/core/cbin.c
test/new/db/formats/elf/crash

listing imports on ld-uclibc results on 1 entry which is filled by zeros. maybe t shouldnt be there, but in case is there it shouldnt be asserting because of null strings.
**Test plan**
i added a test which shows the current output
fixes #16455

Fix #16455 - iij asserts for ld-uclibc with a null import ##bin

---

libr/asm/asm.c
libr/include/r_types.h

should fix the problems in travis-s390x related to setting the endianness because there's no such arch if it's not in the .h.
**Test plan**
wait for travis
#16109

Fix #16109 - Add R_SYS_ARCH for s390x ##ports

---

libr/asm/p/asm_x86_nz.c
test/new/db/asm/x86_64

This pr adds support for the `movabs` instruction, equivalent to the x86_64 MOV r64, imm64 instruction (opcode B8+ rd). This is consistent with both capstone (via the tests) and objdump:
`objdump -D -b binary -m i386:x86-64 -M intel ./testbin`
**Test plan**
Closes #16433.

Fix #16433 - Support movabs for x86_64's MOV r64, imm64

---

libr/core/cmd_debug.c
test/new/db/cmd/cmd_dr

Don't use color codes in JSON mode. There was code that tried to disable it but parts of it were still printed. While making the changes also fix:
* Changed value highlighting in the human readable mode. When a register which didn't need highlighting was  reached color got overwritten with empty preventing further registers from being highlighted.
* fix memory leak when handling `rrstr`
**Test plan**
* There is a test for json mode
Does color printing in human readable mode also need test case. How to specify the color codes in r2r?

Don't use colors in json mode and fix some bugs.

---

libr/anal/function.c
test/new/db/anal/x86_64
test/new/db/cmd/cmd_af
test/new/db/cmd/cmd_zignature

This fixes the following issue:
```
$ r2 /bin/ls
> af;.afi*
> af;.afi*
> af;.afi*
```
or more narrowed down:
```
[0x00000000]> af+ 0x1337 func
[0x00000000]> af+ 0x1337 func
Invalid function name 'func' at 0x00001337
Cannot add function (duplicated)
[0x00000000]> af+ 0x1337 func
[0x00000000]> af+ 0x1337 func
Invalid function name 'func' at 0x00001337
Cannot add function (duplicated)
[0x00000000]>
```
The expected behavior is that all subsequent `af+` calls show the error.
This is however not only about error printing, in fact the duplicated `af+` would remove the function from the address and name hashtables which is a problem.
#15453 (doesn't directly solve the project-related issue but I think we can close with r2db coming soon^TM)

Fix dup af+ removing function from hts

---

libr/include/r_util/pj.h
libr/include/r_util/r_table.h

Add some ifdef cplusplus extern c to headers. There are quite a few left.
```
[karlis@desktop1 libr]$ grep -r -L "extern" . | grep "\.h" | wc -l
255
[karlis@desktop1 libr]$ grep -r  "extern" . | grep "\.h" | wc -l
1508
```
For now only fixed the ones  causing r2ghidra compilation problems on windows.
**Test plan**

Add some extern C to headers.

---

libr/bin/format/mach0/mach0.c

fixes another fufzz test
**Test plan**
run the fuzzz tests
yes

Fix crash issue induced by an integer overflow in the mach0 parser ##bin

---

libr/anal/xrefs.c
libr/include/r_anal.h
test/unit/meson.build
test/unit/test_anal_xrefs.c

About `r_anal_xrefs_set()`:
I need to be able to use this to test RAnal without having to set up RIO.
About `r_anal_xrefs_count()`:
When you have the following xrefs:
0x42 -> 1234
0x42 -> 4567
0x1337 -> 123456
`r_anal_xrefs_count()` should return 3, but before it was 2.
**Test plan**
see the unit test

Minor Fixes for XRefs

---

libr/anal/meson.build
libr/anal/p/Makefile
libr/anal/p/anal_tricore.c
libr/anal/p/tricore.mk
libr/asm/arch/tricore/README.md
libr/include/r_anal.h
libr/meson.build
plugins.def.cfg
test/new/db/anal/tricore

Added tricore register profile support.
Still works need to be done in giving alias to some special registers.
The 64 bit case is due to, tricore for arguments size 64 uses E[0] or (d[0]/d[1]) data registers. Same for address registers.
Also added some documentation links for tricore in asm README. Just tell me if we want this at different place. I will add more clarity to it.
```[0x80000000]> drp
=PC	pc
=SP	a10
gpr	a0	.32	0	0
gpr	a1	.32	32	0
gpr	a2	.32	64	0
gpr	a3	.32	96	0
gpr	a4	.32	128	0
gpr	a5	.32	160	0
gpr	a6	.32	192	0
gpr	a7	.32	224	0
gpr	a8	.32	256	0
gpr	a9	.32	288	0
gpr	a10	.32	320	0
gpr	a11	.32	352	0
gpr	a12	.32	384	0
gpr	a13	.32	416	0
gpr	a14	.32	448	0
gpr	a15	.32	480	0
gpr	d0	.32	512	0
gpr	d1	.32	544	0
gpr	d2	.32 …
```

Tricore analysis support.

---

libr/asm/p/asm_x86_nz.c
test/new/db/asm/x86_64

This pr makes the x86_64 assembler use the shorter MOV C7 encoding (MOV r/m64, imm32) when the immediate is between -1 and -0x80000000.
**Test plan**
For https://github.com/radareorg/radare2/issues/16433#issuecomment-612592213.

x86_64: Use MOV opcode C7 for MOV r64, -<1 to 0x80000000>

---

libr/include/r_vector.h

if the for loop starts at count 0, we have UB from pointer overflow
there was a pointer overflow if the count was 0, in the count-1 is pointer overflow in `r_pvector_foreach_prev`
...
**Test plan**
run r2r, same results
...
closes #16550
...

fix undefined behavior in r_pvector_foreach_prev

---

libr/core/core.c

In `bool chgdir = !strncmp (str, "cd  ", 3);` the string literal passed has a length of 4 but the size argument passed is 3.
I believe this is a typo in the string literal and it should be `"cd "` instead of `"cd  "` (note the two spaces).

Fix wrong string literal in core.c

---

libr/bin/p/bin_bflt.c

Even `a * 4 >= a`, the multiplication may still overflow.
Eg: `a = 0x58000000, a * 4 = 0x60000000`
Instead, we should use division to test whether a*b overflows.
**Test plan**
...
...

Proper multiplication overflow test

---

libr/asm/p/asm_bf.c

The `strncmp` calls with `"in"` and `"out"` string literals seems to have wrong size argument passed. This PR fixes it.

Fix off by one errors in asm_bf

---

libr/core/cmd_info.c

The string literal "zzz" has a length of 3 so the `strcnmp` used should have size argument of 3 instead of 2.

Fix off by one when checking for "zzz"

---

libr/io/p/io_winedbg.c

The string literal `"dr*"` has a length of 3 so the strncmp used should have size argument of 3 instead of 2.
PS: I am not sure if this fix is correct but it seems so. If it is not, please close this PR. However, if the fix is incorrect it seems there could be some bug as next `else if` checks for `"dr"` too.

Fix off by one in "dr*" matching

---

libr/bin/format/mdmp/mdmp_pe.c

The string literal `".rdata"` has a length of 6 so the `strncmp` used should have size argument of 6 instead of 5.

Fix off by one when checkinf for .rdata section

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_64

I've confirmed https://github.com/radareorg/radare2/issues/16433#issuecomment-612592213 (including the nasm `rax` -> `eax` bug) and thus this pr makes the x86_64 assembler use the MOV B8+ encoding (MOV r64, imm64) when the immediate is between 0x80000000 and 0xffffffff for both:
1. Consistency with GNU assembler.
1. It actually does seem to be the expected encoding.
This does mean that `mov eax, 0xffffffff` and `mov rax, 0xffffffff` will have very different semantics.
**Test plan**
GitHub Actions and AppVeyor are green.
Closes #16433.

Fix #16433 - Use MOV opcode B8+ for MOV r64, <0x80000000 to 0xffffffff>

---

libr/anal/var.c
libr/core/anal_tp.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_core.h
libr/include/r_parse.h
libr/parse/p/parse_arm_pseudo.c
libr/parse/p/parse_mips_pseudo.c
libr/parse/p/parse_x86_pseudo.c

This should probably be merged only AFTER the release.
`RAnalVar.addr` was always set to the function's addr. No need to keep it there. Especially as a preparation for #16547.
**Test plan**
Check that rebasing of variables still works (Open file, `aaa`, `ood`, check vars)

Remove some useless members from RAnalVar

---

.github/workflows/ci.yaml
.github/workflows/newshell.yml
.github/workflows/pr.yaml

Unfortunately GH action does not directly support filtering of PRs by branch name (the name you specify in `on.branches` is the "base" branch. With this PR, newshell is always built on every PR, but only those that are named `newshell-*` run the full tests.

Improve newshell.yaml and use better names for GH builds

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_64

This pr makes the x86_64 assembler set REX.B to 1 when encoding a MOV r64, imm32/64 instruction when r64 is from r8 to r15.
**Test plan**
...

x86_64: Fix REX.B for MOV r64-extended, imm32/64

---

libr/bin/format/mach0/mach0_specs.h
libr/bin/p/bin_dyldcache.c

- carve dependencies looking at load commands when accelerator info isn’t there (important for iOS 13.4+ caches)
- follow upwards deps as well
- expose metadata about all images (addresses and sizes)
- emit header metadata in JSON format, it's always possible to get the human readable format with `ih~{:`
- make sure libobjc is always loaded, to prevent glitches on the slide estimation logic
- blindly support rebase info v4, as it should work like v2

Improve dyldcache bin plugin ##bin

---

libr/bin/p/bin_dyldcache.c

It was a false positive due to wrong boundary check.

Fix dyldcache malformed local symbol ##bin

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_64

This pr fixes the x86_64 assembler encoding when the MOV r32, -imm32 notation is used.
**Test plan**
...

x86_64: Fix MOV r32, -imm32 encoding

---

libr/util/format.c

newsize already >=1
**Test plan**
...
...

Fix a LGTM alert

---

libr/asm/p/asm_x86_nz.c
test/db/tools/rasm2

This pr prevents the x86_32/64 assembler from assembling overlarge MOV imm32 assembly constants.
**Test plan**
GitHubCI and AppVeyor are green with attached test.
...

x86_32/64: Don't assemble overlarge MOV imm32

---

libr/core/visual.c

Using `om=` in debug mode will cause segfault.
```
$ r2 -d rax2
Process with PID 31203 started...
= attach 31203 31203
bin.baddr 0x56254d888000
Using 0x56254d888000
asm.bits 64
Warning: r_bin_file_hash: file exceeds bin.hashlimit
-- I C dead bugs everywhere!
[0x7f1769e54090]> om
1 fd: 3 +0x00000000 0x00000000 - 0x7ffffffffffffffe rwx 
[0x7f1769e54090]> om=
```
Because a default `RIOMap` is created without setting its name when r2 is in debug mode.
https://github.com/radareorg/radare2/blob/35290dd51d815ed0e36623b1fba63c6f8a93bd84/libr/core/cfile.c#L688-L691
Thefore, when calling `om=`, it passes `map->name` (NULL) to `r_listinfo_new` and the function calls `strdup (NULL)`, which causes the …

Fix segfault when passing null string to "r_listinfo_new"

---

.github/workflows/newshell.yml
test/db/cmd/cmd_hash
test/db/cmd/types

build should be completely green with newshell now, so we can make sure it will always be.
I removed two tests that were "wrong".
- `tk - crash` was just checking that a particular command was not crashing. Returning 0 is wrong in those case, because if the command is invalid the parser should just say "Invalid command" (or something like that) and not return 0. The new parser correctly complains about the invalid command, but the old one does not so I just removed the test.
- `hash_subcommands_not_noop` was executing (invalid) commands that are treated as comments in the new parser. Everything after `#` is a comment in the new parser, apart from commands that start with `#!` (and `#?`). The test was using `#a`, which just makes everything after `#` being treated as a comment.

Enforce newshell build from now on

---

shlr/gdb/src/arch.c

gdb arch reg profile memory leak fix ##debug

---

.github/workflows/static.yml
libr/socket/run.c
sys/static.sh

Debian/Ubuntu doesn't seems to provide libutil.a so symbols are missing and libr.a is not purely static
We should provide a fallback with just fork imho, but at least this will keep it working
...
**Test plan**
...
...

Fix the static build by dynamically resolving libutil symbols ##build

---

libr/anal/var.c
libr/core/anal_tp.c
libr/include/r_anal.h

Previously, this "linking" was used to add information that in a case like this, where `ecx` is an argument and it is directly saved in `var_3ch`, these variables are linked together.
```
0x00083e83      894c240c       mov dword [var_3ch], ecx    ; arg4
```
However this is now completely unnecessary and we can recover the info directly from the accesses by checking which is a read and which is a write.
This is also the last step to remove everything var-related from sdb, unless I overlooked something.
**Test plan**
`db/cmd/types` contains tests for exactly these cases

Remove Variable Linking and replace with Info from Accesses

---

.github/workflows/ci.yaml

With some past changes I disabled newshell tests in master. This re-enables them.

Restore newshell tests in master branch

---

meson.build
meson_options.txt
shlr/meson.build

As of https://github.com/tree-sitter/tree-sitter/pull/602 it is possible to install tree-sitter as a system shared library, and distros want to be able to disable vendored code.
/cc @anthraxx @FFY00 @SantiagoTorres (who want this for packaging radare2 on Arch Linux)

tree-sitter: add option to build with system library

---

libr/core/cmd.c
test/db/cmd/cmd_visual

Visual mode was already disabled when scr.interactive=false. This PR adds similar behavior for panels.
**Test plan**
* Test case added to the tests - set `e scr.interactive=false` and try to enter `v` and `V`. It should fail and print a message.
* Manually test that sure `v` and `V` still work when scr.interactive isn't disabled.
Closes #16689

Don't start panel mode when noninteractive.

---

libr/core/cmd.c
libr/core/cmd_api.c
libr/include/r_cmd.h
test/unit/meson.build
test/unit/minunit.h
test/unit/test_cmd.c

Right now the new shell just parse the arguments and then put them back together to call `r_cmd_call`. However, in the future  our command handlers (defined in RCmd) will receive argc/argv, so we need RCmd to be able to merge argv together only when needed (that is when we want to call an "old" command handler that does its own parsing).
This PR introduces RCmdParsedArgs and moves the responsability of creating a single "exec string" to RCmd and not in arged_command function.

Pass parsed arguments directly to RCmd

---

libr/core/cmd.c
test/db/cmd/cmd_seek

Old parser supports `<cmd> @ +<val>`, but new parser did not. This PR adds support for it.
**Test plan**
```
pd 10 @ +0x10
```
should move the seek to `$$ + 0x10`
closes #16682

Support relative temporary seek in cfg.newshell

---

libr/core/cmd_write.c
libr/crypto/crypto.c
libr/include/r_crypto.h

- Add a structure of supported encoder names
- Add a function to get the name of the encoder corresponding to the id given as parameter
- Change the way `woD` command prints supported encoders names
**Test plan**
`woD` should print the same help message as before.
...

Remove hardcoded supported encoders names

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc

The relocations are loaded 3 times... I try to fix that. 
**Test plan**
...
#12732
...

Unify the relocations loading

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_64

Previously, for x86-64, rasm2 incorrectly assembled `pop rn` where rn is an extended register (i.e. `r8-r15`). This pull request fixes that.
...
**Test plan**
...
...

Fix assembling of pop r8-r15

---

libr/anal/var.c
libr/include/r_anal.h

size is never used and regname shouldn't be deprecated that hard, it is useful for rebasing at least.

Minor Restructuring of RAnalVar

---

libr/anal/meta.c
libr/anal/var.c
libr/core/cmd_meta.c
libr/core/disasm.c
libr/include/r_anal.h
test/db/anal/x86_64
test/db/cmd/cmd_meta

Variable comments make no sense in meta. Also they completely ignored the "normal" meta sdb format that is used for everything else. Having a single `char *` in RAnalVar is enough here.
**Test plan**
run the tests

Refactor Variable comments from SDB into RAnalVar 

---

binr/r2r/r2r.c

With r2r on Windows:
Before:
After
The `setvbuf()`s are there since otherwise there can be horrible flickering of the status line, especially noticeable with something like `r2r -i db/asm/x86_64`.
**Test plan**
Tested with both cmd and Windows Terminal. Tested also `r2r -V db/asm/x86_64`, and not sure which terminal better handles things.
...

r2r: Enable ANSI esc seqs on Windows

---

libr/bin/bfile.c
libr/bin/bin.c
libr/core/cconfig.c
libr/include/r_bin.h
test/db/cmd/cmd_i

This pr allows `bin.str.enc` to affect `izz` (though not `iz` for some reason), and `ascii` is now an alias for `latin1`.
**Test plan**
Fixes #16543.

Fix #16543 - bin.str.enc affects izz + ascii is now alias for latin1

---

binr/r2r/r2r.c

Right now you get this:
```
$ r2r @unit
Cannot find db/ directory related to the given test. 
```
**Test plan**
just apply this pr and run r2r @unit and see that after the fix the command above works
There's no open issue for this. imho travis and such should use r2r to run all the tests

Fix autodetection dbdir in r2r @unit ##tests

---

libr/bin/p/bin_dex.c

* Use proper RBuf api instead of doing bulk reads in DEX ##bin
* Loading an 8MB DEX file: Before:  48s,  After: 17s
Before it was read the whole file for every entry in the debug info section. then parsing it by using the uleb apis. translating this to use the reading just the necessary bytes makes it much faster (about 3.5x in a 8MB dex file)
**Test plan**
time r2 -qcq classes.dex
no issue tracking this

3.5x faster DEX loading parsing debug_info section ##bin

---

libr/anal/meta.c
libr/bin/format/dex/dex.c
libr/bin/format/dex/dex.h
libr/bin/p/bin_dex.c
libr/include/r_vector.h

**Benchmark results**
```
type    top    vsz     rss      time
------------------------------------
calloc  339M   4732640 365452   48s
pvector 338M   4731012 371484   48s // XXX fails somehow with trash indexes
htup    338M   4731556 371620   58s
nocache 350M   4742936 376156   52s
```
nocache -> calloc = 8% faster and 3% less memory usage

Reduce memory usage in DEX files by caching the getstr calls ##bin

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_32
test/db/asm/x86_64

Previously, rasm2 incorrectly assembled `bswap` and `xchg` for x86-64 as shown below.
```
$ rasm2 -b 64 -
bswap r15
480fcf
bswap r15d
0fcf
xchg al, dl
92
xchg dl, al
92
xchg ax, dx
92
xchg rax, rdx
92
xchg rdx, rbx
87da
xchg rbx, rdx
87d3
xchg r8, r15
97
xchg r15, r8
97
xchg r8d, r15d
97
xchg r15d, r8d
97
```
While the expected behavior is as follows.
```
$ rasm2 -b 64 -
bswap r15
490fcf
bswap r15d
410fcf
xchg al, dl
86c2
xchg dl, al
86d0
xchg ax, dx
6692
xchg rax, rdx
4892
xchg rdx, rbx
4887d3
xchg rbx, rdx
4887da
xchg r8, r15
4d87c7
xchg r15, r8
4d87f8
xchg r8d, r15d
4587c7
xchg r15d, r8d
4587f8
```
This pull request fixes this problem.
**Test plan**
...
...

Fix assembling of xchg and bswap

---

.travis.yml
sys/debian/radare2/CONFIG

debian != ubuntu
**Test plan**
take an ubuntu xenial and try to run the deb generated in here
no issue tracking this, but i cant find where this deb is in this PR

Aim to fix the debian package for "Xenial"

---

binr/r2r/load.c
binr/r2r/r2r.c

r2r -i and fix on the following:
```
CMDS=?e hello
EXPECT=
RUN
```
**Result Before:**
```
CMDS=?e hello
EXPECT=<<EOF
hello
EOF
EXPECT=
RUN
```
**Result After**
```
CMDS=?e hello
EXPECT=<<EOF
hello
EOF
RUN
```

Fix r2r -i fix for single-line EXPECT=

---

sys/meson.py

During Windows installation, this pr adds an `r2` shell script that calls `radare2`, for shells that don't recognize .bat or .cmd extensions (e.g. git bash). This is to support #16747.
**Test plan**
Running `r2` on the git bash prompt works (assuming that it's in PATH ofc).
...

Windows sys/meson.py: Add r2 shell script

---

libr/core/visual.c

<kbd>F9</kbd> key was to bind to continue if no debugger were attached. Now it will perform the `aec` command for ESIL.
**Test plan**
I could not find how to simulate the press of <kbd>F9</kbd> key in a test.

Add F9 continue key to ESIL

---

libr/cons/cons.c
libr/cons/dietline.c
libr/cons/input.c
libr/cons/line.c
libr/cons/output.c
libr/core/cconfig.c
libr/include/r_cons.h

This makes radare2 compatible with the new Windows Terminal and semi-working under MinTTY
* Fix radare2 immediately exiting when console is redirected to pipe
* Hack to get viewport size under MinTTY
* Fix mouse when VT input disabled and buffer scrolled
* Fix line wrapping when VT output disabled
**Test plan**
- On ConHost (Windows 10 1909)
- On Windows Terminal/Mintty
Maybe #15674 cc @pandasauce

Add VT sequences input support ##windows

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h

The error value (not found) inside `RBinElfDynamicInfo` was 0. The problem is that some value inside the dynamic section are 0 and it is VALID. So i change the default value.
PS: All size have a value of 0, imho an invalid size is 0 not a big value.
**Test plan**
...
#12732

Change default value inside struct dyn

---

libr/cons/canvas.c
libr/core/agraph.c
libr/include/r_agraph.h
libr/include/r_core.h
libr/include/r_util/r_str.h
libr/util/str.c
libr/util/vector.c
test/unit/test_str.c

to be able to scroll to the next position of the highlighted word. this will be usful to have in visual disassembly too. but for now this pr works in the interactive graph.
Observations: the whole graph seems to be shifted by the position of the first node in order to make x=0,y=0 the location of the first node. so it needs substracting the origin_x to the rest of positions. another exception is when multiple hits are found in the same line.
* The strstr_xy should be moved to util/str
* The list of matches and positions should be moved to util/
* This feature should be using the node body info and node position instead and scroll to the node instead of the text location.
* Should not use globals
**Test plan**
```
$ r2 …
```

Fix #16636 - Add \ key in visual graph to scroll to the next highlighted word ##graph

---

libr/anal/class.c
libr/anal/rtti.c
libr/anal/rtti_itanium.c
libr/anal/vtable.c
libr/bin/format/mach0/mach0.c
libr/flag/flag.c
libr/include/r_anal.h
libr/include/r_flag.h
test/db/anal/classes
test/db/anal/x86_64

- Improve itanium RTTI parsing, to work on MachO arm/arm64, to allow class recovery and to work even without symbols
- Improve vtable search, making it compatible with arm/arm64 and using simpler heuristics for carving the tables from the data section (inspired by paper "Devil is Virtual: Reversing Virtual Inheritance in C++ Binaries" (Rukayat, Erinfolami 2020) [arXiv:2003.05039](https://arxiv.org/abs/2003.05039))
- Fixed a bug in Mach-O parsing of relocs, for which on arm/thumb the pointers were wrongly aligned to 16 bits
- Fixed a NULL dereference in class.c for which incomplete vtables caused a segfault
NOTE: added tests, but the binaries are here: https://github.com/radareorg/radare2-testbins/pull/18

Improve itanium RTTI parsing ##anal

---

libr/bin/pdb/pdb.c

This fixes types that start/end with underlines being trimmed
**Test plan**
Tests pass

Fix aggressive name filtering for PDB types

---

libr/core/cmd_type.c
libr/util/utype.c
shlr/tcc/libtcc.c
shlr/tcc/libtcc.h
shlr/tcc/tcc.h
shlr/tcc/tccgen.c
test/db/cmd/types

Numeric named structs shouldn't be appearing in "ts" commands.
**Test plan**
Create a test asserting that a numeric named struct generated after typedeffing anonymous struct does not show up in "ts" commands.
Closes https://github.com/radareorg/radare2/issues/16343.

Fix #16343 - Do not generate numeric structs from unnamed typedefs in "ts" ##types

---

libr/bin/dwarf.c
libr/bin/format/objc/mach0_classes.c
libr/include/r_util/r_uleb128.h
libr/util/uleb128.c
test/db/cmd/cmd_flags
test/db/cmd/dwarf
test/db/cmd/lea_intel
test/unit/test_uleb128.c

What was the problem: DWARF parsing with large dSYM files for iOS had both stability and correctness issues, here's the solution:
- fix `r_leb128` decoding logic and add support for boundary checking
- support up to v4
- ensure all v4 line number program header fields are parsed
- remove wrong assumptions about the content of included directories
- ensure unit length calculation is correct
- ensure all leb128 / uleb128 have boundary checking
Along the way also fixed what i think it's typo in `mach0_classes.c` which caused a NULL dereference.
**Test plan**
Added a test in `test/db/cmd/dwarf` which relies on a binary added here: https://github.com/radareorg/radare2-testbins/pull/19

Fix DWARF v4 parsing ##bin

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h

I tried to reduce the use of dyn_buf. The last function using it is `Elf_(r_bin_elf_get_libs)`.
The only problem is that DT_NEEDED should be a list.
**Test plan**
...
#12732

Minimize dynamic loading

---

libr/cons/cons.c

Occasionally on mintty, `__xterm_get_size()` will get a value of 0 for rows which can disrupt the Visual mode display. This pr fixes that by reusing previous values if so, and assumes that all is fine and dandy at time = 0.
**Test plan**
Expand the mintty terminal window to full size, run `r2 --`, go to Visual mode (`V`) and hold down the arrow-down key. The display should not flicker.
I use the mintty from git bash.
...

When getting terminal size on mintty, reuse prev vals if rows=0

---

libr/core/cmd.c
libr/core/cmd_api.c
libr/include/r_cmd.h
test/unit/minunit.h
test/unit/test_cmd.c

The idea is to use RCmdDesc to hold info about different kinds of commands. RCmdDesc will be structured in a tree, used to keep the structure of the commands as we have now. Moreover, some of RCmdDesc are also stored in a hashtable for quick retrieval when you need to execute a command.
To keep supporting existing command handlers, there will be different kinds of RCmdDesc.
* `R_CMD_DESC_TYPE_OLDINPUT`: this is used to store info about the existing handlers. Those handlers accept `(void *user, const char *input)` and they do the parsing of input themselves. In a distant future, we should probably convert all these to something else, but it will require time.
* `R_CMD_DESC_TYPE_ARGV`: this store info about the new kind of …

Extend RCmdDesc with different types

---

libr/core/cmd.c
libr/core/cmd_api.c
libr/include/r_cmd.h
libr/include/r_core.h
test/unit/test_cmd.c

RCoreCmdStatus is the same as RCmdStatus. That enum belongs more to r_cmd.h than to core in general, so this PR removes RCoreCmdStatus and just uses RCmdStatus. It also changes the API of r_cmd_call_parsed_args so that it directly returns RCmdStatus.

Remove RCoreCmdStatus and just use RCmdStatus

---

libr/bin/bfile.c
libr/bin/bobj.c
libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/mach0/mach0_defines.h
libr/bin/p/bin_mach0.c
libr/bin/p/bin_xnu_kernelcache.c
test/db/anal/classes

Support BIND_OPCODE_THREADED and its sub-opcodes, for both parsing relocs correctly and reconstruct the pointer-rebasing chains.
Rebasing and stripping happens on-the-fly by swizzling the IO read function and leveraging the chain starts generated by supporting the BIND_OPCODE_THREADED machinery. (This feature is enabled only when opening arm64 binaries)
Add “informational” support for new load commands (but didn't manage to find a sample binary to actually go on and implement them yet):
- LC_DYLD_EXPORTS_TRIE
- LC_DYLD_CHAINED_FIXUPS
Along the way also fixed a bug in the xnu kernelcache rebasing of pointers.
NOTE: these are the sources of truth i used to implement this:
- …

Support Mach-O arm64e threaded binding

---

.gitignore
libr/anal/anal.c
libr/anal/fcn.c
libr/anal/meta.c
libr/anal/reflines.c
libr/core/anal_objc.c
libr/core/blaze.c
libr/core/canal.c
libr/core/cbin.c
libr/core/citem.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_eval.c
libr/core/cmd_meta.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/core/core.c
libr/core/disasm.c
libr/core/project.c
libr/core/visual.c
libr/core/vmenus.c
libr/include/r_anal.h
test/db/cmd/cmd_repeats
test/db/cmd/metadata
test/db/formats/elf/helloworld-gcc-elf
test/unit/meson.build
test/unit/test_anal_meta.c

This removes meta from SDB and instead stores it in an RIntervalTree. More info on the storage can be found in the comments in `r_anal.h`.
One important change in the API is that it now returns weak references into the existing RAnalMetaItems, so callers must not free the returned stuff anymore!
This also includes some minor convenience changes in RIntervalTree and fixes for `@@@C:` in both old and new shells because that had to be refactored somehow to conform to the new API but it was completely broken so I fixed it as a side effect.

Refactor Meta out of SDB

---

libr/bin/p/bin_elf.inc

...
**Test plan**
...
Fix #16791

Fix potential nullptr dereference in lookup_symbols()

---

binr/r2r/r2r.c
libr/include/r_cons.h

This pr reduces flicker of the summary line for some consoles when doing `r2r -V`, without mangling the scrollback buffer.
Example before:
Example after:
Apparently some terminals are line-buffered at their core and thus it appears line clearing and printing of new content should be done in 1 go for each line.
**Test plan**
Tested on Conhost (Windows 10 1903), Windows Terminal, alacritty and mintty [Windows], and gnome_terminal, konsole, xfce4_terminal, mlterm and xterm [Linux].
...

Reduce flicker when doing r2r -V (for some consoles)

---

libr/bin/format/pe/pe.c

Especially noticeable in multi-megabyte bins
Before:
```
time r2 -qq /mnt/c/Windows/System32/MRT.exe
8.20s user 1.23s system 99% cpu 9.440 total
```
After:
```
time r2 -qq /mnt/c/Windows/System32/MRT.exe
1.55s user 1.20s system 100% cpu 2.749 total
```
**Test plan**
Tests pass

PE: Get actual checksum speedup ##bin

---

libr/core/cmd_api.c
libr/include/r_cmd.h
test/unit/test_cmd.c

Maybe after all we don't need this inner nodes :D
While working on PR #16782 I realized I could have multiple RCmdDesc with the same name in the hashtable by having both inner and argv nodes. Shall we just remove the inner nodes and consider them as ARGV node?

Remove INNER nodes and merge inner node with the command with same name

---

libr/include/r_util/pj.h
libr/util/pj.c
test/unit/meson.build
test/unit/test_pj.c

This can be used to re-use the same pj instance for creating multiple jsons without re-allocating the string buffer all the time.

Add pj_reset()

---

binr/r2r/r2r.c

This pr fixes Windows r2r so that it actually tries to display its emojis.
Seen on Windows Terminal 0.11.1251.0:
Seen on alacritty 0.5.0-dev (7901b45):
There appears to be full support from Windows Terminal, and partial support from alacritty and mintty (3.1.0), though this could be due to my lack of knowledge regarding font setup for them. Support for Conhost is somewhere ["in the future"](https://github.com/microsoft/terminal/issues/190#issuecomment-562731321) apparently.
**Test plan**
Do `r2r -i` with failing `cmd` tests. The emojis should be displayed like on Linux.
...

Windows r2r: Actually display emojis (on consoles that support them)

---

libr/core/cmd_api.c

`parent` of `RCmdDesc` is NULL when creating the root node. This was not detected because the command initialization happen before cfg.level takes place, so the assertion was not printed.

When configuring root RCmdDesc node, parent may be NULL

---

libr/core/cmd_anal.c
libr/debug/trace.c
libr/include/r_debug.h

This allows to avoid extra call of `r_anal_op()` in `r_core_esil_step()`. But yes, new API for a single case is a really hackish solution.
`aaft` time for `/usr/bin/snap` (~18MB): 95s vs 88s
`/bin/ls`: 1.25s vs 1.16s
...
**Test plan**
...
...

Add r_debug_trace_op() API

---

libr/core/cmd_anal.c
test/db/cmd/cmd_fnj

Anal regs is not reseted between iterations of `aaft`. For example this can cause unnecessary loops during emulation of `rep stos*` instructions.
In my case `rdx = 0xffffffffffffffff` on entry of this function:
```
/ 21: sym.r_util.dll_r_mem_memzero (int64_t arg1, int64_t arg2);
|           ; var int64_t var_20h @ rsp+0x8
|           ; arg int64_t arg1 @ rcx
|           ; arg int64_t arg2 @ rdx
|           0x180014f90      48897c2408     mov qword [var_20h], rdi
|           0x180014f95      488bf9         mov rdi, rcx               ; arg1
|           0x180014f98      33c0           xor eax, eax
|           0x180014f9a      488bca         mov rcx, rdx               ; arg2
|           0x180014f9d      f3aa           rep stosb …
```

Reset anal regs in every iteration of aaft

---

libr/core/cmd_meta.c
test/db/cmd/cmd_meta

This is a regression introduced in edf1be10d1
**Test plan**
```
$ r2 /bin/ls
-- radare2 is like windows 7 but even better.
[0x000067d0]> af
[0x000067d0]> Cf.
$
```
none

Fix crash in 'C{fd..}.', reproducible with r2dec

---

binr/r2r/r2r.c
test/unit/meson.build
test/unit/r2r_cmd_test
test/unit/test_r2r.c

Fixing tests from `r2r -i` was messing up the line numbers when multiple tests were fixed in the same file, resulting in broken tests.

Fix r2r -i and add Tests

---

libr/core/cmd_print.c
test/db/esil/apple

When using the webui and displaying the output of pdsf it was totally messed up because the inner disassembly was containing html tags which broke the parser of pds. So, in order to fix that 
As a bonus, this pr fixes problems in pxa when scr.color=0 or scr.html=true
**Test plan**
```
e scr.html=1
af
pdsf
```
nope

Honor scr.html in pxa, pdsf and fix some ansi glitches in scr.color=0 ##cons

---

binr/r2r/r2r.c
libr/include/r_cons.h

This pr replaces the `\x##` emoji sequences in r2r.c with actual emoji so that it's clear what the `\x##` emoji sequences represent, and also adds a `#define` for Variation Selector-16.
**Test plan**
The emojis should still appear when doing `r2r -i` with failing tests.
...

r2r.c: Replace \x## emoji seqs with #defines

---

binr/Makefile
binr/rasign2/Makefile
binr/rasign2/meson.build
binr/rasign2/rasign2.c
libr/include/r_main.h
libr/main/Makefile
libr/main/rasign2.c

This is the first steps toward making rasign2 useful. This updates the build so rasign2 will be compiled but not installed to the users path. The rasign2 binary will once again be able to make signature files. This almost closes issue #9336.  
**Test plan**
I pretty much stole the zignature code from `libr/main/radiff.c`. Here are some examples of the tool running:
help menu
```
[rasign2]$ ./rasign2
Usage: rasign2 [options] [file]
-a [-a]          add extra 'a' to analysis command
-o sigs.sdb      add signatures to file, create if it does not exist
-r               show output in radare commands
Examples:
rasign2 -o libc.sdb libc.so.6
```
Without flags the number of signatures are displayed. This also shows extra analysis. …

Move rasign2 into RMain

---

libr/anal/esil2reil.c

Add "weak equality" ESIL operation (`:=`) in ESIL to REIL converter.
**Test plan**
Before:
```
[0x00006930]> "aetr 0,cf,:="
:=
cf
0
^C
[0x00006930]> 
```
After:
```
[0x000068d0]> "aetr 0,cf,:="
0000.00:      STR      R_cf:01 ,              ,      V_00:01
0000.01:       OR         0:64 ,         0:01 ,      V_01:01
0000.02:      STR      V_01:01 ,              ,      R_cf:01
[0x000068d0]> 
```
...

Add ESIL weak eq support to `aetr` command

---

libr/core/cmd.c

I dislike the use of macros unless there's no other option. in this case i think its half explainable in order to force the function and help string to follow a specific naming convention, also as long as its inlined, a lot of more code is generated. in this case cmd.o is now 8KB smaller
**Test plan**
```
make 
ls -l cmd.o
git checkout cmdesc
make
ls -l cmd.o
```
...

Half replace the command description macros with a function (-8KB)

---

libr/bin/p/bin_pyc.c

radare2 fail to build with default option on RHEL 7 with a error due to C99 constucts without -c99.
See #14593, #14550 and #12879.

Fix c99 construct for pyc

---

binr/radare2/Makefile
binr/rasign2/Makefile
libr/Makefile
shlr/Makefile
shlr/yxml/deps.mk

Static build is broken because the yxml PR was merged without any proper review and because the static builds got rid from the CI
**Test plan**
run sys/static.sh
Fixes clusterfuzz, sdk, android and static builds, but no one filled an issue or complained even if i spotted this a week ago.

Fix static build

---

libr/main/rasign2.c
test/db/tools/rasign2

I will send a PR for the radare2book once my other radare2book PR is accepted.
This pull adds the `-f` option to rasign2 which just acts as a shortcut to the `zfd` command. So `-f` will dump the provided FLIRT signature file using FLIRT syntax.
**Test plan**
The included tests are the pretty much the same tests done for `zfd`.
This feature is pretty weak. Rasign2 does not yet match signatures, so implementing `zfs` is out. The `zfz` command does not currently do anything in r2. So you may not consider #16930 closed yet.

add dumping of FLIRT signatures to rasign2

---

libr/core/cmd.c
test/db/cmd/cmd_print

This pr fixes the `@@s` `to` param so that it's inclusive, bringing it in line with its own help message (`run 'x' on all offsets from, to incrementing by step`) and `woe`. Also, UT64_MAX + 1 < UT64_MAX which is mathematically improper.
**Test plan**
...

Fix @@s 'to' param so that it's inclusive

---

libr/socket/socket.c

Signed-off-by: Paul Fertser <fercerpav@gmail.com>
This problem is detailed fully in #16788. This patch (provided by Paul) fixes the timing issue found when trying to connect to OpenOCD's GDB server using r2. The patch adds the socket fd to the writefds set, allowing `select` to return when the socket is ready. Testing with this patch allows r2 to connect to an unmodified version of OpenOCD consistently.
**Test plan**
See #16788

Fix socket timeout in r_socket_connect

---

libr/anal/p/anal_riscv.c
test/db/anal/riscv

Analysis doesn't stop when `ret` op is reached because it is marked as `R_ANAL_OP_TYPE_UCALL`.
Copypaste from `jal` handler
https://github.com/radareorg/radare2/blob/6e401547a745fd191e066275bc5a373a2d808b8e/libr/anal/p/anal_riscv.c#L531-L534
Related: #16834

Fix ret op type for riscv

---

.github/workflows/pr.yaml

Default 6h timeout is too much. Typical runs takes 5-15 minutes. 35 should give it  a reasonable reserve.
**Test plan**
Check that corresponding PR checks take less than 35 minutes.

Limit PR build timeout.

---

libr/asm/arch/wasm/wasm.c

I've also patched a coverity issue where the `size_t` is compared to check negative values, which can't happen since it's unsigned in the first place.

[wasm] fixed pre c99 for loop

---

shlr/gdb/src/arch.c

I missed a pair of parenthesis in the `gdb_reg_t` array size calculation, which causes out-of-bounds write in `memcpy`.
**Test plan**
closes https://github.com/radareorg/cutter/issues/2194

Fix out-of-bounds write

---

libr/core/cmd_anal.c

This pr with regard to the ahi help messages:
- Removes 1 as a numeric base (base s still exists).
- Fixes ahi topline.
- Uses `<base>` instead of `[base]` since it's required.
- Adds some missing items to man ahi help message i.e. `i, p, S`.
- Sorts ahi help items according to main ahi help message `(2, 8, 10, 16, i, p, S, s)`.
**Test plan**
Emm ahi help is more accurate and consistent?
...

Fix ahi help msgs

---

libr/anal/var.c
libr/include/r_list.h
test/unit/test_list.c

> radare2 is WYSIWYF - what you see is what you fix
For those slower users like me, who can't get at it in a single r2 run, smooth `Ps`/`Po` is important.
This patch fixes one annoying bug in that (maybe also several others). Illustrating unit test included!

Fix half-assed comparators

---

libr/anal/sign.c

The functions r_sign_diff and r_sign_diff_by_name had repeated code to create
a list of deserialized signatures from a sign space. This commit moves that
code into a helper function.
Two different functions in sign.c had repeated code. I moved the code to a separate function. This just refactoring, there should be no change to functionality and so no new tests or documentation are needed.
**Test plan**
No additional tests are needed. Code was just moved around.
...

replace repeated code in sign.c with new function

---

.github/workflows/newshell-treesitter-tests.yml
shlr/radare2-shell-parser/corpus/pf_commands.txt
shlr/radare2-shell-parser/src/scanner.c

When using cfg.newshell=true, `pfo` without arguments was not working as it was not identified as a `cmd_identifier` but neither as a `pf_command`. This PR makes sure the scanner considers `pfo` as a regular `cmd_identifier`, so that it can be handled like others `arged_command`s.
It also fixes a problem with the github action for testing tree-sitter corpus files. Changed to inner directories in shlr/radare2-shell-parser were not monitored.

Fix pfo command without arguments

---

libr/anal/p/anal_riscv.c
test/db/esil/riscv_32

Previous jump offset and return address were not computed right in ESIL for RISC-V.
**Test plan**
One test added.

Correct RISC-V ESIL for jumps

---

sys/build.sh

Do the check for need to use rpath based on PREFIX after PREFIX has been set by command line argument.
**Test plan**
* Do `sys/user.sh` in a VM preferably on Ubuntu 18.04 or other distro that uses `--enable-new-dtags` by default
* make sure running ~/bin/prefix/radare2/bin/r2 directly works
* using `readelf -d binary` check that RUNPATH is correctly set for r2 and lib/libr_core.so
* compile Cutter against ~/bin/prefix/radare2 r2 and make sure it opens without problems loading any of r2 libraries

Do the prefix check after prefix argument has been processed.

---

libr/core/cmd_anal.c
libr/parse/filter.c
test/db/cmd/cmd_ahi

This pr does 2 things:
1. `ahi 10` or `ahi d` does signed decimal if it detects an x86 32-bit register (see https://github.com/radareorg/radare2/compare/master...kazarmy:ahi-10-signed-ahi-10u?expand=1#diff-0147cd662e9a03b59a8deb98c5e3b400R375 for an example).
1. `ahi 10u` or `ahi du` forces unsigned decimal if needed.
Method used is somewhat hacky but since this is a deliberate hint, it isn't enabled by default and the hint can be removed. Unfortunately only supporting x86 for now -- support for other archs is somewhere in the distant future.
**Test plan**
...

ahi 10 does signed decimal with 32-bit gp regs + ahi 10u for unsigned decimal

---

libr/core/panels.c

Issue:
Glitch happens when using W + j and moving a panel to bottom like the screenshot attached
Fix:
Calculation of height and position of the panels was not right so fixed it.

Fix a glitch of W + j in panels

---

libr/bin/d/elf32
libr/bin/format/elf/elf.c
test/db/cmd/cmd_pf2
test/db/cmd/cmd_pf_elf

This pr does 2 things to the elf32 pf.elf_header format:
1. Change w -> N2 for phnum, shnum and shstrndx (600f051da5b93b20aa99cb481cf47cdcbc52f277), because array indexing is usually done in decimal.
1. Change w -> N2 for ehsize, phentsize and shentsize (0a137ae4e9f435cd6b539cb6d054bf784c8c62d8), because data structure sizes are usually stated in decimal bytes.
This pr removes the need to convert between hex and decimal.
**Test plan**
...
**TODO** (if pr is accepted)

elf32 pf.elf_header: w -> N2 for phnum, shnum, shstrndx, ehsize, phentsize and shentsize

---

shlr/radare2-shell-parser/corpus/special_commands.txt
shlr/radare2-shell-parser/src/scanner.c

In https://github.com/radareorg/radare2/pull/16966#issuecomment-636436231 it was reported that with cfg.newshell=true:
`%R2_CURL=1 ;idpd` does not,
`%R2_CURL=1;idpd` works
This PR fixes this behaviour by making sure EQ_SEP_CONCAT is implemented by reusing `is_concat`.
**Test plan**
Added new commands in the corpus files.

Fix `;` at the end of the value of eq_sep_args

---

libr/core/anal_tp.c

This fixes getting a flag in the wrong flagspace
Use r_flag_get_by_spaces() instead of manually comparing the flagspace name
**Test plan**
Tests pass

Fix type matching with loaded PDB ##anal

---

libr/bin/format/mach0/mach0.c
libr/core/cbin.c
test/db/formats/mach0/swift

Running r2 on the `dyld_shared_cache_arm64e` from my iOS/arm64e device running iOS 13.5, I ran into the following issues:
1. It crashes because the `THREADED` opcode is encountered before the usually preceding `SET_SEGMENT_AND_OFFSET_ULEB` opcode. Apple's state machinery handles this case.
2. The reason 1) happens is because parsing doesn't stop when encountering the `DONE` opcode, so it goes ahead and parses “junk”.
3. With 1) and 2) out of the way, a lot of warnings were printed to the console: `WARNING: r_meta_set_with_subtype: assertion 'm && size' failed (line 185)`. This happens because of [this](https://github.com/radareorg/radare2/blob/f255a82a1bb45614a921e3cf156ac37b2b40811d/libr/core/cbin.c#L2206-L2209) logic in …

Fix crash and warnings when opening an iOS/arm64e DSC

---

libr/bin/blang.c

- [] I've added tests that prove my fix is effective or that my feature works (if possible)
- [] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
rabin2 only detects go language for ELF binaries. This update now detects golang when using the `-I` flag with rabin2 against a go binary built for macho.
...
**Test plan**
1. Build a go binary with any of the following: `GOOS=darwin GOARCH=amd64 go build`
2. Run `rabin2 -I <binary> | grep lang`
3. The result should be `lang     go` (previously it returned `lang     c`
...
N/A
...

rabin2 could not detect go in macho binaries

---

libr/include/r_vector.h
meson_options.txt
test/unit/minunit.h
test/unit/test_addr_interval.c
test/unit/test_annotated_code.c
test/unit/test_buf.c
test/unit/test_event.c
test/unit/test_intervaltree.c
test/unit/test_vector.c

I found myself always enabling unit tests when compiling in meson, am I the only one? I think package maintainer can easily add that one flag the one time they need to create the spec file (or whatever for their distro), but for us as upstream developer it's quite annoying, at least to me, to have to specify that every time, since I often create different build directories for various PRs, tests, etc.
This PR makes enable_tests default to true.

Enable unit tests compilation by default in meson

---

libr/parse/p/parse_x86_pseudo.c
test/db/anal/x86_64

PR alters pseudo code for lea operator to not include brackets. Variable resolution is preserved.
Example:
```
> e asm.pseudo = false
0x0804843c      8d45f8         lea eax, [var_8h]
```
```
> e asm.pseudo = true
0x0804843c      8d45f8         eax = var_8h
```
**Test plan**
Use e.g. crackme0x02 from IOLI crackmes series. Run ```e asm.pseudo = true``` and confirm pseudo code for lea looks as described in example.
closes #16777

x86 pseudo for LEA is wrong

---

libr/anal/p/anal_arm_cs.c
test/db/esil/arm_16
test/db/esil/arm_32

Carry and overflow flags were not updated after adds or subs instructions in ESIL,
**Test plan**
Test added.
#10577 should be closed.

Add ESIL flag update for adds and subs instructions

---

libr/core/visual.c

This pr (basically 9ac00d93f98a2d4ada66cd1ce4bf9fdd9391ddbd) prevents runaway scrolling in Visual mode after mashing down hjkl or an arrow key on Windows Terminal, by clearing the stdin buffer. It is #12761, #12764 and #12823 ported over to Windows.
**Test plan**
Tested with keyboard and mouse wheel with default `scr.vtmode` and the following:
- Conhost Windows 10 1903
- Windows Terminal 1.0.1401.0
- Alacritty 0.5.0-dev (e6475c6) -- apparently currently no mouse support even with `e scr.vtmode = 2`
- mintty 3.1.6
...

Fix runaway scrolling in Visual mode after mashing down movement key on Windows Terminal

---

libr/bin/format/elf/elf.c
test/db/anal/arm64

Work on  #12732
See #12061 
PS: i will add one regression test (i just need to push libarm64.so)
https://github.com/radareorg/radare2-testbins/pull/24
**Test plan**
r2 libarm64.so
#12061

Fix Missing Exports and Imports on ELF

---

libr/bin/dwarf.c
test/db/formats/mangling/bin

#16975 
Compilation unit can have multiple line information sequences, radare2 parsed only one because the algorithm was wrong. 
There is one header per compilation unit, and there can be multiple sequences, in the algorithm there wasn't any tracking of read length (there was a loop that was always executed only once, because at the end it appended the length between start to end to the start) 
So I've changed `r_bin_dwarf_parse_opcodes` to return read length so I know if there are still more sequences left. Move the header creation outside the loop, because it's created only once per unit. And I read a sequence every loop.
Tests in #16965  (WIP)
(Compared to previous output shown in the #16975 )
Now:
```
$ r2 cpp_dwarf3
> …
```

Fix in a dwarf line information parsing implementation

---

test/db/anal/vars

Fix the test for running ARMv8 64 bit built radare2
https://travis-ci.com/github/radareorg/radare2/jobs/345486453

Fix test for ARM64 builds

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc
test/db/formats/elf/elf-relro

This PR supersedes https://github.com/radareorg/radare2/pull/16829 . It should fix a crash while loading the librsjni_androix.so bin from the testsuite.
It does so by:
- fixing wrong computation of the offset in function `get_next_not_analysed_offset`
- using virtual address instead of offset files in `read_reloc`. All relocations values are expressed in vaddr, so using offsets+-baddr was wrong
- passing `num_relocs` around so that we can use it both as a defensive measure in case `get_num_relocs_approx` returns wrong value and also as a way to limit the number of relocation entries to read in case the section info are fake and too large.
It also adds support for AARCH64 reloc entries.

Fix elf reloc crash

---

libr/util/format.c
test/db/cmd/cmd_pf2

This pr adds support for `n1`/`n2`/`n4`/`n8` to `pfc`.
**Test plan**
GitHubCI and AppVeyor are green with attached test.
...

pfc: Support n#

---

binr/r2r/r2r.c
libr/include/r_diff.h
libr/util/udiff.c

This pr patches r2r so that it uses `git diff --no-index` on Windows, for nicer diff output. I think it's safe to assume that every r2r Windows developer has git installed.
**Test plan**
On Windows, mess up a single line of test output, run `r2r -i` on the test, and then see whether the messed-up line is highlighted.
...

r2r: Use git diff on Windows

---

libr/asm/p/asm_x86_nz.c
test/db/asm/x86_32
test/db/asm/x86_64

endbr64 and endbr32 instructions were not supported by the assembler
**Test plan**
32 and 64bit assembly and disassembly of those instructions work as expected in the testsuite
none

Implement assembler endbr32 and endbr64 instructions for x86-32/64 ##asm

---

libr/bin/format/objc/mach0_classes.c
test/db/formats/mach0/objc

Flags are encoded in the lower / upper bits of the pointer to objc class data. This strips those bits from the pointer before using it.
**Test plan**
- open a binary with objective-c categories on swift classes
- run `ic` and check the base class name of the category, if it's `(null)` is wrong
```diff
[0x100001b00]> ic
-0x100003078 [0x100001ad0 - 0x100001ad0]      0 class 0 (null)(TEST)
+0x100003078 [0x100001ad0 - 0x100001ad0]      0 class 0 TestSwiftObjc.ThisIsASwiftClass(TEST)
0x100001ad0 method 0      testObjc
0x1000031e8 [0x100001d80 - 0x100001d80]      0 class 0 TestSwiftObjc.ThisIsASwiftClass :: NSObject
0x100001d80 method 0      init
```
Added an r2r test which does just that, depends on this test bin: …

Fix objc rodata mask

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
test/db/cmd/cmd_i
test/db/tools/r2r
test/db/tools/rabin2

Add the dt_needed array.
So i could remove the old dyn entries buffer.
This PR need the validation of the pr #17004
**Test plan**
One regression test fail. But for me the test is false.
The expected value for the test suite
```
-vaddr      paddr      type   name
----------------------------------
-0x00600988 0x00000988 SET_64 __gmon_start__
-0x006009a8 0x000009a8 SET_64 write
-0x006009b0 0x000009b0 SET_64 close
-0x006009b8 0x000009b8 SET_64 __libc_start_main
-0x006009c0 0x000009c0 SET_64 open
```
```
❯ readelf --relocs --use-dynamic ./test/bins/elf/analysis/dynamic-poffset
'RELA' relocation section at offset 0x0 contains 17179869188 bytes:
readelf: Warning: Virtual address 0x0 not located in any PT_LOAD segment.
readelf: …
```

Add dt needed inside dt dynamic struct

---

.travis.yml
libr/bin/dwarf.c
libr/include/r_bin_dwarf.h

(tests are already there)
I am abusing PR so I can run tests on ARM to check if I found the error  for #15688 
I think it might be because signedness of `char` is implementation defined and the line_base is supposed to be -5, but instead it's 251 which is -5 on 8bit 2's complement

Fix signedness issue in the DWARF line parser on ARM64

---

test/db/formats/mach0/mach0

When the host where r2 runs is aarch64, the 64 bit part of the binary is selected by default and the test fails, so I select the arch/bits explicitly.
Since I never worked with fatmach0 stuff I am not entirely sure whether switching with `oa` is the correct approach here so please review.
**Test plan**
Run the tests on a 64 bit arm system.

Fix a fatmach0 test under aarch64 ##test

---

libr/core/cmd.c

When running `?` I got this:
```
==659891==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x60200009fc0f at pc 0x7f02ecef3db5 bp 0x7ffd7c27fe20 sp 0x7ffd7c27f5c8                                                                                                                                      
READ of size 1 at 0x60200009fc0f thread T0                                                     
#0 0x7f02ecef3db4  (/lib64/libasan.so.5+0xd6db4)                                           
#1 0x7f02ea8f3d09 in handle_ts_help_command_internal ../libr/core/cmd.c:5144               
#2 0x7f02ea8f3a21 in handle_ts_help_command ../libr/core/cmd.c:5129 …
```

Check node_string length before subtracting 2 from strlen

---

binr/r2r/load.c
binr/r2r/r2r.c
binr/r2r/run.c
libr/core/cbin.c
libr/core/cconfig.c
libr/include/r_util/r_str.h
libr/util/str.c

Before:
After:
**Test plan**
Eyeball diff output for tests that have leading space.
...

r2r: Don't trim whitespace from diff lines

---

libr/bin/format/pe/pe.c

Found by clusterfuzz
**Test plan**
merge the PR in r2bins and open the file
```
/Users/pancake/prg/radare2/libr/..//libr/bin/p/../format/pe/pe.c:3135:60: runtime error: signed integer overflow: 2147483647 + 1 cannot be represented in type 'int'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/pancake/prg/radare2/libr/..//libr/bin/p/../format/pe/pe.c:3135:60 in
/Users/pancake/prg/radare2/libr/include/r_endian.h:150:33: runtime error: addition of unsigned offset to 0x00012041d800 overflowed to 0x00002041d800
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior /Users/pancake/prg/radare2/libr/include/r_endian.h:150:33 in
AddressSanitizer:DEADLYSIGNAL
============================================================= …
```

Fix crash in PE when resolving corrupted ordinal exports ##bin

---

libr/asm/arch/pyc/opcode.c
libr/asm/arch/pyc/opcode.h
libr/asm/arch/pyc/opcode_15.c
libr/asm/arch/pyc/opcode_2x.c
libr/asm/arch/pyc/opcode_36.c
libr/asm/arch/pyc/opcode_3x.c

running make in mac resulst in about 300 warnings from the pyc disassembler
```
/Users/pancake/prg/radare2/libr/asm/arch/pyc/opcode_3x.c:155:79: warning: initializer overrides prior initialization of this subobject [-Winitializer-overrides]
def_op (.op_obj = ret->opcodes, .op_name = "MAP_ADD", .op_code = 147, .pop = 2, .push = 1); // Calls dict.setitem(TOS1[-i], TOS, TOS1)
^
/Users/pancake/prg/radare2/libr/asm/arch/pyc/opcode.h:125:95: note: expanded from macro 'def_op'
#define def_op(...) def_op((struct op_parameter){ .pop = -2, .push = -2, .fallthrough = true, __VA_ARGS__ })
^~~~~~~~~~~
/Users/pancake/prg/radare2/libr/asm/arch/pyc/opcode_3x.c:155:2: note: previous initialization is here
def_op (.op_obj = ret->opcodes, …
```

Fix ~300 warnings in the pyc disasembler

---

libr/anal/sign.c
test/db/cmd/cmd_zignature

In the function `print_list_type_body` two new JSON contexts are created if there are 2 or more items to print (see function `print_list_separator`). However, before return these two contexts are closed anyways, without respecting whether they were actually created, resulting in corrupt JSON under some circumstances.
**Test plan**
`rasign2 -aj /bin/ls | jq .`
*Before patch*
```
Error: Parse error on line 1:
...args","type":"1"}]}],"hash":{"bbhash":"f
-----------------------^
Expecting 'EOF', got ','
```
*After patch*
```
rasign2 -aj ls | jq . ; echo $?`
...
0
```
...

Bugfix: Zignatures corrupt JSON output in types

---

.github/stale.yml

This enables the stale bot https://github.com/probot/stale .
The bot checks all issues that didn't have **activity** in the last 700 days (2 years). Activity including any comments, reference from other issues, adding to milestones, etc.
In addition, issues with one of these Labels would not be closed. And you can suggest labels to the list by reviewing the PR
```
exemptLabels:
- architectures-enhancements
- enhancement
- New Architecture
- New File-Format
```
For these inactive issues that do not have one or more of these labels, it is adding a "_stale_" label, and adds a comment telling the community that this is an old issue and ask them to check whether it is still relevant:
_"This issue has been automatically marked as stale because it has not had recent activity. Considering a lot …

First version of stale file to automatically close old issues

---

libr/anal/p/anal_riscv.c
test/db/anal/riscv
test/db/formats/elf/elf-riscv64

Previous compressed instructions were not analysed.
**Test plan**
One test added.

Improve RISC-V analysis for compressed instructions

---

libr/util/table.c

Printing a table in fancy mode results in a glitchy ascii art, this patch makes it not print anything
**Test plan**
I have to create some unit tests for it
I have spotted this bug while doing the comma(nd)

Do not print malformed table if no columns are set

---

libr/bin/dwarf.c

See previous PR (#16850 #14593), this doesn't build unless -c99 is used for gcc.

Fix C99 construct without -c99

---

libr/core/linux_heap_glibc.c
libr/debug/debug.c
libr/include/r_debug.h

With this feature the heap commands for the glibc run faster, since they resolve the main_arena using the symbol from the glibc (if the glibc is compiled with symbols, otherwise it uses the bruteforce method which is slower).
I measured the time of the commands `dmh[ft]`:
1. Using the symbol: ~0.07 seconds
2. Without the symbol: ~1.10 seconds
Before I had an hard time to use the commands `dmht` and `dmhf` in `V!` mode because it took more than a second to refresh the view at every step, now it works fine.
This is an improvement but it doesn't solve the problem completely.
In fact on my machine if I try the command `dmh` before `dmh[tf]` is very slow, while the other way round is super fast.
Related to "#16248"

Heap glibc resolve main_arena using symbol

---

libr/cons/input.c

Output was not printed when `r_cons_yesno` was called.
Reproducer:
```
[0x00400de0]> pd 1234
Do you want to print 1257 lines? (y/N) y
[0x00400de0]> 
```
**Test plan**
Just try the reproducer, it should print 1234 lines of output (on any binary).

Fix r_cons_yesno. Key variable was never changed

---

libr/core/cmd_api.c
test/db/cmd/cmd_help

If root_cmddesc has `help` enabled, it will try to generate the help automatically. However, for now we don't have all the correct messages in place, so it would show wrong stuff.
By setting `help` to NULL we ensure that `?` just fallbacks to old command handler.

Fix root help in newshell

---

.github/workflows/debianold.yml
shlr/Makefile

Add Debian 8 (Jessie) Docker build to ensure radare2 works
on the older Debian-based systems too.
Along with CentOS 6 build, it makes sense to make sure radare2 works on the older Debian-based systems as well: Debian itself, old versions of Ubuntu, etc.
**Test plan**
All green.
...

Add Debian OLD (Debian 8 Jessie)

---

libr/core/cmd_debug.c
libr/debug/dreg.c

Putting double quotes between hexadecimal big numbers to make them JSON strings, because big numbers are not generally supported in JSON and string is good enough.
**Test plan**
Test that `drtj fpu` or any other register types outputs a valid json. I am thinking of including it in the json test. However, every time r2r runs, it says `Skipping json tests because jq is not available.`, although I have `jq` installed and tested. The `jq` process seems to always exit with an error code. I have found that the sourcehut ci does not run the json test as well. Is there a bug or configuration error?
closes #16635

Fix invalid json output for drtj command

---

binr/r2r/run.c

I found out that `jq` always exits with code 2 (usage error) and outputs its help message to `stderr`. This is because `r2r` writes the json to the `stdin` after `jq` ran. To fix this, we run `jq .` instead with the extra argument `.`, so `jq` will wait for inputs from `stdin` and parse them before exiting.
This was also explained in #17073 PR and also https://github.com/stedolan/jq/issues/1110.
**Test plan**
Instead of saying `Skipping json tests because jq is not available.`, `r2r` runs json tests when jq is available.
I could not find any issues related to this yet.

Fix non-working json tests in r2r ##test

---

libr/util/file.c

If `0` is an empty file:
```
% radiff 0 1
radiff2: Cannot open 0
```
This patch fixes it.
...
**Test plan**
...
...

r_file_slurp: don't choke on an empty file ##util

---

libr/main/radare2.c

Fixes
```
../libr/main/radare2.c: In function ‘r_main_radare2’:
../libr/main/radare2.c:873:35: warning: pointer targets in passing argument 3 of ‘r_io_write_at’ differ in signedness [-Wpointer-sign]
873 |    r_io_write_at (r->io, mapaddr, buf, sz);             
|                                   ^~~                                                  
|                                   |                                                    
|                                   char *                                               
In file included from ../libr/include/r_core.h:11,
from ../libr/main/radare2.c:12:                                               
../libr/include/r_io.h:334:58: note: expected ‘const unsigned char *’ but argument is of type ‘char *’
334 | R_API bool r_io_write_at …
```

Fix wrong type warning

---

libr/lang/p/pipe.c

This pr fixes the Windows #!pipe code so that it works.
This is the companion pr to radareorg/radare2-r2pipe#117.
**Test plan**
Tested with the following Python 3 script using the `. <script>` command:
```python
import r2pipe
r2 = r2pipe.open()
r2.cmd('aa')
print('\nFunction names:')
for func in r2.cmdj('aflj'):
print(func['name'])
print('\nDisassembly of entry0:')
print(r2.cmd('pdf'))
```
Further tests on other scripts welcome.
...
**TODO**

Fix Windows #!pipe

---

libr/core/cmd.c
test/db/cmd/cmd_interpret

interpretting a line uising a subcommand of ? it was failing 
**Test plan**
i added a test
none

Fix '.?e ?e msg' - interpret ? subcommands ##shell

---

libr/include/r_vector.h
libr/util/binheap.c
libr/util/vector.c

Insert is only valid when the index lies inside the vector or exactly one after it.
Fix #16730

Fix #16730 - Add bounds check to r_vector_insert ##util

---

libr/anal/p/anal_arm_gnu.c
libr/anal/p/anal_pyc.c
libr/anal/p/anal_tms320_c55x_plus.c
libr/core/cmd_debug.c

Fix GCC 10.1 warnings on Fedora 32.
Closes #17054

Fix some GCC 10.1 warnings

---

libr/core/cmd.c
test/db/cmd/cmd_search

This works fine in the newshell but not in the oldshell. this commit fixes it and adds a test
**Test plan**
Wait for travis
see pr title

Fix #2818 - Fix proper chopping of trailing spaces after comments

---

libr/bin/p/bin_dex.c
test/db/formats/dex

reading function arguments is causing many r_io_read calls for methods with > 1 arg. this can be simplified to make the code more readable as well as use strbuf instead of manual pointer mangling.
There's almost no real speedup gain, but the code is more optimal.
**Test plan**
i added a test
noine

Optimize and cleanup the dex_get_proto function ##bin

---

libr/anal/sign.c
test/db/cmd/cmd_zignature

command `zj` output mask is wrong, which was actually bytes
The root cause is at libr/anal/sign.c:1348
```
pj_ks (pj, "bytes", strbytes);
pj_ks (pj, "mask", strbytes);
```
here accidentally copy strbytes to mask rather than strmask
**Test plan**
...
...

Fix zignature mask from `zj` is differ from `z` (#17179)

---

.github/workflows/centos6.yml
.github/workflows/debianold.yml

It allows to run the following builds and tests 3 time a week - at Monday, Wednesday, Friday. Like Coverity, it will allow to spot bugs early rather than before the release:
- Debian Jessie
- CentOS 6

Check some OS 3 times a week

---

libr/lang/Makefile
libr/lang/lang.c
libr/lang/meson.build
libr/lang/p/spp.c
libr/lang/p/spp_r2.inc
libr/util/meson.build
libr/util/spp.mk
plugins.def.cfg
shlr/spp/Makefile
shlr/spp/p/spp.h
shlr/spp/r_api.c
shlr/spp/r_api.h
shlr/spp/spp.c
shlr/spp/spp.h
sys/rebuild.sh
test/db/cmd/cmd_interpret
test/scripts/r2test.spp

SPP is integrated into r2 already, but wasn't yet used as a templated lang extension, this way it is possible to write template files for markdown, html or just plain scripts with conditionals and run r2 commands inline.
I will refactor/rewrite SPP and add a proper testsuite for it, because the current code was supposed to be used as a standalone program and extended in a hacky way with globals to work inside r2 as a library. But it's not thread safe. But this will take a long run and its unrelated to this pr.
**Test plan**
I added a test, and the screenshot shows how to use that feature.
none. its a new feature

Implement RLang.spp for templated scripting ##lang

---

README.md

it's quite outdated/wrong
**Test plan**
is windows 7 the minimum windows supported?
What do you think about putting the release download links in the REAMDE?

Fix supported OS list from the README

---

binr/r2pm/r2pm
libr/main/radare2.c

When using r2 from non-git (release builds), installing packages can result in build problems. This PR aims to enable r2pm with the ability to pick the right commit from the tagged version from 3rd party repos if available.
Afaik this is done by r2ghidra-dec and r2dec-js, it may be good to define a different tag name than just the r2 version string, otherwise it will confuse users with the version of the decompiler and the veresion of the r2 required to build. so my suggestion is to use `r2-` as prefix in the 3rd party repos
**Test plan**
Get r2-4.4, replace the r2pm shellscript with the one in this PR, and type the following command:
```
$ r2pm -ci r2ghidra-dec
```
As you can see the PR also introduces r2 -H R2_VERSION, …

Initial support for git tags in r2pm ##r2pm

---

libr/anal/p/anal_gb.c

Fix OOB in the Gameboy instruction decoder ##anal

---

libr/core/anal_objc.c
libr/include/r_core.h
test/db/formats/mach0/objc

The aao command has been optimized a couple of times, based on the origin which was a Python script, the boost compared to the original script is more than 10 times faster. With this refactoring and cleanup I plan to make it even faster.
* [.] Use a single allocation instead of all the readQword calls (future optimization)
**Test plan**
There are objc tests for this already, but i may add another one and do proper benchmarking.
None

Optimize 'aao' objc analysis ##anal

---

libr/util/buf.c

Spotted in clusterfuzz-testcase-minimized-ia_fuzz-6301506113634304
**Test plan**
```c
$ cat shift.c
main() {
unsigned long long a=0x12389;
int i = 0;
while (1) {
a <<= i;
i++;
}
}
$ gcc -fsanitize=undefined shift.c
$ ./a.out
shift.c:8:5: runtime error: shift exponent 64 is too large for 64-bit type 'unsigned long long'
^C
```
two from coverity

Fix two shift overflow causing undefined behaviour

---

libr/search/aes-find.c
libr/search/privkey-find.c

If the function **r_search_privkey_update** return 0 when nothing is found, the search will stop after one block because the return value match with **r_search_hit_new** return value.
**Test plan**
I will update test binary in the repository to test that properly.

Correct output value for AES and private key search

---

libr/main/ragg2.c
test/db/tools/ragg2

Change the behavior of ragg2 to check for an empty string only after we know `file` is not NULL, making it closer to the purpose of the original commit without changing other behaviors of ragg2.
**Test plan**
Added tests for the scenario that was described by the user alex on IRC.
Closes #17201

Fix incorrect ragg2 empty string check

---

shlr/meson.build

This pr fixes the problem seen in #17197 and radareorg/sdb#209, i.e.
aka there is a BOM in my Windows sdb.
**Test plan**
...

Use type instead of Get-Content to prevent BOM insertion on sdb generation in Windows

---

binr/r2r/load.c
binr/r2r/run.c

Fix r2r crash on Windows if test doesn't have CMDS

---

libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/include/r_parse.h
libr/parse/filter.c
libr/parse/p/parse_arm_pseudo.c
libr/parse/p/parse_x86_pseudo.c
libr/parse/parse.c
test/db/anal/arm
test/db/anal/x86_64
test/db/cmd/cmd_ahi
test/db/cmd/cmd_att
test/db/cmd/cmd_pd
test/db/cmd/cmd_pd2
test/db/cmd/lea_intel
test/db/formats/elf/serial

On #16801, it was proposed to organize `asm~sub` to `asm.sub.*`. 
Here, I've renamed `asm.jmpsub` to `asm.sub.jmp` and renamed the node `jmpsub` to `subjmp`.
**Test plan**
A simple build from source will update the changes.
Related to #16801 
(Being a beginner, I was going through the 'good first issues'. Any forms of advices and opinions are welcome on this, as I'd like to work on the whole issue and remaining commands under this.)

Rename asm.jmpsub to asm.sub.jmp

---

libr/bin/format/elf/elf.c

During refactoring i forgot to add a default mips_pltgot value in the function `set_default_value_dynamic_info`.
**Test plan**
...
I didn't open any issue.

Add mips_pltgot default value

---

libr/include/r_io.h
libr/io/meson.build
libr/io/p/fd.mk
libr/io/p/io_fd.c
libr/meson.build
plugins.def.cfg

Useful for self:// and r2frida when injecting the lib inside a target process
This plugin was in the issues for a very long time, i saw it when it was pinged by the stalebot, so it was easy to implement
**Test plan**
Uhm maybe opening a file and assuming we get the right fd from the OS to manipualte it in live.. but there are no tests for libr2preload or self:// or for r2frida
Fixes https://github.com/radareorg/ideas/issues/116

Initial implementation of io.fd plugin ##io

---

.github/workflows/debianold.yml

Those binaries require the i386 libc6 to run. I included the package in the `apt install` command.
**Test Plans**
I tested it by setting up a `debian:jessie` docker container similar to the one specified in `debianold.yml`
closes #17227

Fix debug tests on Debian Jessie ##test

---

libr/include/r_th.h

Fixing the following warning during the compilation of `lang-python`:
```
cc python.c python/*.c -I/home/akochkov/.local/share/radare2/prefix/include -I/home/akochkov/bin/prefix/radare2/include/libr  -DPREFIX=\"\" -I/home/akochkov/bin/prefix/radare2/include/libr  -DPREFIX=\"\" -I/usr/include/python3.8 -I/usr/include/python3.8 -DPYVER=3 -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib -L/home/akochkov/bin/prefix/radare2/lib  -lr_core -lr_io -lr_util -shared -lr_asm \
-I/home/akochkov/bin/prefix/radare2/include/libr -L/home/akochkov/bin/prefix/radare2/lib -lr_core -lssl -lcrypto -lr_config -lr_debug -lr_bin -lr_anal -lr_bp -lr_egg -lr_asm -lr_lang -lr_parse -lr_flag -lr_reg -lr_search -lr_syscall -lr_fs -lr_io …
```

Avoid pesky warning

---

libr/bin/pdb/pdb_downloader.c
libr/core/cconfig.c
libr/core/cmd_info.c

* Add support for UNC paths as symbol servers on Windows
Closes #17137

Fix #17137 - Support multiple symbol servers with ';'

---

libr/core/canal.c
libr/core/cmd.c

It's a while I have these warnings on my system (Fedora 31):
```
[1090/1507] Compiling C object 'libr/core/f105261@@r_core@sha/canal.c.o'                                                                                                                      
../libr/core/canal.c: In function ‘is_skippable_addr’:                                                                                                                                        
../libr/core/canal.c:1943:45: warning: passing argument 3 of ‘r_list_find’ from incompatible pointer type [-Wincompatible-pointer-types]                                                      
1943 |  return !(flags && r_list_find (flags, fcn, find_sym_flag)); …
```

Fix compiler warnings

---

libr/core/cfile.c
test/db/archos/linux-x64/dbg_oo

Reinitialize debugger state when reopening in debug mode.
**Test plan**
* perform the steps described in #17212 testcase added
Closes #17212

Cleanup debugger state during restart.

---

libr/bin/format/mach0/mach0.c

* in this case the lib is mapped at 0 so the first executable section
> iS paddr/sort,perm/str/-r-x,vaddr/cols~:3
0x00000c30
see https://github.com/radareorg/radare2/pull/17195, macho libs show 1 entrypoint at adderss 0 when typing ie:
```
$ r2 /usr/local/lib/libr_util.dylib
-- License server overloaded (ETOOMUCHCASH)
[0x00000000]> ie
[Entrypoints]
vaddr=0x00000000 paddr=0x00000000 haddr=-1 type=program
1 entrypoints
[0x00000000]>
```
**Test plan**
need to add a test opening a lib and chking the entry0 if it exists and whcih is the initial seek address. we can add another flag for this instead of entry0 which is tied to the bin headers.
kind of related to https://github.com/radareorg/radare2/pull/17195

macho libraries don't have an entrypoint and 0 is not a valid address ##bin

---

libr/core/cconfig.c

On #14927, it was suggested to rename `anal.in`=raw to `anal.in=range` to honour `anal.in` and `anal.from`. I plan to solve the issue with this Pull Request.
**Test plan**
* The right direction in solving this, if I missed anything.
*  Guidance on `e.search.in` and `e.zoom.in` as it has the same options.
Closes #14927

Rename anal.in=raw to anal.in=range

---

libr/core/cannotated_code.c
libr/include/r_util/r_annotated_code.h
libr/util/annotated_code.c

This PR adds an annotation type (`R_CODE_ANNOTATION_TYPE_FUNCTION_NAME`) for function names in the decompiled code. This will be required for implementing some features in the decompiler in Cutter.
**Note**: I haven't modified tests so CI can fail during tests due to this. I will modify tests after getting feedback on this.
...
**Test plan**
1. Fetch and compile [PR #123](https://github.com/radareorg/r2ghidra-dec/pull/123) from r2ghidra-dec after compiling this PR.
...
...

Annotation for function name

---

.github/workflows/ci.yaml
.github/workflows/pr.yaml

Yesterday a new meson version was released, however it causes issues when used with coverage. See https://github.com/radareorg/radare2/runs/864707895 and https://github.com/mesonbuild/meson/issues/7437 .
This PR tries to fix the problem by ensuring we always use the same version of meson/ninja. Also, 0.52.0 should be more than enough at the moment to build the project.

Hardcode the version of meson/ninja to use to ensure consistency

---

libr/core/canal.c
test/db/anal/arm

in armv7, if data refs are not aligned do not mask.
finds data ref in https://github.com/radareorg/radare2-testbins/pull/34
- [] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
arm can make data misaligned, and it mustn't always be masked off, like code refs should be.
...
**Test plan**
verify that the data ref is calculated properly with esil analysis in https://github.com/radareorg/radare2-testbins/pull/34
...
none
...

Fix esil data refs in arm for misaligned data ##anal

---

libr/asm/arch/z80/z80.c
test/db/asm/z80

There is only one 8bit constant to read. Doesn't fix leak in z80 assembler that's a separate problem and requires more refactoring.
**Test plan**
Run `r2r db/asm/z80` with sanitizer and `ASAN_OPTIONS=detect_odr_violation=0:detect_leaks=0`
closes #17265

Fix OOB access in z80 disasm for "OP [ixy+nn]" instructions.

---

libr/io/p/io_self.c

Applying patch from Dports.
Using highr level api rather than querying direct fields which are
prone to changes.
Original author: @zrj-rimwis.

io_self update DragonFly support and fix one typo. ##libr

---

libr/bin/format/mach0/mach0.c
test/db/cmd/cmd_i

Solves https://github.com/radareorg/radare2/pull/17233
**Test plan**
theres a test
https://github.com/radareorg/radare2/pull/17233

Fix duplicated entry symbols in macho ##bin

---

libr/core/cmd_open.c
libr/core/core.c
test/db/cmd/cmd_open

This command was marked as deprecated for enough time
**Test plan**
Check if its not misused internally via rcore_cmd
dunno

Deprecate `obb` command and make `obo` use the file descriptor ##bin

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h
test/db/cmd/cmd_zignature

This is a refactor of some sign code. It will result in a speed increase on signature creation. It will also help me to expand the `zb` command soon.
Currently, `zaf` on a single function will result in around 8 `RSignItem`'s being create, saved and then freed. Saving each individually causes a name collision which requires reallocating old items and merging.
The `r_sign_addto_item` function was created so a single `RSignitem` can easily have signature types added to it. The `addItem` function was renamed and added to the `r_sign` API. Now the `zaf` command will only allocate a single `RSignitem`, signatures are added to the item with `r_sign_addto_item`. Since only one item is saved there are no collisions under normal …

rasign2 refactoring ##signatures

---

libr/anal/p/anal_cr16.c
libr/asm/arch/cr16/cr16_disas.c
libr/asm/arch/cr16/cr16_disas.h
libr/asm/p/asm_cr16.c

Who is the "owner" of this assembler? I don't even know what this architecture is about... However, this whole disassembler is missing any check on the length at all. It is completely ignored
**Test plan**
...
Closes https://github.com/radareorg/radare2/issues/17285

Check length before disassembling cr16 instructions ##asm

---

libr/anal/type_dwarf.c
libr/bin/dwarf.c

Fixed OOB read and leak in dwarf code base based on ASAN and valgrind findings when executing 
"radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Qc 'CL 0x0000a24e
' bins/mach0/TestRTTI-armv7-dSYM"

DWARF - fixed OOB read and memory leak

---

libr/util/sys.c
libr/util/thread.c

backtrace is supported w/o external lib.
thread affinity implementation.

complete a bit better illumos support ##libr

---

libr/core/agraph.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd_debug.c
libr/core/cmd_info.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/include/r_io.h

ive removed io.debug, but there's still bin.is_debugger, which should be addressed in a separate PR (and discussed) because imho rbin should autodetect if its loading a memory dump of the process state without having any special flag.
ill wait to address the bin.is_debugger thing after this PR gets merged.
**Test plan**
wait for the green
fixes this one:
https://github.com/radareorg/ideas/issues/294

Fix #ideas-294 - Remove RIO.debug

---

libr/anal/type_dwarf.c

radare2 do not build without -std=c99 on the version of GCC I used. But, plot twist, I tried to add -std=c99, and it fail to build for others reasons. So I am fixing this code for the time being, while trying to fix it for good later.

Fix build without -std=c99

---

.appveyor.yml
.github/workflows/centos6.yml
.github/workflows/ci.yaml
.github/workflows/newshell-treesitter-tests.yml
.github/workflows/pr.yaml
.github/workflows/static.yml
.travis.yml
libr/core/cannotated_code.c
libr/include/r_util/r_annotated_code.h
libr/util/annotated_code.c

This PR implements annotations for constant and global variables. As of now, the only information that is stored in the annotation is the address of the constant/global variable. The actions in Cutter that we will be having using these annotations is to add/rename/delete flags at the address of constant/global variables. See the corresponding PR[ #124](https://github.com/radareorg/r2ghidra-dec/pull/124) in r2ghidra-dec
...
**Test plan**
...
...

Annotations for Constant Variables and Global Variables for the decompiler

---

test/db/cmd/cmd_zignature

I added the following tests to cmd_zignature:
x86-64 function with hole
x86-64 function with jumpback
x86-64 r_sign_fcn_bytes bounds check
80386 function with hole
80386 function with jumpback
80386 r_sign_fcn_bytes bounds check
MIPS R3000 function with hole
MIPS R3000 function with jumpback
MIPS R3000  r_sign_fcn_bytes bounds check
PowerPC function with hole
PowerPC function with jumpback
PowerPC r_sign_fcn_bytes bounds check
ARM function with hole
ARM function with jumpback
ARM r_sign_fcn_bytes bounds check
ARM aarch64 function with hole
ARM aarch64 function with jmpback
ARM aarch64 r_sign_fcn_bytes bounds check
Mostly this checks edge cases when creating byte signatures. I manually double checked that the output was …

Add tests for creating #signatures

---

libr/io/p/io_gdb.c

see shlr/gdb/src/packet.c
**Test plan**
justt see compiler output. its a warning
none, but it may behave wrong because of UB
...

Fix wrong function signature in io.gdb

---

libr/util/Makefile
libr/util/meson.build
libr/util/sys.c

backtrace is available but not as system library but third party package.

backtrace support for haiku ##port

---

libr/bin/dwarf.c

Fixes #17304 and incorrect line information parsing of special opcode and standard const add pc opcode.

DWARF - OOB read and multiple incorrect parsing fixes

---

libr/util/udiff.c

Fixes the following warnings:
(e.g. https://github.com/radareorg/radare2/runs/887292162#step:9:326)
**Test plan**
Builds are warning-free with regard to the above.
...

Fix udiff.c warnings

---

libr/anal/bb.c
test/db/cmd/cmd_seek

The `r_anal_get_bbaddr` function was just a wrapper for `r_anal_get_block_at` . This is incorrect since `r_anal_get_block_at` wont return a block if the provided address is not the block entry point. This mistake causes `VV` to get lost if you current seek is in the middle of a block. 
This PR fixes the problem and ads a regression test using the `sb` command.
**Test plan**
The `sb` command relies on  `r_anal_get_bbaddr`, so you can test for off by one errors by seeking to tricky addresses. Below shows an example of `sb` performing correctly when at main-1, main, main+1, main+blocksize-1 and when you seek to the second block.
```
$ r2 test/bins/elf/vim 
-- ---8<--------------------8<------------------8<-----------------8<--- …
```

Fix r_anal_get_bbaddr to include internal addrs ##anal

---

libr/core/cmd_anal.c

aaa runs aao on any binary, aao is smart enough to not do anything if there are missing sections and such, but aaa is not that smart. this piece of code makes that work only on macho-arm,ppc-x86 bins. any other target or objc programs? (i know there's opensource objc, but this is probably using a different format for that objc section.
**Test plan**
...

Only run aao in aaa on apple targets ##bin

---

libr/core/linux_heap_glibc.c

With the pull request https://github.com/radareorg/radare2/pull/17018 we can resolve the main arena using the symbol from the glibc, however if the glibc is not compiled with all the symbols (ex. ubuntu 20) then main arena is found with a bruteforce. With this pull request is possible to compute the main arena using the malloc_hook symbol (this symbol can be found inside the glibc of ubuntu) and this method is faster than the bruteforce.
With bruteforce:
```
[0x00401364]> ?t dmht
1.229636
```
With malloc hook symbol:
```
[0x00401364]> ?t dmht
0.107265
```

Speedup (10x) glibc's main arena resolution using malloc hooks ##debug

---

libr/include/r_bin_dwarf.h

Fix compilation on CentOS 6. RBin is already forward declared at the
beginning of r_bin.h. RAnal is not used.
See https://github.com/radareorg/radare2/runs/899717533?check_suite_focus=true

Remove (again) wrong forward declarations

---

libr/util/udiff.c

I saw issue #17237 and took a look. I could not get the unit test to run but I spotted an unhanded edge case which the test uses. This PR will fix the case when one or both provided buffers are of length 0.
**Test plan**
I couldn't get the unit tests to run, but this works now:
```
radiff2 -ss /tmp/tests/1/*
File size differs 5 vs 0
similarity: 0.000
distance: 5
```
Previously distance was reported as 0.
Maybe #17237 ?

Fix Levenstein distance on empty buffers ##radiff2

---

libr/anal/class.c
libr/core/cmd_anal.c
libr/include/r_anal.h

I've added option to print "acll" information about single class
```
[0x00001120]> acl
Bat
Bird
Cat
Dog
Kappa
Mammal
[0x00001120]> acll Bat
Bat
(vtable at 0x3b98)
(vtable at 0x3bc0)
virtual_0 @ 0x192e (vtable + 0x0)
virtual_8 @ 0x1967 (vtable + 0x8)
virtual_16 @ 0x146c (vtable + 0x10)
[0x00001120]> ac?
Usage: ac  anal classes commands
| acl[j*]                                                    list all classes
| acll (class_name)                                        list all or single class detailed
```

Add `acll (class_name)` to print class information ##anal

---

libr/bin/dwarf.c
libr/cons/cons.c
libr/include/r_cons.h

There was a segfault linked to a very large binary with DWARF information (http://xvilka.me/vmlinux_ida_dwarf_fail.zip) when using `id`. It was caused by the information being over several GiB of text and r_cons_context using `int` for it's size and length, changing it to ut64 fixed the segfaulting behaviour.

r_cons_print fix for very large output ##cons

---

libr/core/cmd_api.c
libr/include/r_cmd.h
test/unit/test_cmd.c

Commands can be unregistered in some cases, for example by plugins. This provides an API to unregister those commands.
**Test plan**
...
Closes https://github.com/radareorg/radare2/issues/16931

Add r_cmd_desc_remove API to unregister commands

---

libr/socket/r2pipe.c
test/unit/meson.build
test/unit/test_r2pipe.c

Passing null on failed initializations caused an unhandled crash, this patch aims to r_return_ify the r2pipe C API.
**Test plan**
There are no tests for the C api of r2pipe, and i am aware of some improvements that must be done in this API to be considered stable. But having a null deref is a no-go. I will update the PR adding tests and improving the capabilities of the client side api for r2pipe.
None

Add more null checks and fix a lock when no r2 in path ##r2pipe

---

libr/core/cmd_debug.c
libr/include/r_io.h
libr/include/r_util/r_sys.h
libr/io/p/io_debug.c
libr/main/radare2.c
libr/socket/run.c
libr/util/sys.c

Duplicate and save the original `environ` and use it for `execvpe` later in `io_debug` so the child process will not inherit the `environ` of `r2`. 
**Test plan**
Run `env -i /usr/local/bin/r2 -c dc -d /usr/bin/env` and check for empty outputs. However, afaik there is no way to run command like that in the test suite. This test should be done in debug mode, so a custom binary is required to check for environment variables set by `r2` and one of which is in `PATH`. But, this way will make the test depends on the binary and any changes in future will require the binary to be replaced to make the test valid which is too troublesome. I would be glad to receive any suggestion on this.
closes #16359

Fix debugee to inherit original environment variables ##debug

---

.github/workflows/debianold.yml

Currently we test periodically only the Debian 8 (Jessie). Adding the job to test also with Debian 7 (Wheezy).
Inspired by:
- https://github.com/radareorg/cutter/issues/2316
- https://github.com/radareorg/radare2/pull/17345
You can see actual building logs here: https://github.com/radareorg/radare2/runs/906280908?check_suite_focus=true

Add periodic CI job for testing also on Debian Wheezy along with Jessie

---

binr/r2r/meson.build
libr/core/meson.build
meson.build
shlr/meson.build
test/unit/meson.build

Compiling radare2 on older systems like CentOS 6 or Debian:Wheezy resulted in errors due to missing reference to clock_gettime. This was fixed for acr/make in a29f0ccce5b0281a89ab3aff174fcbf07a477054 . This PR fixes it for meson as well.
**Test plan**
Try to compile radare2 on centos:6 container with meson.
This partially fix https://github.com/radareorg/cutter/issues/2316 (only the r2 part of the problem).

Support compilation with meson on old systems like CentOS6/DebianWheezy ##build

---

libr/anal/p/anal_arm_cs.c
test/db/esil/arm_16
test/db/esil/arm_32

- [*] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [*] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [*] I've added tests that prove my fix is effective or that my feature works (if possible)
Indentation fixed by script
Added support for :
- ARM_INS_CLZ
- ARM_INS_LDRB
- ARM_INS_SBC
- ARM_INS_TBH
- ARM_INS_TBB
Fixed:
- ARM_INS_IT (partial)
- ARM_INS_BLX (consider thumb)
- ARM_INS_ASR
- ARM_INS_LSL
- Update flags for CMP
Tested against binary running on target, seems to solve lot of issues yet.
Credits also goes to @Baldanos who contributed to this pull request

Improve ESIL support for ARM (clz, ldrb, sbc, tbh, tbb, it, blx, asr, lsl, cmp) ##anal

---

libr/bin/format/mach0/mach0.c

Th eoriginal purpose of this PR has changed. it is now a cleanup and random cleanup
* Use more size_t for loop variables
* Fix a memleak in checkSym
* remove unused variables
There are more bugs like using globals and such, will be slowly addressing them all
**Test plan**
nothing must break after merging this
nope but the code is full of bugs

Use more size_t in the MACHO parser ##bin

---

.github/workflows/pr.yaml
libr/core/cmd.c
shlr/radare2-shell-parser/corpus/simple_commands.txt
shlr/radare2-shell-parser/grammar.js
shlr/radare2-shell-parser/src/grammar.json
shlr/radare2-shell-parser/src/parser.c
test/db/anal/x86_32
test/db/cmd/cmd_zignature
test/db/cmd/feat_grep

newshell parser can directly parse multi-line scripts. Even more, trying to split scripts manually may result in wrong behaviour. This PR finally enables the use of newshell even for multi-line commands. On the way, it also fixes a bug linked below.
**Test plan**
...
Fixes https://github.com/radareorg/radare2/issues/16684

Directly pass multi-lines command to newshell ##newshell

---

libr/lang/p/pipe.c
test/db/cmd/cmd_pipe

This pr replaces the busy-wait on PeekNamedPipe() in the Windows #!pipe code that was noted in https://github.com/radareorg/radare2/pull/17139#issue-438658733, i.e. https://github.com/radareorg/radare2/blob/b25c3275dee4543e2464de60f58e8f279d9eed87/libr/lang/p/pipe.c#L68-L70 with overlapped I/O.
**Test plan**
...

Windows #!pipe: Remove busy-wait on PeekNamedPipe()

---

libr/util/sys.c

The pr adds an error code to the Windows r_sys_perror() string, to make it easier to look up and confirm the id of the error in the [System Error Code table](https://docs.microsoft.com/en-us/windows/win32/debug/system-error-codes#system-error-codes). Example output:
**Test plan**
...

Windows r_sys_perror: Add error code to string

---

libr/util/sys.c

This pr prevents blank lines after r_sys_perror() error messages on Windows.
**Test plan**
Replace the following line: https://github.com/radareorg/radare2/blob/fca4fa618064eec5f10d436bc425d4d62b4cbf88/binr/r2r/run.c#L202
with
```c
r_sys_perror ("CreateProcess failed");
```
and run r2r on Windows with no jq in PATH. There should be no blank lines after the "CreateProcess failed" messages.
...

Windows r_sys_perror: Don't add end newline if an end newline already exists

---

libr/core/cannotated_code.c
libr/include/r_util/r_annotated_code.h
libr/util/annotated_code.c

This PR adds annotation for local variables and function parameters. The data we have for each variable is the location of the variable in the code and the name of the variable. This will suffice for implementing retype local variables action in the decompiler widget in Cutter.
...
**Test plan**
1. Compile this PR.
2. Fetch [PR #128](https://github.com/radareorg/r2ghidra-dec/pull/128) from r2ghidra-dec and compile it. 
3. Follow the test plan in the PR linked in step 2.
4. Check code.
...
...

Annotation for local variables

---

libr/bin/format/elf/elf.c

Not sure where the file comes from, can we add it to our tests? @SjRNMzU 
So, let's start by saying that I think the whole ELF symbols/imports retrieval is really really hacky and probably wrong in some cases, always because of the same issue that things are taken from the sections first and then "adjusted" with the info of phdr (it should be the opposite).
This problem was quite hard to debug, because ASAN/valgrind for some reason could not detect the issue at all, but there was buffer overflow. Function `_r_bin_elf_get_symbols_imports` has an initial loop where it computes `import_ret_ctr`, then it calls `fix_symbols` and then it allocates an array `import_ret` of size `import_ret_ctr`, copying elements from `ret`. …

Fix #17379 - Avoid buffer overflow while identifying imports

---

libr/io/p/io_self.c
libr/rules.mk

using libproc to get proper mapping names to match better Linux version.

io_self: giving more meaningful mapping names when possible ##port

---

libr/cons/cons.c

On Windows Terminal, the escape sequences to disable mouse tracking is emitted even though the mouse is already disabled. This at least messes up test runs when `!radare2` is used. This pr prevents that.
**Test plan**
Run `r2r -i db/tools/r2` under Windows Terminal.
...

Don't disable (enable) mouse if mouse is already disabled (enabled)

---

libr/include/r_util/r_annotated_code.h
libr/util/annotated_code.c

This PR implements the following two functions. Read the documentation below.
```
/**
* is_annotation_reference() - Checks if the specified annotation is a reference.
* @annotation: Pointer to an annotation.
* 
* This function recognizes the type of the specified annotation and returns true if its
* type is any of the following three: R_CODE_ANNOTATION_TYPE_GLOBAL_VARIABLE,
* R_CODE_ANNOTATION_TYPE_CONSTANT_VARIABLE, R_CODE_ANNOTATION_TYPE_FUNCTION_NAME
* 
* Return: Returns true if the specified annotation is a reference.
*/
R_API bool is_annotation_reference(RCodeAnnotation *annotation);
/**
* is_annotation_variable() - Checks if the specified annotation is a function variable.
* @annotation: Pointer to an annotation.
* 
* …
```

API for checking if an annotation is a reference or function variable.

---

libr/anal/base_types.h

Remove tokens after #endif to remove warnings as shown here #17384

Remove warning about extra tokens after #endif

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h
test/db/cmd/cmd_zignature

This adds the bytes signature into the the `zb` command to find the top `n` closest matching signatures. The bytes comparison is done by the Levenshtien distance. The Levenshtien algorithm is slow, so the difference in signature lengths is considered first to see if the Levenshtien algorythm is even necessary.
Example on known `strdup` and `fclose` functions in a statically compiled binary against signatures from the known libc version.
```
[0x0041e390]> z* ~ g cc=?
3149
[0x0041e390]> s sym.strdup 
[0x0041e390]> zb
1.00000  1.00000 B  1.00000 G   sym.__strdup
0.95000  0.91176 B  0.98824 G   sym.wcsdup
0.92754  0.86957 B  0.98551 G   sym.strndup
0.77465  0.55556 B  0.99375 G   sym.envz_remove
0.73906  0.51562 B  0.96250 G …
```

Add bytes to zb command ##signatures

---

libr/include/r_core.h
libr/include/r_util/r_annotated_code.h

Earlier, I had used kernel-docs documentation style for documenting new API functions created for the annotations in the decompiler. This PR replaces these documentations by Doxygen. 
...
**Test plan**
1. Make sure this compiles properly.
2. Read the documentation and make sure nothing is wrong.
...
...

Update docs in annotate code API 

---

test/unit/test_annotated_code.c

This PR implements unit tests for the following API:
1. `r_annotation_is_reference()`
2. `r_annotation_is_variable()`
3. `r_annotation_free()`
4. JSON printing for context-related annotations.
...
**Test plan**
1. Run `make unit` from the test directory and make sure tests pass.
2. Check code.
3. Try to see if I should implement tests for anything else related to `RAnnotatedCode`.
...
...

Unit tests for annotated code API

---

libr/anal/type_dwarf.c
libr/bin/dwarf.c

Fix for #17383 
In case the string pointer into debug_str isn't valid, the string can be NULL which wasn't accounted for in the future type parsing, I've added the handling for this situation.

Fix malformed DWARF crash due invalid .debug_str reference ##bin

---

libr/anal/rtti_itanium.c

While running valgrind during `aaaa` command I've noticed that valgrind complains:
```
==65046== Conditional jump or move depends on uninitialised value(s)
==65046==    at 0x4A4082D: _itoa_word (_itoa.c:179)
==65046==    by 0x4A5C6F4: __vfprintf_internal (vfprintf-internal.c:1687)
==65046==    by 0x4A71119: __vsnprintf_internal (vsnprintf.c:114)
==65046==    by 0x494DA56: sdb_fmt (fmt.c:33)
==65046==    by 0x62D29AD: r_anal_class_vtable_set (class.c:871)
==65046==    by 0x630A93D: recovery_apply_vtable (rtti_itanium.c:571)
==65046==    by 0x630AA7A: r_anal_rtti_itanium_recover_all (rtti_itanium.c:595)
==65046==    by 0x63065FF: r_anal_rtti_recover_all (rtti.c:94)
==65046==    by 0x5ACBC20: cmd_anal_rtti (cmd_anal.c:9538) …
```

Fix move based on uninitialized value in rtti_itanium ##anal

---

libr/anal/vtable.c
test/db/anal/ppc

I've been testing out the VTable, RTTI detection and parsing, I've tried some exotic Arches and found that sometimes only some Vtables are found, so far we assumed that vtable always have to be in the same section as a vtable, but in some binaries (PowerPC one, some RTTIs were in the .rodata and others were in .sdata) that wasn't the case, I've relaxed the requirement so we only check if the RTTI pointer points to an initialized data section which improved the detection. But I don't know how to properly detect such section in Radare, I got inspired by the implementation for possible Vtable section.
I've looked into Retdec way and they only seem to check if RTTI is a valid pointer somewhere in the binary and then they parse …

Change Itanium VTable detection heuristic ##anal

---

binr/r2pm/r2pm

This pr prevents a `git clone` due to R2PM_GIT while cleaning. This is especially bad when doing `r2pm -ci` on a fresh install (and a cleanable package) because the package repo is cloned twice.
**Test plan**
Eyeball `r2pm -ci`.
...

r2pm: Don't clone while cleaning

---

libr/anal/rtti_itanium.c
test/db/anal/classes

We have RTTI parsed, but we are not using any information about base classes, this PR adds information about the bases from the RTTIs
example:
```
// before
[0x00400a20]> avrr
[0x00400a20]> acl
Bat
Bird
Cat
Dog
Kappa
Mammal
// after
[0x00400a20]> avrr
[0x00400a20]> acl
Bat: Bird, Mammal
Bird
Cat: Mammal
Dog: Cat
Kappa: Cat
Mammal
```

Add base class information from RTTI into anal classes ##anal

---

libr/anal/class.c
libr/anal/meson.build
libr/core/agraph.c
libr/core/cmd_anal.c
libr/include/r_agraph.h
libr/include/r_anal.h
libr/include/r_util/r_graph.h
libr/util/graph.c
test/unit/meson.build
test/unit/test_agraph.c
test/unit/test_anal_class_graph.c

So I was thinking about adding ability to print out class hierarchy graph, based on class information in anal/classes
I've made a rough idea, I still need to look into agraph implementation more so I can make it look better, maybe add other options, this was made just by looking at the agraph interface to sketch it out. What do you think?
PS: I know dogs don't come out of cats
Example now:
```
[0x00001120]> acl
Bat
Bird
Cat
Dog
Kappa
Mammal
[0x00001120]> acb Bat Bird
[0x00001120]> acb Bat Mammal
[0x00001120]> acb Kappa Cat
[0x00001120]> acb Dog Cat
[0x00001120]> acb Cat Mammal
[0x00001120]> acg
┌────────────────────┐    ┌────────────────────┐
│  Bird              │    │  Mammal            │
└────────────────────┘ …
```

Add `acg` - printing class hierarchy graph ##anal

---

libr/core/cbin.c
libr/core/cmd_info.c
libr/include/r_core.h
libr/util/file.c
test/db/formats/pdb

From telegram:
```
a> Hi guys.
a> I have a question.
a> When using radare2 with -B to set the correct base address the function names are not presented when I load the pdb
a> Without the -B everything works perfectly
a> 
```
**Test plan**
see tests
#17322

Fix #17322 - Honor bin.baddr from idp to load rebased PDB files ##bin

---

libr/util/file.c

`mkstemps()` was added only in GLIBC > 2.19, see https://man7.org/linux/man-pages/man3/mkstemp.3.html
To support earlier version it should be emulated manually
**Test plan**
It should build with Debian Lenny: https://github.com/XVilka/debian-oldies/tree/master/lenny
Just run "./build" there for the Docker container to build radare2

mkstemps() is available only since glibc 2.19

---

libr/io/p/io_ptrace.c

[Debian Etch](https://wiki.debian.org/DebianEtch) has old glibc (2.2.3 for example) that doesn't define `PTRACE_GETSIGINFO`, but Linux kernel already supports this value - it appeared in linux-2.3.99-pre6 while Etch has linux-2.6.18.
I skimmed through history and it seems value didn't change since - it's `0x4202` for all this time. Thus, we define it manually for these older distributions.
**Test plan**
It should build with Debian Etch: https://github.com/XVilka/debian-oldies/tree/master/etch
Just run "./build" there for the Docker container to build radare2

Add missing `PTRACE_GETSIGINFO` for old glibc

---

binr/r2pm/r2pm

This pr allows r2pm package scripts to do their own cleaning of their git dir.
**Test plan**
Add the following to the r2dec package script before R2PM_END:
```sh
if [ "$ACTION" = clean ]; then
rm -rf "${R2PM_GITDIR}/r2dec-js"
DONE=1
fi
```
and then run `r2pm -ci r2dec`. There should be no error message stating that the r2dec git dir cannot be found.
This is currently necessary for cleaning because the git dirname (`r2dec-js`) is hardcoded in the r2dec source.
...

r2pm: Allow package script to declare cleaning is done

---

libr/core/cmd_anal.c

Add help for `axtj`, `axt*`, `axtq` and `axtg`
**Test plan**
Right now, `axt?` returns nothing. With this, `axt?` returns:
```
[0x00000100]> axt?
Usage: ax[?gq*]  find data/code references
| axtj [addr]  find data/code references to this address and print in json format
| axtg [addr]  display commands to generate graphs according to the xrefs
| axtq [addr]  find and list the data/code references in quiet mode
| axt* [addr]  set flags on the corresponding xrefs
| axt?         Show this help
```
For the radare2book, I had put a PR regarding this on [#263](https://github.com/radareorg/radare2book/pull/263)
None

Add help under `axt?` ##cons

---

libr/core/cmd_anal.c

Use floating point during coverage percentage calculation to avoid overflow. 
Triggering the problem requires analyzing quite large executable so I don't it's practical to have automated test for it.
**Test plan**
Tested using blender executable (82MB) from ArchLinux repository.
* `aa`
* `aaij`
Before
```
[0x00d00560]> aaij
{"fcns":89083,"xrefs":1053522,"calls":588786,"strings":1348,"symbols":84802,"imports":1842,"covrage":35230923,"codesz":69489608,"percent":-11}
```
After
```
[0x00d00560]> aaij
{"fcns":89083,"xrefs":1053522,"calls":588786,"strings":1348,"symbols":84802,"imports":1842,"covrage":35230923,"codesz":69489608,"percent":50}
```
Closes #17385

Use floating point for coverage percent calculation.

---

libr/anal/rtti_itanium.c

Fix left build warnings from #17365 
```
rtti_itanium.c:592:10: warning: enumeration values 'R_TYPEINFO_TYPE_UNKNOWN' and 'R_TYPEINFO_TYPE_CLASS' not handled in switch [-Wswitch]
switch (cti->type) {
^
rtti_itanium.c:622:18: warning: incompatible pointer types assigning to 'RListFree' (aka 'void (*)(void *)') from 'void (class_type_info *)' (aka 'void (struct class_type_info_t *)') [-Wincompatible-pointer-types]
rtti_list->free = rtti_itanium_type_info_free;
^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
2 warnings generated.
```

Fix build warnings in rtti_itanium.c ##anal

---

libr/anal/p/anal_arm_hacks.inc
libr/asm/p/asm_arm_hacks.inc

The line `ut32 *insn = (ut32 *)buf;` assumes a buffer length `>=4`. This leads to an overflow on the following line according to Asan. This PR will bail out of the function early. There is probably a better way to handle this, but this will fix the overflow.
**Test plan**
Ensure it is ok to return -1 here.
closes #17414

Fix #17414 heap overflow hackyArmAnal

---

.appveyor.yml
doc/windows.md
sys/meson.py

The recent SDB header PR #17249 required an update to meson.py's manual installation paths. This PR replaces the dist building functions in the script with meson's install command to avoid modifying file paths each time include dirs are added.
**Test plan**
Build r2 using sys/meson.py. This solves an issue when building r2 with Cutter so you can also run Cutter's prepare_r2.bat and then run build.bat.

Use meson install instead of manual installation in meson.py

---

binr/r2r/run.c
libr/include/r_util/r_sys.h
libr/util/sys.c

Wall clock time is conceptually wrong for measuring time deltas. This adds a portable function for monotonic time.
**Test plan**
r2r should still show the elapsed time correctly on exit.
Fix #17264

Add r_sys_now_mono() and use in r2r ##util

---

libr/anal/p/anal_mips_gnu.c

We should judge Bit Endianness before analyzing
**Test plan**
Will be tested after fixing the load instruction later because it seems difficult to test separately
closes #17413

Fix mips.gnu did not judge Bit Endianness before instruction analysis ##anal 

---

libr/anal/sign.c

This fixes multiple leaks in `r_sign_deserialize` and `r_sign_item_free`. The `r_sign_deserialize` function will be more strict and skip over poorly formatted signatures, rather then try to parse them. When a signature is skipped because of poor formatting a descriptive error sent to stderr.
**Test plan**
`r2r ./db/tools/rasign2` and `r2r ./db/tools/rasign2` complete quickly, with no errors, on my system. 
I added a `#define` that may be considered ugly. If you don't like it, let me know how I can make it better.
closes #17418
~~There appears to be (I think) a minor leak in `r_sign_fcn_types` as called by `sign.c:typesMatchCB`. The leak can be avoided with `e sign.types = false`. I will create a separate …

Fix #17418 leaks in ##signatures

---

libr/io/p/io_ptrace.c

Enable is_pid_already_attached for NetBSD ##io

---

libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/linux/linux_coredump.h
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_debug.h
libr/debug/p/native/linux/linux_ptrace.h

A continuation of https://github.com/radareorg/radare2/pull/17416. [Debian Etch](https://wiki.debian.org/DebianEtch) has old glibc (2.2.3 for example) that doesn't define `PTRACE_GETSIGINFO`, `PTRACE_SETSIGINFO`, `PTRACE_O_*` flags, but Linux kernel already supports this value - it appeared in linux-2.3.99-pre6 while Etch has linux-2.6.18.
**Test plan**
It should build with Debian Etch: https://github.com/XVilka/debian-oldies/tree/master/etch
Just run "./build" there for the Docker container to build radare2
**Original error**
See https://github.com/XVilka/debian-oldies/issues/1:
```
In file included from p/debug_native.c:65:
p/native/linux/linux_debug.h:112:1: warning: "TRAP_BRKPT" redefined
In file included from …
```

Define PTRACE_O_* flags for old glibc

---

binr/r2pm/r2pm

This pr exposes r2pm's gitdir-cleaning code for use by package scripts. Example usage below.
**Test plan**
Add the following to the r2dec package script before R2PM_END:
```sh
if [ "$ACTION" = clean ]; then
R2PM_AUTOCLEAN_GITDIR=0
R2PM_CLEAN_GITDIR "r2dec-js"
RC=$?
fi
```
and then run `r2pm -ci r2dec`. There should be a message stating that the `r2dec-js` dir is being cleaned.
...

r2pm: Allow reuse of gitdir-cleaning code in package scripts

---

libr/asm/arch/include/mybfd.h
libr/asm/arch/mips/gnu/mips-dis.c

Just add some missing entries inside mybfd.h and mips-dis.c from latest source code of binutils, for loongson MIPS processor support. 
**Test plan**
...
...

Append missing loongson 2e/2f entries in mips-dis.c and mybfd.h

---

sys/sdk.sh

SDB headers are not included in the sdk, so all the projects using the sdk are broken. this patches solves the problem
**Test plan**
sys/sdk.sh ; find r2sdk | grep sdb.h
none registered

Fix sys/sdk.sh after the sdb refactoring

---

libr/util/pkcs7.c
libr/util/x509.c

I was following [Windows Authenticode Portable Executable Signature Format](https://download.microsoft.com/download/9/c/5/9c5b2167-8017-4bae-9fde-d599bac8184a/authenticode_pe.docx) to verify which fields are mandatory and which are optional, and added further verifications to make sure  that objects that were not initialized correctly, will be dropped.
...
**Test plan**
...
Closes #17431

Fix null dereference in Pe64_bin_pe_compute_authentihash

---

libr/cons/html.c
test/unit/test_cons.c

Old implementation didn't handle well mix of text and background color changes.
**Test plan**
* Unit tests work
* disassembly output in Cutter which uses cons_html_filter isn't broken
...

Improve cons_html_filter.

---

libr/core/canal.c
libr/debug/p/native/linux/linux_debug.h

A continuation of https://github.com/radareorg/radare2/pull/17459. Continuing to bringing radare2 to the older platforms - older GCC and Glibc.
**Test plan**
It should build with Debian Etch: https://github.com/XVilka/debian-oldies/tree/master/etch
Just run "./build" there for the Docker container to build radare2
**Original error**
```
In file included from p/native/linux/linux_debug.c:14:
p/native/linux/linux_debug.h:112:1: warning: "TRAP_BRKPT" redefined
In file included from /usr/include/signal.h:212,
from /radare2-master/libr/include/r_util/r_signal.h:5,
from /radare2-master/libr/include/r_cons.h:16,
from /radare2-master/libr/include/r_diff.h:6,
from /radare2-master/libr/include/r_util.h:7,
from …
```

Older GCC/Glibc warning fixes

---

libr/anal/p/anal_mips_cs.c
test/db/anal/mips

When the target file does not have loc._gp and the daddu instruction appears when calculating gp, a GP value calculation error will occur.
Such as the following instruction sequence:
```
0x000023d0      25c8e003       move t9, ra                 ; [11] -r-x section size 127280 named .text
0x000023d4      01001104       bal 0x23dc
0x000023d8      00000000       nop
0x000023dc      25908003       move s2, gp
0x000023e0      04001c3c       lui gp, 4
0x000023e4      24cc9c27       addiu gp, gp, -0x33dc
0x000023e8      2de09f03       daddu gp, gp, ra
```
[my test file](https://github.com/junchao-loongson/test-bin/raw/master/ld-nogp)
s 0x000023ec
pd 10
```
0x000023ec      25f82003       move ra, t9
0x000023f0      208084df …
```

Handle DADDU instruction MIPS, used for GP calculation ##anal

---

libr/core/project.c
test/db/cmd/cmd_project

I made radare projects reload their binary if the project was not saved in debug mode. This patch fixes a problem that makes radare2 projects unusable because radare won't load any binary when the project is loaded.
This patch does not reload projects that are opend in debug mode.
This patch does not work if the binary is emulated.
#17270 that is also me
...
**Test plan**
I have added a new test to test/db/cmd/cmd_project the test opens a file adds a comment, saves a project and then reopens it the comment should still be there or else the test will fail.
I have had this issue a while ago #16353 
...

Reload file when opening a project ##projects

---

Makefile
libr/util/Makefile
libr/util/sdb.mk
shlr/Makefile
shlr/sdb/Makefile
shlr/sdb/config.mk
shlr/sdb/src/Makefile
shlr/sdb/src/cdb.c
shlr/sdb/src/disk.c
shlr/sdb/src/ls.c
shlr/sdb/src/sdbht.c
shlr/sdb/src/util.c
sys/sdk.sh

sdb_version.h is removed in make clean step which happens when runnig those two targets in parallel.
**Test plan**
make -j
none

Fix race condition and remove unnecessary SDB build targets ##build

---

sys/create_r2.bat
sys/create_r2.sh

Commit fb1190d248 adds custom meson install scripts which do not inherit `DESTDIR`, preventing installation to a custom directory.
This pull request adds `DESTDIR` following the example at https://mesonbuild.com/Installing.html#custom-install-behavior to achieve expected behavior, which is particularly useful for packaging purposes.
**Test plan**
Specify a custom `DESTDIR` while installing. For example:
```
$ ./sys/meson.py --prefix="/usr"
$ DESTDIR="${pkgdir}" ninja -C build install
```
Note: I updated the Windows batch script as well, but do not have the capability to test it.

Add DESTDIR to sys/create_r2.sh

---

.github/workflows/pr.yaml
libr/util/pkcs7.c

This pr fixes the following (https://github.com/radareorg/radare2/runs/1002808994):
Also makes the GitHubCI run fuzz tests if the branch name contains "fuzz".
**Test plan**
All builds are green. All GitHubCI test builds run fuzz tests.
...

Fix MS-DOS fuzz tests

---

libr/core/cmd_debug.c
libr/debug/dsession.c
libr/include/r_debug.h
shlr/sdb/src/json/rangstr.h
test/db/archos/linux-x64/dbg_dts
test/unit/meson.build
test/unit/test_debug_session.c

* Add dtst and dtsf commands
* Change Rangstr to unsigned int to increase json length limit
Store `RDebugSession` in sdb and save it to disk in the following format:
```
maxcnum=<maxcnum>
reglist=<addr>,<addr>,...
registers={"<addr>": {"size":<size_t>, "a":[<RDebugChangeReg>]}, ...}
memorylist=<addr>,<addr>,...
memory={"<addr>": {"size":<size_t>, "a":[<RDebugChangeMem>]}, ...}
chkptlist=<cnum>,<cnum>,...
checkpoints={
"<cnum>": {
registers: {"<RRegisterType>": <RRegArena>, ...},
snaps: {"size":<size_t>, "a":[<RDebugSnap>]},
},
...
}
RDebugChangeReg JSON:
{"cnum":<int>, "data":<ut64>}
RDebugChangeMem JSON:
{"cnum":<int>, "data":<ut8>}
RRegArena JSON:
{"size":<int>, "bytes":"<base64>"}
RDebugSnap JSON:
{"name":<str>, …
```

Implement save and load functions for debug session ##debug

---

binr/r2r/load.c
test/db/cmd/types

Currently, tests missing both EXPECT and EXPECT_ERR (maybe via a missing EOF) are silently ignored. This pr makes r2r check whether a test has either EXPECT or EXPECT_ERR (or both) and aborts if not so.
Sample output using `r2r -i db/tools/r2`:
**Test plan**
Remove line 118 from
https://github.com/radareorg/radare2/blob/b67d1bf7c22be6e5e31a9fa37347bab10fe00f28/test/db/tools/r2#L111-L122
and run `r2r -i db/tools/r2`. Output should be like the above.
...

r2r: Check whether test has EXPECT or EXPECT_ERR

---

libr/core/canal.c
test/db/cmd/cmd_af

If the function name is less than 4 chars, this will strdup out of bounds. `asm.flags.real` is only for changing the display of things, not how analysis names things, so I think this can be removed completely. Moreover, it is almost always directly overwritten later in `set_fcn_name_from_flag()`.
**Test plan**
Run `r2 -Qc "f a; af" -` with valgrind or asan. The added test triggers the bug too but doesn't crash directly for me because it's just a read in "usually" valid memory. The tests purpose is primarily to ensure this change doesn't alter the functionality.

Fix oob read in getFunctionName()

---

libr/anal/dwarf_process.c

fixes crashes on gcc 4.9.4 and ld 2.35 with score7 target "aaa"
...
**Test plan**
...
...

Don't try to parse the function if null ##dwarf

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h

I did not like the `r_sign_find_closest_fcn` function accepting a signature name instead of a signature item. Changing it to accept a signature item allows for `cmd_zign.c:bestmatch_fcn` to add/remove signature types from the item according to user preference.  I wanted to fix this early before someone else uses the interface.
Also, the first commit ads a NULL pointer de-reference guard to `r_sign_fcn_bytes`. See #17528. I don't know that this really fixes the issue. If `RAnalFunction->bbs` can be empty, then the `r_return_if_fail` should probably not be used.
I felt like it was a minor thing to include this one line guard. I made the commits separate so you can squash or not. I can close this and submit separate PRs if you …

Refactor zbr to honor vars ##signatures

---

libr/bin/bin.c
libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc
libr/include/r_bin.h
test/db/cmd/cmd_i

Before MIPS32/64, a number of versions of the MIPS architecture were written down.
I added the  function that the iA command can output target ISA
I want to pass the ISA information to the gnu disassembler, do you have any suggestions?
...
**Test plan**
...
...

Improve iA command for MIPS ##bin

---

libr/core/cmd.c
test/db/tools/r2

When executing a command like:
```
> ?e `!!r2 -h~Usage?`
```
One of the `!` was ignored, leading to the execution of different commands (`!r2 -h`was executed instead of `!!r2 -h`).
**Test plan**
The test should pass for both newshell and old.
Closes https://github.com/radareorg/radare2/issues/17494

Fix #17494 - Pass the whole input string to r_core_cmd_str_pipe ##newshell

---

libr/util/sys.c
libr/util/thread.c
libr/util/time.c

A continuation of #17468. Continuing to bringing radare2 to the older platforms - older GCC and Glibc.
Old version of Glibc don't have support for `cpu_set_t` types and `CPU_SET` macro. Moreover, the type of `usleep()` is different - it returns void in older versions.
**Test plan**
It should fix some build errors on Debian Potato: https://github.com/XVilka/debian-oldies/tree/master/potato
See more errors at: https://github.com/XVilka/debian-oldies/runs/1040090876?check_suite_focus=true

Fixes for <=glibc-2.2 versions

---

libr/reg/reg.c

This pr fixes the following asan test and others like it (https://travis-ci.com/github/radareorg/radare2/jobs/378789409#L2801):
by not treating empty reg names differently from other invalid reg names.
**Test plan**
All asan tests that are XX only because of the above assertion are fixed. All non-asan builds are green.
...

r_reg_get_name_idx: Don't treat empty reg name differently from other invalid reg names

---

libr/anal/fcn.c

This pr fixes the following asan test (https://travis-ci.com/github/radareorg/radare2/jobs/378852160#L12178):
It appears `r_anal_op()` can set `asm.bits` and if this is fully processed, `anal->reg` gets a new register profile and pointers obtained through the old register profile, such as:
https://github.com/radareorg/radare2/blob/0b671bc3578cc52211ff340c6e69fd8b44ef3266/libr/anal/fcn.c#L500-L502 and
https://github.com/radareorg/radare2/blob/0b671bc3578cc52211ff340c6e69fd8b44ef3266/libr/anal/fcn.c#L504-L505 can dangle.
**Test plan**
The asan test above is fixed. All non-asan builds are green.
...

fcn_recurse: Fix dangling pointers if r_anal_op's setting of asm.bits is fully processed

---

libr/core/cconfig.c
libr/core/linux_heap_glibc.c
libr/include/r_heap_glibc.h
test/db/archos/linux-x64/dbg_dmht

In glibc 2.32 malloc introduces a new security safeguards to single-linked lists: chunk alignment enforcement and pointer mangling. This is a diff between malloc from glibc 2.31 and glibc 2.32:
```diff
> /* Safe-Linking:
>    Use randomness from ASLR (mmap_base) to protect single-linked lists
>    of Fast-Bins and TCache.  That is, mask the "next" pointers of the
>    lists' chunks, and also perform allocation alignment checks on them.
>    This mechanism reduces the risk of pointer hijacking, as was done with
>    Safe-Unlinking in the double-linked lists of Small-Bins.
>    It assumes a minimum page size of 4096 bytes (12 bits).  Systems with
>    larger pages provide less entropy, although the pointer mangling
>    still works.  */
> #define PROTECT_PTR(pos, …
```

Add commands to parse mangling pointers glibc heap

---

libr/anal/dwarf_process.c
test/unit/test_dwarf_integration.c

```
./libr/anal/dwarf_process.c:54:8: warning: passing argument 1 of 'free' discards 'const' qualifier from pointer target type [-Wdiscarded-qualifiers]
free (var->name);
../test/unit/test_dwarf_integration.c:42:8: warning: unused variable 'object_name' [-Wunused-variable]
char *object_name = "_cairo_status";
```

Fix compilation warnings ##dwarf

---

.github/workflows/ci.yml

Something does not work well with static (it hasn't at least from the
moment build-static started running full tests). To avoid all kind of
brokeness all around, let's switch back to no-tests. We will enable them
together with the proper fixes for the static build.

Do not run tests for build-static ##build

---

test/unit/test_idstorage.c

Fixes the following warning (https://travis-ci.com/github/radareorg/radare2/jobs/379559222#L2138):
**Test plan**
All non-asan builds are green.
...

Fix test_idstorage mu_assert warnings

---

libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_ptrace.h

A continuation of #17540. Continuing to bringing radare2 to the older platforms - older GCC and Glibc.
Old version of Glibc doesn't export `PTRACE_GETEVENTMSG' [ptrace() API](https://www.man7.org/linux/man-pages/man2/ptrace.2.html) types but the Linux kernel >= 2.5.46 provides it. There is no reliable and portable way to check the kernel version during the compilation, thus it's defined for sufficiently old glibc unconditionally.
**Test plan**
It should fix some build errors on Debian Etch: https://github.com/XVilka/debian-oldies/tree/master/etch

Fixes for old glibc (Debian Etch)

---

libr/util/sys.c

Fixes r_sys_pid_to_path for Haiku using proper team_id/pid_t ##util

---

libr/anal/class.c
libr/core/cmd_anal.c

I was going through my notes of details, TODOs etc. and I added help string to print help to a new `acg` command with `ac?`, I've also noticed that since we are adding RTTI inheritance info with `aaa` or `avrr` if you do it multiple times, the same base will be added twice, so you might end up with:
```
[0x00001120]> acl
Bat: Bird, Mammal, Bird, Mammal
Bird
Cat: Mammal, Mammal
Dog: Cat, Cat
Kappa: Cat, Cat
Mammal
```
So I've added a check that confirms the base doesn't already exists for a class before adding it

Don't add already existing parent class ##anal

---

libr/core/cconfig.c
libr/core/cmd_zign.c
test/db/cmd/cmd_zignature

Book update [pending here](https://github.com/radareorg/radare2book/pull/271/commits)
Small change to finally make use of the score threshold variable in zb commands. Setting `e zign.bestthresh = 0.5` will limit requires results to have a similarity score above `0.5`.  Setting a good threshold value should increase the speed of the algorithm by reducing the number of times the Levenshtein Distance is executed.
I am not a big fan of `bestthresh`, so if you have a better name I am happy to change it.  
**Test plan**
Tests were submitted to take care of common edge cases. The bulk of this feature was previously implemented, I just added the variable.
...

Add zb score threshold variable ##signatures

---

libr/anal/p/anal_xtensa.c
test/db/esil/xtensa_32

ESIL, xtensa
```
e asm.arch=xtensa
e asm.bits=32
e asm.emu=1
```
Input code:
`0x00000000      4ce8           movi.n a8, 78`
`0x00000000      4ce8           movi.n a8, 78               ; a8=0x4e`
`0x00000000      4ce8           movi.n a8, 78               ; a8=0xffffffffffffffce`
According to the [xtensa Instructions manual](https://0x04.net/~mwk/doc/xtensa.pdf )(page 422, movi.n) immediate argument's sign should be extracted as logical AND on bits 6 and 5 not only bit 6
...
**Test plan**
Corresponding test created for signed and unsigned values
...
...

Fix ESIL movi.n immediate value parsing ##emu

---

libr/asm/p/asm_x86_nz.c

```
$ rasm2 -f fail.asm
Expected register number 'art'
e800000000c3
$ cat fail.asm
call start
start:
ret
```
**Test plan**
Not sure if we really need a test for this, i have improved the checks for registers names, this reduces the possibility to try to encode this call as a `call reg`
Reported by skuater in chat

Fix 'call start' register confusion warning ##asm

---

libr/util/file.c
test/unit/test_util.c

Do not return a buffer when slurping a empty file

---

libr/core/core.c
libr/socket/socket_http_server.c

I fixed the 2 last critic error discover by lgtm.
1. Is a false positif, cmd is type ut8 and can't overflow because the standart defined his value between 0 and 255. But i add a condition to prevent regression.
2. Add a threshold of 5000 -> https://en.wikipedia.org/wiki/Maximum_transmission_unit
**Test plan**
Run the test suite
work on https://github.com/radareorg/radare2/issues/16493

Fix 2 last critic error lgtm

---

libr/core/canal.c

This pr fixes the following (https://travis-ci.com/github/radareorg/radare2/jobs/380644746#L3173):
**Test plan**
The asan test above is fixed. All non-asan builds are green.
...

Fix 'anal && op && len > 0' assertion in asan build

---

binr/r2r/load.c
binr/r2r/r2r.c
binr/r2r/r2r.h
binr/r2r/run.c
test/README.md
test/db/formats/pe/65535sects

Right now the timeout was a global defined in Config. This PR adds support for per-test timeout, in case some tests are expected to take a bit more time.
**Test plan**
`db/formats/pe/65535sects` should pass in ASAN build in travis.

Add support for TIMEOUT key for cmd tests ##r2r

---

libr/socket/run.c
libr/util/sys.c

ASLR on NetBSD is also settable via sysctl call.

Implements r_sys_aslr for NetBSD ##port

---

libr/bin/pdb/pdb.c
libr/util/list.c

Make sure streams are in their proper index for `r_list_get_n` by appending a NULL item when necessary
**Test plan**
Tests pass
Closes #17590

Fix #17590 - Fix invalid deref in print_types_format

---

libr/bin/p/bin_xtr_fatmach0.c

Now r_list_append accepts null data because of 080bf49

Fix null deref in fuzzed xtr after 080bf49

---

libr/core/cconfig.c

Offset signatures match when a functions address matches the signatures address. Most use cases of signatures would suffer from false positives because of this signature type. This PR sets the `zign.offset` var to `false` by default. This will prevent the offset matching only, all other uses of the offset signature will be unaffected. In the special circumstances where offset matching is desired the command `e zign.offset = true` will re-enable the signature type.
**Test plan**
...
...

Disable offset zig by default ##signatures

---

libr/include/r_socket.h
libr/main/radare2.c
libr/socket/run.c

Escape the environment variable values with `'` in the startup rarun profile to prevent misinterpreting special characters as rarun prefixes.
For example, an env var with special characters like `DISPLAY=:0` should not be parsed as a hexpair string by `run.c:getstr`
**Test plan**
...

Escape environment vars in the default rarun profile

---

libr/core/cconfig.c

For bigger stack usage. ESIL command translated from P-codes can use 40~60 elements on stack.

Extend ESIL VM's stack size from 32 to 256.

---

libr/anal/esil.c
test/db/esil/esil

“~” means extends **n** bit value to 64-bit value
A bug occurs when the number of digits to be expanded is greater than **n**
For example, I execute the  "ae 32,0xffffffffffffff12,~"
output:
```
0xfffffffeffffff12
```
should be:
```
0xffffffffffffff12
```
**Test-plan**
...
...

Fix ESIL sign extension operator bug ##anal

---

libr/include/r_socket.h

Fix clang-cl build error
https://ci.appveyor.com/project/radareorg/radare2/branch/master/job/880yhff4r6ix9ap6
```
../libr/socket/run.c(1232,13): error: conflicting types for 'r_run_get_environ_profile'
R_API char *r_run_get_environ_profile(char **env) {
^
..\libr\include\r_socket.h(259,13): note: previous declaration is here
R_API char *r_run_get_environ_profile(char **environ);
^
4 warnings and 1 error generated.
```

Fix clang-cl build error

---

libr/bin/bobj.c
libr/bin/p/bin_bflt.c
libr/bin/p/bin_elf.inc
libr/core/core.c
libr/core/disasm.c
libr/include/r_bin.h
test/db/cmd/cmd_pd
test/db/formats/coff
test/db/formats/elf/reloc

See issue, it's well described.
**Test plan**
See https://github.com/radareorg/radare2-testbins/pull/49.
Closes #17583

Fix ELF R_X86_64_PLT32 relocation entries patching ##bin

---

.github/upload.sh
.github/workflows/continuous.yml
.travis.yml

Avoid polluting the Releases page with a lot of "continuous build"
releases, which also break the "Latest release" shown by API/UI. This
job will upload as artifacts the .deb packages created on each
commit and create a pre-release "Continuous build" instead of an actual one.
Closes #17598

Create new GitHub workflow for continuous build ##build

---

libr/anal/sign.c
libr/include/r_sign.h

The `r_sign_item_dup` appears to only be used in one place. This is to set up a list of `RSignItems` for `r_search`. The items don't need to be duplicated if they are never free'd. This should result in a performance boost. 
The `r_sign_item_dup` function also has a bug where it does not properly duplicate the `items` signature. So by refactoring this function out, the `searchHitCB` should now get the necessary information to apply the type information to a function.
**Test plan**
See the command executed in #17607 PR.
...

Remove r_sign_item_dup ##signatures

---

libr/core/cmd_help.c
test/db/esil/x86_32

needed because:
* theres no way to strcmp in r2
* x86.as tests are x86-specific
other solutions for the 2nd problem are:
- add ARCHONLY= in r2r
- do some r2 scripting magic
- make arch-specific tests in a separate directory
- install x86 toolchain on non-x86 testsuite platforms
- fallback to x86.nz inside the plugin
but also bear in mind that there are more failing x86.as tests that must be addressed, this PR is only fixing one
```
$ git grep x86.as test
test/db/esil/x86_32:e asm.assembler=x86.as
test/db/esil/x86_32:e asm.assembler=x86.as
test/db/tools/rasm2:CMDS=!rasm2 -s att -a x86.as -b 64 "test %rbx, %rax" 
test/db/tools/rasm2:CMDS=!rasm2 -s intel -a x86.as -b 64 "test rax, rbx" 
test/db/tools/rasm2:CMDS=!rasm2 -s att …
```

Implement ?== operator to compare strings ##shell

---

libr/core/cmd_cmp.c

In the internal help of `c?`, there's a blank line between the help of `cX` and `cd`, which I believe is unnecessary.
```
| cx [hexpair]             Compare hexpair string (use '.' as nibble wildcard)
| cx* [hexpair]            Compare hexpair string (output r2 commands)
| cX [addr]                Like 'cc' but using hexdiff output
| cd [dir]                 chdir
```
I've removed that blank space in this Pull Request.
**Test plan**
None

Remove an unnecessary blank space in `c?` ##cons

---

meson.build
meson_options.txt

Found myself needing this to speed up CI builds in a [project](https://github.com/frida/cryptoshark) that consumes r2's libraries.

Add Meson option to specify whether CLI tools should be built

---

libr/anal/fcn.c

Filling this template is moisten.
`buf` has size `bb->size` so `buf + off` has size `bb->size - off`.
**Test plan**
Run with asan:
`r2 -Aq test/bins/fuzzed/9255cead7e2cb22611359fec200090da`
The error can be seen here: https://github.com/radareorg/radare2/runs/1101358657

Fix heap oob read in bbget()

---

libr/bin/bin.c

`iAj` currently works by constructing a JSON string and printing it. Here, I've reimplemented it using the PJ API. 
**Test plan**
Currently, `iAj` on one of the test binary prints:
`{"bins":[{"arch":"x86","bits":32,"offset":0,"size":5240,"machine":"Intel 80386"}]}`
Using this, `iAj` would print:
`{"bins":[{"arch":"x86","bits":32,"offset":0,"size":5240,"machine":"Intel 80386"}]}`
None

Use PJ in `iAj` ##json

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach064_is_kernelcache.c
libr/bin/format/mach0/mach0_defines.h
libr/bin/format/mach0/mach0_specs.h
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_xnu_kernelcache.c
test/db/cmd/cmd_tc

This change adds early support for "modern" i/macOS, in particular:
- add support for macOS arm64 xnu kernel caches, the ones with the `MH_FILESET` format; this also adds preliminary support for parsing chained fixups, used in arm64e mach-O binaries
- add support for iOS 14.x dyld shared caches, with support for multiple rebase info and extra RW mappings
- add support for recent changes to Objective-C, in particular the "small" method lists, in which pointers to method's name, implementation and types are expressed as 32-bit relative offsets instead of absolute 64-bit pointers
I decided to do all the changes in a single PR because they're all inter-dependent.

Early support modern i/macOS ##bin

---

libr/bin/mangling/microsoft_demangle.c
test/db/formats/mangling/mangling

* Also fix not adding the template name as an abbreviation
* Add test
**Test plan**
Tests pass

Fix MSVC template demangling with ref to mangled symbol

---

libr/core/cmd_zign.c

This refactors out multiple bugs in the matching of signatures. When a signature is matched, either `fcnMatchCB` or `searchHitCB` is called. This previous lead to `addFlag` where there were a few bugs. These bugs prevented the function from being renamed, having types applied and resulted in some leaks.
There is still a bug where types are not applied because the `RSignItem` passed to `searchHitCB` does not have a `types` member. This is due to a bug in `r_sign_item_dup` and is addressed in #17608.
**Test plan**
```
$ r2 static 
-- Did you know that radare2 can decompile to assembly?
[0x00401c60]> s 0x0041dec0
[0x0041dec0]> af
[0x0041dec0]> afs
void fcn.0041dec0 (int64_t arg1);
[0x0041dec0]> zo ./out.sdb 
[0x0041dec0]> z* …
```

Fix multiple bugs in matching ##signatures

---

libr/anal/esil.c
libr/core/cmd_anal.c
test/db/anal/arm
test/db/anal/arm64
test/db/anal/tms320.c64x_32
test/db/anal/x86_16
test/db/anal/x86_32
test/db/anal/x86_64
test/db/cmd/cmd_ao
test/db/esil/x86_64

cc @sanguinawer 
Right now we get execution cost information statically. this patch adds support for computing the cost of executing the esil expression. this way we can properly cmopute the costs for `rep` instructions and other tricky instructions
**Test plan**
Needed to fix a bug in r2wars

Show ESIL execution cost information in `ao` and `aoj` ##anal

---

libr/anal/d/types-darwin.sdb.txt
libr/anal/type.c
libr/core/cmd_type.c
test/db/cmd/cmd_pd2
test/db/cmd/cmd_tc
test/db/cmd/cmd_to
test/db/cmd/types
test/unit/meson.build
test/unit/test_anal_types.c
test/unit/test_dwarf_integration.c
test/unit/test_pdb.c
test/unit/test_sdb.h

Filling this template is fun.
see commit titles
**Test plan**
run the tests

Add API for getting Atomic and Typedef Types and remove broken !size

---

codecov.yml

Ignore failures in coverage for PRs.
Also, only test "project" coverage on master or release branches.
**Test plan**
Check the coverage stats on this PR, it should pass (even though it may or may not have bad coverage).

codecov: Add yaml config for ignoring failures in coverage for PRs

---

.github/workflows/ci.yml
libr/core/cmd_anal.c

Previously coverage was measured on meson-gcc-tests which isn't run on pull requests. meson-gcc-newshell-tests should do more or less the same code except part of command parsing code.
**Test plan**
Wait for pull request tests to finish. Make sure test coverage for whole project not the diff is ~40% same as when master is being tested.

Move coverage testing to  meson-gcc-newshell-tests

---

codecov.yml

I don't think we want to see master red because we coverage is not good. It is definitely something we want to look at from time to time, but seeing master red just because of codecov does not seem right. Hopefully this will make it green.

Make codecov/project informational on master as well

---

.github/workflows/ci.yml

Fuzzing isn't done for pull requests. It causes difference in coverage report. As far as I am aware there is no easy way to disable data collection without recompiling r2 so instead upload collected data before fuzzing is executed. This PR should fix the 1-1.3% decrease currently reported for all pull requests.
**Test plan**
Result will only be seen once changes have been merged to master. 
CI for PR should at least confirm that syntax for CI configuration isn't completely broken.
...

Match PR coverage number with master.

---

libr/core/cmd_anal.c
test/db/cmd/dwarf

Use sdb_set instead of sdb_querys. sdb_querys takes a lot of time doing some json stuff, there is also risk of command injection.
This was discovered when profiling r2. After the changes time for doing aaa on Cutter debug executable is reduced from ~840s to 
125s.
Doing the changes also improved the argument analysis for two rust tests. I am guessing that this was due to function name getting interpreted as part of query.
**Test plan**
Covered by existing r2r testsuite. Having the 2 changed lines commented out or using wrong sdb command breaks ~ 20 tests.

Use sdb_set instead of sdb_querys.

---

libr/core/cmd.c

Issue #13969 suggests to implement `rj`for consistency and standardization.
**Test plan**
Currently, through this commit, I'm not sure that `rj` has been implemented perfectly, as on a test binary, it there's a difference in the outputs, as shown:
```
[0x08048360]> r
7580
[0x08048360]> rj
7.4K
```
Any other high level or specific guidance is hereby requested and appreciated.
As discussed in #13969

Implement `rj` ##json

---

libr/anal/function.c

`RAnalFunction.imports` wasn't freed when deleting the function.
**Test plan**
I wanted to add a unit test here but there is no API at all for imports yet so it would have to hack the stuff into the struct manually into the test. Instead here is a test from r2db that shows the leak with asan/valgrind: https://github.com/thestr4ng3r/r2db/blob/master/test/unit/test_anal.c#L305

Fix RAnalFunction leaking imports

---

libr/core/cbin.c
libr/core/disasm.c
libr/fs/p/fs_io.c
libr/fs/p/fs_r2.c
libr/include/r_util/r_str.h
libr/util/str.c

Store read files with line information in in a dictionary. Simplifies the logic within `bin_dwarf` and prevents memory leak. This also reduces execution time by not having to process the same file multiple times. Previous version only stored last 1-2 files. 
As usual there is room for further optimizations but it isn't the worst part anymore. There is little value for doing it right now before improve other parts first.
When testing on Cutter debug executable
* prevent 6.7 GB memory leak
* reduce peak memory usage from 6.7GB to 1.9GB
* reduce execution time 49s -> 20s
**Test plan**
* comparisons performed by running `r2 -ci -qq executable`
Wait for coverage report to check if modifed code is executed during tests, based on …

Fix leak in dwarf processing.

---

meson.build
shlr/sdb/src/main.c
shlr/sdb/src/query.c
shlr/sdb/src/sdb.1

Filling this template is filling this template.
Build on Pinebook Pro (`time ninja`):
Before:
```
real    4m8.053s
user    20m34.937s
sys     2m58.248s
```
After:
```
real    3m9.292s
user    15m23.409s
sys     2m21.460s
```
linux-meson-gcc-build:
Before: 2m 38s
After: 2m 6s
**Test plan**
Build r2 with meson.

Use sdb == for generating dbs in meson

---

libr/core/cconfig.c

When using -a r2ghidra the -b wil lbe always ignored and every call lto `e asm.bits=..` too. This patch fixes the probblem.
**Test plan**
It depends on an asm/anal plugin with .bits=0
...

Allow to set asm.bits when using the r2ghidra asm/anal plugins ##disasm

---

libr/core/cmd.c
test/db/cmd/cmd_r
test/db/json/json4

This PR fixes [an issue](https://github.com/radareorg/radare2/pull/17443#issuecomment-695193995)(also explained below) with `rj` and add tests for it.
**Test plan**
`rj` also printed `r_io_resize: cannot resize`, along with the required output.
```
[0x08048320]> rj
r_io_resize: cannot resize
{"size":5240}
```
Which stopped, when I replaced the break statement in the case that prints `rj` with, a return statement, just like the other cases in the same switch statement.
I'm not sure whether this is the right way to fix this, which is why I'm putting this on draft.
Other than that, I've added the tests for `rj`.
```
$ r2r -i db/cmd/cmd_r
Running from /home/cjunior/Downloads/programs/radare2/test
Loaded 3 tests.
Skipping json …
```

Fix `rj` and add tests ##json

---

libr/include/r_core.h

Fixes the following [compilation error](https://github.com/XVilka/debian-oldies/runs/1145536590?check_suite_focus=true#step:3:18485) on Debian Wheezy, Squeeze, Etch:
```
gcc -c  -MD   -fPIC -g -Wall -D__UNIX__=1 -DR2_PLUGIN_INCORE -I/radare2-master/libr/..//shlr -I/radare2-master/libr/../shlr/sdb/src -I/radare2-master/libr/../shlr/zip/include -I/radare2-master/libr -I/radare2-master/libr/include -I/radare2-master/libr/../shlr/sdb/src -fvisibility=hidden -I../../shlr/sdb/src/ -DHAVE_FORK=1 -DUSE_R2=1 -I../../shlr -o log.o log.c
In file included from log.c:6:
/radare2-master/libr/include/r_core.h:346: error: redefinition of typedef 'RCore'
/radare2-master/libr/include/r_cmd.h:12: note: previous declaration of 'RCore' was here …
```

Fix forward declaration of RCore

---

libr/main/rasm2.c
test/db/tools/rasm2

Fix rasm2 -L bits field for 4 and 0-bit plugins ##asm

---

libr/anal/var.c
libr/core/anal_tp.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_core.h

See title, having them in sdb would make the constraints leak beyond the lifetime of vars/functions and harder to use.
**Test plan**
There is a test in `test/db/cmd/types` that covers this code quite well: https://github.com/radareorg/radare2/blob/1c485e8bfc94e052ac3976dcc3251a5e76650532/test/db/cmd/types#L1342-L1362.

Refactor Variable Constraints out of SDB ##anal

---

shlr/radare2-shell-parser/corpus/special_commands.txt
shlr/radare2-shell-parser/src/scanner.c

Commands like `-` or `\` were not working.
`-` is supposed to open the editor, `\` is for rap commands.
**Test plan**
Try `-` with `e cfg.newshell=true`, it should open your editor and execute whatever you put there

Add support for additional cmd_identifiers ##newshell

---

libr/anal/p/anal_x86_cs.c
test/db/cmd/cmd_print

This pr fixes the following (https://github.com/radareorg/radare2/runs/1128444655#step:15:67):
**Test plan**
The error above should not appear in the asan fuzz test output. All other builds are green.
...

x86 cmp/sub: Properly generate esil for bitsize of 64 ##anal

---

libr/anal/dwarf_process.c
libr/bin/dwarf.c
libr/bin/format/mach0/mach0.c
libr/bin/p/bin_dex.c
libr/include/r_util/r_uleb128.h
libr/util/uleb128.c
test/db/formats/mach0/leb128
test/unit/test_uleb128.c

I removed the duplicate implementations of read_{u,s}leb128 in mach0.c and wrote wrappers to use the implementations from RUtil. I also removed ulebr structure as I found it useless.
**Test plan**
...
Closes #17353

Fix #17353 - Remove duplicated implementation of uleb128 in mach0 ##bin

---

libr/anal/anal.c
libr/core/anal_tp.c
libr/core/cmd_anal.c
libr/core/core.c
libr/include/r_anal.h
test/db/cmd/cmd_k
test/db/cmd/types

**DO NOT SQUASH!!!!!!!!!!!!!!!!!!!!!!!!!!!!**
Filling this template is power, France is bacon.
I'll go through the previously remaining uses of `sdb_fcns` and how they have been killed.
... were saved in this sdb until #16547 which was merged months ago. Apparently the only remaining use of vars there was the `exists_var` callback for RPrint, which I rewrote for the correct variable storage.
`axt` queried accesses to variables from `sdb_fmt`, but there was no place that actually wrote these accesses there so it was basically a nop. The correct way to query accesses to vars is by using `afv=`.
This one is a bit more complicated. This is roughly how the relevant type matching part worked before:
```
foreach f in all functions {
foreach call to callee …
```

Kill RAnal.sdb_fcns

---

libr/anal/pin.c

This pr fixes possible use of a dangling pointer in r_anal_pin, when calling r_anal_pin_fini() followed by r_anal_pin_init(), due to sdb_free() being called twice.
**Test plan**
Probably fixes #17718.

Fix possible use of dangling pointer due to calling r_anal_pin_fini() followed by r_anal_pin_init()

---

libr/include/r_io.h
libr/io/p_cache.c

There is absolutely no reason why this should be an sdb when the key is ut64 and the value is a pointer.

Use Ht instead of SDB for pcache ##io

---

libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/include/r_parse.h
libr/parse/p/parse_arm_pseudo.c
libr/parse/p/parse_mips_pseudo.c
libr/parse/p/parse_wasm_pseudo.c
libr/parse/p/parse_x86_pseudo.c
libr/parse/parse.c
test/db/cmd/cmd_pd
test/db/formats/elf/mips

On #17455, it was suggested to rename `asm.var.sub` to `asm.sub.var` for better organization. That is what this PR is hoping to achieve.
Mainly, to do this, I have renamed three things : 
* `r_parse_varsub` to `r_parse_subvar`
*  the bool `asm_varsub` to `asm_subvar`
* the bool `varsub` to `subvar`
**Test plan**
I renamed the tests and tried running it. Files including this particular command were in `cmd/cmd_pd` and `/formats/elf/mips`,which seemed to be doing fine:
```
$ r2r -i test/db/cmd/cmd_pd
Running from /home/cjunior/Downloads/programs/radare2/test
Loaded 117 tests.
[117/117]                 117 OK         0 BR        0 XX        0 FX
Finished in 2 seconds.
```
```
$ …
```

Rename `asm.var.sub` to `asm.sub.var` ##cons

---

libr/bin/format/mach0/mach0.c

#17489 introduced a string format security build warning, by calling `eprintf()` with the reuslt of `r_str_newf()`, `error`. This PR is fixing this warning by calling `eprintf()` with `error` as an argument to `"%s"`, a format string, [as suggested](https://fedoraproject.org/wiki/Format-Security-FAQ#How_do_I_fix_these_errors.3F).
**Test plan**
None
Closes #17730

Fix format-security build warning ##bin (#17730)

---

libr/core/cmd.c
libr/core/cmd_api.c
libr/core/cmd_helps.c
libr/core/cmd_helps.h
libr/core/cmd_write.c
libr/include/r_cmd.h
test/unit/test_cmd.c

Some background:
when you do `a` as a command can mean 2 things: 1) `alias for aai - analysis information` 2) the group which includes all analysis information. In the help, you see them in 2 places: when you do `?` you will see `| a[?]                    analysis commands`, when you do `a?`, you will see `Usage: a     analysis commands` and then one line below `| a                  alias for aai - analysis information`.
As you can see, the same string can reference two different "concepts" in the help. Before this PR, we had merged the help strings in one single structure, however most of the other commands did not use those additional fields (group_summary, group_args_str) and they required special handling in the cmd_api …

Split GROUP RCmdDesc and regular ones ##newshell

---

libr/core/cmd.c
libr/util/str.c
test/db/cmd/cmd_pd
test/db/cmd/feat_quote
test/db/cmd/regexp

When a user wraps an argument, it means like in SH that he wants the
command to consider the argument as one single arg, even if composed by
multiple words. The same applies for r2newshell. So far we did not
unwrap quoted strings to maintain compatibility with old shell, but
doing this unwrapping is one of the nice feature of newshell.
When using old shell,
```
w Hello   World
```
would write to file the string 
```
Hello   World
```
because it simply takes as argument whatever is found after `w `. However, with `cfg.newshell=true`, arguments are parsed and split by the parser itself, which is not aware of how each command handlers wants to parse its arguments. To be generic, it splits arguments by space, but if a user …

Unwrap quoted strings when passing args to newer handlers ##newshell

---

libr/debug/p/debug_native.c

As described in #17500, an error was printed after each step because `r_debug_native_wait` failed due to an incorrect handling of `r_debug_handle_signals`'s return value.
I have also added a warning for platforms that don't support signal handling after stepping without causing a failure.
**Test plan**
Open a program in FreeBSD and step/continue.
closes #17500

Fix FreeBSD step error ##debug

---

libr/bin/mangling/microsoft_demangle.c
test/db/formats/mangling/mangling

* Fix back-reference to templated operator functions
* Fix back-reference to templated names
* Support demangling rvalue references
* Support demangling 'std::nullptr_t' type
* Support demangling function types inside templates
* Support demangling array types inside templates
* Support demangling empty templates
* Support demangling compiler generated statics
* Support demangling thunk functions
**Test plan**
Tests pass

Fixes for MSVC name demangling

---

libr/debug/p/debug_native.c
libr/debug/p/native/bsd/bsd_debug.c
libr/debug/p/native/bsd/bsd_debug.h

`dp` failed with permission denied on FreeBSD, didn't display the process' children and running `dp [pid]` didn't work.
**Test plan**
In *BSD without root:
* Run `dp` and see that the process and it's children are displayed
* Run `dp 0` and see that all processes shown in `ps` are printed(without threads)
* Run `dp [other pid]` and see that the process and it's children are displayed

Fix dp command in BSD systems ##debug

---

libr/syscall/example.syscall-file

There is an example file named `example.syscall-file` inside `libr/syscall` which houses an outdated example which is not needed. This PR removes that file.
This was mentioned twice in [#140](https://github.com/radareorg/radare2book/issues/140#issuecomment-703081995) of the radare2book.
**Test plan**
None.
As discussed in [#140](https://github.com/radareorg/radare2book/issues/140)

Remove example.syscall-file ##build

---

libr/core/cmd_print.c
test/db/json/json4

The pxd[1,2,4,8] commands had no equivalent JSON version. I've added that behavior and modeled it after pxh/pxw/pxq.
**Test plan**
The output of pxdj/pxd1j/pxd2j/pxd4j/pxd8j should contain the same numbers as pxd/pxd1/pxd2/pxd4/pxd8.

Add JSON variants of pxd[1,2,4,8] commands ##print

---

libr/core/core.c

r2 -
ls /<tab> # and nothing happens
**Test plan**
we cant test interactive autocompletion
nope. but it was anoying

Autocomplete 'ls' with TAB as its done for cd, rm, .. ##shell

---

libr/core/cconfig.c
libr/core/cmd_log.c
test/db/cmd/cmd_list

For issue #17708 it is required to implement `e asm.parser=?` which should print all the parsers loaded currently. I've added code to update `node->options` list to have all the plugins listed.
Similarly `e asm.bits=?` is implemented by getting the value of `core->rasm->cur->bits` and populating all the `node->options` list to have all the available configurations.
Also the `Lp` command has been added to print all the parsers which will just call the `e asm.parser=?` command similar to implementation of `La`
Tab completion works for those fields now.
**Test plan**
Test case for `Lp` has been added to list the plugins (current output from my local terminal). I've tested locally for the changes made and autocomplete along …

Add support for listing parsers, bits and add Lp command

---

libr/core/cmd_help.c

I've noticed that for `?i` all variations except the path one have a help string, so I added one for `?ip`.
**Test plan**
`???` and look for `?ip`.

Add help string for path input prompt

---

libr/core/disasm.c
test/db/cmd/cmd_pd

There is no new allocation in r_parse_immtrim, so it is not required to
free the "previous" string.
r_parse_immtrim just moves bytes but it does not allocate a new string, so the free is wrong.
**Test plan**
Run `e asm.imm.trim=true; pd 10` and you will get a double free.

Do not free ds->opstr after r_parse_immtrim

---

libr/core/cmd.c

The help under `v?` currently doesn't look pretty as it's just `eprintinf`-ing it.
I've reimplemented it properly in this Pull Request, by using `r_core_cmd_help`.
**Test plan**
This is what the `v?`will output after this PR:
Also, to save the layout, the current help asks us to run `v.` but it's on `v=`, `r_save_panels_layout` is actually called and the layout is saved, as you can see [here](https://github.com/radareorg/radare2/blob/master/libr/core/cmd.c#L1917). 
Currently, I've added the help as `v=`, but I'd like a maintainer to review it.
None

Improve help under `v?` ##cons

---

.github/workflows/ci.yml
libr/anal/p/anal_x86_cs.c
libr/asm/p/asm_tms320.c

See https://github.com/radareorg/radare2/pull/17781#issuecomment-708124769 . I've seen this option in https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html .
**Test plan**
Everything should be green, capstone included.

Use -Wno-cpp to avoid errors on #warning

---

binr/r2pm/r2pm
man/r2pm.1

This change is needed for example for radare2-extras
to successfully install packages on a particular testing branch for CI.
Relates to https://github.com/radareorg/radare2-extras/pull/265 (please drop the WIP commit)

Add R2PM_GITSKIP env var to skip git checkout master && git pull  ##r2pm

---

libr/anal/rtti_msvc.c

**Test plan**
We don't have a CI building 32 bit bins, so tested manually
Fixes #17790

Fix #17790 - Fix crash when recovering MSVC RTTI on 32-bit host

---

libr/socket/r2pipe.c

Current the travis-ci reports
```
sh: 1: rodoro2: not found
return code 32512 for rodoro2 -q0 -
test_r2pipe OK
test_r2pipe_404 ERR
[XX] Fail at line 17: r2pipe can spawn
```
Using gdb on both ubuntu 20.04 amd64 and arm64(WSL), I noticed that when line 276 fails, on amd64 it jumps to line 281, but on arm64 it jumps to line 287. That's because `char` is treated as `unsigned char` on arm, making `ch == -1` false forever.
https://github.com/radareorg/radare2/blob/2ccd0c0cd21086d5aa7ed88939b5f5bf70b80184/libr/socket/r2pipe.c#L274-L287
**Test plan**
See travis-ci report whether test_r2pipe_404 succeeds. But it seems travis-ci isn't enabled here. Could you enable it manually?
...

Fix travis arm64 test_r2pipe_404

---

shlr/meson.build

Removes annoying warning:
```
cl : command line warning D9002: ignoring unknown option '-std=c99' [C:\projects\radare2\build\shlr\cafa177@@tree_sitter@sta.vcxproj]
```

Remove some of MSVC warnings

---

test/db/anal/arm

By default on arm64 this case fails because 0x00000000 is invalid.
```sh
rasm2 -a arm -b 64 -d 00000000
```
As the test is about arm, its success on x86 is by chance (0x0000 is valid in x86).
Moreover, since there's a separate file db/anal/arm64, why does db/anal/arm contain cases where `e asm.bits=64`? Should they be moved to db/anal/arm64?
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/403288481#L802 at least this case passed.
...

Fix travis db/anal/arm noreturn errno

---

libr/core/cmd_print.c
libr/core/core.c
libr/include/r_util/r_str.h
libr/util/print.c
libr/util/str.c
test/db/anal/x86_32
test/db/cmd/cmd_px
test/db/cmd/cmd_pxw

pxr is bind to asm.bits, theres no way to use a different word size until...NOW
also i fixed a boundary bug that was shown in one BROKEN test.
there are still more formats to be supported as output for pxr, but i think this wont come until i finish and get merged the table PR, so for me its fine to merge this as is
**Test plan**
i wrote tests
no issue listed

Fix bugs and improve pxr ##print

---

libr/bin/p/bin_xbe.c
test/db/formats/xbe

This PR is a fix to a bug I found on Cutter, where the list of symbols on an Xbox XBE file did not match what was expected.
I found the symbol name lookup was off-by-one. The issue was that the thunk indexes start from 1, not 0. Radare2 implements the name lookup using an array of strings without correcting this index.
I verified the expected symbol list on the test file `bins/xbe/default.xbe` using **XbeExplorer**: https://github.com/PatrickvL/Dxbx/releases
The symbol name uses a different convention, but `RtlSprintf` is the same import as `sprintf` (see https://github.com/PatrickvL/Dxbx/blob/7d86a82050be2a1b461fca0dc5e2fea952a88948/Source/Delphi/src/uKernelThunk.pas#L417)
**Test plan**
1. I modified `test/Makefile` to …

Fix xbe symbol name lookup

---

libr/util/sys.c

Same API and approach as FreeBSD.

Fixing r_sys_pid_to_path for DragonFlyBSD ##util

---

libr/core/disasm_stackptr.inc

disasm_stackptr.inc:124:29: warning: 'ostackptr' may be used uninitialized in this function [-Wmaybe-uninitialized]
...
**Test plan**
...
...

Fix uninitialized variable use in ostackptr

---

libr/core/cmd.c

cmd.c:1510:3: warning: 'cur_cmd' may be used uninitialized in this function [-Wmaybe-uninitialized]
...
**Test plan**
...
...

Fix UB crash in cmd_kuery

---

libr/debug/dreg.c

dreg.c:294:3: warning: 'pj' may be used uninitialized in this function [-Wmaybe-uninitialized]
...
**Test plan**
...
...

Fix uninitialized pj instance in dreg.c

---

libr/util/json_parser.c

json_parser.c: In function 'parse_value':
json_parser.c:240:9: warning: 'new_key' may be used uninitialized in this function [-Wmaybe-uninitialized]
p = parse_value (js, new_key, p);
^~~~~~~~~~~~~~~~~~~~~~~~~~~~
...
**Test plan**
...
...

Fix warning in the JSON parser

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h

This refactors r_sign function metrics matching. Now instead of a function to match each metric type, there is a single function. This allows RSignItems to created only once, instead of once per type. Additionally, a cache was added to some of the expensive function information. This results in a significant speed increase.
```
$ ./r2test.sh 
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
generated zignatures: 3182
[+] searching function metrics
hits: 15919
774.342817
15919
$ ./r2test.sh 
Warning: run r2 with -e io.cache=true to fix relocations in disassembly
generated zignatures: 3182 …
```

Refactor r_sign metrics match ##signatures

---

libr/core/rtr_http.c

```
In file included from rtr.c:234:0:
rtr_http.c: In function 'r_core_rtr_http_run.isra.1':
rtr_http.c:403:44: warning: 'path' may be used uninitialized in this function [-Wmaybe-uninitialized]
path = (*index == '/')? strdup (index): r_str_append (path, index);
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
...
**Test plan**
...
...

Fix uninitialized usage of a variable, fix crash in r_str_append

---

libr/anal/esil.c
test/db/esil/flag_tests

**Test plan**
We need OVF macros for signed/unsigned and zero division checks to cover all possible r2 fpu exceptions.
* i cant share the binary, but its easy to reproduce with this oneliner. But the signed instructions were not documented (ae??)
```
[0x00000000]> "ae -1,0x8000000000000000,~/"
zsh: floating point exception  r2 -
$
```

Fix unexpected FPU exception in ESIL emulation ##esil

---

libr/core/cmd.c
libr/core/cmd_search.c

- [Y] I've read the [guidelines for contributing](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md) to this repository
- [Y] I made sure to follow the project's [coding style](https://github.com/radareorg/radare2/blob/master/DEVELOPERS.md#code-style)
- [N] I've added tests that prove my fix is effective or that my feature works (if possible)
- [Y] I've updated the documentation and the [radare2 book](https://github.com/radareorg/radare2book) with the relevant information (if needed)
extend the help info of '/' and '*' command.
**Test**
Fuzz Timeout 
```
r2r -LF bins/fuzzed @fuzz
Running from /home/runner/work/radare2/radare2/test
Category: fuzz
Loaded 505 tests.
[XX] TIMEOUT …
```

extend usage info about '/*' and '*/'

---

libr/core/core.c

- just type 'e '
- press `<tab>`
- nothing happens.
...
**Test plan**
...
...

Autocomplete `e <tab>` does not work

---

libr/bin/format/coff/coff.c
libr/bin/format/coff/coff.h
libr/bin/format/coff/coff_specs.h
libr/bin/p/bin_coff.c
test/db/formats/coff

Dummy loader for COFF objects was added to avoid issues with alignment in ARM binaries.
Related issue: #7310.
Simple example: `pdf` output of function `buffer_putflush()` https://github.com/radareorg/sdb/blob/master/src/buffer.c#L53-L58  
```asm
[0x000000d0]> pdf @ sym.buffer_putflush
/ 68: sym.buffer_putflush ();
|           ; var int16_t var_0h @ sp+0x0
|           ; var int16_t var_4h @ sp+0x4
|           ; var int16_t var_8h @ sp+0x8
|           ; var int16_t var_18h @ sp+0x18
|           ; var int16_t var_1ch @ sp+0x1c
|           ; var int16_t var_20h @ sp+0x20
|           0x00000218      0fb4           push {r0, r1, r2, r3}
|           0x0000021a      2de90048       push.w {fp, lr}
|           0x0000021e      eb46 …
```

COFF: add ARMNT and ARM64 support ##bin

---

libr/bin/dwarf.c

```
$ gcc -c -MD -fno-common   -fPIC -g -Wall -D__UNIX__=1 -DR2_PLUGIN_INCORE -Iformat -Imangling -I/Users/liumeo/github/radare2/libr/../shlr/zip/include -I../format/pyc/ -I/Users/liumeo/github/radare2/libr/..//shlr/yxml/ -I/Users/liumeo/github/radare2/libr -I/Users/liumeo/github/radare2/libr/include -I/Users/liumeo/github/radare2/libr/../shlr/sdb/src -fvisibility=hidden -o dwarf.o dwarf.c
dwarf.c:107:28: warning: initializer overrides prior initialization of this
subobject [-Winitializer-overrides]
[DW_TAG_template_alias] = "DW_TAG_template_alias",
^~~~~~~~~~~~~~~~~~~~~~~
dwarf.c:88:28: note: previous initialization is here
[DW_TAG_template_alias] = "DW_TAG_template_alias",
^~~~~~~~~~~~~~~~~~~~~~~
1 warning generated.
``` …

Fix macOS warning: overrides prior initialization

---

shlr/gdb/src/gdbclient/core.c

LLDB's connect implementation didn't properly handle attaching to the current pid/tid and setting them for step/continue operations. gdbr's implementation is shared with lldb now.
**Test plan**
* Run lldb-server with:
```
lldb-server-10 g localhost:1234 -- test_binary
```
* Run the following command in r2 to connect to the server:
```
oodf gdb://127.0.0.1:1234
```
* Check that the registers are synchronized, step/continue/breakpoints work and that `dp` and `dpt` show the correct thread+process.

Attach to target pid/tid on remote lldb connect ##debug

---

libr/core/cmd.c

I noticed that inside the help under `u?`, there was no indication that some sub commands exists under `uc?`, so I've added the `[?]`. 
I also improved the help under `uc?`, which was just `eprintf`-ing the help, with `r_core_cmd_help()`.
**Test plan**
So, this is what `uc?` will look like with this commit:
```
[0x00000000]> uc?
Usage: uc [cmd] [revert-cmd]  undo core commands
| uc   list all core undos
| uc*  list all core undos as r2 commands
| uc-  undo last action
| uc.  list all reverts in current
```
Please request changes, if necessary.
None

Update `u?` and improve `uc?` ##cons

---

libr/core/cmd_flag.c
libr/core/cmd_open.c
libr/core/core.c
libr/include/r_io.h
libr/include/r_util/r_idpool.h
libr/io/io_desc.c
libr/io/io_fd.c
libr/util/idpool.c
test/db/io/dupfd
test/unit/test_id_storage.c

**DO NOT SQUASH**
================
Based on https://github.com/radareorg/radare2/pull/17271 
* I fixed the review comments i wrote there
* fixed next/prev/lowest/highest apis
* confirm behaviour with r2 tests
* this is ready to review, but ill squash and rebase all the commits properly when the review is done
See https://github.com/radareorg/radare2/pull/17162 and https://github.com/radareorg/radare2/pull/17161
**Test plan**
There are unit and r2 tests
None. thats a feature

Fix #6467 - Add opn/opp/opr commands to priorize next/previous/rotate file ##io

---

libr/core/cmd_debug.c

Close any existing trace session when stopping debug with `doc` to avoid accidentally starting a new debug session with an existing trace. 
**Test plan**
Run `ood` -> `dts+` -> `doc` and see that `dts-` reports that there's no session

Stop trace sessions in the doc command ##debug

---

libr/include/r_parse.h
libr/meson.build
libr/parse/meson.build
libr/parse/p/parse_riscv_pseudo.c
libr/parse/p/riscv_pseudo.mk
plugins.def.cfg
plugins.static.cfg
test/db/anal/riscv
test/db/cmd/cmd_list
test/db/formats/elf/elf-riscv64

What I'm hoping to add here, is support for `asm.pseudo` for the RISC-V architecture. I referred to [The RISC-V Instruction Set Manual](http://content.riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf), notably page 110, for the instructions.
As I am not an expert in this, I was mostly looking at the commit [e28ce](https://github.com/radareorg/radare2/commit/e28ce2990d90660a35053263555d796f034f74e3) and `parse_arm_pseudo.c` to make this possible.
**Test plan**
It seems to work, at least on layman's terms:
I've added a small test which succeeds, but I think its probably not enough, as it's not very big and I believe that there's lot more to fix and add in this PR.
```
$ r2r -i test/db/anal/riscv 
Loaded 4 tests. …
```

Implement `asm.pseudo` for RISC-V

---

libr/io/p/io_windbg.c

Closing windbg io with `oo` caused r2 to crash since debug_windbg's DbgEngContext pointed to a null pointer after it was freed in the io plugin.
**Test plan**
`radare2.exe -A ./file.exe`
`oodf windbg://file`
`doc`
See that r2 doesn't crash and the file is rebased back to normal.

Fix not being able to return from debug when using WinDbg(DbgEng) ##debug

---

.travis.yml

Assembler cares about arch only.
**Test plan**
https://travis-ci.com/github/eagleoflqj/radare2/jobs/431657391
Lots of errors come back instead of instant failure.
On my qemu `r2r db/tools/rasm2` shows 7XXs and they are all not x86.as.
...

Revive travis s390x and fix x86.as test

---

libr/core/cconfig.c
test/db/esil/arm_16

Can't set asm.bits=16 on ppc. Must set asm.arch first.
Also revert #17679 as https://github.com/radareorg/r2ghidra/pull/164 already fix the problem. This has to be reverted because otherwise `e asm.bits` could outputs 16 while the actual bits is still 64 on ppc (here `node->i_value` and `rasm->bits` mismatch). 
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/440088471#L1041 db/esil/arm_16 passed.
...

Fix travis ppc64le db/esil/arm_16

---

README.md

Through #14826, support for AMD Am29000 or AMD 29k was added to radare2, but was never added to the README. I've added that to the list of supported architectures on the README.
**Test plan**
None
Related to #14826

Add AMD Am29000 under architectures on the README

---

libr/util/utype.c
test/db/cmd/types

Current implementation of `r_type_get_struct_memb()` wrongly assumes that struct fields are packed.
**Test plan**
...
Closes #17884 
...

Use offset info in r_type_get_struct_memb()

---

man/r2r.1

On r2r, you can pass the `-i` option for interactive mode. The manpage for r2r has been updated with information about that now.
**Test plan**
Manpage after adding this:
None

Update r2r's manpage about the `-i` mode

---

libr/anal/p/anal_arm_cs.c

* Remove static `RRegItem` from anal_arm_cs.c
**Test plan**
Tests pass

Fix ASAN crash when analyzing arm64

---

libr/anal/fcn.c
test/db/anal/vars

Fix taking over variable use on the last instruction of block

---

libr/core/cmd.c
test/db/cmd/cmd_b
test/db/json/json2

In this patch, I have used the PJ API for the command `bj` and added tests for both `b` and `bj`. `bj` was previously `printf`-ing the output to STDOUT.
**Test plan**
All the written tests pass without any breaks:
```
$ r2r -Vi test/db/cmd/cmd_b
Running from /home/cjunior/Downloads/programs/radare2/test
Loaded 2 tests.
[OK] /home/cjunior/Downloads/programs/radare2/test/db/cmd/cmd_b bj
[OK] /home/cjunior/Downloads/programs/radare2/test/db/cmd/cmd_b b
[2/2]                       2 OK         0 BR        0 XX        0 FX
Finished in 1 seconds.
```
Related to #13969

Use PJ in `bj` and add tests ##json

---

libr/bin/format/pe/pe.c

#16168. It works, but not pretty. pe.c is already big. Any suggestion where to put these code, or another approach to deal with endian?
**Test plan**
https://travis-ci.com/github/eagleoflqj/radare2/jobs/443283549 no such warnings, and db/formats/pe/dllnullep fixed.
...

Fix s390x Warning: File is not PE

---

libr/core/cfile.c
test/db/cmd/cmd_open
test/db/json/json3

`oij` currently works by constructing a JSON string and printing it. Here, I've reimplemented it using the PJ API.
**Test plan**
Using this, `oij` on one of the test binary prints:
`[{"raised":false,"fd":3,"uri":"bins/elf/crackme0x05","from":0,"writable":false,"size":7656},{"raised":true,"fd":5,"uri":"bins/elf/crackme0x00b","from":0,"writable":false,"size":7375}]`
None

Use PJ in `oij` ##json

---

libr/bin/format/mdmp/mdmp.c
libr/bin/format/pe/pe.c
libr/bin/format/pe/pe_specs.h

#16168. Bit field is not portable. And if we set union.a but then uses union.b, it's not portable either.
**Test plan**
```
liumeo@liumeo-s390x:~/radare2/test$ r2 -Qc is~? bins/mdmp/hello.dmp 
[WARN] Invalid or unsupported enumeration encountered 21
[WARN] Invalid or unsupported enumeration encountered 22
Error parsing resource directory
[INFO] Parsing data sections for large dumps can take time, please be patient (but if strings ain't your thing try with -z)!
7469
```
...

Fix s390x mdmp symbols count

---

libr/asm/arch/snes/snes_op_table.h

WDM is a two byte instruction incorrectly being decoded as a single byte. Modified the table to correct this and updated the format string appropriately.
This is a minor change. The `SNES_OP_8BIT` was replaced with `SNES_OP_16BIT`, and the format string was updated to include the operand.
...
**Test plan**
Is it really necessary for such a small change?
...
...

Update snes_op_table.h WDM

---

libr/asm/p/asm_cris_gnu.c
libr/asm/p/asm_hppa_gnu.c
libr/asm/p/asm_lanai_gnu.c
libr/asm/p/asm_mips_gnu.c
libr/asm/p/asm_ppc_gnu.c
libr/asm/p/asm_sparc_gnu.c
libr/asm/p/asm_v850_gnu.c
test/db/anal/v850.gnu

The V850.gnu disassembler target didn't honour memory offset in reading code memory, mis-disassembling e.g. mov instructions with an IMM32 operand. This fixes that.
**Test plan**
echo -ne '\x21\x06\x74\x06\x00\x00' > test.bin; r2 -A -a v850.gnu -c 'pd 1 @0' test.bin
Good output: 0x00000000      210674060000   mov 0x674, r1

asm_*_gnu.c: *_buffer_read_memory: honour memaddr as offset into code buffer

---

libr/bp/bp.c
libr/include/r_bp.h

* Placing breakpoints without a selected bp plugin(the selection can be seen in `dbh`) caused breakpoint creation to fail even though the debug backend might have supported setting a breakpoint.
* It seems that issues with section mapping in avr arch/using qemu gdb information caused confusion in #17931 when breakpoints were marked as invalid and weren't placed. The second change simply adds a warning for users to be aware that their breakpoints aren't going to work without `dbg.bpinmaps` set to false in case they placed them in an invalid addresses.
**Test plan**
* See that you are able to place breakpoints without a selected bp plugin when connecting to gdbserver(you can change the x86 plugin's name in …

Fixed breakpoint placement when no bp arch is available and added a warning for invalid bps ##debug

---

libr/bin/bobj.c
libr/main/radare2.c

```
$ r2 /tmp/speed_test_v51.sfc
Cannot determine if this is a LoROM or HiROM file
Cannot determine if this is a LoROM or HiROM file
WARNING: r_bin_load_languages: assertion 'binfile->o->info' failed (line 70)
WARNING: r_bin_file_set_hashes: assertion 'bin && bin->cur && bin->cur->o && bin->cur->o->info' failed (line 968)
[0x00000000]>
```
**Test plan**
```
$ R2_DEBUG_ASSERT=1 lldb -- r2 /tmp/speed_test_v51.sfc
```
...

Fix asserts in r2 -a snes foo.sfc ##bin

---

libr/core/cannotated_code.c

```
cannotated_code.c: In function 'r_core_annotated_code_print_json':
cannotated_code.c:80:4: warning: 'type_str' may be used uninitialized in this function [-Wmaybe-uninitialized]
pj_ks (pj, "syntax_highlight", type_str);
```
...
**Test plan**
...
...

Fix UB in cannotated_code

---

libr/core/cmd_debug.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/flag/flag.c
libr/include/r_core.h
libr/include/r_util/r_print.h
libr/util/print.c
test/db/anal/x86_32
test/db/cmd/cmd_dr
test/db/cmd/cmd_px

before:
after:
before:
```
$ r2 /tmp/Notes
[0x100002e10]> af
[0x100002e10]> aeim
[0x100002e10]> e io.cache=1
[0x100002e10]> wv reloc.objc_msgSend @ reloc.objc_msgSend
[0x100002e10]> aepc main ; aesu 0x100002e4b;drr~A0,A1,r15
A1   rsi    10025bfba         4297441210 (3.__TEXT.__objc_methname) R X 'jae 0x10025c030' (standardUserDefaults)
A0   rdi    0                 0
r15    1002fcf98         4298100632 (12.__DATA_CONST.__got) R 0x1002fcf98
PC   rip    100002e4b         4294979147 (0.__TEXT.__text) main R X 'call r15'
[0x100002e10]>
```
after:
```
$ r2 /tmp/Notes
[0x100002e10]> af
[0x100002e10]> aeim
[0x100002e10]> e io.cache=1
[0x100002e10]> wv reloc.objc_msgSend @ reloc.objc_msgSend
[0x100002e10]> aepc main ; aesu …
```

drr show all flags and pxrj is now structured ##print

---

libr/cons/hud.c
libr/cons/less.c
test/db/cmd/cmd_interactive_modes

mode
Interactive output modes - Internal less and hud - were available while `e scr.interactive=false`, which caused certain Cutter's console panel - And maybe other UIs - to hang.
**Test plan**
Test available at `test/db/cmd/cmd_interactive_modes`
Closes #17677 "
...

Fix for internal less and hud mode available while in non-interactive

---

.github/workflows/tcc.yml
shlr/heap/include/r_jemalloc/internal/util.h

Building r2 with TCC is somewhat desirable. This PR aims to fix https://github.com/radareorg/radare2/issues/4328
**Test plan**
Maybe add a github action with the following lines:
```
r2pm -ci tcc
export CC="tcc"
r2pm -r ./configure --with-compiler=tcc
r2pm -r make
```
Closes https://github.com/radareorg/radare2/issues/4328

 Bring back tcc support ##build

---

libr/core/anal_tp.c

**Checklist**
The `__var_retype` function is used to change the type of a variable. The provided type is a `const` so it's contents are expected to stay constant.  The current `var->type` will get free'd when it is replaced. So if `var->type == type` then the content of `type` will be corrupted by heap metadata on the free.
I have seen this happen due to `retype_callee_arg` being called with the `type` of some variable, then `retype_callee_arg` obtaining that same variable through the call to `r_anal_var_get_dst_var`. At least, I think that is what is happening. 
I don't know the code here well enough to correct the logic properly, so I added the guard. This should cause some warnings until the logic is fixed but I don't think it should cause too many analysis mistakes. …

Prevent corruption of ##types  __var_retype

---

libr/main/radiff2.c

**Checklist**
There's no open issue for that what there was at some point. the thing is that globals are bad and we want to use radiff2 from inside r2 on multiple threads.

Remove globals in radiff2 ##build

---

libr/anal/esil_dfg.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/include/r_anal.h
libr/include/r_core.h
libr/include/r_util/r_rbtree.h
libr/util/rbtree.c
test/unit/test_esil_dfg_filter.c

**Checklist**
The esil dfg filter already allows filtering for subexpressions, which would compute a specified register. This PR adds const folding to that. The following example shows filtering for eax, w/o const folding:
`4,!,3,ebx,:=,!,1,+,eax,:=  ===> 0x4,!,!,0x1,+,eax,:=`
Now the same with const folding:
`4,!,3,ebx,:=,!,1,+,eax,:=  ===> 0x2,eax,:=`
Const folding is done on the dfg graph, it is a function to tune up the dfg.

Esil dfg lemon const folder

---

libr/core/cmd.c

**Checklist**
```
sys/sanitize.sh
r2r -i test/db/cmd/cmd_table
```

Fix oob in load_table_asciiart ##asan

---

libr/bin/mangling/microsoft_demangle.c

tmp must be initialized to null
in the case a function isn't parsed properly, tmp doesn't get touched in parse_function, so then a wild pointer is free'd
**Checklist**
before
```c
} else {
char *tmp; // uninitialized
err = parse_function (sym, &str, &tmp, &ret);  // tmp doesn't always get touched
*str_type_code = r_str_newf ("&%s", tmp); // empty string
free (tmp); // free uninit var!!!!
}
```

Initialize variable that could result in wild free

---

libr/core/cbin.c
libr/debug/dsession.c

Fix null deref in `is` command ##bin

---

libr/core/cmd_hash.c
libr/core/panels.c
libr/include/r_lang.h
libr/lang/lang.c
libr/lang/p/c.c
libr/lang/p/cpipe.c
libr/lang/p/lib.c
libr/lang/p/pipe.c
libr/lang/p/rust.c
libr/lang/p/spp.c
libr/lang/p/vala.c
libr/lang/p/zig.c
libr/main/radare2.c

* Captures the output of the r2pipe interpreter's `print`
Running r2pipe scripts in visual panels results in no output captured because the `print` statements of the language are printed directly to fd=2, in order to capture them this patch checks if the command is starting with a dot and uses the cmdstr_pipe() function instead.
Known issues:
* I tried to handle #! but it doesnt works. 
```
$ cat test.py
import r2pipe
r2 = r2pipe.open()
print(r2.cmd("?e hehehehe"))
$
```
**Test plan**
run r2 panels mode like this: `r2 -cv /bin/ls`
press `e` to edit the command to run in the current panel and type `. test.py`
without this patch there's no output captured.
None but reported in the chat by dreg

Use r_core_cmd_str_pipe when using `.` in a panel

---

libr/core/cmd_anal.c

**Checklist**
#17898 
`ut64` should be `n`.
https://github.com/radareorg/radare2/blob/4a1a624318704778f784b9d888580f26036f4a46/libr/util/table.c#L205-L210
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r db/cmd/cmd_ab
Loaded 2 tests.
[2/2]                       2 OK         0 BR        0 XX        0 FX
Finished in 0 seconds.
```

Fix arm32 db/cmd/cmd_ab

---

libr/bin/p/bin_any.c
libr/core/cfile.c

**Checklist**
#17898 
No need to assign system bits to unknown file. Instead, this should be done by `info->bits = r->rasm->bits;`.
Also remove some comparisons which are already guaranteed by previous conditions.
Test:
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r db/cmd/cmd_open 
Loaded 30 tests.
[30/30]                    29 OK         1 BR        0 XX        0 FX
Finished in 2 seconds.
```

Fix arm32 db/cmd/cmd_open

---

libr/asm/arch/snes/snesdis.c

**Checklist**
#17898 
See https://github.com/radareorg/radare2/blob/master/libr/asm/arch/snes/snes_op_table.h, there's no 64-bit operator. But `pc` is ut64, so the result have to be converted to 32-bit.
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r -t 0 db/asm/snes_16
Loaded 8 tests.
[8/8]                       8 OK         0 BR        0 XX        0 FX
Finished in 0 seconds.
```

Fix arm32 db/asm/snes_16

---

libr/bin/bin.c
libr/include/r_types_base.h
libr/util/str.c
test/db/cmd/cmd_i

**Checklist**
#17898 
Fix all tests of db/cmd/cmd_i, for various reasons:
* `r_table_add_rowf` wrong format
* `SSIZE_MAX` not defined, so that `#else` branch is applied: https://github.com/radareorg/radare2/blob/56cdc7c112e5a51ce71715dcf84252d016155076/libr/include/r_types_base.h#L104-L114
* wrong limit `sizeof (encoded_str)` which is the size of a pointer passed to `snprintf`. Use `sprintf` is safe since the buffer is big enough and the arg `(ut8) buf[loop]` is 0 to 255.
* assign bit in test
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r db/cmd/cmd_i
Loaded 142 tests.
[142/142]                 134 OK         7 BR        0 XX        1 FX
Finished in 6 seconds.
```

Fix arm32 db/cmd/cmd_i

---

libr/bin/format/dmp/dmp64.c
libr/bin/format/mdmp/mdmp_windefs.h
libr/include/r_util/r_sys.h

**Checklist**
#17898 
* Use `offsetof` instead of wrongly subtracting.
* Eliminate pointer field of `struct windows_exception_record64` in mdmp_windefs.h. `struct windows_exception_record32` also needs modifying, but I can't find a reference of mdmp data structure. There's no test for that either.
* `R_SYS_BITS_32` must be defined as macro, as there are https://github.com/radareorg/radare2/blob/38e33288fb39a5a373885a516d9a2a3a7094f9b5/libr/include/r_types.h#L487 and https://github.com/radareorg/radare2/blob/38e33288fb39a5a373885a516d9a2a3a7094f9b5/libr/include/r_util/r_bitmap.h#L4-L10 Because preprocessor doesn't recognise enum, `#if R_SYS_BITS == 4` always fails since `R_SYS_BITS_32` is treated as 0.

Fix arm32 db/formats/dmp/dmp

---

libr/debug/p/native/windows/windows_debug.h
shlr/heap/include/r_windows/windows_heap.h

My PR radareorg/radare2#17935 must be reverted since it causes a crash after opening binary in debug mode.

Revert "Fix clang-cl build"

---

libr/include/r_regex.h

**Checklist**
#17898 
It's a preprocess problem. Due to the included headers, `libr/search/regexp.c` see `RRegexMatch`'s `off_t` field as 64-bit, while `libr/util/regex/regexec.c` see the `off_t` as 32-bit. This can be noticed by comparing the output of `gcc -I../include -I../../shlr/sdb/src -E regexp.c` and `gcc -I../../include -E regexec.c`.
The macro that produces this difference is `__USE_FILE_OFFSET64`. We can run `gcc -I../include -I../../shlr/sdb/src -E -dM regexp.c` and `gcc -I../../include -E -dM regexec.c` to see the difference.
The solution is to force 64-bit.
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r -t 0 db/cmd/regexp
Loaded 4 tests.
[4/4]                       4 …
```

Fix arm32 db/cmd/regexp

---

libr/anal/rtti_msvc.c
test/db/cmd/cmd_avr

**Checklist**
Note: these 4 functions are not tested, as they are R_API and not used in radare2. This can be easily checked by `git grep`.
r_anal_rtti_msvc_print_complete_object_locator
r_anal_rtti_msvc_print_type_descriptor
r_anal_rtti_msvc_print_class_hierarchy_descriptor
r_anal_rtti_msvc_print_base_class_descriptor

Use pj in rtti_msvc ##refactor

---

test/unit/test_vector.c

**Checklist**
#17898 
Get rid of 64bit specific things.
The macro comes from https://github.com/radareorg/radare2/blob/dcc17e7f327db213f4ad50d7fa358143b69906ad/libr/util/vector.c#L5-L13

Fix arm32 test_vector_fini

---

libr/anal/p/anal_riscv.c
test/db/esil/riscv_64

**Checklist**
- Fix sign extension for load instruction.
- Correction of shift immediate instruction.

Fix ESIL for RISC-V 64-bit load instruction

---

libr/util/print_code.c

**Checklist**
#17898 
The returned string are all used to format the return value of `r_read_ble`, which is ut64.
```sh
pi@liumeo-rpi4:~/github/radare2/test $ r2r db/cmd/cmd_pc
Loaded 15 tests.
[15/15]                    15 OK         0 BR        0 XX        0 FX
Finished in 0 seconds.
```

Fix arm32 db/cmd/cmd_pc

---

libr/anal/d/cc-x86-64.sdb.txt
test/db/cmd/cmd_afcl
test/db/cmd/cmd_ara
test/db/cmd/cmd_tcc

Add amd64syscall calling convention definition ##anal

---

libr/core/cbin.c
libr/core/cmd_anal.c
libr/core/core.c
test/db/anal/vars
test/db/anal/x86_64
test/db/formats/pe/pe64

**Checklist**
`afc=` was superseded by `e anal.cc`

Remove afc=

---

libr/bin/bfile.c
libr/bin/bin.c
libr/bin/i/private.h
libr/core/cbin.c
libr/core/cmd_info.c
test/db/cmd/cmd_i
test/db/formats/mach0/fatmach0

**Checklist**
Before:
```sh
liumeo@liumeo-x64:~/radare2/test$ r2 -Qc iAj bins/mach0/fatmach0-3true
"bins":[{["arch":"x86","bits":64,"offset":4096,"size":13792,"machine":"x86 64 all"]}
{["arch":"x86","bits":32,"offset":20480,"size":13760,"machine":"386"]}
{["arch":"ppc","bits":32,"offset":36864,"size":13616,"machine":"7400"]}
]liumeo@liumeo-x64:~/radare2/test$
```
Now:
```sh
liumeo@liumeo-imac:~/github/radare2/test$ r2 -Qc iAj bins/mach0/fatmach0-3true
{"bins":[{"arch":"x86","bits":64,"offset":4096,"size":13792,"machine":"x86 64 all"},{"arch":"x86","bits":32,"offset":20480,"size":13760,"machine":"386"},{"arch":"ppc","bits":32,"offset":36864,"size":13616,"machine":"7400"}]}
```
Both `rabin2 -Aj` and `r2 -Qc iAj` are fixed. See …

Fix iAj and use pj in bin.c ##refactor

---

libr/anal/fcn.c
libr/anal/p/anal_riscv.c
libr/anal/p/anal_x86_cs.c
libr/asm/arch/riscv/riscv.c
libr/asm/p/asm_dalvik.c
libr/bin/bin.c
libr/bin/format/mach0/dyldcache.c
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dex.c
libr/cons/cons.c
libr/cons/hud.c
libr/core/anal_tp.c
libr/core/canal.c
libr/core/cbin.c
libr/core/cconfig.c
libr/core/cfile.c
libr/core/cmd_debug.c
libr/core/cmd_flag.c
libr/core/cmd_mount.c
libr/core/cmd_type.c
libr/core/visual_tabs.inc
libr/core/vmenus.c
libr/debug/debug.c
libr/debug/dmap.c
libr/debug/p/native/w32.c
libr/main/radiff2.c
libr/main/rasm2.c
libr/util/charset.c
libr/util/syscmd.c

**Checklist**
r_str_get_fail() has been added in appropriate locations throughout the code base after being noticed during the process of adding the PJ API in various files. Additionally, two missing r_str_getf() instances have been added.
The name of r_str_get_fail() is still subject to change. I welcome any suggestions for a new, more descriptive/concise name.

Use r_str_get_fail() throughout codebase ##refactor

---

configure
configure.acr

* Added the Comma API
* Added r_str_wrap() and r_cons_printat() APIs
* Fix adding comments in panels
* Improved help messages
* Removed problematic fortunes
* Add ?et command to change terminal title
* Fix double-click issue in vte terminals
* Formalize the flag names and its filtering APIs
* Fix return code when using q!. Fixes r2pipe.go
* Add experimental asm.flags.real to get strings from bin.str.real
* Removed unmaintained enyo and panels webuis (-2MB)
* Set realname on all bin strings for better asm.flags.real when bin.str.real is set
* Fix ansi colors embedded inside json output formatting
* Improve socket and http server APIs
* Add opn/opr/opp commands to rotate between opened files
* Initial implementation of scr.cursor for keyboard accessibility in visual and panels
* Add …

Release 5.0.0

---

DEVELOPERS.md

**Checklist**
Added a missing space in the expected style for switch statements in DEVELOPERS.md.

Fix incorrect style guide for switch statements in DEVELOPERS.md

---

libr/debug/p/native/windows/windows_debug.c

**Checklist**
This check works almostly as expexted but it compares only first 2.5 (ok, first 3) chars since `sizeof("File")` is 5.

Fix type check and mem leak in w32_desc_list()

---

libr/anal/esil.c
test/db/esil/esil

**Checklist**
Introduce new **~=** operator doing sign extension assignment of a register. For example:
```
> "ae 0x81,a0,="
> "ae 8,a0,~="
> ar a0
0xffffff81
```
This would simplify a lot of ESIL expressions for architecture using sign extension.

Add sign extension assignment operator

---

Makefile

Fix version string from git formerly known as GIT_TAP

---

libr/core/cconfig.c
libr/core/cmd_print.c
test/db/cmd/charset

**Checklist**
`e cfg.charset=pokered; ps` changes now the encoding. I also removed a redundant ps declaration. I preview to separate in 2 commits. I want your opinion first.

Merge pse to ps

---

DEVELOPERS.md

**Checklist**
Also set cino-m to 1 because `setl cino=mN` option is just a zero/non-zero flag, there is no need to set it to 2.

Use tab width 8 in editor configuration templates ##doc

---

libr/cons/cons.c

**Checklist**
* Fix help rendering: avoid printing trailing whitespaces
Related to https://github.com/radareorg/radare2/pull/18103.

Fix help rendering: avoid printing trailing whitespaces ##shell

---

libr/anal/rtti_msvc.c
libr/anal/vtable.c
libr/asm/arch/arm/winedbg/be_arm.c
test/db/asm/arm.winedbg_32
test/db/asm/arm_32

**Checklist**
Some problems noticed when applying @Lazula 's pj patches.
* The return value of `pj_drain` should be manually freed, so better use `pj_string` instead.
* be_arm.c produces something like `ldmdbeq r2, {r0, r1}`, which is not json so pj cannot be applied.
* arm.winedbg lacks tests. I added some from db/asm/arm_32 and find bugs on `msr`, `mrc/mcr` and `cdp`. I fixed them according to [ARM datasheet](https://developer.arm.com/documentation/ddi0406/latest/) B9.3.10, B9.3.11, A8.8.112, A8.8.108 and A8.8.30.
* Removed 3 duplicate tests in db/asm/arm_32

Add test to arm.winedbg

---

libr/asm/arch/arm/winedbg/be_arm.c
test/db/asm/arm.winedbg_32

**Checklist**
* There's no `b register` instruction in armv7 according to https://developer.arm.com/documentation/dui0489/e/arm-and-thumb-instructions/branch-and-control-instructions/b--bl--bx--blx--and-bxj
* According to A8.8.56 of [ARM datasheet](https://developer.arm.com/documentation/ddi0406/latest/), #0 and #-0 generate different instructions, so `offset *= -1;` is wrong.

Test arm part of arm.winedbg

---

libr/core/project.c

**Checklist**
Now the user won't be able to save debugging/emulating projects instead they will get an error.
I think this is kindof related to this issue https://github.com/radareorg/radare2/issues/17034

Tell the user that debugging projects don't work ##projects

---

libr/bin/bfile.c
libr/bin/pdb/pdb.c
libr/core/cbin.c
libr/core/cmd_info.c
libr/core/cmd_open.c
test/db/cmd/cmd_idp
test/db/tools/rabin2

The information packed in the `pdb` field of the json, such as the `types` and `gvars` should be objects inside an array but, with recent changes in the json/pdb area, those were ommited.
The result was an invalid json when calling, for example `rabin2 -Pj some.pdb > some.pdb.json` or `idpij` in the radare shell.
**Test plan**
On the master branch, the issue can be reproduced as follows:
```
$ rabin2 -Pj ntdll.pdb | jq . 1>/dev/null
parse error: ':' not as part of an object at line 1, column 15
```
Also, the issue can easily be seen by inspecting the first items in the resulting json ( the missing `[{` before the `"types"` array):
```
{"pdb":"types":[{"type":"structure","name"
```
With the following fix, the resulting json …

Fix rabin2 -Pj and idpij (json PDB output format) ##bin

---

README.md
libr/main/radare2.c
test/db/cmd/cmd_project
test/unit/test_big.c

**Checklist**
#18150 
```sh
liumeo@liumeo-x64:~/r2asan$ r2
Usage: r2 [-ACdfLMnNqStuvwzX] [-P patch] [-p prj] [-a arch] [-b bits] [-i file]
[-s addr] [-B baddr] [-m maddr] [-c cmd] [-e k=v] file|pid|-|--|=
=================================================================
==5850==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 7 byte(s) in 1 object(s) allocated from:
#0 0x7fe452eb2257 in __interceptor_strdup (/lib/x86_64-linux-gnu/libasan.so.6+0x5a257)
#1 0x7fe4523610eb in r_main_radare2 /home/liumeo/radare2/libr/main/radare2.c:354
#2 0x564ad29fe85f in main /home/liumeo/radare2/binr/radare2/radare2.c:96
#3 0x7fe451791cb1 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x28cb1)
SUMMARY: AddressSanitizer: 7 byte(s) leaked in 1 allocation(s).
```
It was awful. …

Fix memleak in `r2` and test_big

---

libr/core/cmd_anal.c
libr/core/cmd_debug.c

**Checklist**
The commands `arS` and `drS` lacked their internal help. This PR adds the help for both of them under `ar?` and `dr?`, respectively.

Add internal help for `arS` and `drS` ##docs

---

libr/core/cmd_api.c
test/unit/test_buf.c
test/unit/test_cmd.c

Fix memleak in test_buf & test_cmd

---

libr/core/cmd.c

**Checklist**
```sh
liumeo@liumeo-ubuntu:~/github/radare2/test$ r2 -
-- Do you want to print 333.5K chars? (y/N)
[0x00000000]> ac A
[0x00000000]> kj
free(): invalid pointer
Aborted (core dumped)
```

Fix kj segfault

---

libr/core/cmd_print.c

**Checklist**
- Replaces the old `disasm_until_ret` to allow specific optype from `R_ANAL_OP_TYPE_*` members.
- Replaces command `piu` to allow specifying a instruction, like `piu add` to disasm until first `add` opcode.
Example
```
[0x08000040]> pi 11
push rbp
mov rbp, rsp
mov dword [var_ch], 5
mov dword [var_8h], 7
mov edx, dword [var_ch]
mov eax, dword [var_8h]
add eax, edx
mov dword [var_4h], eax
mov eax, dword [var_4h]
pop rbp
ret
[0x08000040]> piuq add
push rbp
mov rbp, rsp
mov dword ptr [rbp - 0xc], 5
mov dword ptr [rbp - 8], 7
mov edx, dword ptr [rbp - 0xc]
mov eax, dword ptr [rbp - 8]
add eax, edx
[0x08000040]> piu pop
0x08000040             push rbp
0x08000041             mov rbp, rsp
0x08000044             mov dword ptr [rbp - 0xc], 5
0x0800004b             mov …
```

Implement print disasm until optype ##print

---

libr/io/p/io_ar.c
shlr/ar/ar.c
shlr/ar/ar.h
test/db/formats/ar

**Checklist**
This PR fixes the archive io plugin. This will let you open `ar://file.a//obj.o` files again. Tests already existed for this, but were marked broken. This PR updates the tests because formatting has changed since the tests worked. Additionally, a couple of the test appear broken from the start (ELF header should not be at entry0).
The code was refactored a lot. While I hope this makes the code more readable, the primary reason for the refactor is to add in open_many support later. Archive files have no compression. So many files could be supported by the single buffer. The `refcount` member of the `RArFp` structure is mostly unused now. When many file support is added it will ensure the underlying `RBuffer` will be cleaned up when the last reference to it is …

Fix and refactor the ar:// plugin ##io

---

libr/asm/arch/arm/armass64.c
test/db/asm/arm_64

**Checklist**
* Distinguish post-index, pre-index and unsigned offset in `ldrsb` (and so on) immediate mode
* Support extended register offset (uxtw, sxtw, sxtx) and shifted register offset (lsl) in `ldrsb` (and so on) register mode
* Support `ldrsw` label mode
* Add and fix constraints on register bits (32 vs 64)
* Add and fix wrong tests (generated by trusted arm.as, guaranteed by disassemble result)
*  Drop some meaningless (and maybe wrong tests) ~~as I don't want to copy-paste and correct them~~

Initial support for arm64 asm extendtype ##asm

---

libr/util/list.c

**Checklist**
If you pop from an empty list the `RList->length` value will go negative. I think this is an unexpected state that could cause unexpected behavior.
I don't know if there is any code in r2 that uses this in an unsafe way. I only found this because I did a `while (r_list_pop (list))` and ended up with a list of length -1.

Fix underflow in r_list_pop

---

libr/asm/arch/arm/armass64.c
test/db/asm/arm_64

**Checklist**
* Define `cond_check` to reduce code. Also, positive condition is better than negative condition.
* Extract register encoding logic in common, so that fix the bug below:
```sh
liumeo@liumeo-x64:~$ rasm2 -a arm -b 64 'stur x0, [x30]'
p/../arch/arm/armass64.c:316:61: runtime error: left shift of 30 by 29 places cannot be represented in type 'int'
c00300f8
```
* Support sbfm/ubfm and their aliases sbfx, ubfx, sbfiz, ubfiz.
```sh
liumeo@liumeo-imac:~$ rasm2 -aarm -b64 "UBFX X8, X0, 8, 8"
083c48d3
```

Support sbfm/ubfm in arm64 ##asm

---

libr/core/panels.c

Fix 'left'/'h' key in Symbols tab

---

libr/core/cmd_anal.c
test/db/esil/x86_64

FIx #18171 - Support RNum for syscall-name in `asl` command ##anal

---

libr/io/io.c
libr/io/p/io_ar.c
shlr/ar/ar.c
shlr/ar/ar.h

**Checklist**
This ads open_many support to the ar IO plugin. Not much to see or test yet because opening multiple files does not seem to work right now (see #18194). 
I did step through this in gdb to ensure there are no leaks. Even when the AR parser passes the magic bytes test but fails to parse the first ar file. The trickery with the reference counter works well.
I also added a line is added to `r_io_open_many` to ensure it's returned `RList` is will not have it's `RIODesc` members closed (free'd) when the list is free'd. The `r_io_open_many` function stores each `RIODesc` element of the list in io storage (via `r_io_desc_add`). So if the list keeps it's free method, a double free will occur when IO is free'd. The zipall plugin deals with this by returning a list that …

Add arall:// and liball:// #IO plugin

---

libr/core/cmd_open.c

**Checklist**
```sh
r2 -Qc doo -
```
My bad doing #18178. `r_io_reopen` frees `desc`.

Fix `doo` segfault

---

libr/anal/esil.c
test/db/esil/esil

**Checklist**
Add floating point operations. This is based on code by @FXTi in r2ghidra, slightly adapted to push the doubles to the stack as normal hex strings. This results in a lot less friction with the current working of ESIL

Esil float

---

libr/core/cfile.c
libr/core/disasm.c
test/db/cmd/cmd_pd2
test/db/cmd/metadata

* The Cd size is now honored even if its HUGE
* so still not honoring this
* asm.meta=false still not supporting this well
**Checklist**

Fix #18202 - Large Cd truncates and crashes in pd ##disasm

---

libr/io/Makefile
libr/io/io_memory.c
libr/io/io_memory.h
libr/io/meson.build
libr/io/p/io_http.c
libr/io/p/io_malloc.c
libr/io/p/io_tcp.c

**Checklist**
Replace buggy http/tcp plugins' read (and maybe others) to malloc plugin's implementation.
Before:
```sh
liumeo@liumeo-imac:~/github/radare2$ r2 tcp://localhost:8001
-- Order pizza for $12.48? [Y/n]
[0x00001fa0]> aaa
[Cannot find function at 0x00001fa0 sym. and entry0 (aa)
[x] Analyze function calls (aac)
[x] find and analyze function preludes (aap)
[x] Analyze len bytes of instructions for references (aar)
[x] Check for vtables
[x] Finding xrefs in noncode section with anal.in=io.maps
[x] Analyze value pointers (aav)
[x] Value from 0x00000000 to 0x0000353c (aav)
[x] 0x00000000-0x0000353c in 0x0-0x353c (aav)
[Warning: No SN reg alias for current architecture.aaef)
Warning: No SN reg alias for current …
```

Reuse code in memory-based io plugins ##refactor

---

libr/anal/esil.c
libr/include/r_util/r_num.h

**Checklist**
Use unions instead of type punning in order to eliminate errors, avoid endian issues, and generally clean up the code so it is not hacky af. Will be tested by CI

Unionize ESIL float conversions

---

libr/core/cmd_anal.c

**Checklist**
#18150 
https://github.com/radareorg/radare2/runs/1695017648#step:4:86711
Occurs when emulating more than 1 instructions:
```sh
r2 -Qc 'aecu 4' -
```
Don't use goto back and forth. Use for+continue to guarantee freeing.

Fix memleak in `aecu`

---

libr/util/lib.c

Fix plugin type name array issue in Lc command

---

libr/bin/format/mach0/mach0_defines.h
libr/bin/p/bin_xnu_kernelcache.c

**Checklist**
Fix a crash happening when opening XNU standalone kernels for arm64 macOS. It happened because it's not a kernel cache, though it retains empty information about kexts.
After fixing it, also noticed the pointer rebasing wasn't working correctly, because this kind of kernels has a different chained pointer format, so i added it and took the chance to rename one of them for which i didn't know the name at the time i wrote the logic to handle it.

Fix crash in XNU kernel parsing (no cache) ##bin

---

libr/anal/diff.c
libr/main/radiff2.c
man/radiff2.1

**Checklist**
- [X ] Closing issues: 18235, 18236 and 18244.
- [ X] Mark this if you consider it ready to merge
**Issue 18236**
This fix makes changes to `libr/main/radiff2.c`  around line 1118.  I included a description of how to build a test case when I submitted this issue.
**Issue 18235**
This fix changes line 189 in  `libr/anal/diff.c.`  This is "it can't happen here" code, so it's not clear how to build a test case.  The original code is incorrect on inspection.  If either `fcn->name`  or `fcn2->name` is `NULL`, control falls into the code that will compare one function with a `NULL` name to one function with a name that may not be `NULL`.
**Issue 18244**
Fixes some minor documentation inconsistencies that I spotted.  I believe I understand the current semantics for …

Minor bugfixes to radiff2

---

libr/bin/format/mach0/mach0.c
libr/bin/format/objc/mach0_classes.c
libr/core/carg.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_skiplist.h
libr/util/skiplist.c

**Checklist**
#18150 
As I said in discord, there's a problem of `r_skiplist_insert`. When it meets duplicate key, it simply returns the original node. but this result is always ignored, thus a call `r_skiplist_insert (list, data)` may cause memory leak.
Should we check the result every time, or use a new function to insert and free if duplicate?
the leak can be reproduced by `r2 -Qc 'pd 2~?push' bins/mach0/arm16-ofp.lzh`

Fix memleak in db/esil/apple

---

libr/bin/format/mach0/mach0.c
libr/bin/p/bin_mach0.c
test/db/formats/mach0/fatmach0

**Checklist**
The gist of it is: compensate for the bin file offset when running the rebasing logic.
This aims to fix the same problem as https://github.com/radareorg/radare2/pull/18222 in a less hacky way.
I still think that fat slices should be mapped alone and not relying on bin file offset, but this works in the short term.

Fix Mach-O rebase on fat slices ##bin

---

libr/util/unum.c

* unum.c:41: runtime error: passing zero to clz(), which is not a valid argumentruet
**Checklist**

Fix UB in clz(0) spotted by asan

---

libr/core/cmd_print.c
libr/core/disasm.c
libr/core/task.c
libr/core/yank.c
libr/include/r_core.h
test/db/cmd/cmd_pd
test/db/esil/x86_32
test/db/formats/elf/crash
test/db/formats/elf/helloworld-gcc-elf
test/db/json/json1
test/db/json/json4

**Checklist**
After this, the only handmade json in core is in cmd_type.c, which is hard to replace because
1. it calls `r_core_cmdf`
2. it's in a callback function

Use pj in core ##refactor

---

libr/core/cbin.c
libr/core/cconfig.c
test/db/cmd/types

Add bin.cache evar to use io.cache when bins need to patch relocs ##bin

---

libr/bin/format/wasm/wasm.c
libr/bin/format/wasm/wasm.h
test/db/formats/web_assembly

Fix crash when wasm file contains symbols with large names ##bin

---

libr/core/cmd_mount.c

When executing 'mg', the message is printed when file does not previously exist.  With this fix, error message is only printed when the file exists and cannot be truncated.

Fix mg when file exists and cannot be created

---

libr/core/core.c
libr/main/radare2.c
test/unit/test_esil_dfg_filter.c

Fix memleak in test_r2pipe & test_esil_dfg_filter

---

libr/anal/cc.c
libr/core/canal.c
libr/include/r_anal.h

* fix anoying warning on archs with dynamic or unknown regprofiles
**Checklist**

Warn once about the missing anal.cc ##anal

---

libr/core/canal.c

Use r_core_flag_get_by_spaces() in getFunctionName() ##rizin
