libr/egg/egg.c

The code piece is 9 years old. At that time arm64 wasn't an option.
**Test plan**
My travis test https://travis-ci.com/github/eagleoflqj/radare2/jobs/401773540#L1509 db/tools/ragg2 passed.
...

Fix travis arm64 db/tools/ragg2

---

libr/socket/run.c
libr/util/sys.c

Setting ASLR support for DragonFlyBSD ##util

---

test/db/cmd/feat_redirect

`-f` option isn't supported in r2, so this file wasn't removed after running test.
**Test plan**
...
...

Fix temp file remains after test

---

shlr/grub/kern/mm.c

https://ci.appveyor.com/project/radareorg/radare2/builds/35901972/job/ghq9uefp4vktn6wj?fullLog=true#L1323
Fix by removing unused functions.
**Test plan**
...
...

Fix msvc warning pointer truncation

---

libr/core/cbin.c

https://ci.appveyor.com/project/radareorg/radare2/builds/35901972/job/ghq9uefp4vktn6wj?fullLog=true#L2298
**Test plan**
...
...

Fix msvc warning 'void' function returning a value

---

test/db/cmd/feat_variables

Same reason #17816 
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/403845113#L490 db/cmd/feat_variables passed.
...

Fix travis arm64 db/cmd/feat_variables

---

libr/core/agraph.c
libr/core/cmd_anal.c

Got broken with https://github.com/radareorg/radare2/commit/6b6f88efd32c9bf8433c9a28106977f7906cae4c
**Test plan**
Manual test

Fix prompt autocompletion when in graph mode

---

libr/asm/p/asm_dalvik.c

Original https://travis-ci.com/github/radareorg/radare2/jobs/404238389#L405.
Another signed char on arm issue. It should be signed char as per https://source.android.com/devices/tech/dalvik/dalvik-bytecode 28 10t.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/405817075#L1355 db/asm/dalvik passed.
...

Fix travis arm64 db/asm/dalvik

---

libr/io/p/io_debug.c

As with the windbg implementation of `fork_and_ptraceme`, this checks for the presence `io->args` and appends its contents to the child command before invoking it.
The primary purpose of this fix is to make argument-passing possible when using Cutter to debug programs, as Cutter sets `dbg.args` in order to pass user-provided arguments to the child task. Presently, this does not do anything on *nix platforms, greatly limiting Cutter's usefulness insofar as debugging.
**Test plan**
Using the modifications from this PR, repeat the steps described in #17845 and observe that the contents of `dbg.args` is now printed appropriately
closes #17845

Use dbg.args on *nix and macos ##debug

---

test/db/cmd/cmd_print

Yet another arch issue.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/405395627#L524 db/cmd/cmd_print passed.
...

Fix travis arm64 db/cmd/cmd_print

---

libr/core/cmd_anal.c

...
**Test plan**
...
Closes #17843 
...

Don't clear write cache in "aaa"

---

libr/core/cbin.c

Fix ub pj cbin

---

sys/debian/CONFIG
sys/debian/radare2-dev/CONFIG
sys/debian/radare2-dev/Makefile
sys/debian/radare2/CONFIG
sys/debian/radare2/Makefile

Fixes and improvements for the Debian packaging scripts ##build

---

.travis.yml

Add command to install r2pipe which appears in Dockerfile.travis.
**Test plan**
My travis test https://travis-ci.com/github/eagleoflqj/radare2/jobs/401798723#L424 passed.
...

Fix travis arm64 db/cmd/cmd_pipe

---

libr/core/cmd.c

Fix UB in r_core_cmd_init

---

test/db/cmd/cmd_px

New test with old arch issue.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/407525976#L1165 db/cmd/cmd_px passed.
...

Fix travis arm64 db/cmd/cmd_px

---

test/db/cmd/cmd_ara

Maybe the last arch issue.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/407817490#L544 db/cmd/cmd_ara passed.
Only 3 tests fail now.
closes #17803

Fix travis arm64 db/cmd/cmd_ara

---

libr/socket/r2pipe.c

Do not show return code message in r2pipe api if it succeds

---

.github/workflows/ci.yml
binr/r2r/run.c
test/db/cmd/cmd_aae

The pr is because:
1. The master asan build is still timing out on the cmd_aae test despite #17793.
2. I accidentally ran the asan+fuzz tests (probably because I used the pencil) and the following asan fuzz test is timing out (https://github.com/radareorg/radare2/runs/1274872621#step:15:20):
**Test plan**
...

Add 6 minutes to cmd_aae timeout and skip aaa for swift_read fuzz test

---

.appveyor.yml

The [current Visual Studio 2019 version](https://www.appveyor.com/updates/2020/10/26/) on AppVeyor appears to be significantly slower than the previous version (compare [build 8019](https://ci.appveyor.com/project/radareorg/radare2/builds/35969274/job/66xv58jrm3wy8m7v?fullLog=true#L3198) with [build 8020](https://ci.appveyor.com/project/radareorg/radare2/builds/35973349/job/gi0canyx39j44l53?fullLog=true#L3197)). As a temporary measure, this pr reverts back to the previous version.
It appears that we need to send a request to AppVeyor support [for a build timeout greater than 60 minutes](https://github.com/appveyor/ci/issues/517#issuecomment-429520574).
**Test plan**
...

Revert to previous Visual Studio 2019 image for Windows tests

---

libr/anal/sign.c
libr/core/cmd_print.c

Fix #17857 - Fix warnings

---

libr/core/anal_tp.c

Fix UB in r_core_anal_type_match

---

libr/bin/format/mach0/mach0.c

https://ci.appveyor.com/project/radareorg/radare2/builds/35901972/job/ghq9uefp4vktn6wj?fullLog=true#L1912
**Test plan**
...
...

fix msvc warning not enough args for macro

---

.travis.yml

Use x86 gas for corresponding rasm2 tests
**Test plan**
All green
Resolves part of the https://github.com/radareorg/radare2/issues/17814

Fix rasm2 tests for PPC and S390

---

libr/bin/format/dmp/dmp64.c
libr/bin/format/dmp/dmp_specs.h
libr/bin/format/elf/elf.c
libr/bin/p/bin_dmp64.c

Fix warnings in RBin.{dmp,elf}

---

libr/anal/fcn.c

Fix memleak in __anal_fcn_check_bp_use()

---

libr/core/cmd_anal.c

`core->rasm->cpu` is `""` here. It seems `arch` field is treated more seriously than `cpu`.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/410652751#L1288 db/anal/x86_32 passed.
...

Fix travis arm64 db/anal/x86_32

---

libr/debug/p/debug_native.c

...
**Test plan**
https://travis-ci.com/github/radareorg/radare2/jobs/417635109#L351
https://travis-ci.com/github/eagleoflqj/radare2/jobs/419279434#L349
...

Remove some arm64 warnings

---

libr/anal/esil.c
libr/include/r_types_base.h
libr/include/r_types_overflow.h

Add division overflow macros in r_types ##util

---

libr/asm/arch/z80/z80.c
libr/asm/arch/z80/z80_tab.h

Constify.
**Test plan**
https://ci.appveyor.com/project/radareorg/radare2/branch/master/job/te1llyok9ft5wnc6?fullLog=true
https://ci.appveyor.com/project/eagleoflqj/radare2/builds/36064030/job/hu06c5tdgn3mpue1?fullLog=true
No C4090 in z80.
...

Fix msvc warning c4090 in z80

---

libr/cons/grep.c
test/db/archos/darwin-x64/http
test/db/archos/linux-x64/http
test/db/cmd/tables
test/db/formats/ne
test/scripts/test-webserver.sh

This pr makes it such that `~:s..e` doesn't skip blank lines, for the following reasons:
1. Skipping blank lines only guarantees that each line has at least 1 char, which doesn't seem particularly useful.
1. Skipping blank lines causes the line numbers to be out of sync compared to an editor's line numbers (now it's just off-by-1).
**Test plan**
...

~:s..e doesn't skip blank lines

---

libr/anal/block.c
libr/anal/fcn.c
libr/anal/function.c
libr/anal/var.c
libr/core/agraph.c
libr/core/cconfig.c
libr/core/core.c
libr/include/r_anal.h
libr/include/r_io.h
libr/include/r_util/r_event.h
libr/io/io.c
libr/io/io_cache.c
libr/io/io_plugin.c
libr/io/p_cache.c
test/db/cmd/write

* Re-analyze function control flow after a write
* Refresh graph after a write
**Test plan**
Test pass
Fixes #15644

Re-analyze function control flow after a write ##anal

---

libr/core/cmd_type.c
test/db/cmd/types

Half of #17884 fixed
**Test plan**
Tests pass

Fix printing array types inside structs in C format ##types

---

libr/parse/code.c
shlr/tcc/libr_tcc.h

Include .h instead of .c.
`tcc_sym_push` isn't in the header, so explicitly delare.
No LNK4006.
**Test plan**
https://ci.appveyor.com/project/radareorg/radare2/branch/master/job/te1llyok9ft5wnc6?fullLog=true
https://ci.appveyor.com/project/eagleoflqj/radare2/build/job/b2k1kmmwao93h0ii?fullLog=true
...

Fix msvc warning LNK4006

---

libr/bin/format/coff/coff.c

Fix #17878 (COFF fuzz segfault)

---

libr/core/core.c
libr/util/file.c
libr/util/str.c

Fix r_core_editor() on Windows ##ports

---

.github/workflows/ci.yml

Checking if it helps with https://github.com/radareorg/radare2/issues/17870

Add MacOS Meson build job

---

libr/bin/p/bin_coff.c

`r_bin_coff_obj::scn_va` can be NULL:
https://github.com/radareorg/radare2/blob/87b10ed586ce6eff6af4e65ea93ed81b82ebce24/libr/bin/format/coff/coff.c#L198-L201
so this pr adds guards around its use. This was originally done to fix #17878 but now it's to prevent future segfaults.
**Test plan**
...

Add r_bin_coff_obj::scn_va guards

---

libr/util/file.c

Reworked version of https://github.com/radareorg/radare2/pull/17908 （revert of the offending commit)
**Test plan**
All green.

Fix Windows tests - partial revert of a26f6c5

---

libr/anal/esil2reil.c
libr/bin/dwarf.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_pe64.c
libr/bin/p/bin_qnx.c
libr/debug/dreg.c
libr/debug/pid.c
libr/flag/zones.c
libr/include/r_types.h
libr/io/io_cache.c
libr/io/io_plugin.c
libr/io/p/io_r2k_linux.c
libr/util/format.c
libr/util/print.c
libr/util/print_code.c

Continuation of https://github.com/radareorg/radare2/pull/17529 but also covering `PrintfCallback` type that often used for defining printing callbacks.
**Test plan**
All green

Apply compiler checks for PrintfCallback

---

libr/anal/class.c

Random negative numbers #17898.
There remains a potential bug https://github.com/radareorg/radare2/blob/91aebb64901285f5177151604816d270d0862039/libr/anal/class.c#L512
which should be `atoll` but it's only available in C99. I notice ANSI C building is still supported now, so I didn't change this.
**Test plan**
`r2r db/cmd/cmd_ac` on rpi4.
...

Fix raspbian32 db/cmd/cmd_ac

---

libr/crypto/p/crypto_serpent.c
libr/crypto/p/crypto_serpent_algo.c
libr/crypto/p/crypto_serpent_algo.h
test/db/tools/rahash2

UB in crypto_serpent.c: out of boundary memory read.
UB in crypto_serpent_algo.c: shift of int more than 31.
Partially solved #15849 and #17898 
**Test plan**
https://travis-ci.com/github/radareorg/radare2/jobs/427537252#L1047
https://travis-ci.com/github/eagleoflqj/radare2/jobs/430534124#L1020
db/tools/rahash2 fixed.
...

Fix UB in serpent

---

libr/core/linux_heap_glibc.c

Internal help for `dmhj` was missing inside the help for `dmh?`. I've added that in this Pull Request.
**Test plan**
See if there's a change which needs to be addressed.
None

Add internal help for `dmhj` ##cons

---

libr/core/cfile.c
test/db/tools/rasm2

Fix `asm.bits` showing random negative numbers #17898.
**Test plan**
`r2r db/tools/rasm2` on rpi4. Only cases with R2_X86AS remain (hopefully someday I get a cross-assembler).
...

Fix raspbian32 db/tools/rasm2 push ebp

---

libr/anal/esil.c

...
**Test plan**
`r2r db/anal/x86_64` on rpi4. 3XX->1XX
...

Fix raspbian32 db/anal/x86_64 sar on x86-64

---

libr/io/p/io_r2k_linux.c

Partially solve #17121.
**Test plan**
https://travis-ci.com/github/eagleoflqj/radare2/jobs/432619041
No format warnings.
...

Fix arm64 format warnings

---

libr/include/r_util/r_time.h
libr/magic/file.h
libr/magic/mdump.c
libr/magic/softmagic.c
libr/util/format.c
libr/util/time.c

Defined `r_ctime_r` like `r_asctime_r`. There remain 2 `localtime` calls in shlr, so I didn't change [them](https://lgtm.com/projects/g/radareorg/radare2/alerts/?mode=list&id=cpp%2Fpotentially-dangerous-function).
Also removed the `size` parameter in `r_asctime_r`. As said [there](https://github.com/radareorg/radare2/pull/17465#issuecomment-696270740) it's useless, but before we call it, we have to make sure the buffer is big enough, so no need to even pass this parameter.
**Test plan**
...
...

Fix some LGTM dangerous functions

---

libr/anal/p/anal_arm_cs.c
libr/anal/var.c
libr/core/canal.c
libr/include/r_anal.h
test/db/anal/arm64
test/db/anal/vars

* Add `R_ANAL_VAR_ACCESS_TYPE_PTR`
* Fix ARM64 preindex esil to actually modify the register before doing the operation
* Fix destination register for store ops with multiple sources
* Fix source register for load ops with multiple destinations
* Fix src/dst register for post-indexed ops
* Fix src/dst delta info
* Fix stack modification detection with add instruction
* Fix `tmp` esil register breaking variable access info
* Fix stack analysis for indexed load/stores
* Fix variable detection at sp
* Add ARM64 pre-indexed `str` function prelude
* Fix tests
**Test plan**
Tests pass

Fixes for variable access analysis for ARM64

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mdmp/mdmp.c
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_elf.inc
libr/bin/p/bin_mdmp.c
libr/bin/p/bin_pe64.c
libr/core/cmd_flag.c
libr/core/pseudo.c
libr/debug/dsession.c
meson.build
shlr/sdb/Makefile
shlr/sdb/README.md
shlr/sdb/meson.build
shlr/sdb/src/Makefile
shlr/sdb/src/ls.c
shlr/sdb/src/main.c
shlr/sdb/src/sdb.c
shlr/sdb/src/sdb.h
shlr/sdb/src/text.c

**DO NOT SQUASH**
Memleak in `shlr/sdb/src/main.c`  causes build error in case of using mesonbuild with ASAN.
**Test plan**
...
...

Update sdb to 2faeca6dfe516b3ab5f1fcd3655d878fdcbdad0f

---

test/.gitignore
test/db/cmd/cmd_project

Another 16bit on ppc issue.
Origin: https://github.com/radareorg/radare2-regressions/pull/841, so 16bit is kept but on a platform that supports it.
Moreover, ignore temp files left after running `r2r db/cmd/cmd_project`.
**Test plan**
My travis https://travis-ci.com/github/eagleoflqj/radare2/jobs/440092506#L437 db/cmd/cmd_project passed.
...

Fix travis ppc64le db/cmd/cmd_project & ignore tmp

---

libr/anal/p/anal_arm_cs.c
libr/anal/var.c
libr/asm/arch/pyc/opcode.c
libr/bin/dwarf.c
libr/bin/format/le/le.c
libr/cons/cons.c
libr/cons/input.c
libr/core/windows_heap.c
libr/debug/p/debug_native.c
libr/debug/p/native/windows/windows_message.c
libr/io/p/io_w32dbg.c
libr/magic/fsmagic.c
libr/util/str.c
libr/util/sys.c
libr/util/thread.c

Fixing format and type warnings.
**Test plan**
All green.

Fix some warnings in Windows and Linux builds

---

libr/debug/p/debug_windbg.c

Fix copy-paste bug in windbg_reg_read()

---

libr/debug/p/native/windows/windows_debug.h
shlr/heap/include/r_windows/windows_heap.h

...
**Test plan**
...
Closes #17926 
...

Fix clang-cl build

---

libr/main/rax2.c

A step forward to solve #16168.
**Test plan**
https://travis-ci.com/github/eagleoflqj/radare2/jobs/442084042 is not readable, but on my qemu it was 10XXs, now is
```
liumeo@liumeo-s390x:~/radare2/test$ r2r db/tools/rax2 
Running from /home/liumeo/radare2/test
Loaded 67 tests.
[67/67]                    66 OK         1 BR        0 XX        0 FX
Finished in 26 seconds.
```
...

Fix s390x rax2

---

libr/hash/fletcher.c
libr/hash/hcalc.c
libr/include/r_hash.h

A step forward to solve #16168.
**Test plan**
`r2r db/tools/rahash2` 24 XXs -> 21 XXs on my qemu.
...

Fix s390x fletcher

---

libr/anal/fcn.c
libr/bin/bin.c
libr/core/cbin.c
libr/core/cconfig.c

Fix memleak in fcn_recurse(), r_bin_info_free(), r_core_anal_cc_init(), update_asmbits_options()

---

libr/anal/p/anal_xtensa.c
libr/asm/arch/include/xtensa-isa.h

#17814
**Test plan**
Original: https://ci.appveyor.com/project/radareorg/radare2/builds/36421278/job/62gagbgrkfruxok4#L3228
Current: https://ci.appveyor.com/project/eagleoflqj/radare2/builds/36441248/job/331wi2a6o001j901#L3154
...

Fix msvc warning LNK4217

---

test/unit/test_dwarf_info.c

#16168. https://travis-ci.com/github/radareorg/radare2/jobs/443337475 down to the end, test_dwarf4_cpp_multiple_modules ERR.
Should access the correct member of the union.
**Test plan**
On my qemu
```sh
liumeo@liumeo-s390x:~/radare2/test$ unit/bin/test_dwarf_info 
test_dwarf3_c OK
test_dwarf4_cpp_multiple_modules OK
test_dwarf2_big_endian OK
```
...

Fix s390x unit/bin/test_dwarf_info

---

libr/anal/d/Makefile
libr/anal/d/cc-sysz-64.sdb.txt
libr/anal/d/meson.build

#16168
Reference: https://refspecs.linuxfoundation.org/ELF/zSeries/lzsabi0_zSeries.html#AEN413
**Test plan**
`r2 -a sysz -` no warning.
...

Define calling convention for sysz

---

libr/asm/p/asm_x86_nz.c

#16168. Fixed 6 XXs.
**Test plan**
```sh
liumeo@liumeo-s390x:~/radare2/test$ r2r db/asm/x86_64
Running from /home/liumeo/radare2/test
Loaded 1077 tests.
[1077/1077]              1053 OK        24 BR        0 XX        0 FX
Finished in 2 minutes and 1 seconds.
```
...

Fix s390x db/asm/x86_64

---

test/db/cmd/archs
test/db/cmd/cmd_aek
test/db/cmd/cmd_pf
test/db/cmd/cmd_print
test/db/cmd/types

#17898 
**Test plan**
```
pi@liumeo-rpi4:~/github/radare2/test $ r2r -j8 db/cmd/{archs,cmd_aek,cmd_pf,cmd_print,types}
Loaded 198 tests.
[198/198]                 193 OK         5 BR        0 XX        0 FX
Finished in 15 seconds.
```
...

Fix some tests on arm32

---

libr/core/cbin.c
test/db/formats/mz/cdogs

Before:
`r2 -QAq test/bins/le/cdogs.exe  32.80s user 158.66s system 99% cpu 3:11.46 total`
After:
`r2 -QAq test/bins/le/cdogs.exe  3.34s user 0.08s system 99% cpu 3.430 total`

Fix not needed sdb reloading

---

libr/core/p/core_java.c

***SQUASH ME***
==============
```
libr/core/p/core_java.c: In function 'r_cmd_java_handle_help':
libr/core/p/core_java.c:390:34: warning: iteration 20 invokes undefined behavior [-Waggressive-loop-optimizations]
help_msg[3 + (i * 3) + 0] = cmd->name;
~~~^~~~~~
libr/..//libr/core/p/core_java.c:388:2: note: within this loop
for (i = 0; i < END_CMDS; i++) {
```
...
**Test plan**
...
...

Fix UB in core.java plugin

---

libr/util/skyline.c

Fix UAF in r_skyline_add()

---

.appveyor.yml
.github/workflows/ci.yml
binr/r2r/r2r.c
binr/r2r/r2r.h
binr/r2r/run.c
test/.gitignore
test/Makefile

* Fix warning in r2r/run.c
* Add option to log r2r test results
* Upload test results artifacts on CI

Add option to log r2r test results

---

test/unit/meson.build
test/unit/test_skyline.c

Add unit tests for RSkyline

---

shlr/grub/include/grub/cpu/types.h

#16168. GRUB supports big endian. We need to enable it.
**Test plan**
https://travis-ci.com/github/radareorg/radare2/jobs/443337475#L18924 the 10k+ lines of "+f" will go away.
```
liumeo@liumeo-s390x:~/radare2/test$ r2r db/cmd/cmd_fs
Running from /home/liumeo/radare2/test
Loaded 18 tests.
[18/18]                    18 OK         0 BR        0 XX        0 FX
Finished in 4 seconds.
```
...

Fix s390x db/cmd/cmd_fs

---

libr/core/cmd_print.c

Minor optimizations to cmd_print.c

---

libr/bin/pdb/pdb.c
libr/util/name.c
test/db/formats/pdb

Set realname for PDB flags

---

libr/util/skyline.c

Fix another UAF in skyline

---

README.md

...
**Test plan**
...
closes #17958

Document local meson build

---

test/db/archos/darwin-x64/http

Aim to fix the http test in macOS

---

libr/core/cmd.c

```
cmd.c: In function 'cmd_autocomplete':
cmd.c:2151:29: warning: iteration 15 invokes undefined behavior [-Waggressive-loop-optimizations]
if (autocomplete_flags[i].desc) {
~~~~~~~~~~~~~~~~~~~~~^~~~~
cmd.c:2150:3: note: within this loop
for (i = 0; i < R_CORE_AUTOCMPLT_END; i++) {
^~~
```
...
**Test plan**
...
...

Remove R_CORE_AUTOCMPLT_END and fix UAF/crash

---

libr/anal/p/anal_v850.c

Add ep and lp register aliases for v850 ##disasm

---

test/db/anal/snes
test/db/asm/snes_16

See https://github.com/radareorg/radare2/pull/17988
**Test plan**
The bin comes from https://github.com/VitorVilela7/SnesSpeedTest/blob/master/speed_test_v51.sfc
...

Add tests for snes

---

libr/bin/format/pe/pe.c

r_buf_read is extremely slow
**Test plan**
Tests pass 
Closes #17979

Fix #17979 - Fix ASAN timeout for PE

---

configure
configure.hook

Fix acr quiet version

---

libr/core/cconfig.c
libr/core/disasm.c

Make hints seek directly to indirect call target address

---

libr/anal/type_pdb.c
libr/bin/pdb/pdb.c
libr/bin/pdb/tpi.c

Fix #17976 - PDB: Fix NULL deref with unsupported leaf type

---

libr/anal/p/anal_arm_hacks.inc
libr/asm/p/asm_arm_hacks.inc
test/db/anal/arm64
test/db/asm/arm_64

* Fix addg/subg instruction decoding
* Fix MTE intruction decoding in big endian mode
**Test plan**
Tests pass
https://github.com/radareorg/radare2/issues/17135#issuecomment-739334643 
cc @AmerNTahat

Fixes for ARM MTE ##anal

---

libr/core/cmd_anal.c
libr/core/cmd_print.c
test/db/json/json1

Added internal help for `aij` and `arj` under `ai?` and `ar?`, respectively. 
Also updated `test/db/json` with `aij`.
I'm also hoping to add help for `pdaj`. But I'm confused on where exactly to add them.
**Test plan**
None.

Add help for `aij` and `arj` ##anal

---

libr/core/cmd_hash.c

Cleanup cmd_hash.c a little bit

---

Makefile

Improve GIT_{TIP,TAP,VER}

---

libr/core/agraph.c
libr/core/cmd.c
libr/core/panels.c
libr/core/visual.c
libr/include/r_cons.h
libr/include/r_core.h
libr/include/r_util/r_panels.h

* function signatures DO NOT have a space before the (
* use size_t in some places
* do not put all the static functions on top
* Prefix public functions with r_core_panel_*
* move functions up and down to order them by dependency
**Test plan**
no logic changes in this PR, just cleanup
...

Honor coding style in panels.c and loss 370LOC

---

libr/core/cmd_open.c
libr/include/r_io.h
test/db/formats/pe/sectiondata
test/db/io/om

This makes om. output consistent with om

Update cmd_open_map() output format for current map

---

libr/core/cmd_open.c
test/db/json/json3

Very simple change, just borrowed the existing json output from map_list(). @condret says no tests needed for this one, so it should be ready to merge immediately after the om. update.

Add om.j command

---

libr/include/r_io.h
libr/io/io_cache.c

Minor cleanup and fix uninitialized PJ usage warning in io_cache.c

---

libr/main/rafind2.c

Remove globals from rafind2

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/PULL_REQUEST_TEMPLATE.md

Simplify github issue/pr templates

---

.github/workflows/tcc.yml

**Checklist**
There lines were necessary only for debugging the build in the pull request, see https://github.com/radareorg/radare2/pull/17295#issuecomment-741531892

Remove forgotten debugging lines

---

test/README.md

This pr states (hopefully complete) requirements for r2pipe tests.
**Test plan**
Eyeball the changes and see whether they are complete and explain the requirements properly.
...

Add requirements for r2pipe tests

---

libr/asm/arch/arm/armass64.c
test/db/asm/arm_64

Fix #15264 - Implement AND and BIC instructions in the ARM64 assembler ##asm

---

libr/core/cmd_quit.c

Fix return code when using q! without arguments ##core

---

libr/cons/cons.c
libr/cons/input.c
libr/core/panels.c

Fix double click issue in panels ##visual

---

shlr/Makefile

Do not rebuild everything when running make in the root directory ##build

---

libr/bin/format/elf/elf.c

Handle RELATIVE (todo) and IRELATIVE relocs for relative relocs in ELF for ARM64 ##bin

---

libr/anal/p/anal_x86_cs.c
test/db/esil/x86_32

added cmc to esil

---

test/db/cmd/cmd_project

Fix race condition in project test

---

DEVELOPERS.md

Improve DEVELOPERS.md markdown styling ##doc

---

libr/anal/p/anal_x86_cs.c

Refactor aoj~{} opex for x86-64 to use the PJ api

---

shlr/Makefile
shlr/sdb/Makefile
shlr/sdb/src/json.c

Update capstone and SDB

---

libr/cons/pal.c
test/db/cmd/cmd_ec

Slightly more readable, blue is too dark in some setups

Use CYAN in the single line edges in the graph

---

libr/core/cmd.c

**Checklist**
**Before**
**After**

Fix #18006 - @v: doesnt wasnt reverting the origfd properly ##shell

---

libr/anal/p/anal_ppc_cs.c

Add missing =SN for ppc64 ##anal

---

libr/core/cbin.c
libr/core/cconfig.c
test/db/cmd/cmd_pdc

before
after
**Test plan**
...
...

Set realname on all bin strings for better asm.flags.real when bin.str.real is set ##disasm

---

test/db/archos/linux-x64/dbg_dL
test/db/archos/linux-x64/dbg_dmi
test/db/archos/linux-x64/dbg_io
test/db/archos/linux-x64/dbg_oo
test/db/archos/linux-x64/dbg_step

Fix #17997 - Do not use system binary for testing the debugger

---

libr/core/cbin.c

Do not call filterQuoteShell after r_name_filter

---

libr/core/cconfig.c
libr/core/cmd_print.c
libr/core/core.c
libr/include/r_core.h
libr/include/r_util/r_print.h
libr/util/print.c

**Checklist**
fix the first point of this comment: https://github.com/radareorg/radare2/pull/18028

Move rcharset from core to rprint

---

libr/anal/vtable.c
test/db/cmd/cmd_av

Use pj in vtable ##refactor

---

libr/anal/p/anal_riscv.c
test/db/esil/riscv_64

**Checklist**
- Update register analysis for argument, syscall and return registers
- Update ESIL for shift instruction for RISC-V 64-bit

RISC-V 64-bit ESIL for shift instructions ##esil

---

libr/cons/dietline.c

Do not glitch the prompt when using scr.color=0 ##cons

---

libr/core/cconfig.c
libr/core/panels.c
libr/core/visual.c
libr/include/r_cons.h

Initial implementation of scr.cursor for keyboard accessibility in visual and panels ##visual

---

libr/anal/p/anal_x86_cs.c
libr/core/agraph.c
libr/core/cbin.c
libr/core/cfile.c
libr/core/cmd.c
libr/core/cmd_api.c
libr/core/cmd_eval.c
libr/core/cmd_open.c
libr/core/cplugin.c
libr/core/linux_heap_glibc.c
libr/core/project.c
libr/debug/debug.c
libr/include/r_cmd.h
libr/main/radare2.c

**Checklist**
Build with asan and try:
```
r2 -v
r2 -qcq -
r2 -d 0
```

Fix several address sanitize issues, from uaf to memory leaks

---

libr/bin/meson.build
libr/bin/pdb/pdb_downloader.c
libr/core/cmd_info.c
libr/main/rabin2.c
test/db/formats/pdb

Use pj in pdb_downloader ##refactor

---

README.md
sys/release-notes.sh

Improve the release-notes script

---

libr/core/canal.c
test/db/cmd/cmd_ag
test/db/cmd/cmd_agC

**Checklist**
db/json/json1 already contains `agcj`.

Use pj in `agcj` ##refactor

---

codecov.yml

**Checklist**
https://codecov.io/gh/radareorg/radare2 here test/unit is wrongly included.
https://docs.codecov.io/docs/ignoring-paths I don't know whether it works, just test it.
Update: Ok it works https://codecov.io/gh/radareorg/radare2/tree/ce2bed3173a45cdd728fa58c04e87dbb1470bd9b.

Codecov ignore test dir

---

libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_m68k_cs.c
libr/anal/p/anal_mips_cs.c
libr/anal/p/anal_ppc_cs.c
libr/anal/p/anal_riscv_cs.c
libr/anal/p/anal_sparc_cs.c
libr/anal/p/anal_sysz.c
libr/anal/p/anal_tms320c64x.c
libr/anal/p/anal_x86_cs.c
libr/anal/p/anal_xcore_cs.c
libr/include/r_util/pj.h
test/db/anal/ppc
test/db/anal/sysz

**Checklist**
Thanks @Lazula . I fixed some small bugs, and refactored a bit (see the 3rd commit).
According to https://codecov.io/gh/radareorg/radare2/tree/master/libr/anal/p, only sysz is completely not tested, so I added a test.

Fix ppc opex & use pj in RAnal plugins ##refactor

---

libr/anal/p/anal_riscv.c
libr/asm/arch/riscv/riscv-opc.c
test/db/esil/riscv_64

**Checklist**
. Update each sign extension operation with new ESIL operators.
. Corrected **subw** instruction.

Update RISC-V ESIL with sign extention operator

---

DEVELOPERS.md
libr/anal/dwarf_process.c
libr/anal/esil_dfg.c
libr/anal/p/anal_chip8.c
libr/anal/rtti_itanium.c
libr/asm/arch/arc/gnu/arc-dis.c
libr/asm/arch/arc/gnu/arcompact-dis.c
libr/asm/arch/arm/gnu/arm-dis.c
libr/asm/p/asm_chip8.c
libr/bin/format/pyc/marshal.c
libr/bin/pdb/pdb.c
libr/cons/dietline.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_type.c

**Checklist**
Update DEVELOPERS.md code style section and refactor switch-cases across all code base.

 Move breaks inside switch-case scopes ##refactor

---

libr/core/project.c

**Checklist**
I tried to check if I renamed all camel case variables properly but you should propbaly double check weather or not I gave a variable a stupid name. I used the macros IS_UPPER and IS_LOWER in is_valid_project_name()
I made he paramter of remove_notes_file() and remove_rop_directory() constant.
The function r_core_project_save() now uses r_retrun_val_if_fail ().

#projects #refactor project.c: Changed Camel To Snake Case And Used Macros In is_valid_project_name()

---

libr/anal/block.c
libr/bin/format/le/le.c
libr/bin/p/bin_dex.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_coredump.h
libr/debug/p/native/linux/linux_debug.c

**Checklist**
#17898 
Mainly 32-bit pointer and ut64 conversion.
See what CI says.

Fix some arm32 warnings

---

libr/core/cmd_anal.c

**Checklist**
Before adding test, it must be determined whether pj_ki should also apply encoding.

Enable encoding in afbj

---

libr/asm/arch/i4004/i4004dis.c
libr/asm/p/asm_i4004.c
test/db/asm/arm_16
test/db/asm/i4004
test/db/tools/rasm2

Implement i4004 assembler ##asm

---

DEVELOPERS.md

**Checklist**
DEVELOPERS.md: Reword about r_return_* conditions, and stop confusing functions with macros.
---
I kind of lost myself among those commas, while trying to parse huge compound sentence, separated by homogeneously ranked punctuations, despite logically forming a hierarchy, which... dammit, you get the idea.

DEVELOPERS.md: Reword about r_return_* conditions ##doc

---

libr/asm/arch/arm/winedbg/be_arm.c

Add missing license of be_arm.c

---

libr/config/callback.c
libr/config/config.c
libr/cons/cons.c
libr/core/cconfig.c
libr/core/cmd_debug.c
libr/core/cmd_open.c
libr/core/rtr.c
libr/main/rahash2.c
shlr/winkd/iob_net.c
test/db/tools/rahash2

Import last random rizin fixes

---

libr/anal/block.c

Use the Set API instead of hashtable in anal.block.automerge

---

libr/bp/bp.c
test/db/archos/linux-x64/dbg_bps

Use pj in bp.c & add test ##refactor 

---

libr/main/radiff2.c

Diff stuff

---

libr/core/cbin.c
libr/core/cmd_info.c
test/db/cmd/cmd_i
test/db/cmd/cmd_open
test/db/formats/pe/versioninfo
test/db/json/json3
test/db/tools/rabin2

Use pj in cbin.c ##refactor

---

libr/cons/cons.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/core.c
libr/core/project.c
libr/include/r_cons.h
libr/util/hex.c

Initial implementation of r_cons_eprintf ##cons

---

libr/core/cconfig.c
test/db/anal/x86_64
test/db/cmd/cmd_project

Automatically set prj.git if `git` is found in PATH ##projects

---

libr/anal/bb.c
libr/core/cmd_anal.c
libr/include/r_anal.h
test/db/cmd/cmd_afb
test/db/json/json1

`abj` used to be an alias to `afbj`, but now it returns information (in JSON) for only one basic block.
I'm not sure what is the difference between  the properties `addr` and `opaddr` of a basic block, and I did not find documentation about it. Still, I think that the `opaddr`  of a block might be incorrect sometimes, so hit me up if you have information. 
**Test plan**
...
Closes #17039

Fix #17039 - abj output ##json

---

libr/bin/bfile.c
libr/core/agraph.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd_debug.c
libr/core/cmd_info.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/include/r_bin.h
libr/include/r_core.h
test/unit/test_bin.c

Fix #18136 - Remove RBin.is_debugger and use cfg.debug

---

libr/anal/function.c
libr/anal/var.c

Fix asan st overflow ##asan

---

libr/cons/cons.c
libr/cons/line.c
libr/io/io_cache.c
test/unit/test_anal_block.c
test/unit/test_io.c

Fix memleak in test_anal_block & test_io

---

libr/bin/bfile.c
libr/core/agraph.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd_debug.c
libr/core/cmd_info.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/include/r_bin.h
libr/include/r_core.h
test/unit/test_bin.c

lol totally forgot to push this branch xD
**Checklist**

No bin dbg

---

libr/anal/anal.c
libr/config/config.c
libr/core/Makefile
libr/core/canal.c
libr/core/cconfig.c
libr/core/cfile.c
libr/core/cmd.c
libr/core/cmd_open.c
libr/core/cmd_project.c
libr/core/core.c
libr/core/cproject.c
libr/core/meson.build
libr/core/project.c
libr/include/r_core.h
libr/include/r_util/r_file.h
libr/main/radare2.c
libr/util/file.c
libr/util/sys.c
libr/util/syscmd.c
test/db/anal/x86_64
test/db/cmd/cmd_i
test/db/cmd/cmd_print
test/db/cmd/cmd_project
test/db/tools/r2

WIP: Prj workout

---

libr/debug/dsession.c
test/unit/test_str.c

Fix memleak in test_str & test_debug_session

---

libr/core/canal.c
libr/core/cmd_anal.c
libr/core/cmd_magic.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/include/r_core.h
test/db/cmd/cmd_rop
test/db/cmd/cmd_search
test/db/cmd/cmd_search_hit

Use pj in cmd_search.c##refactor

---

test/unit/test_dwarf.c
test/unit/test_skyline.c

Fix memleak in test_dwarf & test_skyline

---

libr/anal/cc.c
libr/bin/format/elf/elf.c
libr/bin/format/pe/pe.c
libr/core/cbin.c
libr/core/cio.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_type.c
libr/core/hack.c
libr/include/r_anal.h
test/db/cmd/cmd_afcl
test/db/cmd/cmd_ara
test/db/cmd/cmd_tcc

Fuzz fixes

---

libr/include/r_util/r_buf.h
libr/util/buf_sparse.c

Fix s390x test_buf

---

libr/core/canal.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/debug/dreg.c
libr/include/r_core.h
libr/include/r_debug.h
test/db/formats/mach0/swift
test/db/json/json1

Use pj in cmd_anal.c ##refactor

---

libr/core/canal.c
libr/core/cbin.c
libr/core/cconfig.c
libr/core/cfile.c
libr/core/cio.c
libr/core/cmd.c
libr/core/cmd_debug.c
libr/core/cmd_info.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/core/cmd_write.c
libr/core/core.c
libr/core/p/core_java.c
libr/core/rtr.c
libr/core/rtr_http.c
libr/core/visual.c
libr/core/yank.c
libr/include/r_core.h
libr/main/rabin2.c
libr/main/radare2.c

Remove core.file ##refactor

---

Makefile
libr/debug/p/native/linux/linux_debug.c

Termux patches

---

libr/core/cbin.c
libr/core/cfile.c
libr/core/cmd_open.c
libr/core/core.c
libr/include/r_core.h
libr/main/radare2.c
libr/main/radiff2.c
libr/main/rasign2.c
test/db/cmd/cmd_open
test/db/cmd/cmd_project
test/db/json/json3

Kill rcorefile

---

libr/reg/rvalue.c

Fix s390x test_reg

---

binr/r2r/r2r.c
libr/core/linux_heap_glibc.c
libr/debug/dmap.c
libr/util/regex/regcomp.c
test/db/json/json2

Use pj in `dmj`, `dmhj` & fix regex r2r ##refactor

---

libr/anal/p/anal_arm_cs.c
test/db/esil/arm_32

**Checklist**
Support ldmda, ldmdb, ldmib, stmda, stmdb, stmib.

Support arm32 esil stmib/ldmib ##esil

---

libr/core/canal.c
libr/core/cmd_type.c
libr/core/project.c
test/db/cmd/cmd_tcc

Prj tcc fix

---

libr/core/cconfig.c
libr/core/project.c

Remove the prj.simple option ##projects

---

libr/bin/format/pe/pe.c
test/db/formats/pe/delayimports

Fix PE Delay Imports for multiple delayed DLLs ##rizin

---

libr/asm/arch/arm/armass64.c
test/db/asm/arm_64

**Checklist**
Broken tests are because capstone doesn't follow the rule of alias. Need to check whether they are fixed by the latest.

Fix arm64 movk, movn, movz

---

.github/workflows/ci.yml
.github/workflows/codeql-analysis.yml
.github/workflows/tcc.yml
libr/bin/format/mach0/mach0.c
libr/bin/format/pe/pe.c
libr/bin/format/pyc/marshal.c
libr/bp/bp.c
libr/cons/grep.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/core/linux_heap_glibc.c
libr/debug/dmap.c
libr/util/udiff.c
shlr/sdb/src/sdb.c
sys/debian.sh

Fix some stuff in the CI

---

.github/workflows/ci.yml

Fix macos r2pipe

---

libr/anal/esil_dfg.c
libr/bin/format/mach0/mach0.c
libr/core/cmd_anal.c

Fix aof and tcc db/formats/mach0/mach0

---

.github/workflows/ci.yml
sys/sanitize.sh

Dont detect leaks in the asan job and install r2pipe in brew ##ci

---

binr/r2r/run.c
libr/asm/arch/arm/armass64.c

Fix memleak in db/asm/arm_64

---

libr/core/casm.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_write.c

Fix memleak in db/esil/arm_16

---

libr/anal/esil.c
libr/anal/fcn.c
libr/asm/arch/msp430/msp430_disas.c
libr/cons/pal.c
libr/core/agraph.c
libr/core/core.c
libr/core/vmenus.c
libr/debug/p/native/linux/linux_coredump.c
libr/fs/shell.c

Remove strncat usage

---

libr/core/cmd_debug.c

Use pj in `dbtj` ##refactor

---

libr/hash/md4.c
libr/main/rahash2.c
test/db/tools/rahash2

**Checklist**
Additionally fix a memleak and signed left shift overflow.

Use pj in rahash2 ##refactor

---

libr/anal/meta.c
libr/bin/bin.c
libr/config/config.c
libr/core/canal.c
libr/core/cbin.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/core/cmd_eval.c
libr/core/cmd_flag.c
libr/core/cmd_meta.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/project.c
libr/core/windows_heap.c
libr/debug/p/debug_native.c
libr/debug/p/native/windows/windows_message.c
libr/debug/trace.c
libr/include/r_anal.h
libr/include/r_core.h
libr/include/r_util/r_str.h
libr/include/r_util/r_table.h
libr/util/str.c
libr/util/table.c
test/unit/test_table.c

Implement RTable:sql and add RTable.name ##core

---

libr/anal/p/anal_x86_cs.c

fix x86-cs rep/repe/repne esil expressions ##esil ##anal

---

.github/workflows/ci.yml
libr/config/config.c
libr/core/cconfig.c
libr/include/r_config.h
libr/include/r_list.h
libr/include/r_syscall.h
libr/util/list.c

Stabilize the RConfig API a litte bit more

---

libr/anal/p/anal_x86_cs.c

Fix x86_cs cmpbs esil ##anal ##esil

---

libr/core/core.c

**Checklist**
fixes a crash in https://github.com/radareorg/radare2-rlang/pull/24/files

Fix crash in radare2-rlang

---

libr/core/cmd_log.c
libr/core/cmd_print.c
libr/include/r_util/pj.h
libr/util/pj.c
test/db/json/json3

Use pj in cmd_log and cmd_print ##refactor

---

.github/workflows/ci.yml
Makefile
libr/util/d/Makefile

Add CI test to ensure symlink reinstalls work

---

libr/anal/esil_dfg.c
libr/core/panels.c

Some bugs in esil_dfg.c

---

libr/bin/demangle.c

Dont demangle with libs unless requested ##bin

---

libr/core/cmd_debug.c
libr/debug/dsignal.c
libr/debug/plugin.c
libr/include/r_debug.h
libr/util/pj.c
test/db/json/json2

**Checklist**
Not perfect. There is still `r_cons_strcat ("[");` and manually printed comma, because the callback is not easy to deal with.

Use pj in debug ##refactor

---

dist/plugins-cfg/plugins.android.cfg
dist/plugins-cfg/plugins.bin.cfg
dist/plugins-cfg/plugins.def.cfg
dist/plugins-cfg/plugins.emscripten.cfg
dist/plugins-cfg/plugins.ios-store.cfg
dist/plugins-cfg/plugins.ios.cfg
dist/plugins-cfg/plugins.nogpl.cfg
dist/plugins-cfg/plugins.static.cfg
dist/plugins-cfg/plugins.static.nogpl.cfg
dist/plugins-cfg/plugins.tiny.cfg
libr/anal/Makefile
libr/anal/anal.c
libr/anal/meson.build
libr/anal/p/dummy.mk
libr/anal/p/esil_dummy.c
libr/config.h.in
libr/core/cmd_anal.c
libr/core/cmd_log.c
libr/core/libs.c
libr/include/r_anal.h
libr/include/r_core.h
libr/include/r_lib.h
libr/meson.build
meson.build

Add support for RAnal.ESIL plugins ##esil

---

libr/anal/p/anal_java.c
libr/anal/p/anal_wasm.c
libr/bin/format/wasm/wasm.c
libr/bin/format/wasm/wasm.h
libr/bin/p/bin_wasm.c
libr/parse/p/parse_wasm_pseudo.c

WIP: Fix HUGE bottleneck in the WebAssembly pseudo disassembler and analyzer ##disasm

---

libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_riscv_cs.c
libr/asm/p/asm_riscv_cs.c

Fix build for capstone5 ##build

---

libr/bin/format/wasm/wasm.c
libr/core/cmd_anal.c

Fix #18274 - Fix crash in r2 *.wasm ##bin

---

libr/include/r_diff.h
libr/main/radiff2.c
libr/util/udiff.c
man/radiff2.1
test/unit/test_diff.c

MODE_DIST (-s) is the same as MODE_DIST_LENVENSTEIN (-ss) but much slower.
Drop it. Make MODE_DIST_MYERS (-sss, faster than MODE_DIST_LENVENSTEIN) take its place (-s).
The original comment was incorrect (-s is not Eugene W. Myer's
algorithm). It is correct now.
...
**Test plan**
...
...

radiff2: drop MODE_DIST

---

libr/anal/p/anal_x86_cs.c

Some memory access sanitization for anal_x86.cs ##emu

---

libr/anal/anal.c
libr/bin/mangling/microsoft_demangle.c
libr/core/cmd_eval.c
libr/core/core.c
libr/core/vmenus.c
libr/include/r_core.h
libr/main/rabin2.c
libr/util/str.c

Fix memleak in db/formats/mangling/mangling

---

libr/anal/p/anal_arm_cs.c
libr/core/cfile.c
libr/core/disasm.c
libr/socket/socket.c
shlr/gdb/src/gdbclient/xml.c

Fix some of the last coverities related to UAF and OOBREAD

---

libr/cons/dietline.c
libr/include/r_cons.h

Implement history filtering for dietline ##cons

---

.github/workflows/ci.yml
sys/android-ndk-install.sh

Fixes for the android-ndk-installer script and the android-arm64 CI job

---

doc/esil.md

Fix wrong documentation of rep cmpsb esil expression in esil.md

---

libr/anal/p/anal_riscv.c
libr/anal/var.c
libr/asm/arch/8051/8051_ass.c
libr/asm/arch/arm/armass64.c
libr/asm/asm.c
libr/asm/p/asm_i4004.c
libr/asm/p/asm_x86_nz.c
libr/bin/mangling/microsoft_demangle.c
libr/bin/pdb/pdb_downloader.c
libr/cons/cons.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/core.c
libr/core/disasm.c
libr/core/project.c
libr/core/visual.c
libr/lang/p/spp_r2.inc
libr/main/rax2.c
libr/search/keyword.c
libr/util/print.c
libr/util/unum.c
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/responses.c
shlr/gdb/src/gdbclient/xml.c
shlr/gdb/src/gdbserver/core.c
shlr/gdb/src/utils.c
shlr/mpc/mpc.c
shlr/sdb/src/query.c

Cast char to unsigned char for standard reasons and security purposes.
**Checklist**
Fixes build issues on NetBSD.

Avoid array subscript type issues

---

libr/bin/p/bin_mach0.c

Fix iCj for mach0 ##bin

---

libr/include/r_io.h

**Checklist**
Remove stupid things/Clean up

Remove dead function signatures ##IO

---

.github/workflows/ci.yml

Add Windows ZIP in the CI

---

.github/workflows/ci.yml
sys/source_bat.bash

Introduce w32 and w64 builds

---

.github/workflows/tcc.yml
binr/r2r/load.c
binr/r2r/r2r.c
test/db/archos/linux-x64/dbg_maps
test/db/archos/linux-x64/dbg_px0
test/db/archos/linux-x64/dbg_step_back

Fix the broken debugger tests after last gha update

---

libr/core/cmd_print.c
test/db/cmd/cmd_help

Add print, println, and placeholder for printf and printfln ##cons

---

libr/core/cmd_help.c
libr/core/visual.c

Fix #18316 - ?0 and ?1 were a bad idea, move to ?t

---

Makefile
binr/r2r/load.c
libr/main/radare2.c
test/Makefile

Fix the archos regression in the CI

---

libr/anal/fcn.c
libr/core/canal.c

Optimize af

---

libr/config/config.c
libr/config/hold.c
libr/core/agraph.c
libr/core/anal_objc.c
libr/core/anal_tp.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/core/panels.c
libr/core/pseudo.c
libr/core/visual.c
libr/include/r_config.h

Config bool

---

libr/bin/p/bin_dyldcache.c

import commit from rizin "Replace HtPP with more suitable types in bin_dyldcache.c (#518)"

from rizin: Replace HtPP with more suitable types in bin_dyldcache.c (#518)

---

libr/bin/format/mach0/mach0.c

import commit from rizin "Fix dead nested assignment libr/bin/format/mach0/mach0.c"

from rizin: Fix dead nested assignment libr/bin/format/mach0/mach0.c

---

libr/anal/fcn.c
libr/core/cconfig.c
libr/core/cmd_anal.c
test/db/cmd/cmd_af

Honor anal.depth in a more consistent way ##anal

---

.github/workflows/ci.yml
libr/anal/p/anal_arm_cs.c
libr/bin/p/bin_dyldcache.c
libr/include/r_cons.h
libr/util/big-ssl.c
libr/util/print.c
libr/util/table.c

Dist for macOS

---

test/Makefile
test/db/asm/x86_32
test/db/extras/asm/x86.ks_32
test/db/extras/asm/x86.ks_64

**Checklist**
- x86 32-bit tests merge duplicate tests and merge test lines.
- Keystone test fix

x86 test cleanning and keystone test fix

---

.github/workflows/ci.yml
binr/r2r/r2r.c
libr/cons/cutf8.c
libr/core/agraph.c
libr/core/cmd_anal.c
libr/include/r_cons.h
libr/util/print.c
libr/util/table.c
test/db/asm/x86_32

Add 32bit Debian packaging

---

.github/workflows/ci.yml
binr/blob/Makefile
binr/blob/meson.build
binr/blob/r2blob.c
binr/r2r/Makefile
binr/rules.mk
libr/util/charset.c
sys/static.sh

Fix static again

---

libr/fs/p/fs_posix.c
libr/fs/shell.c

Fix fs.posix.cat and use r_sys_dir instead of reimplement (-48LOC) ##fs

---

libr/util/charset.c

**Checklist**
Fix the bug that attempt to write the last char.
Does not fix the bug that write 2 times multiple charsets.

Fix bug to write the last chars

---

libr/fs/shell.c

**Checklist**
This aims to fix a segfault in `ms` shell. Just hitting enter in the shell will cause a segfault. This is because `shell->readline ()` returns a non-null pointer, pointing at an empty string in non-writable memory. Then `r_str_trim ((char *)ptr)` would cause  a `memmove(ptr, ptr, 1)` resulting in a segfault. This update makes it so the returned `ptr` buffer is never written to. It also simplifies the code a bit (imho) and removes a memory leak.

Fix segfault in ms with blank line

---

libr/meson.build
meson_options.txt
shlr/meson.build

Add meson -Dplugins=a,b,c to build only the specified plugins ##build

---

autogen.sh
meson.build

Remove meson version hacks

---

libr/core/cconfig.c
libr/core/cmd.c

Add scr.loopnl to add a newline on all the @@ loops ##shell

---

libr/bin/p/bin_elf.inc
libr/bin/p/bin_mach0.c
test/db/cmd/cmd_i
test/db/formats/elf/elf-relarm

Fix warning message when loading files with relocs ##bin

---

libr/core/cmd_anal.c

New command: aaw, flag all words pointing to known flags ##anal

---

libr/core/cmd_print.c
test/db/cmd/cmd_pi

Add pi+ and pi- commands as aliases for 'pi +' and 'pi -'

---

libr/anal/esil.c
libr/anal/esil_plugin.c
libr/anal/esil_stats.c
libr/anal/esil_trace.c
libr/anal/p/anal_avr.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/debug/desil.c
libr/include/r_anal.h
libr/include/r_debug.h

Fix some asserts and nullderef spotted on arm64 ##esil

---

libr/io/io_map.c

Fix infinite loop in r_io_map_next_available ##io

---

libr/core/cbin.c
libr/core/cconfig.c
libr/core/disasm.c

Enable bin.cache by default ##bin

---

libr/cons/canvas_line.c
libr/core/agraph.c
libr/core/cmd_anal.c
libr/core/linux_heap_glibc.c
libr/include/r_agraph.h
libr/include/r_cons.h

Initial implementation of graph edge highlighting ##visual

---

libr/core/agraph.c
libr/core/cmd_anal.c
test/db/cmd/cmd_graph

Add support for highlighted edges in graphviz ##graph

---

binr/r2pm/r2pm

Fix #18391 - Show help in r2pm even before initializing the db ##tools

---

sys/user.sh

Fix #18360 - Absolutize the relative --install-path in sys/user.sh

---

libr/core/agraph.c
libr/core/canal.c
libr/core/cmd_anal.c
test/db/cmd/cmd_graph

Fix issue when highlighting edges on low addresses + test

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc
test/db/formats/elf/elf-relro

Cleanup the ELF using size_t and ut64.max instead of 0 ##bin

---

libr/core/cmd_open.c

Implement omd command, as a simplified version of om ##io

---

libr/anal/p/anal_arm_cs.c

Fix SN register value for linux-arm64 ##anal

---

libr/include/r_util/r_file.h
libr/util/file.c
libr/util/sandbox.c

Inspired by https://github.com/termux/termux-packages/blob/master/packages/radare2/libr-util-sandbox.c.patch
**Checklist**

Add r_file_binsh() and avoid hardcoding /bin/sh for Termux ##android

---

libr/core/cmd_meta.c
test/db/cmd/metadata

Cd1 Cd2, Cd4, Cd8 are aliases for Cd<space>[1248] ##anal

---

libr/anal/esil_handler.c
libr/anal/p/esil_dummy.c
libr/include/r_anal.h

Implement some more interrupt/syscall lifecycle functions for esil-plugins ##emu ##api

---

shlr/Makefile
shlr/meson.build

Update capstone5 branch

---

libr/flag/flag.c
libr/flag/zones.c
libr/include/r_flag.h

Remove unused SDB code from flag/zones

---

libr/io/p/io_malloc.c

* Same as oom but without the extra step
**Checklist**

Implement slurp:// uri handler plugin ##io

---

libr/anal/anal.c
libr/anal/function.c
libr/include/r_anal.h

Fix RAnalFunction.free signature

---

binr/r2r/r2r.c

Dont use large stack buffers and fix overflow in r2r

---

libr/core/rtr.c
libr/util/str.c

Fix warnings spotted by gcc 10.2.1

---

libr/include/r_util/r_rbtree.h
libr/util/rbtree.c
test/unit/test_contrbtree.c

Extend r_rbtree api ##util

---

autogen.sh
libr/fs/meson.build
libr/meson.build
meson.build

Add plugins=nogrub option for meson builds

---

binr/radare2/radare2.c
libr/main/radare2.c

r2 -b acts like -e asm.bits, which resulted in anal plug issue

---

libr/core/cmd.c
libr/core/cmd_open.c
libr/core/project.c
libr/include/r_io.h
libr/io/io.c
libr/io/io_map.c

Rename r_io_map_get_for_fd to r_io_map_get_by_fd ##io

---

libr/core/disasm.c

Improve asm.meta=false for 16, 32 and 64 words ##disasm

---

libr/util/table.c

Fix alignment issues in RTable with utf8 fields ##print

---

libr/core/cbin.c
libr/core/cmd_debug.c
libr/core/disasm.c

Workaround the dmi issue by using rabin2 in macOS for now ##debug

---

libr/anal/fcn.c
libr/anal/jmptbl.c
test/db/anal/v850

Add support for jump tables on v850 ##anal

---

libr/include/r_io.h

Fix comment ##io

---

libr/core/cmd_open.c

Sync om and omj output ##cmd

---

libr/anal/p/anal_x86_cs.c
libr/core/cmd_cmp.c

Fix cX command and minor cleanup ##anal

---

libr/core/agraph.c
libr/core/blaze.c
libr/core/canal.c
libr/core/cbin.c
libr/core/cconfig.c
libr/core/cfile.c
libr/core/cio.c
libr/core/cmd_anal.c
libr/core/cmd_info.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/core/core.c
libr/core/disasm.c
libr/core/linux_heap_glibc.c
libr/core/panels.c
libr/core/project.c
libr/core/visual.c

Boolify cfg.debug

---

libr/core/cmd_anal.c
test/db/anal/x86_32

aaef: Add help msg and x86_32 test

---

libr/core/cmd_api.c

Check if Core Plugin implements call before calling (#670)

---

libr/anal/dwarf_process.c

Fix memory leak librz/analysis/dwarf_process.c

---

.github/workflows/tcc.yml
binr/r2r/load.c
binr/r2r/r2r.c

Add R2R_SKIP_ASM env var handling in r2r ##test

---

libr/include/r_vector.h
libr/util/vector.c
test/unit/test_vector.c

Add r_vector_flush() ##api

---

libr/core/cmd_anal.c
test/db/anal/x86_64

af-*: Remove function flags too ##anal

---

libr/anal/class.c

Co-authored-by: parallels <parallels@vmdevelop.lan>
**Checklist**

Fix duplicate vtable entries after 'aaa' ##anal

---

libr/anal/p/anal_arm_gnu.c
libr/config/config.c
libr/core/cmd_search.c
libr/core/panels.c
libr/io/p/io_r2pipe.c
libr/main/radiff2.c
libr/util/buf.c
libr/util/print.c
libr/util/str.c
shlr/gdb/src/utils.c
shlr/qnx/src/core.c
shlr/tcc/tccgen.c

Random uninitialized variable uses fixups

---

libr/core/canal.c
test/db/anal/x86_32

aae: Realign on fcn start if not in bb ##anal

---

libr/core/cmd_debug.c

Aim to fix the regression in dmiqq

---

libr/anal/p/anal_ppc_cs.c

Fix oobread ppc plugin ##anal

---

libr/bin/p/bin_coff.c
libr/bin/p/bin_mdmp.c

Set free method for relocs on mdmp and coff

---

libr/asm/arch/dcpu16/dcpu16.h
libr/asm/arch/dcpu16/dis.c
libr/asm/p/asm_dcpu16.c

dcpu16/dis.c: Use snprintf/strncpy instead of sprintf/strcpy

---

.github/workflows/ci.yml
libr/debug/snap.c

Dont run debugger tests in ASAN mode and fix crash in snap.c

---

libr/main/radare2.c

Enable io-plugins to set bin.baddr on launch ##io

---

libr/include/r_io.h
libr/io/p/io_mach.c

Close #18257 / Remove RIODescData ##io

---

libr/bin/format/dex/dex.c

Fix asan crash found in r2_hoobr_dex_loadcode ##bin

---

libr/core/anal_objc.c

* Reproducer: r2 -A hang_02.dms
**Checklist**

Fix long time analyzing oob objc data ##bin

---

libr/include/r_util/r_rbtree.h
libr/util/rbtree.c
test/unit/test_contrbtree.c

Implement r_rbtree_cont_last and r_rbtree_cont_node_prev ##util

---

libr/anal/block.c
libr/anal/jmptbl.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_zign.c
libr/fs/p/fs_r2.c

Fixes the following vulnerabilities found by Coverity:
- 1447031 Resource leak
- 1447034 Resource leak
- 1447092 Structurally dead code
- 1447093 Resource leak
- 1448201 Read from pointer after free
- 1448202 Out-of-bounds access
**Checklist**

Fix some vulnerabilities

---

libr/util/rbtree.c

Optimize r_rbtree_cont_{first/last} #18485 ##util

---

libr/util/rbtree.c

Rename d, d2, d3 in rbtree.c to direction ... ##util

---

libr/core/cmd.c
libr/core/cmd_write.c
libr/include/r_util/r_sys.h
libr/util/sys.c

Implement whoami and uid commands ##shell

---

libr/hash/Makefile
libr/hash/hash.c
libr/hash/hcalc.c
libr/hash/meson.build
libr/hash/ssdeep.c
libr/hash/state.c
libr/include/r_hash.h
libr/include/r_util/r_str.h
libr/main/rahash2.c
libr/util/str.c
test/db/tools/rahash2
test/unit/test_ssdeep.c

* Based on https://github.com/glaslos/ssdeep
**Checklist**

Implement ssdeep fuzzy hashing algorithm ##hash

---

libr/bin/format/dex/dex.c

Fix asan crash in DEX with big negative type sections

---

libr/util/rbtree.c

Rename dep in rbtree.c to depth ##util

---

libr/io/p/io_qnx.c
libr/meson.build
meson_options.txt

Meson nogpl

---

libr/core/cmd_anal.c

Simplify and correct `an` fix

---

libr/cons/Makefile
libr/cons/meson.build
libr/cons/pixel.c
libr/core/agraph.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/include/r_cons.h
libr/include/r_core.h
libr/include/r_util/r_print.h
libr/include/r_util/r_str.h
libr/util/print.c
libr/util/str.c

Add p-- for graphing oneliner with the current block byte values

---

libr/core/pseudo.c
test/db/cmd/cmd_pdc

Improved pdc, added pdco and pdcj, print orphan nodes ##print

---

libr/bin/format/mach0/mach0.c
libr/bin/format/objc/mach0_classes.c
libr/bin/format/xnu/r_cf_dict.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_mach0.c
libr/bin/p/bin_xnu_kernelcache.c

**Checklist**
Attempt to fix some of the Mach-O related critical coverity issues.

Fix Mach-O related coverity issues ##bin

---

libr/anal/sign.c
libr/asm/arch/wasm/wasm.c
libr/core/canal.c
libr/core/cmd.c
libr/core/cmd_help.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/rtr.c

**Checklist**
Fix 1380409 Resource leak
Fix 1355077 Resource leak
Fix 1355075 Resource leak
Fix 1408978 Resource leak
Fix 1408693 Resource leak
Fix 1408947 Resource leak
Fix 1355076 Resource leak
Fix 1259928 Resource leak
Fix 1134937 Resource leak
Fix 1134819 Resource leak
Fix 1430478 Out-of-bounds read
Fix 1408737 Out-of-bounds write

Fix coverity vulnerabilities 2

---

libr/anal/meta.c

Fix UB in RMeta.get_size()

---

libr/bin/p/bin_xnu_kernelcache.c
libr/core/cmd_anal.c
libr/core/pseudo.c
libr/debug/debug.c
libr/socket/run.c
libr/socket/socket_http.c
shlr/winkd/iob_net.c

Fix last covs I got by mail

---

libr/anal/dwarf_process.c
libr/core/cmd_meta.c
test/db/cmd/cmd_meta
test/db/cmd/dwarf
test/db/formats/mach0/coresymbolication

Implement CLj command and improve CL output ##dwarf

---

libr/asm/p/asm_ppc_gnu.c

Honor asm.cpu for asm.arch=ppc.gnu ##disasm

---

libr/asm/arch/arc/gnu/arc.h
libr/asm/arch/arm/armass.c
libr/asm/arch/i8080/i8080dis.c
libr/asm/arch/include/opcode/hppa.h
libr/asm/arch/sparc/gnu/sparc-dis.c
libr/asm/arch/tms320/c55x_plus/c55plus_decode.c
libr/asm/arch/tms320/c55x_plus/decode.h
libr/asm/arch/z80/z80_tab.h
libr/cons/canvas_line.c
libr/parse/p/parse_6502_pseudo.c
libr/parse/p/parse_arm_pseudo.c
libr/parse/p/parse_att2intel.c
libr/parse/p/parse_avr_pseudo.c
libr/parse/p/parse_chip8_pseudo.c
libr/parse/p/parse_dalvik_pseudo.c
libr/parse/p/parse_m68k_pseudo.c
libr/parse/p/parse_mips_pseudo.c
libr/parse/p/parse_ppc_pseudo.c
libr/parse/p/parse_riscv_pseudo.c
libr/parse/p/parse_sh_pseudo.c
libr/parse/p/parse_tms320_pseudo.c
libr/parse/p/parse_v850_pseudo.c
libr/parse/p/parse_x86_pseudo.c
libr/parse/p/parse_z80_pseudo.c
libr/util/regex/cclass.h
libr/util/regex/cname.h
libr/util/regex/regcomp.c
shlr/gdb/src/gdbclient/xml.c
shlr/grub/fs/iso9660.c
shlr/grub/fs/xfs.c

Fix incorrect use of non-const strings and fiz zousans of warnings

---

libr/bin/format/mach0/mach0.c

**Checklist**
Fix the last High coverity issue in Mach-O which is not a false positive. Slipped through previous passes.

Fix coverity issue in Mach-O format

---

libr/bin/format/objc/mach0_classes.c

Fix large loading times when parsing encrypted/fuzzed macho ##bin

---

libr/core/casm.c
libr/core/cmd_search.c

Show results after pressing ^C in /ad ##search

---

libr/anal/fcn.c
test/db/anal/v850

Fix jump table analysis issue for r2ghidra.v850

---

libr/util/axml.c

Coverity fixes for Android Binary XML

---

libr/fs/fs.c
libr/fs/meson.build
meson.build

Fix meson build issues related to grub

---

libr/parse/c/tcc.h
libr/parse/c/tccgen.c

Fix tcc warnings

---

libr/cons/cons.c
libr/cons/dietline.c
libr/core/cmd.c
libr/core/cmd_mount.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/yank.c
libr/include/r_cons.h

Rename r_cons_memcat to r_cons_write ##api

---

libr/bin/bin.c
libr/bin/bobj.c
libr/bin/format/ne/ne.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_elf.inc
libr/bin/p/bin_mach0.c
libr/bin/p/bin_mdmp.c
libr/bin/p/bin_nro.c
libr/bin/p/bin_pe.inc
libr/bin/p/bin_wasm.c
libr/include/r_bin.h

Use r_bin_import_free() as <free> cb for imports list (#893) ##bin

---

libr/crypto/p/crypto_serpent_algo.c
libr/crypto/p/crypto_serpent_algo.h
libr/egg/egg_lang.c
libr/egg/rlcc/rlcc.c

Remove some exit() calls in libr ##api

---

libr/anal/p/anal_avr.c

Use =RS 8 for avr ##anal

---

libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_sparc_cs.c
libr/anal/p/anal_sysz.c
libr/anal/p/anal_x86_cs.c
libr/anal/p/anal_xcore_cs.c
libr/include/r_anal.h

Remove duplicate definitions of `esilprintf`

---

libr/bin/p/bin_dyldcache.c

**Checklist**
On all the macOS caches I've tried (x86_64, x86_64h and arm64e) there are no `locsyms`, so now a NULL `locsym` is supported. The dyld cache is rebased properly, and previous behaviour should be unchanged.

Support x86_64 and macOS dyld caches ##bin

---

libr/core/cbin.c
libr/core/cmd_info.c

iVj must print valid json, not empty output

---

libr/bin/format/elf/elf.c
libr/util/sys.c

Parse the symbols from the ELF .gnu_debugdata section ##bin

---

libr/core/cmd.c
libr/include/r_util/r_file.h
libr/util/file.c

**Checklist**
A while ago I wrote this stupid function https://github.com/radareorg/radare2/pull/18526 
of course me being me I fucked up the code and unfortunately the issues went over the reviewer's head so I hopefuly fixed some of the glraing issues in the function. Now the function can be accesed by the cmdline.

Tried to fix certain problems in r_file_dir_recursive and added it to a cmd.c

---

libr/anal/dwarf_process.c
libr/core/agraph.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/core/rtr.c
libr/debug/debug.c
libr/fs/p/fs_posix.c
libr/search/uds.c
libr/socket/socket_http_server.c
libr/util/file.c
shlr/sdb/src/main.c

**Checklist**
Fixes the following issues:
- Fix 1445553 Uninitialized scalar variable
- Fix 1445924 Resource leak
- Fix 1446205 Resource leak
- Fix 1446541 Resource leak
- Fix 1446543 Resource leak
- Fix 1446544 Argument cannot be negative
- Fix 1446545 Resource leak
- Fix 1446672 Resource leak
- Fix 1447033 Resource leak
- Fix 1450830 Resource leak
- Fix 1451978 Use after free
- Fix 1451561 Resource leak
- Fix 1451981 Resource leak in dwarf_process.c

Fix some coverity issues

---

Makefile

Fix empty R2_GITTAP

---

libr/anal/diff.c
libr/core/cmd_zign.c
libr/include/r_list.h
libr/util/list.c

Fix #18260 - Sort bbs before comparing them for diffing code ##diff

---

libr/bin/p/bin_dyldcache.c

**Checklist**
macOS caches have `value_add` set to a non-zero value, and `estimate_slide` wasn't taking it into account resulting in a wrong side estimation.
Kudos to @meme for reporting and help narrowing down.

Honor value_add when estimating dyldcache slide ##bin

---

libr/anal/p/anal_x86_cs.c
test/db/anal/x86_32

**Checklist**
ESIL for pssldq, xorps, pxor, por, pand, pandn, andps, andnps instructions.

ESIL for some SSE and MMX bitwise instructions

---

libr/util/udiff.c

**Checklist**
Just removes some duplicate code. I am not real excited about how it worked out, so feel free to offer suggestions. Or if you want we can just leave the duplicate code.
The matrix loops are tricky enough as it is, I am happy to keep that code mostly duplicated to avoid debugging both `chgs` and `!chgs` conditions. 
I was going to make `zb` rely on this new function, before modifying the code. However, the new Levenshtein function causes `zb` to run much slower, more then 2x slower. I think this is because bytes signatures are at most 500 bytes in size. So all the added extra overhead, like using `lev_get_val` instead of pointers, just slows things down. I might try to speed it up later but for the moment I am sick of debugging Levenshtein :)

Remove duplicate code in levenshte path ##diff

---

libr/anal/codemeta.c
libr/include/r_codemeta.h
libr/include/r_vector.h
test/unit/test_codemeta.c

Use rbtree_cont in codemeta

---

.github/workflows/ci.yml

Use debian stable to build the debian package instead of Ubuntu

---

libr/core/project.c
test/db/cmd/cmd_project

**Checklist**
Before the update the following chars were accepted:  \\ . _ : - [A-Z] now project names are restricted to lower case letters and numbers.

Added stricter rules to is_valid_project_name ##projects

---

libr/core/cbin.c
libr/core/cmd_info.c

Fix warnings in the ihj command

---

libr/anal/codemeta.c

Haven't tried, idk if this works

Codemeta speedup

---

libr/core/agraph.c

F keys in interactive graph forces to refresh the thing

---

libr/util/uleb128.c

Fix #18604 - UB in left shift parsing uleb128

---

configure
configure.acr
libr/core/cconfig.c
libr/include/r_io.h
libr/io/io.c
meson.build
meson_options.txt

Add dbg.wrap for changing want_ptrace at runtime ##debug

---

libr/anal/p/anal_arm_cs.c

Fix out of bounds read in anal.arm64 bug spotted by coverity

---

libr/bin/p/bin_dex.c

Fix OOB read crash in dex parser

---

libr/asm/arch/mcore/mcore.c
libr/util/rbtree.c

Fix a couple of oobreads

---

libr/bin/format/pe/pe.c

Fix oobreads in the PE SEH parser

---

libr/asm/arch/arm/gnu/arm-dis.c

Fix oobread bug in the GNU arm64 disassembler

---

libr/bin/bfile.c
libr/bin/format/dex/dex.c
libr/bin/p/bin_dex.c

Fix some Leaks in Dex

---

libr/anal/codemeta.c

Fix upper boundary check in r_codemeta_in

---

libr/bin/format/elf/elf.c

Fix loading symbols from nested ELF ##bin

---

libr/anal/codemeta.c

Speedup r_codemeta_in on 32-bit platforms

---

libr/core/cconfig.c
libr/include/r_io.h
libr/io/io_cache.c

Do not write nops in the cache ##io

---

libr/core/canal.c
libr/core/cmd_anal.c
test/db/anal/ppc

aflm output is now sorted by offset ##anal

---

libr/core/cbin.c

Speedup dwarf loading when no files are found in disk ##bin

---

libr/core/panels.c

Fix #18624 - Panels layout save menu crash and action

---

libr/core/cconfig.c
libr/core/disasm.c
libr/core/visual.c

Implement asm.hint.imm and integrate it in visual ##disasm

---

libr/core/Makefile
libr/core/cconfig.c
libr/core/meson.build
libr/core/project.c
libr/core/rvc.c
libr/include/rvc.h
test/db/anal/x86_64
test/db/cmd/cmd_project

**Checklist**
This is supposed to be a replacement for git in radare2 (not the actual method used for contributing). Not much has been completed yet. I just wrote the nesessary code for initing (so the data types, branching and initing). This system is supposed to be accumulative meanning that patch files will be stored and every time patches reach a certain limit the base is restored.
directory structure:
.rvc
.rvc/branches
.rvc/branches/new
.rvc/branches/new/commits
.rvc/branches/new/commits/be104552aaef802cf59242763ccec7e99d1d94e07a9db66bfd97d534ef3fd0c8
.rvc/branches/master
.rvc/branches/master/commits
.rvc/branches/master/commits/be104552aaef802cf59242763ccec7e99d1d94e07a9db66bfd97d534ef3fd0c8
.rvc/blobs
.rvc/blobs/e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca49599 …

Radare2 Version Control System

---

libr/core/rvc.c

**Checklist**
Recently I was pointed to some memeory issues with libr/core/rvc.c

Fixed some memeory issues with rvc.c

---

libr/cons/cons.c
libr/cons/cpipe.c
libr/core/cmd_api.c
libr/core/cmd_write.c
test/db/cmd/cmd_print

cc @gogo2464 ill add the tests and fix alias files here

Add guard check for r_cons_write

---

libr/core/anal_objc.c

Fix boundary check in aao to parse more refs ##anal

---

test/db/extras/cmd/yara

**Checklist**
Correct result addresses for yara scan output.

Update yara test with correct address

---

libr/lang/lang.c
libr/lang/p/go.c

Add rlang-golang plugin

---

libr/core/anal_objc.c

Refix the objc parsing boundary check

---

libr/core/cmd_debug.c

Show string version of the stop reason in `di` ##debug

---

libr/cons/dietline.c

Fix double-prompt bug

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h
test/db/cmd/cmd_zignature

**Checklist**
Mostly refactors code. This also makes reporting of found signatures a bit more verbose (showing specific types found). 
A very minor bug was fixed. Before two different search contexts were used. This meant the match count for byte signatures was unique, while graph, refs, offset, etc all shared a second match count. Now all signatures share the same match count. 
Before you would get flags like:
```
0x00400536 37 sign.bytes.sym.print_0
0x00400440 41 sign.graph.sym.print_0
0x00400420 6 sign.graph.sym.print_1
0x00400410 6 sign.graph.sym.print_2
0x0040055b 32 sign.graph.sym.print_3
0x00400536 37 sign.graph.sym.print_4
```
Now you get:
```
0x00400536 37 sign.bytes.sym.print_0
0x00400440 41 sign.graph.sym.print_1
0x00400420 6 sign.graph.sym.print_2
0x00400410 6 …
```

Refactor signature matching ##signatures

---

.github/workflows/ci.yml
binr/rules.mk
config-user.mk.acr
libr/config.mk.tail
libr/rules.mk

Fix --with-rpath

---

libr/asm/Makefile
libr/util/charset.c
libr/util/d/Makefile
shlr/sdb/src/main.c

Use gperf in util/charset

---

shlr/Makefile
shlr/mpc/deps.mk
shlr/mpc/mpc.c
shlr/mpc/mpc.h

Update mpc from git and add the `mpc-sync` target

---

binr/r2r/Makefile
libr/parse/code.c

Dont check further colon separated directories after the file is loaded

---

libr/core/cconfig.c

**Checklist**
prj.vc.type would have been git even if it wasn't installed. This PR changes that

Fixed the vc check

---

test/db/cmd/cmd_search_hit

**Checklist**
Test for `/d` command.

Add test for /d command

---

binr/r2r/r2r.c

Make r2r pull/clone test/bins if not found instead of the Makefile

---

libr/anal/sign.c
test/db/cmd/cmd_zignature

**Checklist**
MergeItem is used to overbite a signature with new information. Previously this
function was leaking and excluded xrefs.

Fix bugs in mergeItem ##signatures

---

libr/core/project.c

Minor project api cleanup

---

libr/anal/sign.c
test/db/cmd/cmd_zignature

**Checklist**
Mostly to make tests more deterministic. A sorted list might also be easier to parse.

Make collision ##signatures more efferent

---

libr/core/cmd.c
libr/core/rtr.c
libr/core/rtr_shell.c
libr/include/r_core.h

* == honors scr.interactive
* Improved help in ==? and =+?

Add ===errmsg to support the new r2pipe side ##r2pipe

---

.github/workflows/coverity-scan.yml
dist/plugins-cfg/plugins.def.cfg
libr/bin/format/wad/wad.h
libr/bin/meson.build
libr/bin/p/bin_wad.c
libr/bin/p/wad.mk
libr/include/r_bin.h

**Checklist**
Bin plugin to parse WAD files and create symbols and flags for each element found.

Add wad parsing

---

libr/util/axml.c

Remove assertion in pFA ##print

---

libr/util/list.c

Optimize r_list_sort()

---

libr/debug/debug.c

Port of the pull request https://github.com/rizinorg/rizin/pull/1149 to radare2
**Checklist**
Same as the one in the pull request

Fix dmha output when reopen in debug mode

---

libr/core/cfile.c
libr/core/cmd_open.c
libr/debug/debug.c
libr/debug/p/debug_native.c

Fix infinite loop in r2 -c 'ood;ood' - ##debug

---

.gitignore
binr/Makefile
binr/blob/Makefile
binr/rvc2/Makefile
binr/rvc2/meson.build
binr/rvc2/rvc2.c
libr/core/rvc.c
libr/include/r_main.h
libr/include/rvc.h
libr/main/Makefile
libr/main/meson.build
libr/main/rvc2.c
man/r2r.1
man/rabin2.1
man/radare2.1
man/radiff2.1
man/rafind2.1
man/ragg2.1
man/rahash2.1
man/rarun2.1
man/rasign2.1
man/rasm2.1
man/rax2.1
man/rvc2.1
meson.build

Add initial rvc2 command ##shell

---

libr/main/rasm2.c

Fix rasm2 -w in termux (honor R_SYS_ARCH) ##asm

---

libr/core/cmd_hash.c

Adding output results to several hashing commands fixing: #18727

---

libr/include/ptrace_wrap.h
libr/include/r_agraph.h
libr/include/r_bind.h
libr/include/r_drx.h
libr/include/r_getopt.h
libr/include/r_heap_jemalloc.h
libr/include/r_main.h
libr/include/r_qrcode.h
libr/include/r_regex.h
libr/include/r_skiplist.h
libr/include/r_skyline.h
libr/include/r_types_base.h
libr/include/r_types_overflow.h
libr/include/r_util/r_alloc.h
libr/include/r_util/r_assert.h
libr/include/r_util/r_intervaltree.h
libr/include/r_util/r_str_util.h
libr/include/r_util/r_time.h
libr/include/r_util/r_tree.h
libr/include/r_util/r_uleb128.h
libr/include/r_util/r_utf16.h
libr/include/r_util/r_utf32.h
libr/include/r_util/r_utf8.h
libr/include/rvc.h
libr/include/sflib/common/sfsocketcall.h
libr/include/sflib/common/sftypes.h
libr/include/sflib/darwin-arm-64/sfsyscall.h

Honor extern "C" in all the include files

---

libr/syscall/Makefile
libr/syscall/d/Makefile
libr/syscall/meson.build
libr/syscall/splugs.c
libr/syscall/syscall.c

Fix #18719 - gperfizy r_syscall

---

libr/core/cmd_print.c

**Checklist**
Adds help strings for pde pdr and pdp

Add help messages for pde pdr pdp

---

dist/plugins-cfg/plugins.def.cfg
dist/plugins-cfg/plugins.static.cfg
dist/plugins-cfg/plugins.static.nogpl.cfg
doc/fortunes.fun
libr/anal/p/anal_arm_cs.c
libr/core/cmd_open.c
libr/include/r_io.h
libr/include/r_socket.h
libr/io/io_memory.c
libr/io/io_memory.h
libr/io/meson.build
libr/io/p/io_socket.c
libr/io/p/socket.mk
libr/socket/socket.c

Implement socket:// plugin, inspired by radare1 ##io

---

libr/anal/p/anal_s390_cs.c
libr/asm/p/asm_s390_gnu.c
test/db/anal/s390

Fix s390.gnu disassembly and add test for 6 byte instructions ##anal

---

libr/bin/bfile.c
libr/core/cbin.c
libr/core/cconfig.c
libr/include/r_util/r_str.h
libr/main/rabin2.c
libr/util/charset.c
libr/util/str.c
test/db/cmd/charset

Fix #18724 - Use RCharset in rabin2 -z ##bin

---

libr/core/disasm.c
test/db/cmd/cmd_pd2
test/db/cmd/metadata

Nometahints

---

dist/plugins-cfg/plugins.android.cfg
dist/plugins-cfg/plugins.def.cfg
dist/plugins-cfg/plugins.ios-store.cfg
dist/plugins-cfg/plugins.ios.cfg
dist/plugins-cfg/plugins.nogpl.cfg
dist/plugins-cfg/plugins.static.cfg
dist/plugins-cfg/plugins.static.nogpl.cfg
dist/plugins-cfg/plugins.tiny.cfg
libr/bin/meson.build
libr/bin/p/bin_off.c
libr/bin/p/off.mk
libr/include/r_bin.h
test/db/anal/s390

Add initial toy IBM S390 Object File Format parser ##bin

---

libr/core/disasm.c
test/db/cmd/print

Fix #16677 - Honor asm.sub.jmp in pd ##disasm

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c
libr/include/r_anal.h
test/db/esil/x86_32

Fix #18736 - Eliminate REPEAT ESIL command ##esil

---

libr/anal/d/Makefile
libr/asm/Makefile
libr/asm/d/Makefile
libr/syscall/d/Makefile
libr/util/d/Makefile
shlr/sdb/src/main.c

Update SDB: Use the thin cgen instead of gperf

---

libr/core/project.c
libr/include/r_core.h
libr/main/radare2.c

**Checklist**
Fix a number of issues with projects specifically: https://github.com/radareorg/radare2/issues/18641

Fix some issues with ##projects

---

libr/anal/jmptbl.c
libr/core/disasm.c
test/db/anal/x86_64

Fix many zero cases

---

libr/asm/arch/arm/armass64.c
shlr/Makefile
shlr/sdb/src/main.c

Update sdb again to fix the missing gperf warning

---

libr/core/cmd_print.c
libr/util/format.c

Fix #18308 - Fix pf parsing issues and write on enums and bitfields ##print

---

libr/core/cmd_print.c

Fix #18309 - Better error messages for the pf command ##print

---

libr/asm/d/meson.build

Simplify some meson

---

libr/core/disasm.c
test/db/cmd/cmd_disassembly
test/db/cmd/cmd_pd
test/db/cmd/cmd_pd_bugs
test/db/cmd/cmd_pde
test/db/cmd/dwarf
test/db/cmd/metadata

Fix #18427 - Sort flags by [sections,formats][other][regs] ##disasm

---

binr/rules.mk
libr/include/r_io.h

**Checklist**
- [] Closing issues: #issue

io: ptrace openbsd build fix proposal

---

shlr/sdb/src/query.c
shlr/sdb/src/sdb.c

jasdfklasjfkld

---

libr/cons/grep.c
test/db/cmd/feat_grep

Fix grep cmd with neg

---

shlr/sdb/src/query.c
shlr/sdb/src/sdb.c

Try bumping sdb back

---

Makefile
global.mk
libr/count.sh
libr/magic/Makefile
libr/magic/d/Makefile
libr/magic/deps.mk

Improve output for make -s

---

libr/bin/format/pe/pe.c

Dont trust the rich

---

libr/core/cmd_anal.c

Improve aaaa log messages and avoid aaef to run in debugger mode ##anal

---

libr/core/vmenus.c
shlr/sdb/src/main.c
shlr/sdb/src/query.c

Fix the last issues spotted by coverity

---

libr/util/list.c

Fix bug in r_list_insert that breaks r_list_sort ##util

---

libr/core/cmd_egg.c
libr/core/cmd_log.c

Add Lg to list egg plugins

---

.github/workflows/ci.yml
binr/r2r/run.c
libr/include/r_types.h
libr/socket/run.c
libr/util/time.c

Switch to ubuntu18, seems like gha is shipping them again

---

libr/core/visual.c

Fix visual debugger after 5206c636f547a8ba6ab5b486e7ba5a256fa86df0

---

libr/include/r_list.h
libr/util/list.c

Add r_list_iter_get_prev (siol eternal) ##util

---

libr/config/config.c

**Checklist**
There were some pointless frees in r_config_set. This PR attempts to remove some of them.

Removed some pointless frees in r_config_set in config.c

---

binr/r2r/run.c

Fix double unlock regression

---

libr/core/cconfig.c
libr/core/rtr_http.c

HTTP Basepath

---

libr/count.sh

Fix count script

---

libr/cons/dietline.c
libr/cons/input.c
libr/core/cmd.c
libr/util/signal.c
libr/util/str.c

Reduce stackframe usage in exchange for the heap for portability

---

libr/asm/arch/arm/armass64.c

…sembler must fail
**Checklist**

Fix #18825 - Invalid/unknown/unsupported instructions on the arm64 assembler must fail

---

dist/macos/build-pkg.sh

Fix macos packaging in the CI

---

libr/debug/debug.c
libr/io/p/io_debug.c
libr/main/radare2.c

**Checklist**
Remove the debugee PID at the start of the launch of radare2. It will permit to make tests easier.

Remove pid start message

---

libr/io/p/io_debug.c

refactor fork_and_ptraceme_for_unix

---

libr/anal/esil.c
libr/anal/esil_cfg.c
libr/core/cmd_print.c
libr/core/esil2c.c

Initial implementation of the pdo esil2c output ##print

---

libr/anal/esil.c
libr/include/r_anal.h

Esil macros

---

libr/anal/esil.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/include/r_core.h
test/db/anal/arm
test/db/anal/arm-esil

Context : https://blog.nviso.eu/2019/08/13/intercepting-traffic-from-android-flutter-applications/

Fix aef to actually find xrefs at least ##anal

---

libr/core/cconfig.c
libr/include/r_util.h
libr/include/r_util/r_file.h
libr/socket/run.c
libr/util/file.c

Honor $SHELL and PATH instead of hardcoded /bin/sh

---

libr/core/cmd_anal.c

Finish the tolowering of anal.noNULL

---

libr/anal/p/anal_vax.c
libr/asm/arch/vax/vax-dis.c
libr/asm/p/asm_vax.c
libr/bin/format/elf/elf.c
test/db/formats/elf/vax

Vaxination

---

libr/parse/p/parse_x86_pseudo.c
libr/parse/parse.c
test/db/anal/x86_64
test/db/cmd/cmd_pdc

Improve x86.parse for asm.pseudo ##disasm

---

libr/core/cmd_anal.c

Add some help and better parsing for the anal hints ##shell

---

.github/workflows/ci.yml
sys/wasi.sh

Build and publish the ZIP with the WASI bins ##build

---

libr/util/thread_cond.c

ThreadCond APIs require windows 2008 or higher

---

libr/cons/grep.c
libr/cons/hud.c
libr/core/cmd.c
libr/core/vmenus.c
libr/include/r_cons.h

* Add new RCons.hud.line(_string) APIs
**Checklist**

Initial implementation of ~.... for hudline prompt ##visual

---

libr/core/cmd_search.c
libr/core/cmd_seek.c
libr/include/r_util/r_mem.h
libr/util/mem.c
test/db/cmd/cmd_seek

Initial implementation of spp, snp, /bp and /pp to find next/prev preludes ##search

---

shlr/sdb/config.mk
shlr/sdb/src/query.c
shlr/sdb/src/text.c
test/db/formats/pe/dep
test/db/formats/pe/no_dep

Update to the latest SDB

---

libr/core/panels.c

Handle 'o' key for options in panels ##visual

---

libr/core/core.c
libr/include/r_core.h
libr/main/radare2.c

Faster ^D (leave r2 without freeing the core) ##shell

---

libr/core/disasm.c
test/db/cmd/cmd_pd_str

Improve invalid address and string parameter issues in emu.str and pd comments ##disasm

---

binr/r2pm/r2pm

r2pm runs init/update without user interaction when needed ##r2pm

---

libr/core/cmd_write.c
test/db/cmd/cmd_w

FIx #18872 - New command 'wan' to write and nop affected instructions  ##assembler

---

libr/core/rvc.c
libr/include/rvc.h

put the rvc and git functionality in one function and add an extra check to rvc functions.

Take advantage of prj.vc.type and merge rvc & git ##projects

---

libr/core/cmd.c
libr/core/cmd_print.c
test/db/cmd/feat_foreach

Implement @@== foreach word iterator operator ##core

---

libr/core/cmd.c
libr/core/cmd_print.c
libr/core/core.c
libr/include/r_core.h

Implement &: for queue commands ##core

---

libr/core/cmd.c
libr/core/rvc.c
libr/include/r_types.h
libr/include/rvc.h

**Checklist**
This PR is supposed to make the rvc add apis abit more elegent and better suitable for directory adding.

Rework the rvc_commit functions ##projects

---

config-user.mk.acr

Improve the DL_LIBS check in config-user

---

libr/core/cmd_zign.c
libr/include/r_util/r_file.h
libr/util/file.c

Simplify r_file_glob name and string allocation logic

---

libr/core/cmd_mount.c
libr/core/rvc.c
libr/include/rvc.h

Rework r_vc_checkout and fix some mem leaks ##projects

---

libr/core/rvc.c
libr/include/rvc.h
libr/main/rvc2.c

rvc add r_vc_find_rp ##projects

---

dist/plugins-cfg/plugins.android.cfg
dist/plugins-cfg/plugins.def.cfg
libr/anal/p/anal_arm_v35.c
libr/anal/p/arm_v35.mk
libr/asm/Makefile
libr/asm/arch/arm/v35arm64/Makefile
libr/asm/arch/arm/v35arm64/deps.mk
libr/asm/p/arm_v35.mk
libr/asm/p/asm_arm_v35.c
libr/include/r_anal.h
libr/include/r_asm.h
shlr/Makefile

Initial import of the arm64-v35 disassembler and analysis plugins ##anal

---

.github/workflows/ci.yml
sys/version.py

Windows CI zip stuff with version

---

libr/asm/arch/xtensa/gnu/xtensa-modules.c
libr/core/agraph.c
libr/core/cbin.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/cmd_seek.c

Fix some issues spotted by msvc

---

libr/anal/fcn.c
libr/core/cmd_anal.c
test/db/cmd/types

Fix afsj, taking signature args instead of fcnargs in json ##anal

---

libr/asm/arch/arm/v35arm64/Makefile
libr/asm/arch/arm/v35arm64/deps.mk

Rebuild v35 disassembler once

---

libr/include/r_util/r_intervaltree.h

Fix undefined behaviour when traversing uninitialized trees

---

dist/plugins-cfg/plugins.nocs.cfg

Use v35 in the nocs builds

---

.github/workflows/ci.yml
sys/version.py

Version the artifacts

---

.github/workflows/ci.yml

More version ci stuff

---

libr/core/visual.c

* Populate a temporary buffer with R_ANAL_ARCHINFO_MAX_OP_SIZE bytes (or 32,
whichever is bigger) and disassemble it, instead of directly passing
core->block and fixed 32 bytes length to r_asm_disassemble.
* Fixes incorrect disassembly in visual mode when the current
instruction is longer than 32 bytes. The corresponding analysis
plugin needs to correctly report R_ANAL_ARCHINFO_MAX_OP_SIZE.
* This shouldn't break any plugins, since they still receive at minimum
the same 32 bytes as before. However, if there are plugins that, for some
reason, ignored the passed length and continued reading the buffer
beyond that, this change will break them. Those plugins should probably be
fixed.
**Checklist**
`r_core_visual_disasm_down` passes `core->block` as the buffer and 32 as length …

Use a temporary buffer for disassembly in r_core_visual_disasm_down

---

libr/cons/dietline.c

Improved reverse-search in command history ##shell

---

libr/cons/dietline.c
libr/core/cconfig.c
libr/core/cmd_quit.c
libr/include/r_cons.h
libr/main/radare2.c

* Introduced in f6f7728cf411a08bf81374aaf301b896c49ff842

Add scr.hist.filter to toggle the filtered history up/down search ##shell

---

libr/core/cmd_anal.c

Fix assert in afco

---

libr/core/cconfig.c
libr/core/rvc.c
libr/include/rvc.h
libr/main/rvc2.c

**Checklist**
r_vc_commit now checks if author is NULL in case it is it sets author to the value of prj.vc.author. prj.vc.author is by default set to the return value of r_sys_whoami().

Use r_sys_whoami as the author name for r_vc_commit ##projects

---

sys/wasi.sh

Honor error codes in wasi CI builds

---

libr/bin/format/le/le.c

Fix #18923 - Fix resource exhaustion bug in LE binary

---

libr/anal/var.c
libr/bin/p/bin_coff.c
libr/core/canal.c
libr/reg/profile.c

Polish some asserts here and there

---

libr/core/rvc.c
libr/main/rvc2.c

**Checklist**
There was a *NULL derf in /libr/main/rvc2.c: ln 107 this PR is supposed to fix it.

Fix *NULL derfrence in /libr/main/rvc2.c

---

libr/anal/anal.c
libr/anal/op.c
libr/asm/asm.c
libr/core/core.c
libr/include/r_anal.h
libr/include/r_asm.h

Use RAnalBind in RAsm to reuse RAnalPlugins to disassemble ##asm

---

libr/main/rasm2.c
man/rasm2.1

Add rasm2 -LL to list anal plugins loaded ##tools

---

libr/core/vmenus.c

Fix #18292 - Clarify the use of Vdn/Vdr and rename VdR to VdX ##visual

---

test/db/archos/linux-x64/cmd_di_onsignals

Fix debugger signal tests

---

.gitignore
binr/Makefile
binr/blob/Makefile
binr/ravc2/Makefile
binr/ravc2/meson.build
binr/ravc2/ravc2.c
libr/include/r_main.h
libr/main/Makefile
libr/main/meson.build
libr/main/ravc2.c
man/radare2.1
man/ravc2.1
meson.build

Rename rvc2 to ravc2 to follow the ra*2 pattern ##tools

---

libr/core/cmd_anal.c
libr/include/r_util/r_name.h
libr/util/name.c
libr/util/str_trim.c
test/db/cmd/cmd_i
test/db/cmd/cmd_pd
test/db/cmd/metadata

* Improve workflow after checking profiler logs
**Checklist**

Improve function analysis times ##anal

---

libr/cons/dietline.c
libr/cons/hud.c

Fix glitches when clicking in the hud ##visual

---

libr/anal/anal.c
libr/core/cconfig.c
libr/include/r_anal.h
libr/reg/profile.c
test/unit/test_esil_dfg_filter.c

Add one more RReg wrapper in RAnal for bindings

---

libr/asm/p/asm_null.c

Use NULL disassembler in the NULL asm plugin

---

libr/bin/bfile.c
libr/bin/format/le/le.c
libr/core/cbin.c
libr/core/cmd_info.c
libr/main/rasm2.c
libr/main/ravc2.c
libr/util/name.c

Fix memleaks spotted by coverity

---

libr/bin/bobj.c
libr/bin/filter.c
libr/include/r_bin.h

Replace SDB with HtPU in RBin.filter_name() ##bin

---

libr/core/cmd_search.c
libr/search/keyword.c
test/db/cmd/cmd_search

Add /cg command to search for GPG artifacts ##search

---

libr/anal/anal.c
libr/anal/pin.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/include/r_anal.h
test/db/cmd/cmd_aes

Bring back pins to esil land ##esil

---

libr/anal/xrefs.c
libr/core/visual.c
libr/include/r_anal.h

Fix #18843 - Implement Vx[+-] to add/delete xrefs ##visual

---

libr/core/cmd_print.c
libr/core/pseudo.c
test/db/anal/x86_32
test/db/anal/x86_64
test/db/cmd/cmd_af
test/db/cmd/cmd_pd2
test/db/cmd/cmd_pdc
test/db/cmd/cmd_pdr
test/db/cmd/write

Improve the pdc output to allow recompilation

---

binr/r2pm/r2pm
libr/asm/arch/arm/v35arm64/Makefile
libr/asm/arch/arm/v35arm64/deps.mk
preconfigure

* Use git clone -q for a quieter experience
**Checklist**

Initial import of `./preconfigure` for packaging purposes

---

dist/plugins-cfg/plugins.def.cfg
libr/bin/p/bin_tic.c
libr/bin/p/tic.mk
libr/include/r_bin.h

Initial support for the TIC-80 Fantasy Computer cartridges ##bin

---

libr/debug/debug.c
libr/include/r_debug.h

Fix null deref and boolify the RDebug.attach() function

---

libr/core/cmd_search.c
test/db/cmd/cmd_search

**Checklist**
Artifacts for v4 encrypted RSA private key. Test file added in https://github.com/radareorg/radare2-testbins/pull/65

Add PGP search for signature and RSA encrypted private keys

---

test/db/tools/rasign2

**Checklist**
Fixes a rasign2 test that broke because of an update to how signatures are displayed.

Rasign2 space test fix

---

libr/core/cconfig.c
libr/core/project.c
libr/core/rvc.c
libr/include/rvc.h

This pr adds a variable called prj.vc.message which sets a default commit message to rvc/git. and now, projects use rvc_git... instead of r_vc_git.. this is the git+rvc api which is for now at least just for testing.

Integrate rvc in projects and add a default commit message

---

libr/core/cmd_help.c
libr/util/calc.c
test/db/cmd/cmd_help

Use RNum.math in "?b" to make '?b 1<<1' work ##shell

---

libr/include/r_util/r_num.h
libr/util/calc.c
test/db/cmd/cmd_help

Honor < and > comparison operators in RNumMath ##shell

---

libr/core/cmd_help.c
test/db/cmd/cmd_help
test/db/cmd/feat_variables
test/db/formats/firmware

Remove colons in "?" number conversion output ##shell

---

doc/fortunes.fun

Small Typo Fix

---

libr/cons/dietline.c
libr/core/cmd.c
libr/main/radare2.c

Honor faster ^D on interactive execution path ##cons

---

libr/anal/sign.c
libr/core/cmd_zign.c
libr/include/r_sign.h

**Checklist**
Added function `r_sign_metric_search` to r_sign. This essentially exports the `z/f` command.

Add r_sign_metric_search to r_sign.h ##signatures

---

libr/anal/p/anal_riscv.c
libr/asm/arch/v850/gnu/v850-dis.c
libr/bin/pdb/pdb_downloader.c
libr/cons/canvas.c
libr/cons/cons.c
libr/cons/rgb.c
libr/core/p/core_java.c
libr/debug/p/native/windows/windows_debug.c
libr/debug/p/native/windows/windows_debug.h
libr/io/io_desc.c
libr/io/io_map.c
libr/io/p/io_ar.c

Fix some warnings spotted by visual studio

---

libr/anal/p/anal_v850.c
libr/debug/p/debug_native.c

Use data-align = 2 for v850

---

libr/asm/arch/xtensa/gnu/xtensa-modules.c
libr/bin/p/bin_elf.inc
libr/core/panels.c
libr/util/donut.c

Fix more sign bugs spotted by vs

---

libr/core/cmd.c
libr/debug/debug.c
libr/debug/p/native/maps/windows_maps.c
libr/debug/p/native/w32.c
libr/debug/p/native/windows/windows_debug.c
libr/io/p/io_w32dbg.c
libr/util/w32.c
make.bat

Fix the windows debugger and make it more stable ##debug

---

libr/cons/cons.c

Dont check out of bounds last chars

---

libr/core/cconfig.c
libr/core/project.c
libr/core/rvc.c

**Checklist**
My last PR broke projects this one fixes that and probably breaks something else...

Fix a problem with rvc/git and projects ##projects

---

libr/parse/p/parse_v850_pseudo.c
libr/parse/parse.c

Support arch.* namings for the parse plugins ##disasm

---

configure
libr/include/r_types.h
libr/io/p/io_gprobe.c
libr/socket/run.c

Add portability support for Vinix ##build

---

libr/core/cmd_search.c

Implement /ck command to search for crypto constant tables ##search

---

libr/core/rvc.c

**Checklist**
rvc_git_commit was not working now it does.

Fix a problem with rvc

---

libr/core/rvc.c

**Checklist**
fix some memory leaks

Fix some memeory leaks in rvc

---

binr/rules.mk
test/unit/Makefile

Build things

---

libr/io/io_cache.c

Fix #19006 - oobread crashes in io.cache ##io

---

libr/util/sys.c
sys/static.sh

Fix sys/static.sh on iOS/macOS targets ##build

---

libr/asm/arch/arm/v35arm64/Makefile
libr/count.sh
preconfigure.bat

Fixed v35 commit

---

libr/cons/cons.c
libr/core/cmd.c
libr/core/core.c
libr/include/r_cons.h

Check if user interrupted the shell command in nested macros ##shell

---

.github/workflows/ci.yml

Use /MT on windows builds (requires meson flag) ##build

---

libr/cons/cons.c
libr/cons/cutf8.c
libr/core/cbin.c
libr/main/rabin2.c
test/db/tools/rabin2

jklasdjfklaskjlf

---

libr/core/cmd.c
libr/core/cmd_help.c
libr/util/syscmd.c

* Also available via the recursive help
**Checklist**

Write proper help message for the ls and less commands ##shell

---

libr/core/cmd.c
libr/util/syscmd.c

Sort the output of `ls`

---

libr/core/rvc.c
libr/include/rvc.h
libr/main/ravc2.c
test/db/tools/ravc2

**Checklist**
I have added a ravc2 log command which outputs the list of commits, a ravc2 status command which outputs thew current branch and unstaged files. I have also added tests.

Add a status and log commands to ravc2 and add tests for rvc

---

libr/core/rvc.c
libr/include/rvc.h
libr/main/ravc2.c

Fix the rvc asan tests and some heap issues in rvc ##vc

---

libr/anal/p/anal_arm_cs.c
test/db/cmd/cmd_search

Fix /ai on arm64 movs ##search

---

libr/debug/debug.c
libr/include/r_util/r_sys.h

Support 16bit debuggers and fix 27bit define ##debug

---

libr/core/cmd_mount.c
libr/fs/fs.c
libr/fs/shell.c
libr/include/r_fs.h

Use r_return in the r_fs api

---

libr/core/cmd_anal.c

Add aoeq as a quiet aoe command ##anal

---

test/db/formats/mz/cblp0

**Checklist**
Thanks for the feedback at https://github.com/radareorg/radare2/pull/19042#pullrequestreview-744747391. Here are the changes that were recommended.

Improve and consolidate db/formats/mz/cblp0 tests

---

libr/core/cmd_open.c
libr/core/visual.c

Support base64: prefix in the `o` command ##shell

---

libr/core/cmd.c
libr/include/r_util/r_file.h
libr/util/file.c
test/db/tools/ravc2

**Checklist**
this adds a command called rr which allows the removal of a non-empty directory with its contents

Add an rr function which does rm -rf 

---

binr/rules.mk
config-user.mk.acr
preconfigure

Fix --with-rpath and use it from preconfigure

---

configure.bat

Create vs folder when running configure on Windows ##build

---

libr/core/disasm.c
libr/util/str.c
test/db/cmd/cmd_pd
test/db/cmd/cmd_pd_str

Fix missing string in movabs ##disasm

---

libr/cons/dietline.c

Fix #19065 - Fix prompt input when using scr.color=0 ##cons

---

configure.bat
libr/debug/ddesc.c
libr/debug/p/native/windows/windows_debug.c

Fixes for windows

---

.github/workflows/ci.yml

Add job to build r2 for the m1 macs

---

libr/io/p/io_ar.c

**Checklist**
Small fix to prevent the ar io plugin from truncating the provided uri.

Fix const clobber in ar ##io

---

libr/cons/cons.c
libr/cons/input.c
libr/include/r_cons.h

Remove globals on input.c for w32

---

libr/core/rvc.c
libr/debug/p/debug_native.c
libr/include/r_util/r_sys.h
libr/util/sys.c

Move linux specific thing used only in the debugger out of RUtil

---

libr/anal/p/anal_x86_cs.c

Fix #19070 - register size issue on esil for pop ax ##anal

---

libr/cons/dietline.c
libr/cons/input.c
libr/include/r_cons.h

Fix arrows win

---

libr/socket/r2pipe.c

Fix warnings on Socket.r2pipe.child for Windows

---

libr/core/cconfig.c
libr/core/cmd_help.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/include/r_util/r_num.h
libr/include/r_util/r_print.h
libr/util/unum.c
test/db/cmd/cmd_help
test/db/formats/firmware

Improved codesegment support ##disasm

---

libr/util/file.c

Add extra checks in r_file_copy ##util

---

libr/anal/fcn.c
libr/core/cmd_anal.c
test/db/cmd/cmd_afn

Fix #19063 - rename function signature when renaming the function ##anal

---

libr/core/linux_heap_jemalloc.c

Fix segfault in the jemalloc code using RBin instead of RCore ##debug

---

.github/workflows/ci.yml

Fix #19055 - w32/w64 windows artifacts filenames

---

libr/anal/jmptbl.c

Fix #19099 - Fix assert on invalid jump table analysis ##anal

---

libr/anal/p/anal_x86_cs.c

Fix #19103

---

libr/core/rvc.c
libr/include/rvc.h
libr/main/ravc2.c

Add an ravc2 reset command

---

binr/radare2/radare2.c
libr/core/project.c
libr/main/radare2.c

Fail with r2 -p unexistent-project

---

libr/core/rvc.c

Some more code cleanup for rvc.c

---

libr/core/cmd_open.c
libr/core/project.c
test/db/cmd/cmd_project

Fix #19101 - saving/loading projects for PE binaries ##projects

---

libr/core/canal.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_core.h
test/db/cmd/cmd_pd_trunk

Pd700 lazula

---

libr/bin/format/mz/mz.c
libr/bin/format/pe/pe.c
libr/bin/p/bin_mz.c
test/db/formats/mz/1byte

Fix #19043 - Fix loading MZ with text < bsize aka 1byte ##bin

---

libr/main/rasign2.c

**Checklist**
Adds `-S` flag to rasign2. This will cause rasign2 to act on a signature .sdb files. So you can dump signatures with `rasign2 -Sr sig.sdb` or add content of one signature file to another with `rasign2 -So another.sdb one.sdb`. This means combining a lot of signatures files can be done easily in bash with `for i in ./all/*.sdb; do rasign2 -So all.sdb $i; done`
With `-S` putting `-o -` will act as a shortcut to save the signature file to itself. This is only useful for `-Sco -` which will load signatures from the input file, compute collisions, then save those collisions to the input file.

Add zign file reading to rasign2 ##signatures

---

libr/core/task.c
libr/include/r_util/r_w32.h
libr/util/thread_cond.c
libr/util/w32.c

Fix w32 thread_cond using r_w32

---

.github/workflows/ci.yml

Aim to fix the w32 builds

---

libr/include/r_io.h
libr/io/Makefile
libr/io/io.c
libr/io/io_bank.c
libr/io/io_map.c
libr/io/io_submap.c
libr/io/meson.build

I am too lazy to write this down again, so here is a snapshot from tg.
Some of the changes that I want to do, can be done seperately, and don't need to be on this branch, so I'll open small PRs for those.

Rewrite some parts of RIO and add more features (SIOL Eternal) ##io

---

libr/core/project.c

**Checklist**
r_core_project_delete used to remove the project files one by one now it uses r_file_rm_rf so the code is simpler.

Simply the code of r_core_project_delete ##project

---

libr/bin/bin.c
libr/core/cbin.c
libr/core/cfile.c
libr/core/cmd.c
libr/core/cmd_help.c
libr/core/disasm.c
libr/include/r_bin.h
test/db/cmd/cmd_foreach

Foreach fix

---

libr/core/cmd_open.c
libr/io/io_bank.c

Some RIOBank related fixes

---

libr/include/r_io.h
libr/io/io.c
libr/io/io_bank.c
libr/io/io_map.c

Some cleanup and code deduplication ##io

---

libr/core/cmd.c

Better subcommand error messages for @@, @@@ and @@@@ ##shell

---

libr/main/radare2.c
libr/util/sys.c

Fix format string vuln in crash handler

---

Makefile

Improve GIT_TAP

---

dist/plugins-cfg/plugins.def.cfg
libr/asm/arch/include/opcode/pdp11.h
libr/asm/arch/pdp11/gnu/pdp11-dis.c
libr/asm/arch/pdp11/gnu/pdp11-opc.c
libr/asm/p/asm_pdp11_gnu.c
libr/asm/p/pdp11_gnu.mk
libr/include/r_asm.h

Add PDP-11 disassembler support from binutils ##disasm

---

libr/core/cmd_write.c
libr/crypto/crypto.c
libr/crypto/p/crypto_aes.c
libr/crypto/p/crypto_aes_cbc.c
libr/crypto/p/crypto_aes_wrap.c
libr/main/rahash2.c

**Checklist**
As discussed in  #19128, removes global variable in AES encryption plugins.

Remove AES global variables and cleanup

---

dist/plugins-cfg/plugins.def.cfg
libr/bin/meson.build
libr/bin/p/bin_hunk.c
libr/bin/p/hunk.mk
libr/include/r_bin.h
test/db/formats/hunk

Initial implementation of the HUNK file parser ##bin

---

libr/cons/cons.c
libr/cons/grep.c
libr/cons/less.c
libr/cons/more.c
libr/cons/pal.c
libr/cons/rgb.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_info.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/core/fortune.c
libr/core/rtr.c
libr/core/rtr_http.c
libr/core/visual.c
libr/include/r_cons.h
libr/main/radiff2.c

* Fix |H |T and | suffixes when webserver in background
**Checklist**

Move more context fields out of the globals ##cons

---

libr/util/unum.c

Implement ternary support for numeric input ##util

---

dist/plugins-cfg/plugins.def.cfg
libr/asm/arch/alpha/gnu/alpha-dis.c
libr/asm/arch/alpha/gnu/alpha-opc.c
libr/asm/arch/include/opcode/alpha.h
libr/asm/p/alpha.mk
libr/asm/p/asm_alpha.c
libr/include/r_asm.h

Add support for the ALPHA disassembler ##disasm

---

libr/debug/p/native/xnu/xnu_debug.c

Handle PPID on macOS debugger ##debug

---

USAGE.md

Remove duplicate command in USAGE.md ##doc

---

doc/fortunes.fun

Fortune prefix is ` -- `. Added a space so the heart is centered properly. :)

Align heart fortune spacing

---

libr/core/rvc.c
libr/include/rvc.h
libr/main/ravc2.c

**Checklist**
rvc clone copies src/.rvc to dst/.rvc and calls r_vc_reset(dst).

Add an rvc clone command

---

libr/anal/p/anal_hexagon.c
libr/anal/p/anal_vax.c
libr/core/anal_tp.c

Soft crashfixes

---

libr/core/anal_tp.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/reg/rvalue.c

Soft fixes2

---

libr/bin/format/elf/elf.c

Soft fixes3

---

libr/anal/dwarf_process.c
libr/bin/dwarf.c

Fix oobread crash in DWARF parser (tests_64924) ##crash

---

libr/bin/dwarf.c
libr/util/uleb128.c

Fix oobread crash in DWARF parser (tests_64922) ##crash

---

libr/core/rvc.c

**Checklist**
instead of copying files in r_vc_checkout, tell r_vc_reset to do so.

Write r_vc_checkout in terms of r_vc_reset to make it shorter

---

libr/bin/dwarf.c
libr/bin/format/mach0/mach0.c
libr/bin/format/mdmp/mdmp.c

Fix r_buf lifecycle in mdmp

---

libr/core/agraph.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_reg.h
libr/reg/arena.c

Save and check the reg arena size when peekpoking (Fix tests_64923) ##crash

---

libr/bin/format/elf/elf.c

Fix oobread crash in the ELF parser (tests_64931) ##crash

---

libr/anal/p/anal_z80.c

Fix oobread in z80 disassembler (tests_65081) ##crash

---

libr/anal/function.c
test/db/cmd/cmd_af

Improve debug message when misleading a function name in analysis

---

libr/bin/dwarf.c

Wrong bounds initializing dwarf dies (tests_64901) ##crash

---

libr/anal/fcn.c

Fix #19327 - Comment dead code to fix a warning

---

libr/anal/xrefs.c
libr/core/cmd_anal.c

Implement axtm, axfm and add helps for axf? and axt? ##anal

---

libr/core/cbin.c
libr/core/cfile.c
libr/core/cmd.c
libr/core/yank.c
libr/include/r_io.h
libr/io/io.c
libr/io/io_map.c
libr/main/radare2.c

Remove r_io_map_new from public API ##io

---

libr/core/cmd_anal.c

Fix minor leak when adding vars

---

.github/workflows/ci.yml
Makefile
libr/asm/arch/arm/v35arm64/Makefile
libr/util/spp.mk
preconfigure
shlr/Makefile
shlr/capstone.sh
sys/install.sh

Offline builds

---

libr/anal/sign.c

**Checklist**
Fix small leak that might happen if alloc fails.

Fix leak in sig serialization ##signatures

---

libr/anal/sign.c

**Checklist**
Copy paste error prevented a guard on next signatures from working.
The guard should only be needed if something else went wrong, so it's not too worrisome.

Fix validation of next sigs ##signatures

---

libr/include/r_io.h
libr/io/io_map.c

**Checklist**
This will be useful for some later optimizations

Add r_io_map_add_bottom ##io

---

test/unit/meson.build
test/unit/test_crbtree.c

Add unit tests for new rbtree API

---

libr/util/new_rbtree.c

Fix 2 covs and minor cleanup in rbtree

---

libr/util/hex.c
test/unit/test_hex.c

Fix assert crash in unit test

---

dist/plugins-cfg/plugins.wasi.cfg
dist/wapm/Makefile
dist/wapm/README.md
dist/wapm/wapm.toml
libr/anal/Makefile
libr/anal/p/arm_v35.mk
libr/rules.mk
libr/socket/run.c
libr/util/file.c
package.json
sys/emscripten.sh
sys/wasi.sh

Fix wasi builds and update wapm package in the new dist/wapm

---

test/db/cmd/cmd_print
test/db/cmd/cmd_zignature
test/db/cmd/sidbug

raw -> range

---

libr/anal/sign.c
test/db/cmd/cmd_zignature

**Checklist**
Fix bugs in r_sign types validation. See tests for examples

Fix bugs in types validator ##signatures

---

libr/core/cmd_zign.c

Add help message for zac ##signatures

---

.github/workflows/ci.yml
.github/workflows/windows.yml

This version of meson works fine on local Windows

---

.github/workflows/ci.yml
.github/workflows/windows.yml
libr/anal/d/meson.build
libr/anal/meson.build
libr/bin/d/meson.build
libr/bin/meson.build
libr/meson.build
libr/syscall/meson.build
make.bat
meson.build

Check the preconfigure+configure+make Windows workflow in the CI

---

libr/bin/bin.c
libr/bin/bobj.c
libr/bin/i/private.h
libr/core/cbin.c
libr/core/core.c
libr/include/r_bin.h

Use new rbtree api to store relocs

---

libr/core/cbin.c
libr/include/r_util/r_new_rbtree.h

Add r_crbtree_foreach

---

libr/util/print.c

Allow NULL in RPrint.hexdump()

---

libr/anal/sign.c

**Checklist**
Forgot to wrap vars in `{}` so `zj` was producing invalid JSON.

Fix `zj` vars output ##signatures

---

libr/bin/format/pe/pe.c

Fix PE Metadata header name parsing (.net related) ##bin

---

test/db/cmd/cmd_project

Fix broken project test

---

libr/util/w32.c

Winapi all the things

---

libr/anal/fcn.c
libr/anal/jmptbl.c
libr/anal/var.c
libr/core/agraph.c
libr/core/anal_tp.c
libr/core/blaze.c
libr/core/canal.c
libr/core/carg.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/core/disasm_stackptr.inc
libr/core/visual.c
libr/core/vmenus.c
libr/include/r_anal.h
test/db/anal/x86_64

Rename the r_anal_fcn* apis to r_anal_function* (#16178)

---

libr/cons/d/bluy
libr/core/cmd_eval.c
libr/include/r_core.h

Add eco! and eco* and sort eco listing ##cons

---

binr/rabin2/rabin2.c
libr/main/rabin2.c
man/rabin2.1
test/db/tools/rabin2

Honor rabin2 -p to change io->va

---

libr/core/core.c

**Checklist**
Aliases can now be tab-completed for both commands and pseudo-files. The new alias system did not support tab completion, and #19295 introduced an error message when trying to run a help command for incomplete aliases. This implementation is slightly wonky because it shows the alias key and value in the possible completions, but only completes the key in the line buffer when there is a single possible completion. This distinction is important due to `r_line_completion_push()` using the same string both when showing possible completions and during line buffer autocompletion, so `autocomplete_alias()` is somewhat bespoke. There may be some improvements that can be made to this, but it works as desired.

Add tab completion for aliases

---

dist/plugins-cfg/plugins.def.cfg
libr/asm/arch/jdh8/jdh8dis.c
libr/asm/meson.build
libr/asm/p/Makefile
libr/asm/p/asm_jdh8.c
libr/asm/p/jdh8.mk
libr/include/r_asm.h

**Checklist**
##asm
Support disassembly for JDH-8 toy architecture

Jdh-8 asm support  #19227

---

libr/core/visual.c
test/db/cmd/cmd_seek

Fix so-1 in runofthemill

---

libr/cons/canvas.c
libr/core/panels.c
libr/include/r_cons.h

Improve the snow experience in panels mode ##cons

---

libr/bin/format/pe/pe.c
make.bat
package.json

Fix #19448 - Fix atoi on non-null terminated string in PE shdr ##crash

---

libr/anal/fcn.c

**Checklist**
As suggested in https://github.com/radareorg/radare2/issues/19436#issuecomment-977865424, I added a counter to avoid analysing the function after N nops. I have done some local testing however, since I'm not fully familiarized with the project, I marked it as WIP.

Fix #19436  - DoS analysing ELF64 binary for MIPS architecture ##analysis

---

libr/main/radiff2.c
man/radiff2.1

Implement symbol diffing in radiff2 ##diff

---

libr/anal/dwarf_process.c
libr/bin/dwarf.c
libr/include/r_bin_dwarf.h
test/unit/Makefile
test/unit/test_reg.c

* Exploited by tests_65179, tests_65180	and tests_64901
* Unions should be only used wisely and this dwarf code is crap
**Checklist**

Fix invalid pointer read issue in dwarf parser ##crash

---

libr/anal/arch/hexagon/hexagon_anal.c
libr/anal/p/anal_hexagon.c
libr/asm/arch/hexagon/hexagon.c
libr/asm/arch/hexagon/hexagon_disas.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/include/r_anal.h

Vliw support

---

libr/anal/p/anal_dalvik.c

**Checklist**
These changes simply fix the conditionals for dalvik analysis by just using the inequality operators (<,>,<=,...) instead of flag bits. The previous expressions were wrong, and the new ones are clearer anyway. With these changes we can now correctly ESIL emulate all static dalvik code.

Dalvik fix

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc
libr/core/cbin.c
libr/include/r_bin.h
libr/include/r_core.h
test/db/formats/elf/elf-relarm

Inspired by https://github.com/rizinorg/rizin/commit/cd6bde4aeb3221fb336b9df6080d4477d4fc0e78
**Checklist**

Handle more ELF relocs for ARM binaries ##bin

---

libr/io/io.c
libr/io/io_bank.c
libr/io/io_map.c
libr/io/io_private.h
libr/io/ioutils.c
test/db/io/write

Fix #19463 - io write error reporting regression ##io

---

libr/include/r_search.h
libr/search/search.c

**Checklist**
This should have no affect on current code. It will allow future `r_search` update functions to use more complicated states that require a more complicated free.

Update defines how data is free'd ##search

---

libr/core/cmd_open.c

Fix crash and cleanup argparsing in omf command

---

libr/core/anal_objc.c

Fix #19476 - heap overflow in aao ##crash

---

test/db/formats/mach0/objc
test/db/formats/symbols

Add test for the objc crash

---

libr/core/cmd_zign.c
test/db/cmd/cmd_zignature

**Checklist**
Adds JSON output to `zb` commands via `zbj` and `zbrj`.

Add JSON output to zb commands ##signatures

---

libr/anal/Makefile
libr/rules.mk

Do not remake on modules with d/ ##build

---

libr/anal/p/anal_x86_cs.c
libr/asm/p/asm_x86_cs.c

Use cs_disasm_iter to save few allocations ##disasm

---

libr/asm/arch/8051/8051_ass.c

Fix 8051 2

---

libr/lang/Makefile

**Checklist**
Quick-fix to a bug that crashes radare2 when it tries to use an library.

Fix crash 
