radareorg/radare2

libr/bin/p/bin_dex.c
=> Fix #18256 - Double free in RBin.DEX.libs

sys/docker_build_alpine_image.sh
Caught in pkgsrc on NetBSD.
**Checklist**
== is an unportable shell construct.
=> Fix shell portability issue

libr/anal/p/pyc.mk, libr/anal/p/wasm.mk
Avoid passing -I as this is a non-portable construct.
Caught in pkgsrc on NetBSD.
**Checklist**
Passing "-I" without the path breaks the build.
=> Define PYC_ROOT and WASM_ROOT

libr/debug/Makefile
Append, instead of setting -lkvm for BSD platforms.
**Checklist**
Overwriting LDFLAGS causes spurious fallout in the build system, as detected on NetBSD.
=> Avoid overwriting LDFLAGS

libr/include/r_types_overflow.h
=> Fix unused argument warning spotted in r2cutter

binr/radare2/meson.build
**Checklist**
This way, when radare2 is used as a subproject with cli=enabled, the radare2 executable can be referenced
=> Assign radare2 binr target ##build

sys/install.sh
**Checklist**
The [sys/install.sh](https://github.com/radareorg/radare2/blob/95af8dd05e2f7d918454cd403bec0a3793ee1a38/sys/install.sh) script tries to downgrade credentials if run as root but the logic was broken and it couldn't really do that. Also this was being done a little late while it must be the first thing to do. This PR fixes both these problems.
=> Fix a credentials downgrade problem in Install.sh

libr/anal/dwarf_process.c
**Checklist**
I have a binary that triggers a SEGFAULT in R2 because of a null dereference in `prefer_linkage_name`.
=> Function `prefer_linkage_name` fails if `ctx->lang` is NULL

libr/core/core.c
**Checklist**
Fix null dref segfault when tab completing file path in `mo` command after `ms` command as run. This might be a bug in `ms` not putting the `rfs` structure in a proper state, but I don't know enough about `rfs` to really comment. 
To cause the segfult do this:
```
$ dd if=/dev/zero of=ext2.img count=10 bs=1M
> 10+0 records in
10+0 records out
10485760 bytes (10 MB, 10 MiB) copied, 0.0062472 s, 1.7 GB/s
$ mkfs.ext2 ./ext2.img
mke2fs 1.46.1 (9-Feb-2021)
Discarding device blocks: done                            
Creating filesystem with 10240 1k blocks and 2560 inodes
...
$ r2 -v 
radare2 5.1.1 26621 @ linux-x86-64 git.5.1.1
commit: 8841faf4aec261cd7488fe919a3046afeaf85c7a build: 2021-02-15__15:18:42
$ r2 ./ext2.img
Mounted ext2 on /root at 0x0
[0x00000000]> mo …
```
=> Fix NULL dereference in rfs tab complete

libr/core/cmd_open.c, test/db/cmd/cmd_open
**Checklist**
Fix bug with oa command, add a case usage without filename if opened only one file. Add tests for oa.
Probably need to change command description in the book because the new use case not obvious, but not sure how
=> Fix #17049 - oa whithout filename specify, add oa test ##shell ##test

libr/util/charset.c
**Checklist**
Fix the bug that write 2 times multiple charsets.
=> Fix bug to not print both long chars

test/db/asm/x86_16
In real mode – make sure the operand-size override prefix (0x66) is added when, and only when, necessary.
In x86 real mode, it is possible to access 32-bit registers by prefixing the instruction with 66h. This is exemplified in this PR's commit.
I've added tests that make sure that the operand-size prefix is added when needed, and not added otherwise.
=> Add x86-16 tests for the operand-size prefix

libr/bin/format/mach0/coresymbolication.c, libr/bin/format/mach0/coresymbolication.h, libr/bin/p/bin_symbols.c, test/db/formats/mach0/coresymbolication
**Checklist**
The new format is similar to the older one, but all string references are offsets from the start of the string table instead of relative to where the reference lives.
This change detects and reacts to this condition.
Depends on new test bin:  https://github.com/radareorg/radare2-testbins/pull/60
=> Add Support for new CoreSymbolication element format ##bin

libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/cmd_print.c, libr/include/r_reg.h, libr/reg/profile.c, libr/reg/reg.c, test/db/cmd/cmd_arp, test/scripts/badrp.r2, test/scripts/badrp2.r2
This PR aims to:
* Let the user load broken regprofiles without breaking R2 (no null derefs and no broken state)
* Do not allow regprofiles without A0 alias defined. Minimum need to derive the calling convention
**Test plan**
See provided tests. we had 0 tests covering the regprofile parsing or managing. This PR adds some at least. Will add more before i finish this PR
None. its boring to fill the bug template. so i just submitted a WIP PR
=> WIP: Initial work on properly managing invalid regprofiles

libr/cons/cons.c
=> Fix null derefs on RCons when no context is provided ##cons

libr/core/canal.c
**Checklist**
Previously the `label` and `fontname` values were swapped.
Because of this the generated dot graphs only displayed
"Courier" as their label and not the asm code.
This bug was found by generating dot graphs with the radiff2 tool (`radiff2 -m d -g ...`).
=> Fix Ordering Of Fontname And Label For Dot Graphs

libr/util/lib.c
**Checklist**
I get an abort in `free` when running esilsolve plugin because `stru` contains an offset inside the .so file found from:
`stru = (RLibStruct *) r_lib_dl_sym (handler, lib->symname);` and not from `stru = strf ();`. This will fix it.
=> Fix abort in r_lib_open

libr/cons/grep.c, libr/include/r_cons.h, test/db/cmd/feat_grep
**Checklist**
Now grep expression converts from `~str1[0]~str2~str3~?` into `?&str1[0],str2,str3`, and parses in series: modifier, endmodifier, column, row and at the end words. After the parsing of column or row has occurred, it is deleting col or row part by `\0` split, so we get `~str1\00]~str2~str3~?`, lost all data after and cases like a `~[0]~:1` will not work. So better way is to convert the expression to `?&str1[0]~str2~str3` create pointer to every nested grep, split by `\0` and parse every expression apart in the loop
=> Fix #16254 - grep expression parse improvement ##cons

libr/core/canal.c, libr/core/cmd_anal.c
**Checklist**
json commands are supposed to return valid json. This PR is supposed to fix this for aflj (mentioned in the original issue) and abj (aka afbij). There might be more commands where this happens.
=> Fix #18284 (json command returning empty string) ##anal ##json

libr/io/p/io_zip.c
=> io/p/io_zip: fix NULL deref when opening unknown zip

libr/bin/format/elf/elf.c
* Reproducer: r2 elf7
**Checklist**
=> Fix ASAN crash when allocating more relocs than the filesize ##bin

libr/util/asn1.c, libr/util/astr.c, libr/util/pkcs7.c, libr/util/x509.c
* Reproducer: r2 SEGV-a94-0b5-0a6
**Checklist**
=> Fix ASAN crash spotted after r_str_ndup refactoring in x509

libr/include/r_diff.h, libr/util/udiff.c
**Checklist**
I did not see a way to get the changes from a Levenshtien algorithm in r2, so I made it.
This pull ads a the function `r_diff_levenshtein_path`. Like `r_diff_buffers_distance_levenshtein` this function computes the Levenshtien distance. Unlike `r_diff_buffers_distance_levenshtein` it produces enough of the matrix to return a `RLEVEND` terminated array of changes that can be used to get from one buffer to the other. So this is not a replacement for `r_diff_buffers_distance_levenshtein`. This is only helpful if you want to display where difference in buffers occur, and what those differences are.
Currently nothing in r2 uses this function yet. I hope to use it for diffing signatures to help debug why a signature does not match. Thus the capability to include a …
=> Add Levenshtiend path API to ##diff

libr/util/udiff.c
**Checklist**
Had some bad logic for an edge case in `lev_parse_matrix` that my fuzzer picked up. This fixes it.
=> Fix overflow in lev path #diff

libr/anal/fcn.c
@trufae's jmptable PR https://github.com/radareorg/radare2/pull/18447 examines the whole memory and sprinkles the asm listing with many false `case`s:
This PR mitigates this bad side effect but needs further work to fix.
=> V850 jmptable fix, cmpval is almost always -1 and slows anal to a crawl

libr/include/r_diff.h, libr/util/udiff.c
**Checklist**
This abstracts the `r_diff_levenshtein_path` function so it can compare things other then byte buffers. The `RLevBuf` now holds a `void *` and the caller provides a function pointer to do comparisons between two buffers. So this could be used to compare ESIL strings. I ran my differential fuzzer on this using a simple `ut8 *` buffers and it seemed to work properly.
Double check that the function declaration and types make sense. Nothing relies on this code yet, so it's best to nit pick it now. Maybe it would be better to store both buffers and their lengths in a single struct like the following?
```
typedef struct r_lev_buf {
void *bufa, *bufb;
ut32 lena, lenb;
void *user; // for callback, just in case
}
```
I am terrible at organizing this kind of stuff, let …
=> Abstract r_diff_levenshtein_path ##diff

sys/install.sh
The `UID` variable used previously is a Bash extension that isn't present on all
POSIX shells.
**Checklist**
This PR relates to a [comment I made earlier](https://github.com/radareorg/radare2/commit/815c4322171398d3807869e8cd3fdc77efcf724f#commitcomment-48786111).
=> Fix the failure in finding the executing user's ID during install ##build

libr/socket/run.c
**Checklist**
I've corrected the function pointers in the original dyn_init logic. If we're on linux and any symbol failed to be found, dl_open libutil.so and try to resolve any fps which are still NULL.
=> correct function pointers and allow fallback on libutil.so for dyn_init

libr/util/rbtree.c
**Checklist**
I haven't tested
=> Fix uninitialized RBIter.path ##util

libr/core/cmd_anal.c, libr/core/core.c, libr/hash/state.c, libr/socket/run.c
Fixes the following vulnerabilities from Coverity scan:
- Fix 1409066 String not null terminated
- Fix 1451074 Buffer not null terminated
- Fix 1451532 Resource leak
- Fix 1451533 Resource leak
=> Fix coverity vulnerabilities

libr/core/project.c
**Checklist**
In project.c ln 231 you can see: char *rc_path = get_project_script_path (core, prjfile);
and then in line 232 rc_path is used for the last time but it is not freed until the function returns.
=> Freed Variables After Last Use In project.c

libr/core/casm.c, test/db/cmd/cmd_search
**Checklist**
Fix for bug in `/ad` command where a search of multiple consecutive instructions returns offset of last instruction instead of first.
Demo:
```
e asm.arch = avr
e asm.bits = 8
wa ldi r30, 0xac @ 0
wa ldi r31, 0x06 @ 2
"/ad/ ldi r30, 0xac; ldi r31, 0x06" 
```
Expected output:
```
0x00000000   # 4: ldi r30, 0xac; ldi r31, 0x06
```
Actual output:
```
0x00000002   # 4: ldi r30, 0xac; ldi r31, 0x06
```
=> Fix search of multiple consecutive instructions

libr/anal/p/anal_arm_cs.c, test/db/esil/arm_32
**Checklist**
ARM LDR translation in ESIL was wrong when pcdelta was not zero.
We have to add it to the $$ value.
=> Fix pcdelta for ARM esil LDR ##anal

libr/include/r_util/r_file.h, libr/util/file.c
**Checklist**
This patch is supposed to add the functionality given by the unix command find <dir>. In the future this functionality might enable fetures like recursive copy and remove
=> Add recursive list functionality to libr/util/file.c

libr/include/r_diff.h, libr/util/udiff.c
**Checklist**
Add `r_diff_levenshtein_dist` which acts like `r_diff_levenshtein_path` but does not allocate the matrix or return the path through the matrix. 
This is pretty much identical to `r_diff_buffers_distance_levenshtein` except `r_diff_levenshtein_dist` is abstract. It can work on any data type since comparisons are done via a function pointer. The `r_diff_levenshtein_dist` function also has the same `maxdist` logic from `r_diff_levenshtein_path` which can improve speed. In particular, `zb` and `zbr` should see a speed increase in using the new function because of an early exit when two signatures show differences early but are of similar size.
The new function will also attempt to calculate fewer cells as the number of changes seen increases. This could have a …
=> Add abstract Levenshtein dist ##diff

libr/bin/format/elf/elf.c
Context https://sourceware.org/gdb/onlinedocs/gdb/MiniDebugInfo.html
=> Do not consider ELFs with .gnu_debugdata section as stripped ##bin

libr/core/cmd.c, test/db/cmd/cmd_interpret, test/db/cmd/cmds
The problem was that the quotes are not checked to be before or after
the hash comment.
Fixes: 765f2b6bd4098b8e90e46a45c174a71099bc0d56
Signed-off-by: Anthoine Bourgeois <anthoine.bourgeois@gmail.com>
**Checklist**
Any command after the hash sign can be executed if double quote is after the hash.
Example:
```
[0x00000004]> ?  # ;0.wrongseek;Invalidcmd|\wrongsh;3=4@4>/@\wrongfile"";=h
Cannot seek to unknown address '0.wrongseek'
|ERROR| Invalid command 'Invalidcmd' (0x49)
sh: 1: wrongsh: not found
r_cons_pipe_open: Cannot open file '/@\wrongfile""'
Error: Unknown host
Error: Unknown host
Starting http server...
open http://localhost:9090/
r2 -C http://localhost:9090/cmd/
```
=> Fix proper hash comments & quotes mix ##cmd

libr/meson.build
**Checklist**
Meson leaves out `r_util/r_axml.h` which was added in b23a063c3c9fab4c2dedeca005f3cdf0f802f22b.
=> Fix meson missing r_util/r_axml.h

libr/anal/p/anal_pyc.c, libr/asm/arch/pyc/opcode.c, libr/asm/arch/pyc/pyc_dis.c, libr/asm/p/asm_pyc.c, libr/bin/format/pyc/marshal.c, libr/bin/format/pyc/pyc_magic.c, test/db/formats/pyc
* Fix segfault when loading pyc9 file
* Lowercase all instructions (user can later decide asm.ucase)
* Use 1 space, not 20, between instruction and arg
* Detect pyc3.9 bins, not loading properly yet
**Checklist**
=> Improve python disassembler and binary parser ##bin

libr/util/print.c
=> Prevent r_print_hexdump to get a negative size

libr/bin/mangling/swift-sd.c, test/db/formats/coff
=> Fix wrong demangling of tiff swab16 bit data ##bin

libr/main/rafind2.c, test/db/tools/rafind2
**Checklist**
Hi, I have discovered some issues in ``rafind2`` when it is used with multiple files.
The first issue is that ``rafind2`` segfaults when multiple files are provided.
For example (invoked in the top of the repo):
```
$ rafind2 -s radare.org Makefile README.md
File: Makefile
0x36d5
File: README.md
```
The issue seems to be that after some refactoring the list of keywords to search for is freed prematurely.
Note that this issue also affects the recursive search when providing a dir instead of files.
The first patch in this PR should fix this, see:
```
$ rafind2 -s radare.org Makefile README.md
File: Makefile
0x36d5
File: README.md
0xb9
0xacd
0xae6
```
The second issue is that the context for each file is not re-initialized and …
=> Fix rafind2 issues when used with multiple files ##search

libr/hash/state.c
Build failure happens at:
```
$ ./configure --with-openssl && make
....
state.c: In function 'r_hash_do_hmac_sha256':
state.c:155:19: error: 'r_SHA256_BLOCK_LENGTH' undeclared (first use in this function); did you mean 'SHA256_BLOCK_LENGTH'?
155 |         ut8 bskey[r_SHA256_BLOCK_LENGTH]; // block-sized key
|                   ^~~~~~~~~~~~~~~~~~~~~
|                   SHA256_BLOCK_LENGTH
```
=> state.c: fix --with-openssl build

sys/clang-format-diff.py
**Checklist**
The first patch fixes an off-by-one error when detecting formatting issues.
Without this, for example such change goes unnoticed:
```
diff --git a/libr/main/radare2.c b/libr/main/radare2.c
index 7699c091a..a7a6397f9 100644
--- a/libr/main/radare2.c
+++ b/libr/main/radare2.c
@@ -280,6 +280,7 @@ beach:
}
static bool mustSaveHistory(RConfig *c) {
+       test();
if (!r_config_get_i (c, "scr.histsave")) {
return false;
}
```
The second patch improves the debug output by moving the printed line after printing the boundaries.
Thanks to this, using `--debug` we get:
```
lineidx :  }
lineidx :  
lineidx :  static bool mustSaveHistory(RConfig *c) {
set range_start: 284
lineidx : +     test();
set range_end: 285
lineidx :       if (!r_config_get_i (c, "scr.histsave")) …
```
=> Clang format script fixes

libr/main/rafind2.c, test/db/tools/rafind2
**Checklist**
The current implementation of the filename header wasn't very useful when there are many files without any match, for example:
```
$ rafind2 -s R2AGENT man
File: man/rax2.1
File: man/rarun2.1
File: man/radare2.1
File: man/r2agent.1
0x15
0x2c
File: man/r2pm.1
File: man/r2-docker.1
File: man/rahash2.1
File: man/radiff2.1
File: man/r2r.1
File: man/rafind2.1
File: man/rasm2.1
File: man/esil.7
File: man/rasign2.1
File: man/ragg2.1
File: man/rabin2.1
```
This gets worse if there are more files.
And even worse when it is combined with other printing modes (like json, where the header literally breaks the json by printing filenames in between).
The first patch changes the way the header is printed o more grep-like approach - the name is printed before each match:
``` …
```
=> filename printing improvements in rafind2 ##search

libr/core/cmd.c
**Checklist**
In #18526 I added the r_file_lsrf function to the cmd.c file and it caused a problem as I passed *input to a function instead of *arg. I would like to express my apology towards trufae and everyone who uses r2. I clearly didn't write my code responsibly and I can only hope to one day improve so I can give back to this truly wonderful project.
=> Fixed confusion between *input and *arg in cmd_ls()

libr/main/rafind2.c
**Checklist**
The `-e` switch (regexp) didn't work in rafind2 - the keywords were never set.
It seems that the code can be shared with regular keyword search. The only issue, which I don't think can be solved without some proper refactoring is that some of the modes that can specify the keywords multiple times share the same variables (e.g. the keywords) and overwrite the mode. So I guess it won't work as expected (?)
=> Fix regexp search in rafind2 ##search

libr/main/rafind2.c, test/db/tools/rafind2
strlen does not count the trailing \0 - the r_search_keyword_new call
uses memcpy internally to copy the string based on the length provided
in the argument.
Effectively we do not copy the trailing \0 to the keyword and the search
does not always work as intended (sometimes the garbage from the memory
is 'joined' to the keyword string).
**Checklist**
=> Rafind regexp fixes ##search

libr/crypto/p/crypto_cps2.c
**Checklist**
Hello,
this patch avoids c99 feature of declaring variable withing the for stanza. 
In rest of the radare2 the same pattern of NOT declaring the variables in for cycle is already followed.
This was the only exception.
Sample build log output
FAILED: libr/crypto/libr_crypto.so.5.2.0.p/p_crypto_cps2.c.o 
cc -Ilibr/crypto/libr_crypto.so.5.2.0.p -I. -I.. -I../libr/include -I../shlr/spp -I../shlr/sdb/src -pipe -D_FILE_OFFSET_BITS=64 -fvisibility=hidden -O2 -g -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -fPIC -pthread -DR2_PLUGIN_INCORE=1 -MD -MQ libr/crypto/libr_crypto.so.5.2.0.p/p_crypto_cps2.c.o -MF libr/crypto/libr_crypto.so.5.2.0.p/p_crypto_cps2.c.o.d -o …
=> Avoid c99 feature

libr/include/r_types.h
**Checklist**
Build failure due to absent TARGET_OS_IPHONE
=> r_types: Reverse order of constant definitions for Darwin

libr/core/cmd_zign.c, test/db/cmd/cmd_zignature
**Checklist**
This ads the `zd` command to print a diff of the current function and a chosen signature.
I am not great at making pretty interfaces, so feedback is welcome. The test I added shows how output looks currently.
=> Add byte signature diff `zd` ##diff ##signatures

libr/core/cmd_zign.c
**Checklist**
Now `zb` command has no output when function signature is smaller than minsz, it's meant to print warning but `\n` is missing so users can just see blank.
I make small changes so the warning is shown along with the matched functions.
`make -k all` throw lots of errors on my machine saying `<r_*.h>: No such file or directory`. But I have checked the tests manually and there is no test related to small function signature size so I think it can be merged.
=> Fix unshown warning in `zb` command when size is small

libr/anal/sign.c, test/db/cmd/cmd_zignature
**Checklist**
Before this commit, when in the NULL zignspace (`zs *`), the `z`, `z*` and `zj` commands will display all signatures in all zignspaces. However, the `z/` command will only search signatures in the current NULL space. See below:
```
[0x00006160]> zs *
[0x00006160]> z ~entry
(testspace) testspace:entry0:
realname: entry0
types: func.entry0.args=1, func.entry0.arg.0="int64_t,arg3"
[0x00006160]> z/
[+] searching 0x000245c8 - 0x000258b8
[+] searching 0x00023350 - 0x000245c8
[+] searching 0x00019000 - 0x00021f08
[+] searching 0x00004000 - 0x000181a9
[+] searching 0x00000000 - 0x00003538
[+] searching function metrics
[0x00006160]> zs testspace 
[0x00006160]> z/
[+] searching 0x000245c8 - 0x000258b8
[+] searching 0x00023350 - 0x000245c8
[+] searching 0x00019000 - …
```
=> Make z/ search sigs seen in z* ##signatures

libr/anal/sign.c, libr/core/cmd_zign.c
**Checklist**
The code for `z`, `z*` and `zj` has been bothering me for a while. So I refactored it a little and dropped a lot of code. It should be a much easier to implement a new signature type that uses a `RList` data type.
Two things were fixed. Dumping signatures of type RList was abstracted into a single function (except for types signatures, they take special handing for json).  Then `r_sign_foreach` is being used instead of `sdb_foreach`. This means the `r_sign_foreach` will handle the de-serialiaztion, space handling and free'ing of the RSignItem.
=> Refactor output of ##signatures

libr/util/strbuf.c
**Checklist**
Very minor optimization to `r_strbuf_vappendf` (and thus `r_strbuf_appendf`). The `r_strbuf_vappendf` function already computes the length of the appended string and stores it in `ret`. So instead of doing `r_strbuf_append_n (sb, p, strlen (p))` via `r_strbuf_append` you can just do `r_strbuf_append_n (sb, p, ret)` and save a `strlen` loop.
=> Small optimzation to r_strbuf_vappendf

libr/core/cmd_search.c, test/db/cmd/cmd_search_hit
**Checklist**
Certificate search was not reset thus displaying wrong results if previous search was made.
=> Reset certificate search properly

libr/anal/sign.c, libr/include/r_sign.h
**Checklist**
Refactors the serialization of signatures. I am going to be adding a new signature type soon but saw the current serialization code was difficult to add to, so I refactored it.
I replaced the old sdb key seriliaztion code with code that allocates the key in the heap. This removes the need use of `R_SIGN_KEY_MAXSZ` and `R_SIGN_VAL_MAXSZ`. 
I reworked completely rewrote the value serialization function. Now there should be a lot fewer allocations and re-allocations. Additionally, adding a new `RList` style signature will only require a single line be added to the serialization function.
While replacing the old key serialization function, I saw a lot of repeated code. Mainly sdb_foreach callbacks that all did a serialization. So I made a slightly more …
=> Refactor serialization of ##signatures

libr/core/cconfig.c, libr/parse/code.c
=> Fix #16687 - Handle multiple colon separated paths in dir.types ##types

meson.build
This patch makes it possible to build with older version of meson.
It is needed to build radare2 on RedHat Enterprise Linux 8 where the meson version 0.49 is older than on RHEL7+EPEL7 or Fedora.
Issues fixed:
- set minimum meson version down to 0.49 (version available in RHEL8)
- meson 0.49 has bug which prevents processing of '\' split-lines => build r2_version_number on single line
- on meson 0.49 the ternary operator is not possible to use with some constructs (subdir in add_install_scripts) => replace one ternary operator with if-else construct
**Checklist**
=> Make meson compatible with older versions (RHEL8 meson 0.49)

meson.build
The pkgconfig module is named libxxhash on Debian/Fedora/RedHat/SuSE/Arch so I added libxxhash on first place.
Keeping the xxhash checked second.
**Checklist**
=> Improve the xxhash system library detection

test/db/cmd/cmd_zignature
**Checklist**
`r2r db/cmd/cmd_zignature` takes 20 seconds on my machine. There is a lot of unnecessary analysis in this file. Replacing `aaa` with `aa` or `af @...` has resulted in no change to the results. The testing time is reduced on my machine from 20 seconds to 5.
=> Faster signature tests

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/db/cmd/cmd_zignature
**Checklist**
This commit ads the R_SIGN_COLLISIONS ('C') signature type, which will later be used to resolve what an unkown function should be named when multiple signatures match. Currently, there is not enough code around this signature type to make it very useful. Additionally, the way matching is done with byte signatures and graph signatures being matched separately,  r2 can not fully benefit from this feature. I am sending this now in hopes for comment, let me know if you think I can do something better. Also, I am sending this now because it can help signature database maintainers (if there are any) trim their databases.
This pull ads the `zac` command to add zignature collisions. This is another signature type that is added to `RSignItem` and is just a `RList` of …
=> Add collisions type to ##signatures

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h
**Checklist**
Moves bytes searching against functions into the `r_sign_fcn_match_metrics`.  This will allow `fcnMatchCB` to get all the found signatures for a function at once and make a better decision on if the function should be renamed, or if there are signature collisions.
If `z/` is run, with no other function metrics enabled, then this new code should have no effect. The byte search callback function `searchBytesHitCB` will be responsible for renaming functions and setting flags.
If `z/` is run with other search metrics enabled, then the usual `z/` byte search will occur but `searchBytesHitCB` will not rename anything. That function will only be responsible for finding and creating new functions. Then the metric search will also check known functions, including …
=> Add byte ##signatures to metric search

libr/core/cmd_zign.c, test/db/cmd/cmd_zignature
**Checklist**
Followup to #18703, this makes `z/` create new functions when a byte signature is found outside of a function. If bytes are the only signature in use, the function will get named. Otherwise the new function will be named by the combination of matched signatures that occurs later.
=> Create function when z/ finds byte ##signatures 

libr/bin/format/mach0/mach0.c
**Checklist**
Removes sdb_fmt usage in mach0.c.
=> Remove sdb_fmt references in mach0.c

libr/debug/p/native/bsd/bsd_debug.c
OCF's KF_TYPE_CRYPTO flag had been retired for the 13.x release,
but the 12.x release is still very much supported.
**Checklist**
- [] I've added tests (optional)
=> debug: Fix FreeBSD 13 build.

libr/anal/sign.c
**Checklist**
Previous graph match logic was inverted for `bbsum` logic. This is because small `bbsum` would mess up the math in `matchCount`. For example, `matchCount( 5, 5)` returns `0` because `R_ABS(5 - 5) == 0 !< 0 == 5 /10`. So it was thought that `matchCount` returning `0` was a match. This means, normal sized functions would fail to match because `matchCount(>10, >10)` returned 1:
```
> r2 /bin/ls
[0x00006160]> s main
[0x00004760]> af
[0x00004760]> zaf
[0x00004760]> z/
[+] searching 0x000245c8 - 0x000258b8
[+] searching 0x00023350 - 0x000245c8
[+] searching 0x00019000 - 0x00021f08
[+] searching 0x00004000 - 0x000181a9
[+] searching 0x00000000 - 0x00003538
[+] searching function metrics
bytes:  1
refs:   1
types:  1
bbhash: 1
total:  4
[0x00004760]> zi~graph?
0
``` …
=> Fix bug in graph matching ##signatures

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/db/cmd/cmd_zignature
**Checklist**
This makes the collision signature useful. Now the function matching callback will revive a `RList` of `const char *` signature names that should collide. If this list is empty, it means there are no collisions. 
If the list is non-empty, the callback function won't rename the function anymore. It will apply flags for each matched signature and mention that a collision exists in the flag.
Collisions are resolved with a set intersection operation on `RList`'s. So if a signature has the following collisions `g:badbytes, g:other, b:badgraph, b:other` and both the byte and graph signature match, it implies the only collision is with the signature `other`. If `other` was not in the list, then there would be no collision because there would be no other signature in …
=> Consider collision ##signatures before renaming

libr/core/cconfig.c, libr/core/cfile.c, libr/core/core.c, test/db/esil/x86_64
=> Fix #18717 - Syscall table is always loaded on startup now

libr/anal/p/anal_s390_cs.c, libr/asm/p/asm_s390_cs.c, libr/asm/p/asm_s390_gnu.c, test/db/anal/s390
=> Fix disasm alignment of data words in s390x disassembler plugins ##anal

libr/config/config.c, libr/core/cconfig.c, libr/core/core.c, libr/include/r_config.h, libr/include/r_core.h, libr/include/r_util/r_str.h, libr/util/charset.c
=> Fix autocompletion for 'e ' and handle cfg.charset=<tab> ##shell

libr/asm/arch/arm/armass64.c, test/db/asm/arm_64
**Checklist**
- [ X] Closing issues: #18619
- [X ] I've added tests (optional)
=> Fix 18619 - Wrong assembly generated for: "add x0, x0, 1, lsl #12" (ARM64)

libr/include/r_magic.h, libr/magic/apprentice.c, libr/magic/file.h, libr/magic/magic.c
**Checklist**
It is still UTF-8, and thus not valid to have a NULL inside of the the
file, but sometimes inputs are not NULL-terminated
=> Add size parameter to r_magic_load_buffer ##util

libr/anal/esil.c, libr/core/cmd_anal.c, libr/core/visual.c, libr/core/vmenus.c, libr/include/r_core.h
* n/p keys seek one instruction forward/backward
* o key to enter new offset
* e key to enter new esil expression
* infinite loop fixed on invalid expressions
* : enter commands working again
**Checklist**
=> Add 'aev' as an alias for VbE and improve esil debugger ##esil

shlr/sdb/src/main.c
=> Fix the infamous 160 byte memory leak in sdb

libr/include/r_util/r_rbtree.h, libr/util/rbtree.c
**Checklist**
Sometimes you need to get the first node instead of the item so that you can iterate forwards/backwards on the tree. I need this for iobanks
=> Add r_rbtree_cont_node_{first/last} (siol_eternal) ##util

libr/anal/p/anal_arm_cs.c, test/db/esil/arm_16, test/db/esil/arm_32
**Checklist**
In ARM architecture, the ldrd instruction was handled as ldrb by ESIL. 
A ldrb instruction loads an unsigned byte into a register. A ldrd instruction loads a word into a register, and the following word (first word address + 4) into a second register.
The ESIL representation of ldrd was thus wrong. This PR fixes the ESIL and adds a few tests to ensure future non-regression.
`LDRB` is `LDR` with `B` type:
`LDR{type}{cond} Rt, [Rn {, #offset}] ; immediate offset`
-> Loads the byte [Rn + offset] into Rt
`LDRD` is a separate instruction:
`LDRD{cond} Rt, Rt2, [Rn {, #offset}] ; immediate offset, doubleword`
-> Loads the word [Rn + offset] into Rt and the word [Rn + offset + 4] int Rt2
=> Fix arm ldrd esil ##emu ##test

libr/debug/p/native/linux/linux_coredump.c
In e92d170a3b9fa70e2abacae73e30acfb3dcfc6bd, the include of `asm/ptrace.h` has been silently disabled (it is presently unclear to me why). Thereby basically reverting #13427. However, without `asm/ptrace.h` included the build will fail on musl armhf/armv7 targets with the following compilation failure:
p/native/linux/linux_coredump.c: In function 'linux_get_arm_vfp_data':
p/native/linux/linux_coredump.c:950:27: error: 'ARM_VFPREGS_SIZE' undeclared (first use in this function)
950 |  char *vfp_data = calloc (ARM_VFPREGS_SIZE + 1, 1);
|                           ^~~~~~~~~~~~~~~~
This commit fixes this build failure by including asm/ptrace.h again.
---
CC: @trufae
=> Fix armhf/armv7 musl compatibility again

libr/core/cconfig.c
**Checklist**
Ps used to fail on windows due to a missuse of r_file_path, prj.vc was always set to true and prj.vc.type was sometime undeclared. This PR attempts to fix these problems
=> Set prj.vc to false if git is not in PATH

libr/core/cmd.c, libr/include/r_core.h, test/unit/meson.build, test/unit/test_cmd_str.c
**Checklist**
When r2pipe commands are executed the result is not supposed to be printed to the console but instead it should be returned as a string to r2pipe, while this works in general but there are some command combination that cause some leakage. This patch ensures the console isn't flushed until r_core_cmd_str is finished including the case when r_core_cmd_str is reentrant.
=> Fix issue #18799 - r2pipe commd output leaks to stdout

libr/main/ragg2.c
**Checklist**
Support loading user plugins (from R2_USER_PLUGINS) in ragg2. Based on rasm2 code.
```sh
$ ragg2 -L
shellcodes:
exec : execute cmd=/bin/sh suid=false
myshc : egg shellcode plugin template
encoders:
xor : xor encoder for shellcode
myenc : egg encoder plugin template
```
```
[0x00000000]> gl
shc    exec : execute cmd=/bin/sh suid=false
enc     xor : xor encoder for shellcode
enc   myenc : egg encoder plugin template
shc   myshc : egg shellcode plugin template
```
[egg-plugin-templates.zip](https://github.com/radareorg/radare2/files/6593513/egg-plugin-templates.zip)
=> Ragg2 user plugins ##egg

libr/util/Makefile, libr/util/d/Makefile
**Checklist**
radare2 failed to build without using `--without-gperf` option,
with the following message: No rule to make target 'd/ascii.o',
needed by 'libr_util.so'.
I took a look into anal/d/Makefile which seems to be doing the same
thing. I noticed that it was using `all` as default target instead
of `alle` as done in util/d/Makefile. Moreover the .PHONY only mention
`all` an not `alle`, thus I believe this is a typo, and it was meant
to be `all`, fix this.
This could also be fixed by changing the `all` to `alle` target in `.PHONY`. not sure if it is a better fix.
---
edit: Maybe the issue I was having is only related to a dirty build directory.
The issue I was having can no longer be reproduced after cleaning the `libr/util/d/` directory
This commit now add a clean …
=> Add doclean target into libr/util/d/Makefile ##build

libr/main/ragg2.c
**Checklist**
Fixes the following option parsing issues
- The X flag should require an argument
- The E flag throws an illegal option error
```sh
$ ragg2 -i exec -E xor -c key=0xa
ragg2: illegal option -- E
```
Expected behavior
```sh
$ ragg2 -i exec -E xor -c key=0xa
6a1b596a0a5be8ffffffffc15e4883c60d301e48ffc6e2f93bca42b1db979c9bda869df542fdd1595e5593585d5e54ba31050f
```
=> Fix ##ragg2 options 

libr/anal/p/anal_arm_cs.c, test/db/esil/arm_16, test/db/esil/arm_32
**Checklist**
ESIL translation of ldr instructions lacked support for pre/post-indexed register offset, along with negative register offset.
Instructions like `ldr r0, [r1], -r2` and `ldr r0, [r1, -r2]` where thus handled like `ldr r0, [r1, r2]`.
Strictly speaking, the problem with negative register offset (the `-r2`) is not related to the pre/post-indexed problem. But as I resolved both problems at the same time I only do one PR. Let me know if you want me to make two separate PR for this.
Anyway, this PR includes tests for ARM32 and ARM16 in order to ensure no future regression.
=> Fix ldr pre post esil ##emu ##test

binr/preload/libr2.c, libr/io/p/io_debug.c, libr/io/p/io_self.c, libr/main/r2agent.c, libr/socket/run.c, libr/util/sys.c, libr/util/thread.c
=> Use r_sys_getpid() for source portability whetever getpid() is called

libr/util/str.c
=> Fix oob read bug in r_str_home on empty env vars

libr/asm/asm.c
=> Fix `aod` (opcode description) when using the `r2ghidra` asm plugin

libr/anal/fcn.c, libr/anal/p/anal_avr.c, libr/core/canal.c
* Early emulation interruption for faster ^C
**Checklist**
=> Avoid assert on avr's null cmpreg test ##anal

binr/rvc2/rvc2.c, libr/core/rvc.c, libr/include/rvc.h, libr/main/rvc2.c
**Checklist**
In https://github.com/radareorg/radare2/pull/18499 I helped introduce the abomination known as rvc. This pr tries to make rvc use sdb for branches instead of having them as dirs. This has many advantages most notably:
* Rvc does no longer copy & dup commits when branching since commit don't hold info about their position
* Rvc no longer has to have the "loading_functionality" since needed data is loaded on command
a disadvantage would be that now Rvc would have to load important data every time an R_API function is called
I would recommend the revs to focuse on the sdb usage because it is probably not valid.
TODOs:
* Add some proper error messages
* Add r_vc_checkout functionality
* Add some checks to know whether or not an rvc_repo exists before executing a …
=> WIP: use sdb in rvc

libr/core/canal.c, test/db/cmd/cmd_agf
**Checklist**
Details on the bug can be found in Issue #18852.
Turns out that when processing a graph for export in several formats (including graphviz), when processing a jump table, an edge `caseop->addr` -> `caseop->jump` is added for each case of the jump table. However debugging the `caseop` struct shows that these fields contain the same value, hence the reason of the self-looping edge. 
Given that the GML implementation was only slightly different and did not present the bug, I replaced `caseop->addr` and `caseop->jump` with the values used in that implementation.
Additionally:
- replaced `color2` with `color`. color2 is not a valid graphviz keyword and is ignored (tested with dot 2.47.3).
- changed the color to be consistent with all the other representations. …
=> Fix #18852 wrong tables in graphviz dot ##print

libr/core/cbin.c, libr/core/cmd.c, libr/core/cmd_info.c, test/db/anal/s390, test/db/cmd/cmd_i, test/db/cmd/cmd_open, test/db/cmd/feat_grep, test/db/formats/dmp/dmp, test/db/formats/elf/elf-riscv64, test/db/formats/elf/v850, test/db/formats/mdmp, test/db/formats/prg, test/db/formats/smd, test/db/formats/web_assembly, test/db/tools/rabin2
* Does not requires rbin to work, its tied to RAnal which is global
**Checklist**
=> Put archinfo.{minopsz,maxopsz,align} in the output of i ##bin

libr/include/r_types.h
**Checklist**
r2 assumes that arm64 Darwin targets don't have `system()`, which applies only to iOS/tvOS/watchOS, so this adds a check to exclude macOS targets.
=> Fix `system()` on arm64 macOS targets 

libr/util/str.c, test/db/anal/arm, test/unit/test_str.c
=> Fix r_str_ansi_len() causing unaligned 'unaligned' words ##disasm

libr/core/cmd_anal.c, test/db/cmd/types
=> Implement 'afs*' command to export function signature info in r2 commands ##anal

libr/core/cconfig.c, libr/debug/p/native/linux/linux_debug.c
* Hide GETREG error shown on WSL1
**Checklist**
=> dbg.verbose is now set to false by default

libr/anal/p/anal_arm_v35.c, libr/anal/p/anal_dalvik.c
**Checklist**
This PR makes many changes to the dalvik plugin that fix the ESIL and analysis information for wide and math instructions. Previously the wide instructions did not use register pairs in order to properly get and set 64 bit values. Also there were very few supported math instructions and no consistency with how the different types (int, long, float, double) were handled. Now all instruction formats and types are handled in a somewhat organized way. 
These changes make emulation of any static methods correct, as long as it only deals with primitives and constant strings. It is still not possible to get or set object fields. In order to make the emulation fully correct we need to add some sort of lightweight runtime that actually creates objects in memory. …
=> Add wide and math instr esil for dalvik, pac esil for arm64 ##esil

libr/core/cmd_anal.c
fix invalid argv read for table param and others,
fix memory leak by missing free for strdup,
fix invalid elem size and elem count for jmtbl which previously was set to same value, now it can be set properly
extend afj command by adding 2 new parameters elem_sz and seg for precise jmp tbl reading.
According to our IRC conversation about afj naming it is not changed yet. Great subject for discussion about analyzing function jumptable command name.
**Checklist**
=> fix afj command and afj command extension

libr/anal/p/anal_x86_cs.c
**Checklist**
On x86, `POPF`, `POPFD` and `POPFQ` pop the flags register off of the stack, increasing the stack pointer. Currently esil correctly updates the flags, but does not change the stack pointer, resulting in incorrect emulation. This change fixes that.
=> Fix POPF POPFD POPFQ not increasing stack pointer ##esil

libr/anal/fcn.c, libr/core/canal.c, libr/include/r_anal.h
Changed found r_anal_fcn api calls to r_anal_function to reflect new changes.
**Checklist**
The changes done were to replace the r_anal_fcn with r_anal_function. This is due to the r_anal_fcn being depreciated.
=> Changed r_anal_fcn call to r_anal_function in support of depreciation ##anal

libr/core/disasm.c, libr/parse/p/parse_x86_pseudo.c, libr/parse/parse.c, test/db/anal/s390, test/db/anal/x86_16, test/db/anal/x86_32, test/db/anal/x86_64, test/db/cmd/cmd_ahi, test/db/cmd/cmd_pd, test/db/cmd/cmd_pd2, test/db/cmd/cmd_pdc, test/db/cmd/print
This change exposes a bug in the regrssions suite, the varsub doesnt seems to work well without spaces. ( and ) chars should be used as delimiters as comma or space do.
**Checklist**
=> Drop spaces in pseudo strings

libr/core/cconfig.c
=> Dont use scr.responsive on android by default

libr/anal/p/anal_x86_cs.c, test/db/esil/x86_64
**Checklist**
Fixes my bad mul / imul ESIL which did not work for *dx operands (the register is written to and then used again as if it were not) and also MUL was not valid for 64 bits. 64 bit IMUL instructions will still be wrong since theres no 128 bit sign extension. I will fix this at some point. I really hate IMUL.
=> fix mul and imul for *dx operands and 64 bit widths ##esil

libr/core/cmd_search.c, test/db/cmd/cmd_search, test/db/cmd/cmd_search_crypto, test/db/cmd/cmd_search_hit
**Checklist**
Can table search was previously in `/cu` but since it is not related to Cryptography I moved it to `/ru`. Crypto tests have been moved to search_crypto.
=> Move CAN table search to /ru command

libr/core/rvc.c
**Checklist**
This PR prevents repo_files() from traversing dirs with a .rvc in them (besides the root)
=> Exclude files of nested rvc repos from repo_files() ##projects

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, libr/main/rasign2.c
**Checklist**
Refactors r_sign to export `r_sign_add_func` and `r_sign_all_functions` which will turn a single function, or all known functions, into signatures. This allows `rasign2` to easily create signatures without relying on `r_core_cmd` family of functions.
=> Expand r_sign API ##signatures

libr/cons/cons.c
Hello, the below PR is the result of a long investigation why radare2
gets stuck in some rare cases. I am not an experienced C coder so
take this analysis with a grain of salt, but it matches with what we
have seen in gdb during debugging.
In case the string to be written by `vsnprintf` including `\0`
termination equals to the length of the buffer, the code enters in a
busy loop. The original code seems to assume, that `vsnprintf` won't
terminate the string with `\0` character which it does.
The [documentation of `vsnprintf` states](https://en.cppreference.com/w/c/io/vfprintf):
> `int vsnprintf( char *restrict buffer, size_t bufsz, const
> char *restrict format, va_list vlist );`
>
> Writes the results to a character string buffer. At most bufsz - 1
> characters are written. The resulting …
=> r_cons_printf_list: fix potential busy loop

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/db/cmd/cmd_zignature
**Checklist**
Before this commit, r2 will create a new zignspace if a function name contains a `:`. See below:
```
[0x00005b20]> s main
[0x000040a0]> afn newspace:name
[0x000040a0]> zs
[0x000040a0]> zaf
[0x000040a0]> zs
1 * newspace
[0x000040a0]> z
(newspace) newspace:name:
...
```
=> Fix bug in zaf creating zignspace ##signatures

libr/core/panels.c
In panels mode `X` closes current panel. This PR documents it.
=> add X description: closes current panel

libr/bin/format/elf/elf.c, libr/bin/format/elf/elf.h, libr/bin/p/bin_elf.inc, test/db/formats/elf/bigph
* Useful for loading qemu coredumps
**Checklist**
=> Fix #18783 - Support ELFs with phnum > 0xFFFF ##bin

libr/anal/sign.c, libr/include/r_sign.h
**Checklist**
This updates the signature foreach family of functions to stop looping if the callback returns false. Additionally, metric searches will stop searching for the next signature if there is a match without collision. This wont prevent a signature from matching two different functions.
=> Early exit on ##signatures match w/o collision

libr/socket/run.c
**Checklist**
This way it'll use `SHELL_PATH` from `libr/include/r_util/r_file.h`, allowing [patching](https://github.com/termux/termux-packages/blob/master/packages/radare2/fix-bin-sh-path.patch) to be simpler.
=> Use `r_file_binsh` in `r_run_start`

binr/r2pm/r2pm, man/r2pm.1
**Checklist**
R2PM_OFFLINE variable allows to install a package offline without pull to $R2PM_DBDIR.
=> r2pm: Add offline option for installation

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, test/db/cmd/cmd_zignature, test/db/tools/rasign2
**Checklist**
This creates the `N`ext signature type. This functions to improve signature matching speed by suggesting what the next function might be when a function is matched. When the suggested signature is matched, the algorithm can safely avoid looping through the entire database of signatures and avoid any signature collision checks.
Tests were update only to fix the tests that this would otherwise break. Namely, functions are now sorted by offset before searching, which results in flag index numbers to be different then previous tests. Second rasign2 will be producing 2 more lines matching `main`. One line for the `N` signature type and another line for the previous functions `N` type pointing at main.
You are welcome to wait until I add tests for this signature …
=> Implement "next" signature type ##signatures

libr/core/rvc.c
=> Dis-allow \.* in rvc commit messages

libr/main/rasign2.c, test/db/tools/rasign2
**Checklist**
This adds the `-c` flag to rasign2 which will cause rasign2 to compute collision signatures before output.
=> Add collision ##signatures feature to rasign2

libr/core/cfile.c
=> Unset default flagspace after loading bin. Fixes ccall:// issues ##bin

binr/r2r/r2r.c, test/README.md
**Checklist**
A test in `test/db/cmd/cmd_i` uses an incorrect timestamp, causing test failure.
```
$ grep timestamp test/db/cmd/cmd_i | uniq
"timestamp": "Thu Jan  1 00:00:00 1970"
$ objdump -x test/bins/pe/standard.exe | grep 'Time/Date' | head -n1
Time/Date               Wed Dec 31 18:00:00 1969
```
Test no longer fails:
```
$ git checkout master && r2r test/db/cmd/cmd_i
...
[144/144]                 135 OK         7 BR        1 XX        1 FX
```
```
$ git checkout fix-broken-cmd_i-test && r2r test/db/cmd/cmd_i
...
[144/144]                 136 OK         7 BR        0 XX        1 FX
```
=> Force tests to run in UTC timezone ##test

.gitignore
**Checklist**
d1d9f7f774162e62a0c2512cd43cda8fec1793ba introduced an additional directory download during the build process which was not added to .gitignore, causing the cloned repository to show up as untracked in `git status` after building.
```
$ git checkout master
$ git status
On branch master
nothing to commit, working tree clean
$ sys/user.sh
$ git status
On branch master
Untracked files:
(use "git add <file>..." to include in what will be committed)
libr/asm/arch/arm/v35arm64/arch-arm64/
nothing added to commit but untracked files present (use "git add" to track)
```
```
$ rm -rf libr/asm/arch/arm/v35arm64/arch-arm64/
$ git checkout add-arch-arm64-dir-to-gitignore
$ git status
On branch add-arch-arm64-dir-to-gitignore
nothing to commit, working tree clean
$ …
```
=> Add libr/asm/arch/arm/v35arm64/arch-arm64 to gitignore

libr/io/p/io_ar.c
**Checklist**
Fix potential problems in ar io plugin. This handles the case where `strdup` returns `NULL` separately, just in case `strstr` can't handle `NULL` input. I did not see anything about that in the man pages.
=> Fix potential fault in ar ##io plugin

binr/r2r/r2r.c, binr/r2r/run.c
The lock subprocs_mutex is not released correctly when write (proc->killpipe[1], &r, 1) != 1 (the second break) in the function static RThreadFunctionRet sigchld_th(RThread *th). Also, the lock could be released before exit (-1); for better resource management and code symmetry.
This PR is to fix them. Thank you for your checking.
=> Fix unreleased locks

preconfigure.bat
Currently the `preconfigure.bat` file only looks at the community edition
and the Enterprise edition of VS 2019. This change adds Professional and BuildTools 
edition to the search.
**Checklist**
The `preconfigure.bat` scripts is looking for a heap of tools needed in order to build radare2 on Windows. One of such tools is the [Microsoft C++ Compiler](https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160#developer_command_file_locations) which can be included in the environment of your current console executing the `vcvarsall.bat` file. The `vcvarsall.bat` file can be located in a few different places depending on your edition of Visual Studio. This change looks at the other two default locations in addition to the two locations …
=> Add path to vcvarsall.bat from VS 2019 Professional

libr/main/rasign2.c, man/rasign2.1, test/db/tools/rasign2
**Checklist**
This is a work in progress. I need to update the man page and add tests.
This is a hack to add initial support for .a (ar archive files of .o object files) to rasign2 without having openmany support in core. An even bigger hack is using a new `RCore` for each object file. But the following basic algorithm in pseudocode did not work.
```
core = r_core_new ()
for (objectfile in archive) {
r_core_file_open (core, objectfile, 0, 0)
r_core_bin_load (core, NULL, UT64_MAX)
file_functions (core)
create_signatures (core)
r_core_file_close_all_but (core) # closes the objectfile?
}
output_signatures (core)   
```
So let me know if there is a better way. This is a stop gap until `r_core_file_open_many` is fixed anyways.
=> Support .a files in rasign2 ##signatures

libr/cons/cons.c
**Checklist**
Got a segfault in `r_cons_flush` while working on a rasign2 feature. The new feature never uses `RCore` and was segfaulting when `r_cons_flush` was being executed but there was nothing to be printed. I think this is the correct fix, but I don't know r_cons well, so feel free to correct me.
=> Fix potential NULL deref in r_cons_flush

libr/core/cmd_print.c, libr/core/disasm.c
* Rename locals and struct members to be consistent with new function signature
* Remove some duplicate locals and replace with struct members
* Move loop counters to loop scope and remove unused counters
* Move variable declarations and assignments to more relevant locations
* Collapse several nested, confusing, or redundant logic branches
* Add ds_offset(), ds_bufat(), and ds_left() macros to consistently track buffer information
* Add error handling to r_io_nread_at() call in cmd_print.c
* Change formatting
**Checklist**
Follow-up to https://github.com/radareorg/radare2/pull/19112, which was slightly rushed to make the 5.4.2 release. All functionality changes were made there, but there was not enough time to do some desired refactoring. Many of the most confusing points …
=> Minor refactors in disasm.c, primarily r_core_print_disasm() ##refactor ##asm

libr/hash/md5.c, libr/hash/md5.h, libr/hash/state.c
The other symbols (e.g. SHA1) are renamed with a r_ prefix, but the
MD5 symbols are not.
**Checklist**
=> Rename MD5 symbols to prevent OpenSSL collision

libr/main/rasign2.c
**Checklist**
Noticed on larger signature files that `rasign2 -S` would prompt and mess up the terminal. This should fix that.
I also notices rasig2 couldn't open /usr/libx32/libc.a even though it has 0644 perms. So I tried to change flags on the open command but it didn't work... I will look into it more later.
=> Use non-interactive RCore in rasign2 -S

libr/anal/flirt.c
**Checklist**
FLIRT does not run over functions that have debugging symbols. Even if the function has said symbols FLIRT scanning can still be useful, hence I'm uncommenting the check.
=> Scan with FLIRT regardless of the function being unknown

binr/r2r/r2r.c, binr/r2r/run.c
=> Show instruction and bytes when failing asm tests ##tests

libr/cons/cons.c, libr/core/cmd.c, libr/core/visual.c, libr/include/r_cons.h, libr/include/r_core.h
When a server is started as a background task, the console will remain silent until the server stops. This is undesirable because the intent of running the server in the background is to be able to keep working in radare while the server is running.
**Checklist**
=> Move the console flushing decision to the console context

libr/bin/format/pe/pe.c, libr/bin/format/pe/pe.h, libr/bin/p/bin_pe.inc, libr/socket/socket.c, test/db/formats/pe/65535sects
Create a couple of test bins for the 32 and 64bit targets using /GS with msvc
https://docs.microsoft.com/en-us/cpp/build/reference/gs-buffer-security-check?view=msvc-160
**Checklist**
=> Detect canary on statically linked RT and stripped PEs ##bin

libr/bin/dwarf.c
hdr->file_names is set to NULL.
However, the corresponding count variable is not set to zero.
It might stay on a non-zero value and
cause the code in line_header_fini() to dereference the NULL pointer.
Setting hdr->file_names_count to zero solves that issue.
**Checklist**
=> FIX #19149: Prevent NULL pointer dereference in line_header_fini()

libr/core/cmd.c, libr/core/cmd_api.c, libr/core/cmd_cmp.c, libr/core/cmd_debug.c, libr/core/cmd_write.c, libr/core/core.c, libr/include/r_cmd.h, libr/include/r_core.h, libr/include/r_util/r_str.h, libr/util/str.c, test/db/cmd/cmd_alias, test/db/cmd/cmd_print
**Checklist**
The alias system up to this point has been pretty bare-bones and stored as string arrays, leading to slow lookups and incorrect behavior with commands that use raw bytes like `pr`. Aliases are now stored in a hashtable mapping a string key to a structure with a data buffer, size, string flag, and command flag. Aliases can now store both strings and raw bytes. To support this, API functions have been added for running commands and getting the raw output, and escaping unprintable characters in a buffer. The alias API is also greatly expanded, making it easier to work with in the future.
=> Add r_core_cmd_tobuf() and overhaul alias system

libr/core/cmd.c, libr/core/cmd_api.c, test/db/cmd/cmd_alias
**Checklist**
Alias string detection now considers presence of non-ASCII characters in addition to null byte locations when determining if data is an unterminated string. e.g. `\x90\x90\x90` is no longer incorrectly considered an unterminated string. Didn't get picked up by other tests because they contained nulls, which caused the string detection to recognize that they were bytes.
=> Improve alias string detection

test/db/anal/arm, test/db/asm/arm_32, test/db/asm/arm_64, test/db/asm/x86_32, test/db/asm/x86_64, test/db/cmd/cmd_af, test/db/cmd/cmd_i, test/db/cmd/cmd_print, test/db/cmd/cmd_table, test/db/cmd/feat_grep, test/db/formats/mangling/swift, test/db/tools/rabin2, test/db/tools/radiff2, test/db/tools/ravc2
**Checklist**
We have some tests that got fixed but are still marked as broken. A few are still left that are only broken on specific platforms, so they still show up as fixed in r2r outside those platforms.
Additionally, some bad x86_32 tests have been changed to correctly track problems like failing to reject `rep` prefixes with non-string instructions.
=> Mark fixed tests as not broken and change incorrect x86_32 tests

libr/util/str.c
**Checklist**
`r_str_firstbut_escape()` now no longer reads past the string terminator when the given string ends with a single backslash. In the bad code, this occurs because when `p` points to `"\\\0"`, `p` is incremented once explicitly (now pointing to "\0"), but then again implicitly in the loop increment (now pointing into uninitialized memory), before the loop condition triggers, dereferencing this bad pointer.
The function now explicitly checks if `p` points to a null terminator, and if it does, uses `break` instead of `continue`.
=> Fix overread in r_str_firstbut_escape() when string ends with a single backslash

libr/bin/demangle.c, libr/bin/mangling/swift-sd.c, libr/core/cbin.c, libr/core/cconfig.c, libr/core/cmd_info.c, libr/include/r_bin.h, libr/main/rabin2.c, man/rabin2.1, test/db/cmd/cmd_i, test/db/formats/mangling/swift, test/db/tools/rabin2
- May fix the macos testsuite as long as latest macOS comes with libSwift
**Checklist**
=> Improve swift demangler and add bin.demangle.trylib config ##bin

libr/core/cmd.c, libr/core/cmd_api.c, libr/core/cmd_cmp.c, libr/core/cmd_debug.c, libr/core/cmd_write.c, test/db/cmd/cmd_alias
* Add proper hashtable functions in RCmdAlias to prevent memory leaks
* Fix off-by-one error in alias name processing
* Don't allow 0-length aliases
* Fix memory leak in r_cmd_alias_set_raw() when malloc fails and add null checks to other alias set functions
* Document intended use of strlen() result for buffer size
=> Improve alias hashtable usage and remedy memory leaks

libr/bin/dwarf.c
=> Fix oobread crash in dwarf parser with non-null terminated strings ##crash

libr/core/rvc.c
**Checklist**
This uses r_file_new instead of r_str_new to create file paths.
=> Use r_file_new in rvc.c

libr/bin/dwarf.c
=> Fix oobread crash in DWARF's parse_die (tests_64926) ##crash

libr/util/signal.c
**Checklist**
env:
Linux junchao-pc 4.19.0-13-loongson-3 #1 SMP Tue Aug 17 01:57:07 UTC 2021 mips64 GNU/Linux
When I compile with the latest master branch code on the mips（loonsong 3a4000） platform, I get the following error：
```
[util 143] CC debruijn.c
[util 144] CC log.c
[util 145] CC getopt.c
[util 146] CC table.c
[util 147] CC utf8.c
[util 148] CC utf16.c
[util 149] CC utf32.c
[util 150] CC strbuf.c
[util 151] CC lib.c
[util 152] CC name.c
[util 153] CC spaces.c
[util 154] CC signal.c
[util 155] CC syscmd.c
[util 156] CC udiff.c
[util 157] CC bdiff.c
signal.c:19:17: error SIGSTKFLT? undeclared here (not in a function); did you mean ?SIGSTKSZ??
{ "SIGSTKFLT", SIGSTKFLT },
^~~~~~~~~
SIGSTKSZ
make[2]: *** [/home/junchao/work/plugin/radare2/libr/../global.mk:42?signal.o] …
```
=> Fix signal definition error on MIPS platform

libr/anal/var.c, libr/include/r_anal.h, test/unit/test_anal_var.c
**Checklist**
Ads API to r_anal to serialize and deserialize variable information. This is very similar to the serialization found in #19353 but put in RAnalVar so plugins can benefit from it. Additionally, I found it helpful to serialize the `isarg` value, so that is in there now too.
Let me know if I named things stupid, I am happy to change it.
Once this is merged I will rebase #19353 and update it to use the RAnalVar serialization API instead of inviting it's own.
=> Add serialization API for vars ##anal

libr/anal/dwarf_process.c, libr/bin/dwarf.c, test/db/cmd/cmd_flags
=> Use r_str_ndup in another bound check in dwarf ##bin

libr/core/anal_tp.c, libr/core/cmd_anal.c
* aaa takes 1.1s instead of 2.1s in /bin/ls
**Checklist**
=> Optimize 'aaft' command, still far from done ##anal

libr/anal/sign.c, libr/core/cmd_zign.c, libr/include/r_sign.h, libr/include/r_util/r_hex.h, libr/util/hex.c, test/unit/test_hex.c
**Checklist**
This is two commits. One creates `r_hex_str2bin_until_new` see the unit tests for examples. Works like so:
```
ut8 *out;
char *str = "010203_NOTHEX";
int len = r_hex_str2bin_until_new (str, &out);
// len == 3
// *out == "\x010203"
// str + len * 2 == "_NOTHEX"
free (out);
```
The second commit uses the first. It simplifies the byte signature (de)serialization/parsing. It bothered me that `za` commands and sdb value deserialization used different parsing functions. Now they are put in the same place.
This also means bytes are stored in sdb files as `|b:0102030405:ffffffffff` now. Previously, serialized signatures looked like `|s:5|b:0102030405|m:ffffffffff` and required the `R_SIGN_SIZE` ('s') and `R_SIGN_MASK` ('m') enums. Those values are now free to be used …
=> Simplify deserialization of byte ##signatures

test/unit/test_hex.c
**Checklist**
Hopefully, this fixes the disabled tests. I think I messed up the pointer logic and so the test was using uninitialized memory before.
=> Fix broken unit test in hex

libr/include/r_vector.h, libr/util/vector.c, test/unit/test_vector.c
**Checklist**
Ads `r_pvector_bsearch` which will perform a binary search on a `RPVector` iff the vector is sorted by `cmp`. Otherwise, undefined results.
=> Add binary search alg to pvector ##util

libr/core/agraph.c
**Checklist**
Fixes crash in `VV`. In `VV` hit `,` to toggle `grpah.few`. Then hit `q` to get to `V` mode, then hit `V` to go back to `VV`. You will segfault.
Crash happens because `node->color` is used even if it's `node == NULL`.
I don't think there is any security impact to this finding. It would only be a DOS when you try to `free (0x18)`. I don't see how a DOS in `VV` with `graph.few` would break any automated r2 things (like auto-triage with r2).
=> Fix use of NULL obj in graph

libr/bin/dwarf.c
**Checklist**
This change adds a bounds check to the print used to display the DW_AT_language attribute. Currently, there is no check on the index, which can lead to memory disclosure or crashes. This print is used in `rabin2 -d`.
I've added a bounds check on the maximum language index, as well as a check that makes sure the language is defined.
I originally found the bug with a fuzzer and used it to create the following synthetic example file:
```bash
#!/bin/bash
echo "int main(){}" | gcc -x c - -o example
echo -n "ATQAEwcTBxMHAAAA" | base64 -d > tmp_abbrev
echo -n "IgAAAAQAAAAAAAgBQUFBQUFBQUEVAAAAAAAAAAwAAAAAAAAAAAA=" | base64 -d > tmp_info
objcopy --add-section .debug_info=tmp_info example
objcopy --add-section .debug_abbrev=tmp_abbrev example
rm tmp_*
```
The test file …
=> Fix missing bounds check in dwarf_langs

libr/core/agraph.c
**Checklist**
This pull does two things. It upgrades `graph.few` to display the nodes that reference the current node (see changes to `cur_points_to_bb`). 
It also fixes a minor bug in `graph.few`. Changing nodes with tab did not refresh the nodes on the screen. I refactored the code a bit so that any change to seek when `graph.few` was enabled would result in a refresh.
=> Show prev nodes in graph.few ##graph

sys/install.sh, sys/meson.py, sys/termux.sh, sys/user.sh
Some users' master branch does not track upstream, causing `git pull` in install scripts to fail when building on master with the error "There is no tracking information for the current branch". Adding the repository URL and specifying the master branch prevents this failure, allowing master to be updated automatically during install without tracking information.
=> Use remote URL for git pull in install scripts ##build

libr/core/agraph.c
**Checklist**
I am not very familiar with this code, so please double check me. 
I had `r_agraph_add_edge` warning because `v` was `NULL`.  If `v` being `NULL` is an error, then an `else` should be added to the code to warn. Otherwise, i think it is good to merge.
=> Fix NULL node warning in VV ##graph

libr/meson.build
**Checklist**
Currently when using the `pe` plugin pemixed is not enabled, however in the non-Meson build it will be enabled as part of the default configuration.
=> Add bin_xtr.xtr_pemixed for PE user plugin ##build

libr/core/cmd_flag.c, libr/core/core.c, libr/core/vmenus.c, libr/include/r_util/r_new_rbtree.h, libr/include/r_util/r_spaces.h, libr/util/new_rbtree.c, libr/util/spaces.c
=> Liberate RSpaces from old rbtree api

libr/bin/format/p9/p9bin.c, libr/bin/format/p9/p9bin.h, libr/bin/p/bin_p9.c
**Checklist**
Currently support for Plan 9 binaries is limited to i386 and even then
it doesn't work properly (certain sections won't load, the base address
is wrong, etc.)
With these changes, all architectures including ones from 9front are
supported.
=> Improve Plan 9 support ##bin

libr/bin/p/bin_p9.c
**Checklist**
All function and data symbols are now parsed and loaded into radare2. As
well, the BSS segment is now also loaded as zeroed virtual memory.
=> Add Plan 9 symbol parsing ##bin

libr/util/str.c, test/db/cmd/feat_grep
**Checklist**
Add check for empty key in `r_str_replace`, fixing an infinite loop when `scr.highlight.grep=true` and the user runs a grep command with an empty string.
=> Fix #19452 - Highlight grep with empty search string causes infinite loop ##util

libr/core/cmd.c, libr/core/core.c
=> Fix r2pipe.cmd("Z") when command fails returns no output ##r2pipe

libr/asm/asm.c
* Fixes anal disasm warnings and related problems
**Checklist**
=> Use null plugin when using unexistent asm plugin ##asm

libr/asm/arch/arm/armass64.c, test/db/asm/arm_64
=> Fix #19464 - incorrect assembly for adrp on arm64 ##asm

libr/anal/p/anal_arm_cs.c, test/db/anal/thumb, test/db/esil/arm_16
=> Fix #18967 - Fix emulation for the mov-pc thumb instruction ##esil

libr/core/linux_heap_glibc.c
**Checklist**
Gentoo keeps its libc in /lib64/libc.so.6 which breaks detection of a map with libc in memory for heap analysis.
I added condition that searches not only for "/libc-" but also for "/libc." among memory map names.
Hope that looks about right, @trufae
=> Fix #19473 - Support libc filename w/o version for heap analysis

libr/bin/format/mach0/mach0_defines.h, libr/bin/p/bin_mach0.c, test/db/formats/mach0/objc
**Checklist**
Support the `DYLD_CHAINED_PTR_64_OFFSET` chained pointer format for the purpose of rebasing Mach-O binaries. This is the default when compiling `arm64` binaries on macOS Monterey on M1 architecture.
Depends on new test bin: https://github.com/radareorg/radare2-testbins/pull/69
(credit: https://github.com/rizinorg/rizin/pull/1996)
=> Support Mach-O DYLD_CHAINED_PTR_64_OFFSET format ##bin

libr/core/canal.c, libr/core/cmd_print.c, libr/core/disasm.c, libr/include/r_core.h
**Checklist**
#19112 fixed a problem where instructions would be cut off in some cases. This was done by reading more bytes into the buffer if it did not have enough bytes left for a full instruction. Unfortunately, the fact that instructions are intended to be cut off when using `pD` slipped by me and I misunderstood what was and wasn't intended behavior. I introduced a specific argument for this behavior, but it can actually be done only (and more correctly) by checking `count_bytes`.
The first commit fixes the problem and leaves the argument untouched, and the second commit removes the now-unused argument. I also changed the debug logging to use eprintf and made the debug flag macro more descriptive.
```
lazula@mint-desktop:~/radare2$ r2 -c 'pD 1' -qN -
0x00000000 …
```
=> Fix pD reading too many bytes and remove unused argument from r_core_print_disasm()

libr/include/r_search.h, libr/search/aes_find.c, libr/search/privkey_find.c, libr/search/regexp.c, libr/search/search.c, libr/search/search.h, libr/search/strings.c, test/unit/legacy_unit/search/test-regexp.c, test/unit/legacy_unit/search/test-str.c, test/unit/legacy_unit/search/test.c
**Checklist**
Trying to clean up the r_search API a bit.
A couple functions in r_earch.h were not used or were duplicates.
I moved the update functions into their own .h file to hide them from public use. They should only be used internally. I have not made this type of change in r2 before, so I probably am not doing it just right.
=> Cleanup public API for ##search

libr/anal/p/anal_8051.c, libr/asm/p/asm_8051.c
* Avoid compile+link the same code twice for asm & anal
**Checklist**
=> Disable the disassembler logic in the asm plugin for 8051

sys/install.sh, sys/meson.py, sys/termux.sh, sys/user.sh
**Checklist**
Follow-up to #19423. If there is an existing remote the user has tracking upstream, using the direct URL leaves the remote lagging behind and requires manual updating. Install scripts now check for an existing named remote before pulling from the direct URL, keeping the remote tracking aligned with the current `master` when updated by these scripts.
=> Check for an existing upstream remote in install scripts ##build

libr/core/cmd_search.c, libr/include/r_search.h, libr/search/bytepat.c, libr/search/search.c, libr/search/search.h
**Checklist**
Consider this a proposal, if you don't like it then don't merge.
Currently `cmd_search.c` searches using `r_search_update` with `core->blocksize` buffers. This means each mode of searching must keep state between `r_search_update` calls in order to find matches that span a `core->blocksize` boundary. This is not easy and some modes fail at it:
```
[0x00000000]> x 0x20 @0xf0
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x000000f0  4141 4141 4141 4141 4141 4141 4141 4141  AAAAAAAAAAAAAAAA
0x00000100  4242 4242 4242 4242 4242 4242 4242 4242  BBBBBBBBBBBBBBBB
[0x00000000]> /e /AB/
Searching 2 bytes in [0x0-0x201]
hits: 0
[0x00000000]> / AB
Searching 2 bytes in [0x0-0x201]
hits: 1
0x000000ff hit1_0 .AAAAAAAAAAAAAAAAABBBBBBBBBBBBBBBBB.
``` …
=> Add r_search_upate_read API ##search

libr/core/cconfig.c, libr/debug/p/debug_native.c, libr/debug/p/native/linux/linux_debug.c, libr/debug/p/native/linux/linux_debug.h, libr/debug/p/native/linux/reg/linux-loongarch64.h, libr/include/heap/r_jemalloc/internal/jemalloc_internal.h, libr/include/r_types.h, libr/include/r_util/r_sys.h
**Checklist**
Hello friends, recently Loongson released the LoongArch architecture processor, this patch is used to support radare2 can be compiled properly on loongarch.、
I'll be submitting a patch to support binary file analysis for the loongarch platform later.
You can view detailed information about LoongArch at the link below
[LoongArch-Documentation](https://github.com/loongson/LoongArch-Documentation)
=> add basic support for LoongArch

libr/include/r_search.h, libr/search/search.c
**Checklist**
The longest keyword was being computed every time an update was done. So for large files, with large keyword lists, a lot of computation can be saved by just remembering the longest keyword. So r_search should continue to function the same after this pull, it should just move faster.
Note: one of the longest variables used a `+1`, I am not completely sure why. Keeping state between update calls is a bit confusing. So I left the logic as is, it should work exactly the same. That is why one of the `longests` has a +1 and the other does not. I hope to pretty this code up further as I understand it better.
=> Add longest field to RSearch ##search

libr/search/regexp.c
**Checklist**
Searching for `/e /A*/` will cause an infinite loop. This fixes that and only allows regex matches that have a positive length.
=> Fix bug in regex searching ##search

libr/include/r_types.h
should fix this:
````
/home/runner/work/radare2/radare2/libr/..//libr/anal/p/anal_gb.c:484:29: warning: unknown conversion type character ‘l’ in format [-Wformat=]
```
=> Use I64x instead of llx format strings for mingw builds too ##windows

libr/include/r_types.h
**Checklist**
Add a few macros that eprintf the variable name and value. Very useful for speeding up debugging without worrying about format specifiers.
=> Add EPRINT macros for debug printing with variable name

libr/include/r_types.h
Missed the newline when writing the first one, so it was missing in all the copypastas. Also mark hex output more clearly with 0x and enclose strings with quotes.
Fixes feature added in #19525
=> Add newlines and hex markers to EPRINT macros

libr/core/cmd.c
**Checklist**
This is totally undocumented and makes e.g. `$1` do `s 1` if no "1" alias is defined but without recording it for `s-` as described in the issue. Now it just fails with "No such alias" as expected.
=> Remove undocumented and unlogged seek behavior when no alias match is found

libr/core/cmd_search.c, libr/core/core.c, libr/include/r_search.h, libr/search/regexp.c, libr/search/search.c, libr/search/search.h
**Checklist**
This moves `/e` command over to `r_search_update_read` and fixes a few bugs in `/e`. 
This fixes some bugs in `/e`.
* Less false negatives due to matches crossing buffer boundaries. This can still happen if a match is larger then 64 characters and it falls across a buffer boundary. This should be updated in the future so users can configure an expected largest match length.
* Prevent infinite loop when searching for a zero length match `/e /A*/`.
* Matches have a proper length.
This pull implements  a second callback system that should replace the first. When a match was found previously, the callback assumed the match length was equal to the keyword length. So a match of `/A{30}/` would be treated as a length of 5. The new callback accepts a size of match to …
=> Move /e to new search API ##search

.gitignore
`binr/` binaries belong in gitignore. This one was added in #19468
=> Add new r2pm binary to .gitignore

libr/core/disasm.c, test/db/cmd/cmd_ah, test/db/cmd/feat_astabs
=> Optimize and fix heap overflow in asm.tabs using RStrBuf ##crash

.github/workflows/ci.yml, libr/asm/p/asm_x86_nasm.c, libr/bin/format/wasm/wasm.c, libr/core/cmd_anal.c, test/db/cmd/cmd_af
* Find function entrypoints and creates a single basic block function
* Useful for fast initial analysis instead of aaa (30min vs 5s)
* Handy to get xrefs context in function boundaries
**Checklist**
=> Initial implementation of the 'aafs' command ##analysis

libr/include/r_types.h, shlr/sdb/src/types.h, shlr/winkd/transport.h
Macro redefinition is messing with CI, this should fix it. Not sure why the CI on my eprintf changes didnt show these errors when I changed the eprintf definition in `r_types.h` to have spaces, but checking for eprintf already being defined should prevent it.
=> Kill HAVE_EPRINTF, replace with ifndef eprintf

libr/core/cmd_search.c, libr/include/r_search.h, libr/search/search.c
**Checklist**
When two maps are next to each other, may as well search them in one go. This will make finding matches that live on the boarder between maps simpler.
**edit**
I went ahead and made this an API to search maps. That will ease the burden on the caller for setting up a search.
=> Add r_search_maps to ##search

libr/anal/p/anal_loongarch_gnu.c
Fixes the broken test referenced [here](https://github.com/radareorg/radare2/pull/19515#issuecomment-1000566119)
=> Fix heap overread in loongarch when len < 4 ##anal

INSTALL.md, README.md
Small changes after the big recent update.
* Improve `r2env` and `r2pm` usage instructions
* Remove missing repology badge
* Don't repeat current packaged version after badge
=> Minor updates to README.md

libr/io/io_bank.c
* See havoc4 bin for reproducer
* Reported via huntr.dev by 'Cen Zhang'
**Checklist**
=> Fix use-after-free in iobank rbtree usage ##io

libr/core/disasm.c
**Checklist**
This fixes what I think is a bug, but maybe I am not thinking about it properly?
For a `call sym.somewhere` you can use `ahc sym.other` to set the suggested location where the call actually lands. Then in visual modes you can get promps that will fast jump to the `sym.other` location.
When you have a `call rax` and you know `rax` is always holds `sym.other` you can *not* do `ahc sym.other` because `ds_print_core_vmode` will de-reference `sym.other`. So for `ahc` to work in this case, you must find a location that points to `sym.other`. In static analysis, such a location may not exist.
I feel like `ahc` means "use this jump location". I see the merit of de-referencing in some situations but I feel like a different command should be used.
So this pull "fixes" …
=> Fix fast jump with ahc on register calls ##visual

libr/core/cconfig.c, libr/core/cmd_log.c
=> Add scr.theme and Lt commands as alias for 'eco' ##cons

libr/bin/format/mach0/mach0_defines.h, libr/bin/p/bin_mach0.c, test/db/formats/mach0/objc
**Checklist**
Add support for Mach-O DYLD_CHAINED_PTR_ARM64E_USERLAND24 pointer format for the purpose of rebasing only (for now).
This is the default format when compiling arm64e binaries on macOS on M1.
The added test depends on https://github.com/radareorg/radare2-testbins/pull/70
=> Add support for rebasing ARM64E_USERLAND24 chained format ##bin

libr/anal/fcn.c, libr/anal/type.c, libr/core/canal.c, libr/core/cbin.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/include/r_list.h, libr/include/r_types.h, libr/util/list.c, libr/util/syscmd.c
* Adds _inplace() variant to avoid creating a new list
* Speedups aafs, aflm, pd, aflt and aflj
**Checklist**
=> Rewrite r_list_uniq with a faster algorithm ##core

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h, libr/bin/format/mach0/mach0_defines.h, libr/bin/p/bin_mach0.c, test/db/anal/classes, test/db/cmd/cmd_tc, test/db/formats/mach0/fatmach0, test/db/formats/mach0/objc
**Checklist**
Modern arm64 / arm64e Mach-O binaries (used in iOS since 14.x and macOS on M1) have no dyld bind opcodes. Information about bound symbols is instead stored as part of the "chained fixups" (the same used for rebasing).
This change does:
- walk the chained fixups if no dyld bind opcodes are found
- centralize the iteration of chained fixups so that the same code is used when rebasing and binding: the `iterate_chained_fixups()` function now handles the underlying quirks and exposes a more abstract interface to it
The most visible effect of this change is that now modern arm64 / arm64e Mach-O binaries have information about Objective-C parent classes even when they are imported, and that's what i changed in the relevant test cases in order to test this.
NOTE: …
=> Parse relocs from Mach-O chained binds if no opcodes ##bin

libr/core/cmd.c
Fix a buffer overread when the input ends with a backslash
=> Ignore trailing backslash in unescape_special_chars()

libr/bin/dbginfo.c, libr/bin/format/elf/elf.c, libr/cons/grep.c, libr/core/casm.c, libr/core/cmd_anal.c, libr/core/cmd_search.c, libr/core/disasm.c, libr/core/esil2c.c, libr/util/format.c
All leaks from `sys/sanitize.sh && r2r test/db/esil`.
The grepbuf change fixes a poorly-designed bandage fix. The removed block, when hit, caused a 20-byte memory leak when `buffer_len == 0 && buffer == NULL`.
=> Fix leaks in esil tests

libr/include/r_types.h
Give char output single quotes and hex value, plus `%p` option for checking addresses, etc.
=> Improve EPRINT_CHAR() and add EPRINT_PTR() for arbitrary addresses

libr/bin/p/bin_dyldcache.c
**Checklist**
This change improves parsing of dyld caches, especially for macOS caches (but modern iOS caches also benefit from this), in 3 ways:
- handle random mixed presence of `/Versions/XXX` in framework paths
- when parsing Objective-C classes where metadata are optimised, in case the `__obc_scoffs` section isn't present, derive the base of method names by finding the "magic selector" (🤯)
- compute the base of symbols from the `__LINKEDIT` vm address of a given sub-bin, instead of making wrong assumptions (on multi-file caches the assumption was symbols are in the highest-mapped file)
=> Improve dyld caches parsing ##bin

libr/core/core.c
**Checklist**
A temp file is created, through `r_file_mkstemp` if the file name is `NULL` or starts with `*`. The temp file should always be deleted but the delete check did not cover the case where the filename is starts with `*`.
This would cause commands like `toe` to leave temp files around needlessly.
=> Fix editor failing to delete tmp files

test/db/io/resize
**Checklist**
Looks like `i` on an empty file returns size `0x0` instead of `0`. This was causing the test two tests to fail. So I updated the tests because I think `0x0` is more consistent.
=> Fix resize tests

libr/include/r_util/r_file.h, libr/util/file.c
**Checklist**
This simplifies `r_file_mkstemp` and fixes a couple bugs. If this is accepted then #19598 can just be closed.
Bugs:
On my system the macro `defined(__GLIBC__) && defined(__GLIBC_MINOR__) && 2 <= __GLIBC__ && 19 <= __GLIBC__MINOR__` does not seem to correctly detect the presence of `mkstemps`. 
The fallback to `mkstemp` causes bugs when a suffix is used. Given `r2.XXXXXX.h`, the alg truncates the name to `r2.XXXXXX` to be acceptable to `mkstemp`. This then returns a file descriptor for `r2.XXXXXX`. Afterward the alg ads the suffix back in, returning a filename of `r2.XXXXXX.h`. So running `toe struct.foo` will populate `r2.XXXXXX` file with the known `foo` struct and open the new file `r2.XXXXXX.h` in the text editor.
Also, previously the sandbox was not used …
=> Update r_file_mkstemp to work with sandbox

libr/core/disasm.c, test/db/cmd/cmd_pd2
=> Fix #15473 - Align meta dwords in the middle of instructions ##disasm

test/db/anal/x86_16
The last test in #19593 was missing RUN. I added this, fixed the spacing in the EXPECT, and marked it as broken since it is.
Relevant incorrect line:
```
-|           0000:0005     9a0d000000     lcall funcA
+|           0000:0005     9a0d000000     lcall 0, funcA
```
=> Add missing RUN to last x86_16 test and mark broken

libr/cons/cons.c, libr/core/cmd.c, libr/include/r_cons.h, libr/include/r_core.h
This new function makes it easier to get help text for specific commands in color. By avoiding grep and working directly on the help text array, we can pinpoint the exact line we want by using strcmp and borrowing the string pointers to craft a custom help text array. The only allocation needed is done to append spec to cmd if `spec != 0`.
```
/* Impossible to get color due to color codes interfering */
r_core_cmd0 (core, "pd?~^\| pdl");
/* These 2 are interchangable - spec makes it easier to check for ? in one place */
r_core_cmd_help_match (core, help_msg_pd, "pdl");
r_core_cmd_help_match_spec (core, help_msg_pd, "pd", 'l');
/* Get help for an appropriate subcommand */
r_core_cmd_help_match_spec (core, help_msg_pd, "pd", input[1]);
```
=> Add r_core_help_match() to get help for a specific command

libr/core/canal.c, libr/core/cmd_print.c, libr/core/disasm.c, libr/include/r_core.h, test/db/cmd/cmd_pdu
**Checklist**
Initial implementation of `pdu` commands. All of the proposed commands have been implemented except for `pdue` and they all have tests.
`r_core_print_disasm()` has been modified to add condition type and pointer arguments. Internally, each condition type can be cast from void* and placed in their own special variable. To add a new condition type, add a new entry to the condition type enumeration in r_core.h and handle it in both cmd_pdu() and r_core_print_disasm()
=> Implement pdu

libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_arm_v35.c, libr/anal/p/anal_x86_cs.c
**Checklist**
This PR fixes the an issue where `bnd jmp` instructions had ESIL corresponding to `repne jmp` because Intel MPX changed the `repne` prefix to mean `bnd` on control flow instructions. it was a security thing that no longer does anything so we too will ignore it 
It also fixes the `cmn` instruction ESIL which is supposed to compare the negative of the register value to the second operand, but instead was being treated as a normal cmp.
=> fix esil for bnd jmp x86 instrs and cmn arm instrs ##esil

libr/anal/fcn.c, libr/anal/var.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/include/r_anal.h
**Checklist**
I noticed `r_anal_var_count` is almost always called multiple times to get a count of all local or argument variables. Additionally, the function unnecessarily allocates/de-allocates a list. So I created a simpler API to get that information. It should run slightly faster and clean up some code.
=> Simpler var counting API

libr/util/format.c
=> Fix: Mark r_print_format globals as TLS ##util

config-user.mk.acr, libr/Makefile
* Installation creates some more symlinks now
**Checklist**
=> Fix #18621 - Specify ABI version to be X.Y instead of X.Y.Z ##build

libr/core/cmd.c
=> Fix parsing of 'ra?' and 'r0x' subcommands ##shell

libr/core/cmd_print.c
**Checklist**
- [ x] Mark this if you consider it ready to merge
When the user try to get a json output of a negative relative offset in the `px` command, it will always get a fixed `256` data block.
This fix will rely in the `core->num->value` instead the `core->blocksize` when passing it to `r_print_jsondump` making the output correct.
How to reproduce:
`xj -10`
=> Fix Negative Offset in Hexdump Json Output

libr/anal/p/anal_x86_cs.c, test/db/esil/x86_64
**Checklist**
The ESIL code of the x86 instruction `pop [rsp]` was wrong, because the calculated memory destination was the value of `rsp` **before** the `pop` instruction; this is wrong behaviour according to the Intel manual:
If the ESP register is used as a base register for addressing a destination operand in memory, the POP instruction computes the effective address of the operand after it increments the ESP register.
=> Fix order of operations in the ESIL code of pop with memory operand

.github/workflows/release.yml
This pull request implements "Automatically publish artifacts in releases" from #19687.
It has been implemented all in one file, alternatively "Download artifacts" can be moved as script in `sys`.
Also using [dawidd6/action-download-artifact@v2](https://github.com/dawidd6/action-download-artifact#readme) has been discarted to reduce external code execution during release creation.
=> Partial #19687: Add release github actions workflow

meson.build
**Checklist**
Allow to override build date with `SOURCE_DATE_EPOCH`
in order to make builds reproducible.
See https://reproducible-builds.org/ for why this is good
and https://reproducible-builds.org/specs/source-date-epoch/
for the definition of this variable.
This date call only works with GNU date. *Is MacOS-support required?*
Also use UTC to be independent of timezone.
This is the equivalent of 6b260b87c3345568ebeddf57fbe95c864ee8baf2 for meson.
This PR was done while working on [reproducible builds for openSUSE](https://en.opensuse.org/openSUSE:Reproducible_Builds).
=> Allow to override build date with SOURCE_DATE_EPOCH

libr/anal/jmptbl.c
**Checklist**
If a hint is used then the code returns without free'ing `bb_buf`. This moves the early return for a code hint to just before `bb_buf` allocation, so no extra free case needs to be done.
=> Prevent leak when jumptable has size hint ##anal

libr/io/io_bank.c, libr/util/new_rbtree.c
* That's a workaround, proper fix will come later
* Reproducer: bins/fuzzed/iobank-crash
* Reported by Akyne Choi via huntr.dev
**Checklist**
=> Prefer memleak over UAF in io.bank's rbtree bug ##crash

meson.build
**Checklist**
As a follow-up of #19699,
Rework `SOURCE_DATE_EPOCH` usage in meson to be portable
to make @rofl0r and FreeBSD users happy.
Please test.
=> Rework `SOURCE_DATE_EPOCH` usage be portable

libr/cons/cons.c
=> Fix Windows console mouse disable escape sequence ##windows

libr/include/r_io.h
- Argument  **r_ptrace_data_t** needs to be **int** instead of **void**  on FreeBSD ptrace(2)
- Then **R_PTRACE_NODATA** should be initialized as **0** instead of **NULL**
=> Fix #19687 - Correct types definitions for ptrace(2) on FreeBSD ##io

libr/bin/p/bin_dex.c
* Reported by Google clusterfuzz
* Reproducer: clusterfuzz-testcase-minimized-ia_fuzz-5227091270959104
=> Early break when parsing corrupted DEXs to avoid DoS ##crash

libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_arm_v35.c, libr/anal/p/anal_x86_cs.c
This PR fixes `sdiv` so that it uses the signed divide operator `~/`. It also sets the dst register to 0 when the divisor is 0 which is what aarch64 does apparently.
https://armkeil.blob.core.windows.net/developer/Files/pdf/graphics-and-multimedia/ARMv8_InstructionSetOverview.pdf
It also adds ESIL for the `cwd` and `cqo` x86 instructions which sign extend rax into rdx.
=> Sdiv Fix ##esil

.github/workflows/android.yml, .github/workflows/apple.yml, .github/workflows/ci.yml, .github/workflows/freebsd.yml, .github/workflows/linux.yml, .github/workflows/release.yml, .github/workflows/windows.yml, .gitignore, sys/download-artifacts.sh
This pull request responses to #19687 and improves CI changes performed in #19695.
Features:
1. Adds a new script in `sys/download-artifacts.sh` to download all artifacts into `dist/artifacts` using the [gh cli tool ](https://github.com/cli/cli#readme).
2. Renames all CI artifacts names to match the job name that publishes it.
3. Move jobs from CI workflow to external workflows (like it was with freebsd and windows)
4. Add 30 days retention policy to all generated artifacts (not to the release assets)
Any comment or feedback will be welcome if any folder or change don't match with the philosophy of the project.
=> Partial #19687: Create download artifacts script and other CI changes

binr/r2r/run.c
One more from the threading change. Cleaning up memleaks via tests needs r2r to be clean.
=> Free subprocess thread lock in r2r

libr/anal/fcn.c
This should be the culprit breaking some tests for pull #19738.
=> Fix uninitialized switch shift variable

libr/core/cmd_anal.c, test/db/cmd/cmd_agf
The agfm command will handle switches now. So the following r2 commands will produce the graph below:
```
e asm.arch=x86
e asm.bits=64
s 0x100
wx 42000000000000004e000000000000005a00000000000000660000000000000072000000000000007e00000000000000
s 0x10
wx 554889e5897dfcc745f8000000008b45fc89c14889ca4883ea0548894df00f8756000000488b45f0488b0cc500010000ffe1c745f800000000e943000000c745f801000000e937000000c745f802000000e92b000000c745f803000000e91f000000c745f804000000e913000000c745f805000000e907000000c745f8ffffffff8b45f85dc3
af
agfm
```
```mermaid
stateDiagram-v2
state "ENTRY: 0x10" as _0x10
state "0x34" as _0x34
state "0x42" as _0x42
state "0x4e" as _0x4e
state "0x5a" as _0x5a
state "0x66" as _0x66
state "0x72" as _0x72
state "0x7e" as _0x7e
state "0x8a" as _0x8a
state "0x91" as …
```
=> Handle jump tables in agfm ##anal

libr/bin/format/ne/ne.c
Function [__func_name_from_ord](https://github.com/radareorg/radare2/blob/master/libr/bin/format/ne/ne.c#L51) does not perform a NULL check on module which can result in a segfault with a specially crafted binary.
A specially crafted binary will result in crashing radare2 as shown in the image below.
=> Adding NULL Check to __func_name_from_ord to prevent segfault 

libr/anal/p/anal_arm_v35.c
The `arm.v35` plugin has two types of "shifts" in `InstructionOperand`, `shiftType` and `extend` 
```c
struct InstructionOperand {
...
ShiftType shiftType;
bool shiftValueUsed;
uint32_t shiftValue;
ShiftType extend;
...
}
```
However AArch64 can have operands that have both a shift AND an extension. For these operands instead of having the shift in `shiftType` and the extension type in `extend`, `shiftType` contains the extend type and the left shift is implied and has its value in shiftValue. Previously the shift type would be missed as in the ESIL expression
```
str w16, [x12, w15, sxtw  0x2]    ->    w16,x12,2,w15,,+,=[4]
```
instead of 
```
str w16, [x12, w15, sxtw  0x2]    ->    w16,x12,32,2,w15,<<,~,+,=[4]
```
This is really confusing and I may make a PR to the v35 …
=> Fix operands that have an extension plus a shift

libr/cons/grep.c, libr/include/r_cons.h, test/db/cmd/feat_grep, test/db/tools/ravc2
Fixes #18690.
Grep `!`, `^`, and `$` - negation, begin, and end are now tracked per-term. Logic has been modified to cope with these changes, allowing the user to string multiple simple grep expressions together as described in the issue. 2 grep tests have been fixed.
This patch contains a breaking change - `~!a,b,c` must now be `~!a~!b~!c`, since b and c have their own negation flag now instead of a single negation applying to all terms. See ravc2 tests.
=> Make grep begin, end, and negate properties per-word

libr/core/cmd.c, libr/fs/fs.c, libr/util/file.c, libr/util/syscmd.c, test/db/cmd/cmd_ownshell
Input for `cmd_ls()` changed without being accounted for. The command string changed from `"ls"` to `"l"`, moving the input pointer back.
=> Fix problems in `l` command

libr/cons/cons.c
`strstr` return value does not act like `strcmp`. Went unnoticed until it was needed for an upcoming PR.
=> Fix inexact r_core_cmd_help_match()

libr/core/cmd_cmp.c, libr/util/file.c
Clean up cp command implementation and emit output in `r_file_copy()` when src and dst are the same instead of failing silently.
=> Refactor `cp` command

test/db/archos/linux-x64/dbg_maps, test/db/cmd/feat_redirect, test/db/tools/rabin2
Fix #19775.
Line counts had to be changed since the internal `~?` seems not to count empty lines, while the external `wc -l` does.
The modified linux-64 tests are all broken anyway, but now whenever they are fixed the line count can simply be accurate to `~?` rather than `wc -l`.
=> Remove usage of wc and awk from tests

libr/core/cmd.c
Fix error message for `yt`, improve help output with `r_core_cmd_help_match()` and provide support for aliases.
=> Fix `yt` command

test/db/cmd/cmd_fs, test/db/cmd/cmd_print, test/db/cmd/cmd_project
Update the testsuite to not leave behind files that show up in `git status`. Wont happen in practice until the ytf fix is merged, but isnt blocked by it. The order doesnt matter once both are in.
=> Clean up files in tests

libr/core/cmd_meta.c, libr/util/file.c
* Speedup large loading times for files with DWARF info
* Only speedups the cases where the files doesnt exist
* Need to refactor file_slurp_random_line() into str for better times
=> Cache file_exists when iterating over the source files ##bin

libr/core/core.c
```
$ r2 test/bins/elf/ls
[0x00005ae0]> e scr.prompt.flag
false
[0x00005ae0]> e scr.prompt.flag=1
[entry0]> s +1
[0x00005ae0]> s -1
[entry0]>
```
```
$ r2 test/bins/elf/ls
[0x00005ae0]> e scr.prompt.flag
false
[0x00005ae0]> e scr.prompt.flag=1
[0x00005ae0 | entry0]> s +1
[0x00005ae1 | entry0+0x1]> s -1
[0x00005ae0 | entry0]>
```
=> Fix #19783: Improve scr.prompt.flag to include offset and hex delta

libr/anal/fcn.c
Potential/partial fix for #19805
This will ensure function prototypes created by `r_anal_function_get_signature` have a function name that tcc will accept. When a function has an invalid name, the invalid chars will be replaced with `_`. So in the case of #19805 the function name `method.OnePasswordNativeMessageHost.OPNMXPCConnection.setXpcConnection:` will become `method.OnePasswordNativeMessageHost.OPNMXPCConnection.setXpcConnection_` in the prototype.
For signatures this won't affect the renaming of the function on match. The matched function should still become `method.OnePasswordNativeMessageHost.OPNMXPCConnection.setXpcConnection:`. I don't know if it will have another ill affect somewhere else.
The core of the issue might be that a functions can have names with `:` …
=> Sanitize function names for prototypes ##anal

sys/install.sh, sys/termux.sh, sys/user.sh
Improvement to #19500. Now, if you used ".git" in the remote name it will still work.
=> Check for .git extension in upstream remote in install scripts

libr/core/panels.c
Unused variable warning is killing the CI
=> Remove unused update variable in __print__decompiler_cb()

libr/anal/fcn.c, libr/anal/var.c, libr/include/r_types.h, libr/include/r_vector.h, libr/util/intervaltree.c
* All those basic primites were based on wrong assumptions
* Added more return_if preconditions on several anal functions
=> Fix undefined behaviour in RVector, RPVector, RInterval and container_of ##fix

libr/core/cmd_hash.c, libr/core/core.c
Closes #19438.
* `#!` has been removed from tabhelp, listing is preferable. Help for `#!` comes from `#?`.
* `#` and `#!` help has also been improved. `#!?` now prints help instead of erroring out.
* `>` and `@` still require a space, but will now automatically add one if it does not exist.
Removing the space requirement for `>` and `@` is not possible without including them in the autocompletion output, which is undesirable. It's something I'd like to see in the future, but the current API can't handle it.
=> Improve autocomplete

libr/core/cmd_anal.c
* No need for `aaaa` to get more functions and xrefs!
* aaef is executed instead of `aae`. so it will miss refs
=> Run 'aap' before 'aae' on arm64 binaries in 'aaa' ##analysis

libr/anal/p/anal_ppc_cs.c, test/db/esil/ppc_32
ESIL of `addis r2, r12, 3` is `3,r12,+,r2,=`, but should be: `16,3,<<,r12,+,r2,=`
`addis` is "add immediate shifted", but its ESIL output is for "add immediate".
=> Fix PPC ESIL of addis instruction ##esil

libr/bin/format/mach0/mach0.c, libr/bin/format/objc/mach0_classes.c, libr/bin/mangling/swift-sd.c, libr/include/r_bin.h, test/db/formats/mach0/swift
* __const section is formatted as dwords
* Fix swift5 symbol demangling on iOS / macOS
=> Add support for parsing swift metadata from macho binaries ##bin

libr/anal/p/anal_arm_cs.c
`mov pc, lr` and conditional variants are rather rets/condrets than movs. This patch has huge impact on function analysis
=> Fix incorrect op-type assignment in anal_arm_cs

libr/io/p/io_ar.c
=> Fix incorrect type, that breaks liball:// and arall://

libr/core/cmd_cmp.c
Use `r_core_cmd_help_match()` when running `ca` and when `cat` is given an empty string for the path.
=> Improve help output for cat command

libr/bin/format/objc/mach0_classes.c, libr/util/name.c
=> Fix swift metadata string allocation and filtering bug

libr/bin/format/mach0/mach0.c
Fix rebasing pointer of `DYLD_CHAINED_PTR_64` format.
And remove some trailing spaces in unrelated code (thanks vim).
=> Fix rebasing Mach-O DYLD_CHAINED_PTR_64 ##bin

libr/core/cmd_cmp.c, libr/include/r_core.h, test/db/cmd/cmd_cw
This command was originally implemented in 2012 but never documented or tested and the help text was sparse with information about what it actually did.
* Change the `R_API r_core_cmpwatch_*` functions to return bool for reporting success and failure.
* The internal `cmd_cmp_watcher()` function now returns an int, so it can propagated through `cmd_cmp()`.
* Fix a bug that caused watchers to be partially overwritten and then duplicated in `core->watchers` when creating a new watcher at an address that already has one.
* Watchers are now totally overwritten when this happens.
* Provide more verbose help text about watchers with `cw??`, including a reference to the book page.
* Add tests for `cw` and its subcommands.
* Ask user for confirmation before deleting/reverting all watchers - it's a …
=> Partial #19887 - Refactor, document, and test `cw` command

binr/r2r/r2r.c, libr/include/r_types.h
EPRINT macros are very useful for debugging, but interfere with output for tests when running r2r. This patch adds a check for the `R2_SUPPRESS_VAR_EPRINT` environment variable to allow the user (or the test suite) to disable them at runtime (must be `"1"`).
This includes a minor refactor to the macros - now, instead of each one being a raw eprintf, they use a wrapper that passes the name, format string, and `__VA_ARGS__` along to eprintf after checking the environment variable. The format string is partially pre-constructed to make the definitions more clear about what the specific type needs to be printed properly.
Example usage:
```
$ git diff libr/core/cmd_print.c
diff --git a/libr/core/cmd_print.c b/libr/core/cmd_print.c
index 0d77c1700..43ed406db 100644
--- a/libr/core/cmd_print.c …
```
=> Add R2_DEBUG_EPRINT to disable debug var printing at compiletime or runtime

libr/main/radare2.c
Fixes `dir->zigns` typo and avoids a warning from `r_sys_dir` if `!path`. I also pulled it as out as a static inline function to simplify `r_main_radare2`.
=> Fix autoloading of ##signatures

libr/util/file.c, libr/util/str.c, test/db/formats/cgc, test/unit/test_glob.c
This PR aims to fix several bugs in the glob pattern matching. These are:
1. When using a recursive glob (e.g: `/path/**.ext`) in the recursive calls to `recursive_glob` when a directory is found the path is not properly formed, as `path` does not end with `"/"` nor `file` starts with the mentioned character. i.e: a path like `/path/tofile` would be formed instead of the correct `/path/to/file`. This is fixed by the changes in `file.c`.
2. The function `r_str_glob` does not behave properly when using a recursive glob (e.g: `/path/**.ext`) as the `glob` variable will point to the second `*` character after the pre-increment in line 2357. Next, `str` is incremented until `*str == *glob`. This is not the intended behaviour as the `*` character is not meant to be found in the …
=> Fix glob matching in several cases

libr/bin/format/mach0/mach0.c
* Reported by @Han0nly via huntr.dev
* Reproducers: heapoverflow1
* BountyID: e589bd97-4c74-4e79-93b5-0951a281facc
=> Fix oobread in the macho parser ##crash

libr/bin/format/ne/ne.c
* Reported by @hmsec via huntr.dev
* Reproducer: nepocaligns
* BountyID: ec538fa4-06c6-4050-a141-f60153ddeaac
=> Fix oobread and unaligned casts in the NE entrypoint logic ##crash

libr/core/disasm.c, test/db/cmd/cmd_disassembly
=> Fix #19940 - infinite loop in x/i on invalid instructions ##crash

libr/core/cmd.c, libr/core/cmd_api.c, libr/core/cmd_help.c, libr/core/cmd_macro.c, libr/core/cmd_print.c, libr/core/cmd_write.c, libr/include/r_core.h, libr/util/str.c, libr/util/str_trim.c, test/db/cmd/cmd_afn, test/db/cmd/cmd_macros, test/db/cmd/cmd_pd, test/db/cmd/cmd_w, test/db/cmd/feat_quote
```
[0x00000000]> (x\;?e hello\;?e world)
[0x00000000]> .(x)
No macro named 'x'
[0x00000000]> (
0 (x\ ; ?e hello\; ?e world)
[0x00000000]>
```
=> Honor escaping semicolons in macro definitions ##shell

libr/meson.build
I found that the meson build of radare2 does not seem to include anal_loongarch_gnu
When I use r2（build with meson） to analyze the loongarch binary I get the following message
```
anal.arch: cannot find (loongarch)
anal.arch: cannot find (loongarch)
asm.arch: cannot find (loongarch)
asm.arch: cannot find (loongarch)
```
I fixed the issue with anal in the patch, but I'm not sure how to fix the issue with asm, because the asm function is included in anal in loongarch, and there is no separate asm module
=> fix loongarch meson script miss

libr/core/cmd_cmp.c, test/db/cmd/cmd_c
Refactor bit compare.
* Rename `__core_cmp_bits` to `cmp_bits` and clean it up a lot.
* Handle the argument more gracefully
* Print help text on error
=> Partial #19887 - Refactor `c1` command

libr/core/cmd_anal.c
=> Fix `aeabj` output which returned different information than `aeab` ##json

libr/bin/format/mach0/coresymbolication.c
* Reported by @cnitlrt via huntrdev
* BountyID: 02b4b563-b946-4343-9092-38d1c5cd60c9
* Reproducer: neoobread
=> Fix oobread bug in NE parser ##crash

libr/core/cmd_write.c
Fixes #19891.
```
$ r2 -
[0x00000000]> o
3 * rwx 0x00000200 malloc://512
[0x00000000]> wz
| wz string  write zero terminated string (like w + \x00)
[0x00000000]> wz1A
| wz string  write zero terminated string (like w + \x00)
[0x00000000]> wz?
| wz string  write zero terminated string (like w + \x00)
```
=> Improve `wz` help and error handling

libr/include/r_bin.h
* Causes `izz` to fail with invalid negative ranges
* Also affects other commands, but this breaks the ABI
=> RBinFile size must be ut64, not signed int to open > 2GB files ##bin

libr/core/cmd_debug.c, libr/debug/debug.c, libr/debug/p/debug_native.c, libr/include/r_debug.h, test/db/archos/linux-x64/cmd_dx
* Break API compat for `r_debug_execute()` by adding an additional argument to ignore stack restoration.
* Add `dxrs` command to restore program state excluding the stack (only registers and overwritten instructions at PC)
* Test `dx` commands and document existing bugs. `dxe` is still untested because I could not get it to compile anything.
These changes are required for the dd refactor.
=> Add `dxrs` command and test `dx` commands

libr/core/cmd_debug.c, libr/debug/debug.c, libr/debug/p/debug_native.c, libr/include/r_debug.h, test/db/archos/linux-x64/cmd_dx
Fix #19966
Other bugfixes and API changes:
* `r_debug_execute()` returns bool instead of ut64 to report if code was successfully run
* Return value is now an output arg
* Fix return value coming from register A0 (arg) instead of R0 (ret)
* Fix stack restoration - always restore the full 4k
=> Fix #19966 - Reset seek in r_debug_execute() to real PC

libr/bin/format/mach0/coresymbolication.c, libr/bin/p/bin_symbols.c
* Reported by @cnitlrt
* BountyID: af6c3e9e-b7df-4d80-b48f-77fdd17b4038/
* Reproducer: symoob
=> Fix oobread and null deref in symbols file parser ##crash

libr/asm/arch/arc/gnu/arcompact-dis.c, libr/hash/sha2.c
Fix several compilation warnings
```
sha2.c:513:26: warning: argument 1 of type 'uint8_t *' {aka 'unsigned char *'} declared as a pointer [-Warray-parameter=]
sha2.c:585:48: warning: argument 2 of type 'char[]' with mismatched bound [-Warray-parameter=]
sha2.c:896:25: warning: argument 1 of type 'uint8_t *' {aka 'unsigned char *'} with mismatched bound [-Warray-parameter=]
sha2.c:927:48: warning: argument 2 of type 'char[]' with mismatched bound [-Warray-parameter=]
sha2.c:974:25: warning: argument 1 of type 'uint8_t *' {aka 'unsigned char *'} with mismatched bound [-Warray-parameter=]
sha2.c:1005:48: warning: argument 2 of type 'char[]' with mismatched bound [-Warray-parameter=]
...
p/../arch/arc/gnu/arcompact-dis.c:102:9: warning: this 'if' clause does not guard... …
```
=> Fix -Warray-parameter & -Wmisleading-indentation warnings

libr/asm/arch/8051/8051_ass.c, libr/asm/arch/8051/8051_disas.c, libr/asm/arch/8051/8051_ops.h
**Checklist**
This is a great refactoring and a great improvement. Not ready yet. I need to check any possible case. For example, it does not work for 'mov 0x0f, a' yet.
=> WIP: 8051: handle any mov case

libr/core/cmd_search.c, libr/search/aes_find.c, test/db/cmd/cmd_search_crypto
- `/ca` is about twice faster by returning false value earlier. 
- JSON output is now supported for crypto functions: `/caj`,`/cdj`, ...
Before:
```bash
[0x00000000]> ?t /ca
Searching 40 bytes in [0x0-0x3d090000]
hits: 0
19.477705
```
After:
```bash
[0x00000000]> ?t /ca
Searching 40 bytes in [0x0-0x3d090000]
hits: 0
11.955273
```
=> Improve /ca speed and add JSON output for crypto functions

libr/core/project.c
If there is no reason not to I'd like to increase the maximum length of a project name. It's particularly annoying as of know when working with files which must respect a certain naming convention. I have some scripts where I automate the analysis and creation of the project and I'd like for the project to have the same name as the file.
=> Increase project name max length ##projects

libr/anal/p/anal_6502_cs.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_evm_cs.c, libr/anal/p/anal_m680x_cs.c, libr/anal/p/anal_m68k_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_ppc_cs.c, libr/anal/p/anal_riscv_cs.c, libr/anal/p/anal_s390_cs.c, libr/anal/p/anal_sparc_cs.c, libr/anal/p/anal_tms320.c, libr/anal/p/anal_x86_cs.c, libr/anal/p/anal_xcore_cs.c, libr/anal/p/capstone.mk, libr/asm/p/asm_tms320.c, libr/asm/p/asm_tms320c64x.c, libr/asm/p/cs_version.h, shlr/capstone-patches/v3/capstone-include.patch, shlr/meson.build
Capstone requires to explicitly state the include path like `#include <capstone/capstone.h>` (see https://www.capstone-engine.org/lang_c.html). Until version 4 `#include <capstone.h>` worked as well. But from version 5 on, the former method is required (see https://github.com/capstone-engine/capstone/issues/1807).
This PR fixes the include paths such that Radare2 can be built against newer versions of capstone.
=> Fix capstone include directory

libr/core/cfile.c
=> Fix warning when trying to resolve GP on MIPS binaries without entrypoint

libr/anal/fcn.c, libr/anal/flirt.c, libr/bin/format/objc/mach0_classes.c, libr/bin/pdb/pdb.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_zign.c, libr/flag/flag.c, libr/include/r_util/r_name.h, libr/util/name.c, libr/util/str.c
* Rename r_name_filter2() to r_name_filter_dup()
* Fixes some project save/load inconsistencies
=> Fix #20040 - invalid char bug in afl* when function names contain ';' ##projects

libr/asm/arch/arm/armass64.c
adding some of  arm64 instructions for assembler (msub, madd, mneg, ngc, sbc, asr, ror, cls, clz, rev, rbit, rbit16, rbit32, umulh)
=> adding support for assembler --##arm64 instructions

libr/main/radare2.c
=> Add R2_COLOR env var for r2 when setting up scr.color ##shell

libr/core/panels.c
=> Fix #20049 - '.' in stack panel seeks to SP or BP if unset ##visual

libr/reg/rvalue.c
=> Fix UB when casting NaN to ut64 in RRegValue

libr/core/cmd_print.c, libr/util/print_code.c
Add a new print support for Golang variable slices, that's very useful when embedding files/shellcodes inside the source.
- [X ] Mark this if you consider it ready to merge
```go
[0x00005bc0]> pcg 10
var BUFF = [10]byte{0xf3,0xf,0x1e,0xfa,0x31,0xed,0x49,0x89,0xd1,0x5e}
```
=> Add pcg to print array in Golang format

libr/socket/meson.build
r_util_static_deps already handled in the block above, currently errors trying to append to an undefined var if use_sys_openssl is set.
=> Fix meson build with use_sys_openssl ##build

libr/syscall/d/Makefile
To fix linking on recent GNU toolchains, e.g. on Fedora 36:
```
/usr/bin/ld: d/darwin-arm-32.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: d/darwin-arm-64.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: d/darwin-x86-32.o: relocation R_X86_64_32S against `.data' can not be used when making a shared object; recompile with -fPIC
…
```
=> Add PIC_CFLAGS to the libr_syscall `%.sdb` rule ##build

libr/anal/p/anal_msp430.c, libr/bin/format/elf/elf.c
* Only crashes with asan builds
* Add missing =SN register
* Reported by cnitlrt via huntrdev
* BountyID: 1c22055b-b015-47a8-a57b-4982978751d0
=> Fix 4 byte oobread in msp430 disassembler ##crash

libr/anal/op.c
=> Add missing op types to r_anal_optype_to_string ##anal

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h
Fixes #20129 
At times, the wasm format parsing functions were treating the `max` variable as a "maximum length" rather than a "maximum offset". This meant section parsing would fail when any strings were read.
I updated the variable name `max` to `bound` in hopes that it is more clear and fixed the bug in `consume_str_r`. 
Afterward r2 still failed to parse exports for `pyodide.asm.wasm` because one of the exported symbol names is larger then 256. So further updates were made to allow arbitrarily large import and export entries.
Additionally various formatting things were updated.
I can squash things any way you like, I left commits separate because there were a lot of formatting things changed and did not want it to hide any logic errors I made.
=> Fix wasm section parsing ##bin

libr/cons/dietline.c, libr/cons/pal.c, libr/core/core.c, libr/core/visual.c, libr/include/r_cons.h, test/db/cmd/cmd_ec
* ec bgprompt=red blue ; ec prompt=green yellow
=> Add `ec bgprompt` for a colorful shell and visual prompts ##cons

libr/anal/anplugs.c
Fix for a memory leak in `r_anal_get_gperf_cc`
=> Fix leak in r_anal_get_gperf_cc ##anal

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h
Fixing a leak and improving code some. You might want to wait for a couple tests to be added before merging.
Looks like the `parse_custom_names_local` code is untested, I don't think there is any wasm files in the test files to even hit that code. I will fix add tests soon. If someone has a wasm file that hits that code, let me know. Otherwise I will find or build something.
=> Fix wasm custom name leak ##bin

libr/core/cbin.c
=> Fix missing calling convention when using asm.arch=*.XXX ##anal

libr/main/radare2.c
If return code from r2 isn't -1 then it's non error and set return code in 0
=> Correction returned code, set zero if ret isn't -1

libr/core/cmd.c
=> Fix bug when loading an r2 script with '.' ##shell

libr/anal/esil_trace.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/disasm.c, libr/core/visual.c, libr/include/r_core.h
* aeim;e key.S=dsb;e dbg.trace=true;ds;dsb
* aes was causing assert when no aeim was executed
=> Cleanup dbg.trace config vars and better error messages ##debug

libr/core/cmd.c
=> Fix #19606 - Dont route the RCore.cmdstr() when there's a pipe ##r2pipe

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h
A Wasm "Name" is valid if it's utf-8, which can include NULL bytes and all kind of other crazy things. So to prevent r2 from choking on this later in tcc or something, I encode the names on entry. This means we don't have to keep the string length and we can decode them later on output if we want.
Encoder might be a bit overkill atm, I pretty much encode every WASM name into something that can be treated as a C var. I probably don't need to encode section names so strongly, for example I could let a section name start with a number or `.`. So maybe this is just a stop gap.
Feel free to ask for better encoding or accept for now.
=> Better handling of Wasm Names ##bin

libr/bin/format/wasm/wasm.c, libr/bin/p/bin_wasm.c
This will cause `iE` to output something. It's still not all the way right, but it's progress:
After pull:
```
[0x00000207]> iE
[Exports]
nth paddr      vaddr      bind   type size lib name
―――――――――――――――――――――――――――――――――――――――――――――――――――
8   ---------- ---------- GLOBAL FUNC 0        _start
23  ---------- ---------- GLOBAL FUNC 0        __errno_location
19  ---------- ---------- GLOBAL FUNC 0        emscripten_stack_init
20  ---------- ---------- GLOBAL FUNC 0        emscripten_stack_get_free
21  ---------- ---------- GLOBAL FUNC 0        emscripten_stack_get_base
22  ---------- ---------- GLOBAL FUNC 0        emscripten_stack_get_end
16  ---------- ---------- GLOBAL FUNC 0        stackSave
17  ---------- ---------- GLOBAL FUNC 0        stackRestore
18  ---------- …
```
=> Wasm iE improvment ##bin

libr/lang/p/pipe.c
Fix error that appears when running a long session with esil.
https://github.com/radareorg/radare2/issues/20206
=> Fix #20206 - pthread_create: Resource temporarily unavailable

libr/core/cmd.c, libr/core/cmd_api.c, libr/core/core.c, libr/include/r_cmd.h
This optimizes alias iteration for autocompletion purposes. Previously, RList was used to easily pass a user pointer into the functional style of ht_pp_foreach() as opposed to the iterative style of e.g. r_list_foreach(). Now, special structs are used to store state during iteration. Since these use single contiguous chunks of memory, they operate much faster.
Additionally, we no longer use r_cmd_alias_get() for potential matches, instead storing both keys and values for potential completions, removing another hashtable lookup and cementing linear time operation.
Alias help has also been slightly edited for accuracy and informativeness.
This also fixes a bug that caused autocompletion to not include data aliases despite them being valid for use in commands. e.g. `> $t<tab>` did not …
=> Optimize alias iteration to linear time and improve alias help

libr/bin/format/pe/pe.c, libr/core/cmd_print.c, libr/core/disasm.c, test/db/cmd/cmd_pd_bugs
=> Fix #17961 - missing flags in asm.reloff=1 + scr.color=0 ##disasm

libr/debug/p/debug_windbg.c, libr/io/p/io_windbg.c
```
../libr/io/p/io_windbg.c:481:43: error: use of undeclared identifier 'DEBUG_ENGOPT_KD_QUIET_MODE'
ITHISCALL (dbgCtrl, AddEngineOptions, DEBUG_ENGOPT_KD_QUIET_MODE);
../libr/io/p/io_windbg.c:613:38: error: no member named 'GetValidRegionVirtual' in 'struct IDebugDataSpaces3Vtbl'
if (SUCCEEDED (ITHISCALL (dbgData, GetValidRegionVirtual, io->off, count, &ValidBase, &ValidSize))) {
```
first is ~~probably fine to remove~~ gone now because it didn't work to begin with, second is more useful though
=> Support building windbg plugin under mingw

libr/bin/p/bin_dol.c
The DOL file format is exclusively used with GameCube / Wii machines.
Both of those use the PowerPC 750CL instruction set, which ships the paired-singles CPU extension.
Radare2 incorrectly defaults to the altivec CPU type when loading a DOL binary with `r2 -F dol ./main.dol`, which garbles assembly.
This fix was tested with RMCP01 ROM at `0x80199fc8` (PSMTXInverse).
=> Set correct CPU in DOL bin loader

libr/bin/format/wasm/wasm.c, test/db/formats/web_assembly
Wasm *Custom Sections* can include a *Name* section which will store debugging information, such as plain text names of functions. I only see 3 sub-section types ([found here](https://webassembly.github.io/spec/core/appendix/custom.html#subsections)). But it seems `sections.wasm` in test bins has more subsection types. When the r2 parser hits these sections, it does not give up, instead it goes off the rails and eventually finds a error in the file and drops all the properly parsed section information.
This pull updates r2 to quickly give up when hitting an unknown sub-section type, but keep the information that was properly parsed. This means most the function names in `section.wasm` can be discovered and named.
=> Wasm allow partial custom name parsing ##bin

libr/anal/arch/wasm/wasm.c, libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h
Every wasm function should have a function type associated to it, by an index number, in the types section.
This pull updates the types to be stored in a RPVector so they can be referenced by index without traversing a double linked list. Additionally, this updates the code to accept types that contain multiple returns (see [this](https://hacks.mozilla.org/2019/11/multi-value-all-the-wasm/) for info).
Types are parsed but not used by anything yet, so I could not add any tests yet. I had a debug function in the code to loop over the types and print them, the printing did match output of `wasm-objdump`.
I would like to get type info associated to functions soon, but I am unsure of how to do that. Especially for functions that return multiple items.
=> Refactor wasm function types ##bin

libr/bin/format/elf/glibc_elf.h, libr/bin/p/bin_elf.inc, test/db/anal/bpf_64
- Adds BPF relocation types
- Adds an attempt to implement said relocations
```
Enum  ELF Reloc Type     Description      BitSize  Offset        Calculation
0     R_BPF_NONE         None
1     R_BPF_64_64        ld_imm64 insn    32       r_offset + 4  S + A
2     R_BPF_64_ABS64     normal data      64       r_offset      S + A
3     R_BPF_64_ABS32     normal data      32       r_offset      S + A
4     R_BPF_64_NODYLD32  .BTF[.ext] data  32       r_offset      S + A
10    R_BPF_64_32        call insn        32       r_offset + 4  (S + A) / 8 - 1
```
Reference: https://www.kernel.org/doc/html/latest/bpf/llvm_reloc.html
=> Add initial BPF ELF relocs

libr/bin/format/elf/elf.c
The ELF plugin currently defaults to returning an arch of x86 as a default, which is undesirable when `e_machine` is set to `EM_NONE` or the architecture is one that isn't explicitly supported. This change removes the current x86 default in favor of reporting "No machine" for `EM_NONE`, and "Unknown or unsupported arch" when `e_machine` is specified but isn't a known value. 
I tested this by running `rabin2 -I` with 32 and 64-bit x86 ELF files, an ARM ELF, a BPF ELF, and a firmware ELF that has`e_machine` set to `EM_NONE`. This change appears to have the intended effect based on those tests.
=> Fix ELF default arch of x86 ##bin

libr/anal/p/anal_bpf.c, libr/anal/p/anal_bpf_cs.c
The archinfo for bpf and bpf.cs is a bit off.
- `R_ANAL_ARCHINFO_MIN_OP_SIZE = 8`, `R_ANAL_ARCHINFO_INV_OP_SIZE = 8`: cBPF and eBPF instructions are 8 bytes long. 
- `R_ANAL_ARCHINFO_MAX_OP_SIZE = 16`: eBPF has a special opcode (`lddw reg, imm`) that fuses two ins into one.
- `R_ANAL_ARCHINFO_ALIGN = 8`: Instructions are 8 byte aligned
- `R_ANAL_ARCHINFO_DATA_ALIGN = 1`: Alignment checks on data are not mandatory
=> Fix BPF archinfo

libr/anal/p/anal_x86_cs.c
SHRD shifts the DST operand right by the third operand, and shifts the bits of SRC into DST as well. If the shift 0 is it is a NOP. CF is set to the last bit shifted out of DST and OF is set if the shift is 1 bit and changes the sign of DST. Its a bit complicated but this ESIL expression does this.
=> Fix SHRD instruction ESIL ##esil

libr/anal/p/anal_m68k_cs.c
Closes #20102
Correctly report `R_ANAL_ARCHINFO_DATA_ALIGN` for CPU types 68030, 68040, 68060.
The bug report mentions additional CPUs but these are not in the list of radare's supported m68k CPUs.
=> Set data alignment of m68k CPUs

libr/parse/c/libtcc.c, libr/parse/c/tcc.h, libr/parse/c/tccgen.c, libr/parse/c/tccpp.c, libr/parse/code.c
This removes the remaining TLS inside of TCC. As well, it fixes a bug where existing saved types would not be restored from sdb when parsing entire C files. I do not have a reproducer for this I just observed that the existing behavior is wrong.
=> Remove TCC TLS

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h, libr/bin/p/bin_wasm.c, test/db/formats/web_assembly
Wasm function names can appear in the custom name section or in the export section. An earlier attempted fix for bad `iE` mistakenly caused duplicate export entries in `iE` output if the wasm file had a custom name section.
This update will properly fix this problem, I think. The only uncertainty I have is in the case that custom names section and export sections disagree on a function name. I suspect the export section should be trusted in this case. That is how the current code will work. You can see this happen in the tests I updated.
This new code updates exports from a `RList` to a `RPVector`. This means it can be quick sorted and binary searched. So finding exports should be much faster.
=> Fix wasm iE duplicates ##bin

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h, libr/bin/p/bin_wasm.c
Mostly refactoring things to RPVectors. This does clean up a bunch of code and fix a few bugs that could cause if double free's.
This does change how ordinals are assigned to some symbols. Wasm uses separate "index spaces" to identify functions, tables, memories and globals.  So there is a `global[0]` and a `function[0]` rather then `symbols[0]` being either a function or global. This code will better this behavior in ordinals. So there may be a global symbol with the same ordinal as a function.
=> Last of RBinWasmObj entries to RPVectors ##bin

libr/anal/p/anal_i8080.c
Fixes regression in https://github.com/radareorg/radare2/pull/20303 where anal.i8080 would read up to 2 bytes past the buffer end.
=> Fix OOB disasm in anal.i8080

libr/anal/p/anal_arm_cs.c, test/db/esil/arm_16
ESIL support for ARM ´ror´ instruction was missing. This PR adds support and a test.
=> Add ESIL support for ARM-16 ROR instruction

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h, libr/bin/p/bin_wasm.c, test/db/formats/web_assembly
This code addresses two things.
First the import sectoin is now split into 4 `RPVector`'s instead of 1, there is a separate vector for functions, memories, globals and tables. The import section marks the start of the index space and since there is a different index space for each type, having them separated will simplify parsing logic. This also produces a very minor speed improvement because import parsing loops don't need switches for types.
With the separate import types I then fixed an issue where the WASM `.get_offset` API was returning the wrong function. Now that API returns the offset to the correct function. This results in `aa` finding functions in a different order, so a test had to be fixed.
I did not add a test for `get_offset` yet because it is still not …
=> Fix wasm function offset lookup ##bin

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h
Fixes a leak and should speed up parsing modestly.
This also sets up the code to be able to use the custom name locals section. I will work on this next I think, to get local variable names for functions.
=> Refactor wasm custom name parsing ##bin

libr/anal/p/anal_wasm.c
The `wasm_dis` function populates `wop->txt` with a `char *` that was never free'd. This pull ensures it gets free'd.
=> Fix leak in wasm opcode disassembly ##anal

libr/anal/p/anal_arm_cs.c, libr/parse/p/parse_arm_pseudo.c
ARM disassembler: for [pc, #imm ] , is ok to compute the address to display out. but not for [pc, reg].
=> ARM disassembler: don't compute [pc, reg] memory location

libr/core/cfile.c, libr/main/radare2.c
2 null checks are needed for debug file open to avoid a crash when the file doesn't exist.
No longer crashes:
```
$ r2 -e dbg.exe.path=nonexistent -AA -d gdb://localhost:1234
ERROR: Could not resolve address 'localhost' or failed to connect
gdb.io.open: Cannot connect to host.
[r] Cannot open 'gdb://localhost:1234'
```
=> Close #20453 - Fix crash due to null debug file handle/uri

libr/util/print.c
For bigger terminals no more hardcoded value for bar width.
I tried to keep old look default.
=> Allow to change entropy bars width with '[]' keys ##print

libr/cons/rgb.c
The R_DIM call was using wrong max allowed value.
Do not try to loop over colors reserved for gray.
Was wondering why pze output was not matching with prc=e in 256 colors mode, 16 colors mode worked fine.
Probably because of wrong R_DIM second parameter it caused overflows.
=> Fix picking colors for 256 colors terminals  ##cons

libr/anal/p/anal_pickle.c, test/db/anal/pickle
This pull adds an assembler for the python pickle machine architecture. 
At this time, the assembler handles all ops except `INST`, `GLOBAL`, `FLOAT`, `INT`, `LONG`, `PERSID`, `STRING`, `UNICODE`, `GET` and `PUT`. I hope to add assemblers for those soon. Assuming this looks ok, you can merge now or wait.
Also, I did this in rather a lazy way. If you want me to use a hash table for opcode names I can refactor a bit.
=> Add pickle assembler ##anal

libr/core/visual.c
I get irritated by increasing input buffer when keeping page up/down keys pressed down.
On slower machines it will not stop scrolling when keys are no more pressed down, instead
r2 will in visual mode continue to scroll several seconds more, much more obvious in disassembly output with colors then in hex one.
=> Make PageUp/Down keys less laggy ##visual

libr/core/cmd_print.c, test/db/cmd/cmd_print
The case was never triggered. Giving only zero bars output results.
=> Fix p=F output ##print

libr/core/cmd_print.c
The color issue of small numbers have been fixed in another commit.
The prc=f would switch colors, if used on same block again, because it accumulates changes.
Better fix would be to round away from zero in such cases, would fix scr.colors=0 in all other print cases.
Cant scr.colors=0 case have more entries? One could just count number of white pixels in default font per each character ....
and sort that from lowest to highest, and get more entries than current 9.
=> Fix color changing for same block and prc=f ##print

libr/core/disasm.c, test/db/cmd/cmd_pd_bugs
=> Dont show asm.describe on strings ##disasm

libr/util/str.c
Fixed crash in 'v' panel mode under address sanitizer, when showing entropy bars.
=> Fix overreads in r_str_utf8_codepoint()

libr/asm/asm.c, libr/core/casm.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/cmd_print.c, libr/core/cmd_search.c, libr/core/cmd_seek.c, libr/core/core.c, libr/core/disasm.c, libr/core/panels.c, libr/core/visual.c, libr/core/vmenus.c, libr/main/rasm2.c
Fixes some leaks.
The RAsmOp is used on stack when disassembling and after its content is not need it needs to call its _fini to free possible heap memory previously allocated.
=> Fix not calling r_asm_op_fini() when needed

libr/bin/p/bin_dol.c
I'm not sure how this ever worked. `RBinInfo::cpu` is a heap string, not a rodata constant
Fixes a minor skill issue
=> Fix string literal free in bin.dol

libr/bin/p/bin_wasm.c
Was wondering why 'ii' shows nothing for wasm files.
=> Fix returning imports table ##bin

libr/util/vector.c
realloc() call can return NULL for size of 0 and still free()
that memory, there was no check for this so code ends prematurely
and double free can happen later.
=> Fix double free when shrinking vectors ##crash

libr/egg/egg_cfile.c
Please refer to Issue https://github.com/radareorg/radare2/issues/16209 for all details.
A basic test:
```c
$ cat ./hi.c
int main() {
write (1,"Hello!\n",7);
exit(0);
}
```
Compile it,
```
$ ragg2 -O -F hi.c
'llvm-gcc' -arch x86_64 -fPIC -fPIE -fno-stack-protector -nostdinc -include '/usr/local/include/libr/sflib'/'darwin-x86-64'/sflib.h -z execstack -fomit-frame-pointer -finline-functions -fno-zero-initialized-in-bss -o 'hi.c.tmp' -S 'hi.c'
clang: warning: -z execstack: 'linker' input unused [-Wunused-command-line-argument]
In file included from <built-in>:1:
/usr/local/include/libr/sflib/darwin-x86-64/sflib.h:38:89: warning: declaration of 'struct rusage' will not be visible outside of this function [-Wvisibility]
static inline _sfsyscall4(pid_t, wait4, pid_t, pid, int *, status, int, …
```
=> Fix for #16209 - ragg2 not working on MAC OS

libr/core/gdiff.c, libr/include/r_core.h, libr/main/radiff2.c
Radiff2 when run with `-AAC` creates a table of similar functions based on their similarity scores. This information is not available as json, so I added a new function `r_core_diff_show_json`. The output of this function consists of an array of objects that have the following template:
```
{
"addr": 4203120,
"name": "entry0",
"size": 88,
"diff_addr": 4203248,
"diff_name": "entry0",
"diff_size": 88,
"match": "MATCH",
"dist": 0.965909
},
{
"addr": 4213228,
"name": "fcn.004049ec",
"size": 664,
"match": "NEW",
"dist": 0.000000
},
```
=> Emit json when radiff2 is run with -Cj ##diff

libr/core/cmd_anal.c
This breaks out some of the `ar` handler code into it's own static functions. Then 3 instances of `r_core_cmd*` calls can be replaced with a call to the new function.
I hope to remove more `r_core_cmd*` functions from this file in the future.
=> Refactor `ar` set command to static func ##anal

libr/core/cmd_anal.c
Squash this, left separate to see steps and maybe revoke last step if you like.
This removes 20 lines and simplifies cmd_anal some. There was a lot of repeated code for getting a new esil.
This will change a couple minor things. I think the changes are bugs where esil was not initialized with `verbose` or it `r_anal_esil_setup` was called on an already initialized esil with all parameters 0, instead of using r_config.
=> Refactor esil new in cmd_anal ##anal

libr/bin/p/bin_dyldcache.c
* Inpired in https://github.com/rizinorg/rizin/commit/556ca2f9eef01ec0f4a76d1fbacfcf3a87a44810
* When n_slide_infos is too high, the sum would overflow and too few entries would be allocated.
=> Fix oob write in dyldcache ##crash

libr/anal/p/anal_pickle.c
Currently rasm2 does not seem to use io bind. So `a->iob.is_valid_offset` call just lands at NULL.
=> Fix NULL deref in rasm2 on pickles

libr/main/rasm2.c
Updates rasm2 so that if a file fails to slurp r_io is attempted.
=> Allow rasm2 -f to open files with r_io files ##io

libr/anal/p/anal_pickle.c, test/db/anal/pickle
Assembler and disassembler should now agree on quotes. After the pull you can do:
```
x='string "test test"'; for i in {1..10}; do x=$(rasm2 -da pickle $(rasm2 -a pickle "$x" )); echo $x; done
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
string "test test"
```
=> Fix quotes in pickle assembly ##anal

libr/socket/run.c, test/db/tools/rarun2
- Fix r_run_parseline OOB read when using `@<n>@<pat>` (missing null terminator)
- Fix truncation when using null bytes in stdin #9782
=> Fix r_run_parseline OOB read and truncate bug ##crash

libr/bin/mangling/cxx/cp-demangle.c
Syncs fixes from GCC
- mangling/cxx: d_expression_1: Don't peek ahead unless the current char is valid. https://github.com/gcc-mirror/gcc/commit/956bea2cd6110f104f12d5861143efc71213c140 
- mangling/cxx: d_encoding: Guard against NULL return values from d_right (dc) https://github.com/gcc-mirror/gcc/commit/927e42fd52ed7dee859ac85fec9dd6830d769773
- mangling/cxx: d_print_comp_inner: Guard against a NULL 'typed_name' https://github.com/gcc-mirror/gcc/commit/80024f3180b9c4c904cd65323e1d1333cf19d1fe
=> Sync cp-demangle fixes

libr/debug/p/native/xnu/reg/darwin-arm64.h, libr/debug/p/native/xnu/xnu_debug.c, libr/debug/p/native/xnu/xnu_threads.c, libr/debug/p/native/xnu/xnu_threads.h
* Inspired by commit e893d2fb66916734fa71589058f7de9bb8c8fbf5
* in rizinorg/rizin by Author: Florian Märkl <info@florianmaerkl.de>
* Date:   Sat Aug 6 19:09:11 2022 +0200
Fix arm64 register access in xnu debugger
ARM_THREAD_STATE64 fetches arm_thread_state64_t but our struct was
arm_unified_thread_state_t, which adds a header. The pc in the register
profile was hacked to account for the shift, but all the x-regs were
not, so x7 had the value of x8 for example. Now we just use the specific
state for 32 or 64.
=> Fix arm64 register access in xnu debugger ##debug

libr/anal/p/anal_arm_cs.c
:= is faster than = in esil, and should be used, when no helpers are invoked to set flags
=> Minor optiomation of generated esil in anal_arm_cs.c ##refactor

libr/core/visual.c
* Unsigned integers in print format list
Issue #20671
```
[nik@viki radare2]$ binr/radare2/radare2 -v
radare2 5.7.7 28754 @ linux-x86-64 git.5.7.7
commit: e241f89b362b36d74d3491a47306eaab94652d69 build: 2022-09-09__12:54:16
```
```
[0x00000000 *0x00000000 [Xadvc]8 ($$+0x0)]> pxu                                                        
- offset - |  0  1   2  3   4  5   6  7   8  9   A  B   C  D   E  F   0  1   2  3| 0123456789ABCDEF0123
0x00000000 |           22            86             6             0             0  ....V...............
0x00000014 |            0          2785          2729          1428             9  ....................
0x00000028 |            0          3450    3221225471          1428             9  ....z...............
```
=> Add 'pxu' mode to ##visual

libr/core/cconfig.c, libr/core/visual.c
=> 5.8.0 - Deprecate scr.seek configuration variable ##core

libr/core/cconfig.c, libr/main/radare2.c
* It was set for a while, RBinFile holds this info in loadaddr
* file.offset was conceptually wrong because its 'global'
=> Remove the `file.offset` unused config variable

libr/util/str.c
=> [5.8.0] Fix memory leak in r_str_list_join()

libr/anal/p/anal_pickle.c
Fix bug where 0 is treated as a 64 bit number. The pickler would assemble it anyways due to another bug that this fixes.
=> Fix pickle arch thinking 0 is 64 bit ##anal

libr/anal/cond.c, libr/anal/fcn.c, libr/anal/jmptbl.c, libr/anal/op.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_bpf.c, libr/anal/p/anal_gb.c, libr/anal/p/anal_m68k_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_mips_gnu.c, libr/anal/p/anal_ppc_cs.c, libr/anal/p/anal_riscv.c, libr/anal/p/anal_riscv_cs.c, libr/anal/p/anal_rsp.c, libr/anal/p/anal_sh.c, libr/anal/p/anal_sparc_cs.c, libr/anal/p/anal_sparc_gnu.c, libr/anal/p/anal_x86_cs.c, libr/anal/var.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_type.c, libr/include/r_anal.h
Hi, I spent some time changing RAnalOp.src and RAnalOp.dst to use RPVector type, they are now RAnalOp.srcs and RAnalOp.dsts. The thing was that instructions like ARM ldm/stm might have multiple src or dst, and they won't be able to fit in the limited 3 src slots or 1 dst slot in the old RAnalOp.  Currently, I've changed all the places that use them so at least it compiles, and (hopefully) functions. Please double-check if I've broken anything... Thank you!
=> use RVector for RAnalOp src and dst instead of fix-sized array

libr/core/cmd_open.c
=> Fix null derefs in cmd.open

libr/crypto/meson.build
If you do a = files('example.c') and then a += a, meson rewrite will loop infinitely
=> Fix meson infinite loop ##build

libr/io/p/io_ptrace.c
Fix possible overreads.
FIxed also some strange ut32 * usage while here.
Hoping I have not broken something in process.
=> Fix io_ptrace UB when increasing NULL pointer

libr/anal/p/anal_evm_cs.c
Use the new functions use sdb_num_nget and sdb_num_nset to avoid convertion in evm,cs.
=> EVM: use sdb_num_nget and sdb_num_nset functions

libr/anal/p/anal_pickle.c, test/db/anal/pickle
The long1 and long4 opcodes were implemented wrong. This updates the assembler/disassembler to fix them, mostly.
Previously I thought `long1` would push a 8 bit number to the stack, instead it can push a 2040 bit number to the stack. The first byte after `long1` op indicates how many bytes should be interpreted as a signed little endian number and pushed onto the VM stack. The `long4` op uses 4 bytes.
Giant numbers are not completely handled, but handled well enough to get through I think.
In light of this, I also output longs as decimal numbers. Signdness gets a little funny otherwise because 0x00ff is treated as 255 while 0xff is treated as -1.
=> Fix long1,long4 pickle opcodes ##anal

libr/util/pj.c
I hit the JSON depth limit and it took a bit to figure out why JSON failed. This may save someone in the future some debugging. Assuming `R_LOG` is allowed here.
=> Add log error when pj depth limit reached ##util

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h, libr/bin/format/mach0/mach0_defines.h, libr/bin/p/bin_mach0.c
Add support for 32-bit chained fixup formats.
=> Add basic support for 32bit Mach-O fixups ##bin

libr/bin/mangling/java.c
=> Code cleanup using RStrBuf instead of Rbuf in the java demangler

libr/bin/p/bin_elf.inc, libr/bin/p/bin_mach0.c, libr/bin/p/bin_rel.c, test/db/cmd/cmd_i, test/db/formats/rel, test/db/io/write
* Use R_LOG for elf and rel fileformats
=> Warn about unpatched relocs when no bin.cache is set for macho fixups ##bin

libr/core/visual.c, libr/util/str.c
=> RStr.wrap() supports ansi and use it in VT ##visual

libr/bin/format/elf/elf.c
ELF files without sections were automatically considered as not "not stripped". Given that static symbols and MiniDebugInfo are stored in dedicated sections (.symtab, .strtab, and .gnu_debugdata, respectively) an ELF file without any section would have a difficult time providing that information.
=> Fix r_bin_elf_get_stripped for ELF files without section header.

libr/asm/p/asm_x86_nz.c, test/db/asm/x86_32, test/db/asm/x86_64
- [X ] Mark this if you consider it ready to merge
`xchg eax,eax` is not the same as `nop` in 64-bit, must not translate as 0x90
Expected output:
rasm2 -a x86.nz -b 64 "xchg eax,eax" -> 87c0
rasm2 -a x86.nz -b 32 "xchg eax,eax" -> 90
Also add some more test cases for xchg
=> Fix rasm2 x86.nz for "xchg eax,eax"

libr/anal/p/anal_loongarch_gnu.c
* Missing ->fail field in the 'bl' instruction
* Fix race condition using TH_LOCAL when initializing globals
* Constify more global structs
=> Loongarch analysis bug fixes (bl, race condition) ##analysis

libr/core/cmd_magic.c, libr/core/cmd_search.c, libr/magic/d/default/encoding, test/db/cmd/cmd_search_magic
base64 is removed from `/ck`, it was not really crypto and the final goal is to have all ck into magic. The numbering of hit is corrected. Magic file for encoding is from https://github.com/ReFirmLabs/binwalk/blob/master/src/binwalk/magic/encoding
=> Correct magic hit numbering and move base64 into magic

libr/io/p/io_rbuf.c
=> [5.8.0] Fix free-before-use on r_io_reopen of a rbuf:// fd/desc ##io

libr/anal/op.c, libr/core/cmd_search.c, libr/include/r_anal.h
* Check all the types/families provided before searching
* Needed for: /at `/atl~^sh` for shl/shr oneliners f.ex
=> Support space separated instruction types and family in /at and /af ##search

libr/core/core.c, libr/util/print.c
=> Fix unref issue when calling RCore.free from multiple threads

libr/crypto/meson.build
`libr/crypto/meson.build`used `files(sys_xxhash)` instead of just `sys_xxhash`, resulting in `libr/crypto/meson.build:44:2: ERROR: files argument 1 was of type "PkgConfigDependency" but should have been "str"`.
=> Fix meson with sys_xxhash

shlr/Makefile, shlr/capstone.sh
Instead of just checking that the capstone directory exists, check that we're at the correct commit. Avoids problems if new enums are added.
=> Sync capstone if not at correct commit

libr/bin/p/bin_xnu_kernelcache.c
Modern kernel caches don't need valid `prelink_info` in order to be parsed. This change improves the definition of "modern".
The `0xc0000002` constant is literal because there's no public name for it AFAIK and i prefer not making it up.
=> Fix validation check in xnu ##bin

libr/core/cmd_write.c
Print help and leave if `input[1]` is `'\0'`. Better behavior and avoids attempting to read `input[2]`.
=> Fix out-of-bounds read when running "wtf"

libr/anal/p/anal_pickle.c, test/db/anal/pickle
Lets you pickle some empty strings like  `rasm2 -a pickle 'short_binstring ""'`
=> Fix pickle asm rejecting empty strings ##anal

binr/r2r/load.c, libr/util/vector.c
* Crashing when passing corrupted tests to r2r
=> Fix rvector assert when indexing empty ones ##r2r

libr/bin/bobj.c, libr/bin/format/elf/elf.c, libr/bin/p/bin_elf.inc, libr/core/disasm.c, test/db/formats/elf/elf-relarm, test/db/formats/elf/reloc
=> Fix #18375 - Only patch arm64 relocs when not initialized ##bin

libr/core/panels.c
I noticed that in the disassembly panel, when trying to move left/right in cursor mode it 'skips' a byte. This commit aims to fix that.
=> Don't skip byte when moving left/right in cursor mode

libr/bin/format/p9/p9bin.h, libr/bin/p/bin_p9.c
Currently we do not load Plan 9 kernels properly, because their header is not mapped (unlike userspace applications) and the load address is wrong. This fixes loading amd64 and arm64 Plan 9 kernels so that they can be analyzed and all cross-references work.
=> Support loading Plan 9 kernels ##bin

libr/anal/type.c
This PR fixes an issue in the type removal code that was using an invalid `char *` in an `snprintf` operation to create the name of an SDB subkey to be searched for. Consequently, we ended up iterating over all SDB keys to search for a key with the incorrect format: `.<name>.`, where the correct format should have been `<type>.<name>`.
=> Fix subkey removal ##bin

libr/core/cmd.c
=> Fix null deref on wrong api usage for RCore.cmdStr ##api

libr/main/radare2.c
=> Fix `r2 /directory` behaviour ##shell

libr/core/anal_tp.c
* reproducer: $ r2 -c 'aaaa;o /bin/ls;aaaa;o /bin/sleep;aaaa' Twitter
=> Fix UAF in `aaft` when the BB is removed during the loop ##crash

libr/core/disasm.c
I noticed that in panels disassembly, when you enter cursor mode, you sometimes see two cursors if too many bytes are on screen. This commit aims to fix that.
=> Fix for the double cursor issue in panels

libr/anal/p/anal_arm_cs.c, libr/arch/meson.build, libr/arch/p/riscv.mk, libr/arch/p/riscv/plugin.c, libr/asm/asm.c, libr/asm/p/asm_arm.c, libr/core/canal.c, libr/core/cconfig.c, libr/include/r_arch.h, libr/include/r_asm.h, test/db/anal/8051, test/db/asm/riscv_64
* Fixes the arch/bits combo selection order issue for riscv tests
* Move the riscv arch plugin to the new plugin structure
* Deprecate r_asm_setup ()
=> Fix asm.acur supporting arch, anal and asm plugins ##arch

libr/main/rax2.c, test/db/tools/rax2
Finish to correct #20978. Null bytes are included.
=> rax2: corrects base64 encoding for null bytes

libr/core/disasm.c
Follow up to #21095. That PR revealed a new problem, the cursor stops getting drawn in panels mode towards the bottom  of the screen. This PR aims to fix that. Basically, I changed some the conditions to stop relying on `ds->index` because it gets reset (back to 0) when printing if there are too many bytes.
=> Fix for the disappearing cursor issue in panels mode when at the bottom of the screen

libr/anal/esil_dfg.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/include/r_anal.h, test/unit/test_esil_dfg_filter.c
Allows esil dfg to take into account if a specific addr is RO and read from the corresponding map instead of the treebuf fd
=> Add esil.dfg.mapinfo and esil.dfg.maps config vars ##anal

libr/bin/dbginfo.c, libr/bin/dwarf.c, libr/core/cmd.c, test/db/formats/dwarf
* Add test for dwarf 2 3 4 and 5
=> Add warning when loading DWARF5 files (not supported) ##bin

libr/arch/p/pickle/plugin.c, libr/include/r_arch.h
Pickle opcodes can have inline data. Inline data can is often preceded by a size value which can be huge.
Since the disassembler may get off track or encounter corrupted data, it needs a means of checking if an op is of reasonable size. 
Previously `RIOBind` was used to check if a op containing inline data would end in an invalid location. The refactor to RArch messed this up a bit this patch aims to fix it again.
After this patch `is_valid_offset` from RIOBind will again be used to check if opcodes fit in the file.
=> Fix counted string bug in pickle ##arch

libr/cons/line.c
=> Fix runtime warning after leaving an rlang session ##shell

libr/util/rxml.c
- [/] I've added tests (optional)
- [/] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)
The `R_XML_IS_*()` macros assume that `ch` has more than 8 bits, so they can do clever subtraction and only perform a single comparison.
While we could add casts to those macros, the 0..255 clamping logic also seems to assume there being more than 8 bits.
So these things considered it seems to make the most sense to do what the original yxml code does, and use `unsigned`. It is also consistent with `r_xml_refend()`.
=> Fix the XML parser ##util

libr/core/cbin.c, test/db/cmd/cmd_i
- [/] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)
The addresses are `ut64`, not `st64`. This fix means `cfg.json.num` is taken into account, and large addresses will not be encoded as negative numbers.
=> Fix JSON encoding of section addresses ##bin

libr/core/cmd_search.c, test/db/cmd/cmd_search, test/db/cmd/cmd_search_asm
- [/] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)
This fix means `cfg.json.num` is taken into account, and large addresses will not be encoded as negative numbers.
=> Fix JSON encoding of unsigned search values ##search

shlr/qjs/src/quickjs.c, shlr/qjs/src/quickjs.h
=> Fix undefined behaviour in quickjs when casting doublet to int64 ##js

libr/anal/d/cc-arm-64.sdb.txt, libr/anal/d/cc-x86-64.sdb.txt, libr/bin/format/p9/p9bin.c, libr/bin/format/p9/p9bin.h, libr/bin/meson.build, libr/bin/p/bin_dbginfo_p9.c, libr/bin/p/bin_p9.c, libr/bin/p/p9.mk, test/db/cmd/cmd_afcl, test/db/cmd/cmd_ara, test/db/cmd/cmd_tcc
* Fix load address of Plan 9 arm64 kernels
* Add Plan 9 calling convention for arm64 and x86-64
* Add Plan 9 line number information
Additionally, since I have rewritten the Plan 9 bin plugin entirely from its original state, with your blessing pancake I'd like to relicense it to be an MIT plugin like the Plan 9 source itself (we now borrow the line recovery algorithms from the source, specifically `hline` and `pc2line` from `sym.c` in `libmach` so I've added the foundation to the copyright header).
=> Add line information for Plan 9 ##bin

libr/anal/op.c
---
- Make r_anal_optype_{to,from}_string use the same optypes array ##analysis
- Balance spacings in braces ##indent
- Use R_ARRAY_SIZE in r_anal_op_family_from_string
-  Use R_ANAL_OP_DIR* enum value instead of hardcoded values
=> Cleanup in libr/anal/op.c ##analysis

.github/workflows/build.yml
This should increase the number of allowed api requests from 60 to 1000. So hopefully, we don't get any failed api calls anymore.
[Link to the doc](https://docs.github.com/en/rest/overview/resources-in-the-rest-api?apiVersion=2022-11-28#rate-limiting)
=> Use an authorized API call for the abi job

shlr/gdb/include/libgdbr.h
After merging #21237 mark `libgdbr_t.server_debug` field as deprecated to be removed during next ABI change.
=> Mark libgdbr_t.server_debug field as deprecated

libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_mips_gnu.c, libr/core/cmd.c, libr/main/rasm2.c, test/db/anal/mips, test/db/anal/mips_micro
* Added tests
* Fix archinfo.mininstrlen for micromips
* Dont assume 4 byte is fixed instruction size
* To support data align and remove globals it must be moved to RArch
=> Support micromips on both gnu and capstone plugins ##anal

shlr/gdb/include/reg/mips.h, shlr/gdb/src/gdbclient/xml.c
Fixes comment https://github.com/radareorg/radare2/issues/8992#issuecomment-1384983689
A0 register is required to successfully apply the profile. Add this register to the default MIPS profile and to profile received be GDB client to prevent error during profile application.
=> Add A0 register into MIPS register profiles

libr/bin/p/bin_symbols.c
=> Fix allocation crash in bin.symbols ##bin

libr/arch/p/v850/v850dis.c, test/db/anal/v850
=> Blindfix for a glitch in the v850 disassembler ##arch

meson.build
This file is installed by the GNU autotools-based build system but not by meson.
=> meson: install rasign2.1 man page too ##build

libr/include/r_util/r_x509.h, libr/util/asn1.c, libr/util/x509.c, test/fuzz/fuzz_x509_parse.c
Move function used only by x509 fuzzer and update checks in ASN.1 lengths to reject length over 48 bits.
=> Clean-up ASN.1 parser and update x509 fuzzing

libr/fs/p/fs_zip.c
Fix potential memleak in [fs_zip.c](https://github.com/radareorg/radare2/blob/master/libr/fs/p/fs_zip.c) line 129.
Fix #21293
=> Fix memleak in fs_zip.c

libr/bin/dwarf.c, libr/include/r_bin_dwarf.h, test/db/cmd/dwarf, test/db/formats/dwarf
(Irrelevant for DWARF5 as the compilation directory is already in the line number program header)
Files in the line number program header with 0 as their directory index end up with the wrong directory,
because only the final compilation directory is stored. This PR aims to fix that by storing compilation  directories along with their offsets from the .debug_line section (DW_AT_stmt_list). 
We can then calculate this offset when parsing the line number program header to associate files with the correct directories if needed.
=> Use correct compilation directory for DWARF binairies

libr/bin/dwarf.c
Sorry missed this from my previous PR #21297. Since we support DW_FORM_line_strp now we need to free those strings as well.
=> Fix memory leak when parsing DW_FORM_line_strp ##bin

dist/plugins-cfg/plugins.android.cfg, dist/plugins-cfg/plugins.def.cfg, dist/plugins-cfg/plugins.ios-store.cfg, dist/plugins-cfg/plugins.ios.cfg, dist/plugins-cfg/plugins.mingw.cfg, dist/plugins-cfg/plugins.nocs.cfg, dist/plugins-cfg/plugins.nogpl.cfg, dist/plugins-cfg/plugins.static.cfg, dist/plugins-cfg/plugins.static.nogpl.cfg, dist/plugins-cfg/plugins.termux.cfg, dist/plugins-cfg/plugins.tiny.cfg, libr/bin/format/coff/coff.h, libr/bin/format/coff/coff_specs.h, libr/bin/format/coff/xcoff64.c, libr/bin/format/coff/xcoff64.h, libr/bin/meson.build, libr/bin/p/Makefile, libr/bin/p/bin_xcoff64.c, libr/bin/p/xcoff64.mk, libr/include/r_bin.h, libr/meson.build, test/db/formats/xcoff64
Basic XCOFF64 support. Unfortunately, some duplicated code. 
XCOFF32 not implemented yet.
=> Add XCOFF64 support ##bin

shlr/Makefile
I noticed that if you run `make clean` followed by `sys/user.sh`, the build will fail because of a missing libcapstone rule.
This simple change fixes that.
=> Fix 'no rule to make libcapstone.a' error

libr/include/r_arch.h
The fini callback has a type (RArchPluginFiniCallback) use that.
=> Fix the type used for the fini callback in r_arch_plugin_t ##arch

libr/core/cconfig.c, libr/core/cmd_print.c
* Just set asm.offset=0 and asm.bytes=0 if needed on multicolumn disasm
=> Deprecate the asm.minicols config variable ##disasm

shlr/Makefile
Fixes a silly mistake I made last time that causes libcapstone.a to be built even if it already was. See #21335.
=> Don't recreate libcapstone.a if it's already there

libr/bin/p/bin_dyldcache.c
So that it works with latest format of arm64/arm64e caches (iOS 16.3.1 and macOS), where many more "slices" of the dyld cache are present (more than 40 on iOS) and some versioning of objc format has changed. The x86_64 caches for macOS still need some more love, though.
=> Update dyld shared cache parser ##bin

meson.build
=> Fix #21332 - Add missing use_sys_openssl option for meson ##build

libr/bin/p/bin_dyldcache.c
Bail out parsing multiple headers if malformed (as opposed to keeping re-parsing the same header when size is zero until the max limit is reached).
=> Improve checks parsing dyldcache headers ##bin

libr/bin/bfile.c
Fix the dead store warning detected by static analyse tool infer@facebook
**Warning Type**
Dead Store
**Component Name**
radare2/libr/bin/bfile.c (line:167)
**Additional Information**
The value written to &len (type long) is never used.
=> Fix potential dead store

libr/arch/p/kvx/plugin.c
The plugin user struct used to be in bss, thus zero initialized... Lets use calloc here, just in case.
=> Use calloc in kvx arch plugin

libr/bin/format/elf/elf.c
.plt.got size read from the section header is not sanity checked to lie within file, hence get_import_addr_x86_manual() may get stuck in a loop  with high CPU usage on crafted ELF, unable to find plt_addr but still increasing it. 
It may take r2 a very long time to open such ELFs if size of .plt.got as stated in its header is too big, effectively looking like a DoS.
=> Fix ELF parser hang on malformed .plt.got header ##bin

libr/esil/esil.c, test/fuzz/fuzz_x509_parse.c
=> Fix -Wimplicit-const-int-float-conversion spotted by latest clang

libr/anal/p/anal_x86_cs.c, libr/reg/reg.c, test/fuzz/fuzz_cmd.c
=> Fix uaf caused by RRegItem.free instead of .unref ##crash

libr/bin/p/bin_dyldcache.c
Fix a boundary check which was too aggressive and broke parsing in some dyldcaches with v2 rebase info.
=> Fix wrong check in dyldcache rebase v2 logic ##bin

libr/core/canal.c
=> Optimize RCore.analOp() lowers aa from 1m23 to 1m19 ##anal

libr/bin/format/xnu/r_cf_dict.c, libr/bin/format/xnu/r_cf_dict.h, libr/bin/p/bin_xnu_kernelcache.c
See issue #21451. This fixes it by adding (optional) support for ID/IDREF attributes in plist parsing.
=> Fix #21451 - Support IDREF in cf_dict parsing ##bin

libr/cons/help.c, test/db/cmd/cmd_pf2
Fix #21449
Also allows exact mode to have multiple matches in cases where this applies such as `tej`:
```
[0x00000000]> tej?
| tej         list all loaded enums in json
| tej <enum>  show enum in json
```
=> Correctly align r_core_cmd_help_match output in inexact mode

libr/main/radare2.c, libr/util/sys.c
* Supports overriding system paths at startup time
* Makes happy snaps and other sandboxed or randomized execution environments
=> Support R2_PREFIX env var to override compile-time PREFIX ##core

libr/bin/p/bin_coff.c
extra check added before for loop if bin->symbols is not NULL in patch_relocs()
=> fix segfault when bin->symbols is NULL #21503 ##bin

libr/bin/p/bin_dyldcache.c
This change correctly computes the offset to reach the symbol info from each actual binary in the multiple sub-caches scenario.
=> Fix Mach-O symbol parsing in dyldcache ##bin

libr/core/disasm.c, libr/io/io_cache.c
- Proper handling of IO cache in pde command. A deep copy is made, since pde command can modify the IO cache. After the command, the cached is replaced with the copy to undo effects of pde.
- Fixed a bug in case cache was initialized multiple times (memory leak).
- Fix bug in clone function that reversed order of the writes.
- Fix a nasty bug when cloning cache items due to C not checking any types on `void*`.
=> More fixes for new IO cache implementation ##io

libr/io/io_cache.c
=> Fix segmentation fault when listing cache entries before init ##io

libr/asm/meson.build
Removes a redundant line from the meson build file for asm.
=> Remove unneeded line in meson build after plugin migration ##arch

libr/esil/esil.c, libr/reg/rvalue.c
* Still limited to 64bit values
=> Fix RReg.setValue on 128bit registers ##reg

libr/core/disasm.c
=> Fix '\xff' strings issue in bsd-rv64/arm64 ##disasm

libr/bin/p/bin_xnu_kernelcache.c
=> Unused var had a meaning in the xnu kernelcache parser ##bin

libr/main/rax2.c
For https://github.com/radareorg/radare2/issues/21434
Tried to sync rax2 -r with r2's ? output (and reuse code)
https://github.com/radareorg/radare2/issues/21434
- removed extra ':' in float and double
- matched the order/sequence of the output to r2's '?'
**Limitation**
- 'fvalue' is not reported by rax2
=> Try to duplicate visual output of libr/core/cmd_help.c "?" command

libr/anal/op.c, libr/debug/trace.c
=> Resolve ${arch}.nz as fallback when finding an assembler peer ##arch

libr/core/cbin.c
* Patch 'r_core_bin_set_arch_bits' worked only for anal ones
=> Support fatmachos with slices using arch plugins ##arch

libr/core/canal.c, test/db/anal/arm64
In this way is consistent with mem write logic and mem read xrefs are found too.
=> Fix aae logic for mem read xrefs ##anal

libr/main/r2pm.c
This breaks the tar I use, seems this "dashless" syntax is GNU-specific. This change should result in no breakage, and just improve support for various tar implementations.
=> Add - to tar xzvf ##r2pm

libr/anal/op.c, test/db/cmd/archs
=> Fix the wrong plugin used after failed arch.encoding ##arch

libr/core/cmd_anal.c
=> Fix wrong json key string (refs to name) in anal_axg

binr/r2r/Makefile, binr/r2r/load.c, binr/r2r/r2r.c
* That looks like a gcc bug, because clang is not affected
* Anyway, lets just workaround it this way
=> Fix r2r build when doing static linking ##build

libr/bin/format/mach0/mach0.h
For some corrupt binaries, the `nindirectsyms` field would be negative, breaking the array length check. This resulted in an out-of-bounds array access.
=> Fix crash due to int overflow loading mach0 ##bin

libr/bin/format/elf/elf.c, libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h
Simply changing `nindirectsyms` from `int` -> `ut32` did not help. A value that was negative previously, would now try to allocate a very large amount of memory. The previous change was reverted, and a check was added to see if `nindirectsyms` is a positive number.
=> Improve handling of nindirectsyms for corrupt macho binaries ##bin

libr/anal/p/anal_x86_cs.c, test/db/anal/x86_16
=> Handle 'int 0x20' as eob on x86-16 (assume DOS) ##analysis

libr/anal/op.c
=> Fix spelling of R_ANAL_OP_TYPE_LENGTH ##API ##capstone

libr/arch/p/sparc_cs/plugin.c, test/db/anal/sparc
=> Fix #17850 - Fix sparc disassembler with invalid instructions

libr/bin/p/bin_elf.inc.c
=> Fix #21823 - tag static elfs as non libinjectables ##bin

libr/core/anal_tp.c, libr/core/cmd_debug.c, libr/esil/esil.c, libr/esil/esil_trace.c, sys/counters.sh
* Requires `e dbg.trace=1; aeim` before testing
=> Fix null derefs and memleaks in {esil,debug}traces ##esil

shlr/java/code.c
=> Fix 1byte oobread bug in the java decoder spotted by arch

libr/debug/p/debug_gdb.c, shlr/gdb/src/gdbclient/core.c, shlr/gdb/src/libgdbr.c
…debug plugin ##debug
* Refs #21813
=> Fix #21813 - reading and parsing /proc/pid/maps from remote gdb on android ##debug

libr/anal/p/anal_dalvik.c, libr/arch/p/wasm/plugin.c, libr/bin/p/bin_dex.c, libr/bin/p/bin_wasm.c, libr/include/r_bin.h
The `RBinBind->get_offset` returns an `int` while the code using these values cast them to `ut64`. This will update the API to ut64. 
Still not 100% confident this code is right, figured I would let the tests run while I check a few things manually.
=> Use ut64 for bin bind offsets ##bin #if R2_590

libr/anal/op.c, libr/anal/p/anal_x86_cs.c, libr/include/r_anal/op.h
COMISS and UCOMiSS instructions are prevalent when using GCC under Linux x64. Example:
```c
// compile with gcc -S -O3 test.c
#include <stdio.h>
int main(int argc, char **argv)
{
float f1;
float f2;
scanf("%f", &f1);
scanf("%f", &f2);
if(f1 > f2)
{
puts("bigger");
}
else if(f1 < f2)
{
puts("smaller");
}
return 0;
}
```
=> Add recognition to (U)COMISS instruction set ##API ##capstone

libr/include/rvc.h, libr/util/rvc.c
=> Remove the empty definition of rvc.use()

libr/bin/p/bin_bflt.c, libr/bin/p/bin_coff.c, libr/bin/p/bin_elf.inc.c, libr/bin/p/bin_mach0.c, libr/bin/p/bin_rel.c, libr/core/cbin.c, libr/core/cconfig.c, libr/include/r_io.h, libr/include/r_types.h, libr/io/io.c, libr/io/io_bank.c, libr/io/io_map.c, test/db/anal/classes, test/db/anal/x86_64, test/db/cmd/cmd_i, test/db/cmd/cmd_ie, test/db/cmd/cmd_pd_str, test/db/formats/coff, test/db/formats/dwarf, test/db/formats/elf/elf-relarm, test/db/formats/elf/reloc, test/db/formats/rel, test/db/io/write
Ok, so why is this better than cache abuse and reloc_maps:
reloc_maps spams a shitload of maps, rwx perms are fuzzy to handle, potentially causes crashes when a dynamic loaded plugin gets dlclosed at runtime
cache abuse cannot handle remapping, map priorization and it allows esil to ignore w perms, because iocache disables checks in io. Also it renders iocache useless for it's primary purpose
=> Map overlay ##io

libr/anal/anal.c, libr/include/r_anal.h
=> Deprecate r_anal_op_hexstr() ##api

libr/core/cbin.c, libr/core/cmd_info.c, test/db/cmd/cmd_i, test/db/formats/dwarf
* Needed for bin.pcap to display extra details
* Maybe good to have an opex-like string in RBinInfo
=> Support bin details from non-arch bin files ##bin

libr/bin/d/Makefile
Without the fix, install-symlink in Makefile causes link loop of libr/bin/d/dll directory:
`lrwxrwxrwx 1 root root 40 Jun 19 01:06 libr/bin/d/dll/dll -> /home/dvertx/radare2/libr/bin/d/dll`
Output of `lr` command:
`...
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/kernel32.sdb.txt
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/keyboard.sdb
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/keyboard.sdb.txt
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/lzexpand.sdb
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/lzexpand.sdb.txt
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/maincp16.sdb
./libr/bin/d/dll/dll/dll/dll/dll/dll/dll/dll/maincp16.sdb.txt
...`
=> Fix to symlink of DLL which causes link loop

libr/meson.build
Building iaito with latest commit checkout for radare2 reveals:
```
/packages/radare2_x86-5.8.9-1/.self/develop/headers/x86/libr/r_util.h:38:10: fatal error: r_util/r_base36.h: No such file or directory
```
This fixes the installation for the header.
=> fix missing header install for r_base36.h

libr/util/syscmd.c
Found some errors in ls cmd which are obvious. Some are not so obvious and would like more time to delve in it to create a fix in another PR.
I also put a note as a remark: tilde (~) is always received as 0x00, why is that, masked in the shell part or what?
=> Fix some ls cmd part

libr/bin/bin.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/dmh_windows.inc.c, libr/debug/trace.c, sys/lint.sh
=> Fix caller to RTable.toString() memory leaks

libr/syscall/syscall.c
=> Handle 'asm.os=android' syscall as an alias for 'linux' ##analysis

libr/config/config.c, libr/core/cmd_eval.c
Reworked `e?` and `e??` commands to have these behavior:
When the `e?` command supplied with a correct key, gives out the (only correct) description:
```
[0x00006ab0]> e?asm.bytes
display the bytes of each instruction
```
When `e?` is given incomplete key/var name. Notice the missing 's': byte instead of bytes:
```
[0x00006ab0]> e?asm.byte
Key not found. Try e??asm.byte
```
Will always suggest to try `e??` even for non existent key
The `e??` will supply any key and descriptions when given something similar to available keys. Again notice the missing 's':
```
[0x00006ab0]> e??asm.byte
asm.bytes: display the bytes of each instruction
asm.bytes.align: align bytes at right (left padding space)
asm.bytes.asbits: show instruction bits instead of bytes
asm.bytes.opcolor: colorize …
```
=> Rework e? and e?? commands for better output

libr/arch/p/arm/armass.c
=> Fix left shift of negative value in the arm assembler

libr/arch/p/x86/plugin_cs.c
Fix #22029 an issue with `repz ret` instruction which should not actually have the ESIL for the REP prefix as it is undefined for non-string instructions like `ret`. The `repz` prefix only serves to create a single 2 byte `ret` instruction for branch prediction optimization as noted [here](https://repzret.org/p/repzret/). Specifically these changes remove the `rep` ESIL for any of the control flow instruction types also excluded from `repne` already.
=> Fix #22029 ESIL for REP[Z] [BRANCH INSTR] ##esil 

README.md
The XAP architecture appears twice in the README's list of supported architectures.  
I've removed one instance, and also added "CSR" in parentheses. (An inaccurate but somewhat common parlance. See #5355.)
=> Fix XAP mention in `README.md`

libr/bin/p/bin_dyldcache.c
fixes a bug which caused segfault in loading dyld cache files after mach0 refactorings.
=> Fix uninitialized mach0 opts in dyldcache loading ##bin

binr/r2r/r2r.h, binr/r2r/run.c
`ENV` contains a `;`-separated list of `K=V` env variable definitions to use for the single test.
=> Implement ENV directive for r2r ##tests

test/README.md
Seems the underscore got transformed into a dash.
=> README: Fix unit tests target after fd9f8d631

libr/arch/p/m680x_cs/plugin.c, test/db/extras/asm/m680x_6805_8
Seems r_str_replace_in wants the buffer size, not the string size, so it was truncating the last character.
=> Fix mnemonic output in m680x plugin ##fix

doc/abi.md
When clicking the link on github in the CI section https://github.com/radareorg/radare2/blob/94a31e97b868ead86d27031280ead2f5c64fecbd/doc/abi.md#ci
It redirects you to https://github.com/radareorg/radare2/blob/master/doc/.github/workflows/build.yml#L522
Which is wrong since .github is not in the doc folder. Also pinning line 522 without a fixed commit gets outdated quite fast.
=> Fix relative doc link and perma link it

libr/core/cconfig.c, libr/core/disasm.c, libr/include/r_core.h, test/db/cmd/cmd_pd_bugs
The patch adds a new option `-e asm.offset.relto` to the `pd` command, which allows users to specify relative offsets for functions, maps, sections, and symbols.
https://github.com/radareorg/radare2/assets/6431515/013e6cb5-c423-438e-be1a-33f7bf0742e0
* Previously known as `bool asm.offset.relative`
* It's now a comma separated string, ..
* Well in fact just the 2 first chars is needed
* Support file, disk, maps, dmap, flag, func, symb, libs
```
[r2ai:0x100003a38]>> -i /tmp/p Explain this patch, what it does and determine if its a bugfix or new feature
```
This patch appears to be a bugfix for the `r_core` library. The changes made are:
1. A new `RELOFF_TO_*` constant is added to the `libr/include/r_core.h` header file, which defines the different types of offsets
that can be shown in the …
=> Improve asm.offset.relto only via pd ##disasm

libr/core/cmd.c, libr/core/cmd_anal.inc.c, libr/core/cmd_cmp.inc.c, libr/core/cmd_debug.inc.c, libr/core/cmd_egg.inc.c, libr/core/cmd_eval.inc.c, libr/core/cmd_flag.inc.c, libr/core/cmd_hash.inc.c, libr/core/cmd_help.inc.c, libr/core/cmd_info.inc.c, libr/core/cmd_log.inc.c, libr/core/cmd_meta.inc.c, libr/core/cmd_mount.inc.c, libr/core/cmd_open.inc.c, libr/core/cmd_print.inc.c, libr/core/cmd_project.inc.c, libr/core/cmd_search.inc.c, libr/core/cmd_seek.inc.c, libr/core/cmd_type.inc.c, libr/core/cmd_write.inc.c, libr/core/cmd_zign.inc.c, libr/include/r_core.h
Closes #21437. Reads much better now.
Used the following regex:
```
$ find libr -type f -exec sed -i {} -E \
-e 's/r_core_cmd_help_match (\(.*), true/r_core_cmd_help_match \1/' \
-e 's/r_core_cmd_help_match (\(.*), false/r_core_cmd_help_contains \1/' \
-e 's/r_core_cmd_help_match_spec (\(.*), true/r_core_cmd_help_match_spec \1/' \
-e 's/r_core_cmd_help_match_spec (\(.*), false/r_core_cmd_help_contains_spec \1/' \;
```
=> Split r_core_cmd_help_match and add r_core_cmd_help_contains

libr/core/cbin.c
=> Handle Kotlin as an alias for Java in icc classdump ##bin

libr/util/print.c
=> Fix r_print_hexdump() when called with RPrint *=NULL ##util

libr/bin/p/bin_hunk.c, test/db/formats/hunk/grey-final, test/db/formats/hunk/mc0201
**Test1**
```
radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -NN -Qc 'pd 3' radare2-testbins/hunk/mc0201
;-- entry0:
0x00000024      33fc01a000..   move.w 0x1a0, 0xdff096.l
0x0000002c      43f90000004c   lea.l 0x4c.l, a1
0x00000032      23c900dff080   move.l a1, 0xdff080.l
```
**Test2**
```
radare2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -NN -Qc 'pd 3' radare2-testbins/hunk/grey-final 
;-- entry0:
0x00000020      4df900dff000   lea.l 0xdff000.l, a6
0x00000026      3e3c7fff       move.w 0x7fff, d7
0x0000002a      3d470096       move.w d7, 0x96(a6)
```
=> Fix entry point determination and info for HUNK file parser ##bin

libr/util/syscmd.c
Popd throws an error incorrectly on final pop. An empty stack should not be considered an error, after emptying it.
=> Fix: Popd throws an error incorrectly on final pop

libr/util/str.c
A follow up to CVE-2023-0302.
Since the original report I've learned of C1 control codes, which would make a bypass possible.
Additionally, the original fix would allow a trailing ESC character to pass through, also allowing a bypass by splitting the rest of the sequence to a consecutive print.
Also, added BEL, ENQ and DEL to the sanitization due to their potential for abuse.
I tried my best to preserve original behavior to not cause side effects in dependent code.
I *might* not be able to add the tests in the next couple of days. FYI, in case that's a blocker.
=> Patch Escape Sequence Injection Bypass

libr/bin/dwarf.c
#22449 introduces a bug where NULL can be passed to strstr in some cases.
=> Minor dwarf getsection fix

dist/plugins-cfg/plugins.def.cfg, dist/plugins-cfg/plugins.static.cfg, libr/arch/meson.build, libr/arch/p/fslsp.mk, libr/arch/p/fslsp/plugin.c, libr/include/r_arch.h, libr/meson.build
This adds support for disassembling Freescale service processor code, as used in QorIQ and Layerscape systems.
=> Add arch fslsp

libr/bin/p/bin_dyldcache.c
This change gets rid of a couple of wrong assumptions:
- we assumed that entries in the images array were unique: wrong because multiple items with different names can refer to a single image in the dyld cache, for example when links are present when the cache is built (like `/usr/lib/libobjc.A.dylib` and `/usr/lib/libobjc.dylib` in iOS 9.x caches) and in that case we don't want to load and parse duplicated information
- we assumed that local symbol entries were 1:1 in terms of number and ordering with the images in the image list: wrong, symbol entries can come in any number - instead they reference the corresponding image by offset in the file, we just need to correct those offsets for some overhead we have when dealing with multi-file caches and we're now sure to not miss symbols or …
=> Fix a few long-standing issues in dyldcache parsing

sys/lint.sh
Probably useful to have this since this symbol is not available on Windows.
=> Add strndup to lint checks

libr/bin/format/coff/coff.c, libr/bin/p/bin_coff.c
Kudos to @trufae for reporting.
1. Fix out-of-bounds read in XCOFF ldsym handling (Affected versions: none, as this was a recent regression in https://github.com/radareorg/radare2/pull/22458)
2. Fix unbounded memory allocation in (X)COFF section handling 
The second bug has probably been there for a while. If `RBinSection::size` is not bounded, then the generic logic to find strings will calloc a large buffer. It is low severity, as the alloc failure will be gracefully handled without terminating the process. We should probably harden the RBinObject logic regardless to always truncate the section file ranges to the bounds of the file. It's better to never attempt to alloc that much memory in the first place.
=> Fix security issues in coff plugin ##bin

libr/include/r_io.h
=> Remove unused undo field in RIOPlugin ##io

libr/cons/pixel.c, libr/include/r_util/r_print.h, libr/util/print.c
On AIX with GCC 10, "#define $00" does not compile.
Apparently, '$' in identifiers is a GCC extension.
See https://stackoverflow.com/a/369524
=> Fix invalid macro identifies in r_print ##bug

libr/config.mk.tail, libr/include/r_types.h, libr/util/deps.mk, libr/util/thread_lock.c
First of many patches to support AIX.
- Add AIX config support ##port
- Fix lock_init sym collision on AIX ##port
=> AIX fixes ##port

libr/core/core.c, test/unit/test_util.c
- Closes https://github.com/radareorg/radare2/issues/22468
- Adds a regression test
=> Fix NULL deref in r_core log handling ##bug

configure, dist/docker/fuzz-asm/fuzz.sh, sys/install.sh
`/dev/stderr` is not supported on AIX.
=> Don't use /dev/stderr ##port

shlr/qjs/aix.patch, shlr/qjs/src/quickjs.c, shlr/qjs/src/quickjs.h
- quickjs assumes NAN and INFINITY are constant expressions.
This is not true on AIX. Adds a workaround.
- Don't use tm_gmtoff on AIX. (tm_gmtoff appeared in 4.3BSD Tahoe,
but AIX hasn't bothered to backport it in over 35 years)
=> Improve quickjs portability ##shlr

libr/core/cconfig.c
`dbg.glibc.path`  was declared as boolean setting this makes the check in https://github.com/radareorg/radare2/blob/702cbbef4d3a668a9255920b99acdace1e8c58c9/libr/core/dmh_glibc.inc.c#L399 not work as expected. 
An alternative solution would be to use something like this keeping the boolean type (suggested by Lazula)
```
const char *dbg_glibc_path = r_config_get_b (core->config, "dbg.glibc.path")? r_config_get (core->config, "dbg.glibc.path"): NULL;
```
=> Fix dbg.glibc.path type ##debug

binr/r2r/r2r.h, libr/include/r_types.h
- Removes unused `R2R_ARCH`
- Adds `R_SYS_OS` detection for AIX
=> Fix archos detection on AIX ##port

libr/core/agraph.c
check_changes was updating graph's title before potentially updating the current node
This resulted in title not showing the correct address in some circumstances, like when pressing '^' to go to beginning of function.
=> Fix graph title not current ##graph

test/db/archos/linux-x64/dbg_drv
Fix the tests for command `drv` formerly known as `drm`
=> Fix test for refactor of drm command to drv

test/db/archos/linux-x64/dbg_px0
Fix a one byte typo in test for `dbg.px0`
=> Fix typo in dbg.px0 test

libr/anal/sign.c, test/db/cmd/cmd_zignature
Detection code in signdb_type doesn't seem to work when the correct extension is not provided. This also happens when trying to load from a gzipped sdb file (because temporary file does not have sdb extension).
I did't know that signature files created by zos should have .sdb extension and I did zos test.sig, but didn't load when I tried zo test.sig. Now it loads fine.
I don't know if the sdb format has changed over time, there are parts of the current detection code that seem odd to me. I think this commit should make detection a bit better than before.
=> Improve sigdb file format detection ##anal

dist/docker/Makefile, dist/docker/README.md, doc/snap.md
- Disable GIT docker publish via Makefile (since this is done via github actions on [radare2-snap](https://github.com/radareorg/radare2-snap)).
- Update docker README with all the details of the 2 versions available (also fix the build commands).
- Update snap doc to include all new architectures and commands.
=> Update docker readme

libr/cons/dietline.c
- Make the behaviour of some vi commands closer to vim's behaviour.
- Fix some bugs in the word deletion functions.
- Implement `c` commands (`cw`, `ce`, ...).
- Implement vi horizontal motions `f`/`F` and `t`/`T` and the corresponding delete commands (`df<char>`, `dT<char>`, ...).
- Implement `dd` and `cc` commands to delete/change the whole line.
- Implement the `~` vi command which swaps the case of the current character.
- Make it possible to submit (by pressing Enter) the line in normal mode (CONTROL_MODE). Currently, we have to go into insert mode and press Enter.
If you're ok with this, I will update the book.
Happy new year!
=> Improve dietline's vi mode ##cons

libr/bin/p/bin_vsf.c
This change avoids misinterpreting vsf files currently produced by the C64 Debugger app (https://sourceforge.net/projects/c64-debugger/) in which the header has one more field (the Vice version), and can also produce a module named `"C64MEMHACKS"` which clashes with the vital `"C64MEM"` since only the prefix is compared.
Turns out also Vice for macOS is emitting this format now.
=> Add initial support for vsf dialect produced by C64 Debugger app ##bin

libr/core/cconfig.c
In this way it doesn't crash for NULL dereference if `e scr.demo=false` is run within a `r_core_task` like it happens in Iaito when running scripts from the GUI.
=> Check cons->line is there in `scr.demo` setter ##config

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h
Before this change we were walking the exports trie from the `LC_DYLD_INFO*` commands, but they can also be defined directly by the `LC_DYLD_EXPORTS_TRIE` command which was ignored by the Mach-O bin plugin.
This change adds support for that.
=> Walk Mach-O exports from LC_DYLD_EXPORTS_TRIE too ##bin

libr/core/cmd_debug.inc.c
This PR flips a boolean condition checking if we are currently in debugging mode (flag `cfg.debug` set). 
Currently, the `di` command only works when we are _not_ in debug mode, and it should be the other way around :)
=> Flip boolean condition for di command ##debug

libr/include/r_util/r_str.h, libr/util/Makefile, libr/util/bscanf.c, libr/util/meson.build, test/unit/test_scanf.c
* %s requires length via %.s
* cant use %*s for backward compat reasons (printf vs scanf inconsistencies)
* support %Lx as a portable ut64 modifier
* add some unit tests
=> Initial import of our custom and safe r_str_scanf ##util

libr/util/bscanf.c, test/unit/test_scanf.c
=> Implement scansets support in RStr.scanf ##util

shlr/grub/fs/sfs.c
=> Fixed null pointer dereference issue in treeblock

libr/bin/p/bin_xnu_kernelcache.c
Fix #22604 by removing an hardcoded offset added by mistake in https://github.com/radareorg/radare2/commit/b447f4f04777326372b653560448ec498600eada (when such an offset in strings appears is instead because the binary is fat and must be thinned before opening)
=> Fix kernelcache sections vaddr offset ##bin

libr/debug/p/debug_winkd.c
Currently `winkd` debugger never attaches because plugin's name is never not `winkd` so fix that...
PS. Looks like 9878dd0ad9f004edbd095623d880ecf04d224ce4 broke it
=> Enable winkd

libr/bin/format/pe/pe.c, libr/bin/p/bin_pe.inc.c, libr/io/p/io_cyclic.c, libr/io/p/io_default.c, libr/io/p/io_dsc.c, libr/io/p/io_r2k.c, libr/io/p/io_r2pipe.c, libr/io/p/io_r2web.c, libr/io/p/io_self.c, libr/io/p/io_shm.c, libr/io/p/io_sysgdb.c, libr/io/p/io_treebuf.c, libr/io/p/io_w32dbg.c, libr/io/p/io_windbg.c, libr/io/p/io_winkd.c, libr/util/buf.c
When debugging recent Windows 10 x64 kernel then it maps kernel modules very high in virtual memory (above `0x7fffffffffffffff`, eg. `0xfffff8018f920000`) that means it's not addressable using `ST64_MAX`.
And that is causing `oba` to not work due to such high address space.
This PR fixes that by:
* Reserving `UT64_MAX` for error case in `RBufferSeek()` 
* Updating  `ST64_MAX` to `UT64_MAX - 1` for `R_IO_SEEK_END`  in `winkd`
* Updating  `UT64_MAX` to `UT64_MAX - 1` for other plugins - they're broken in similar way and would fail above ST64_MAX anyway so this actually increases addressable space
* Use `buf_seek() != -1` instead of `buf_seek() >= 0` because `buf_seek` uses `st64` while `RBufferSeek` uses `ut64` - probably better would be to convert `buf_seek()` to `ut64` …
=> Support whole address space for IO

libr/util/lib.c
Previously, the plugin name was stored in the hash table with the preceding slash (like `/core_ghidra.so`).
But `already_loaded` searched for the name without the slash. This PR removes the preceding slash when storing plugin names.
=> Fix issue with detecting if a library/plugin was already loaded

libr/core/cmd_debug.inc.c, libr/main/r2pm.c
=> Use RTime.today() instead of time() in two leftovers

libr/reg/reg.c
Hi, I love reverse engineering binaries using radare and would love to contribute to this repository :).
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 ls` with LeakSanitizer
```
Direct leak of 32 byte(s) in 1 object(s) allocated from:
#0 0x55c8b678a627 in calloc /home/aniruddhan/aflgo/instrument/llvm_tools/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
#1 0x7f95161a89a6 in r_list_new /home/aniruddhan/radare2/libr/util/list.c:184:16
#2 0x7f95161a8a00 in r_list_newf /home/aniruddhan/radare2/libr/util/list.c:193:13
#3 0x7f951616e006 in r_str_split_duplist /home/aniruddhan/radare2/libr/util/str.c:3460:15
#4 0x7f9511120495 in r_reg_ro_reset /home/aniruddhan/radare2/libr/reg/reg.c:429:19
#5 0x7f95158a64b7 in cb_anal_roregs …
```
=> Free leak in reg.c

libr/reg/profile.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 ls` with LeakSanitizer
```
Direct leak of 9792 byte(s) in 136 object(s) allocated from:
#0 0x559ab5f87627 in calloc /home/aniruddhan/aflgo/instrument/llvm_tools/compiler-rt/lib/asan/asan_malloc_linux.cpp:154:3
#1 0x7f4be5245f05 in parse_def /home/aniruddhan/radare2/libr/reg/profile.c:64:19
#2 0x7f4be5245208 in r_reg_set_profile_string /home/aniruddhan/radare2/libr/reg/profile.c:249:8
#3 0x7f4be53f37d6 in r_anal_set_reg_profile /home/aniruddhan/radare2/libr/anal/anal.c:248:9
#4 0x7f4be99c53cd in cb_asmbits /home/aniruddhan/radare2/libr/core/cconfig.c:940:9
#5 0x7f4bea8830d4 in r_config_set_i /home/aniruddhan/radare2/libr/config/config.c:627:13
#6 0x7f4be970dbff in r_core_init …
```
=> Fix leaks in profile.c

libr/util/lib.c
Hi, I love reverse engineering binaries using radare and would love to contribute to this repository :).
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 ls` with LeakSanitizer
```
Indirect leak of 48 byte(s) in 1 object(s) allocated from:
#0 0x561a240c046f in malloc /home/aniruddhan/aflgo/instrument/llvm_tools/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x7fa38fb65005 in sdb_gh_malloc /home/aniruddhan/radare2/libr/../shlr/sdb/include/sdb/heap.h:39:9
#2 0x7fa38fb64f05 in sdb_gh_calloc /home/aniruddhan/radare2/libr/../shlr/sdb/include/sdb/heap.h:63:14
#3 0x7fa38fb6220b in internal_ht_new /home/aniruddhan/radare2/libr/../shlr/sdb/src/ht.inc.c:107:29
#4 0x7fa38fb64c4e in internal_ht_default_new …
```
=> Fix leak in lib.c

libr/debug/p/native/xnu/xnu_threads.c
So that if you have SIP disabled, but running an arm64 version of r2 on an arm64e target, it's still possible to read the target registers and step (but you can't modify the registers).
=> Avoid failing reg read if conversion fails on xnu native ##debug

libr/core/cmd_meta.inc.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 /bin/ls` with LeakSanitizer followed by visual mode 'V!' and 'q' followed by another 'q' to exit.
```
Direct leak of 1613 byte(s) in 1 object(s) allocated from:
#0 0x555a112c946f in malloc /home/aniruddhan/aflgo/instrument/llvm_tools/compiler-rt/lib/asan/asan_malloc_linux.cpp:145:3
#1 0x7f85c20fad09 in cmd_meta_others /home/aniruddhan/radare2/libr/core/./cmd_meta.inc.c:948:16
#2 0x7f85c1fd8b47 in cmd_meta /home/aniruddhan/radare2/libr/core/./cmd_meta.inc.c:1333:3
#3 0x7f85c22eabff in r_cmd_call /home/aniruddhan/radare2/libr/core/cmd_api.c:520:11
#4 0x7f85c2067681 in r_core_cmd_subst_i /home/aniruddhan/radare2/libr/core/cmd.c:5001:10
#5 0x7f85c205b925 in r_core_cmd_subst …
```
=> Fix leak in cmd_meta.inc.c

libr/bin/bin.c, libr/bin/p/bin_elf.inc.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 /bin/ls` with LeakSanitizer followed by visual mode 'V!' and 'q' followed by another 'q' to exit.
```
Direct leak of 1162 byte(s) in 113 object(s) allocated from:
#0 0x55bab18cc9d7 in strdup /home/aniruddhan/aflgo/instrument/llvm_tools/compiler-rt/lib/asan/asan_interceptors.cpp:452:3
#1 0x7fed5a003e46 in r_bin_name_clone /home/aniruddhan/radare2/libr/bin/bin.c:1510:15
#2 0x7fed5a003b4a in r_bin_import_clone /home/aniruddhan/radare2/libr/bin/bin.c:152:15
#3 0x7fed5a15256a in setimpord /home/aniruddhan/radare2/libr/../libr/bin/p/bin_elf.inc.c:43:28
#4 0x7fed5a14b3d3 in imports /home/aniruddhan/radare2/libr/../libr/bin/p/bin_elf.inc.c:434:3
#5 0x7fed5a04659d in r_bin_object_set_items …
```
=> Fix leaks related to name of RBinImport

libr/core/dmh_glibc.inc.c
Breaks out the function to get libc filename from memory maps since it is gonna be needed in other functions later.
Also changes the regex for finding libc. (inspired by pwndbg)
=> refactor resolve_glibc_version, improve libc regex

libr/esil/esil.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 /bin/ls` with LeakSanitizer followed by visual mode by  'q' to exit.
```
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x7fb50e4333ed in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cc:445
#1 0x7fb50a312739 in cb_mdevrange /home/aniruddhan/radare2/libr/core/cconfig.c:2161
#2 0x7fb50c524b03 in r_config_set_cb /home/aniruddhan/radare2/libr/config/config.c:404
#3 0x7fb50a32c0f9 in r_core_config_init /home/aniruddhan/radare2/libr/core/cconfig.c:4209
#4 0x7fb509f72090 in r_core_init /home/aniruddhan/radare2/libr/core/core.c:3339
#5 0x7fb509f4a255 in r_core_new /home/aniruddhan/radare2/libr/core/core.c:960
#6 0x7fb50d3245a9 in r_main_radare2 …
```
=> Fix leak in esil.c

libr/bin/mangling/swift-sd.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 /bin/ls` with LeakSanitizer followed by visual mode 'V!' and 'q' followed by another 'q' to exit.
```
Direct leak of 256 byte(s) in 4 object(s) allocated from:
#0 0x7fc816a66a06 in __interceptor_calloc ../../../../src/libsanitizer/asan/asan_malloc_linux.cc:153
#1 0x7fc81607d545 in r_strbuf_new /home/aniruddhan/radare2/libr/util/strbuf.c:6
#2 0x7fc8093df348 in my_swift_demangler mangling/swift-sd.c:296
#3 0x7fc8093e3102 in r_bin_demangle_swift mangling/swift-sd.c:729
#4 0x7fc808e83062 in r_bin_demangle /home/aniruddhan/radare2/libr/bin/demangle.c:165
#5 0x7fc8129dd9b2 in bin_imports /home/aniruddhan/radare2/libr/core/cbin.c:2162
#6 0x7fc812a0063a in r_core_bin_info …
```
=> Fix leak in swift-sd

libr/bin/bin.c
The PR fixes the below leak. It happens when I ran `./binr/radare2/radare2 /bin/ls` with LeakSanitizer followed by visual mode 'V!' and 'q' followed by another 'q' to exit.
```
Direct leak of 5 byte(s) in 1 object(s) allocated from:
#0 0x7f0bb2a933ed in __interceptor_strdup ../../../../src/libsanitizer/asan/asan_interceptors.cc:445
#1 0x7f0ba4f1fbe6 in r_bin_name_new /home/aniruddhan/radare2/libr/bin/bin.c:1493
#2 0x7f0ba4f1e421 in r_bin_field_new /home/aniruddhan/radare2/libr/bin/bin.c:1383
#3 0x7f0ba50e2f64 in fields /home/aniruddhan/radare2/libr/..//libr/bin/p/bin_elf.inc.c:1140
#4 0x7f0ba4f687a4 in r_bin_object_set_items /home/aniruddhan/radare2/libr/bin/bobj.c:362
#5 0x7f0ba4f65d18 in r_bin_object_new /home/aniruddhan/radare2/libr/bin/bobj.c:234
#6 0x7f0ba4f58509 in …
```
=> Fix leak due to r_bin_field_free

libr/io/p/io_dsc.c
Otherwise seeks beyond the end of the file will not be detected as failures and this causes the dyldcache bin plugin to load single-slice caches 128 times instead of 1, with obvious performance implications.
=> Bring seek error back to UT64_MAX in dsc ##io

libr/arch/p/snes/optable.h, test/db/asm/snes_16
Fixes the incorrect opcode type for MVN and adds tests for both MVN and MVP disassembly. Fixes #22653.
=> Fix MVN handling in SNES plugin and add tests ##arch

libr/cons/canvas.c
This patch fixes a memory leak within `r_cons_canvas_resize`.  In one location the authors manually free memory of individual fields and even miss fields such as `bgcolor` of `RConsCanvas`. Please do note that entire `c->b` is deallocated by authors. The patch instead frees using `r_cons_canvas_free` which includes free for `bgcolor`.
=> Fix leak in canvas.c

libr/core/cconfig.c, libr/core/dmh_glibc.inc.c
adds `dbg.glibc.main_arena` to retain resolved glbic `main_arena` address, it got resolved once then every subsequent command just did  not work because `m_arena` was not set.
=> Add dbg.glibc.main_arena config setting to retain resolved main_arena

libr/core/dmh_glibc.inc.c
This adds a new way to resolve `main_arena` address  in libc `get_main_arena_offset_with_relocs` which does a clever thing with relocations directly ported from pwndbg (https://github.com/pwndbg/pwndbg/blob/da3f0f3b26ffaa3c1680340a6e13731603c1bdb9/pwndbg/heap/ptmalloc.py#L1526).
This also cuts down the functionality of `get_main_arena_with_symbol` by _only_ looking for `main_arena` and failing if it is not there. The method of just taking an offset of `__malloc_hook` produced a lot of false results, and this symbol might be even removed since malloc hooks are deprecated.
There is still work to do to make this function with different versions of libc, this only works for >= 2.27 right now.
Also non-pie and static binaries need a different approach.
=> add new way to resolve main_arena ##debug

libr/arch/p/pyc/pyc_dis.c, libr/bin/format/pyc/marshal.c
The code assumes py objects are of a type that contains a r_list in it's data. This may not be true, so this verifies that a list is available. A deeper check may be necessary that the list contains intended objects, I did not get that far.
=> Fix type confusion in pyc ##arch

libr/util/ubase64.c, test/db/tools/rax2
According to [RFC 4648 §5](https://datatracker.ietf.org/doc/html/rfc4648#section-5) another way of doing base64 encoding  is using "-" instead of "+" and "_" instead of "/". This modification allows r2 to decode such strings.
=> Handle URL safe base64 decoding

libr/core/disasm.c
The leak can be easily reproduced by disassembling a function with `pD ` in a loop, e.g. using r_core_cmd_str in a loop.
In the function `r_core_print_disasm` memory allocated for `ds->analop` with `r_anal_op_init` by
```c
ret = r_anal_op (core->anal, &ds->analop, ds->at, ds_bufat (ds), ds_left (ds), R_ARCH_OP_MASK_ALL);
```
is only freed after the loop. So in the next iteration of the loop, `ds->analop` will be initialized again without freeing previously allocated memory.
I detected this memory leak while doing some memory profiling with Tracy
This profiling only showed the one leak for which I changed the last line. I changed the two lines above because it also looked like a memory leak was happening there and the init seemed unnecessary as this is also done in …
=> Fixes memory leak in r_core_print_disasm

sys/termux.sh
This fixes problems when script is invoked from directories other than the radare's root directory.
=> Ensure termux installation script only runs from root directory

libr/io/p/io_gprobe.c
=> Fix large shift-right msvc warning in the io.gprobe plugin

libr/core/cbin.c, test/db/anal/x86_64, test/db/formats/dwarf, test/db/formats/le
This change removes the part of the `printHere` address check where it explicitly checked for `paddr` even if the paddr / vaddr dichotomy is already handled via the `addr` variable, which is the only one we have to check here.
That caused wrong behaviour in binaries where the vaddr and paddr space numerically overlap (like old DOS/4GW LE binaries) where `iS.` was in fact picking the `paddr` instead of `vaddr` to filter if such an entry came first in the list.
=> Fix iS. paddr vaddr confusion ##core

libr/core/dmh_glibc.inc.c, libr/include/r_heap_glibc.h, test/unit/test_get_main_arena_offset.c
This adapts `get_main_arena_offset_with_relocs` to 3 different `main_arena` structure versions. This should now work for all >= 2.12
=> get_main_arena_offset_with_relocs for different libc versions ##debug

libr/bin/format/le/le.c, test/db/formats/le
This change fixes an issue for which whenever we encountered negative `source` offset we gave up on the entire page missing out the rest of the relocs on that page.
Instead negative means it is a cross-page fixup which is defined in both pages (started N bytes before the beginning of the current page), and we can also use this fact to avoid dupe relocs.
=> Fix handling of LE cross-page relocs ##bin

libr/core/cbin.c, test/db/formats/elf/sections, test/db/formats/pe/96emptysections
Now the size is virtual or physical consistently with the chosen address. This makes it possible to get correct ouput for `iS.` on addresses belonging to sections which have different `vsize` than `size` (like for example bss sections).
=> Use size or vsize consistently in iS. ##core

libr/bin/format/mach0/mach0_specs.h, libr/io/p/io_dsc.c
Spotted in macOS 14.4 arm64e, the rebase info v5 didn't make it to the open source yet, this is what i could make out of dyld:
```
struct dyld_cache_slide_info5
{
uint32_t    version;            // currently 5
uint32_t    page_size;
uint32_t    page_starts_count;
uint64_t    value_add;
uint16_t    page_starts[/* page_starts_count */];
};
union dyld_cache_slide_pointer5
{
uint64_t  raw;
struct {
uint64_t    pointerValue        : 34,
high8               : 8,
unused              : 10,
offsetToNextPointer : 11,
authenticated       :  1; // = 0
}         plain;
struct {
uint64_t    pointerValue              : 34,
diversity                 : 16,
hasAddressDiversity       :  1,
key                       :  1, // 1 = da, 0 = ia
offsetToNextPointer       : 11,
authenticated …
```
=> Add dyld shared cache rebase info v5 ##io

libr/core/cmd_open.inc.c, libr/debug/debug.c
This corrects the improper fix from https://github.com/radareorg/radare2/pull/18710, which resets ` core->dbg->main_arena_resolved` after every debugging step or breakpoint.
=> fix the fix for dmh after ood ##debug

libr/anal/c/tccgen.c, libr/arch/p/pic/pic_pic18.c, libr/bin/dwarf.c, libr/core/cconfig.c, man/rax2.1, test/db/cmd/cmd_pf
Fix 8 times the typo `endianess` --> `endianness` in 6 files.
There is one more in `shlr/zip/zlib/crc32.c` but that seems to have an external source.
=> Fix 8 typos in 6 files

libr/bin/format/le/le.c, libr/bin/format/le/le.h, test/db/formats/le
This change introduces the optional environment variable `R_LE_BASES` which can contain a `:`-separated list of addresses where the base of each defined object should be. This can be used to easily match the same memory layout as a running DOS system can have while debugging.
The env variable is not great, but it's needed since each object is rebased independently, instead of "rigidly translated" like is more common on modern systems where the existing concept of a single base address would suffice.
=> Rebase LE objects independently ##bin

libr/arch/p/bpf/plugin.c
strnlen(3) might not be available on older systems e.g OS X Tiger.
=> libr/arch/p/bpf/plugin.c: Use r_str_nlen

libr/debug/p/native/xnu/xnu_debug.c, libr/debug/p/native/xnu/xnu_threads.c
`ppc_debug_state_t` was never type defined.
=> Guard off parts which do no apply to Darwin/PowerPC

libr/core/cmd_anal.inc.c, libr/core/cmd_search.inc.c
Fixes two minor typos in command help text
=> Typo fixes in command help

libr/core/rtr.c, libr/io/p/io_ptrace.c
=> Fix unaligned ptrace reads - spotted on s390 ##debug

libr/util/str.c
This adds support for reflecting the status of sanitized builds compiled with `gcc` < 14 when running `-v`.
=> Show ASAN in -v options when compiling via `gcc` ##shell

libr/anal/jmptbl.c, test/db/anal/arm
The cases in ARM switch-case is looking a bit funky at the moment.
The cases are actually jump instructions (not integers) and thus, need to be treated as code.
For this, I've added a switch to turn off the hint insertion at the case locations for this arm-style jmptable.
=> Fix jmptable analysis on ARM ##analysis

libr/debug/p/native/xnu/xnu_threads.c
=> Do not make THREAD_CONVERT_THREAD_STATE_TO_SELF mandatory for old macs

binr/r2r/run.c
There's a bit of a problem with r2r on Android aarch64.
```
$ r2r test/db/asm
INFO: Running from /data/data/com.termux/files/home/project/radare2/test
Already up to date.
Loaded 10298 tests.
INFO: Skipping json tests because jq is not available
[41/10298]                 41 OK         0 BR        0 XX        0 FXFORTIFY: pthread_mutex_unlock called on a destroyed mutex (0xb400007303ff884c)
[1]    6672 abort      r2r test/db/asm
```
This patch makes sure that sigchild thread will fire a signal to the subprocess wait func only after it has done with the lock.
Also a small fix about unlocking an unlocked lock.
=> Fix concurrency issue ##test

libr/egg/egg_lang.c, test/unit/test_egg.c
**Description** 
Ragg2 when processing immediate strings in function call arguments previously didn't save call returns due to the string processing. String processing now creates a temporary destination variable, and frees that, allowing for the destination variable to be processed. 
Haven't fully checked ASAN output yet.
=> Ragg2 FIx Saving Call Returns

libr/core/cmd_search.inc.c
=> Remove all globals from search ##globals

libr/core/disasm.c
=> Fix 32bit value displayed twice in disasm on big endian hosts

libr/core/p/core_sixref.c
* This was fixed three years ago, but never synced back
* https://github.com/Siguza/misc/commit/222e14da3cb57118ed0c8e28eba99a85df7e4742
=> Fix #22939 - ub shifts on sixref ##analysis

libr/bin/format/mdmp/mdmp.c
radare2 blindly allocates memory according to size fields in the
minidump.  This size field was misinterpreted on big endian.
=> Fix mdmp list sz ##endian

libr/main/radiff2.c, test/db/tools/radiff2
=> radiff2 -A = aa instead of aaa ##tools

test/unit/test_scanf.c
Fixes a bug where format string arguments were given incompatible
pointers.
=> Fix test_r_str_scanf_procstat

libr/core/cmd_anal.inc.c
=> Fix infinite loop in the afla command spawned by a^5 ##crash

libr/core/cmd_seek.inc.c, test/db/cmd/cmd_seek
=> Fix s+0x1000000000 ##shell

libr/bin/bin_write.c, libr/bin/format/elf/elf_write.c, libr/core/cmd_anal.inc.c, libr/include/r_bin.h, libr/main/rabin2.c, test/db/formats/dwarf
=> Support resizing the BSS section with rabin2 -O ##bin

libr/core/cmd_info.inc.c, test/db/cmd/cmd_ih
=> Bring back the ig command to guess binary size ##bin

libr/arch/p/arm/pseudo.c, test/db/cmd/cmd_pdc
=> Fix asm.pseudo for arm64's movk ##disasm

libr/bin/format/mach0/dsc.c, libr/bin/format/mach0/mach0.h, libr/io/p/io_dsc.c
iOS 18 beta introduces a couple new fields to the dyldcache header, the purpose of which is still unclear to me (and it reflects on the bad names i gave 'em) but broke the heuristics for detecting the subcache info format. This change leverages the first of the two new fields to update the format detection logic.
The other big issue was that r2's Mach-O size was represented as an `int`, but the new dyldcache have a logical combined size which now requires 33 bits 😅 , so our bounds checking code was overreacting. Fixed by bringing the `size` field up to `ut64` capacity.
=> Fix dyldcache parsing for iOS 18 beta changes

libr/core/cmd_info.inc.c, test/db/json/cmd_i, test/db/json/json2
=> (r2) i cmd: consistent json output when no file is loaded

libr/bin/format/ne/ne.c
=> Fix bin.ne endian

libr/bin/p/bin_dyldcache.c
The dyldcache-specific logic which parses library-loading Mach-O load commands to carve dependencies in order to filter them was wrongly assuming the path of the loaded library is always at offset 24 instead of looking up the right offset from the command itself.
While this was working 99.99% of the times, when it didn't it broke the deps carving logic and produced weird-looking "alien dep" errors.
=> Fix dyldcache deps carving logic ##bin

libr/core/visual.c, libr/debug/p/native/xnu/xnu_threads.c
lots of panels to change and more refactoring to do, but at least its accessible and listed in human readable form. discussions are more than welcome on this
=> Implement Vbw command to browse window types in visual ##visual

libr/core/cmd_zign.inc.c
=> Add command name comments to libr/core/cmd_zign.inc.c

libr/core/cconfig.c, libr/core/cmd_anal.inc.c, test/db/anal/avr, test/db/anal/emu, test/db/cmd/r2pipe2, test/db/formats/elf/helloworld-gcc-elf
=> FIx aaa for x86-32 systems and ensure aaef is used ##analysis

libr/main/radiff2.c
=> Check and early fail if symbol existance in radiff2-g ##diff

shlr/qjs/Makefile, shlr/qjs/package.json
=> WIP: Update to the latest r2papi typescript api

libr/core/cmd_info.inc.c, test/db/cmd/cmd_i, test/db/json/cmd_i
I'm still unsure if we should drop an error in some cases, as happens in the second one:
```
[0x00000000]> iDj
{}
[0x00000000]> iDj xxx
ERROR: Missing or unknown language.
{}
[0x00000000]> iDj swift xxx
{"lang":"swift","mangled":"xxx","error":"Cannot demangle string"}
```
The thing is that iD without params doesn't drop any kind of error but a help message, so in that case maybe an empty json is just ok.
=> Add json support to iD command ##shell

libr/core/panels.c
=> Add manpage submenus for the Help menu ##panels

libr/core/cmd.c, libr/util/token.c
=> Fix 'Cannot redirect the same fd twice' bug in the command parser ##shell

libr/core/cmd.c
=> Add a warming help message under the `help` command ##shell

libr/core/cmd_quit.inc.c
=> Honor numeric argument in q!! and simplify command logic ##shell

libr/bin/p/bin_p9.c
Symbol parsing for Plan9's a.out files was failing both because the content of type `Z` (which is currently ignored) was not being discarded, and because a UT8_MAX (255 or 0xff) was being read in the PC table and treated as an error when it is actually a valid value.
=> Fix the symbol parsing in Plan9

libr/io/p/io_dsc.c
Add the iP command to the dsc io plugin, to get **i**nfo about a **P**ointer. That draws information from the underlying rebase infos which are embedded in the pointer itself (whose semantics potentially changes over different maps), which otherwise gets lost as part of rebasing / pointer cleanup.
This is especially useful for getting info about pointer authentication, like the **diversity** and the **key** to use if there's any need to ever re-sign a pointer from the dyld cache.
The usage is `:iP [size][@vaddr]` if no size is provided defaults to 8, runs at current seek (or virtual seek if provided). The output is JSON only.
Example:
```
> pxq 8@0x1f242f210
0x1f242f210  0x00000001b972985c                       \.r.....
> :iP @0x1f242f210~{}
[
{
"paddr": "0x707b7210", …
```
=> Add iP command to dsc ##io

libr/core/cconfig.c, libr/core/cmd_anal.inc.c, test/db/cmd/r2pipe2
=> Make anal.vinfun false by default ##analysis

libr/anal/var.c, libr/core/canal.c, libr/core/cmd_anal.inc.c, libr/include/r_anal.h, libr/include/r_types.h, test/unit/test_anal_var.c
=> Reuse R_PERM in RAnalVarAccess.type instead of custom enum ##analysis

.github/workflows/build.yml, .github/workflows/ci.yml
=> Get rid of the deprecated macos-11 github targets ##ci

dist/plugins-cfg/plugins.def.cfg, libr/bin/p/Makefile, libr/bin/p/bin_uf2.c, libr/bin/p/uf2.mk, libr/core/cfile.c, libr/include/r_bin.h
=> Initial support for RBin->RIO redirections ##bin

libr/anal/sign.c, libr/core/cconfig.c, test/unit/test_sign.c
Probably solves the issue #22901. I removed the code that creates new signatures from the same functions.
=> Remove duplicated function signature entries

dist/plugins-cfg/plugins.def.cfg, libr/include/r_io.h, libr/io/meson.build, libr/io/p/io_uf2.c, libr/io/p/uf2.mk, libr/meson.build
Initial uf2:// io plugin.
Many functionalities still need to be implemented (write, checksum validation, file container, ...)
=> WIP: Initial support for UF2 file format #io

libr/bin/p/bin_dyldcache.c, libr/io/p/io_dsc.c
This PR brings three changes:
- add the `:iF` command to get information about what file is contributing the physical address corresponding to the current seek. This is mostly useful for multi-file caches.
- set the dyldcache entry point to the first map (the one which maps the offset 0) so the user is pointed by default to an address which is mapped (instead of being left floating over address 0 which is unmapped).
- create sections for stub islands: modern multi-file caches clump all import stubs in "stub islands". These live in specific stub-only subcaches which can be detected by checking that they contain no images and have only one `r-x` mapping which extends beyond the cache header page. This change creates specific sections called `STUB_ISLAND` (followed by an …
=> Improve dyldcache ##io and ##bin

libr/bin/format/objc/mach0_classes.c, libr/bin/mangling/swift-sd.c, libr/bin/p/bin_dyldcache.c, test/db/cmd/classes, test/db/formats/mach0/fatmach0, test/db/formats/mach0/objc, test/db/formats/mach0/swift, test/db/formats/mangling/swift
Use `r_bin_demangle_swift` to demangle Swift Objective-C classes in the couple of places where that was missing, and ensure all parsed classes have `index` set, to allow coexistence of different categories with the same name.
=> Fix Objective-C classes Swift demangling ##bin

libr/asm/filter.c
`ut8 *ip = (ut8*)&ip32` is assuming that the host machine is little-endian. The fix makes the code endianness-independent.
=> Fix improper display of IPv4 addresses in big-endian machines

libr/bin/format/mz/mz.c
The comment in the code says it all:
```
// TODO: read field by field to avoid endian and alignment issues
...
// dos_header is not endian safe here in this point
```
A struct is directly loaded in a single read operation, so, on machines with a different endianness than the file format, loading failed.
Reading field by field using `r_read_le16` fixes 10+ tests.
=> Fix incorrect parsing of MZ headers in big-endian machines

libr/core/disasm.c, libr/util/buf.c
=> Fix asm.emu derefenced word issue on big endian ##disasm

libr/core/cio.c
Avoids unnecessary iteration of all the sections to get the value of bits and arch, in case they're both fixed.
Not a big deal most of the time, unless you try to emulate code in a binary which has a lot of sections (like an unfiltered dyld cache).
=> Don't ask sections if fixed arch / bits are set ##core

libr/core/cmd.c
They're already set back to the original value on the `is_arch_set` / `is_bits_set` branches above, removing the second restoration allows for actually setting them via the `anal.fixed.arch` / `anal.fixed.bits` configs.
=> Avoid over-unsetting fixed arch / bits ##core

libr/core/canal.c, test/db/anal/loongarch, test/db/anal/mips, test/db/esil/arm_64
This prevents a scenario in which an invalid instruction also invalidated the next ones, causing missing references.
=> Fix aae behaviour on invalid instructions ##core

libr/debug/p/native/bsd/bsd_debug.c
Use the p_stat of the main thread to decide in which state the process is. For multi-threaded applications this is still not quite correct but at least this compiles on OpenBSD-current.
See also https://github.com/openbsd/ports/commit/290aac569141a2c69255a1dc864d2053249031e1
Fix for #23158
=> Adjust OpenBSD code to set the process state to be less wrong.

libr/core/cmd_search.inc.c
`aac` on rebased (`-B`) files searches incorrect ranges. The impact of this is that it breaks autoanalysis of rebased files.
This issue was introduced by the following commit:
```
commit dec3698578a0057703af07b2f679f18bf6563c00
Author: pancake <pancake@nowsecure.com>
Date:   Fri Feb 16 12:52:27 2024 +0100
Fix aac bug caused by anal.in on binaries with sections ##analysis
```
Below is a short description of my findings: 
In the function `cmd_anal_calls` in `libr/core/cmd_anal.inc.c`:
```
RBinFile *binfile = r_bin_cur (core->bin);
addr = core->offset;  // <--- this address is correct
if (binfile) {
if (len) {
// not taken
} else {
ranges = r_core_get_boundaries_prot (core, R_PERM_X, NULL, "anal");
}
}
if (!binfile || (ranges && !r_list_length (ranges))) {
// Not taken
} else …
```
=> Fix aac on rebased files

libr/cons/input.c, libr/core/agraph.c
normal panning works now in termux. the graph follows the finger 
```
binr/radare2/radare2 -c "aa;s main;VV" binr/rabin2/rabin2
```
this branch emit the horizontal codes
https://github.com/john-peterson/termux-app/tree/scroll
=> horisontal swipe in termux

libr/core/disasm.c, libr/core/pseudo.c, libr/util/format.c
=> Fix null format when displaying unknown argument types ##decompiler

libr/arch/p/lua/lua53_parser.c, libr/bin/p/bin_lua.c
Primarily this is a refactor of some of the bin lua code. I hope to add more lua versions, but first I will remove the global.
This is a WIP but you may want to merge now because it fixes a bug.
Lua 5.3 files won't load properly because a mistake with `sizeof` [here](https://github.com/radareorg/radare2/blob/3e169c2b7e28e8a989ab773dfda75ca2ba7395ac/libr/bin/p/bin_lua.c#L51) will prevent the header parsing function from getting a large enough buffer to work.
=> Start refactoring lua #bin

libr/arch/p/mips/plugin_cs.c
Add missing translation for MIPS `movn` instruction.
Its a conditional move instruction with semantics
movn d,s,t      if (t) d = s;
Which is quite similar to the existing:
movt d,s,$fccN  if (fcc(N)) d = s;
In fact, we can reuse the exact same implementation.
PS: Would be nice if someone could explain to me what the `$z` does and why it is there.
=> Add ESIL translation for `movn` instruction (fixes #23286) ##emu

.github/workflows/build.yml, sys/wasi-api.sh
Renamed WASI API zip (and subfolder) to include -api in their name.
And added into the release files list.
=> Add WASI API into release files

libr/bin/mangling/swift-sd.c
=> Fix null deref bug in the swift demangler ##crash

libr/arch/p/mips/plugin_cs.c, libr/arch/p/mips_gnu/plugin.c
The semantics of `movn` and `movt` are:
```
MOVN rd, rs, rt
If the value in GPR rt is not equal to zero, then the contents of GPR rs are placed into GPR rd.
```
and
```
MOVT rd, rs, cc
If the floating-point condition code specified by cc is one then the contents of GPR rs are placed into GPR rd.
```
respectively.
Thus, my previous assessment in #23295 that the same case can be used is wrong. This PR should correct the situation by giving it its own case. It also adds the insn for GNU Mips.
=> Fix ESIL of `movn` insn (MIPS) ##emu

libr/core/canal.c
=> Assume x27 as global pointer only in dart binaries ##analysis

libr/core/cmd_search.inc.c
When using /cp if pubkey parameter was not supplied it resulted in a segfault.
`
[0x00000000]> /cp ed25519 
WARN: r_str_trim_head_ro: assertion 'str' failed (line 110)
[1]    956100 segmentation fault (core dumped)  r2 file.bin
`
This patch displays back the help instead of crashing r2.
=> Fix /cp segfault on missing key

libr/core/cmd.c, libr/util/unum.c
=> Improved syntax error handling on tmpseek expressions ##shell

preconfigure.bat
=> Throw error when python>3.11 in preconfigure.bat ##build

preconfigure.bat
Now it will work. batch error handling is a mess.
=> Fix preconfigure.bat setuptools installation ##build

libr/cons/html.c, test/unit/test_cons.c
The font HTML element is deprecated.
- [/] I wrote some lines in the [book](https://github.com/radareorg/radare2book) (optional)
=> Emit span instead of font in the scr.html filter ##cons

libr/bin/p/bin_lua.c
Fixes double free, list elements are freed by plugin caller so I had to duplicate them.
=> Fix double free in lua ##bin

libr/core/cmd_print.inc.c, test/db/cmd/cmd_print
`ps` command with leading zeros is no expected to print the string. Simplify help message of `ps` as well.
=> Remove broken test and minor help message fix

libr/main/rafind2.c, man/rafind2.1
- [ * ] Mark this if you consider it ready to merge
This PR adds support for the `V` flag in the `rafind2` command, enabling value-range searches as specified in issue [#22704](https://github.com/radareorg/radare2/issues/22704). Users can now specify a range of values using the format `/V<size>:<min_value>[,<max_value>]`, which enhances data manipulation capabilities. The implementation includes input parsing and size validation.
Please review my implementation and provide feedback.
=> Added support for /V range search logic

libr/anal/block.c, libr/anal/fcn.c, libr/core/canal.c
=> Fix #21171 - Infinite loop caused by a weak tovisit check on large functions

libr/core/cmd.c, libr/core/cmd_help.inc.c
Making help messages more clear and easy to understand by improving wording. Finding inconsistent, duplicated commands, etc.
Issue #23392
=> WIP: Improve help messages

libr/search/sm4_find.c
The SM4 key is not directly in the key schedule as for AES. Adds a log message in `/ca` with the key value to help analysis.
=> Display SM4 master key when found

libr/core/cmd_help.inc.c
=> Invalid h subcommands dont flush the error text ##shell

libr/core/cmd_print.inc.c, libr/include/r_util/r_asn1.h, libr/util/asn1.c, test/db/cmd/cmd_pFa
This PR aims at enhancing the `pFa` command output with the following:
- Fix length miscalculation
- Add header on `pFa` output for better understanding
- Change the output format of some ASN.1 tags (hexstring), truncate to 100 characters if too long
- Tree view using `pFat`
=> WIP: ASN.1 printings enhancements

libr/search/sm4_find.c
- [* ] Mark this if you consider it ready to merge
Add the offset to the SM4 "Master key found" message
=> Add offset on MK hit for SM4 ##crypto

libr/core/cmd_help.inc.c, libr/core/numvars.inc.c, libr/io/p/io_gdb.c, libr/io/p/io_mach.c, libr/io/p/io_ptrace.c, libr/io/p/io_winedbg.c, test/db/archos/linux-x86_64/dbg_oo
=> Revert e0b19776681 - bring back the full IO address space ##debug

libr/core/disasm.c, test/db/cmd/cmd_pd
- [ X ] Mark this if you consider it ready to merge
- [ X ] I've added tests (optional)
Currently, when using negative numbers in the `pdj` command, in `r_core_print_disasm_json_ipi` a new offset (computed going backward) is assigned to the `core->offset` variable. However, the `old_offset` is not restored before returning from the function, which has the undesired side-effect that the cursor goes back after the command (annoyingly breaking r2pipe automations).
PoC:
radare2 version:
5.9.6-158-gc72b9514ad
This pull request should fix this behaviour.
Same command, with the patch:
=> Fixed old_offset not restored on pdj ##print

libr/anal/anal.c, libr/include/r_io.h, libr/util/print.c
both previously existing uses of r_io_bind_init were applied to instances of RIOBind, which were previously allocated with R_NEW0, so r_io_bind_init cleared memory, that was already clear.
r_io_bind_init no longer calls memset
=> Remove needless uses of r_io_bind_init

libr/bin/dwarf.c, test/db/formats/dwarf
=> Print MD5 checksum when available in DWARF5

libr/core/Makefile, libr/core/cconfig.c, libr/core/core_esil.c, libr/core/meson.build, libr/esil/esil.c, libr/esil/esil_handler.c, libr/esil/esil_plugin.c, libr/include/r_core.h, libr/include/r_esil.h, libr/include/r_io.h, libr/io/io.c
=> WIP: Start refactoring of esil engine

libr/core/core_esil.c, libr/include/r_core.h, libr/include/r_esil.h
=> Prepare core_esil trap revert feature

libr/esil/esil.c, libr/include/r_esil.h
=> Start integrating new esil stuff

libr/io/p/io_r2k.c, libr/io/p/io_r2k_linux.c
=> Use R_LOG messages in the r2k plugin ##io

libr/arch/p/gb/gb.h, libr/arch/p/gb/plugin.c
It has never been utilized as intended, mostly because analysis doesn't necessarily go lineary through functions. Also depending on anal is an artefact of the old analplugin architecture. this has fallen out of time
=> Kill GBUser

libr/core/cmd_open.inc.c
=> Fix uninitialized vsize variable warning

libr/core/cmd.c
=> Fix #14779 - Check number errors when parsing @@= args ##shell

.github/workflows/build.yml, .github/workflows/ci.yml
update macos github action runner images. probably not critical but ive been watching this project for a little while and keep seeing these failures
>The macOS-12 environment is deprecated, consider switching to macOS-13, macOS-14 (macos-latest) or macOS-15. For more details, see https://github.com/actions/runner-images/issues/10721
example failures:
- [radareorg/radare2/actions/workflows/build.yml](https://github.com/radareorg/radare2/actions/workflows/build.yml?query=branch%3Amaster)
- [macos-acr (x86_64, 12)](https://github.com/radareorg/radare2/actions/runs/12418209216/job/34670912552)
- [ios (cydia)](https://github.com/radareorg/radare2/actions/runs/12418209216/job/34670908821)
- [ios (cydia32)](https://github.com/radareorg/radare2/actions/runs/12418209216/job/34670909 …
=> Update macos github action runner images ##build

dist/macos/build.sh
As it has been requested:
https://github.com/radareorg/iaito/issues/170#issuecomment-2130003128
This PR intends to change all artifact names from `m1` to `arm64`.
> [!Note]
> The rest of the projects will need to update the download path when they want to update to the next radare2 version in their workflows if this PR gets merged.
=> Rename m1 to arm64 for mac builds

libr/anal/xrefs.c
=> Fix random segfault caused by unaligned fields on macos-m1 ##crash

.github/dependabot.yml, .github/workflows/ci.yml, .github/workflows/qemu.yml
Enable Dependabot just for GitHub Actions dependencies.
Configure the commit message to start with `##build ` (there is no setting to set suffix instead of prefix).
Also update upload-artifact to v4.
=> Enable Dependabot and update some GitHub Actions

.github/workflows/build.yml
Update action-gh-release to v2.2.1.
Hopes to fix Dependabot fail when detecting versions.
=> Update action-gh-release to v2.2.1 ##build

libr/arch/p/x86/plugin_cs.c
This sets ->ptr and other values when the operand points to memory.
Partial fix for issue #23857.
As per discussion in #23857, additional instructions now have operands handled.
Some - like rotate and shift instructions - only take memory address in the first operand. Some already had equivalent parsing, e.g. `cmp*` instructions are covered by the `inscmp()` function.
This PR doesn't change any of the MMX/SSE/AVX instructions, which need a bit more thought as some take three operands / 128 bit memory pointers etc.
Tests still required.
=> Improve operand parsing for more instructions

libr/arch/p/pickle/dis_helper.inc, libr/arch/p/pickle/plugin.c, libr/arch/p/pickle/pseudo.c
This is still not quite right but all opcodes are supported.
```
r2 -a pickle -qc 'af+ $$ main; afb+ $$ $$ $s;pdc' selfref/dict.pic
// callconv: x0 reg (x0, x1, x2, x3);
int main (int argc, char **argv, char **envp) {
loc_0x00000000:
stack.append({})
memo[len(memo)] = stack[-1]
stack.append("selfref") // 0x4
stack.append(memo[0x0])
key = stack.pop()// value = stack.pop()// stack[-1][key] = value
return stack[-1]
return x0;
}
```
I guess I need to set up analysis to fix return. Also, I don't think I quite understand how pseudo is suppose to work. This parser is getting previous output as input?
So if you want to wait until I figure that stuff out to accept, that is fine.
=> Add last pseudo instructions to pickle ##arch

libr/arch/p/x86/plugin_cs.c, test/db/esil/x86_32
=> Fix parsing of memory operands for x87 FPU instructions ##arch

libr/core/cmd_debug.inc.c, libr/core/cmd_open.inc.c, libr/debug/p/debug_native.c, libr/include/r_io.h, libr/io/io_map.c
=> WIP: RIOMaps should have a 'kind/klass' attribute

libr/anal/fcn.c, libr/anal/jmptbl.c, libr/core/cmd_anal.inc.c, libr/include/r_anal.h
Missed when grepping for R2_600 renaming stuff.
=> Rename try_walkthrough_jmptbl -> r_anal_jmptbl_try_walkthrough

libr/anal/vtable.c, libr/include/r_util/pj.h, libr/io/io_map.c, libr/util/pj.c
=> Fix few low hanging memleak fruits

libr/main/rahash2.c, test/db/tools/rahash2
- [ x] Mark this if you consider it ready to merge
- [ x] I've added tests (optional)
This should be a straight-forward code change to ensure `> rahash2 -a ssdeep -j /path/to/bin` actually prints the correct `ssdeep` hash as expected.
This is my first PR. I believe I followed everything correctly and expect this to be good to go, but I'm happy to learn and make updates if needed. Specifically, I:
* Recompiled and tested the expected output locally
* Added a test and reran the `r2r` test suite. Everything finished and I didn't see my test throw an error but I was unclear on how to specifically confirm that my new test actually ran.
I tracked some of my analysis to identify the fix on my personal fork [here](https://github.com/mattunleashed/radare2/issues/1).
=> Fix #23937 - fix rahash2 JSON ssdeep output ##json ##print

libr/debug/p/debug_native.c, libr/debug/p/native/bsd/bsd_debug.c, libr/io/p/io_self.c
=> Fix FreeBSD/arm64 support

libr/crypto/hash/hash.c, test/db/cmd/cmd_i
- [x ] I've added tests (optional)
This PR fixes a bug similar to the one fixed in https://github.com/radareorg/radare2/pull/23938. Since a `ssdeep` hash is a printable buffer, we can just print it straight away instead of printing the hex representation.
=> Fix #23930 - fix ssdeep output formatting

shlr/gdb/src/arch.c
In the `parse_def` function, `r->name` is a buffer that holds the name of a register. However, it is only 32 bytes in size. But in the arch_parse_reg_profile function, there is a buffer `tmp` which is `128` bytes long and is used to hold parsed tokens from the `reg_profile` string.
As you see in `parse_def`, The **strcpy** function is used to copy the string from `tok[1]` into `r->name` and there is no check to ensure that `tok[1]` will fit into `r->name` (which is only 32 bytes). To fix this issue, I replaced `strcpy` with `snprintf`, which allows you to specify the maximum size of the destination buffer, ensuring that the string is copied safely and that the buffer boundary is respected.
=> fix(parse_def): prevent buffer overflow in register name copy

libr/arch/p/x86/plugin_cs.c
* Fix 'ERROR: No regprofile from debug plugin (esil) for (x86)' error
=> Fix x86.multibits esil debugger ##debug

libr/core/core_esil.c
`core->esil.cmd_intr`is checked but `core->esil.cmd_todo`is called
=> Fix wrong command called on core_esil_op_interrupt ##esil

libr/bin/format/mach0/mach0.c
This will honor the right crypto value inside SDB when parsing a Mach-0 File.
=> fix: store the right crypto value in SDB when parsing Mach0

libr/arch/p/pickle/dis_helper.inc, libr/arch/p/pickle/plugin.c, libr/arch/p/pickle/pseudo.c
Fix gcc 12.2.0 segfault ##crash
gcc 12.2.0 segfaults prior to these patches when compiled with any
optimization level:
```bash
$ make clean && ./configure && CFLAGS=-O2 make -j 4
```
which produces:
```
during RTL pass: expand
p/pickle/plugin.c: In function ‘pickle_encode’:
p/pickle/plugin.c:632:17: internal compiler error: Segmentation fault
632 |                 switch (ob) {
|                 ^~~~~~
0x7fc4bd56604f ???
./signal/../sysdeps/unix/sysv/linux/x86_64/libc_sigaction.c:0
0x7fc4bd697f7a __memset_avx512_unaligned_erms
../sysdeps/x86_64/multiarch/memset-vec-unaligned-erms.S:236
Please submit a full bug report, with preprocessed source (by using -freport-bug).
Please include the complete backtrace with any bug report.
See <file:///usr/share/doc/gcc-12/README.Bugs> …
```
=> Circumvent gcc 12.2.0 segfault

libr/main/r2pm.c
This commit adds an environment variable for `MANDIR` which can be used by `r2pm` managed plugins to determine where to place any manfiles they contain.
Currently `r2pm` doesn't provide a consistent way to handle manfiles provided for the plugins it installs. This MR adds a directory under the `r2_prefix` for this. It'll end up being something like `$HOME/.local/share/radare2/prefix/man`.
NOTE: This relies on the behavior of how a `manpath` is constructed where `../man` (and `../share/man`) are both added to the `manpath` if they exist for a given element in `PATH`. This means manpages will only be accessible if the user has added the `R2PM_BINDIR` to their `PATH`. We deliberately do _not_ set the `MANPATH` explicitly as it will override manpage discovery based on `PATH` …
=> r2pm: Add env for man pages.

libr/io/io.c
=> Fix #23966 - Avoid %p on windows because is not prefixing with 0x ##crash

shlr/zip/zlib/inflate.c
This PR fixes a security vulnerability in inflate() that was cloned from zlib but did not receive the security patch applied in zlib. The original issue was reported and fixed under https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1.
This PR applies the same patch as the one in zlib to eliminate the vulnerability.
**References**
https://nvd.nist.gov/vuln/detail/CVE-2022-37434
https://github.com/madler/zlib/commit/eff308af425b67093bab25f80f1ae950166bece1
=> Fix: Potential Vulnerability in zlib Library

test/db/anal/aavr
Tests the usage of `aavr` to find references to async Swift tasks, by setting `anal.in` accordingly.
Depends on https://github.com/radareorg/radare2-testbins/pull/105
=> Add test for aavr on async swift binary

libr/core/cmd_anal.inc.c, test/db/anal/aavr
When `bin.lang` is set to `swift`, the `aaa` command will now also run `aavr@e:anal.in=bin.sections.rw`.
This helps finding references to code from Swift metadata.
=> Run aavr during aaa on Swift bins ##core

libr/core/cmd.c
Before:
```
{"platform":"Darwin","arch":"arm","bits":1}
```
After:
```
{"platform":"Darwin","arch":"arm","bits":64}
```
spotted because of a compiler warning
=> Fix type for uname bits

libr/anal/global.c, libr/core/cbin.c, libr/core/cmd_anal.inc.c, libr/core/cmd_flag.inc.c, libr/core/cmd_print.inc.c, libr/core/core.c, libr/core/disasm.c, libr/core/vmenus.c, libr/flag/flag.c, libr/include/r_flag.h, test/db/formats/dwarf
The RFlagItem has several metadata fields: color, comment, alias, type​. These provide useful annotations (color coding, comments, expression alias, and a user-defined type tag). If any of these are rarely used or redundant, they could be candidates for removal in a future major version to streamline the struct. For example, if “type” is not actively used by radare2 (one might check how it’s used in practice), its purpose might be covered by either flag spaces or tags. If so, it could be dropped. However, removing a field is a breaking change, so only do so with strong justification (memory savings or replacing with a better system).
=> Reduce memory moving barely used RFlagItem fields into Meta ##performance

libr/bin/p/bin_dyldcache.c
Because it's not the same as `__objc_catlist`, so attempting to parse the same structures there fails with noisy warnings.
=> Skip __objc_catlist2 in dyldcache parsing ##bin

.github/workflows/build.yml, libr/core/xpatch.c
=> Fix maybe-uninitialized warn from ubuntu22 gcc in xpatch

libr/core/cconfig.c
Fix `e emu.maxsize` getter and sets its default value to 128M.
=> Fix emu.maxsize getter and sets default value to 128M

libr/anal/reflines.c, libr/core/cconfig.c, libr/core/disasm.c, libr/include/r_anal.h, libr/include/r_anal/op.h, test/db/cmd/metadata
=> Implement asm.lines.split to show backward branch lines in a separated column ##disasm

libr/anal/flirt.c, libr/util/buf.c, libr/util/unum.c
=> The 's' suffix in numbers work as an alias for 'seconds' ##analysis

meson.build
Since 1d51641e9b725a2d09b31ae7f7b2e5fd0fd4c5fb, a static library is being installed as if it was a shared library. Besides not working, this causes a warning message every time `ldconfig` is run in the machine.
Probably 1d51641e9b725a2d09b31ae7f7b2e5fd0fd4c5fb was intended to fix the issue where the `r2sdb` tool does not work since it is linked to `libsdb.so`. This pull request fixes that issue by installing the correct file, with the correct name. The original original fix is not very clean, this one also isn't very clean, and I apologize since I don't have enough experience with Meson to do it better. A cleaner fix would probably involve changing the libsdb project to somehow allow the parent project to control whether the library is installed when it is used as a …
=> Fix libsdb shared lib install ##build

sys/install.sh
The installation script `sys/install.sh` used `${SHELL} --help` to detect  fish shell, however the `fish` command does not have a `--help` argument. I changed it to `--version` which outputs something like `fish, version 4.0.0-g1e069b0`.
=> Fix Fish Shell Detection In The Install Script 

libr/core/project.c, test/db/cmd/projects
I had the issue with an AVR bare metal binary, that after saving and reloading the project, the selected fd was not restored. For some reason, this results in radare2 only showing 0x00 bytes (in `pd` and `px`). Only after selecting the correct fd using `o=X`, I could see the correct bytes again.
1. `r2 -a avr my-avr-binary.bin`
2. `aaaa` (creates fd 4)
3. ```
[0x0000a360]> o
3 * r-x 0x0001f800 my-avr-binary.bin
4 - rw- 0x000f0000 malloc://983040
```
4. `Ps project-name` and quit
5. `r2 -p project-name`
6. ```
[0x0000a360]> o
3 - r-x 0x0001f800 my-avr-binary.bin
4 * rw- 0x000f0000 malloc://983040
```
7. `o=3` to revert to the state in 3. and fixes 0x00 bytes explained above
The behavior with the changing fd selection after loading a project is reproducible with other binaries and …
=> Add current fd selection to project script ##projects

binr/r2r/run.c
=> fix memleak in function r2r_subprocess_init

.github/workflows/build.yml, .github/workflows/ci.yml
Update GitHub windows 2019 runners to 2022 since they will be deprecated:
- https://github.com/actions/runner-images/issues/12045
It is not `-latest` since there are also `windows-2025`.
=> Update windows GH runners ##ci

libr/util/print.c
- [X ] Mark this if you consider it ready to merge
Fix for the $ prefix for imm values in AT&T mode
I reverted the changes in the if statements at the beginning of the function, and added the colorization stuff in the '$' case:
=> Fix att imm display

libr/bin/format/p9/p9bin.c, libr/bin/format/p9/p9bin.h, libr/bin/p/bin_p9.c
Opening this as a draft since 9front RISC-V support is WIP, not yet upstream, bringup still being debugged.
See
- load address: https://shithub.us/moody/riscv/d82d996819447cd5896553a8405e51d43f9d0599/sys/src/9/riscv64/mkfile/f.html
- magic: https://shithub.us/moody/riscv/d82d996819447cd5896553a8405e51d43f9d0599/sys/include/a.out.h/f.html
I managed to get the disassembly, functions and symbols in r2. :partying_face:
=> Add initial Plan 9 RISC-V 64 support ##bin

libr/debug/p/native/reg/kfbsd-x64.h
rflags was defined twice and always printed warnings:
```
WARN: Duplicated register definition for 'rflags' has been ignored
```
=> Fix FreeBSD x64 register profile ##debug

shlr/bochs/src/libbochs.c, shlr/zip/zip/zip_hash.c
1. Fix memleak in function bochs_open
2. Revert #24289  for the incorrect modification：
Confirmed by the maintainer of libzip，there is no memory leak. The entry has already been added to the hash
=> Fix memleak in function bochs_open and revert PR-24289

libr/core/visual.c
Opening the visual prompt shouldn't change the configuration. Probably this was leftover debug code.
=> Don't rotate asm.emu on visual prompt

libr/bin/p/bin_xnu_kernelcache.c
=> Fix typo in xnu syscall detection

libr/bin/p/bin_xnu_kernelcache.c
Syscalls array was mapped off-by-one element on "modern" kernels.
=> Fix xnu kernelcache syscalls misalignment ##bin

libr/core/cmd_anal.inc.c
=> Fix typo in help for aaf? ##shell

sys/install.sh
Move argument parsing to the beginning. Otherwise the PREFIX is evaluated in sudosetup before it is set.
`sys/install.sh` tries to handle a situation where no `sudo` is required, e.g. `install.sh --prefix=/home/frukto/.local`. However the script fails to properly detect a user writeable prefix, because this is checked before arguments are parsed. This patch moves the argument parsing to the beginning.
=> Fix install script

libr/arch/p/arm/armass64.c, test/db/asm/arm_64
=> Fix #24520 - Fix arm64 assembler for ldr x0,[x27,0x100]' ##arch

libr/debug/p/native/xnu/xnu_debug.c, libr/debug/p/native/xnu/xnu_debug.h
There is no such header `mach/ppc/_types.h`. There is an arch-specific `ppc/_types.h` and generic `machine/_types.h`, which includes respective arch-specific headers. Since here it is used only for powerpc, `ppc/_types.h` should be the right one.
=> xnu_debug: fixes for powerpc

libr/bin/format/elf/elf.c
ELF parser can get stuck in loops in `parse_pt_dynamic()` and `dtproceed()`, as `PT_DYNAMIC` entries are not checked to lie within file, so r2 just reads 0 bytes many many times.
The higher the sizes, the longer it takes to open malformed files. This was enough to freeze my machine in a few seconds and eventually invoke OOM killer:
```sh
$ xxd hang.elf
00000000: 7f45 4c46 1000 0000 454c 4600 0000 e3ff  .ELF....ELF.....
00000010: 0000 c200 0000 6400 0000 0100 0000 0000  ......d.........
00000020: 0200 0000 0000 0000 1900 0000 0200 6900  ..............i.
00000030: 00ff 574c 4600 0001 1b00 0000 d600 0000  ..WLF...........
00000040: 0200 0000 0000 0000 1900 0000 0200 6900  ..............i.
00000050: 00ff 574c 4600 0001 1b00 0000 d6         ..WLF........
```
(similar thing was …
=> Fix elf parser hang on malformed PT_DYNAMIC entry ##bin

libr/util/sys.c, libr/util/udiff.c
Do not stop reading if SIGCHLD arrives as there might be more unread data in kernel buffer.
=> r_sys_cmd empty output fix

libr/core/cmd_mount.inc.c, libr/core/cmd_print.inc.c, libr/fs/meson.build, libr/fs/p/Makefile, libr/fs/p/fs_ubifs.c, libr/fs/p/ubifs.mk, libr/include/r_fs.h
Implement complete UBIFS (Unsorted Block Images File System) support for analyzing embedded filesystem images.
New filesystem plugin (fs_ubifs):
- Parse UBIFS superblock, master node, and index B-tree structure
- Read and cache inodes with directory entries and data nodes
- Support ZLIB compression using raw deflate format (no headers)
- Mount, directory listing, and file reading operations
- Proper offset reporting for compressed data nodes
New commands:
- prgr: Print raw deflate decompressed data without ZLIB headers Added for filesystems using raw deflate
- mis: Mount info + seek, combines mi and s commands Gets file offset/size and seeks to it in one operation
Fix #23463
Tested using OpenWRT UBIFS image.
```
[0x00000000]> m /mnt ubifs 0
INFO: Mounted ubifs on /mnt at 0x0
[0x00000000]> …
```
=> Add UBIFS filesystem plugin

binr/Makefile, binr/rafs2/Makefile, binr/rafs2/rafs2.c, libr/include/r_main.h, libr/main/Makefile, libr/main/rafs2.c, test/db/tools/rafs2
Introducing `rafs2`, a new command-line tool for working with filesystem images using radare2's filesystem plugins. Similar to GNU mtools but leveraging all radare2 filesystem support (ext2/3/4, FAT, NTFS, ISO9660, HFS, UBIFS, and more).
The tool makes use radare2's existing filesystem infrastructure and provides a standalone alternative to mounting images or using filesystem-specific tools.
Tests:
Added 14  tests covering all major operations across multiple filesystem types (ext2, FAT, NTFS, ISO9660)
```
rafs2 -h
Usage: rafs2 [options] -t <fstype> <file>
Options:
-t <type>    Filesystem type (ext2, fat, ntfs, iso9660, hfs, ubifs, etc.)
-o <offset>  Offset to mount filesystem (default: 0)
-m <path>    Mount point path (default: /)
-i           Interactive mode (shell)
-l <path>    List …
```
=> Add rafs2 - radare2 filesystem tool ##fs

libr/fs/p/fs_ntfs.c, libr/fs/p/fs_ubifs.c
Adds bounds checking for untrusted on UBIFS/NTFS filesystem data before memory allocation to prevent potential crashes or security issues from corrupted/malicious filesystem images.
=> Add boundary checks in UBIFS/NTFS filesystem parsers

libr/main/rafs2.c
Added r_list_free before all three returns in rafs2_details()
This ensures the RList allocated by r_fs_root() is properly freed, eliminating the resource leak
=> Added r_list_free before returning to prevent leaks
