radareorg/radare2

- libr/anal/p/anal_avr.c
- libr/asm/arch/avr/format.c
- libr/bin/format/pyc/marshal.c
- libr/core/anal_objc.c
> Fix the last covs reported in pyc/avr/aao

- libr/core/cmd_print.c
- libr/core/cmd_write.c
- libr/core/cmd_zign.c
- libr/core/linux_heap_glibc.c
- libr/search/strings.c
> Address dead code in widechar search spotted by coverity

- libr/asm/arch/8051/8051_ass.c
> Handle registers on push on 8051

- libr/asm/acode.c
- libr/main/rasm2.c
> Bind anal into rasm2

- libr/anal/esil.c
- libr/anal/p/anal_gb.c
> Fix formatting for some esil function calls

- Makefile
- binr/Makefile
- binr/r2pm/Makefile
- binr/r2pm/meson.build
- binr/r2pm/r2pm.c
- binr/r2pm/r2pm.sh
- libr/include/r_main.h
- libr/main/Makefile
- libr/main/main.c
- libr/main/meson.build
- libr/main/r2pm.c
- libr/util/sandbox.c
- libr/util/sys.c
> Initial implementation of r2pm.c ##r2pm

- libr/main/r2pm.c
> Fix typo ##r2pm

- .github/workflows/ci.yml
- libr/main/r2pm.c
- libr/socket/socket.c
- libr/util/sandbox.c
- mk/darwin.mk
- mk/ndk-gcc.mk
> Fix issues in r2pm -i acr

- libr/core/cconfig.c
- libr/core/disasm.c
- libr/include/r_util/r_print.h
- libr/util/print.c
> Add asm.bytes.opcolor configuration option

- libr/core/cconfig.c
- libr/include/r_util/r_sandbox.h
- libr/socket/socket.c
- libr/util/sandbox.c
- libr/util/sys.c
> Sandboxgrain

- binr/r2r/run.c
- libr/anal/cc.c
- libr/anal/type.c
- libr/asm/arch/pyc/opcode.c
- libr/bin/dwarf.c
- libr/bin/format/elf/elf.c
- libr/bin/format/wasm/wasm.c
- libr/core/anal_objc.c
- libr/core/canal.c
- libr/core/cmd_anal.c
- libr/core/cmd_print.c
- libr/core/cmd_search.c
- libr/core/cmd_write.c
- libr/core/visual.c
- libr/core/vmarks.c
- libr/main/r2pm.c
- libr/main/ragg2.c
- libr/search/keyword.c
- libr/search/uds.c
- libr/util/sys.c
- libr/util/table.c
- shlr/grub/fs/ntfs.c
- shlr/grub/fs/reiserfs.c
- shlr/grub/kern/disk.c
- shlr/java/class.c
- shlr/qnx/src/core.c
> Fix last covs on wasm binparser and r2pm-c

- libr/core/cmd_anal.c
> Add axl command for consistency with afl for 'axlc' ##analysis

- dist/rpm/radare2.spec
Remove old ones that dont exist any more and add new ones.
> Update doc files for rpm dist

- libr/core/cmd_info.c
- test/db/cmd/cmd_i
- test/db/cmd/cmd_open
> Fix #19534 - isqq. command ##bin

- libr/core/cmd_search.c
> Add help for /re? and handle invalid subcommands properly

- README.md
> Add 'first session' example in the README

- libr/anal/p/anal_x86_cs.c
> Add support for x86-32 callpop artifacts ##analysis

- libr/anal/arch/v850np/v850dis.c
- libr/bin/format/mach0/mach0.c
- libr/core/cmd_open.c
- libr/io/io_map.c
- libr/io/p/io_zip.c
Today's batch, and a couple older ones.
> Fix new coverity leaks

- libr/anal/arch/v850np/opc.inc
- libr/anal/arch/v850np/v850dis.c
> More esil support for v850.np

- libr/core/cmd_info.c
- shlr/sdb/Makefile
- shlr/sdb/config.mk
- shlr/sdb/src/array.c
- shlr/sdb/src/fmt.c
- shlr/sdb/src/journal.c
- shlr/sdb/src/json/js0n.c
- shlr/sdb/src/lock.c
- shlr/sdb/src/ls.c
- shlr/sdb/src/ns.c
- shlr/sdb/src/query.c
- shlr/sdb/src/sdb.c
- shlr/sdb/src/sdb.h
- shlr/sdb/src/text.c
- shlr/sdb/src/types.h
- shlr/sdb/src/util.c
> Update to the latest thread-friendly sdb

- test/Makefile
- test/db/extras/asm/evm
**Checklist**
Add test for evm plugin in radare2-extras.
> Add EVM test

- libr/anal/arch/v850np/opc.inc
- libr/anal/arch/v850np/v850dis.c
- libr/anal/p/anal_arm_regprofile.inc
- libr/anal/p/anal_v850_np.c
- libr/core/cmd_anal.c
> Fix help for the 'aaa' subcommands ##help

- libr/core/disasm.c
**Checklist**
fixed x86-16bit seg:off disassembly print for seg=0. now analysed function name can be correctly printet in disassembly.
tests done and requested in https://github.com/radareorg/radare2/pull/19607 PR
no issue was opened for that bug.
> fixed x86-16bit seg:off disassembly print for seg=0

- dist/plugins-cfg/plugins.def.cfg
- libr/anal/p/anal_evm_cs.c
- libr/anal/p/evm_cs.mk
- libr/include/r_anal.h
> Initial import of the evm.cs plugin ##arch

- libr/cons/cons.c
- libr/include/r_cons.h
- libr/io/p/io_tcpslurp.c
> Dont SIGINT in RCons when used in a thready way ##cons

- libr/anal/p/anal_evm_cs.c
- test/db/asm/evm.cs
**Checklist**
Instruction size can be 1 byte or more.
> Correct EVM instruction size and add tests

- libr/anal/arch/v850np/opc.inc
- libr/anal/arch/v850np/v850dis.c
> Add support for list12 parsing in v850.np ESIL distillate

- libr/anal/p/anal_x86_cs.c
- libr/asm/p/asm_x86_cs.c
- test/db/anal/x86_16
> Tests for x86 16 v2

- libr/cons/cons.c
- libr/include/r_th.h
- libr/parse/code.c
- libr/util/thread_lock.c
> Safe locks

- libr/anal/var.c
- libr/bin/p/bin_xnu_kernelcache.c
- libr/io/p/io_self.c
- libr/io/undo.c
- libr/magic/fsmagic.c
- libr/magic/mdump.c
> Address latest covs and remove some %zu format warnings

- .github/workflows/windows.yml
> Add 16GB pagefile for the windows ci ##build

- binr/r2r/run.c
- libr/util/strbuf.c
> Increase read buffers in r2r and strbuf

- libr/bin/format/mach0/mach0.c
- libr/bin/p/bin_coff.c
- libr/bin/p/bin_dex.c
- libr/core/cconfig.c
- libr/core/p/core_java.c
- libr/io/p/io_r2k_linux.c
- libr/magic/funcs.c
- libr/util/print.c
> Remove all the uses of %z as its not supported on Windows

- libr/anal/esil.c
- libr/anal/var.c
> Macrofication of the '+=' and '-=' esil operations ##esil

- libr/core/panels.c
> Fix #19409 - Close menu after creating a new panel from it

- libr/cons/cons.c
- libr/cons/cpipe.c
- libr/core/task.c
- libr/util/thread.c
- sys/sanitize.sh
> Fix disable-threads builds

- libr/cons/canvas.c
> Fix panel focus glitch ##visual

- libr/anal/Makefile
- libr/anal/p/anal_arm_cs.c
- libr/bin/format/pyc/marshal.c
- shlr/java/class.c
- sys/rebuild.sh
- sys/sanitize.sh
> Huntr fixes

- libr/bin/format/pyc/marshal.c
* Reported by Cen Zhang via huntr.dev
* Reproducer: bins/fuzzed/harep2.pyc
**Checklist**
> Fix UAF in pyc parser ##crash

- libr/core/panels.c
> Close menu when a different decompiler is selected ##panels

- libr/bin/format/dex/dex.c
* Reported by clusterfuzz
* Reproducer: bins/fuzzed/clusterfuzz-issue-44410-infloop-sample-5101731329998848
**Checklist**
> Fix DoS when loading a fuzzed DEX file ##crash

- shlr/java/class.c
* Reported by Cen Zhang via huntr.dev
* Reproducer: javaoob-havoc.class
**Checklist**
> Fix more oobread segfaults in the java parser ##crash

- libr/cons/d/bluy
> Fix visibility issue in the bluy theme ##cons

- .github/workflows/freebsd.yml
- README.md
> Add freebsd in github ci ##build

- libr/bin/format/mach0/mach0.c
* Reproducer: iafuzz-forever
**Checklist**
> Fix DoS in MACHO parser spotted by clusterfuzz ##crash

- .github/workflows/freebsd.yml
- README.md
> Publish FreeBSD artifacts and purge the srcdir ##ci

- libr/cons/pal.c
- libr/core/cmd_print.c
> Minor cleanup (-8LOC) in cons/pal.c

- libr/core/cmd_debug.c
> Fix #19617 - Use PJ in dij ##json

- libr/bin/bobj.c
- libr/bin/format/mdmp/mdmp.h
- libr/bin/format/mdmp/mdmp_pe.h
- libr/bin/format/pe/pe.c
- libr/bin/format/pe/pe.h
- libr/bin/format/pe/pe_write.c
- libr/bin/format/pe/pemixed.c
- libr/bin/format/pe/pemixed.h
- libr/bin/p/bin_mdmp.c
- libr/bin/p/bin_pe.c
- libr/bin/p/bin_pe.inc
> Cleanup varnames in PE and MDMP plugins

- libr/core/core.c
- libr/util/charset.c
- shlr/sdb/src/ns.c
- shlr/sdb/src/sdb.c
> Support local charset file loading and fix echo issue in sdb ##charset

- libr/core/cmd_print.c
> Fix ghosty allocation

- libr/core/cmd_flag.c
- libr/core/cmd_print.c
> Fix more harmless asan oobreads in pdu and fc

- libr/asm/arch/arm/armass.c
- test/db/asm/arm_32
> Fix cmn, teq and tst in arm32 assembler ##asm

- libr/bin/p/bin_elf.inc
- test/db/formats/elf/reloc
> Add ELF reloc patching for R_386_32 and R_386_PC32 ##bin

- libr/io/io_bank.c
* Associated with the CVE-2022-0559
* Reported by alkyne Choi via huntr.dev
> Properly fix the UAF in r_io_bank_map_add_top ##crash

- .github/workflows/freebsd.yml
> Run some tests in freebsd

- libr/bin/p/bin_dyldcache.c
* Reported by: Lazymio via huntr.dev
* Reproducer: dyldovf
```mermaid
graph LR;
Fuzz --> Crash;
Crash -->Verify;
Crash --> Fuzz;
Verify --> Report;
Report --> Fix;
Fix --> Verify;
Fix --> Publish
```
> Fix heap buffer overflow in dyldcache parser ##crash

- libr/core/cmd_print.c
- test/db/cmd/cmd_ps
- test/db/cmd/cmd_psj
> Fix #19729 - Make pswj consistent with psw output ##print

- libr/bin/format/mdmp/mdmp.c
* Reported by lazymio via huntr.dev
* Reproducer: mdmp-dos
> Fix DoS in the minidump parser ##crash

- libr/bin/format/mach0/mach064_is_kernelcache.c
* Reported by lazymio
* Reproducer z/rt/gwAAAEuAAB//wAAAACe2QEaAAAG+s8yAOH/AQAAAA==
> Fix DoS in kernelcache bin parser ##crash

- libr/bin/format/mach0/mach0.c
* Not really a DoS, but almost
* Reported by lazymio
* Reproducer:
zvrt/gCd7QBMYWT6AAD6/2NiQGsOAAGbuAAAADQAAID7AAAAAAEAAAEBZWUgcmR4LCByY3gBHQAAABEAAAAB/wAA7wABAAFiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiY2JiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJiYmJi/3///2KdYmJidmJiZc767QIA/38BAAr/7n/WAc767QAAAgD2AB0AABAFAAAVAQAAAAHv7+/v7+/v7+/v729jYWwvc2hhcmUvcmFkYXJlMi9wZGJ4QAAAAAQAAAEBYmVxPwCQHckEAAAAANBEyQR6ABQAkETJBAAAAAAhAAAAAAIAAAAQAAIAAAAQEAAAEgAAAAEAAABlYXhAKysBAA==
> Fix large loading times in macho parser ##bin

- libr/bin/format/pe/pe.c
- libr/bin/p/bin_dyldcache.c
- libr/bin/p/bin_psxexe.c
- libr/bin/p/bin_qnx.c
- libr/util/buf.c
* Reported by lazymio
* Reproducer: AAA4AAAAAB4=
> Fix DoS in PE/QNX/DYLDCACHE/PSX parsers ##crash

- libr/core/core.c
> Fix memory leak in RCore.cmdQueue

- libr/core/cmd_print.c
- libr/core/cmd_write.c
> Fix off by one read in psw

- shlr/sdb/src/cdb.c
- shlr/sdb/src/dict.c
- shlr/sdb/src/dict.h
- shlr/sdb/src/disk.c
- shlr/sdb/src/json.c
- shlr/sdb/src/json/path.c
- shlr/sdb/src/ls.c
- shlr/sdb/src/main.c
- shlr/sdb/src/query.c
- shlr/sdb/src/sdb.c
- shlr/sdb/src/sdb.h
- shlr/sdb/src/types.h
- shlr/sdb/src/util.c
> Sync sdb again from git

- shlr/java/class.c
> Fix timeout analyzing a small class reported by clusterfuzz ##crash

- libr/bin/bfile.c
- libr/main/radare2.c
- test/db/cmd/cmd_iz
> WIP: Honor maddr in izz ##bin

- libr/anal/anal.c
- libr/anal/class.c
- libr/anal/dwarf_process.c
- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_avr.c
- libr/anal/p/anal_s390_cs.c
- libr/asm/p/asm_dalvik.c
- libr/bin/bfile.c
- libr/bin/format/dex/dex.c
- libr/bin/format/elf/elf.c
- libr/bin/format/objc/mach0_classes.c
- libr/bin/format/pe/pe.c
- libr/bin/p/bin_pe.c
- libr/bin/p/bin_pe.inc
- libr/bin/p/bin_pe64.c
- libr/cons/canvas.c
- libr/core/agraph.c
- libr/core/canal.c
- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_print.c
- libr/core/cmd_search.c
- libr/core/p/core_java.c
- libr/main/rabin2.c
- libr/util/table.c
Fix lots of memory leaks for anal tests. Not totally clean yet.
> Significantly reduce memory leaks in anal tests

- libr/bin/bfile.c
Despite being reported leaked its shared with core
> Don't free binfile->sdb

- binr/r2r/run.c
- libr/anal/p/anal_ebc.c
- libr/asm/arch/arm/armass.c
- libr/asm/arch/riscv/riscvasm.c
- libr/asm/arch/z80/z80asm.c
- libr/asm/asm.c
- libr/asm/p/asm_x86_nz.c
Make asm tests leak-free. Includes a fix for a leak in r2r when running asm tests.
> Fix leaks in asm tests

- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
Adds ESIL for arm64 `stlx*` instructions. This instruction comes up regularly from atomic operations.
> Stlxr ESIL

- libr/bin/p/bin_dex.c
* Reported by google's clusterfuzz
* Reproducer: clusterfuzz-testcase-minimized-ia_fuzz-4640848678092800
> Break large loops when method name resolution fails ##crash

- libr/core/cmd_anal.c
> Add an* and fix many other conceptually broken logics in an ##analysis

- libr/anal/arch/kvx/kvx-dis.c
- libr/core/canal.c
* Reported by peacock-doris via huntr.dev
* Reproducer: poc_uaf_r_reg_get
> aaef on arm/thumb switches causes uaf ##crash

- libr/anal/arch/kvx/kvx-dis.c
- libr/anal/arch/kvx/kvx-reg.c
- libr/util/syscmd.c
> Fix the latest covs (memleaks, oobshift, syntax)

- libr/anal/arch/kvx/kvx-reg.c
remove unneeded returns and line break cleanup.
> kvx: Minor syntax cleanup ##arch

- libr/core/cmd_anal.c
Adds mermaid output to all `ag` commands. The `agdm` command is still a bit wrong because it includes the console color escape codes. 
Also the LOC for mermaid is growing, should I move mermaid code into a libr/core/mermaid.c and mark the public functions as `R_IPI`?
So you can merge now or wait for `agdm` fixes and some tests. Those may take a bit though.
Example output of `agCm` on a simple program:
```mermaid
stateDiagram-v2
state "[entry0]\n" as node_0
state "[reloc.__libc_start_main]\n" as node_1
state "[sym.__do_global_dtors_aux]\n" as node_2
state "[reloc.__cxa_finalize]\n" as node_3
state "[sym.deregister_tm_clones]\n" as node_4
state "[sym.func1]\n" as node_5
state "[sym.func2]\n" as node_6
state "[sym.func3]\n" as node_7
state "[main]\n" as node_8
state …
```
> Add mermaid output to all ag commands ##anal

- libr/anal/dwarf_process.c
> Complete DWARF4 register mappings ##bin

- libr/core/cmd_meta.c
> Add help for the CL command ##bin

- libr/core/cmd_debug.c
> Add ddf command

- libr/cons/cons.c
- libr/cons/grep.c
- libr/include/r_cons.h
- libr/include/r_util.h
- libr/include/r_util/r_token.h
- libr/util/Makefile
- libr/util/meson.build
- libr/util/str.c
- libr/util/token.c
* Integrated in pdg~:) .. the happy filter
> Initial import of the code tokenizer ##print

- libr/main/rasm2.c
> Use R_SYS_BITS by default in rasm2 ##tools

- libr/cons/pixel.c
- libr/core/vmenus.c
- libr/util/chmod.c
- libr/util/table.c
> Fix some bugs spotted by CodeQL

- libr/core/cmd_anal.c
> Add aaepa command to set all unknown imports as ret0 ##esil

- .github/workflows/tcc.yml
> Try this commit for TinyCC

- libr/core/cbin.c
- libr/core/disasm.c
- libr/main/radare2.c
- test/db/cmd/cmd_aes
> Fix #19838 - Show pins in the disassembly as comments ##disasm

- libr/anal/block.c
- libr/anal/fcn.c
- libr/anal/op.c
- libr/anal/value.c
- libr/include/r_anal.h
* Fix an UAF on thumb/arm analysis, but there's still another one more problematic
> Save sp,bp,src,dst in heap outside the loop ##anal

- libr/anal/p/anal_dalvik.c
> Fix signed shift bug (UB) in dalvik analysis plugin

- libr/core/cmd_debug.c
* `dxr` now uses `r_debug_execute()`'s `restore` option instead of trying and failing to store and restore registers itself.
* `dd` now correctly uses `dxr` instead of `dx`.
* `dx ` and `dxr` case blocks have been collapsed with shared logic.
> Fix dxr and use it in dd

- libr/core/cmd_anal.c
> Implement 'aeb' using APIs instead of commands ##esil

- libr/anal/p/anal_x86_cs.c
This PR adds proper ESIL for x86 SSE floating point instructions.
> x86 floating point instruction ##esil

- libr/bin/format/mach0/mach0.c
- libr/bin/format/mach0/mach0.h
- libr/core/cmd_api.c
* Reported by peacock-doris via huntr.dev
* Reproducer 'tests_65305'
> Fix heap OOB read in macho.iterate_chained_fixups ##crash

- libr/core/core.c
> Fix double-free in RCore.free

- libr/bin/bin.c
> Honor baddr=0 in RBin, as it's done for RIO ##bin

- libr/bin/p/bin_mach0.c
- libr/core/cmd_debug.c
- libr/include/r_bin.h
- test/db/tools/rabin2
* Let's extend that auto-identification!
> Assume all machos are made by clang ##bin

- libr/crypto/p/crypto_serpent.c
- libr/crypto/p/crypto_serpent_algo.c
- libr/main/rahash2.c
- libr/util/list.c
- man/radare2.1
- man/rahash2.1
> Allow rahash2 -a to be passed multiple times ##tools

- libr/cons/grep.c
- libr/util/token.c
- test/db/tools/token
> Add tests for the code tokenizer and fix <<= assignments

- libr/util/format.c
> Add pfW for signed short format ##print

- libr/core/canal.c
- libr/core/cmd_anal.c
- libr/core/cmd_search.c
- libr/include/r_core.h
* Find relative references using Apple's Swift pointer mangling
* Add aav? help message
> Initial implementation of the aavr command ##search

- libr/util/format.c
> Implement pfP for relative pointer format memory formatting ##print

- .github/workflows/build.yml
- libr/bin/format/objc/mach0_classes.c
> Fix UB in the objc parser logic after handling swift types

- libr/core/cmd_seek.c
- test/db/cmd/cmd_seek
> Fix seek history for the 's..' partial seeks ##shell

- libr/main/radare2.c
- man/radare2.1
- test/db/archos/linux-x64/http
- test/db/cmd/cmd_interpret
- test/db/cmd/cmd_pd
- test/db/cmd/cmd_zignature
- test/db/cmd/feat_grep
- test/db/cmd/feat_quote
- test/db/cmd/regexp
Still a few instances of it left over
> Remove last vestiges of newshell

- libr/anal/block.c
- libr/core/canal.c
- libr/core/cmd_anal.c
> Allow abt to handle addresses in the middle of basic blocks ##analysis

- libr/core/cmd_zign.c
- test/db/cmd/cmd_zignature
> Fix bug in z/, that creates misplaced functions ##zign

- libr/anal/op.c
- libr/core/cmd_anal.c
> aho command related fixes

- libr/core/cmd_anal.c
> Fix `aeim` on --without-debugger builds ##emulation

- .github/workflows/tcc.yml
> Run the tests for non-debugger builds ##ci

- libr/bin/format/mach0/mach0.c
> Minor refactoring in macho

- libr/core/cmd_anal.c
- test/db/cmd/cmd_ao
> Add missing 'direction' field in the output of aoj ##analysis

- libr/anal/bb.c
- libr/anal/block.c
Found some spelling errors, and fixed a weird space gap in a comment, no capitalizations this time around!
I am new to github, I was unsure how to just amend my old branch within the browser version, so I just deleted the branch and did a new edit!
Sorry about that.
> Fixed Some Spelling Errors in Comments

- libr/bin/format/ne/ne.c
* Reported by @han0nly via huntr.dev
* Reproducers: seed1 seed2
* BountyID: ad3c9c4c-76e7-40c8-bd4a-c095acd8bb40
> Fix oobread segfaults in the NE bin parser ##crash

- libr/bin/format/mach0/dyldcache.h
- libr/bin/p/bin_dyldcache.c
* Reported by @hdthky via huntr.dev
* Reproducers: poc1
* BountyID: 8ae2c61a-2220-47a5-bfe8-fe6d41ab1f82
> Fix oobread in dyldcache ##crash

- libr/bin/format/ne/ne.c
- test/db/formats/ne
* Reported by @hmsec via huntr.dev
* Reproducer: necrash
* BountyID: 52b57274-0e1a-4d61-ab29-1373b555fea0/
> Fix oobread in NE parser ##crash

- libr/core/cmd_print.c
- libr/util/str.c
- libr/util/utf8.c
- test/db/cmd/cmd_print_strings
> Add psa command to print any kind of string ##print

- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_cmp.c
- libr/core/cmd_debug.c
- libr/core/cmd_flag.c
- libr/core/cmd_help.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/core/cmd_quit.c
- libr/core/cmd_search.c
- libr/core/cmd_seek.c
- libr/core/cmd_write.c
- libr/core/rtr.c
- libr/include/r_core.h
> Ship RCmd.returnValue into RCore.num.value ##shell

- libr/core/cbin.c
- libr/core/cmd_info.c
> Warn the user when no header fields are found ##bin

- libr/core/cmd.c
- libr/core/cmd_help.c
- test/db/cmd/feat_arroba
> Implement @c: temporal seek operator ##shell

- libr/core/cmd_cmp.c
* Fixes https://github.com/radareorg/ideas/issues/242
> Implement 'curl' command ##shell

- libr/core/cmd_help.c
- test/db/cmd/cmd_help
> Trim extra spaces before second argument in ?==

- libr/core/cmd_cmp.c
- test/db/cmd/cmd_cmp
- test/db/cmd/feat_input
> Add the `cmp` command to compare two (alias) files ##shell

- libr/core/cmd_anal.c
> Use standard help api for `aeim` too ##shell

- libr/io/io_bank.c
> Fix random segfault with wrong null preconditions in iobank ##crash

- libr/main/rabin2.c
* It was previously handled only in the `iH` command
> Show 'missing X info' error in rabin2 -H ##bin

- libr/cons/cons.c
- libr/core/canal.c
- libr/core/cmd_flag.c
- libr/core/disasm.c
> Handle ^C in fg and improve ^C in pd ##shell

- libr/core/cmd.c
- libr/include/r_core.h
- libr/main/radare2.c
> Run r2pm from core internally ##shell

- libr/core/cmd_type.c
- test/db/cmd/types
@Lazula sorry i pick your ticket
> Fix #16335 - `tp` not handling blocksize properly ##types

- libr/core/cmd_project.c
- libr/core/project.c
- libr/include/r_core.h
- test/db/cmd/cmd_project
> Add an error return to r_core_project_cat ##projects

- libr/anal/var.c
- libr/core/canal.c
- libr/core/cmd_anal.c
- libr/core/cmd_meta.c
- libr/core/disasm.c
- test/db/anal/arm
- test/db/anal/emu
- test/db/anal/vars
- test/db/anal/x86_32
- test/db/anal/x86_64
- test/db/archos/linux-x64/dbg_aslr
- test/db/cmd/cmd_af
- test/db/cmd/cmd_graph
- test/db/cmd/cmd_meta
- test/db/cmd/cmd_pd2
- test/db/cmd/cmd_zignature
- test/db/cmd/dwarf
- test/db/cmd/structures
- test/db/cmd/types
- test/db/formats/elf/crackme7
- test/db/formats/elf/elf-riscv64
- test/db/formats/mach0/swift
> Fix #19876 - Smarter local variable and argument sorting ##disasm

- libr/core/cmd.c
> Fix infinite loop in -1 command ##shell

- libr/cons/dietline.c
- libr/io/p/io_debug.c
- libr/io/p/io_mach.c
- libr/io/p/io_w32dbg.c
- libr/util/sys.c
> Add sandbox checks for the debugger io plugins ##security

- libr/anal/anal.c
- libr/anal/p/anal_loongarch_gnu.c
- libr/asm/asm.c
- libr/include/r_anal.h
> Add RAnal.use in RAnalBind to use it from RAsm ##anal

- libr/bin/bin.c
- libr/bin/bobj.c
- libr/bin/format/elf/elf.c
- libr/cons/cons.c
- libr/core/cbin.c
- libr/core/cconfig.c
- libr/core/cfile.c
- libr/core/cmd_api.c
- libr/core/cmd_search.c
- libr/core/panels.c
- libr/include/r_types.h
- libr/include/r_types_base.h
- libr/include/r_util.h
- libr/include/r_util/r_assert.h
- libr/include/r_util/r_log.h
- libr/main/radare2.c
- libr/util/assert.c
- libr/util/file.c
- libr/util/log.c
- test/db/cmd/cmd_i
- test/db/cmd/dwarf
> Improve and integrate the use of the RLog API

- libr/main/rafind2.c
> Check for hexpair keyword before adding a null in rafind2 ##tools

- sys/install.sh
> Fix for --without-pull not working in install.sh

- libr/asm/asm.c
> A little better asm directive parsing ##asm

- shlr/java/class.c
* Reported by @bet4it via @huntrdev
* BountyID: 229a2e0d-9e5c-402f-9a24-57fa2eb1aaa7
* Reproducer: poc4java
> Fix oobread crash in java parser ##crash

- libr/anal/flirt.c
- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
- libr/anal/p/anal_java.c
- libr/bin/format/elf/elf.c
- libr/cons/cons.c
- libr/cons/cpipe.c
- libr/cons/dietline.c
- libr/cons/editor.c
- libr/cons/grep.c
- libr/cons/html.c
- libr/cons/hud.c
- libr/cons/input.c
- libr/cons/less.c
- libr/cons/line.c
- libr/cons/output.c
- libr/cons/pal.c
- test/db/cmd/cmd_interactive_modes
> Use RLog in RCons

- libr/io/io_bank.c
> Fix some TODOs in libr/io/io_bank.c ##io

- libr/anal/p/anal_riscv_cs.c
- libr/asm/p/asm_arm_cs.c
- libr/asm/p/asm_riscv_cs.c
- libr/asm/p/cs_mnemonics.c
- libr/core/cmd_anal.c
- test/db/cmd/cmd_ao
> Fix #19990 - Fix `aoml` for non-x86 targets and add tests ##analysis

- libr/core/cconfig.c
- libr/core/cmd_anal.c
- libr/core/cmd_log.c
* Listing the asm/anal plugins in JSON/Quiet/normal formats
> Implement proper dyslexic subcommands for La/aL ##shell

- libr/bin/p/bin_pebble.c
- test/db/formats/pebble
- test/db/formats/peeble
> Fix #6647 - check map bounds in the pebble bin loader ##bin

- shlr/capstone.sh
> Honor capstone commit in ci ##build

- libr/core/rvc.c
> Refactor some functions in rvc

- libr/anal/type.c
* A bit faster and cleaner code (-80LOC) in 500LOC file
> Proper use of the SDB api in anal/type.c

- libr/core/cmd_type.c
- test/db/cmd/types
> Typedef facility under `t` for `pf` support ##types

- libr/anal/arch/loongarch/gnu/loongarch-dis.c
- libr/anal/p/anal_loongarch_gnu.c
- libr/anal/p/anal_xtensa.c
- libr/asm/arch/include/ansidecl.h
- libr/asm/arch/include/disas-asm.h
- libr/asm/arch/include/libiberty.h
- libr/asm/arch/include/xtensa-isa.h
- libr/asm/arch/tricore/gnu/tricore-dis.c
- libr/asm/arch/xtensa/gnu/elf32-xtensa.c
- libr/asm/arch/xtensa/gnu/xtensa-dis.c
- libr/asm/arch/xtensa/gnu/xtensa-isa.c
- libr/include/r_types.h
- libr/socket/socket.c
- libr/util/d/Makefile
> Xtensa loongarch

- libr/core/cmd_project.c
> Make P command follow the r2 philosophy for consistency ##projects

- libr/anal/p/anal_avr.c
> Remove duplicated register definitions for AVR

- libr/config/config.c
- libr/core/project.c
> Dont save dir. variables in project scripts ##projects

- libr/cons/dietline.c
- libr/cons/grep.c
- libr/cons/pal.c
- libr/core/anal_tp.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
- libr/parse/c/tccgen.c
- libr/parse/c/tccpp.c
> WIP: Fix build with -Wshadow -Werror

- libr/core/cmd_open.c
- libr/core/cmd_project.c
- libr/core/project.c
- test/db/cmd/projects
> Fix avr prj

- test/Makefile
- test/test-8051-reassembly.sh
> Add 8051 disassemble/reassemble tests on realtek firmware.

- libr/core/cbin.c
- libr/core/cconfig.c
> asm.cpu listing fixes for asm.arch=r2ghidra

- libr/core/cbin.c
- libr/core/cconfig.c
> Deprecate anal.cpu, just use asm.cpu ##core

- libr/include/r_util/r_log.h
> Add R_LOG_DISABLE hint for extra debugging

- libr/include/r_th.h
- libr/util/thread_lock.c
> boolify and r_returnify the thread apis

- libr/anal/op.c
- libr/asm/asm.c
* r2 -a arm.v35 - ; pa nop # wasnt working
> Fix assembling with the arm.v35 plugin ##asm

- libr/core/cbin.c
- libr/include/r_bin.h
> Permit RBin plugins to expose a default charset ##bin

- dist/plugins-cfg/plugins.def.cfg
- libr/anal/p/anal_s390_cs.c
- libr/bin/bin.c
- libr/bin/p/bin_s390.c
- libr/bin/p/s390.mk
- libr/include/r_bin.h
- test/db/anal/s390
> bin.s390 improvements

- libr/bin/meson.build
- libr/bin/p/bin_s390.c
- libr/egg/Makefile
- libr/egg/egg_cfile.c
- libr/egg/meson.build
- libr/include/r_egg.h
- libr/include/r_magic.h
- libr/magic/ascmagic.c
- libr/main/ragg2.c
- libr/meson.build
> Rename REgg.Cfile to REgg.cfile ##abi

- libr/anal/op.c
- libr/anal/p/anal_m68k_cs.c
- libr/asm/arch/m68k/gnu/m68k-dis.c
- libr/asm/p/asm_m68k_gnu.c
> Add missing Motorola cpu models for m68k.gnu and m68k.cs ##anal

- libr/magic/ascmagic.c
was 12 seconds too slow to add this to the previous PR
> Unconditionally compile r_magic_from_ebcdic

- libr/core/meson.build
- libr/include/heap/r_windows.h
> Fix mingw64 build

- doc/fortunes.fun
Seems to be a typo in a fortune. If it suppose to be some kind of joke which I do not understand, ignore it
> Fix typo in fortune 

- libr/core/canal.c
> Fix a couple of infinite loops in `aav` ##anal

- libr/anal/block.c
- libr/core/canal.c
- libr/core/cmd_anal.c
> Fix infinite loop when anal.vars on huge empty basic blocks ##anal

- libr/core/project.c
- test/db/anal/x86_64
> Save and restore the register values ##projects

- libr/bin/format/elf/elf.c
> Fix main detection in x64 elf, after updating condret's machine ##bin

- libr/anal/bb.c
- libr/anal/fcn.c
- libr/anal/p/anal_gb.c
- libr/anal/p/anal_i8080.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/anal_z80.c
- libr/include/r_anal.h
> Introduce RAnalPlugin.jmpmid and replace some is_x86 ##anal

- libr/anal/arch/v850np/v850dis.c
- libr/anal/p/anal_v850_np.c
> R5 is actually named TP in v850speak

- libr/bin/format/pe/pe.c
- libr/bin/format/pe/pe.h
- libr/bin/p/bin_pe.c
> Expose CLR metadata in `ih` output instead of messy eprintfs ##bin

- libr/core/cmd_search.c
> Honor anal.calls in `aap` ##anal

- libr/anal/p/anal_8051.c
> Improve boundary oobread checks for anal.8051

- libr/anal/anal.c
- libr/core/cbin.c
- libr/core/cconfig.c
- libr/core/core.c
- libr/core/disasm.c
- libr/debug/dreg.c
- libr/include/r_anal.h
- libr/include/r_arch.h
- libr/include/r_reg.h
- libr/include/r_types.h
- libr/main/rasm2.c
- libr/reg/profile.c
- libr/reg/reg.c
- libr/reg/rvalue.c
> Reg config

- libr/core/cmd_anal.c
> Use @@@F instead of @@f in aaa - fix deadlock in iaito ##anal

- libr/include/r_arch.h
- libr/util/Makefile
- libr/util/arch.c
- libr/util/meson.build
> Move RArch into RUtil

- libr/anal/op.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
> Expose `RAnal.opDirection.toString` as a public method ##api

- libr/bin/format/objc/mach0_classes.c
* Spotted by @meme when using loading it via API
* Further optimizations to reduce iterations and fix io will come later
> Fix allocation peak in macho property parser ##bin

- libr/anal/anal.c
- libr/anal/bb.c
- libr/anal/fcn.c
- libr/anal/p/anal_gb.c
- libr/anal/p/anal_i8080.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/anal_z80.c
- libr/include/r_anal.h
- test/db/anal/v850
> WIP: Remove RAnalPlugin.jmpmid use ANAL_ARCHINFO_ALIGN instead

- sys/clang-format.py
> Update clang-format.py skiplist

- libr/meson.build
> Fix meson build

- configure-plugins
- dist/plugins-cfg/plugins.bin.cfg
- dist/plugins-cfg/plugins.def.cfg
- dist/plugins-cfg/plugins.emscripten.cfg
- dist/plugins-cfg/plugins.mingw.cfg
- dist/plugins-cfg/plugins.nocs.cfg
- dist/plugins-cfg/plugins.nogpl.cfg
- dist/plugins-cfg/plugins.static.cfg
- dist/plugins-cfg/plugins.termux.cfg
- dist/plugins-cfg/plugins.wasi.cfg
- libr/io/Makefile
- libr/io/p/shm.mk
- mk/gcc.mk
> Fix #13196 - Honor SHARED in configure-plugins ##build

- libr/anal/xrefs.c
- shlr/sdb/config.mk
- shlr/sdb/src/array.c
- shlr/sdb/src/json.c
- shlr/sdb/src/json/path.c
- shlr/sdb/src/main.c
- shlr/sdb/src/query.c
- shlr/sdb/src/sdb.c
> Update sdb with fixes for -Wshadow

- libr/anal/cc.c
- libr/anal/p/anal_arm_cs.c
- libr/asm/arch/arm/gnu/arm-dis.c
- libr/asm/p/asm_arm_cs.c
- libr/asm/p/asm_arm_gnu.c
- libr/bin/format/pe/pe.c
- libr/bin/mangling/microsoft_demangle.c
- libr/bin/mangling/swift-sd.c
- libr/bin/p/bin_dex.c
- libr/bin/p/bin_dyldcache.c
- libr/bin/p/bin_mach0.c
- libr/bin/p/bin_xnu_kernelcache.c
> Move more {bin,asm} globals into the TLS

- libr/bin/format/mach0/mach0.c
- libr/bin/format/mach0/mach0.h
- libr/core/cconfig.c
- libr/crypto/crypto.c
- libr/include/r_bin.h
- libr/include/r_th.h
- libr/util/thread_lock.c
- test/db/cmd/metadata
* Fix memory consumption explossion while parsing corrupted binaries
> Do not accept symbol names in mach0s larger than 2KB ##bin

- libr/io/io.c
- libr/io/p/io_rbuf.c
* Allow zero-copy file loading once again
> Fix the io.rbuf plugin (broken since 2017) ##io

- libr/anal/esil.c
> Make ESIL TODO messages go thru R_LOG_DEBUG instead ##emu

- libr/cons/cons.c
- libr/core/cmd_anal.c
> Honor anal.timeout and better ^C handling in `aaaa` ##anal

- libr/core/cmd_print.c
- test/db/cmd/cmd_pdr
> pdrj: change JSON output, group instructions by basic blocks ##json

- libr/bin/p/bin_wasm.c
`RList` of sections should be created with `r_list_newf ((RListFree)r_bin_section_free);` to ensure section is free'd properly.
The rest is just an update to formatting.
> Fix leak in wasm sections ##bin

- libr/core/cbin.c
> Optimize thumb code analysis (4x faster) ##analysis

- libr/cons/cons.c
- libr/core/anal_tp.c
- libr/core/cmd_anal.c
- libr/debug/trace.c
- libr/include/r_types_base.h
- shlr/sdb/src/ht.inc
- shlr/sdb/src/ht_inc.h
- shlr/sdb/src/util.c
> Introduce R_LIKELY macros and update sdb for faster ht ##core

- libr/anal/vtable.c
* Reported by @greatergoodest via huntrdev
* BountyID 0730a95e-c485-4ff2-9a5d-bb3abfda0b17
* Reproducer: minified_crash
> Fix crash in vtable analysis on UB ##crash

- libr/asm/asm.c
- libr/core/anal_tp.c
- libr/core/carg.c
- libr/core/cconfig.c
- libr/core/cmd_anal.c
- libr/core/cmd_help.c
- libr/core/cmd_print.c
- libr/core/cmd_search.c
- libr/core/core.c
- libr/core/disasm.c
- libr/include/r_arch.h
- libr/include/r_util/r_print.h
- libr/main/rax2.c
- libr/util/format.c
- libr/util/print.c
- libr/util/print_code.c
- libr/util/time.c
- test/db/cmd/cmd_ahi
- test/db/esil/x86_32
> Use RArchConfig in RPrint ##api

- libr/anal/arch/v850np/opc.inc
- libr/anal/arch/v850np/v850dis.c
> Initial implementation of the v850 prepare/dispose ##esil

- libr/anal/p/anal_v810.c
- libr/anal/p/anal_v850.c
- libr/anal/p/anal_v850_np.c
> In the V8xx families the R0 is a WTG register ##emulation

- libr/core/cmd_debug.c
> Handle ? in all the `dc` subcommands ##shell

- libr/core/cmd_print.c
- libr/core/visual.c
- libr/core/vmenus.c
- libr/util/bitmap.c
- test/db/cmd/cmd_print_bitformat
> Initial implementation of pfb, binary formatting ##print

- libr/parse/p/parse_v850_pseudo.c
> Add a parse plugin for tweaking references to r0 ##disasm

- libr/core/cmd_print.c
- test/db/cmd/cmd_pi
> Handle pd1 and pi1 (imm without space) ##shell

- binr/radare2/radare2.c
- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_cmp.c
- libr/core/cmd_debug.c
- libr/core/cmd_flag.c
- libr/core/cmd_help.c
- libr/core/cmd_macro.c
- libr/core/cmd_mount.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/core/cmd_quit.c
- libr/core/cmd_search.c
- libr/core/cmd_seek.c
- libr/core/cmd_write.c
- libr/core/core.c
- libr/core/project.c
- libr/core/rtr.c
- libr/include/r_core.h
- libr/main/radare2.c
- test/Makefile
> Add test for 'q' return code bug and minor cleanup r2r ##tests

- libr/core/cmd_project.c
- test/db/cmd/projects
See https://github.com/radareorg/radare2/issues/20094
> Add command to close a project

- libr/core/cconfig.c
- libr/core/cproject.c
- libr/core/rvc.c
I recently opened 2 prs: https://github.com/radareorg/radare2/pull/20170 and https://github.com/radareorg/radare2/pull/20012
they introduced many bugs, this PR hopes to fix them without creating any new ones,
> Fix a bunch of bugs I introduced in prev prs ##projects

- libr/core/cmd_mount.c
https://github.com/radareorg/radare2/issues/19968
The `mk?` left unfixed. Looks like it is absent now. 
> Add help messages for ms mp mL mo commands

- libr/anal/p/anal_arm_cs.c
- libr/bin/format/mach0/mach0.c
- libr/bin/format/mach0/mach0.h
- libr/bin/p/bin_mach0.c
- libr/core/core.c
> Fix crash when doing aac in frida://0 which calls 's $S' ##anal

- libr/core/cmd_info.c
- test/db/cmd/cmd_i
> Implement and document iz* and izz* ##shell

- libr/anal/p/anal_x86_cs.c
- libr/core/cmd_anal.c
- libr/core/cmd_search.c
- libr/hash/sha2.c
- shlr/gdb/src/gdbclient/xml.c
> Fix gcc12 warnings. Ref #20087

- libr/cons/Makefile
- libr/cons/cons.c
- libr/cons/help.c
- libr/cons/meson.build
- libr/core/cmd.c
- libr/core/cmd_print.c
- libr/include/r_cons.h
- libr/include/r_core.h
> Initial support for JSON help messages ##json

- libr/core/cconfig.c
- libr/core/cmd_search.c
> Implement search.in=flag ##search

- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_info.c
- libr/core/cmd_print.c
- libr/core/corelog.c
> Some better help, error capitalization and more PJ usage

- binr/radare2/radare2.c
- test/unit/test_buf.c
> Check return codes on some write() calls

- COMMUNITY.md
> Improve wording of COMMUNITY.md

- libr/anal/xrefs.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
> Implement ax, to list xrefs using RTable ##print

- binr/r2pm/r2pm.sh
- libr/main/r2pm.c
* Checks for python3, python and python2 in PATH
> Fix #20200 - Set PYTHON env var if not defined

- test/db/asm/i4004
> Fix tests for i4004

- binr/r2pm/r2pm.sh
Just correction of dependencies installation.
Before when you installed some package by -gi key you got his dependencies in local folders.
> Correction of dependencies installation

- libr/anal/p/anal_x86_cs.c
> Improve avx support in anal_x86_cs.c

- libr/io/io_plugin.c
> Optimize io.open() by skipping plugin iteration if no uri found ##io

- libr/main/radare2.c
> Expose R2_HISTORY in r2 -hh and r2 -H to locate history file ##shell

- libr/core/cmd_cmp.c
- libr/core/cmd_debug.c
- libr/core/cmd_print.c
- libr/include/r_util/r_time.h
- libr/magic/mdump.c
- libr/magic/softmagic.c
- libr/util/format.c
- libr/util/time.c
> Remove newline in date and pt. output ##shell

- libr/asm/arch/arm/armass64.c
- test/db/asm/arm_64
> Support assembler arm64 ##asm

- libr/core/cconfig.c
> Fix error message in `e-` when resetting in debugger ##shell

- libr/anal/p/anal_mips_gnu.c
- libr/asm/p/asm_arm_gnu.c
- libr/asm/p/asm_cris_gnu.c
- libr/asm/p/asm_hppa_gnu.c
- libr/asm/p/asm_lanai_gnu.c
- libr/asm/p/asm_m68k_gnu.c
- libr/asm/p/asm_mips_gnu.c
- libr/asm/p/asm_pdp11_gnu.c
- libr/asm/p/asm_sparc_gnu.c
> Make the gnu disassemblers thread safe ##core

- libr/anal/p/anal_arm_cs.c
> fixup arm ujmp op type with rjmp & mjmp ##analysis

- libr/anal/p/anal_x86_cs.c
> Add esil support for VMOVDQU in anal_x86_cs.c ##anal

- libr/anal/esil.c
> Remove dead code ##anal

- libr/asm/arch/arm/armass64.c
- test/db/asm/arm_64
> Support ccmn and csel instructions in the arm64 assembler ##asm

- libr/bin/p/bin_s390.c
> Avoid false positives when loading s390 modules ##bin

- .github/workflows/ci.yml
> Generate r2r.json for profiling the testsuite ##tests

- shlr/meson.build
> Fix Capstone bpf, evm Meson builds

- libr/main/rasm2.c
> Fix disalignment glitch in rasm2 -L and rasm2 -LL ##tools

- libr/anal/p/anal_6502_cs.c
- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_bpf_cs.c
- libr/anal/p/anal_m680x_cs.c
- libr/anal/p/anal_m68k_cs.c
- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_ppc_cs.c
- libr/anal/p/anal_riscv_cs.c
- libr/anal/p/anal_s390_cs.c
- libr/anal/p/anal_sparc_cs.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/anal_xcore_cs.c
Logs to `R_LOG_ERROR` if Capstone `cs_open` fails.
~~Note: Ignore this for now, I ran `clang-format --style=file -i ...` on the changed files and it caused 1400 lines of diff~~
> Log cs_open() errors

- libr/anal/p/anal_bpf_cs.c
`aoml` (list all mnemonics) is useful for fuzzing
> Support aoml for bpf.cs

- libr/anal/p/anal_bpf_cs.c
Use the r10 register as SP, which is how its supposed to be
> Use r10 as SP

- doc/abi.md
Sorry if this looks like a nitpick. Just trying to help.
> I think even would be better than pair in abi.md

- libr/asm/arch/arm/armass64.c
- test/db/asm/arm_64
Support cset, sxtb, sxth and  sxtw instructions in the arm64 assembler
> Support cset and sxt(b,h,w) instructions in the arm64 assembler ##asm

- libr/anal/p/anal_bpf.c
> Remove excess zeroing in anal_bpf.c ##refactor

- libr/bin/format/wasm/wasm.c
- libr/bin/format/wasm/wasm.h
More RPVectors will make life easier when they start getting used. Simplifies the code too.
> Change wasm subsections into RPVectors ##bin

- libr/anal/p/anal_m68k_cs.c
- test/db/anal/m68k
Tracks cycles of the m68k move instruction.
Relates to #20284
> Add op->cycles for M68K move ##anal

- libr/io/io_desc.c
- libr/io/p/io_default.c
- libr/io/p/io_sparse.c
- libr/util/file.c
> Some io cleanup while trying to track down a bug

- libr/io/p/io_ihex.c
- test/db/io/ihex
> Fix bug in io_ihex ##io

- libr/asm/arch/arm/armass64.c
- test/db/asm/arm_64
> Support tbz,tbnz,rev16,rev32 instructions in the arm64 assembler ##asm

- libr/core/cconfig.c
- libr/core/fortune.c
- libr/include/r_core.h
- libr/include/r_userconf.h.acr
> Prepare r2 for the premium r2pm pkg

- dist/plugins-cfg/plugins.static.nogpl.cfg
> Fix build static.nogpl

- libr/core/cmd_anal.c
> Moved afis help msg to use r_core_help

- libr/asm/arch/riscv/riscv.h
> Fix UB shift in anal.riscv

- doc/fortunes.fun
- doc/fortunes.tips
> Add premium installation fortunes

- libr/util/str.c
- libr/util/table.c
> Fix oobread in RTable exposed via an ELF reproducer ##crash

- libr/include/r_util/r_str.h
- libr/util/str.c
> Compile-time optimization for r_str_startswith() ##util

- libr/core/cbin.c
- test/db/cmd/cmd_i
> Fix #17174 - Add the flagname and real symbol name details in the output of icj ##bin

- libr/socket/socket.c
> Fix #20206 - Collect wuntraced corpses

- libr/core/fortune.c
> Fix fortune file detection ##core

- libr/anal/p/anal_arm_cs.c
> Add big endian support for arm prelude search ##anal

- libr/reg/Makefile
- libr/reg/arena.c
- libr/reg/double.c
- libr/reg/profile.c
- libr/reg/rcond.c
- libr/reg/rvalue.c
- libr/util/str.c
- test/db/cmd/cmd_arp
> Refactorings in libr/reg

- libr/bin/p/bin_xtr_xalz.c
> Fix #20354

- libr/core/cmd_eval.c
> Update cmd_eval / en[v]? case help message

- binr/r2r/r2r.c
- man/r2r.1
> Remove the -r and -m flags from r2r ##tests

- libr/core/cmd_quit.c
- libr/core/core.c
- libr/main/radare2.c
- test/Makefile
> Fix echo q|r2 return code ##shell

- libr/anal/p/anal_alpha.c
- libr/asm/arch/pyc/opcode.c
- libr/bin/format/te/te.c
- libr/bin/format/te/te.h
- libr/bin/p/bin_te.c
- libr/bp/bp.c
- libr/core/cmd_anal.c
- libr/core/cmd_debug.c
- libr/core/cmd_hash.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/core/cmd_search.c
- libr/core/cmd_search_rop.c
- libr/debug/debug.c
- libr/io/p/io_r2web.c
- libr/io/p/io_zip.c
- libr/main/radare2.c
- sys/lint.sh
- test/db/cmd/cmd_print
- test/db/cmd/cmd_ps
> Use more R_LOG instead of eprintfs and add more linting checks

- libr/anal/dwarf_process.c
- libr/anal/p/anal_bpf.c
- libr/anal/p/anal_i4004.c
- libr/anal/p/anal_ppc_cs.c
- libr/anal/type.c
- libr/anal/var.c
- libr/bin/dwarf.c
- libr/config/config.c
- libr/core/blaze.c
- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_debug.c
- libr/core/cmd_print.c
- libr/core/core.c
- libr/core/disasm.c
- libr/core/vmenus.c
- libr/core/vmenus_graph.c
- libr/core/windows_heap.c
- libr/debug/dreg.c
- libr/debug/p/native/windows/windows_message.c
- libr/parse/p/parse_ppc_pseudo.c
- libr/util/format.c
- sys/lint.sh
> Lint for x"" ##cleanup

- libr/core/cmd_print.c
> Correct help msg fro ph command ##doc

- doc/fortunes.fun
toki pona doesn't capitalize, and "kama jo e musi" isn't idiomatic
> Correct toki pona

- libr/anal/meson.build
- libr/anal/p/anal_gb.c
- libr/anal/p/anal_kvx.c
- libr/anal/p/anal_propeller.c
- libr/anal/p/gb.mk
- libr/anal/p/kvx.mk
- libr/anal/p/propeller.mk
> Minor simplification of meson build files ##refactor

- libr/core/canal.c
- libr/core/cbin.c
- libr/core/cfile.c
- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/core/cmd_print.c
- libr/core/cmd_search.c
- libr/core/cmd_type.c
- libr/core/disasm.c
- libr/core/pseudo.c
- libr/core/visual.c
- libr/core/vmenus_graph.c
- libr/socket/r2pipe.c
- sys/lint.sh
- test/db/cmd/types
> Add another source linting to avoid newlines in RCore.cmd()

- libr/core/cconfig.c
- libr/core/core.c
- libr/core/rtr.c
- libr/core/rtr_http.c
- libr/include/r_core.h
- libr/socket/socket_http_server.c
> Few http webserver improvements ##web

- libr/cons/cons.c
- libr/include/r_util/r_sys.h
- libr/util/sys.c
> Add r_sys_signable() and use it from r_cons_thready ##cons

- libr/bin/bfile.c
- libr/main/radare2.c
* The `it` command works still as expected and hashes are computed on demand
> Don't hash files when loading, that's too heavy! 1.2s -> 0.8s ##bin

- libr/config/callback.c
- libr/config/config.c
- libr/config/hold.c
- libr/include/r_types_base.h
- shlr/sdb/src/ht.inc
- shlr/sdb/src/sdb.c
- shlr/sdb/src/sdb.h
> Upgrade from latest sdb

- libr/asm/arch/arm/armass64.c
- libr/bin/format/dmp/dmp64.c
- libr/bin/mangling/cxx/cp-demangle.c
- libr/bin/p/bin_xnu_kernelcache.c
- libr/core/cmd_print.c
- libr/core/visual.c
- libr/debug/p/debug_gdb.c
- libr/debug/p/native/darwin.c
- libr/debug/p/native/linux/linux_coredump.c
- libr/debug/p/native/linux/linux_debug.c
- libr/include/r_flist.h
- libr/include/sflib/common/sftypes.h
- libr/util/bdiff.c
- libr/util/donut.c
- libr/util/seven.c
- sys/lint.sh
> Add and fix two more for loop linter rules

- libr/asm/aop.c
- libr/asm/asm.c
- libr/core/cmd_print.c
- libr/core/disasm.c
- libr/util/str.c
> Fix (null) printing on `pi` command ##print

- libr/asm/p/asm_x86_cs.c
- test/db/anal/x86_64
- test/db/asm/x86_32
> Remove all instances of "ptr " in x86 cs assembly output ##asm

- libr/io/io_bank.c
- libr/io/io_map.c
> Miniscule optimization of io vread and mapping operations ##io

- libr/anal/p/anal_java.c
- libr/cons/cons.c
- libr/core/cmd_open.c
- libr/core/cmd_project.c
- libr/core/project.c
- libr/core/vmenus_zigns.c
- libr/include/r_cons.h
- shlr/java/code.c
- shlr/java/code.h
- test/db/cmd/projects
* io maps are now saved and restored
* add an extra test and review/update others
* Use omu in om* and run o*;om* in P
* Better handling multiple P subcommands and help msg
* Use more R_LOG instead of eprintf
> Fix #20405 - Multiple fixes and improvements in projects ##projects

- libr/bin/p/bin_mach0.c
- test/db/cmd/cmd_open
> Fix o-- issue on macho-arm64 ##bin

- libr/util/lib.c
- libr/util/udiff.c
> Fix race condition in radiff2 test

- libr/core/cbin.c
- libr/core/cmd_open.c
- libr/util/buf.c
- test/db/cmd/projects
> Tiny optimization in RBuffer -0.01s speedup ##io

- libr/core/cconfig.c
- libr/core/cmd_mount.c
- libr/fs/shell.c
* Remove unnecessary global variable
> Add fs.cwd to define default path in `ms` ##fs

- shlr/Makefile
- shlr/meson.build
> Update to the latest capstone with fixes for ebpf, tls and arm

- .github/workflows/build.yml
- sys/osx-pkg.sh
> Publish m1 packages automatically on release time ##ci

- .github/workflows/ci.yml
- .github/workflows/tcc.yml
- binr/r2pm/r2pm.sh
- dist/plugins-cfg/plugins.static.cfg
- dist/plugins-cfg/plugins.static.nogpl.cfg
- dist/plugins-cfg/plugins.termux.cfg
- libr/flag/d/meson.build
- libr/flag/d/tags.py
- libr/main/r2pm.c
- libr/util/sandbox.c
> Build r2 with muon+samu ##ci

- libr/bin/p/bin_mach0.c
> Fix macho swizzle bug by cloning the plugin struct ##bin

- libr/core/cmd_seek.c
> Handle the s# command as in 's #' ##shell

- libr/magic/d/default/compressed
- test/db/cmd/cmd_search
> Improve little and big endian LZMA header magic matching ##search

- libr/core/cmd_search.c
- test/db/cmd/cmd_search
* This needs a proper fix which will break abi
> Fix /as on arm64-linux and add missing tests to cover it ##search

- libr/bin/p/bin_mach0.c
> Expose dbgInfo.LineNum on macho files ##bin

- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
- libr/core/cmd_anal.c
- libr/parse/p/parse_arm_pseudo.c
- shlr/Makefile
- shlr/meson.build
- test/db/esil/apple
> Handle arm64's BTI instruction as a nop ##analysis

- libr/asm/p/asm_arm_cs.c
- libr/core/cconfig.c
- libr/include/r_asm.h
> Ignore asm->immdisp ##refactor

- libr/bin/format/mach0/mach0.c
> Fix heap oobread in the macho parser ##crash

- libr/anal/arch/bpf/bpf.h
- libr/anal/p/anal_bpf.c
> In cBPF jt and jf are unsigned, fix the code ##anal

- libr/anal/p/anal_dalvik.c
> Try to make coverity trust that index

- doc/fortunes.tips
> Remove no more useful tip for code that was removed long ago

- libr/util/skiplist.c
- test/unit/test_skiplist.c
> Skiplist rand

- libr/core/disasm.c
> Fix previous fix

- libr/core/cmd_write.c
Update to an incorrect coverity fix, `filename` is handled in a few different ways depending on the control flow. Could be improved but it needs to be fixed now.
> Fix memory management in cmd_wt()

- libr/core/cmd_seek.c
- libr/include/r_util/r_num.h
- libr/main/rasm2.c
- libr/main/rax2.c
- libr/util/calc.c
- libr/util/unum.c
- test/db/cmd/cmd_i
> Use of RNum.calc in rax2 to honor error code ##tools

- libr/include/r_cons.h
- libr/util/print.c
FIxes 'pss' rendering when switching via p/P in visual mode, to reproduce run 'r2 COPYING' from radare2 git top directory.
> Fix display issues with pss visual mode ##cons

- libr/core/cmd_write.c
- test/db/cmd/cmd_print
- test/db/cmd/cmd_w
- test/db/cmd/write
Major logic refactoring. Significantly reduced code duplication, confusing logic, and excessive indents.
> Refactor `wt` command

- libr/bin/format/pe/pe.c
- libr/core/core.c
- libr/include/r_types.h
- libr/util/print.c
> Fix some memory leaks caused by buggy macros for reference counting

- libr/util/Makefile
- libr/util/big.c
- libr/util/big_gmp.c
- libr/util/big_ssl.c
> WIP: Initial work towards onifying r_util ##build

- README.md
> Missing comma in readme

- libr/bin/format/elf/elf.c
- libr/bin/format/pe/pe.c
> Alloc check

- libr/core/cmd_search.c
Simplify code a little.
/rx did nothing for me
> Fix /rx ##search

- libr/core/cmd_print.c
> Fix small leak of list in cmd_prc_zoom()

- libr/bin/p/bin_mach0.c
- libr/io/io.c
> Fix use-after-free in the macho swizzler

- libr/bin/format/mach0/mach0.c
- libr/bin/p/bin_xnu_kernelcache.c
> Fix oobread in iOS arm64 kernel parsing ##crash

- libr/asm/arch/arm/armass64.c
Radare2's arm64 disassembler and assembler work differently.
And there was an error with x0 register.
```sh
$ rasm2 -a arm -b 64 'adr x0, 0x45678'
ERROR: Invalid register to encode
ERROR: Invalid register to encode
ERROR: Invalid register to encode
c2b30030
$ rasm2 -a arm -b 64 'adr x1, 0x45678' | rasm2 -d -a arm -b 64 -
adr x3, 0x1679
$ rasm2 -a arm -b 64 'adrp x1, 0x1234000' | rasm2 -d -a arm -b 64 -
adrp x1, 0x14000
```
I patched adrp and adr instruction.
[arm64 manual](https://developer.arm.com/documentation/ddi0596/2021-12/Base-Instructions/ADR--Form-PC-relative-address-).
```sh
$ rasm2 -a arm -b 64 'adr x0, 0x45678'
c0b32210
$ rasm2 -a arm -b 64 'adr x1, 0x45678' | rasm2 -d -a arm -b 64 -
adr x1, 0x45678
$ rasm2 -a arm -b 64 'adrp x1, 0x1234000' | rasm2 -d -a arm -b …
```
> Fix arm64's adr and adrp instruction ##asm

- libr/core/visual.c
> Fix recently introduced stack buffer overflow ##visual

- libr/core/cmd_print.c
The pointer looks not used by anything else.
> Fix leak by freeing pointer on stack after it is abandoned

- libr/anal/p/anal_pickle.c
- test/db/anal/pickle
Add assembler handlers for last pickle opcodes.
> Add last opcodes to pickle assembler ##anal

- libr/core/canal.c
> Fix leak of abandoned buffer in anal_block_cb()

- libr/anal/p/anal_x86_cs.c
> Check if allocation was positive of r_anal_value_new()

- libr/core/cbin.c
- libr/core/cmd_eval.c
- libr/core/core.c
- libr/debug/p/native/bt/fuzzy_all.c
- libr/main/radare2.c
- libr/parse/c/tccgen.c
- libr/parse/p/parse_x86_pseudo.c
Leaks when using -e bin.cache=true are still present, and are harder to fix, probably missing unref call somewhere.
> Misc leaks

- libr/core/cmd_type.c
- libr/util/file.c
> Add the infamous command `tac` ##shell

- binr/rafind2/rafind2.c
- libr/main/rafind2.c
- libr/search/search.c
- man/rafind2.1
> Fix #20439 - rafind2 -V search for values like in /v ##tools

- libr/cons/cons.c
Found out getctx() was called too much times after inspecting perf reports.
> Speed up rendering by caching context pointer ##cons

- libr/core/panels.c
So they can be tracked easily.
> Add FPU/XMM/YMM panel displays ##view

- libr/asm/arch/riscv/riscv-opc.c
- libr/asm/arch/riscv/riscv.h
- libr/core/panels.c
> Fix r_cons_printf call in calculator ##view

- Makefile
- meson.build
> GIT_TAP=$R2_VERSION if no .git is found ##build

- doc/fortunes.tips
> Remove obsolete tip, and fix another one.

- shlr/Makefile
- shlr/meson.build
- test/db/cmd/cmd_ao
- test/db/cmd/cmd_zignature
> Upgrade to the latest capstone-next for ppc purposes

- libr/include/r_socket.h
- libr/main/rarun2.c
- libr/socket/run.c
> Improve pid directive in rarun2, better info reporting ##tools

- libr/bin/bin.c
- libr/core/cmd_api.c
- libr/core/core.c
- libr/core/visual.c
- libr/core/yank.c
- libr/main/radare2.c
- libr/util/log.c
- libr/util/table.c
> Misc fixes #2

- doc/fortunes.tips
> Tell correct command for function renaming

- libr/anal/arch/vax/vax-dis.c
- libr/asm/arch/riscv/riscv-opc.c
- libr/core/canal.c
- libr/core/cmd_api.c
- libr/include/r_bin.h
- libr/io/p/io_zip.c
- libr/main/rabin2.c
- shlr/java/ops.h
> Misc fixes

- libr/core/cbin.c
- libr/util/table.c
Reproducible also by 'iS=' command.
> Few more leaks fixes

- libr/bin/format/mach0/mach0.c
- test/db/formats/mach0/leb128
> Fix unnecessary large allocation on fuzzed machos

- test/db/formats/web_assembly
> Remove duplicate wasm test

- libr/bin/format/wasm/wasm.c
- libr/bin/p/bin_wasm.c
- test/db/formats/web_assembly
> Add wasm globals to symbols ##bin

- libr/core/canal.c
- libr/core/cmd_flag.c
- test/db/cmd/cmd_search
Fixes for #19250 and another leak.
> Fix for /gg

- libr/core/cmd.c
- libr/core/core.c
> Fix autocompletion for :.<tab> for r2frida ##shell

- libr/bin/bobj.c
- libr/bin/format/mach0/mach0.c
> Handle RABIN2_MACHO_SKIPFIXUPS env var in the macho parser ##bin

- libr/asm/asm.c
> Let a->cur be null and honor host endian by default

- libr/io/p/io_self.c
> Initial blind support for io.self for serenity

- libr/include/r_util/r_json.h
- libr/util/json_parser.c
> Use R_LOG in util/json_parser.c

- libr/anal/arch/v850/opc.inc
- libr/anal/arch/v850/v850dis.c
- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
- libr/anal/p/anal_bpf_cs.c
- libr/anal/p/anal_gb.c
- libr/anal/p/anal_i4004.c
- libr/anal/p/anal_loongarch_gnu.c
- libr/anal/p/anal_rsp.c
- libr/anal/p/anal_v850.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/var.c
- libr/asm/arch/arm/armass64.c
- libr/bin/format/objc/mach0_classes.c
- libr/bin/p/bin_xnu_kernelcache.c
- libr/core/cmd_anal.c
- libr/core/cmd_print.c
- libr/core/disasm.c
- libr/core/linux_heap_glibc.c
- libr/core/rtr_http.c
- libr/egg/egg_cfile.c
- libr/include/r_util/r_print.h
- libr/io/io_plugin.c
- libr/io/p/io_ihex.c
- libr/io/p/io_xalz.c
- libr/magic/d/default/archive
- libr/main/r2pm.c
- libr/parse/c/tcc.h
- libr/util/sys_sh.c
- sys/lint.sh
> Lint for trailing spaces

- libr/anal/anal.c
- libr/anal/arch/z80/z80asm.c
- libr/anal/block.c
- libr/anal/diff.c
- libr/anal/dwarf_process.c
- libr/anal/esil.c
- libr/anal/flirt.c
- libr/anal/function.c
- libr/anal/op.c
- libr/anal/p/anal_wasm.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/esil_dummy.c
> Use R_LOG instead of eprintf in more places

- libr/anal/p/anal_pickle.c
- test/db/anal/pickle
* There's asm.ucase to tweak this
> Lowercase all pickle instructions ##arch

- libr/util/new_rbtree.c
- test/unit/test_esil_dfg_filter.c
> Fix esil dfg filter

- libr/core/cmd_print.c
- libr/core/visual.c
- libr/util/strbuf.c
* Tab to toggle between insert and replace mode
* Cursor is enabled after insertion
* Still not yet a replacement for your favourite editor
> Implement interactive text editor mode in VPi command ##visual

- libr/asm/p/asm_m68k_gnu.c
- libr/config/config.c
- libr/cons/canvas.c
- libr/cons/dietline.c
- libr/core/cconfig.c
- libr/core/cmd_eval.c
- libr/core/cmd_flag.c
- libr/include/r_anal.h
- libr/include/r_types.h
- shlr/sdb/src/query.c
- test/db/cmd/cmd_ec
- test/db/cmd/cmd_eval
> Fix sdb uninit

- libr/core/cbin.c
- libr/core/cmd_api.c
- libr/core/cmd_cmp.c
- libr/core/cmd_debug.c
- libr/core/cmd_log.c
- libr/core/rvc.c
- libr/core/windows_heap.c
> More RLOG usage in core

- binr/r2r/load.c
- binr/r2r/r2r.c
- binr/r2r/r2r.h
- binr/r2r/run.c
- test/db/tools/rasm2
> Support REQUIRE in r2r tests

- libr/bin/pdb/pdb.c
- libr/util/protobuf.c
- libr/util/punycode.c
- libr/util/x509.c
- test/fuzz/fuzz_pdb_parse.c
- test/fuzz/fuzz_pkcs7_parse.c
- test/fuzz/fuzz_protobuf_decode.c
- test/fuzz/fuzz_punycode_decode.c
- test/fuzz/fuzz_x509_parse.c
- test/fuzz/meson.build
More fuzzers, all of them found UB or crashes
> Fuzz pdb, pkcs7, protobuf, punycode, x509 ##fuzz

- libr/bin/dwarf.c
- libr/bin/format/mach0/mach0.c
- libr/bin/p/bin_tic.c
- sys/derizin.sh
> Use more R_LOG in rbin

- libr/bin/bfile.c
- libr/bin/format/mach0/mach0.c
- libr/core/corelog.c
- libr/core/cplugin.c
- libr/core/patch.c
- libr/include/r_core.h
* removed a global to be toggled after release
> Fix oba $$ in frida://0 global ##bin

- libr/core/cmd_info.c
> Fix #20624 - Implement ic, command to query klass information ##bin

- libr/bin/mangling/microsoft_demangle.c
- libr/include/r_util/r_str.h
- test/fuzz/fuzz_bin_demangle.c
Fixes countless libFuzzer findings (stack, heap, global overflows, null deref)
> Harden msvc demangler ##crash

- libr/core/cmd_anal.c
> Remove hack fixing a bug that is now gone for agn

- libr/anal/esil_dfg.c
- libr/include/r_anal.h
> Implement r_anal_esil_dfg_reg_is_const ##anal

- dist/plugins-cfg/plugins.def.cfg
- libr/include/r_io.h
- libr/io/meson.build
- libr/io/p/io_reg.c
- libr/io/p/reg.mk
- libr/meson.build
> Initial implementation of the reg:// io plugin ##io

- test/fuzz/fuzz_ia.c
- test/fuzz/meson.build
Radare can now fuzz in-tree so we can import https://github.com/radareorg/radare2-fuzz/blob/master/targets/ia_fuzz.cc
> Import ia_fuzz from radare2-fuzz

- libr/core/visual.c
- libr/include/r_core.h
> Fix #20653 - uaf of an unused variable in visual

- libr/bin/bfile.c
- libr/bin/p/bin_dyldcache.c
Fix wrong checks which broke parsing of dyld cache files and their content.
> Fix regressions affecting dyldcache parsing ##bin

- libr/bin/format/mach0/mach0.c
- libr/bin/p/bin_mach0.c
- test/db/tools/rabin2
> Fix incorrect relocs=false in macho ##bin

- libr/core/cmd_info.c
- libr/util/table.c
> Add table's :help and ignore commas in `i` subcommand parsing ##bin

- libr/core/cmd_write.c
- test/db/cmd/cmd_w
> Implement wa+ command to assemble + seek ##write

- libr/core/cmd.c
- libr/core/yank.c
> Improve the yank command and help ##shell

- .github/workflows/build.yml
> Fix #20655 - Zip the blob for windows ##ci

- libr/core/cmd.c
- libr/core/cmd_api.c
- libr/core/cproject.c
- test/db/cmd/cmd_repeats
> Make command repeat behave as expected with the foreach operator ##shell

- libr/util/strbuf.c
> Minor bugfix in strbuf.c ##util

- libr/util/print.c
> Don't print eol chars for now to fix an r2pipe issue ##shell

- libr/anal/p/anal_arm_cs.c
- libr/core/cmd_anal.c
- libr/core/disasm.c
- test/db/esil/arm_16
> Remove occurences of $$ in arm_cs esil ##refactor

- libr/anal/p/anal_arm_cs.c
- test/db/anal/arm
> Avoid =[*] in arm_cs esil ##refactor

- libr/anal/p/anal_arm_cs.c
r_strbuf_{append,set} is faster than r_strbuf_{appendf,setf}
> Minor optimization of esil generation in anal_arm_cs.c ##refactor

- libr/anal/p/anal_v810.c
- libr/anal/p/anal_v850.c
> Remove occurences of $$ in v810/v850 esil ##refactor

- libr/bin/format/mach0/coresymbolication.c
- test/db/formats/mach0/coresymbolication
Update the CoreSymbolication cache parser to work on the latest evolution of the format.
The added tests depend on this PR on testbins to be merged: https://github.com/radareorg/radare2-testbins/pull/80
> Update coresymbolication cache parser ##bin

- binr/r2r/r2r.c
- libr/cons/help.c
- libr/core/agraph.c
- libr/core/cmd_anal.c
- libr/core/cmd_debug.c
- libr/core/cmd_help.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/core/disasm.c
- libr/core/panels.c
- libr/core/visual.c
- libr/core/visual_tabs.inc
- libr/core/vmenus.c
- libr/main/radare2.c
- sys/lint.sh
> Add test index progress in default output ##tests

- libr/core/cmd.c
* Only checks for the exec bit if the file doesnt have any known extension
> Support interpreting executable binaries with r2 -i or '.' ##shell

- libr/core/cmd.c
- libr/core/core.c
- libr/crypto/crypto.c
- libr/main/r2pm.c
- libr/util/str.c
- test/db/tools/rafind2
- test/unit/test_str.c
> Assertify the crypto api

- libr/anal/p/anal_bf.c
- libr/anal/p/anal_mips_cs.c
> Remove occurences of $$ in bf and mips_cs esil ##refactor

- libr/anal/p/anal_x86_cs.c
- libr/debug/p/native/xnu/xnu_debug.c
- libr/magic/apprentice.c
> Fix a few GCC 12 warnings from #20087

- libr/asm/arch/riscv/riscv.c
- libr/asm/arch/tms320/tms320_dasm.c
- libr/asm/arch/tms320/tms320_dasm.h
- libr/asm/arch/tms320/tms320_p.h
* Inspired by rizin's 1619d94329ab0665083b5f5aef9030f33146bd33
* Author:     Florian Märkl <info@florianmaerkl.de>
* AuthorDate: Mon Aug 15 19:53:55 2022 +0200
> Fix tms320 on big-endian hosts

- libr/bin/format/mach0/coresymbolication.c
- libr/bin/p/bin_dyldcache.c
> Fix two oobreads in coresymbolication and dyldcache ##bin

- libr/core/cmd_type.c
- test/db/cmd/types
> Fix #16492 - Handle `-` suffix in `te` and `ts`, add tests ##types

- libr/bin/format/mach0/mach0.c
Fix wrong check which could have caused oob writes.
(Fix ported from rizin)
> Fix boundary check in mach0 fixups reconstruction ##bin

- libr/anal/fcn.c
- libr/core/cmd_anal.c
> Implement `aggb` command, like agfb but for agn/age ##graph

- libr/anal/esil.c
- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_mips_gnu.c
- libr/anal/p/anal_riscv.c
- libr/anal/p/anal_riscv_cs.c
> Remove usage of esil $$

- .github/workflows/build.yml
> Disable the freebsd builds from the ci

- libr/core/cio.c
- libr/core/cmd_write.c
- test/db/cmd/cmd_wox
* Better help messages and argument handling
> Fix #20387 - woa 1 confusing error message ##shell

- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_mips_gnu.c
- libr/anal/p/anal_riscv.c
> Minor optimization of generated esil expressions ##refactor

- libr/core/cmd_print.c
* Depending on blocksize that command prints some invalid instructions
* Reverse disassembly is not 100% reliable if the code is not analyzed
> Fix #20202 - pd-55 showing invalid instructions ##disasm

- libr/anal/arch/cr16/cr16_disas.c
- libr/anal/arch/cr16/cr16_disas.h
- libr/anal/arch/loongarch/gnu/loongarch-coder.c
- libr/anal/arch/msp430/msp430_disas.c
- libr/bin/format/mdmp/mdmp.c
- libr/bin/p/bin_xnu_kernelcache.c
- libr/cons/canvas.c
- libr/io/p/io_r2k_linux.c
- libr/util/regex/regcomp.c
> Fix some critical bugs spotted by coverity

- libr/bin/format/dex/dex.h
- libr/bin/p/bin_dex.c
- libr/bin/p/bin_sms.c
- libr/cons/rgb.c
- libr/core/cmd_meta.c
- libr/core/p/core_sixref.c
- libr/main/rahash2.c
- libr/search/strings.c
> Remove all global variables in rahash2 ##tools

- libr/util/str.c
> Fix oobread in `r_str_is_printable_limited` ##crash

- libr/core/cmd_open.c
* `start` on windows, `xdg-open` on Linux and `open` on mac
> Add `open` command as a wrapper for the system launcher ##shell

- libr/cons/canvas.c
- libr/core/canal.c
- libr/core/cio.c
- libr/core/cmd_anal.c
> Fix last coverity findings

- test/db/asm/evm.cs
- test/db/extras/asm/evm
Tests for https://github.com/radareorg/radare2-extras/issues/311.
> Add push32 test for EVM

- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_mips_gnu.c
- libr/include/r_util/r_strbuf.h
- libr/util/strbuf.c
> [5.8.0] Add r_strbuf_replace{f} ##util

- libr/hash/Makefile
- libr/hash/hash.c
- libr/hash/hcalc.c
- libr/hash/md4.c
- libr/hash/meson.build
- libr/hash/sip.c
- libr/hash/state.c
- libr/include/r_hash.h
- test/db/tools/rahash2
> [5.8.0] Implement the SIP hash algorithm ##crypto

- libr/config/config.c
- libr/include/r_util/r_str.h
- libr/util/str.c
> [5.8.0] Add new RStr.replaceAll() api ##util

- libr/anal/var.c
- libr/core/canal.c
- libr/core/cconfig.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
- libr/parse/p/parse_arm_pseudo.c
- test/db/anal/vars
> [5.8.0] Add anal.vars.newstack - configurable improved stack-relative var ##analysis

- libr/include/r_util/r_table.h
- libr/util/table.c
- test/db/cmd/cmd_table
> [5.8.0] Implement TSV and HTML output formats for RTable ##print

- libr/bin/Makefile
- libr/bin/blang.c
- libr/bin/demangle.c
- libr/bin/mangling/Makefile
- libr/bin/mangling/pascal.c
- libr/bin/meson.build
- libr/core/cmd_info.c
- libr/include/r_bin.h
- libr/main/rabin2.c
- test/db/cmd/dwarf
- test/db/formats/mangling/mangling
* https://github.com/rizinorg/rz-libdemangle/blob/main/src/pascal/pascal.c
> Import the free pascal symbol demangler from rizin ##bin

- libr/bp/bp.c
- libr/include/r_bp.h
> Boolified the breakpoint api

- libr/core/cconfig.c
- libr/core/cmd_print.c
- libr/core/core.c
- libr/core/disasm.c
- test/db/anal/x86_16
- test/db/cmd/cmd_pd_bugs
- test/db/cmd/feat_segoff
> [5.8.0] Rename asm.{off} variables to asm.offset. ##shell

- libr/asm/asm.c
- libr/core/disasm.c
> Fix "infinite" loop in cmdseek bug test

- libr/core/cmd.c
- libr/core/cundo.c
- libr/include/r_core.h
> Add the new ucu and ucd commands using the new core-undo apis ##shell

- libr/include/r_lang.h
- libr/lang/p/c.c
- libr/lang/p/cpipe.c
- libr/lang/p/go.c
- libr/lang/p/lib.c
- libr/lang/p/pipe.c
- libr/lang/p/rust.c
- libr/lang/p/spp.c
- libr/lang/p/v.c
- libr/lang/p/vala.c
- libr/lang/p/zig.c
> Add .author field in all the RLang plugins ##api

- libr/anal/p/anal_x86_cs.c
> Simplify x86_cs BSR esil ##refactor

- libr/include/r_util/r_str.h
- libr/util/str.c
> Fix return type of r_str_char_count ##util

- libr/include/r_anal.h
> Un-R_WIP r_anal_esil_dfg_reg_is_const

- libr/bin/p/bin_dex.c
- libr/bin/p/bin_mach0.c
- libr/core/cmd_debug.c
- libr/core/cmd_egg.c
- libr/core/cmd_project.c
- libr/core/cmd_write.c
- libr/core/esil2c.c
- libr/core/rtr_http.c
- libr/debug/debug.c
- libr/debug/dsignal.c
- libr/debug/p/debug_esil.c
- libr/debug/p/debug_native.c
- libr/io/p/io_r2k.c
- libr/io/p/io_winedbg.c
- libr/search/search.c
./sys/lint.sh showed all changes introduced in that PR for some reason.
> Change the way TODO messages are printed from eprintf to R_LOG_TODO #api?

- libr/util/str.c
> Minor COV fix in r_str_char_count ##util

- libr/crypto/meson.build
- libr/crypto/p/crypto_sm4.c
- libr/crypto/p/crypto_sm4_algo.c
- libr/include/r_crypto/r_sm4.h
> Deduplicate SM4 functions

- libr/magic/d/default/flash
- test/db/cmd/cmd_search_magic
Update flash detection according to https://github.com/ReFirmLabs/binwalk/blob/master/src/binwalk/magic/animation and add a test.
> Update flash magic and add a test

- test/db/cmd/cmd_search_crypto
Update test to match https://github.com/radareorg/radare2-testbins/pull/82
> Update test file in PGP test

- libr/core/cmd.c
- libr/core/cmd_cmp.c
- libr/core/cmd_debug.c
- libr/core/cmd_meta.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/core/rtr.c
- libr/core/vmenus.c
- libr/debug/debug.c
- libr/debug/p/debug_native.c
- libr/io/p/io_self.c
- libr/main/r2pm.c
- sys/lint.sh
Change R_LOG_INFO ("TODO calls to R_LOG_TODO
> Change R_LOG_INFO to R_LOG_TODO where suitable  ##api

- doc/fortunes.fun
- libr/core/anal_objc.c
- libr/core/canal.c
- libr/core/cmd_anal.c
- libr/include/r_util/r_print.h
- libr/util/print.c
> Remove RPrintRowlog and use R_LOG isntead ##shell

- libr/anal/p/anal_cris.c
- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_msp430.c
- libr/anal/p/anal_s390_cs.c
- libr/anal/p/anal_v850.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/capstone.inc
- libr/asm/asm.c
- libr/asm/p/asm_x86_as.c
- libr/asm/p/asm_x86_nasm.c
- libr/core/disasm.c
- libr/egg/egg.c
- libr/include/r_arch.h
- libr/util/arch.c
> Rename R_ASM_SYNTAX to R_ARCH_SYNTAX ##refactor

- libr/include/r_arch.h
> Initial commit on RArch structs ##arch

- libr/anal/anal.c
- libr/asm/asm.c
- libr/core/cconfig.c
- libr/core/disasm.c
- libr/include/r_arch.h
- libr/util/arch.c
> Rename r_arch_set_ to r_arch_config_set_ ##refactor

- libr/include/r_arch.h
> Add some r_arch api declarations ##arch

- libr/include/r_arch.h
> Fix license string in r_arch.h

- libr/config/config.c
- libr/include/r_util/r_str.h
- libr/util/str.c
> Fix RConfig.setB when the key doesnt exist ##core

- libr/core/cconfig.c
- libr/core/cmd_anal.c
- libr/core/panels.c
- libr/core/visual.c
> Deprecate graph.web eval config var ##config

- libr/arch/Makefile
- libr/arch/decoder.c
- libr/include/r_arch.h
> First implementation of r_arch decoder api ##arch

- libr/util/vector.c
> Fix UB bug when using r_vector random access ##api

- libr/anal/esil.c
- libr/anal/pin.c
- libr/bin/dwarf.c
- libr/bin/format/mach0/coresymbolication.c
- libr/bin/p/bin_dbginfo_dex.c
- libr/bin/p/bin_dbginfo_elf.c
- libr/bin/p/bin_dex.c
- libr/bin/p/bin_java.c
- libr/bin/p/bin_qnx.c
- libr/core/canal.c
- libr/core/cfile.c
- libr/core/cmd_anal.c
- libr/core/cmd_meta.c
- libr/core/cmd_open.c
- libr/util/table.c
- libr/util/utype.c
- shlr/sdb/Makefile
- shlr/sdb/config.mk
- shlr/sdb/src/array.c
- shlr/sdb/src/fmt.c
- shlr/sdb/src/json.c
- shlr/sdb/src/lock.c
- shlr/sdb/src/num.c
- shlr/sdb/src/query.c
- shlr/sdb/src/sdb.c
- shlr/sdb/src/sdb.h
- shlr/sdb/src/util.c
> Update to the latest SDB that's changing the sdb_itoa() signature

- libr/cons/grep.c
- libr/include/r_cons.h
- libr/include/r_util/r_json.h
- libr/util/json_parser.c
- test/db/cmd/feat_grep
> Fix #20760 - Implement native gron via ~{=} ##shell

- libr/core/cmd_print.c
- libr/util/format.c
> Fix #20772 - ihj rendering an invalid json because of pfj ##json

- libr/util/utf8.c
> Remove global from utf8 ##globals

- .github/workflows/tcc.yml
- binr/r2pm/r2pm.sh
- libr/cons/cons.c
- libr/core/cfile.c
- libr/core/cmd.c
- libr/core/cmd_project.c
- libr/core/disasm.c
- libr/include/r_cons.h
- libr/include/r_util/r_sys.h
- libr/main/r2pm.c
- libr/util/sys.c
- test/db/anal/arm
> Switch to the native implementation of r2pm by default ##tools

- libr/arch/arch.c
- libr/include/r_util/r_ref.h
- libr/main/rasm2.c
> Add r_ref_ptr() and fix unit test fatal warning

- libr/anal/anal.c
- libr/anal/fcn.c
- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_x86_cs.c
- libr/anal/p/capstone.inc
- libr/core/canal.c
- libr/include/r_anal.h
> Remove 10 more globals from analysis and capstone ##globals

- libr/core/cmd_print.c
- libr/include/r_util/r_protobuf.h
- libr/util/protobuf.c
- test/db/cmd/cmd_pFb
> Implemen pFbj for json printing of protobuf ##print

- libr/arch/Makefile
- libr/arch/arch.c
- libr/arch/decoder.c
- libr/arch/p/arch_null.c
- libr/asm/asm.c
- libr/include/r_anal.h
- libr/include/r_arch.h
- libr/include/r_reg.h
> WIP: RArch typedefs

- libr/anal/p/anal_s390_gnu.c
- libr/asm/arch/include/disas-asm.h
> Remove 3 globals in s390.gnu ##globals

- libr/anal/cond.c
- libr/arch/Makefile
- libr/arch/arch.c
- libr/arch/archcond.c
- libr/arch/p/arch_null.c
- libr/include/r_arch.h
> moar rarch

- libr/arch/decoder.c
- libr/include/r_arch.h
- libr/include/r_util/r_sys.h
- libr/util/str.c
> Introduce R_SYS_BITS_4 ##util

- libr/cons/cons.c
- libr/core/cbin.c
- libr/core/cfile.c
- libr/core/cmd.c
- libr/core/core.c
- libr/core/task.c
- libr/include/r_cons.h
- libr/include/r_core.h
- libr/include/r_th.h
- libr/main/radare2.c
Do not merge. its wip. right now the lock is making background analysis lock the shell which is something we dont want.
> WIP: Fixing race conditions with a global core lock

- libr/arch/aconfig.c
- libr/arch/arch.c
- libr/arch/archop.c
- libr/include/r_arch.h
> Introduce RArchConfig->decoder ##arch

- libr/core/cmd_anal.c
- test/db/cmd/cmd_aflxj
> Implement aflxj

- libr/anal/block.c
- libr/anal/p/anal_arm_cs.c
- libr/core/cmd_meta.c
- libr/core/project.c
- libr/core/task.c
- libr/flag/flag.c
- libr/include/r_flag.h
> Morecritical

- libr/anal/block.c
- libr/core/cmd_project.c
- libr/core/panels.c
- libr/core/visual.c
> WIP: Fix the panels cache ##visual

- libr/core/core.c
- libr/core/project.c
- libr/core/rvc.c
- libr/include/r_core.h
- libr/include/rvc.h
- libr/main/ravc2.c
- test/db/tools/ravc2
This is a continuation of https://github.com/radareorg/radare2/pull/20176
> Move rvc apis into callbacks

- libr/anal/esil.c
- libr/arch/p/arch_i4004.c
- libr/include/r_reg.h
- libr/reg/profile.c
- libr/reg/reg.c
- libr/reg/rvalue.c
> Initial ref-counted RRegItems, needed for threadsafety ##threads

- libr/core/cmd_anal.c
> Fix null pointer in aflxj ##anal

- binr/ravc2/ravc2.c
- libr/anal/dwarf_process.c
- libr/main/ravc2.c
> Implement dwarf.regName() for arm64 ##bin

- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_mips_gnu.c
- libr/bin/bin.c
- libr/bin/format/elf/elf.c
- libr/bin/p/bin_elf.c
- libr/bin/p/bin_elf.inc
- libr/config/config.c
- libr/core/cbin.c
- libr/core/cconfig.c
- libr/include/r_arch.h
- libr/include/r_bin.h
- test/db/cmd/cmd_i
- test/db/formats/elf/v850
> Remove useless asm.features, use bin.features to expose arm eabi ##bin

- libr/anal/fcn.c
> Fix #20798 - Fix bx after add lr,pc,0 in arm32 ##anal

- libr/bin/format/elf/elf.c
- libr/core/cproject.c
- libr/core/panels.c
- libr/core/project.c
- libr/core/rvc.c
- libr/include/r_core.h
- libr/include/rvc.h
- libr/main/ravc2.c
> Initial rvc refactoring and cleanup of the api ##vc

- libr/anal/p/anal_arm_gnu.c
- libr/anal/p/anal_s390_gnu.c
- libr/asm/arch/include/disas-asm.h
> Deglob 4 vars in the arm.gnu disassembler ##globals

- libr/bin/format/mach0/mach0.c
- libr/meson.build
* Fix "unknown command" harmless warnings on some binaries
> Expose the id_dylib macho command info into the bin kv ##bin

- dist/plugins-cfg/plugins.def.cfg
- dist/plugins-cfg/plugins.mingw.cfg
- dist/plugins-cfg/plugins.nocs.cfg
- libr/arch/meson.build
- libr/arch/p/Makefile
- libr/arch/p/amd29k.mk
- libr/arch/p/arch_amd29k.c
- libr/include/r_arch.h
> Copy anal_amd29k.c to rarch ##arch

- libr/include/r_io.h
- libr/include/r_types.h
- libr/io/io_bank.c
- libr/io/io_map.c
> Io reloc maps

- libr/io/io_map.c
> Fix reloc map memleak ##io

- libr/include/r_io.h
- libr/io/io_map.c
> Handle reloc maps properly in r_io_map_remap and r_io_map_resize ##io

- libr/bin/format/mach0/mach0.c
- libr/bin/format/mach0/mach0.h
- libr/bin/format/objc/mach0_classes.c
- libr/bin/p/bin_mach0.c
- libr/core/cbin.c
- libr/include/r_util/r_assert.h
- libr/util/buf.c
- test/db/anal/classes
> Stop messing with the io swizzling to remove 4 globals and 7x speedup

- libr/main/r2pm.c
* Dont copy files up and down, just use the repo
> Honor -f in r2pm -U to force clean the r2pm db ##r2pm

- dist/plugins-cfg/plugins.def.cfg
- libr/anal/p/anal_arm_cs.c
- libr/include/r_parse.h
- libr/include/r_util/r_str.h
- libr/main/r2pm.c
- libr/meson.build
- libr/parse/meson.build
- libr/parse/p/bpf_pseudo.mk
- libr/parse/p/evm_pseudo.mk
- libr/parse/p/parse_arm_pseudo.c
- libr/parse/p/parse_bpf_pseudo.c
- libr/parse/p/parse_evm_pseudo.c
- libr/parse/p/parse_x86_pseudo.c
- libr/parse/parse.c
- libr/util/str.c
- shlr/Makefile
- shlr/meson.build
- test/db/anal/arm
- test/db/anal/arm64
- test/db/anal/bpf
- test/db/anal/bpf_64
- test/db/anal/evm.cs
- test/db/anal/s390
- test/db/anal/x86_32
- test/db/asm/arm_64
- test/db/cmd/cmd_ao
- test/db/cmd/cmd_list
- test/db/cmd/cmd_search
> Use the latest capstone5-next with updated aarch64 support ##arch

- libr/anal/esil_dfg.c
- libr/include/r_anal.h
> Rename EsilDFGRegVar to EsilDFGVar and introduce EsilDFGVarType ##refactor

- libr/core/cmd_log.c
- libr/core/core.c
- libr/core/visual.c
- libr/include/r_util/r_log.h
- libr/util/log.c
> Redirect RLog messages into the Corelog ##logs

- libr/anal/esil_dfg.c
> Start implementing mem access support for esil dfg

- libr/core/cmd_search.c
> Add flags under the asm.str flag prefix when doing /az ##search

- libr/anal/anal.c
- libr/core/cconfig.c
- libr/core/core.c
- libr/core/disasm.c
> Implement asm.flags.right option ##disasm

- libr/anal/anal.c
- libr/anal/op.c
- libr/arch/arch.c
- libr/arch/p/arch_i4004.c
- libr/include/r_arch.h
- libr/reg/rvalue.c
> Wire-up RArch into RAnalOp ##arch

- libr/core/cmd_anal.c
> Run /azq in aaaa ##analysis

- libr/core/cmd_search.c
> Add x86-32 support to /az ##search

- shlr/Makefile
- sys/install.sh
> Ensure shlr/capstone is up-to-date in sys/install.sh

- libr/anal/esil_dfg.c
- libr/core/cmd_anal.c
> Simple const pointer support in esil dfg

- libr/anal/p/anal_evm_cs.c
> Fix memleak

- libr/arch/arch.c
- libr/core/cconfig.c
- libr/core/cmd_log.c
* Fix column output of rasm2/ranal2
> Add Ls to list assemblers, and LA to list analysis plugins ##tools

- libr/cons/dietline.c
Fix the issue #20847  
Note : I tested this change in Windows, Linux, but not MacOS because I do not have a Mac
> Fix Ctrl+Arrow shortcut

- libr/bin/format/objc/mach0_classes.c
- test/db/formats/mach0/objc
> Expose klass->super details for objc categories ##bin

- libr/config/config.c
> Use PJ in RConfig.list(.asJson)

- libr/core/cmd_magic.c
- libr/core/cmd_search.c
- test/db/cmd/cmd_search
- test/db/cmd/cmd_search_magic
- test/db/tools/rafind2
Previously the hits flag from `/m` were also 0 and thus erased by following research. It is corrected and display in search results. Test are moved to correct file.
> Correct hit results for /m and update tests

- libr/anal/esil_dfg.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
> Rename R_ANAL_ESIL_DFG_BLOCK_ to R_ANAL_ESIL_DFG_TAG_ ##refactor

- libr/anal/dwarf_process.c
> Silent noisy warning in dwarfprocess ##bin

- libr/cons/pal.c
> Use PJ in RConsPal.list()

- libr/core/cmd_anal.c
- libr/core/cmd_search.c
- sys/sanitize.sh
> Make /az faster after aeim, skipping unrelated regions ##search

- libr/cons/line.c
> Fix memory leak in dietline ##leaks

- libr/include/r_util/r_ref.h
> Improve r_ref implementation with debugging support ##api

- libr/anal/p/anal_arm_cs.c
> Some minor fixes in the anal.arm.cs plugin

- .github/workflows/tcc.yml
- Makefile
> Run unit tests in parallel ##ci

- libr/core/pseudo.c
- libr/include/r_vector.h
> Fix issue in 'pdc' that was showing empty orphan nodes ##print

- libr/anal/fcn.c
- libr/anal/p/anal_x86_cs.c
- libr/arch/aconfig.c
- libr/arch/arch.c
- libr/core/agraph.c
- libr/core/core.c
- libr/include/r_arch.h
> Remaining refleaking fixes

- libr/core/rvc.c
> Fix rvc.commit when non-interactive with a default message ##rvc

- binr/r2r/r2r.c
- configure
- libr/asm/p/asm_x86_nz.c
- man/r2r.1
- test/db/asm/x86_32
Assorted trivial fixes:
* there's a 64-bit instruction in the 32-bit asm test file
* r2r man page and help needs some love
* fixing some typos
I'm happy to split this up if needed
> Improve tests, fix typos

- libr/anal/class.c
- libr/core/agraph.c
- libr/core/canal.c
- libr/core/cmd_anal.c
- libr/include/r_agraph.h
- libr/include/r_util.h
- libr/include/r_util/r_graph_drawable.h
- libr/util/graph_drawable.c
- test/unit/test_agraph.c
- test/unit/test_anal_class_graph.c
> Stop aeg from abusing agg ##refactor

- libr/anal/esil_dfg.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
> Add support for stack-computed const pointers in esil_dfg ##anal

- libr/core/canal.c
- libr/core/rvc.c
> Fix double re

- libr/core/cmd_info.c
- test/db/cmd/classes
> Implement 'ic.' command ##bin

- dist/plugins-cfg/plugins.def.cfg
- libr/include/r_io.h
- libr/io/p/Makefile
- libr/io/p/io_treebuf.c
- libr/io/p/treebuf.mk
> Add treebuf io plugin ##io

- libr/io/p/io_treebuf.c
> Minor bugfix in treebuf io plugin ##io

- libr/core/cmd_log.c
- libr/core/cmd_search.c
- test/db/anal/arm64
- test/db/cmd/cmd_search
- test/db/cmd/cmd_search_hit
> Improve json output for /asj and /atj ##search

- libr/io/p/io_treebuf.c
> Add "reset" system command to treebuf io plugin ##io

- libr/io/p/io_treebuf.c
> Fix stupid segfault

- libr/parse/p/parse_arm_pseudo.c
> Improve pseudodisasm for arm64 ##disasm

- libr/cons/grep.c
- libr/core/pseudo.c
- libr/include/r_util/r_print.h
- libr/include/r_util/r_str.h
- libr/util/print.c
- libr/util/str_trim.c
- libr/util/token.c
- test/db/cmd/cmd_pdc
> Add colorization support to pdc output ##decompiler

- libr/core/cio.c
- libr/core/core.c
- libr/util/print.c
> Minor comment/string colorization improvement in pdc output

- libr/core/cbin.c
> Speedup class bin loading with bin.filter=false ##bin

- libr/core/cmd_print.c
- libr/util/pkcs7.c
- libr/util/utype.c
- test/db/cmd/cmd_pFp
> Add pFpj command to print PKCS7 files as JSON ##print

- libr/cons/cpipe.c
- libr/core/cconfig.c
- libr/core/cfile.c
- libr/core/cmd_cmp.c
- libr/core/cmd_eval.c
- libr/core/cmd_type.c
- libr/core/core.c
- libr/core/fortune.c
- libr/include/r_util/r_file.h
- libr/include/r_util/r_str.h
- libr/main/radare2.c
- libr/util/file.c
- libr/util/sandbox.c
- libr/util/str.c
- libr/util/syscmd.c
- libr/util/xdg.c
- test/unit/test_str.c
> Rename RStr.home() to RFile.home() as part of the Plan ##api

- libr/include/r_util/r_ctypes.h
- libr/util/utype.c
> Remove another unnecessary r2580 comment and add R_TYPE_INVALID

- libr/crypto/hash/sha2.c
- libr/crypto/hash/sha2.h
- libr/util/rvc.c
> Fix static builds

- libr/cons/cons.c
- libr/core/cconfig.c
- libr/core/cmd_project.c
- libr/core/core.c
- libr/core/visual.c
- libr/include/r_cons.h
> Deprecate r_cons_eprintf and use R_LOG instead ##api

- libr/main/r2pm.c
- man/r2pm.1
> Implement r2pm -cp like it was in r2pm.sh ##r2pm

- libr/bin/format/mach0/mach0.c
- libr/core/cmd_print.c
- libr/include/r_util/r_asn1.h
- libr/util/asn1.c
- libr/util/asn1_str.c
- libr/util/pkcs7.c
- libr/util/x509.c
- test/db/cmd/cmd_pFa
> Initial refactoring/cleanup of ASN1 parser api ##print

- libr/anal/value.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
- libr/include/r_anal/op.h
- libr/util/vector.c
> Fix #20827 - Show srcs/dsts in aoj ##analysis

- libr/core/cmd_project.c
- test/db/cmd/projects
> Do changes in Pc/Px/PS as planned

- test/Makefile
> Test units once

- libr/anal/anal.c
- libr/anal/fcn.c
- libr/core/cconfig.c
- libr/include/r_anal.h
> Add anal.noret and refactor anal.noret.refs ##analysis

- libr/anal/p/anal_arm_cs.c
- libr/core/cmd_search.c
> Add /au to search for unknown destination jmp/call ##analysis

- libr/core/cmd_search.c
> Fix /au after aeim ##search

- dist/wapm/r2/Makefile
- dist/wapm/r2/wapm.toml
- libr/asm/asm.c
- libr/io/io_map.c
- sys/android-build.sh
- sys/emscripten.sh
- sys/ios-cydia.sh
- sys/ios-sdk.sh
- sys/ios-simulator.sh
- sys/ios-static.sh
- sys/mingw32.sh
- sys/mingw64.sh
- sys/osx-pkg.sh
- sys/sdk.sh
- sys/static.sh
- sys/wasi.sh
- sys/wasm.sh
> Load descriptions

- libr/core/cmd_eval.c
- libr/socket/r2pipe.c
- test/unit/test_r2pipe.c
> Take into account the static themes when listing via eco ##cons

- libr/core/cmd_flag.c
- libr/socket/r2pipe.c
> Fix segfault in ci

- libr/anal/anal.c
- libr/core/cconfig.c
- libr/include/r_arch.h
- libr/main/rasm2.c
- man/rasm2.1
> Implement rasm2 -LLL to list arch plugins ##tools

- libr/anal/anal.c
> Do not recurse noreturn inspection when !addr or -1 ##analysis

- libr/main/rax2.c
- test/db/tools/rax2
Fix the decoding part of issue #20978 but not the encoding.
> rax2: Fix base64 null byte decoding

- libr/Makefile
> Do not install the v35 archives (-50MB) in `make install` ##build

- libr/include/r_th.h
> Fix zig's @cInclude of r_th.h ##build

- shlr/capstone.sh
Prevents `git reset` from failing with `fatal: Could not parse object `
> Run git fetch if we don't have the correct capstone commit locally

- libr/anal/p/anal_mips_gnu.c
- libr/bin/p/bin_mach0.c
- libr/bin/p/bin_qnx.c
- libr/config/callback.c
- libr/core/cmd_eval.c
- libr/core/panels.c
- libr/core/vmenus.c
- libr/include/r_util/r_str.h
- libr/reg/reg.c
- libr/util/str.c
- shlr/java/class.c
> Deprecate r_str_dup() - related to #20959 ##api

- libr/core/panels.c
- libr/main/rax2.c
> Fix last two covs

- libr/util/rvc.c
Avoids this type of error `error: pathspec 'message' did not match any file(s) known to git` followed by `Cannot save project`
> Quote commit message to avoid git error when saving project

- libr/include/r_reg.h
- libr/reg/arena.c
- libr/reg/reg.c
> WIP: Implement RReg.clone() ##api

- binr/r2r/load.c
- binr/r2r/run.c
- binr/radare2/radare2.c
- libr/anal/fcn.c
- libr/anal/flirt.c
- libr/core/cmd_print.c
- shlr/ar/ar.c
> Remove eprintf calls in favor of r_log_api

- libr/core/cmd_api.c
- libr/core/cmd_print.c
> Fix pCD stack command glitch reported by alex27

- .github/workflows/tcc.yml
Uses all --with-sysFOO flags
I've added building r2 with all the `--with-sys...` configure flags.
> Tests for #20956

- libr/bin/bfile.c
- libr/core/cconfig.c
- libr/include/r_bin.h
> Reduce false positive noisy strings ##bin

- .github/workflows/build.yml
- .github/workflows/coverity-scan.yml
- sys/version.py
* This syntax will be deprecated the 1st of June 2023
> Use github-output instead of set-output in the ci jobs

- libr/core/cmd_debug.c
- libr/core/cmd_open.c
- libr/core/cmd_print.c
- libr/main/rasm2.c
- libr/util/asn1.c
* the 'm' was refering to multimedia, 'v' is about vector
> Fix #20242  - Rename the drm command to drv for consistency ##shell

- README.md
> Fix: discord invite link

- libr/asm/asm.c
- test/db/cmd/egg
> Fix asm.assembler regression fixing tests

- libr/core/cmd_debug.c
- libr/core/cmd_print.c
- libr/include/r_util/r_time.h
- libr/util/time.c
* Available via `date -b`
* As well as another date format via `ptb`
> Add support for the swatch dot-beat internet time ##print

- libr/core/cmd_eval.c
> Fix theme listing

- libr/bin/format/pdb/pdb_downloader.c
- libr/bin/mangling/cxx/cp-demangle.c
- libr/core/cbin.c
- libr/core/cmd_info.c
- libr/main/rabin2.c
- libr/util/time.c
- test/db/formats/pdb
> Fix #21020 - fix json format for rabin2 -jM when no main is found ##bin

- libr/core/cconfig.c
> Enable cmd.undo by default ##core

- libr/main/ravc2.c
- libr/util/rvc.c
- libr/util/rvc_git.c
- libr/util/rvc_rvc.c
rationale: rvc init does not output anything so why should git?
> Fix some problems with the rvc-refactor pr

- libr/asm/acode.c
- libr/asm/asm.c
- libr/asm/p/asm_null.c
- libr/asm/p/asm_x86_nz.c
- libr/bin/p/bin_xnu_kernelcache.c
- libr/core/cconfig.c
- libr/include/r_arch.h
- libr/include/r_asm.h
- libr/main/rasm2.c
> Internal cleanup of asm.c, deprecate the disassembly callback ##asm

- README.md
Changed the Discord invite links, because the old ones were expired.
> Changed the expired Discord invite links

- libr/anal/var.c
> Fix warning in aflj when parsing vargarg signatures ##anal

- libr/core/cconfig.c
- libr/core/core.c
> Implement cmd.usr1 and cmd.usr2 to handle signals on unix ##shell

- libr/core/cbin.c
- test/db/formats/pe/versioninfo
- test/db/json/json4
> Fix rabin2 -gj and add tests

- libr/bin/format/elf/elf.c
> Fix wrong detection of `main` in elf-arm32 ##bin

- libr/esil/esil.c
> Minor indentation fixes in esil.c

- libr/core/panels.c
* Fixes issue where 'k' goes up two rows instead of one
* Previously moving offscreen with 'j/k' would lead to weird behaviour (getting 'blocked', panel not refreshing), this fixes that as well
* 'k' doesn't go up two rows anymore
* Makes the moving out of bounds behaviour more like visual mode
> Some fixes for the j/k movment in panels' cursor mode ##visual

- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
- libr/anal/p/anal_gb.c
- libr/anal/p/anal_h8300.c
- libr/anal/p/anal_tms320.c
- libr/arch/p/arch_amd29k.c
- libr/arch/p/arch_i4004.c
- libr/arch/p/arch_pickle.c
- libr/arch/p/arch_rsp.c
- libr/arch/p/arch_sh.c
- libr/arch/p/arch_v810.c
- libr/asm/asm.c
- libr/core/core.c
- libr/include/r_arch.h
- libr/include/r_asm.h
- libr/libs.mk
> Remove the unused RAsm.binb ##asm

- libr/asm/arch/tms320/tms320_dasm.c
- libr/include/r_parse.h
- libr/parse/filter.c
- libr/parse/p/parse_x86_pseudo.c
- libr/parse/p/parse_z80_pseudo.c
- test/db/anal/z80
> Fix the parse.z80.pseudo plugin and add a test ##asm

- libr/include/r_util/r_asn1.h
- libr/util/asn1.c
- test/db/cmd/cmd_pFa
> Correct ASN.1 BIT_STRING parsing

- libr/core/cmd_open.c
> omfg runs omm if no map is set ##io

- libr/include/r_util/r_num.h
- libr/main/rasm2.c
- libr/util/unum.c
> Fix rasm2 -LLL using the new multi-bits macros ##arch

- libr/anal/op.c
- libr/arch/p/arch_sh.c
> Fix size returned from r_anal_op ##anal

- libr/main/radare2.c
> Fix r2 -2 ##tools

- libr/anal/esil_cfg.c
- libr/anal/esil_dfg.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
- test/unit/test_esil_dfg_filter.c
> Some more improvements to esil_dfg ##anal

- libr/core/cmd_anal.c
- libr/core/cmd_debug.c
> Fix drt? and drr? spotted by d?*

- libr/main/rasm2.c
> Fix asm/dis/esil flagstring in rasm2 -LLL

- libr/core/cmd_help.c
> Show number conversion error messages in `?v` command ##shell

- libr/main/rabin2.c
* Handy for oneliners when .TEXT changes
> Use glob expressions to specify section name to dump ##bin

- libr/bin/bin.c
- libr/core/canal.c
- libr/core/cbin.c
- libr/core/cmd.c
- libr/core/cmd_anal.c
- libr/include/r_bin.h
> Fix use-after-free after @@@e spotted by meme ##crash

- libr/core/agraph.c
- libr/core/anal_objc.c
- libr/core/disasm.c
- libr/core/panels.c
- libr/core/rtr.c
- libr/core/vmenus.c
- sys/lint.sh
> Some more RConfig.geti -> getb code cleanup, wip new lint

- libr/core/cmd_help.c
- libr/core/cmd_print.c
- sys/lint.sh
> Dont use |Usage, because Usage is the new trend

- libr/arch/p/pickle/plugin.c
This allows pickle opcodes to be larger than 64 bytes. Pickles use inline data so opcodes can be very big.
The new arch API is really nice. I had my own patched version of the old API to let me assemble large pickle ops. This is even better.
> Assemble large pickle instructions ##arch

- libr/core/cmd_hash.c
- libr/include/r_lang.h
- libr/lang/lang.c
- libr/lang/p/c.c
- libr/lang/p/cpipe.c
- libr/lang/p/go.c
- libr/lang/p/lib.c
- libr/lang/p/pipe.c
- libr/lang/p/rust.c
- libr/lang/p/spp.c
- libr/lang/p/spp_r2.inc
- libr/lang/p/v.c
- libr/lang/p/vala.c
- libr/lang/p/zig.c
> Refactor RLang api to use the new design ##api

- libr/core/cconfig.c
- libr/core/vmenus.c
> Use RAnalOp instead of RAsmOp in r_core_visual_bit_editor ##visual

- libr/bin/bfile.c
- libr/bin/dwarf.c
- libr/core/cfile.c
- libr/core/cio.c
- libr/core/cmd_meta.c
- libr/core/cmd_open.c
- libr/include/r_bin.h
- libr/io/io_bank.c
- libr/main/radare2.c
- test/db/cmd/dwarf
> Lebinmerge

- libr/anal/anal.c
- libr/core/cmd_anal.c
- test/db/anal/snes
- test/db/cmd/cmd_i
- test/db/formats/elf/v850
> Always show all the archinfo, even when not provided by the plug ##analysis

- libr/core/cmd.c
- libr/core/cmd_hash.c
- libr/core/cmd_print.c
- libr/include/r_arch.h
- libr/include/r_lib.h
> Add 'js' and 'js:' commands, as well as improve help for #!? ##lang

- libr/core/cmd.c
> Add "" command to run RCore.cmdCall() ##shell

- libr/include/r_io.h
- libr/include/r_util/r_itv.h
- libr/io/io_cache.c
> Start rewriting io_cache.c ##io

- libr/io/io_cache.c
- libr/io/io_desc.c
> Remove invocation of v layer cache in r_io_desc_read ##io

- libr/lang/p/qjs.c
- shlr/qjs/deps.mk
- shlr/qjs/src/libbf.c
- shlr/qjs/src/libbf.h
> Enable Bignum support to the QJS interpreter ##lang

- libr/lang/p/qjs.c
- shlr/qjs/src/quickjs.c
> Fix another UB bug in quickjs

- libr/core/cmd_anal.c
- libr/lang/p/qjs.c
- libr/lang/p/tsc.c
- shlr/qjs/Makefile
- shlr/qjs/js_r2papi.c
- shlr/qjs/js_r2papi.qjs
- shlr/qjs/package.json
> Use r2papi 0.0.4 with base64 and R2Api is now known as R2Papi ##lang

- libr/anal/anal.c
- libr/anal/fcn.c
- libr/anal/xrefs.c
- libr/core/cconfig.c
- libr/core/cmd_anal.c
- libr/include/r_anal.h
- test/db/anal/arm
- test/db/anal/x86_64
- test/db/cmd/cmd_ax
- test/db/cmd/cmd_zignature
- test/db/json/json2
* Add missing RAnal.XrefType.JUMP.toString()
> Improve the tailcall detection logic ##analysis

- test/db/cmd/projects
> Use P instead of Po in projects ##projects

- libr/bin/d/jni.h
- libr/include/r_util/r_num.h
- libr/util/unum.c
- shlr/qjs/deps.mk
- shlr/qjs/src/cutils.h
> Enable BigNum in qjs ##lang

- libr/cons/canvas.c
- libr/core/agraph.c
- libr/include/r_cons.h
> Initial work in graph.bubble for custom bg color in nodes ##graph

- libr/core/cmd_anal.c
fixed a used after free the compiler was complaining about
> Fixed use after free...?

- libr/anal/tid.c
- libr/include/r_anal.h
- libr/include/r_reg.h
- libr/reg/reg.c
> Make RReg refcounted ##api

- libr/core/cmd.c
> Print whatever is taken from io_system to rcons ##shell

- libr/core/cmd.c
- libr/include/r_util/r_strbuf.h
- libr/io/Makefile
- libr/io/io_stream.c
- libr/io/io_stream.h
- libr/io/meson.build
- libr/io/p/io_serial.c
- libr/io/p/io_socket.c
- libr/socket/socket.c
> Initial implementation of the generic io-stream api ##io

- libr/core/cmd.c
- libr/core/cmd_help.c
- libr/lang/p/qjs.c
- libr/main/radare2.c
- man/radare2.1
- shlr/qjs/js_repl.c
- shlr/qjs/js_repl.qjs
- sys/rebuild.sh
* Fix "script not found" issue, solve command injection bugs
> Make r2 -j work as a hashbang handler for qjs ##lang

- .github/workflows/build.yml
- sys/tarball.sh
> Generate a tarball with all the sources inside

- libr/arch/p/arm/armass.c
- test/db/asm/arm_32
> Fix ARM assembler for blt, ble, cmn, tst, and teq instructions ##asm

- libr/lang/p/qjs.c
- libr/lang/p/tsc.c
- libr/main/radare2.c
- shlr/qjs/Makefile
- shlr/qjs/README.md
- shlr/qjs/js_r2papi.c
- shlr/qjs/js_r2papi.qjs
- shlr/qjs/package.json
> Update typescript compiler and move r2plugin into r2

- libr/core/cmd_api.c
- libr/core/cmd_log.c
- libr/core/core.c
- libr/lang/p/qjs.c
- libr/lang/t/coreplug.qjs
- libr/util/lib.c
- shlr/qjs/src/quickjs.h
> Remove global in util/lib and just use RLogLevel ##globals

- libr/core/cmd.c
> Implement uname -h, -m, -b, -j ... ##shell

- libr/core/libs.c
> Register RArch plugins to be loaded dynamically ##arch

- libr/core/canal.c
- libr/core/core.c
r2 segfaulted when I was merging functions and this potentially fixes that.
> Rework function merging

- .github/workflows/build.yml
My attempt at addressing #21055. I essentially added a new job to the CI that compares the ABI of the latest release to the one currently being built. Let me know what you think.
> Integrate ABI diffing into CI scripts

- libr/core/cmd.c
- libr/core/cmd_help.c
> Add help message for the quote command `"?` ##shell

- libr/anal/p/anal_arm_cs.c
- libr/anal/p/anal_arm_v35.c
- test/db/esil/arm_64
> Fix emulation of the arm64 `tst` instruction ##esil

- libr/anal/meta.c
- libr/cons/hud.c
- libr/core/canal.c
- libr/core/cconfig.c
- libr/core/cmd_print.c
- libr/core/core.c
- libr/core/disasm.c
- libr/core/visual.c
- libr/util/hex.c
- libr/util/print.c
- libr/util/str.c
> Minor hexdump optimization, use more cmdCall and minor cleanups

- libr/core/cmd.c
- libr/core/cmd_meta.c
- libr/core/cmd_print.c
- libr/core/core.c
- libr/core/patch.c
> WIP: implement RCore.cmdCallAt() ##api

- doc/termux.md
- libr/core/cbin.c
- libr/core/cmd_macro.c
- libr/core/cmd_print.c
- libr/core/corelog.c
- libr/core/panels.c
- libr/core/pseudo.c
- libr/main/r2pm.c
- sys/install.sh
> Remove build warnings spotted in termux and improve install instructions

- libr/lang/p/qjs.c
- shlr/qjs/js_r2papi.c
- shlr/qjs/js_r2papi.qjs
- shlr/qjs/package.json
> Update r2papi-ts 0.0.23

- dist/wapm/r2/wapm.toml
- dist/wapm/rasm2/Makefile
- dist/wapm/rasm2/wapm.toml
- dist/wapm/rax2/Makefile
- dist/wapm/rax2/wapm.toml
- libr/core/cconfig.c
> Publish updated wapm/wasi packages for r2, rax2 and rasm2

- .github/workflows/build.yml
- dist/rpm/Makefile
- dist/rpm/radare2.spec
> Update the SPEC file and build RPM packages in the CI ##ci

- libr/bin/dwarf.c
- libr/include/r_bin_dwarf.h
- test/db/formats/dwarf
My attempt to support DWARF5 line header parsing. Mostly done, just need to update the tests.
> DWARF5 line header parsing

- libr/anal/d/Makefile
- libr/anal/d/cc-mips-16.sdb.txt
- libr/anal/p/anal_mips_cs.c
- libr/anal/p/anal_mips_gnu.c
- libr/bin/format/elf/elf.c
- test/db/anal/mips_micro
> Honor the micromips codealign, add missing =SN and cc ##anal

- libr/main/radare2.c
See https://github.com/radareorg/radare2/issues/8992#issuecomment-1384298988. Try to fix it after #21260 failed using another way. Handle command line arch and bits parameters before initializing debug plugin.
> Apply command line settings before initializing debug plugin

- libr/bin/p/bin_elf.inc
- libr/bin/p/bin_te.c
- libr/core/cmd_info.c
- test/fuzz/fuzz_dwarf.c
- test/fuzz/meson.build
> Add the dwarf fuzzer tool ##test

- libr/core/cmd_meta.c
- libr/core/disasm.c
- libr/include/r_anal.h
- test/db/cmd/metadata
> Bring back and improve the Cr command ##disasm

- test/fuzz/README.md
- test/fuzz/meson.build
As explained  [here](https://www.llvm.org/docs/LibFuzzer.html#fuzzer-usage), meson may have problems handling the fuzzing build.  I update the build according to this [issue](https://github.com/mesonbuild/meson/issues/7761).
> Update fuzzer build instructions ##test

- libr/arch/p/v850/plugin.c
- libr/core/cconfig.c
- sys/rebuild.sh
- test/db/cmd/cmd_eval
> Fix asm.cpu=? when using arch plugins ##arch

- libr/arch/p/v850/plugin.c
- libr/arch/p/v850/v850e0.h
> Improve v850 esil support and fix some related bugs ##arch

- libr/anal/reflines.c
- libr/core/disasm.c
- test/db/cmd/metadata
> Blindfix for the uaf in Cr
