radareorg/radare2

libr/arch/p/v850/plugin.c

moar v850 esil

---

libr/arch/p/v850/plugin.c

Add esil support for v850 reti instruction ##arch

---

libr/arch/p/v850/plugin.c

Add esil support for v850 ei and di instructions ##arch

---

shlr/zip/zip/zip_name_locate.c

Do not depend on strcasecmp in libzip, build fail on Centos7

---

libr/core/cbin.c
test/db/cmd/cmd_i
test/db/cmd/tables
test/db/formats/elf/helloworld-gcc-elf
test/db/formats/mz/1byte

Massage the bottleneck that was making r2dec super slow ##perf

---

libr/arch/p/v850/plugin.c

Add esil support for v850 ldb, ldh and ldw instruction ##arch

---

libr/arch/p/v850/plugin.c

Add esil support for v850 stb, sth and stw instruction ##arch

---

libr/anal/arch/gb/gbdis.c
libr/anal/c/libtcc.c
libr/anal/c/tccpp.c
libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_mips_cs.c
libr/anal/p/anal_riscv_cs.c
libr/anal/p/anal_x86_cs.c
libr/core/visual.c
libr/core/vmenus.c
libr/io/p/io_debug.c
libr/io/p/io_gprobe.c
libr/io/p/io_r2k_linux.c
libr/lang/p/c.c
libr/main/r2agent.c
libr/socket/socket.c
libr/util/print.c
libr/util/randomart.c
libr/util/seven.c
libr/util/utype.c

* Use r_str_newf() or snprintf ensuring buffer size
* No vulns found, but better to avoid compiler warnings
* sprintf like strcpy is a bad practice

Avoid the use of sprintf()

---

libr/util/x509.c

Keep the ABI for x509

---

libr/bin/format/objc/mach0_classes.c

Fix heap overflow in the swift parser ##bin

---

libr/arch/p/v850/plugin.c

I have no idea, if this actually works as expected. I hate signed multiplication

Add esil support for mulh reg, reg v850 instruction ##arch

---

meson.build

Simplify meson.build and fix generation of r_userconf.h

---

libr/core/core.c
libr/include/r_core.h

Just define those apis them in the right place

---

dist/plugins-cfg/plugins.def.cfg
libr/arch/p/arch_lua.c
libr/arch/p/lua.mk
libr/arch/p/lua/Makefile
libr/arch/p/lua/asm/Makefile
libr/arch/p/lua/asm/lua53.mk
libr/arch/p/lua/lua53.c
libr/arch/p/lua/lua53.h
libr/arch/p/lua/lua53.mk
libr/arch/p/lua/lua53_parser.c
libr/bin/p/bin_lua.c
libr/bin/p/lua.mk
libr/include/r_arch.h
libr/include/r_bin.h
sys/lint.sh

Initial LUA support for RBin and RArch ##arch

---

libr/core/canal.c

Remove duplicated code adding a string reference during analysis ##anal

---

libr/arch/p/v850/plugin.c

Add esil support for satadd, satadd_imm5, satsub and satsubr v850 instruction ##arch

---

libr/core/core.c

Fix another refleak in core

---

libr/anal/p/anal_bf.c
libr/anal/p/anal_dalvik.c
libr/bin/p/bin_coff.c
libr/bin/p/bin_java.c
libr/bin/p/bin_xcoff64.c
libr/bin/p/bin_xtr_dyldcache.c
libr/core/cmd.c
libr/core/linux_heap_glibc.c
sys/lint.sh

Add RNEW0( lint and fix some free ((

---

.github/workflows/build.yml

Upgrade to abidiff 2.2 ##ci

---

libr/esil/esil.c

Better nullchk and reduce dereferences in esil ##esil

---

libr/core/cmd_search.c
test/db/cmd/cmd_search
test/db/esil/arm_16

Fix #21339 - Fix syscall search when executed twice ##search

---

libr/anal/p/anal_x86_cs.c

Attempt to fix the esil for shift instructions on X86 ##esil

---

libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_arm_v35.c
libr/anal/p/anal_dalvik.c
libr/esil/esil.c

Implement esil for arm64's brk and clarify TRAP usage ##esil

---

libr/core/canal.c
libr/core/cmd_anal.c
libr/core/cmd_search.c

Invalid call from warning is now a debug message ##anal

---

libr/core/cconfig.c
libr/core/cmd.c

Use single quote instead of "" for RCore.call() ##core

---

libr/esil/esil.c
libr/include/r_esil.h

More code cleanup in esil.c

---

libr/bin/p/bin_msx.c
libr/main/r2pm.c

Some fixes for the bin.msx plugin ##bin

---

libr/anal/esil_dfg.c

WIP: Aim to add POP and DUP for dfg ##esil

---

libr/core/cmd_search.c

Honor esil.* options in RAnal.search ##search

---

sys/user.sh

Passes any arguments given to `sys/user.sh` along to the build scripts.

Support arguments in the user install script

---

libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_search.c

New 'aag' command to reanalize all function refs ##anal

---

libr/bin/format/pdb/tpi.c
libr/bin/format/pe/pe.c
libr/bin/mangling/cxx/cp-demangle.c
libr/bin/mangling/cxx/libiberty.h
libr/bin/p/bin_lua.c
libr/cons/html.c
libr/core/cmd_debug.c
libr/core/cmd_print.c
libr/crypto/hash/hash.c
libr/debug/p/debug_bochs.c
libr/debug/p/native/darwin.c
libr/egg/egg_lang.c
libr/egg/emit_arm.c
libr/lang/p/cpipe.c
libr/util/charset.c
libr/util/print.c
libr/util/unum.c

Remove some unsafe sprintf/strcpy

---

libr/core/cmd_anal.c
sys/counters.sh

Add help message and improve the `ahs` command ##shell

---

libr/esil/esil.c
libr/esil/esil_trace.c
libr/include/r_anal.h
libr/include/r_esil.h
libr/util/unum.c
test/db/esil/flag_tests

Cleanup and minor improvements for esil.c

---

libr/include/r_types_base.h

Introduce the new R_CONST macros ##api

---

libr/esil/esil.c
libr/reg/rvalue.c

Fix two undefined behaviour bugs in esil and reg

---

libr/anal/p/anal_x86_cs.c

Add some recently seen x86-32 preludes ##anal

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0_defines.h

Add missing S_INIT_FUNC_OFFSETS definition for macho ##bin

---

libr/arch/p/dis/dis.c
libr/magic/d/default/dis

* Fix Dis fuzz issue
* Add Dis magic

Fix Dis fuzz issue

---

binr/r2r/run.c
libr/util/print.c
test/db/anal/noreturn
test/db/cmd/midbb

Load the bin.types again from r2r ##test

---

libr/arch/p/dis/dis.c
libr/bin/p/bin_dis.c

Fix asan signed UB warning on the dis plugin

---

libr/arch/p/nios2/nios2-dis.c
libr/arch/p/nios2/plugin.c

Improve the NIOS arch plugin with regs, archinfo and invalid ##arch

---

libr/bin/dwarf.c
test/db/cmd/dwarf

Fix oobread in dwarf5 parser ##crash

---

libr/anal/p/anal_8051.c
libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_arm_v35.c
libr/arch/p/xtensa/plugin.c

Add space before parenthesis to conform the r2 coding style

---

libr/syscall/d/gen.py
libr/syscall/d/meson.build
meson.build
sys/counters.sh

* Like it's with with the make build system

Fix #21375 - Generate .sdb files properly for syscalls with meson ##build

---

libr/arch/p/or1k/plugin.c
libr/arch/p/snes/plugin.c

Remove some R_TH_LOCAL globals in two arch plugin: snes and or1k

Remove some R_TH_LOCAL globals

---

libr/anal/fcn.c
libr/include/r_anal/op.h
libr/lang/p/qjs.c
libr/lang/p/qjs/arch.c
libr/lang/p/qjs/core.c
libr/lang/t/archplug.qjs

Initial support for r_arch plugins via qjs ##lang

---

libr/core/cmd_project.c
libr/include/rvc.h
libr/util/rvc.c
libr/util/rvc_git.c
libr/util/rvc_rvc.c

Fix segfault when saving a project with no write perms in home ##crash

---

libr/arch/p/v850/plugin.c

Improve v850 esil support ##arch

---

libr/arch/p/pic/plugin.c
libr/lang/p/qjs/arch.c

Cleanup the PIC plugin

---

libr/lang/p/qjs.c
libr/lang/p/qjs/loader.c
test/db/cmd/cmd_js

* Supports files generated with frida-compile

Implement ESM module loader for the QJS runtime ##lang

---

libr/lang/p/qjs/arch.c
libr/lang/p/qjs/loader.c

Add fake 'r2papi' module for r2frida-compile scripts ##lang

---

libr/bin/dbginfo.c

* As reported by Ted Carter in the chat. Thanks!

Fix absolute path resolution for dwarf source files ##bin

---

libr/arch/p/riscv/plugin.c
libr/bp/bp.c
libr/cons/pager.c
libr/core/cmd_project.c
libr/core/project.c
libr/io/io.c
libr/io/ptrace_wrap.c
libr/util/format.c
libr/util/list.c
libr/util/print.c
libr/util/str_trim.c

Add Pz[ie] command to import/export project in zip format ##projects

---

libr/core/cmd.c
libr/core/cmd_meta.c
test/db/cmd/dwarf2

Add CLLf command as an alias for 'list' and fix @@i ##dwarf

---

libr/bin/dwarf.c
libr/core/cmd_egg.c
libr/core/cmd_help.c
libr/core/cmd_print.c
libr/core/cmd_project.c
libr/core/cmd_seek.c
libr/core/cmd_write.c
libr/include/r_core.h
test/db/cmd/cmd_help
test/db/io/write

Add ?Tj and get rid of all the eprintf("Usage in cmd.egg ##shell

---

libr/arch/p/dis/dis.c
libr/bin/bin.c
libr/bin/format/pe/pe.c
libr/bin/format/wasm/wasm.c
libr/bin/format/xnu/r_cf_dict.c

Fix oom spotted in the wasm bin parser and other stylish things ##crash

---

libr/core/cbin.c
libr/include/r_util/r_name.h
libr/util/name.c

Move these functions out of cbin.c and into a real API where they belong

Move filter_shell and filter_quoted_shell into RName ##refactor ##util

---

libr/bin/p/bin_nso.c

Prevent another OOM in the NSO parser

---

libr/anal/block.c
libr/core/agraph.c
libr/core/anal_objc.c
libr/core/anal_tp.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cfile.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/core/cmd_log.c
libr/core/cmd_search.c
libr/core/cmd_type.c
libr/core/cmd_write.c
libr/core/panels.c

Use RCore.codeCall instead of abusing flag, 'variable'

---

shlr/grub/fs/hfs.c

Fix #21439 - Fix missaligned read in the hfs parser

---

libr/anal/op.c
libr/core/blaze.c
libr/core/cbin.c
libr/io/undo.c

Make aab even faster (39s -> 32s) ##anal

---

libr/bin/mangling/swift-sd.c

Find libswiftCore and libswiftDemangle in linux paths too ##bin

---

libr/bin/p/bin_mach0.c
libr/include/r_bin.h

Apply macho relocs on the swizzled buffer if bin.cache is not set ##bin

---

libr/anal/dwarf_process.c
libr/anal/type.c
libr/asm/arch/pyc/pyc_dis.c
libr/bin/format/dex/dex.c
libr/core/cconfig.c
libr/core/core.c
libr/egg/emit_arm.c
libr/include/r_core.h
libr/include/r_util/r_asn1.h
libr/include/r_util/r_print.h
libr/lang/p/qjs/core.c
libr/util/asn1_str.c
libr/util/axml.c
libr/util/regex/engine.c

The 3 left in the counter are ABI breaks that will be removed in 5.9

Remove all char* casts in free

---

libr/core/cbin.c
libr/core/cmd.c

Arm nopskip

---

.github/workflows/build.yml

Abidiff shouldnt check internal structs like the capstone ones

---

libr/core/cmd.c
libr/core/cmd_meta.c

Fix duplicated source lines in CLLf output ##print

---

libr/esil/esil.c

Avoid >64 bit shift left on 128bit registers ##esil

---

binr/r2r/r2r.c
binr/r2r/run.c
libr/bin/mangling/swift-sd.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_write.c
libr/egg/egg_cfile.c
libr/main/r2pm.c
libr/socket/run.c
libr/util/file.c
libr/util/sandbox.c
libr/util/sys.c

Also uses it in more places where it should be.
Fixes #21440

Return NULL on miss in r_file_path ##util

---

libr/bin/format/mach0/mach0.c
libr/bin/p/bin_mach0.c
libr/include/r_bin.h
libr/main/r2pm.c

Implement qword to better display patched relocs in macho ##bin

---

libr/core/cbin.c
libr/core/cmd_write.c
test/db/io/write

Initial implementation of the io-write-cache command ##io

---

libr/core/disasm.c
test/db/cmd/cmd_pd_str

Dont try to resolve strings on call destinations ##disasm

---

libr/bin/p/bin_mach0.c

Report errors when failing to patch relocs in the internal buffer ##bin

---

libr/util/pj.c
libr/util/sys.c
libr/util/syscmd.c
sys/counters.sh
test/db/cmd/cmd_pa
test/db/cmd/posixshell
test/db/cmd/write-fun
test/db/esil/arm_16
test/db/esil/arm_64
test/db/esil/esil
test/db/io/zip

Unbreak 7 fixed tests

---

Makefile
dist/tarball/Makefile
dist/wapm/r2/wapm.toml
shlr/Makefile
sys/tarball.sh

Move the tarball distribution code into dist/tarball ##ci

---

libr/esil/esil.c
libr/include/r_types_base.h

Move the esil #! r2 command as an op instead of parse ##esil

---

libr/core/cmd.c

Add -V command as an alias for ?V ##shell

---

libr/io/io_cache.c
test/db/cmd/print
test/db/io/cache

Fix memcpy bug in the new cache ##io

---

libr/anal/anal.c
libr/arch/arch.c
libr/core/cmd_anal.c
libr/debug/debug.c
libr/include/r_arch.h
libr/reg/arena.c
libr/reg/profile.c
libr/reg/reg.c

WIP fixes towards better register profile and arch switching handling

---

libr/anal/p/anal_arm_cs.c
libr/core/hack.c
test/db/anal/arm

Expose the value of arm's ADD in op.val ##arch

---

libr/include/r_io.h
libr/io/io_cache.c

We now keep track of which entries of the IO cache are already written, just like in the previous implementation.

Fix list bug in new cache ##io

---

libr/bin/format/elf/elf.c

Minor cleanup in the ELF parser ##bin

---

libr/bin/format/pe/pe.c

radare2 cannot find main function of 64bit PE Arm64. This pull request adds main function detection for fixing this issue.
You can test this feature with the attached PE binaries.
[test.zip](https://github.com/radareorg/radare2/files/11068507/test.zip)

Make main function detection for 64bit PE Arm64 ##bin

---

libr/core/cconfig.c
libr/core/cmd_search.c

Add search.badpage to customize badpage scan ##search

---

libr/core/cmd_write.c
libr/include/r_io.h
libr/io/io_cache.c
test/db/cmd/write

`wcu` and `wcf` command for new cache

Add missing commands for new io cache

---

libr/bin/dwarf.c

Remove global in the DWARF parser ##bin

---

libr/bin/bfile.c
libr/bin/dbginfo.c
libr/bin/dwarf.c
libr/core/cmd_meta.c

* Down loading times from 20 minutes to 20s

Optimize dwarf parser reducing getsection for strp ##bin

---

libr/core/cmd_anal.c
libr/core/project.c
libr/core/zdiff.c

Minor help improvements for afv and less eprintfs

---

libr/anal/sign.c

Fix #21536  - Filter zignature names before validation ##signatures

---

doc/fortunes.fun
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/debug/debug.c
libr/include/r_debug.h
sys/counters.sh
test/unit/legacy_unit/util/threads.c
test/unit/test_str.c

Implement 'aoem' command to show memory refs via emulation ##esil

---

libr/bin/dwarf.c

Implement parsing optimization for dwarf5 ##dwarf

---

libr/bin/format/elf/elf.c

Fix some oobread bugs in the ELF parser ##bin

---

.gitignore

Ignore meson/ninja build artifacts

---

libr/util/str.c

Fix UAF in RStr.replaceIcase() spotted by coverity ##util

---

libr/anal/meta.c
libr/anal/xrefs.c
libr/core/cbin.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
test/db/formats/elf/crash
test/db/formats/pe/imports_tinyW7
test/db/tools/rabin2

Dont list symbols when using `is,:help` ##shell

---

.github/workflows/qemu.yml

Add arm64 builds ##ci

---

libr/core/cbin.c
libr/core/cfile.c
test/db/esil/bfbug

Fixes the bfbug losing arch setup after `o malloc` ##core

---

.github/workflows/build.yml
libr/arch/p/arm_v35.mk
sys/debian.sh

Aim to fix crosscompilation

---

libr/anal/diff.c
libr/bin/bfilter.c
libr/core/cmd_cmp.c
libr/core/gdiff.c
test/db/cmd/cmd_cmp

Initial implementation of the 'cgfa' command ##diff

---

libr/core/linux_heap_glibc.c
libr/util/str.c

Improve code quality of the `dmh` command

---

libr/arch/p/riscv/plugin.c
libr/util/str.c

Dont use strtok in the riscv plugin ##arch

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/p/bin_mach0.c

Refactor macho imports

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/p/bin_mach0.c
test/db/formats/mach0/mach0

Refactor macho libs

---

libr/anal/p/anal_arm_cs.c
test/db/anal/arm
test/db/cmd/types

Fix #21576 - Function stack frame size in case of FP register in a Thumb's PUSH ##analysis

---

libr/bin/bobj.c
libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_mach0.c
libr/bin/p/bin_mach064.c
libr/include/r_vector.h
libr/util/vector.c
test/db/anal/arm
test/db/cmd/display_flag
test/db/formats/mach0/leb128
test/db/formats/mangling/bin

Refactor macho symbols

---

libr/core/visual.c
libr/esil/esil.c
test/db/esil/arm_64

* Add test case for the arm64 q0 register

Implement 128bit regstore esil emulation ##esil

---

libr/esil/esil.c
libr/include/r_types_base.h
test/unit/test_util.c

Rename R_CONST to R_TAG and add unit tests for them ##api

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_xnu_kernelcache.c
libr/include/r_vector.h

Refactor loading of mach0 sections ##bin

---

libr/anal/dwarf_process.c
libr/bin/dwarf.c

Fix non-null-terminated string in dwarf ##crash

---

libr/core/cmd_help.c
libr/util/str.c

Asan version

---

libr/util/str.c
test/db/tools/r2agent
test/db/tools/rabin2
test/db/tools/rafind2
test/db/tools/ragg2
test/db/tools/rarun2
test/db/tools/rasign2
test/db/tools/rasm2
test/db/tools/rax2

Add build optimization and precondition check levels in -v ##shell

---

libr/include/r_util/r_str.h
shlr/java/class.c

Avoid the use of strtok

---

libr/bin/dwarf.c

Fix UAF in the dwarf parser ##crash

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/objc/mach0_classes.c
libr/bin/format/objc/mach0_classes.h
libr/bin/p/bin_mach0.c
libr/include/r_skiplist.h
libr/util/skiplist.c

Refactor mach0 loading of relocs ##bin

---

libr/main/radare2.c

Use RCore.cmdCall() and just replace pointers for -A

---

libr/anal/block.c
libr/anal/hint.c
libr/anal/p/anal_x86_cs.c
libr/anal/var.c
libr/bin/bfile.c
libr/bin/bin.c
libr/core/cmd_anal.c
libr/util/rbtree.c

Branch prediction optimizations (3/3) ##performance

---

libr/anal/p/anal_gb.c
shlr/grub/fs/ext2.c
shlr/grub/fs/hfs.c
shlr/grub/kern/disk.c
shlr/grub/kern/misc.c

Fix infinite loop in the ext2 grub code (DDoS) ##crash

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc

Refactor elf loading of relocs ##bin

---

libr/crypto/hash/sha2.c

Fix unaligned pointer access in sha256 ##crash

---

libr/main/r2pm.c
test/db/tools/r2pm

Restore the flag R2PM_OFFLINE in r2pm to prevent git pull if set.

Restore R2PM_OFFLINE flag in r2pm

---

test/unit/test_str.c

Cover r_str_tok_r function

---

libr/anal/sign.c
libr/arch/p/arc/gnu/arcompact-dis.c
libr/arch/p/x86_nz/nzasm.c
libr/asm/arch/avr/assemble.c
libr/asm/arch/avr/format.c
libr/cons/cons.c
libr/cons/grep.c
libr/core/casm.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_search.c
libr/core/cmd_search_rop.c
libr/core/cmd_write.c
libr/core/cmd_zign.c
libr/core/project.c
libr/core/windows_heap.c
libr/debug/p/debug_gdb.c
libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/windows/windows_message.c
libr/io/p/io_windbg.c
shlr/gdb/src/common.c
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/responses.c
shlr/gdb/src/gdbserver/core.c

Replace strtok by thread-safe r_str_tok_r

---

libr/arch/arch.c
libr/include/r_arch.h

Improve automatch plugin with encoder support ##arch

---

libr/core/cio.c

Minor code quality improvements in core/cio.c

---

libr/anal/anal.c
libr/arch/arch_config.c
libr/arch/p/arm/plugin.c

Honor RArch.setBits via RAnal.setBits ##arch

---

libr/anal/op.c
libr/arch/p/z80/plugin.c
libr/arch/p/z80/z80asm.c

Use plugin name instead of arch name to fallback ##arch

---

libr/arch/p/arm/plugin.c

Rename arch.arm plugin 'arch.arm.nz' ##arch

---

libr/anal/anal.c
libr/anal/p/anal_gb.c
libr/anal/p/anal_x86_cs.c
libr/anal/value.c
libr/anal/var.c
libr/arch/arch.c
libr/arch/arch_session.c
libr/asm/asm.c
libr/bin/bin.c
libr/bin/p/bin_xtr_fatmach0.c

Handle RArch.getRegProfile() from RAnal.setRegProfile ##arch

---

shlr/grub/fs/hfs.c
test/db/cmd/cmd_fs

Add test and fix oobread in the hfs parser ##crash

---

libr/arch/p/arm/armass64.c

Fix shift ub armass

---

dist/docker/Dockerfile
libr/anal/jmptbl.c

Pick minor jmptbl patch reducing memrefs in arch checks

---

libr/anal/block.c
libr/anal/fcn.c
libr/anal/global.c
libr/core/cmd_anal.c
libr/util/rbtree.c

wip fixes coming from the 'recursefails' pr

---

libr/core/cmd_search.c

* A fuzzed bin for testing takes 1s instead of 15s

Faster aap on large empty maps ##search

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc
libr/include/r_vector.h
test/db/anal/x86_64
test/db/formats/elf/crash
test/db/formats/elf/symbols

Refactor / improve loading of ELF symbols + imports

---

libr/bin/format/pe/pe.c
libr/util/asn1.c

Fix oobread bug in asn1/pkcs7 parser ##crash

---

dist/plugins-cfg/plugins.def.cfg
dist/plugins-cfg/plugins.mingw.cfg
dist/plugins-cfg/plugins.termux.cfg
libr/anal/meson.build
libr/anal/p/6502_cs.mk
libr/arch/meson.build
libr/arch/p/6502_cs.mk
libr/arch/p/6502_cs/plugin.c
libr/include/r_anal.h
libr/include/r_arch.h
libr/meson.build

Migrate 6502_cs plugin ##arch

---

libr/cons/cons.c
libr/socket/socket_proc.c
mk/wasi.mk
shlr/bochs/include/libbochs.h
shlr/bochs/src/libbochs.c
shlr/zip/zip/zip_fdopen.c
shlr/zip/zip/zip_source_file_stdio_named.c
sys/wasi.sh

Update to the latest wasi-sdk-20 ##build

---

libr/include/r_endian.h
libr/reg/rvalue.c

* Required for STM8, UNIVAC and others
* https://en.wikipedia.org/wiki/24-bit_computing

Add support for LE/BE 24 bit registers ##reg

---

.github/workflows/ci.yml
libr/meson.build

Fix `meson -Dnogpl=true` compilation ##build

---

libr/esil/esil.c

Fix UB when shifting value too far left ##esil

---

shlr/sdb/Makefile
shlr/sdb/include/sdb/types.h
shlr/sdb/meson.build
shlr/sdb/src/ht.c
shlr/sdb/src/journal.c
shlr/sdb/src/sdb.c

Update SDB to the latest

---

libr/core/cmd.c

Implement the -L command ##shell

---

libr/bin/format/le/le.c

Fix large memory allocations on corrupted LE binaries ##crash

---

libr/core/cmd_debug.c

Warn the user when using dd/dm/di without a child ##debug

---

libr/bin/p/bin_xtac.c

Fix oom bugs in the XTAC parser ##crash

---

libr/core/cmd_search.c

Fix oobread in /v ##crash

---

libr/config/config.c
libr/core/cconfig.c
libr/core/cmd_eval.c

Fix #17194 - Fix 'e scr.pager=..' to set the internal pager ##cons

---

libr/core/cmd_log.c
libr/lang/lang.c

Better LA/Ll listings ##shell

---

libr/core/agraph.c

* Show registers on the top of the screen
* Put register names at left in the basic blocks
* Interactive Graph handles [] keys to resize hex.cols
* Tricks cmd.gprompt and asm.flags.inbytes

Experimental graph debugger layout ##visual

---

libr/arch/p/x86_nz/nzasm.c
libr/bin/mangling/rust.c
test/db/asm/x86_64

Implement 'call [rip+X]' for x86.nz and add tests ##asm

---

dist/plugins-cfg/plugins.def.cfg
dist/plugins-cfg/plugins.mingw.cfg
dist/plugins-cfg/plugins.nocs.cfg
dist/plugins-cfg/plugins.static.cfg
dist/plugins-cfg/plugins.static.nogpl.cfg
libr/anal/meson.build
libr/anal/p/chip8.mk
libr/arch/meson.build
libr/arch/p/chip8.mk
libr/arch/p/chip8/plugin.c
libr/include/r_anal.h
libr/include/r_arch.h
libr/meson.build

Migrate chip8 ##arch

---

libr/io/io_plugin.c

Fix #21705 - check r_io_plugin_add return value and freed unused allocated memory ##io 

---

libr/bin/mangling/cxx/cp-demangle.c
libr/bin/mangling/cxx/cp-demangle.h
libr/bin/mangling/cxx/demangle.h

Fix some -fvisibility=hidden issues ##build

---

libr/arch/p/i4004/regs.h

* Still no way to map the callstack with =SP alias

Add more call level registers for i4004 ##arch

---

libr/core/vmenus.c
libr/include/r_cons.h

Improve interactive config and color editors ##visual

---

libr/io/io_bank.c
libr/io/io_desc.c
libr/io/io_map.c
libr/io/p/io_http.c
libr/io/p/io_isotp.c
libr/io/p/io_malloc.c
libr/io/p/io_null.c
libr/io/p/io_serial.c
libr/io/p/io_socket.c
libr/io/p/io_tcpslurp.c
libr/io/p/io_xalz.c
libr/io/p/io_xattr.c

Fix hypothetical arbitrary code execution vuln in r_io ##io

---

libr/core/cmd_seek.c
libr/util/calc.c
libr/util/str.c

Fix UAF in RNumCalc ##crash

---

libr/arch/p/kvx/plugin.c
libr/arch/p/loongarch/plugin.c
libr/arch/p/m68k_cs/plugin.c
libr/arch/p/riscv/plugin.c
libr/arch/p/xtensa/plugin.c
libr/cons/2048.c
libr/cons/stiv.c

Refactor globals

---

libr/main/r2pm.c

Fix r2pm when launching it from a deleted working directory ##r2pm

---

binr/radare2/radare2.c
test/db/cmd/cmd_pipe

Fix the r2p tool and add a test ##shell

---

libr/arch/p/lua/lua53_parser.c
libr/bin/p/bin_lua.c

Fix UAF read in the LUA bin parser ##crash

---

binr/r2r/r2r.c
libr/util/str.c

Implement r2r -g to run the tests associated with the files changed #tests

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc
test/db/formats/elf/reloc

Add support for more ELF SPARC relocs ##bin

---

libr/lang/p/qjs/loader.c
libr/main/r2pm.c

r2pm search is case insensitive ##shell

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/include/r_vector.h

Store the vector index instead of a weak pointer for the ELF ##crash

---

libr/cons/dietline.c
libr/cons/input.c
libr/core/core.c
libr/include/r_cons.h

* Faster keyboard reading, reducing terminal control calls

Detect too large input strings in RCons.prompt ##cons

---

libr/lang/p/qjs/loader.c

Support relative module resolution in qjs ##lang

---

libr/lang/p/qjs.c
shlr/qjs/js_r2papi.c
shlr/qjs/js_r2papi.qjs
shlr/qjs/js_repl.c
shlr/qjs/js_repl.qjs
shlr/qjs/package.json

Update r2papi.ts 0.1.1 ##lang

---

libr/lang/p/qjs/loader.c

Handle multiple ../ imports ##qjs

---

libr/lang/p/qjs/loader.c

Improve r2js module loading, honoring relatve and absolute paths ##lang

---

libr/core/cmd_info.c

Fix help message for idp? ##shell

---

libr/anal/hint.c
libr/asm/filter.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_print.c

https://infosec.exchange/@radareorg/110408516779107641

Add ahi36 and asm.offset.base36=true ##disasm

---

libr/include/r_core.h

Make all the RCoreCmdStr functions R_MUSTUSE its return ##core

---

binr/rax2/rax2.c
libr/main/rax2.c
man/rax2.1

Implement rax2 -rS and update manpage ##tools

---

libr/core/fortune.c

Fix r2premium fortune prints

---

libr/anal/anal.c
libr/bin/format/mach0/mach0.c
libr/core/cbin.c
test/db/formats/zip
test/db/tools/rabin2

Infer asm.os from platform's LC_BUILD_VERSION ##bin

---

libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/mach0/mach0_specs.h
libr/bin/p/bin_mach0.c
libr/bin/p/bin_mach064.c
libr/core/cbin.c
libr/include/r_bin.h

* Fix https://github.com/radareorg/ideas/issues/104

Add RBinInfo.libinjprot field for mach0 at least ##bin

---

libr/core/agraph.c
libr/core/cmd_anal.c

Set terminal in raw mode before entering visual graph mode ##graph

---

libr/bin/format/elf/elf.c

Refactor more functions in elf loader ##bin

---

libr/bin/format/elf/elf.c
test/db/cmd/cmd_ie

Continue handling symbols after elf symbol with no name ##bin

---

libr/bin/format/mach0/mach0.c

Add remaining changes to mach0 loader ##bin

---

sys/install.sh

Massage sys/install.sh for Haiku-x86

---

libr/io/io_cache.c

Remove meaningless optimization leftover in io.cache ##io

---

libr/bin/format/elf/elf.c

Refactor more elf loader code ##bin

---

libr/core/cmd_debug.c
libr/egg/Makefile
libr/egg/egg.c
libr/egg/egg_lang.c
libr/egg/emit_a64.c
libr/egg/emit_arm64.c
libr/egg/meson.build
libr/include/r_egg.h

* Still far from complete, also fixes a bug not assembling after compiling

Initial support for arm64 eggs ##egg

---

libr/arch/p/pickle/plugin.c

Partially fixes issue #21195 for the pickle architecture. Also cleans up some code.
The pickle arch can have opcodes of unlimited size (newline terminated). So the max size returned from arch info is just a reasonable guess. When an opcode exceeds that guess, it can cause `pd` and `V` to get off track and print at invalid offsets.
The new code checks if any opcode is larger then the max size guess. If so, it updates the guess to the longest encountered opcode.
This won't fix `pd` output until the opcode max size is seen at least once. Below shows pickle assembly with a single byte mistake in `pd`. The instruction at 0x00000114 is longer then the max size guess. Once that instruction is parsed, the max size guess is updated. The second `pd` operates with a correct max size …

Fix max asm len in pickle ##arch

---

libr/main/rabin2.c
libr/main/radare2.c
libr/main/ragg2.c
libr/main/rasm2.c
man/rasm2.1

* This way r2 -NN will tell the childs to not load any plugin
* Update help messages and man pages

Merge all R*2_NOPLUGINS as R2_NOPLUGINS ##shell

---

libr/cons/grep.c
libr/core/cmd.c

Remove two globals from RCons.grep

---

libr/core/fortune.c

Prior to this change, fortune file selection is not not even pseudo-random

Make fortune file selection random

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/bin/p/bin_elf.inc.c

More code cleanup for the ELF parser

---

libr/bin/format/elf/elf.c

Refactor even more parts of elf loader ##bin

---

libr/bin/p/bin_elf.inc.c

Refactor elf bin plugin

---

libr/bin/format/elf/elf.c

Proper != checks for all the ELF RBuf.reads

---

doc/esil.md
libr/core/vmenus.c
libr/esil/esil.c
test/db/esil/cond
test/db/esil/esil

Improvements in the visual esil debugger and documentation

---

libr/anal/hint.c
libr/core/cmd_anal.c

* A proper new API must be added in r2-5.9, lets just workaround for now

Implement ahb-* missing command ##analysis

---

libr/debug/p/debug_gdb.c

Fix #21813 - parsing reg profiles from android-gdbserver ##debug

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc.c

Add support for more elf reloc types

---

.github/workflows/build.yml
libr/arch/p/tricore_cs/plugin.c
libr/include/r_anal/op.h
shlr/java/class.c

* No esil yet, but at least static analysis starts to work

Improve tricore.cs handling jumps/rets/movs/ ##arch

---

shlr/java/class.h

Fix undefined behavior when reading java uints ##shlr

---

libr/bin/p/bin_dyldcache.c

Fix oob write in dyldcache accel loading ##crash

---

libr/bin/format/mach0/mach0.c
libr/core/cbin.c
libr/util/format.c
libr/util/utype.c

Initial codesig

---

libr/bin/format/elf/elf.c
libr/core/cmd_meta.c
libr/search/strings.c

Fix non-null terminated string in string search hits

---

libr/anal/p/anal_x86_cs.c
libr/core/core.c
libr/egg/egg.c
libr/esil/esil.c
libr/esil/esil_trace.c
libr/main/ragg2.c

Fix some memory leaks in REgg and RAnal.x86

---

libr/core/anal_tp.c

Few less unnecessary allocations for the type propagation

---

libr/anal/fcn.c

Consider zero pages as invalid code ##analysis

---

libr/core/cmd_anal.c

Check for noret destinations in afbr listings ##analysis

---

libr/cons/grep.c

Faster ~? rcons filtering ##cons

---

libr/bin/d/macho
libr/bin/format/mach0/mach0.c

Parse more CodeSignature fields for mach0 ##bin

---

libr/anal/cond.c
libr/anal/pin.c
libr/anal/reflines.c
libr/core/cconfig.c

Show log.level=? help message ##shell

---

libr/bin/p/bin_elf.inc.c
libr/core/cmd_anal.c
libr/core/cmd_write.c
libr/include/r_limits.h
libr/include/r_types_base.h

Refactor some more elf code

---

binr/r2r/r2r.c
binr/r2r/run.c
libr/bin/mangling/swift-sd.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_write.c
libr/egg/egg_cfile.c
libr/include/r_util/r_print.h
libr/main/r2pm.c
libr/main/radare2.c
libr/socket/run.c
libr/util/file.c
libr/util/sandbox.c
libr/util/sys.c

* This helps to simplify the caller's code and reduce logic

RFile.path() returns NULL if not found ##util

---

libr/core/cbin.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/visual.c
libr/core/visual_tabs.inc.c
libr/core/vmenus.c
libr/core/yank.c
libr/include/r_core.h
libr/include/r_util/r_str.h
libr/util/str.c
libr/util/x509.c

Remove few apis, commands and config vars marked as deprecated

---

doc/fortunes.fun
libr/anal/fcn.c
libr/anal/jmptbl.c
libr/anal/op.c
libr/anal/p/anal_arm_cs.c
libr/anal/p/anal_gb.c
libr/anal/p/anal_mips_cs.c
libr/anal/p/anal_x86_cs.c
libr/anal/value.c
libr/anal/var.c
libr/arch/arch.c
libr/arch/arch_value.c
libr/arch/p/m68k_cs/plugin.c
libr/arch/p/ppc_cs/plugin.c
libr/arch/p/sparc_cs/plugin.c
libr/core/canal.c
libr/core/cmd_type.c
libr/debug/trace.c
libr/include/r_arch.h

* Faster analysis and fix some leaks and uafs

RAnalValue no longer refs an RRegItem ##analysis

---

libr/anal/fcn.c

Fix UAF in RRegItem.name

---

libr/core/cconfig.c

Enable anal.strings by default ##analysis

---

libr/include/r_lang.h
libr/lang/lang.c
libr/lang/p/go.c
libr/lang/p/nim.c
libr/lang/p/qjs.c
libr/lang/p/tsc.c
libr/lang/p/vala.c

RLangPluginInit now returns bool ##lang

---

libr/main/r2pm.c

Deprecate the wordish arguments in r2pm ##r2pm

---

libr/bin/dbginfo.c
libr/bin/p/bin_dbginfo_dex.c
libr/bin/p/bin_dbginfo_elf.c
libr/bin/p/bin_dbginfo_p9.c
libr/core/canal.c
libr/core/cmd_debug.c
libr/core/cmd_meta.c
libr/core/disasm.c
libr/include/r_bin.h

The addr2line function, now also returns the column ##bin

---

libr/core/canal.c
libr/util/asn1_str.c

Remove unnecessary cast in free()

---

libr/cons/2048.c
libr/cons/cons.c
libr/cons/hud.c
libr/cons/input.c
libr/cons/more.c
libr/include/r_cons.h

Removes some globals from cons (input.c).

Rm globals ##cons

---

libr/io/p/io_treebuf.c

Fix bug in io_treebuf plugin ##io

---

libr/anal/fcn.c

Fix UAF spotted by asan

---

libr/core/cmd_meta.c

Fix uaf in the elf parser when marking strings

---

libr/anal/xrefs.c

Do not accept invalid xrefs (-1 <-> -1) ##analysis

---

libr/core/cconfig.c

anal.gp also sets the reg value ##analysis

---

binr/r2r/r2r.c
test/db/io/cache

Accept .c files as argument to r2r ##tests

---

libr/anal/jmptbl.c
libr/anal/var.c
libr/core/cconfig.c
libr/include/r_reg.h
libr/reg/profile.c
libr/reg/reg.c
libr/reg/rvalue.c

Optimize anal.roregs ##analysis

---

libr/bin/bin.c
libr/bin/bobj.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_mach0.c
libr/include/r_bin.h

Make RBinSymbol.clone() API public ##bin

---

libr/cons/cons.c
libr/core/core.c
libr/core/disasm.c
libr/core/visual.c
libr/include/r_cons.h

R2_590: Cons mark

---

libr/core/cmd.c
libr/core/cmd_meta.c
libr/include/r_core.h

Add the new RCore.cmdCallAt() and cmdfAt() APIS ##core

---

libr/core/canal.c
libr/core/cmd_anal.c
libr/core/esil2c.c
libr/esil/esil.c
libr/include/r_esil.h

Rename REsil.address -> .addr for consistency ##abi

---

libr/reg/reg.c

Optimize: reg 32 <-> 64 conversion iterates over gpr only ##analysis

---

libr/include/r_util/r_str.h

Fix build with latest musl+fortify

---

libr/core/cmd_write.c
libr/include/r_io.h
libr/io/io_cache.c

Add wc--* command to purge all cache layers ##io

---

libr/anal/op.c
libr/arch/p/6502/6502dis.inc.c
libr/arch/p/6502/plugin.c
libr/core/cmd_anal.c
libr/util/log.c

Get rid of two recent ASAN bugs in 6502 and op

---

libr/anal/anal.c

Faster RAnal.bbTrace() ##analysis

---

libr/core/cconfig.c
libr/include/r_io.h
libr/io/io.c
libr/io/io_bank.c

Add io.overlay config var

---

libr/core/canal.c
libr/include/r_io.h
libr/io/io.c
libr/io/io_bank.c

Introduce RIORegion as an alternative to r_io_is_valid_offset

---

libr/bin/p/bin_lua.c

Use the right #ifdef in bin.lua to avoid dup symbols

---

libr/util/utf8.c

* Fix an assert on release builds, lazy to debug

Lighter precondition checks for acp/utf8 on windows

---

libr/bin/d/Makefile

Reverts radareorg/radare2#21935

Revert "Fix to symlink of DLL which causes link loop"

---

libr/core/disasm.c

Fix crash in emu.ssa reproducible even when disabled ##crash

---

sys/build.sh

Use realpath to force absolute path in sys/install.sh prefix ##build

---

libr/main/r2pm.c
libr/util/sys.c

Set library path for r2 prefix and r2pm prefix in r2pm -r ##r2pm

---

libr/core/libs.c
libr/include/r_lib.h
libr/util/lib.c

Speedup plugin loading and startup times ##core

---

libr/include/r_util/r_graph.h
libr/util/graph.c

This is supposed to compute a dominance tree from a given RGraph and RGraphNode (root).
I took inspiration from https://www.cs.princeton.edu/courses/archive/fall03/cs528/handouts/a%20fast%20algorithm%20for%20finding.pdf, though I'm not sure if i understood it correctly, because I fucking HATE mathematical notation.
I also found this paper https://users-cs.au.dk/gerth/advising/thesis/henrik-knakkegaard-christensen.pdf
Review is appreciated, but please don't waste any time with cosmetic issues (coding style, unchecked allocations, etc.).
I can run the indent.sh script later.

Add r_graph_dom_tree ##util

---

libr/include/r_util/r_graph.h
libr/util/graph.c

Cosmetic patch ##util

---

libr/main/rasm2.c

When as is newed, I add the judgment to check if it is empty, if it is empty, return directly

[fix]Null Pointer reference

---

Makefile

A fix to esil.7 man page in /usr/local/share/man/man7

Fix link to esil.7 man page

---

libr/core/disasm.c

Improved unaligned cases in the listings ##disasm

---

libr/core/canal.c
test/db/esil/arm_64

Fix some missing xrefs in /re $$ ##analysis

---

libr/anal/op.c

Fix recently introduced oobread asan crash

---

libr/arch/p/arm/plugin_cs.c

Add more function preludes for arm32 ##analysis

---

libr/include/r_util/r_log.h
libr/util/log.c

Fix #21970 - Null checks in the R_LOG api ##crash

---

libr/include/r_vec.h
libr/lang/p/qjs.c
test/unit/test_vec.c

Add vec find + find_index, refactor qjs code

---

libr/anal/data.c
libr/anal/fcn.c
libr/anal/xrefs.c
libr/arch/p/arm/plugin_cs.c
libr/bin/format/mach0/mach0.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/include/r_anal.h

* Harden the reftype mask checks

Fix invalid xref types when combining code|data ##analysis

---

libr/arch/p/java/plugin.c

[op] is null dereferenced here

fix: null pointer dereference

---

libr/anal/data.c
libr/anal/fcn.c
libr/anal/xrefs.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/include/r_anal.h
test/db/anal/arm
test/db/anal/x86_64

More partial fixes

---

libr/core/cmd_write.c
libr/core/hack.c
libr/include/r_core.h
test/db/cmd/write

* wao+, writes an opcode and seeks after that
* useful usecase to write 3 nops at main: '3wao+nop@main'

Implement 'wao+' command and remove RCore.hackHelp() ##write

---

binr/r2r/r2r.c

Fix return code when running r2r against .c files ##tests

---

libr/bin/format/mach0/mach0.c
libr/bin/p/bin_dyldcache.c

Now it's faster and we don't loose local symbols along the road 😅

Move dyldcache symbols to symbols_vec ##bin

---

libr/debug/dmap.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c

Dont dupe map file and name if not necessary ##debug

---

libr/anal/jmptbl.c

fix memory leak
Signed-off-by: [wanhui@uniontech.com](mailto:wanhui@uniontech.com)

fix memory leak

---

libr/bin/p/bin_smd.c
test/db/formats/smd

m68k is 32 bit
while at it, fix typo: Peripherials -> Peripherals

m68k is 32 bit ##bin

---

libr/core/cmd_anal.inc.c

Fix #22344 - Fix invalid json in `ax.j` command ##shell

---

libr/core/cmd.c

Faster RCoreCall via RCoreCmd ##core

---

shlr/qjs/js_r2papi.c
shlr/qjs/js_r2papi.qjs
shlr/qjs/package.json

Update r2papi-0.2.6 for r2ai integration fixes

---

doc/gprobe.md
libr/io/p/io_gprobe.c
sys/hex2rapatch.py

Gprobe updates

---

libr/core/canal.c
libr/core/cmd_search.inc.c
test/db/anal/arm64-search

Fix /rc, document argument handling and add test ##analysis

---

libr/core/cmd_anal.inc.c
libr/core/core.c

Honor cfg.json in axt and other a subcommands ##json

---

libr/core/cmd_search.inc.c
test/db/cmd/regexp

This adds the ability to output regular expression search in JSON format which was missing.

Add JSON output to /e

---

libr/core/cmd_anal.inc.c
libr/core/cmd_seek.inc.c
libr/core/disasm.c
libr/include/r_core.h

* This relates to asm.offset.relto

Add sd command to show the delta seek relative to different bases ##core

---

libr/lang/p/tsc.c
shlr/qjs/Makefile
shlr/qjs/js_r2papi.c
shlr/qjs/js_r2papi.qjs
shlr/qjs/package.json

Support latest reestructured r2papi.ts (0.3.1)

---

libr/core/canal.c
libr/core/cmd_search.inc.c

aap /rc and others use R_LOG_DEBUG now to be less noisy for batch runs

---

libr/core/canal.c

Permit partial block reads on analsearch loops ##analysis

---

libr/bin/bfile.c
libr/bin/p/bin_fs.c
libr/core/cfile.c

* Do not try to guess the bintype on address 0 when using frida://

Faster frida://0 startup times ##io

---

libr/anal/fcn.c
libr/core/cmd_anal.inc.c
libr/include/r_anal.h

Remove the unused RAnal.fcnDelLocs()

---

libr/bin/dbginfo.c
libr/core/disasm.c
libr/include/r_bin.h

Deprecate addrline2, it's only used internally

---

libr/core/core.c
test/scripts/palette.r2

Fix gui.alt_background remains

---

libr/core/cmd_print.inc.c

pdua now takes a math arg, not just a number ##shell

---

libr/core/cconfig.c
libr/core/cmd_anal.inc.c
libr/core/cmd_debug.inc.c
libr/core/cmd_search.inc.c
libr/debug/plugin.c
libr/include/r_core.h

Debug plugin fallbacks ##debug

---

libr/core/cmd_anal.inc.c

A bit verboser esil step

---

libr/bin/p/bin_xnu_kernelcache.c

* Works the same was as R_DYLDCACHE_FILTER
* Load less symbols, it's faster and eats less memory

Handle R_KERNELCACHE_FILTER env in RBin.kernelCache ##bin

---

libr/core/cmd_anal.inc.c

Fix bitsize when listing regs via ar= ##debug

---

libr/core/cconfig.c
libr/core/visual.c

Add cmd.vprompt2 to run a command after the visual prompt ##visual

---

libr/core/cbin.c

Minor bin.demangle=false optimization

---

libr/core/cfile.c

Microscopic refactoring

---

shlr/sdb/include/sdb/cwisstable.h

Update sdb to get one less c99 requirement

---

libr/io/io_desc.c

Adjust map boundaries on RIODesc resize ##io

---

libr/debug/debug.c
libr/debug/p/debug_esil.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/magic/apprentice.c

Fix 'attach to pid 1' error regression in the linux debugger

---

libr/core/cmd_open.inc.c
test/db/anal/x86_32

Show closed interval map boundaries on 'om,' command

---

libr/core/cmd_open.inc.c
libr/include/r_io.h
libr/io/io_desc.c

or and omt command

---

libr/core/cfile.c
libr/main/radare2.c

Add missing map covering all the addresspace for frida://

---

libr/core/cmd_debug.inc.c

Better error output for the `dr` command

---

libr/core/cmd.c
libr/core/core.c

0x command also saves seek history ##shell

---

libr/core/cfile.c
libr/debug/dreg.c
libr/debug/p/native/xnu/xnu_debug.c
libr/debug/p/native/xnu/xnu_excthreads.c

Minor cleanups in debug

---

libr/core/cmd_anal.inc.c
libr/core/cmd_print.inc.c

Add afn* command ##shell

---

libr/anal/xrefs.c
libr/core/cmd_anal.inc.c
libr/include/r_anal.h

Initial support for xref sizes ##analysis

---

binr/blob/Makefile
binr/radare2/Makefile
binr/rahash2/Makefile
binr/rasm2/Makefile
binr/rules.mk

Fix static linking on macOS ##build

---

libr/bin/bin.c
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dex.c
libr/core/cbin.c
libr/core/cmd_anal.inc.c
libr/core/cmd_info.inc.c
libr/core/vmenus.c
libr/include/r_bin.h
libr/main/radiff2.c
shlr/java/class.c
test/db/cmd/cmd_i
test/db/cmd/cmd_tc

Refactor to use RBinName for RBinField(s) ##bin

---

libr/bin/format/objc/mach0_classes.c
libr/core/cbin.c
libr/include/r_bin.h

Fix recently introduced assert and ub related to RBinName

---

libr/cons/cpipe.c
libr/core/cmd.c

Fix `?*>` dumping to screen ##shell

---

libr/core/cmd_anal.inc.c

Implement afla and afba commands to list offsets for analysis purposes ##analysis

---

sys/hex2rapatch.py

Somehow the shebang in hex2rapatch.py was incomplete.

Fix hex2rapatch.py

---

libr/core/cmd_anal.inc.c

* Experimental for now, but should be good to move it earlier

Run .afna@@c:afla in aaaaa ##analysis

---

libr/bin/bfile.c
libr/bin/bin.c
libr/bin/bobj.c
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_dyldcache.c
libr/core/cbin.c
libr/core/cmd_info.inc.c
libr/core/cmd_meta.inc.c
libr/core/cmd_print.inc.c
libr/core/vmenus.c
libr/include/r_bin.h
libr/main/radiff2.c
shlr/java/class.c

WIP: Use RBinName for RBinClass too ##bin

---

libr/core/cmd_debug.inc.c

Currently, whenever `dc` or its derivatives is invoked, radare2 will listen to `dbg.follow` and set the offset accordingly.
But this is not needed when, for instance, followed by `?`.
In that case, seeking would be undesirable as it also affects the `?*` command, throwing people's offset every time recursive help is requested.

Fix dc derivatives causing unintended seek towards PC ##shell

---

shlr/java/class.c

Handle null class name properly in a fuzzed java file

---

libr/core/cmd_open.inc.c
libr/include/r_io.h
libr/io/io.c
libr/io/io_desc.c
libr/io/io_map.c
test/db/cmd/write

Improve map tying support ##io

---

libr/bin/format/objc/mach0_classes.c

Fix OOBwrite introduced last week in the mach0 class parsing logic

---

libr/bin/dwarf.c
test/db/formats/xcoff64

Fixes https://github.com/radareorg/radare2/issues/21466

Support DWARF section names for XCOFF64 ##bin

---

libr/bin/format/coff/coff.c
libr/bin/format/coff/coff.h
libr/bin/format/coff/coff_specs.h
libr/bin/p/bin_coff.c
test/db/formats/xcoff

Basic XCOFF32 section handling ##bin

---

libr/core/cmd_print.inc.c

Add support for wide pascal strings ##shell

---

libr/bin/format/coff/coff.c
libr/bin/format/coff/coff.h
libr/bin/format/coff/coff_specs.h
libr/bin/p/bin_coff.c
test/db/formats/xcoff

Support XCOFF entrypoint and imports via loader ##bin

---

libr/arch/p/riscv/plugin.c
libr/arch/p/riscv/riscv.c
libr/arch/p/riscv/riscvasm.c
libr/core/hack.c

Add support for compressed nops in riscv ##arch

---

libr/core/pseudo.c

Fix inter basic block `goto loc` in pdc ##print

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_ic

Move 'ic?' help into a separate listing ##shell

---

libr/io/io_bank.c
libr/io/p/io_malloc.c
libr/io/p/io_null.c

preserve resize on reopen

---

libr/core/cbin.c
libr/core/cmd_info.inc.c
test/db/cmd/cmd_i
test/db/cmd/cmd_ie
test/db/formats/dwarf

Refactor `ie` outside the subcommand loop ##shell

---

libr/io/io.c

Fix r_io_v2p ##io

---

libr/bin/format/elf/elf.c

Not much, but it should make it slightly more readable.

Slight code improvements for ELF bin plugin (elf.c) ##refactor

---

libr/include/r_util/r_assert.h
libr/util/str.c

Make clear that r_return* is a macro! ##refactor

---

configure
configure.acr
meson.build

AIX configure support ##port

---

libr/arch/p/any_as/plugin.c
libr/bin/mangling/microsoft.c
libr/socket/socket_serial.c

- mangling/microsoft: Fix dollar in identifier ##port
- Portability fixes ##port
Fixes #22476

more aix fixes

---

libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_mach0.c
libr/core/cbin.c
libr/core/cmd_info.inc.c

WIP: keeping mangling namings

---

libr/core/cmd_log.inc.c
libr/core/visual.c
libr/core/vmenus.c
libr/include/r_core.h

Text log shift

---

libr/crypto/p/crypto_rc2.c

fix the Memory leak: obuf
Signed-off-by: zengwei zengwei1@uniontech.com

fix the Memory leak: obuf

---

libr/anal/anal.c

Modify memory allocation failure conditions
Signed-off-by: zengwei zengwei1@uniontech.com

Modify memory allocation failure conditions

---

libr/include/r_util/r_mem.h
libr/include/r_util/r_str.h
libr/main/rax2.c
libr/util/mem.c
libr/util/str.c
test/unit/test_str.c

Rename the binstr apis and fix units

---

test/unit/test_r2pipe.c

Fix some local running of unit tests by skipping plugins

---

libr/include/r_util/r_mem.h
libr/main/rax2.c
libr/util/mem.c
test/unit/test_str.c

Fix ub and rename the binstring apis again

---

libr/asm/asm.c
libr/reg/rvalue.c

Implement 24bit regwrite support ##reg

---

test/db/formats/coff

Some more tests for the COFF bigobj binary

---

sys/install.sh

Honor --prefix in /sys/install.sh ##build

---

libr/core/libs.c

Use the core api to run home scripts and handle more extensions ##lang

---

binr/r2r/load.c
test/db/cmd/cmd_zignature

Implement the NORUN directive for r2r ##tests

---

libr/bin/bfile.c
libr/bin/bfilter.c
libr/bin/format/le/le.c
libr/bin/format/pe/pe.c
libr/bin/p/bin_pe.inc.c

Fix latest asan regressions

---

libr/core/cbin.c
test/db/formats/dwarf

Handle ^C when loading/filtering symbols just in case ##bin

---

libr/anal/sign.c
libr/arch/p/pickle/plugin.c
libr/core/cmd_zign.inc.c
libr/core/dmh_glibc.inc.c
libr/include/r_util/r_num.h
libr/util/unum.c

Renaming r_num_get_float to r_num_get_double

---

libr/bin/format/mach0/mach0.c
libr/include/r_util/r_file.h
libr/util/file.c
libr/util/str.c
libr/util/sys.c

Implement RFile.newf() ##api

---

libr/core/libs.c
libr/util/lib.c

Load script plugins from system directories, and cleanup logic

---

libr/include/r_vec.h

Fix dangling pointer use in the rvec implementation

---

libr/anal/block.c
libr/core/canal.c
libr/core/cmd_anal.inc.c
libr/core/cmd_search.inc.c
libr/core/disasm.c
libr/include/r_anal.h

Fix op_pos oobread crash in ollvm'd binary ##crash

---

libr/core/cmd_api.c
libr/core/cmd_cmp.inc.c

Implement the ciE command to compare exports between two objects ##bin

---

libr/core/cmd_help.inc.c

Add help for the single quote command prefix

---

shlr/Makefile
shlr/meson.build

Bump the capstone5 commit hash, just minor fixes

---

libr/bin/bin.c

Use strbuf_newf instead of new+setf

---

libr/debug/p/native/darwin.c
libr/debug/p/native/xnu/reg/darwin-arm64.h

* Many arm64 instructions use the tmp register

Add the tricky 'tmp' register in the arm64 debugger protilfe

---

libr/bin/dwarf.c

The `init_die` and `parse_die` function implemented in [dwarf.c](https://github.com/radareorg/radare2/blob/master/libr/bin/dwarf.c) is quite similiar to those in the [rizin](https://github.com/rizinorg/rizin). Thus, it's very likely that Heap-based OOB write in [CVE-2021-43814](https://nvd.nist.gov/vuln/detail/CVE-2021-43814) also affects [radare2](https://github.com/radareorg/radare2).
Here is the [patch](https://github.com/rizinorg/rizin/commit/aa6917772d2f32e5a7daab25a46c72df0b5ea406?diff=split&w=1) for [CVE-2021-43814](https://nvd.nist.gov/vuln/detail/CVE-2021-43814) is provided.
Similar to [rizin](https://github.com/rizinorg/rizin), there is a heap-based out of bounds write in parse_die when reversing an amd64 elf binary with dwarf debug info, respectively.
Try to fix it based on the …

Fix oob write for dwarf with abbrev with count 0

---

libr/core/disasm.c
test/db/cmd/cmd_disassembly
test/db/cmd/cmd_pd3

Asm.nbytes

---

env.sh
mk/darwin.mk

Maybe comparing empty string with -gt

---

libr/include/r_th.h
libr/util/thread_lock.c
shlr/sdb/include/sdb/cwisstable.h

Fixes for macppc support

---

libr/include/r_util/r_str.h
libr/util/Makefile
libr/util/meson.build
libr/util/rprintf.c
test/unit/meson.build
test/unit/test_printf.c

Initial implementation of our custom r_str_printf api

---

libr/util/bscanf.c
test/unit/test_scanf.c

Add tests and fix %c in r_str_scanf

---

libr/main/rax2.c
test/db/tools/rax2

Fix rax2 -l behaviour ##tools

---

libr/core/cmd_anal.inc.c

afbt -> afb, ##shell

---

dist/plugins-cfg/plugins.def.cfg
libr/debug/meson.build
libr/debug/p/debug_evm.c
libr/debug/p/evm.mk
libr/include/r_debug.h

Import the debug.evm plugin from radare2-extras ##debug

---

libr/bin/dwarf.c
libr/include/r_bin_dwarf.h

Do not use a custom boolean for dwarf

---

libr/core/cmd_print.inc.c

* Kudos to @astralia for kindly reporting the bug

Fix error and add missing help for `r2 -qc '?*~abcd' --` ##shell

---

test/db/cmd/types2

Handle ULL in enums

---

libr/core/cbin.c

Show error when user applies relocs on urified ios ##io

---

libr/anal/c/libtcc.c
libr/anal/c/libtcc.h
libr/anal/c/tcc.h
libr/anal/c/tccgen.c
libr/anal/c/tccpp.c

Minor cleanups on the tcc code

---

libr/anal/c/tcc.h
libr/anal/c/tccgen.c
libr/anal/c/tccpp.c

More tcc cleanups

---

libr/anal/c/tcc.h
libr/core/cmd.c
libr/core/cmd_eval.inc.c
libr/core/cmd_help.inc.c

Implement support for json and r2 output for %env ##shell

---

libr/asm/asm.c
libr/core/cmd_egg.inc.c
libr/core/core.c
libr/egg/egg.c

Fix (null) in gS output

---

libr/main/r2pm.c
libr/util/getopt.c

Fix #22594 - Handle long flags in r_getopt as an alias for help ##shell

---

libr/asm/asm.c
libr/core/core.c
libr/debug/debug.c
libr/debug/snap.c
libr/include/r_asm.h
libr/include/r_egg.h
libr/main/ragg2.c

* debug's eggs must share the same asm instance

Fix #22563 - fix 'cannot assemble' in dmp, using egg shellcodes ##debug

---

libr/core/cmd_debug.inc.c

Improve argument parsing for the dmp command ##debug

---

libr/core/cmd_debug.inc.c
libr/core/cmd_open.inc.c
libr/core/cmd_search.inc.c
libr/debug/p/debug_io.c
libr/io/p/io_mach.c
libr/main/rabin2.c
libr/util/str.c
test/unit/test_str.c

Improve RStr.rwx permission string parsing ##util

---

libr/core/cmd_anal.inc.c

Improve help message for `afl,?` ##shell

---

libr/cons/canvas.c
libr/include/r_cons.h

Add missing r_cons_canvas_goto_write ##cons

---

libr/core/agraph.c
libr/core/cmd_mount.inc.c
libr/include/r_agraph.h
libr/include/r_core.h

Five less globals from agraph

---

libr/core/cmd_debug.inc.c
libr/core/cmd_print.inc.c
libr/util/time.c

Implement the sub-beats computation in RTime.beats() ##util

---

libr/include/r_socket.h
libr/socket/socket_rap_client.c

Closes https://github.com/radareorg/radare2/issues/22269
Breaks ABI.
------

Fix RAP seek over 2GiB

---

libr/bin/format/pe/pe.c
libr/core/cmd_debug.inc.c
libr/core/cmd_log.inc.c
libr/core/cmd_print.inc.c
libr/include/r_util/r_print.h
libr/include/r_util/r_time.h
libr/main/r2pm.c
libr/util/time.c

WIP: Refactoring/cleanup of the RTime API

---

libr/bin/format/elf/elf.c

Fix negative realloc in the ELF parser ##crash

---

libr/debug/p/debug_native.c
libr/debug/p/native/maps/darwin.c
libr/debug/p/native/xnu/xnu_debug.c
libr/debug/p/native/xnu/xnu_debug.h
libr/debug/p/native/xnu/xnu_excthreads.c
libr/debug/p/native/xnu/xnu_threads.c
libr/debug/p/native/xnu/xnu_threads.h
libr/include/r_types.h
libr/include/r_util/r_sys.h
libr/io/p/io_mach.c
test/db/archos/darwin-arm_64/dbg

* https://newosxbook.com/src.jl?tree=xnu&file=/tests/ptrauth_failure.c
* https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/doc/pac.md
* https://opensource.apple.com/source/xnu/xnu-7195.50.7.100.1/tests/thread_set_state_arm64_cpsr.c
* https://github.com/apple/darwin-xnu/blob/main/osfmk/arm64/status.c
* https://github.com/llvm-mirror/lldb/blob/master/tools/debugserver/source/MacOSX/arm64/DNBArchImplARM64.cpp
* https://github.com/frida/frida-gum/blob/main/gum/backend-darwin/gumprocess-darwin.c#L1441

WIP: Fix thread_set_state on arm64e ##debug

---

doc/macos.md

Update documentation for macOS/arm64e ##doc

---

libr/arch/p/pyc/opcode.c
libr/arch/p/pyc/pyc_dis.c
libr/arch/p/pyc/pyc_dis.h
libr/bin/format/pyc/marshal.c
libr/core/cconfig.c

Fix null derefs in pyc, exposing type confussion bugs

---

libr/core/casm.c
libr/core/cmd_print.inc.c
libr/core/disasm.c
libr/util/print.c

Minor cleanup in cmd_print

---

libr/cons/cons.c
libr/core/cconfig.c
libr/include/r_cons.h

Add scr.timeout covering the ^C blocks ##shell

---

libr/core/cbin.c
test/db/formats/dwarf
test/db/formats/rel

Improve uricheck to avoid bin.relocs.apply mess things up

---

libr/core/cmd.c

Handle quoted pipes ##shell

---

libr/core/cmd.c
libr/core/cmd_macro.inc.c

Bring back the multiline macro support ##shell

---

dist/plugins-cfg/plugins.def.cfg
libr/bin/meson.build
libr/bin/p/bin_io.c
libr/bin/p/io.mk
libr/core/cmd_open.inc.c
libr/include/r_bin.h
libr/include/r_io.h
libr/main/radare2.c

[WIP] Initial import of the RBin.io plugin ##bin

---

.github/workflows/build.yml
sys/android-ndk-install.sh
sys/debian.sh

Update GitHub Actions `build.xml` file.
Details separated in each commit.

Update build CICD

---

libr/core/panels.c

This fixes some problems with sidepanels, now instead of hoping that `PANEL_CONFIG_SIDEPANEL_W` space is available, the code goes over the panels to check how much can be offered. I also did some minor refactoring in related functions.

Fix #22640 - improve sidepanels in limited space ##visual

---

libr/anal/p/anal_a2f.c
libr/include/r_bind.h

Aim to fix a c++ build problem

---

libr/main/radare2.c

Include R2_RCFILE in r2 -H output

---

libr/main/rax2.c
libr/util/sys.c

Use an enum instead of hardcoded shifted values in main.rax2

---

libr/include/r_util/r_file.h
libr/main/rax2.c
libr/util/file.c
libr/util/strbuf.c

Add the new r_stdin_readline API and use it from rax2

---

libr/util/base36.c

Fix warning on msvc

---

libr/lang/p/qjs.c
libr/socket/r2pipe.c
test/db/cmd/cmd_js

Implement r2pipe on the r2js lang plugin ##lang

---

libr/core/panels.c
libr/crypto/p/crypto_aes_cbc.c
libr/crypto/p/crypto_base91.c
libr/crypto/p/crypto_blowfish.c
libr/crypto/p/crypto_rc2.c
libr/crypto/p/crypto_rc4.c
libr/crypto/p/crypto_rol.c
libr/crypto/p/crypto_ror.c
libr/crypto/p/crypto_serpent.c
libr/crypto/p/crypto_xor.c
man/r2pm.1
man/rahash2.1
test/db/tools/rahash2

Add missing authors for the crypto plugins, update manpage ##hash

---

libr/io/io_map.c
libr/io/p/io_treebuf.c

Fix potential double free in io_map_overlay and io_treebuf ##io

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc.c
test/db/formats/elf/elf-relarm
test/db/formats/elf/reloc

Better logging when handling unsupported arm64 elf relocs ##bin

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc.c

Elfobj imports

---

libr/core/disasm.c

Fix oobread on the inline metadata used in disasm ##crash

---

libr/debug/p/debug_native.c
libr/fs/p/fs_posix.c
libr/include/r_fs.h

Expose ownership and permissions to the posix filesystem ##fs

---

libr/bin/format/le/le.c
libr/bin/p/bin_le.c
test/db/formats/le

In LE files extracted from DOS extenders, patching relocs is always needed to resolve references.

Patch relocs in LE ##bin

---

libr/io/io_map.c

Add realloc check

---

libr/core/cmd_search.inc.c
libr/main/rafind2.c
man/rafind2.1

Update rafind2 manpage ##doc

---

man/esil.7

Update ESIL manpage ##doc

---

libr/cons/less.c
libr/core/cmd_mount.inc.c
libr/core/cmd_zign.inc.c
libr/main/rasign2.c
man/r2pm.1
man/rasign2.1

Man rasign2

---

libr/crypto/crypto.c
libr/crypto/hash/hash.c
libr/crypto/hash/state.c
libr/crypto/p/crypto_entropy.c
libr/crypto/p/crypto_punycode.c
libr/include/r_crypto.h
libr/include/r_hash.h
test/db/tools/rahash2

WIP: RCrypto/RHash refactorings

---

libr/cons/cons.c
libr/debug/plugin.c

Do not do more work if the first check fails

---

libr/core/cmd_anal.inc.c
libr/io/p/io_dsc.c

Fix CID#1540326 - string not null terminated

---

libr/core/cmd_print.inc.c
libr/esil/Makefile
libr/esil/esil_toc.c
libr/esil/meson.build
libr/include/r_esil.h

Move esil2c from core to libr.esil ##esil

---

libr/bin/format/elf/elf.c
test/db/cmd/cmd_ie
test/db/formats/elf/reloc-arm64

Arm64 1026 relocs

---

libr/cons/canvas.c
man/radiff2.1

Update the radiff2 manpage

---

README.md

Replace dead link in readme, and correct information that was copied from r2ai

Update README for clarity regarding sarif plugin

---

libr/lang/p/tsc.c

* Unless the R2_TSR2JS env var is set to 1

To use r2pipe-ts we depend on nodejs, so ts scripts need node now

---

libr/magic/d/default/microsoft

Add magic number for the codeview debug info

---

USAGE.md
dist/plugins-cfg/plugins.def.cfg
libr/crypto/crypto.c
libr/crypto/p/crypto_entropy.c
libr/crypto/p/crypto_ror.c
libr/crypto/p/crypto_rot.c
libr/crypto/p/crypto_strhash.c
libr/crypto/p/strhash.mk
libr/include/r_crypto.h
libr/main/rahash2.c
test/db/tools/rahash2

Few more cleanups for rahash2 and add the strhash crypto plugin

---

libr/core/cmd_meta.inc.c
libr/crypto/p/crypto_xor.c

Add base64 for CC (not only CCu) ##shell

---

test/db/extras/cmd/yara

Add test for https://github.com/radareorg/r2yara/pull/11

Add test for yara version

---

doc/zsh/_rax2
libr/main/rax2.c
man/rax2.1
test/db/tools/rax2

- https://github.com/radareorg/radare2/issues/22698
- [ * ] Mark this if you consider it ready to merge
- [ * ] I've added tests (optional)

Implement rax2 -j flag for json output format

---

libr/core/cmd_help.inc.c
libr/core/cmd_print.inc.c
libr/include/r_util/r_print.h
libr/util/pie.c

Add colors and improve the pie chart rendering a bit ##print

---

binr/Makefile

Fix r2 symlink because lldb won't resolve them more than once

---

libr/util/str.c

Fix #22750 - char is now unsigned on android

---

libr/bin/format/coff/coff.c
libr/bin/p/bin_coff.c
libr/util/buf.c

Early check for multiplication overflow in the COFF parser ##crash

---

libr/core/cmd_anal.inc.c
libr/esil/Makefile
libr/esil/esil_compiler.c
libr/esil/meson.build
libr/include/r_esil.h
test/db/esil/compiler

WIP: esil compiler

---

libr/bin/p/bin_elf.inc.c

Fix 'reloc conversion failed' on some ELFs ##bin

---

dist/plugins-cfg/plugins.def.cfg
libr/esil/esil.c
libr/esil/p/esil_dummy.c
libr/esil/p/esil_forth.c
libr/esil/p/esil_null.c
libr/esil/p/forth.mk
libr/include/r_esil.h
test/db/cmd/cmd_aes

Implement OVER operation for ESIL, to make it forth compliant ##esil

---

libr/bin/format/coff/coff.c

If symtable fails dont use it

---

libr/core/cio.c
libr/core/cmd_write.inc.c
test/db/io/write

Fix #22648 - Improve error messages when writing to io

---

libr/core/cio.c
libr/util/buf_bytes.c
libr/util/mem.c

Fix #22767 - Some UB when malloc(0) in RBuffer api ##crash

---

shlr/lz4/deps.mk

Remove lz4 leftover

---

shlr/capstone-patches/v5/fix-tricore.patch

Add patch for capstone-v5 to fix build for gcc-4.0

---

libr/core/disasm.c
test/db/cmd/cmd_pd

Fix #22576 - Add esil object in pdJ with detailed info ##disasm

---

libr/core/cio.c

Fix the last cov, a null deref in cio.c

---

libr/bin/format/pcap/pcap.c

These are issues that were flagged by coverity or the clang static analyzer.

Some code quality improvements in pcap.c

---

libr/arch/p/bpf/plugin.c
libr/arch/p/ebc/ebc_disas.c
libr/arch/p/pic/pic_pic18.c

Fix endian bugs ##port

---

libr/main/r2pm.c
libr/util/file.c

Fix all memleaks spotted by valgrind --leak-check=full in r2pm

---

libr/anal/pin.c
libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/disasm.c
test/db/cmd/cmd_aes

Soft esil pins

---

libr/core/cconfig.c
libr/core/disasm.c
test/db/cmd/cmd_pd3

asm.bytes.ascii

---

libr/core/cbin.c

reduce annoyance

---

libr/cons/dietline.c
libr/cons/input.c

Fix arrows

---

libr/core/cbin.c
test/db/cmd/cmd_iz
test/db/formats/dwarf

Show utf8-blocks details as a separate column in strings listing ##bin

---

.github/workflows/build.yml

Bring back the abidiff ci check

---

libr/core/cmd_info.inc.c

Refactor iE outside the i loop

---

libr/asm/acode.c
libr/cons/dietline.c
libr/core/vasm.c

Support live hexpairs input in the visual assembler ##visual

---

libr/core/cmd_info.inc.c

Refactor iZ and iO outside the loop

---

libr/socket/socket.c

Dont warn when resizing the terminal in the webserver

---

libr/core/cmd.c
libr/core/visual.c

Fix VA Visual Assembler in debug mode when io.va is false ##visual

---

libr/io/p/io_ptrace.c
libr/util/bscanf.c

Fix oobreads on fmt of RStr.scanf ##crash

---

libr/anal/cond.c
libr/arch/arch_value.c

Fix memory leak in RAnalCond.value

---

libr/core/panels.c

Fixing some coverity issues in libr/core/panels.c

---

libr/core/cmd.c

Register command calls in the history logs ##shell

---

libr/core/cmd_macro.inc.c
test/db/cmd/cmd_macros

Fix command macro parsing and calling and add another test ##shell

---

libr/core/cmd.c
libr/core/cmd_project.inc.c
libr/core/project.c
test/db/cmd/projects

Return code

---

libr/core/core.c
libr/core/disasm.c

Handle 32 and 64 bit big endian data references (Vdrr1) ##disasm

---

libr/include/r_parse.h
libr/lang/p/qjs.c
libr/lang/p/qjs/parse.c

Initial support for RParse r2js plugins ##lang

---

libr/main/rax2.c

Replace RaxActions enum by struct

---

libr/core/cmd_write.inc.c

Add `wcd` command for patch diffing instruction and sort `wc?` lines ##diff

---

libr/arch/arch_config.c
libr/include/r_types.h
libr/reg/profile.c
libr/reg/reg.c
test/unit/test_reg.c

Endian regs

---

libr/include/r_util/r_buf.h
libr/util/buf.c
libr/util/buf_cache.c
test/unit/test_buf.c

Initial implementation of RBuffer.cache ##abi

---

libr/util/str.c

Show 'newabi' in r2 -v ##shell

---

libr/core/cbin.c
test/db/formats/dwarf

Fix some memory leak issues in libr/core/cbin.c flagged by coverity

---

libr/esil/esil.c

Big endian fix for ESIL pokes ##endian

---

libr/arch/p/arm/armass.c
test/db/asm/arm_32

This PR includes:
* Fix for the case of register-operand shifts such as: "add r0, r1, r2, lsl 2"
* Support for writeback on indexed memory addressing such as: "ldr r0, [r1, r2]!"
* Fix for mvn (It was broken)

A bunch of improvements for ARM ##asm

---

libr/bin/bfile.c
libr/bin/bfilter.c
libr/bin/bin_write.c
libr/bin/blang.c
libr/bin/dwarf.c
libr/bin/format/dex/dex.c
libr/bin/format/objc/mach0_classes.c
libr/bin/mangling/cxx.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_java.c
libr/core/dmh_glibc.inc.c
libr/include/r_bin.h
libr/main/radiff2.c
libr/util/bscanf.c

Use RVec to store the RBinClasses instead of RList ##newabi

---

libr/anal/sign.c
libr/core/cmd_zign.inc.c
libr/main/rasign2.c
test/db/cmd/cmd_zignature

Implement 'z[j*] <addr>'  to show only 1 zignature ##zignatures

---

libr/bin/dwarf.c

Use ' instead of "" in dwarf commands

---

libr/core/cconfig.c
libr/core/cmd_search.inc.c

Make search.verbose=false ##search

---

libr/lang/lang.c
libr/lang/p/dart.c
libr/lang/t/test.dart
scripts/parseplug.r2.js

Initial support for Dart in rlang via system ##lang

---

binr/r2r/run.c

I realized that I left a few things out in my previous PR (#22851).
This should provide a better solution.

Fix concurrency issue (improves 71f57c6c) ##test

---

libr/bin/format/coff/coff.c
libr/util/buf.c

Fix oobread and oobwrite caused by an intovf in coff ##crash

---

libr/core/cconfig.c
libr/core/cmd_anal.inc.c
libr/core/cmd_write.inc.c
libr/util/debruijn.c
test/db/tools/ragg2

Fix big endian debruijn tests and cleanup the implementation

---

libr/util/print.c

Fix pxw on big endian

---

libr/anal/data.c
libr/anal/xrefs.c
libr/core/canal.c

Catch invalid references earlier ##analysis

---

libr/core/canal.c

Suggest -B when finding invalid icod refs ##analysis

---

libr/core/canal.c

Remove one global from the the esil emulation loop ##globals

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/xtensa/plugin.c

Provide proper archinfo details for xtensa ##arch

---

libr/core/cmd_anal.inc.c

Honor maxopsz and minopsz in aae, speeding up emulation a little ##analysis

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc.c
libr/include/r_anal.h

Fix #22804 - Implement a couple of relocs for ppc64 ##bin

---

libr/core/cmd_print.inc.c

Minor improvement with the prc help

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.inc.c
libr/core/cbin.c
test/db/formats/dwarf

* Improves arm/thumb analysis and xrefs

Autodetect thumb main on arm16 elf binaries ##bin

---

libr/anal/op.c
libr/arch/p/ppc_cs/plugin.c
libr/util/print.c

Add nor in the RAnalOp.toString() ##arch

---

libr/core/cmd_print.inc.c
libr/core/visual.c
libr/util/str.c

* Kudos to @phurd@infosec.exchange for the idea
* https://infosec.exchange/@phurd/112284269719833207
https://infosec.exchange/@pancake/112355240246542707

Nibble colordump under prcn/prcb. Idea by Patrick Hurd ##print

---

binr/rules.mk

Fix sys/static.sh

---

libr/core/cmd_print.inc.c

Use proper color palette for prcn/prcb ##print

---

libr/bin/format/elf/elf.c
libr/core/disasm.c

Separate the arm vs arm64 reloc import logic ##bin

---

shlr/Makefile
shlr/meson.build
test/db/cmd/cmd_zignature

Update the capstone/v5 to the latest commit from git

---

libr/bin/dbginfo.c
libr/bin/dwarf.c
libr/bin/p/bin_dbginfo_elf.c
libr/core/cmd.c
libr/include/r_bin_dwarf.h
test/db/formats/zip

Remove apple-ism related to d67f69da66421fd5caa39c93c1ff78ae57c51868

---

libr/arch/p/ppc/gnu/ppc-dis.c
libr/arch/p/stm8/gmtdisas/asm.c
libr/arch/p/stm8/gmtdisas/ins.inc.c
libr/arch/p/stm8/plugin.c
libr/bin/p/bin_cgc.c
libr/bin/p/bin_dbginfo_elf.c
libr/bin/p/bin_elf.c
libr/bin/p/bin_elf64.c

Fix warning

---

libr/arch/p/xtensa/plugin.c
libr/esil/esil.c

Do not use $$ in the xtensa esil, add =SN in the reg profile ##arch

---

libr/core/cmd_anal.inc.c
libr/core/disasm.c

Consider that software interrupt sometimes branch ##analysis

---

libr/arch/p/xtensa/plugin.c

Dont use $$ in xtensa ##esil

---

libr/anal/sign.c
libr/core/cmd_zign.inc.c

Fix #22894 - Add z, to print zignatures in table format ##zignatures

---

libr/core/cconfig.c
libr/main/rasm2.c

Remove the RCconfig(arch.arch) option ##core

---

shlr/Makefile
shlr/meson.build

Update to the latest capstone-v5

---

libr/arch/p/mips/plugin_cs.c

Fix invalid instructions on mips not recognized as invalid ##analysis

---

libr/core/cmd_search.inc.c

Improve /?* and /ad/? helps with 20 more lines ##help

---

libr/arch/p/dalvik/plugin.c
libr/core/cmd_anal.inc.c
libr/core/cmd_info.inc.c
libr/core/disasm.c
libr/core/panels.c
test/db/perf/dex

Fix i subcommand help messages ##shell

---

doc/fortunes.fun

Sorry I didn't realize this automatically starts CI :(

Unfortune compiler

---

sys/build.sh
sys/install.sh

Honor NOSUDO in sys/install.sh ##build

---

libr/cons/pal.c
test/Makefile
test/unit/test_egg.c

Tweak environment to build and run tests on custom paths

---

libr/core/cmd_info.inc.c

iX -> idx, also refactor some i? lines on subcommand helps ##shell

---

test/db/extras/asm/vc4

Update test for VC4 plugin in extras with instruction from https://github.com/hermanhermitage/videocoreiv/tree/master/blinker01.

Update VC4 test

---

libr/include/r_util/r_bitmap.h

Fix pfb and RBitmap in big endian ##print

---

libr/anal/flirt.c

Big endian fix for FLIRT ##endian

---

libr/arch/p/avr/assemble.c

Big endian AVR encode fix ##endian

---

doc/fortunes.fun

Add some fun fortunes from GLaDOS//portal ##fun

---

libr/arch/p/riscv/plugin.c

Big endian RISC-V dis fix ##endian

---

libr/anal/c/tccgen.c
libr/bin/format/elf/elf.c

Fix reading segment count for ELF ##endian

---

libr/anal/c/tccgen.c
libr/arch/p/sparc_cs/plugin.c

Fix sparc disassembler for big endian hosts ##endian

---

libr/core/cmd_info.inc.c

Remove the goto in the i command parser, make isarray a boolean

---

libr/bin/format/mach0/mach0.c
test/db/formats/zip

Improved stripped mach0 detection logic ##bin

---

libr/bin/mangling/swift-sd.c
test/db/tools/rabin2

Implement conformsToProtocol mangling logic for Swift ##bin

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h
libr/core/cmd_anal.inc.c
libr/core/cmd_search.inc.c
libr/syscall/syscall.c
test/db/cmd/cmd_i
test/db/formats/elf/android

Improve osabi detection for android ##bin

---

libr/bin/mangling/swift-sd.c
test/db/formats/mangling/swift
test/db/tools/rabin2

Handle another double string case for the lowerdash swift mangling ##bin

---

libr/arch/p/x86/plugin_cs.c

Show errors when read callback is not available for arch

---

.github/workflows/ci.yml

Aim to fix the asan crash on Ubuntu22 in the ci

---

sys/sanitize.sh

Set safety cflags for the fuzz job

---

libr/core/casm.c
libr/core/cmd_search.inc.c
test/db/cmd/cmd_search_asm

/ad supports glob matching now ##search

---

libr/main/rax2.c
man/rax2.1

Add rax2 -q to be quiet when printing hexdumps ##tools

---

libr/core/cmd.c
libr/core/cmd_print.inc.c

Add r2pm hint for r2ai if the package is not installed ##shell

---

libr/bin/mangling/objc.c

Minor optimizations in the ObjC demangler ##bin

---

libr/bin/bin.c
libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/format/objc/mach0_classes.c
libr/bin/format/objc/mach0_classes.h
libr/bin/p/bin_dyldcache.c

More cleanups on the objc parser, with minor optimizations ##bin

---

libr/bin/format/mach0/mach0.c

Reduce memory dereferences in the macho parser and more cleanups

---

libr/core/cmd.c
libr/util/json_parser.c

Initial implementation of r2pipe2 ##shell

---

libr/util/log.c

Honor log callback return value on custom callback calls ##core

---

libr/core/corelog.c
libr/util/log.c

Each RLogCallback have its own user pointer ##crash

---

libr/core/cmd.c
libr/lang/p/qjs.c
test/db/cmd/r2pipe2

Add r2pipe2 tests

---

libr/main/radare2.c
test/db/cmd/bug_arch

Fix arch selection when loading no files `--` with r2 -a -- ##tools

---

libr/core/core.c
libr/util/thread_chan.c
libr/util/thread_lock.c

Fix #22972 - deadlock in :: fixed by handling ^C ##crash

---

libr/core/cmd_log.inc.c
libr/io/io_plugin.c

Show io and core plugin version in the json listing ##core

---

libr/core/casm.c

Fix #22974 - minimum blocksize to reduce missing matches in /ad ##search

---

libr/include/r_search.h
libr/search/strings.c

Fix stack overflow in strings search ##crash

---

libr/arch/p/x86/plugin_cs.c

Missing read callbacks are now debug messages ##arch

---

libr/main/rasm2.c
test/db/tools/rasm2

Honor <PC> kernel crash hints in hexpairs for rasm2 -D ##disasm

---

libr/core/cmd_info.inc.c

Initial refactoring of the ic command and fix two recent memleaks

---

libr/core/cmd_anal.inc.c

Add help for aax and aaF causing a?* to be slow ##shell

---

libr/core/pseudo.c

Display instruction addresses on each switch blocks in pdco ##disasm

---

libr/core/canal.c

Remove non-id code from the gml graph output ##graph

---

libr/core/cmd_anal.inc.c

Fix bb outputs computation in afij ##analysis

---

libr/core/canal.c
test/db/cmd/cmd_afl

Dont list vars in afij output ##analysis

---

libr/core/core.c
libr/io/p/io_rap.c
libr/socket/socket_rap_client.c

Dont seek from the server side rap ##io

---

libr/core/disasm.c
test/unit/Makefile

Unshadow 'nl' argument in ds_comment calls

---

libr/search/strings.c

Show offset of the truncated large strings ##search

---

libr/egg/egg_cfile.c

Fix ragg2 foo.c on macOS ##ragg

---

libr/core/cmd_anal.inc.c

Only use anal hints in aac on arm 16/32 ##analysis

---

libr/core/cmd_seek.inc.c

Better help and invalid subcommand handling for s ##shell

---

libr/core/cmd.c

Better handling the v subcommands ##shell

---

libr/core/cmd_info.inc.c

iSm is no longer a valid command as it was doing nothing ##shell

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_i
test/db/cmd/cmd_ih
test/db/formats/mach0/coresymbolication
test/db/formats/mach0/mach0
test/db/formats/qnx

Remove ihh and iHH, no need for confusing swappable aliases ##shell

---

libr/lang/p/qjs/loader.c

Fix loading some r2frida-compiled scripts ##qjs

---

libr/core/dmh_glibc.inc.c
test/db/archos/linux-x86_64/dbg_dmht

Fix infinite loops in the heap parser and fix 2 broken tests ##debug

---

libr/core/cmd_search.inc.c

Fix ^C in /ac ##search

---

libr/core/pseudo.c
test/db/cmd/cmd_pdc

Remove empty lines and onelinify the comments in pdc ##decompiler

---

libr/core/cmd_anal.inc.c

Implement missing but documented abi and refactor ab/ap ##analysis

---

libr/core/disasm.c
libr/core/visual.c
libr/include/r_core.h

Implement soft scrolling over varlisting in visual disasm ##visual

---

libr/core/cmd_print.inc.c

Honor cfg.json.num in pdbj ##disasm

---

libr/core/cmd_flag.inc.c

Implement the new fD command to filter/mangle flagnames ##shell

---

libr/core/cmd_cmp.inc.c
libr/socket/socket_http.c

Fixes for the RSocket.httpPost() API, still not working well ##socket

---

libr/core/visual.c

Do you like this change? vote with your thumb pls ^^

Always show function signature in visual disassembly ##visual

---

libr/bin/dbginfo.c
libr/core/cconfig.c
libr/include/r_bin.h

Add dir.sourcebase newabi + faster bin.dbginfo on macOS ##bin

---

libr/core/cmd_help.inc.c
test/db/cmd/r2pipe2

add missing command to r2 `?`

---

libr/cons/hud.c
libr/core/panels.c

Visual panels

---

libr/anal/block.c
libr/anal/function.c
libr/core/pseudo.c
libr/util/list.c

Fix a recently introduced uaf in pdc ##crash

---

libr/core/cmd.c
libr/core/cmd_api.c
test/db/cmd/cmd_pipe

Fix appending redirection on internal alias files ##shell

---

libr/main/r2pm.c

Do not check for updates when r2pm -r, -h and -H ##r2pm

---

libr/cons/grep.c

Highlight code modifier ~:)) ##cons

---

libr/debug/debug.c
libr/debug/plugin.c
test/db/archos/linux-x86_64/dbg_dL

Better output for dL command ##debug

---

libr/core/cmd.c
libr/core/cmd_help.inc.c
libr/core/core.c
libr/lang/p/qjs.c
shlr/qjs/Makefile
shlr/qjs/js_r2papi.c
shlr/qjs/js_r2papi.qjs
shlr/qjs/package.json
sys/rebuild.sh

Update r2papi from git, use src from /tmp instead of npm ##r2js

---

libr/core/cmd_debug.inc.c

Fix drr - register periscoping on arm-thumb ##debug

---

libr/arch/p/arm/plugin_cs.c

Expose missing cpus list in the ARM plugin ##arch

---

libr/core/disasm.c
test/db/anal/x86_32
test/db/anal/x86_64
test/db/cmd/cmd_pd
test/db/cmd/cmd_pd2
test/db/esil/apple
test/db/formats/elf/riscv

Store operations also deserve a place for asm.emu ##disasm

---

libr/core/cconfig.c
libr/core/cmd_anal.inc.c
test/db/anal/arm-esil
test/db/cmd/r2pipe2

Esil regression

---

libr/util/file.c

Fix #23093 - RStdin.slurp() on Windows ##windows

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_i
test/db/formats/pe/tls_noEP

Kill ieee fix obasterisk

---

libr/core/cmd_anal.inc.c

Fix afv help to make it accessible through tghe af?* ##help

---

libr/core/cmd_anal.inc.c
test/db/anal/arm64-search

Show jmptbl bb cases in `ab` output (not just for abj) ##analysis

---

libr/anal/dwarf_process.c
libr/anal/flirt.c
libr/include/r_anal.h
libr/include/r_util/r_assert.h

Fix memory leak in the dwarf parser and more uppercase macros

---

libr/include/r_util.h
libr/include/r_util/r_base32.h
libr/meson.build
libr/util/Makefile
libr/util/base32.c
libr/util/meson.build

Implement r_base32 APIs for my future self ##api

---

libr/core/vmenus.c

Better error handling in vvs ##visual

---

libr/bin/bfilter.c
libr/bin/bobj.c

* This situation should be catched earlier
* But it's easier to debug this way and loads faster

Early stop on corrupted macho method storage ##bin

---

libr/io/p/io_dsc.c

- `:iP` is now human readable instead of JSON
- `:iPj` returns the JSON representation
- `:iP?` shows the help
- `:?` shows the help of dsc io commands

Improve :iP command usability in dsc ##io

---

libr/bin/format/objc/mach0_classes.c
libr/bin/mangling/swift-sd.c
libr/core/cconfig.c
test/db/archos/darwin-x86_64/swift

Run the native swift demangler tests on darwin-x64 too ##bin

---

dist/plugins-cfg/plugins.def.cfg
libr/arch/p/uxn.mk
libr/arch/p/uxn/plugin.c
libr/arch/p/uxn/uxndisass.inc.c
libr/include/r_arch.h

Initial support for the UXN machine ##arch

---

DEVELOPERS.md
libr/include/r_anal.h

Add info about single module recompilation ##doc

---

libr/bin/bfile.c
libr/util/utf8.c
test/db/cmd/cmd_iz
test/unit/Makefile

unrelated fixes from strings foo

---

libr/arch/p/uxn/uxndisass.inc.c
libr/bin/bobj.c
libr/bin/format/objc/mach0_classes.c
libr/io/p/io_dsc.c

Fix last memleaks spotted by coverity

---

libr/bin/bfile.c
libr/util/utf8.c

More fixes from the noheapstring pr

---

shlr/sdb/include/sdb/cwisstable.h

Fix cwisstable on ppc-le ##build

---

libr/core/cmd_zign.inc.c

Add support for parsing next zignatures ##zinatures

---

libr/anal/fcn.c

A bit better experimental nopskip ##analysis

---

libr/core/cmd.c
libr/core/core.c

Improve the multiline comment user experience ##shell

---

libr/core/visual.c

Improved space key behaviour for the hexdump ##visual

---

libr/main/radare2.c

Fix null deref in `r2 -d l` ##crash

---

libr/core/visual.c

Fix shift-tab and space behaviour in visual mode ##visual

---

libr/bin/mangling/swift-sd.c
test/db/cmd/classes
test/db/formats/mach0/objc
test/db/formats/mach0/swift
test/db/formats/mangling/swift

Swift demonger

---

libr/core/cmd_anal.inc.c
libr/core/cmd_help.inc.c
libr/core/visual_riu.inc.c

Initial implementation of ?iu for the onelinered custon UI ##visual

---

libr/core/cmd_search.inc.c

Diplay the `/h` help when invoked with `/h?`

Display /h help

---

libr/core/cmd.c
libr/core/cmd_help.inc.c

Support '0x, not just '@0x and improve "'?'" help ##shell

---

libr/anal/c/libtcc.c
libr/anal/c/tcc.h
libr/anal/c/tccgen.c
libr/anal/c/tccpp.c
libr/anal/c/tcctok.h
libr/anal/cparse.c

Cleanup 300 lines from the libtcc

---

libr/bin/format/dmp/dmp64.c
libr/bin/format/mdmp/mdmp.c
libr/bin/format/mdmp/mdmp_pe.c
libr/bin/p/bin_dmp64.c
libr/bin/p/bin_mdmp.c

Fix parsing dmp binaries on big endian systems ##bin

---

libr/core/cmd_info.inc.c

Fix #23064 - Implemented iclc command ##bin
