radareorg/radare2

.travis.yml

This should hpefully enable builds on container-based infrastructure, which are faster than builds on the old infrastructure. (see http://docs.travis-ci.com/user/workers/container-based-infrastructure/)
The most important part was the recently enabled possibility to install packages without `sudo` via the [APT addon](http://docs.travis-ci.com/user/apt/). Sudo isn't allowed on container-based infrastructure.

Use APT addon on Travis

---

libr/asm/arch/m68k/m68k_disasm/m68k_disasm.c
libr/asm/arch/m68k/m68k_disasm/m68k_disasm.h

I also moved them from the header to the source file, because they are referring to functions that only exist in the source file's compilation unit.
If all goes well this will remove 10 issues at once.

m68k_disasm: replace macro by inline function to please coverity

---

libr/anal/p/anal_v810.c
libr/asm/arch/v810/v810_disas.c
libr/asm/arch/v810/v810_disas.h

* Add system register names
* Fix xor and remove unused instructions
The regression tests need to be updated.

V810: fixes

---

libr/core/cmd.c

Remove bogus 'n' from the end of yp command help
Remove duplicate 'from' in yfa's help

Fix typos in help strings in libr/core/cmd.c

---

libr/debug/p/native/w32.c

mingw64 build fails because of an complation error:
```
make[4]: Entering directory '/var/samba/workspace/radare2/source/libr/debug'
x86_64-w64-mingw32-gcc -c   -MD -D__WINDOWS__=1  -MD -D__WINDOWS__=1    -g -Wall -D__WINDOWS__=1 -DCORELIB -Ip/libbfwbf/include -I/var/samba/workspace/radare2/source/libr/../shlr/gdb/include/ -Ip/librapwrap/include -I/var/samba/workspace/radare2/source/libr/../shlr/wind/ -I/var/samba/workspace/radare2/source/libr/include -DGIT_TAP=\"0.9.9-922-gedd6c18\" -o p/debug_native.o p/debug_native.c
In file included from p/debug_native.c:35:0:
p/native/w32.c:102:13: warning: ‘DebugBreakProcess’ redeclared without dllimport attribute: previous dllimport ignored [-Wattributes]
BOOL WINAPI DebugBreakProcess(
^
p/native/w32.c:172:26: warning: type defaults to ‘int’ in …
```

Fixed type issue in mingw64 build.

---

libr/anal/p/anal_mips_cs.c

+ it was because mips.operands has length 8

fixing coverity defect CID 1341049

---

libr/anal/var.c
libr/core/cmd_anal.c
libr/core/disasm.c

standard ABI of fastcall
param0 ->ecx
param1 ->edx
then on the stack
inorder for pdf to see arguments set by afA
fcn->call should be fastcall
or simply
afC fascall will do the same but from r2 shell

FIX #4204: Implement  fastcall function arguments

---

shlr/qnx/src/core.c

This fixes QNX debugger segfault on Mac OS X (due to MacOS doesn't allow `src` and `dst` of `strncpy` to overlap)

qnx debugger: fix segfault on macos

---

libr/include/r_socket.h
libr/socket/socket.c

1) `r_socket_read()`: was broken on mingw32, a zero length was returned if `ret != len`
2) `r_socket_close()`: fixed closing of socket on mingw32, incl. waiting for last outgoing data to be sent to the wire. This also makes the HTTP server stable (before the fix the connection was sometimes randomly closed before the web browser received all content from the server, leading to ERR_CONNECTION_RESET error in Chrome).

fix r_socket_read, don't lose sent data on r_socket_close (mingw32)

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c

This PR adds new ops to ESIL VM: `~`, `~=`, `~=[]`.
Implements X86 opcode `NOT`: http://x86.renejeschke.de/html/file_module_x86_id_218.html
`// rasm2 still doesn't know how to assemble NOT though`

add bitwise complement ops to ESIL; add NOT opcode to X86

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c

This PR reverts #4728 and uses existing ESIL xor op instead

don't add op to esil vm, use xor

---

libr/anal/p/anal_x86_cs.c

This PR adds x86 `NEG` opcode support for ESIL, see #4724 
http://x86.renejeschke.de/html/file_module_x86_id_216.html

x86 esil: add NEG opcode

---

libr/anal/p/anal_x86_cs.c

esil output for `xchg dword [rdi], ecx` now is `rdi,[4],rcx,^,rcx,=,rcx,rdi,[4],^,rdi,=[4],rdi,[4],rcx,^,rcx,=`.

fix XCHG output while memory access

---

libr/anal/p/anal_x86_cs.c

POP and POPF (though not implemented properly yet) did same as POPAL and POPAW.
Also I feel the need to update 
https://github.com/P4N74/radare2/blob/0c21b433f0f81e520f604de9b0a51c9128708dbc/libr/anal/p/anal_x86_cs.c#L1691-L1699 and have it handled at:
```
case X86_INS_POPAW:
case X86_INS_POPAL:
op->type = R_ANAL_OP_TYPE_POP;
op->stackop = R_ANAL_STACK_INC;
op->stackptr = -regsz * 8;
break;
```
But I am not sure if this would be required or not. Also are any other changes required?

fix POP and POPF

---

binr/ragg2/ragg2-cc

Cross compiling 32 bit on a 64 bit Linux system fails since ragg2-cc doesn't include the "-m32" flag. This change should also help support cross compiling 64 bit on 32 bit systems by adding the "-m64" flag.

Add "-m32" and "-m64" flags for cross compilation with ragg2-cc

---

libr/core/cmd_anal.c
libr/core/cmd_cmp.c
libr/core/cmd_debug.c
libr/core/cmd_egg.c
libr/core/cmd_eval.c
libr/core/cmd_flag.c
libr/core/cmd_hash.c
libr/core/cmd_help.c
libr/core/cmd_info.c
libr/core/cmd_log.c
libr/core/cmd_macro.c
libr/core/cmd_magic.c
libr/core/cmd_meta.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/cmd_project.c
libr/core/cmd_quit.c
libr/core/cmd_search.c
libr/core/cmd_section.c
libr/core/cmd_seek.c
libr/core/cmd_type.c
libr/core/cmd_write.c
libr/core/cmd_zign.c

refactor the includes so that automated tools such as youcompleteme will work with the r2 codebase.
all of the crossreference tools rely on the includes, so this will make them work much better.

Include refactor

---

libr/anal/esil.c

Make sure that the destination register is not reported as "read" in an ESIL eq operation.

Fixes #4726

---

libr/cons/pal.c
libr/core/anal.c
libr/core/config.c
libr/include/r_cons.h

Colours current node in Graphviz output (`ag` command) 'lightblue'.
Add `graph.gv.current` option to config with default to `false`

Colour current graphviz nodes

---

libr/anal/fcn.c
libr/core/disasm.c

test case
```
r2 - 
wx 83ec108b44241899f77c241c8b44241401d08944240c8b44242099f77c24288b44240c01d0894424088b5424148b44240c8d0c028b44242c99f7f98b44240801d0894424048b54240c8b44240801c28b44240401d083c410c38d4c240483e4f0ff71fc5589e55183ec046a076a066a056a046a036a026a01e883ffffff83c41c83ec08506844850408e847feffff83c410b8000000008b4dfcc98d61fcc36690669066909055575653e887feffff81c3371b000083ec0c8b6c24208db30cffffffe8d3fdffff8d8308ffffff29c6c1fe0285f6742531ff8db60000000083ec04ff74242cff74242c55ff94bb08ffffff83c70183c41039f775e383c40c5b5e5f
aa
afCa
pdf
```
this should output all esp args detected and autorenamed named

adding support for esp register in afCa afCa 

---

libr/anal/fcn.c
libr/parse/p/parse_x86_pseudo.c

```
r2 - 
wx 83ec108b44241899f77c241c8b44241401d08944240c8b44242099f77c24288b44240c01d0894424088b5424148b44240c8d0c028b44242c99f7f98b44240801d0894424048b54240c8b44240801c28b44240401d083c410c38d4c240483e4f0ff71fc5589e55183ec046a076a066a056a046a036a026a01e883ffffff83c41c83ec08506844850408e847feffff83c410b8000000008b4dfcc98d61fcc36690669066909055575653e887feffff81c3371b000083ec0c8b6c24208db30cffffffe8d3fdffff8d8308ffffff29c6c1fe0285f6742531ff8db60000000083ec04ff74242cff74242c55ff94bb08ffffff83c70183c41039f775e383c40c5b5e5f
aa
afCa
pdf
```
now it catches all the arguments/vars and rename them or at least should ( ͡° ͜ʖ ͡°)

adding support for handling sp registers at parsing

---

libr/asm/p/asm_x86_nz.c

Fixes issue #4745
The opcode for the dest was set incorrectly, missing the `<<3`
$ rasm2 -a x86.nz -b 32 "mov esi, [esi + 8]"
8b7608
Added a test case for this to radare2-regressions as a separate PR. radare/radare2-regressions#380

Fix incorrect assembly for x86 mov

---

libr/anal/esil.c
libr/include/r_anal.h
libr/include/r_util.h
libr/util/num.c

Adds mul, div, add, sub and eq variants.
Signed-off-by: Damien Zammit <damien@zamaudio.com>

ESIL: add floating point instructions

---

libr/asm/p/asm_x86_nz.c

`nz` assembler now handles dword size offsets aswell as negative offsets. 
Tests added to regression tests with PR radare/radare2-regressions#388

Add support for dword offsets

---

libr/core/config.c

And provide the defaults (if value not set) as examples. Should make descriptions a bit clearer.
Fixes #4758

Make graphviz config options clearer

---

libr/cons/cons.c
libr/core/core.c
libr/core/disasm.c
libr/core/visual.c
libr/include/r_cons.h
libr/include/r_core.h
libr/include/r_print.h
libr/util/print.c

It fixes #4754.
Main things to notice:
* screen_bounds was moved from RCore to RPrint because otherwise it wasn't accessible from r_print_hexdump
* I added RConsBind to r_cons.h so that `r_cons_get_size` and `r_cons_get_cursor` would be accessible from print.c without having circular dependencies at compilation time.
* I added a new api, r_print_set_screenbounds.

util/print: use `screen_bounds` to store the first non visible address

---

libr/io/p/io_mach.c

If r2 is unsigned the message the user gets when trying to debug with it isn't clear as to what the problem is. Add a line to suggest most likely issue and go see the docs to get a cert.

Expand on error message for unsigned OSX binary

---

binr/rahash2/rahash2.c
libr/core/cmd_write.c
libr/crypto/crypto.c
libr/hash/hash.c
libr/include/r_crypto.h
libr/include/r_hash.h
man/rahash2.1

fix https://github.com/radare/radare2/issues/4838.
The PR is somewhat incomplete. Not sure what the sizes at https://github.com/radare/radare2/blob/master/libr/include/r_hash.h#L63-L80 doing. I will update the PR after fixing it.

list all encoders/decoders supported by woE/woD and rahash2 -E/-D

---

libr/util/sys.c

Using functions like `malloc()` in async signal handlers is unsafe, and may result in deadlocks.
Turns out that `backtrace()` is not safe either because its initialization code uses `dlopen()` and `malloc()` and others, but this can be workarounded by calling it once outside of a signal handler.

libr/util/sys.c: Avoid malloc() calls in the signal handler

---

libr/anal/p/anal_mips_cs.c

+ fixed "sub" operands order
+ fixed "add" typo (was implemented using "-" instead of "+")

MIPS esil small fixes, this will unbreak esil/mips regressions

---

libr/anal/p/anal_x86_cs.c

x86 analysis plugin doesn't recognize relative RIP-based calls (whereas it does for jumps). This pull request adds support for this.

Compute RIP-relative calls

---

libr/core/io.c

When using the debugger I'd like to set the prompt to something nice. However, I'm not a fan of "dbg.status"... Instead, stop setting the prompt if it's already set...

Don't override a user's cmd.prompt setting

---

libr/parse/p/parse_mips_pseudo.c

Trivial fix for move instruction being wrongly shown for MIPS pseudo:
Before:
|           0x004005cc      21f0a003       sp,fp,=
:e asm.pseudo=true
|           0x004005cc      21f0a003       fp = 2
After:
|           0x004005cc      21f0a003       fp = sp

Fix MIPS pseudo code for move op.

---

libr/parse/p/parse_mips_pseudo.c

Before:
|           0x004005ec      0000beaf       sw fp, (sp)
e asm.pseudo=true
|           0x004005ec      0000beaf       [sp + ] = fp
After:
|           0x004005ec      0000beaf       [sp + 0] = fp
Will add a test case shortly.

fix pseudo output for MIPS sw ... (xx)

---

libr/anal/p/anal_mips_cs.c
libr/parse/p/parse_mips_pseudo.c

The recently committed changes for auto-detecting arguments and variables are great and I'm looking forward to this being completed.
I wanted to try and get this working for MIPS as well as x86 and ARM so here is a small set of changes which adds support for local variables at least. I had to change the ESIL output to match what the new fill_args()/extract_arg() functions are expecting (use hex and reverse the order of the + arguments) and then add a varsub hook to the MIPS pseudo plugin.
anal/fcn.c: fill_args() is a good start but I don't think it is generic enough to support all architectures. Is it possible to add the facility for this variable/argument detection to be overridden on a per-plugin basis? Something like RAnalPlugin.findvar?
For example, on MIPS I need to do some extra …

Allow local variable detection for mips

---

libr/core/cmd_type.c

bug
tp unsigned char * ebp + 0x25
it will be difficult to differ from the address and the type
but this way we will use `=` as way to differ

Implementing tp <type>  =  address

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c
libr/include/r_anal.h
libr/include/r_util.h
libr/reg/value.c
libr/util/num.c

- Reverted ADD and ADC to set flags based on internal variables
- Fixed calculation of carry and zero flags from internal vars
- Revert "ESIL: add floating point instructions (#4794)"
This reverts commit 964d12b392afedb87d7ba29db62f51aa8e51af2c. Since we
decided that floating point operations will be implemented using separate
ops, these unions are no longer needed. This commit introduced a regression
in setting esil->old and esil->cur

Fixes to ESIL

---

libr/asm/p/asm_x86_nz.c

`nz` now generates the correct opcode when using a word as an immediate in the `sub` instruction with a register + offset as the target
Also adds support for word register offsets and refactors that portion of the code a little
For 32bit only so far
To go with PR radare/radare2-regressions#430

Add support for immediate word for `sub`

---

libr/socket/run.c

Noticed by gcc:
* QA Notice: Package triggers severe warnings which indicate that it
*            may exhibit random runtime failures.
* run.c:65:5: warning: ‘p’ is used uninitialized in this function [-Wuninitialized]
Signed-off-by: Sergei Trofimovich <slyfox@gentoo.org>

libr/socket/run.c: fix use of uninitialized value

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c

**Introduces esil internal set and unset**
- $0 and $1 can be used to set and unset registers without affecting esil
variables cur, old and lastsz and thereby not affecting any flag
computations.
- Minor bug and style fixes in anal_x86_cs.c	
**Generalizes set/unset**
- This commit makes set/unset more generic by allowing any value to be assigned
to a register (as opposed to just 0/1 before) without any side effects.
- $[0-9]* represents a value to be set, in decimal representation, without
having any side effects of changing esil vars old, cur and lastsz and hence
not affecting the flag computations. Example: Set rax to 100. ("$100,rax,=").
If the second one is taking it too far, I'll drop that commit and we can have just $0 and $1 to set/unset. If this is acceptable by everyone, I'll …

Esil internal set

---

libr/asm/p/asm_x86_nz.c

A number of fixes and updates to the `mov` command for the _nz_ assembler including:
* handling of `esp` register in more cases
* able to handle negative offsets for target register both byte and word
* able to handle negative offsets for target with immediate value as
source, both byte and word
* refactor mov block of code to be more consistent (further work needed)
Goes with r2r PR radare/radare2-regressions#435

Fixes for  `mov` op for nz assembler

---

libr/core/disasm.c

This happens after `aa`, because function names are added as comments.

Fix glitch

---

libr/asm/p/asm_x86_nz.c

* reg offset code consolidated to single location and simplified
* Refactor `getreg` for `arg` and `arg2` to use `r0` and `r1` throughout  `mov` case
Should clean it up a little.

Refactor `mov` assembly for nz

---

binr/rahash2/rahash2.c

Fixes #4642, which is about using '-x 5c', which is a backslash.

rahash2: Don't try to unescape inputs provided as hex strings (-x)

---

libr/include/sflib/linux-x86-32/sfsyscall.h

Inline assembly constraints for linux-x86-32/sfsyscall.h are changed to "r" instead of "g". This prevents situations where the compiler may substitute the operand with a memory location that may make the inline assembly function incorrectly. See #5065

Change inline asm constraints to "r" (#5065)

---

libr/anal/fcn.c
libr/anal/op.c
libr/anal/var.c
libr/core/anal.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/include/r_anal.h
libr/parse/Makefile
libr/parse/p/parse_x86_pseudo.c

afa for base pointer arguments/vars
afe for stack pointet arguments/vaes
afv for registers
fixing the J and \0 suffix
using the right register indexer
fixng the negative offsets of afa
fixing the afa afe afv views of pdf
fixing errors in aa
fixing the stack bases arg/var
fixing the varsub
fixing afa*
fixing afat
making afx- space neutral
enabling register renaming at varsub
updating the built-in help
fixing merge conflicts

re construction of argument/var commands

---

libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/util/p_format.c

Proposal fix for #4494
__disasm was changed to disassemble at specified address, otherwise it always disassemble at current offset (or i am missing smth)
r_core_print_disasm_instructions was changed to return number of bytes processed
Is there any good reason why RPrint->disasm() exist? Probably should be removed and this code rewritten to use "R" disasm api directly.

Add support for 'pf [size]D'

---

libr/asm/p/asm_x86_nz.c

mov eax, 0x1122334455667788 now errors if trying to assemble with -b64.

Error if moving 64bit val to 32bit reg

---

libr/asm/p/asm_x86_nz.c

mov eax, -3
r2r tests for this: radare/radare2-regressions#446

Add support to mov for negative immediates

---

libr/core/cmd_print.c

pX command is a left off from some old docs. Removing it from help message 'p?'

pX command removal

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/linux/linux_coredump.h
libr/util/file.c

I've added support for threads and x86 systems to the "generate coredump" feature.
I've also cleaned up all debug stuff and tried to refactor as much code as possible.
It's still missing some minor checks like:
- if the system does not offer a proc_coredump_filter (because the kernel is old enough) just take the default value (0x33)
- if kernel offers process_vm_readv, use it because it's much faster than io r/w
- some other improvments I can't think about them right now.
Once this is passed, i'll put my hands on "load coredumps"

Add: Generate Coredump - added support for threads and x86

---

binr/r2pm/r2pm

Following error is thrown when running 'r2pm update':
```bash
$ r2pm update
Already up-to-date.
rmdir: failed to remove ‘/home/jaroslav/.config/radare2/r2pm/db’: No such file or directory
```
I've fixed this by actually running different rm/rmdir commands when $R2PM_DBDIR is actual directory, or a symlink (which is standard scenario). It will also handle broken cases, where the $R2PM_DBDIR doesn't exist at all or is a plain file.
Actually, I'm not sure why we can't run "rm -rf ${R2PM_DBDIR}". I assumed there's some rationale here, and just tried to make this code more clear.
Previous code had another bug, the line:
```bash
rm -f "${R2PM_DBDIR}/*"
```
is wrong. The star in quotes is not expanded by shell, and files are not removed:
```bash
✔ 14:12 /tmp $ mkdir test && touch test/a_file
✔ …
```

Get rid of the error when 'mkdir' wanted to remove unexisting directory

---

libr/bin/format/elf/elf.c

128 is too conservative. Let's try for 0xFFFF. Also, print the size in case the check fails.

Fix ELF section size validation

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_debug.h
libr/debug/p/native/procfs.c
libr/debug/p/native/procfs.h

* Move procfs-based process listing into linux_debug.c, guarded by __linux__
* Provide a warning and eprintf a TODO on the remaining platforms.
* Break reusable parts into linux_get_proc_pid and call it as needed.
* Add/remove comments for clarity

Fixes #4875: Refactor process listing

---

libr/debug/debug.c

When changing the selected pid, we must change the IO that provides memory R/W as well.
I'm not exactly pleased with this solution but I'm sending this PR so we can start talking about it anyway.

Have r_debug_select change IO pids too

---

libr/core/cmd_debug.c

When outputting a backtrace, line things up depending on the number of bits in the target CPU.

Make "dbt" output aligned to columns based on dbg->bits

---

libr/core/cmd_debug.c

Previously, "dcf" didn't not consider that "clone" may be used to create child
processes. Look for that and also update the text shown to the user.

Add "clone" to the "dcf" command

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/p/debug_native.c
libr/include/r_debug.h

Linux 2.5.46 made changes to the ptrace(2) API to inform a tracer when various
events occur. These are known as PTRACE_EVENTs. Start handling PTRACE_EVENTs
by:
* Handling PTRACE_EVENT_FORK and PTRACE_EVENT_EXIT
* For _FORK, stores the newly created pid in dbg->forked_pid
* Add the "dpc" command to select the most recently forked child process.
Additional minor changes to white space are included.
NOTE: This partially addresses #3549

Properly handle forks on Linux 2.5.46+

---

libr/core/cmd_anal.c

`afbr`'s description isn't worded properly. It doesn't actually print addresses of `ret` instructions, but of instructions which cause the flow of the program to leave the function body, like `call`, `jmp`, `hlt` etc.

Change afbr description

---

libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/core/cmd_flag.c

A couple of commands are not checking that they were called with a required parameter which results in an out-of-bounds read. As an example, here is the handling of the ask command. When typing "ask" input + 2 will point after the NULL character. This is a fairly minor issue with but trigger bugchecks when running with tools like AddressSanitizer.
This patch checks that there is a space character before passing input as a parameter. 
libr/core/cmd_anal.c
```c
case 'k': // "ask"
out = sdb_querys (core->anal->syscall->db, NULL, 0, input + 2);
```
Commands patched by this pull request:
```
ag
agc
ask
ahi
dm-
fc
```

Check that a required argument was passed for a couple of commands.

---

libr/asm/arch/v810/v810_disas.c

Before:
```asm
$ rasm2 -a v810 -d edf90008eaf9001ccffb0014fe01aff9000c
cmpf.s r13, r15
invalid
mov r25, r7
ld.w 251[r28], r24
out.w r16, -20735[r20]
mov r25, r7
invalid
```
After the patch:
```asm
$ rasm2 -a v810 -d edf90008eaf9001ccffb0014fe01aff9000c
cvt.ws r13, r15
divf.s r10, r15
subf.s r15, r30
mov r30, r15
cvt.sw r15, r13
```

V810: Fix floating-point instructions

---

libr/bp/bp.c
libr/bp/io.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/linux_debug.h
libr/debug/trace.c
libr/include/r_bp.h
libr/include/r_debug.h
libr/include/r_reg.h

TODO. Test this PR on:
The major contribution here is completely re-worked breakpoint hit/recoil
handling. This work fixes #4907 and lays the ground work for future native
debugger improvements (multi-threading, etc).
NOTE: Please see comments marked with XXX as they include puzzlement and
questions.
A full list of changes includes:
* Give a human friendly type to enums
* Change many wait functions to return RDebugReasonType
* Better return checking (from r_debug_reg_sync, r_bp_restore)
* Optimized register synchronization
* Lots of comments and whitespace changes
* Improved inferior death detection
Handle EXIT_PID events differently than DEAD process events
* Move breakpoint/recoil handling to wait/cont/step
Rather than handing breakpoint related things inside cmd_debug.c, do that
inside …

Major rework to the native debugger (esp on Linux)

---

libr/core/disasm.c

Bug same as #5105.
Wrong output for backwards disassembling, for example
```
[0x00000000]> wx 56687cd3400090
[0x00000000]> aaa
[0x00000000]> pd 3
╒ (fcn) fcn.00000000 513
│           0x00000000      56             push rsi
│           0x00000001      687cd34000     push 0x40d37c
│           0x00000006      90             nop
[0x00000000]> s 6
[0x00000006]> pd -1
│           0x00000006      687cd34000     push 0x40d37c
[0x00000006]> pdj -1
```
Before commit:
```
[{"offset":3,"fcn_addr":0,"fcn_last":510,"size":3,"opcode":"rol dword [rax], cl","bytes":"d34000","family":"cpu","type":"rol","type_num":36,"type2_num":0}]
```
After commit:
```
[{"offset":1,"fcn_addr":0,"fcn_last":508,"size":5,"opcode":"push 0x40d37c","bytes":"687cd34000","family":"cpu","type":"push","type_num":13,"type2_num":0}] …
```

fix disassembling 'backwards'

---

libr/debug/p/debug_native.c

Linux kernel checks for unknown flags passed via the last argument to
waitpid() and fails waitpid() with EINVAL if it encounters one:
From kernel/exit.c:sys_wait4()
if (options & ~(WNOHANG|WUNTRACED|WCONTINUED|
__WNOTHREAD|__WCLONE|__WALL))
return -EINVAL;
This makes it impossible to use debugger on Linux.
WAIT_ANY macro is actually supposed to be used as PID argument to wait
for all children without specifying particular PID.
Signed-off-by: Pavel Borzenkov <pavel.borzenkov@gmail.com>

libr/debug: fix native debugger on Linux

---

libr/util/ht.c

@radare suggested using `UT32_MAX` instead of `((ut32)~0)`. #5252

Use UT32_MAX as a magic value

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c

A TRAP signal signifes expected stops for breakpoints and so on. There's no
need to display these as signals or stops since they will be communicated
inside r_debug_bp_hit.

Don't print SIGTRAP signals or stops

---

libr/debug/Makefile
libr/debug/p/debug_native.c

kvm_getprocs exists on Net and Free as well so it might work there as well
With this we can do:
```
$ r2 -d /bin/ls 
[ ... ]
[0x28a410037f0]> dp
Selected: 77048 77048
* 77048 s ls
- 90387 s radare2
[0x28a410037f0]> 
[0x28a410037f0]> dp*
- 97712 s ksh
- 77350 s xterm
* 77048 s ls
- 90387 s radare2
- 58861 s ssh
- 18250 s ksh
- 83988 s xterm
- 31464 s ksh
- 78940 s xterm
- 94112 s sh
[ .. snip ... ]
[0x28a410037f0]> 
```

Add support for dp and dp* on OpenBSD.

---

libr/debug/map.c
libr/debug/p/debug_native.c

Note that OpenBSD can have mappings with zero size so relax the assert.
Also note that the protection bits are flipped. Different bit order. Will fix that later.
Before:
```
$ r2 -d /bin/ls                                                                                          $
Process with PID 61308 started...
attach 61308 61308
[p/debug_native.c:910 r_debug_native_map_get] Cannot open '/proc/61308/maps': No such file or directory
[p/debug_native.c:910 r_debug_native_map_get] Cannot open '/proc/61308/maps': No such file or directory
Assuming filepath /bin/ls
asm.bits 64
[p/debug_native.c:910 r_debug_native_map_get] Cannot open '/proc/61308/maps': No such file or directory
-- prove you are a robot to continue ...
[0x51435c037f0]> dm
[p/debug_native.c:910 r_debug_native_map_get] Cannot …
```

Make dm work on OpenBSD by adding a native r_debug_native_map_alloc()

---

libr/debug/p/native/linux/linux_coredump.c

Otherwise may cause undef behaviour.
eg:
```c
void *note_data;
...
if (!elf_proc_note->prpsinfo) {
error = true;
goto cleanup;
}
...
cleanup:
...
free (note_data);
```
Similar thing with `offset`. Actually this var seems redundant

Added vars init in linux corefile gen

---

libr/debug/p/debug_native.c

On OpenBSD you can use the kvm interface without /dev/kmem access but on FreeBSD
you need root or kmem access which one do not want to give a user.
Look at ps(1) on FreeBSD and see how they do it.

kvm_openfiles can fail so make sure we print the error message.

---

libr/include/r_util.h
libr/include/r_util/r_debruijn.h
libr/util/debruijn.c

example for #5314
perhaps the includes for the utils should be in `#include <util/r_xxx.h>` instead?

separate debruijn to it's own header file

---

libr/asm/p/Makefile
libr/asm/p/asm_x86_nz.c
libr/asm/p/asm_x86_tab.c

Beginning to refactor the handmade assembler to incorporate some concepts of the tab assembler with the hackability of the nz assembler.
The idea is that each instruction that takes arguments is handled by its own function. Instructions without arguments just resolve to hardcoded instructions for the lookup table. Special cases are also group 1 and group 2 instructions
http://www.sandpile.org/x86/opc_grp.htm
A further aim is to remove the tab assetmbler in order to reduce the number of assemblers that ship with r2.
Second PR

Refactor nz assembler 

---

libr/asm/p/asm_x86_nz.c

Protect against shifts that might be bigger than 31

Prevent possible max shift value

---

libr/core/rtr.c

Solves issue #5338.
Used messages from HTTP background server.
Also adopted the one thread only convention.

Add ability to start RAP server in background.

---

libr/anal/p/anal_x86_cs.c

When ESIL parses a complex memory operand (an operand that requires multiple arithmetic operations), the parser code misses a comma, resulting in an invalid ESIL expression (++ or +-). This fixes #5431 .

Added a missing comma in ESIL parser

---

libr/anal/p/anal_x86_cs.c

+ LODSB and LODSW are compatible with 16-bits by using the proper size for 'si' register
+ added ss, ds, es segments to 16-bits register profile

ESIL: small x86-16 improvements

---

doc/crosscompile

A few brief pointers on how to cross-compile for ARMv5, define new targets and operate `dockcross`.
Man, @radare does need some proper reorg of `doc/`, it's a mess :_!

Documentation for cross-compiling radare with docker

---

libr/anal/esil.c
libr/core/cmd_anal.c
libr/core/cmd_search.c
libr/core/config.c
libr/core/disasm.c
libr/include/r_anal.h

This is supposed to help delaying PC divergence to null by preventing all null accesses in PC and memory
I am not sure if this will be enough.

adding nonull environment variable

---

libr/core/cmd_anal.c

according to `ae?`,  `aek-` is used to delete all esil->stats key/value pairs, but it wasn't actually implemented.
this is its implementation

fixing aek-

---

libr/core/disasm.c

This also fixes the mips big endian references test

Honor endiannes and size too in reference values in disasm

---

binr/r2pm/r2pm

Usage:
export R2PM_DBDIR="/path/to/the/folder/with/package/description"
export R2PM_GITDIR="/path/to/the/root/folder/of/the/local/repository"
r2pm -i package

Adding R2PM_GITDIR for easy packages local testing

---

libr/anal/types.c
libr/core/cmd_anal.c
libr/core/tp.c
libr/include/r_anal.h

removing address from function names, the reason behind this is that type matching requires function names to be fixed (across all binaries) because functions are only identied there by their names. since adresses my change with will reuqire each binary have his own unique database of function definitions
fixing help

Implementing Function name guessing for type matching

---

libr/core/cmd.c

Fix undeclared variable "i" in cmd.c at line 2215.

Fix undeclared variable error

---

libr/bin/d/Makefile

This is an empty file because I (DanTheColoradan) was unable to
obtain any ordinal information. I tried two versions:
-  9.0.30729.1
-  9.0.30729.6161
Both were downloaded from dll-files.com. I also tried a version
from MS Windows 10, but I don't know what version it was. I'm
also on a mac and used winedump and redump. It's possible 
using dumpbin on Windows would get information, but I doubt it.
This change should close #5486.

Add dll mfc90u to close issue 5486

---

libr/anal/var.c
libr/core/cmd_anal.c
libr/core/tp.c

fix CID 1361617
Resource leaks (RESOURCE_LEAK)
/libr/core/tp.c: 148 in stack_clean()
Var iable "str" going out of scope leaks the storage it points to.
fix CID 1361612
Null pointer dereferences (NULL_RETURNS)
/libr/core/tp.c: 178 in r_anal_type_match()
Dereferencing a null pointer "op".
fix CID 1361611
/libr/anal/var.c: 112 in r_anal_var_retype()
/libr/anal/var.c: 125 in r_anal_var_retype()
Dereferencing a null pointer "fcn".
fix CID 1361610
Incorrect expression (IDENTICAL_BRANCHES)
/libr/core/cmd_anal.c: 1616 in __anal_reg_list()
Dereferencing null pointer "fcn".

Fixing coverity CIDs

---

binr/radare2/radare2.c
libr/core/cbin.c
libr/core/cio.c
libr/core/cmd.c
libr/core/cmd_info.c
libr/core/cmd_open.c
libr/core/cmd_print.c
libr/core/cmd_seek.c
libr/core/cmd_write.c
libr/core/config.c
libr/core/core.c
libr/core/disasm.c
libr/core/file.c
libr/core/visual.c
libr/core/yank.c
libr/include/r_core.h

Backward seek has a bug when used via scripts loaded with `-i <file>` on the command line.  This is accomplished with the following steps:
1. Remove the hack that hides this bug (and others) when entering commands via stdin, verses using `-i <file>` as the regression scripts do.
2. Fix the bug by reloading the current block (instead of the next block), and only for undo seeks, not backward seeks.
3. Remove the `next` parameter entirely from `r_core_block_read()`.  It's broken and confusing.

Fix backward seek

---

binr/radare2/radare2.c
libr/asm/arch/tms320/tms320_dasm.c
libr/bin/p/bin_elf.c
libr/util/file.c

Valgrinding to get exp. Testing with "r2 -Aqcq /bin/ls"
Before:
definitely lost: 22,735 bytes in 250 blocks
indirectly lost: 23,542 bytes in 605 blocks
possibly lost: 2,464 bytes in 7 blocks
still reachable: 3,876,216 bytes in 80,761 blocks
After:
definitely lost: 25,216 bytes in 58 blocks
indirectly lost: 24,830 bytes in 739 blocks
possibly lost: 0 bytes in 0 blocks
still reachable: 20,105 bytes in 34 blocks
The "goto beach" (named like that for consistency) change resulted in freeing most of the "still reachable" stuff on quit, which also moved stuff out of "possibly lost", so.. it looks like it's leaking more now. Yay.

Fix a handful of boring leaks

---

libr/core/visual.c
libr/socket/socket.c

- Implemented connect timeount on r_socket_connect for windows.
- Implemented visual key to set PC register with cursor address, only avaliable in cursor mode using '*' key

add socket timeout on windows connect

---

libr/core/cmd_anal.c

Fix null derefs and mem leak in var_cmd
reproduce steps:
1. `VV`
2. `:afvn` and hit enter
3. crash!
I also find a mem leak bug and patched

Fix null defrefs and memory leak in var_cmd

---

libr/core/config.c

Remove mention of anotated stack from description of stack.size configurable.  stack.size applies regardles of value of stack.anotated
Fix for issue 5541

5541 Fix - Edit stack.size description for clarity

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/linux/linux_coredump.h

* Fixes: 5540 (now i386 will not complain in case they're missing GETREGSET)
* Fixup: Owner set to Linux for NT_PRXFPREG
* Fixup: Now extra section hdr is being written with the right offset
* Fixup: Bug with multithread cfg fixed
* Add: Now r2 is able to generate coredumps on ARM platforms
I tested it on i386, x64_x86 and arm_32bits.
Unfortunately I don't have an arm 64bits board, so if someone could test it there, that would be great.
Besides of adding support for ARM platform, I fixed some bugs I found during my tests.
I hope it passes the tests, let's see ;)

 Coredump support for ARM and fix-ups

---

libr/asm/arch/msp430/msp430_disas.c

Previously, single-operand instructions using a constant of "1" would not be decoded properly.
See corresponding regression PR: https://github.com/radare/radare2-regressions/pull/509
Can split whitespace cleanup into a separate PR if desired.

Add a missing MSP430 constant register instruction encoding

---

doc/sandbox/README.md
libr/include/r_types.h
libr/util/sandbox.c

move from systrace(4) (removed in 6.0 release) to pledge(2) (available since 5.9).

update native sandboxing method for OpenBSD

---

libr/anal/var.c
libr/core/anal_tp.c

At first running aftm without initializing stack will go into undefined behavior
now it will warn user to initialize stack with `aei;aeim` or any other method before running aftm

Fixing type matching with esil into non initialized stack

---

libr/debug/debug.c

As the comment says, we need to pretend to satisfy the caller. For some reason
I also restored the breakpoints here. I cannot for the life of me figure out
why since it should be ok with in all cases.
For swstep=false, the step will stop right away (regardless of any breakpoints)
and thus need to remove breakpoints anyway.
For swstep=true, a breakpoint is created on the next instruction and would stop
too and thus need to remove breakpoints anyway.
So yeah, don't do this. Thanks for the report skuater!

Don't restore breakpoints on STEP recoil

---

libr/core/cmd_anal.c

It's 10:00 PM, do you know where your stack pointers are?
Needed this for some external analysis, the stack op is already there so why not this.

Add stackptr to aOj output

---

libr/bin/demangle.c
libr/core/cmd_debug.c
libr/core/disasm.c

- flag->realname can be NULL (an ELF executable with null symbols). Correct two cases in `cmd_debug.c` and `disasm.c` that are assuming a non-NULL realname.
- Add a NULL check to the prelude of `r_bin_demangle`, just in case.
Avoids the following segfault during disassembly:
```
#0  0x0000197007cdc6e9 in r_bin_demangle (binfile=0x197079c5b900, def=0x19708bbe9a70 "c", str=0x0) at demangle.c:350                                   
#1  0x00001970aebff2fd in ds_show_flags (ds=0x1970965880a0) at disasm.c:1259                                                                           
#2  0x00001970aec05771 in r_core_print_disasm (p=0x197029ea2400, core=0x196db5908880, addr=134217796,                                                  
buf=0x196ff8dce800 "...", len=410, l=41, invbreak=0, cbytes=0) …
```

Handle NULL strings in r_bin_demangle

---

libr/core/cbin.c

Not sure what the use of this was, but it confused me during debugging

Remove unused field `addr` from SymName

---

libr/core/cmd_flag.c
libr/core/cmd_section.c
libr/flags/flags.c
libr/flags/spaces.c
libr/util/str.c

Beside of fixing a oob write, I added it the possibility to change the flag name associated with a section after changing the name with `Sr` command the only issue is that seeking to that new section goes to zero.
```
[0x00005c20]> S.
0x000075a0 0x00017989 .text
[0x00005c20]> f~section..text
0x00003ad0 66537 section..text
[0x00005c20]> f~section_end..text
0x00013eb9 0 section_end..text
[0x00005c20]> Sr newname
[0x00005c20]> S.
0x000075a0 0x00017989 newname
[0x00005c20]> f~section.newname
0x00003ad0 66537 section.newname
[0x00005c20]> f~section_end.newname
0x00013eb9 0 section_end.newname
[0x00005c20]> f~section_end..text
[0x00005c20]> s section.
section.                     section..interp              section..note.ABI_tag
section..note.gnu.build_id   section..gnu.hash …
```

Fix #5543 - oob write in Sr command

---

libr/util/sys.c

the diff corrects a logic error in `__WINDOWS__ && !__CYGWIN__` case, as
r_sandbox_open() will return `-1` on error.
and it makes a sandbox check before calling truncate(2) syscall.

make r_sys_truncate() obey to sandbox mode

---

libr/anal/p/anal_x86_cs.c

- POPFD and POPFQ were not counted.
- POPCNT is not a stack operation but counts the '1' bits in a word. Not sure where POPCNT belongs with it was wrong here.

anal: Fix stack pointer tracking for POPCNT POPFD POPFQ

---

libr/core/anal_tp.c

this is just temporary fix, It just terminates `aftm` once `PC` accesses the same address 10 times

Fixing infinite loop issue

---

libr/core/config.c
libr/core/disasm.c

Disabled by default. When enabled, it shows the flag and comment that is
at the ref of the current instruction.
Test for this: https://github.com/radare/radare2-regressions/pull/522

Added e var asm.cmtrefs. Fix #5571

---

libr/core/vmenus.c

_Vdi d_, _Vdi h_, _Vdi o_ etc wasn't working in visual mode as a numeric base was enforced (in contrast to what the help suggested)

fix immediate base setting in visual mode

---

libr/core/project.c
libr/core/vmarks.c

removing deletion of marks after dump and using UT64_MAX as an unset flag throughout the code.

Virtual marks cleanup & added to project file

---

binr/r2pm/r2pm

add support to have `R2PM_GIT path-to-git-repo directory-name-to-clone-to`

add support to have custom directory name for cloned repo

---

libr/anal/p/anal_x86_cs.c
libr/debug/debug.c
libr/include/r_anal.h

these changes should allow single stepping of instructions like "call qword [rax*8 + 0x6008a8]" and "jmp qword [rbx*8 + 0x6004e0]" to work properly.

single stepping of JMP/CALL with indirect memory operand

---

libr/core/cmd_debug.c

Example of issue:
db entry0
db entry0+2
dbic 1 dr
db
--> shows in cmd "1 dr", which cannot be executed!
This patch should solve this issue

fix for debug command dbic <num> <cmd>

---

binr/rahash2/rahash2.c
libr/core/cmd_print.c
libr/include/r_hash.h

The fix for issue #5007 has caused a gap between the bits in the hash_name_bytes structure. As such, the for loops to print the available hashes stop at the first gap. This fix allows to have any number of gaps in the bits. Since ut64 is a 64bit word, the for loops are hard-coded with the number 64.

Fix #5556 - prints all hashes, even if have gap between the bits

---

libr/include/r_util/r_sys.h
libr/util/sys.c

it permits to properly check sandbox mode before calling mkdir(2).
it is a better way to fix #5595 as the check is at a lower level.

change r_sys_mkdir() from macro to function

---

libr/core/vmarks.c

Visual marks do not respect the specified addresses but uses always the current seek.

fix visual mark target address

---

libr/core/cbin.c

That is not the kind of bug I see everyday
1- calling convention db is loaded
2- function cc types is initialized by project file, that string is only
one copy across the whole database for memory efficiency.
3- The db is reloaded due to change in arch or what ever, Old strings
are freed and new one is created with totally new address. Most cases it
just reload the same database.
4- Addresses in function cc types are not updates, they are already
freed at reloading db step
Solution implemented at db reloading step:
1- create new temp db with all possible available calling conventions and
the adresses in memory of these calling conventions
2- once db is reloaded, grab adress of cc from function, match it with
the name in the new temp db, then replace it with the constant value
from the …

Fixing nasty bug in CC implementation

---

libr/debug/reg.c

Commit 12a6469bbd4fc7 broke some regressions.
How to reproduce?
cd radare2-regressions/t.archos/Linux-x86_64
r2 -AAd ../../bins/elf/x86-helloworld-gcc
==> Will randomly crash with segmentation fault.
Reason looks like the dbg->reg->regset[i].arena->size is giving some strange values, e.g.
i=3, dbg->reg->size=296, dbg->reg->regset[i].arena->size=1
The size of 1 byte from arena->size seems to be causing the crash.
This commit reverts back the line.
Probably a better fix is to look at where, in the codebase, these values are (or should) be initialized.

fix radare2-regressions/t.archos/Linux-x86_64/dbg_bps regressions

---

libr/core/cmd_anal.c

For `afx-`, input starts at `fx-`, so the added offset needs to be 3, not 2. Without this change, it will always print `Usage: afx- [src] [dst]` as `*mi==' '` will never match.

Fix off-by-one error in afx- handling

---

libr/anal/p/anal_x86_cs.c

esilized STOSB are using alway 32 regs, the fix look for arch->bits and use correct reg size.

fixed esil STOSB opcode for 16 bits

---

shlr/bochs/Makefile

Pull request to fix Bash on Ubuntu on Windows builds, as discussed in #5232.
(text below is from the commit)
r2 builds currently fail on Bash on Ubuntu on Windows due to the
${NAME} variable being defined in the environment (as the current
hostname), which meant that libbochs.a was being placed in an
unexpected location. This patch fixes the issue for BoUoW by replacing
use of the ${LIB} variable with a set value of 'lib'. It should be
noted that other build scripts (e.g. shlr/bochs/deps.mk) currently
assume that libbochs.a is located precisely at
shlr/bochs/lib/libbochs.a anyway (and as such, it is suspected that
the use of ${LIB} here may have been spurious to begin with).

Bash on Ubuntu on Windows fix - remove ${LIB} from Makefile

---

libr/anal/types.c

```
struct test {
char name[256];
int id
}
```
to
```
pf [256]zd name id
```
instead of
```
pf *zd name id
```

added array size support for structures

---

libr/anal/types.c
shlr/tcc/tccgen.c

Interpret char[] as char* in the pf format (use z instead of c).

fixed array types in parsing routines + added special case for char[]

---

libr/anal/anal.c
libr/anal/fcn.c
libr/anal/p/anal_x86_cs.c
libr/core/anal.c
libr/core/config.c
libr/core/disasm.c
libr/flags/flags.c
libr/include/r_anal.h
libr/include/r_flags.h

If an analysed address belongs to some function we simply skip all further analysis.
Theoretically this fix should significantly decrease number of false positives, also it solves this issue - https://github.com/radare/radare2/issues/4783.

r_core_anal_fcn fix

---

libr/debug/p/native/linux/linux_coredump.c

I don't how this happened but for some reason in the function where we're writing the files-backed maps I forgot to check if the map was actually a file-backed map.
This didn't hurt small processes, so I guess this is why I didn't spot it, but with big processes like firefox this causes a segfault.
This fixes it.

Fix:  fix segfault for really big processes while dumping it (coredump)

---

libr/anal/fcn.c
libr/core/anal.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_anal.h

This pull request fixes issue https://github.com/radare/radare2/issues/4442 and https://github.com/radare/radare2/issues/4734
The following bugs were fixed:
- `pdf` worked only with continuous functions. (which is wrong because funcs bbs could be aligned not continuously, example of such function can be found in issue #4743)
- `pdf` used size instead of realsize
- `pdr` locs print is added
- loc.* were not a part of a function. Now behavior is similar to the IDA behavior. Each functions includes locs and the function realsize calculated as size of bbs of a function + locs size

"#4734 #4442 fix"

---

libr/core/libs.c

For example given a plugin defined like this:
```C
RIOPlugin r_io_plugin_foo = {
.name = "foo",
...snip...
};
#ifndef CORELIB
RLibStruct radare_plugin = {
.type = R_LIB_TYPE_IO,
.data = &r_io_plugin_foo,
.version = R2_VERSION
};
#endif
```
We will try to `free (&r_io_plugin_foo)`, which was not allocated on the
heap. Static io plugins are OTOH allocated like this, so we need to do
the same for dynamically loaded io plugins. However, this is not the same
across the different plugin types, so we need to special-case io plugins
here.

Fix invalid free() on teardown for io plugins

---

libr/util/debruijn.c

```
debruijn.c: In function ‘r_debruijn_offset’:
debruijn.c:107:6: warning: variable ‘n’ set but not used [-Wunused-but-set-variable]
int n, retval;
^
```
(gcc 6.2.1)

cleanup unused variable in r_debruijn_offset()

---

libr/include/r_util/r_str.h

Was not declared in the r_str.h header and therefore only implicit declared by the compiler

added r_str_startswith to header

---

libr/anal/p/anal_x86_cs.c

fix op->type in libr/anal/p/anal_x86_cs.c for FMOV in swich statement

fix op->type in libr/anal/p/anal_x86_cs.c for FMOV

---

libr/anal/var.c
libr/core/cmd_anal.c
libr/include/r_anal.h

Due to the uniqueness of name of arguments and variables, They can be
used solely to identify every other piece of information (including the
base register type).
This will make the commands some how user friendly and more usable by removing one extra
letter from some commands.

merging some of afv* commands

---

libr/anal/types.c
libr/core/disasm.c
libr/include/r_anal.h

Current unfixed issues:
works with aa, aaa,aaaa but never worked with af

integrating asm.calls with function types database

---

libr/core/anal.c

First off, there is an overshadowing of `esilbreak_last_read`. Second, it should be always updated on read because the validity of the pointer will be checked later anyway.

anal: always save address in the esil read callback

---

libr/cons/cons.c
libr/core/cmd_zign.c

- Confirmation message for number of lines to print will not appear
anymore if the output is redirected to a file.
- "signature too small" message will be printed to stderr instead of
stdout, so will not appear on zignature file.
- Previous flagspace will be restored after running `.z` or `z/`
commands.

Fixed some issues from #5718

---

libr/core/cmd_zign.c
libr/core/config.c

- Added cfg.maxzlen to filter out big zignatures (#5718)
- Changed r_anal_fcn_size to r_anal_fcn_realsize on `zg` and `z.`
(realsize makes more sense)

More zignature fixes

---

libr/cons/input.c
libr/debug/debug.c
libr/debug/p/native/linux/linux_debug.c
libr/debug/p/native/linux/reg/linux-mips.h
libr/debug/p/native/linux/reg/linux-mips64.h

\* A new MIPS profile (32 bits) has been created
\* MIPS (32 bits) registers could be read/written properly (LE is still using the old 64bits profile) 
\* breakpoint (soft) stepping is now working (even with a bp at the same addr)
\* ds, drr, dbc, etc. are working properly
! dS is not working yet
\+ I have tested this patch on x64LE, x86LE with basic functions (ds, dS drr, dbc, etc.) and it works well. It seems nothing is broken.

Fixing debugging problems at MIPS (32bits)

---

libr/debug/debug.c

This is my local patch for #5717 that only checks if the signal was valid and doesn't check the reason of the signal.

Reduce the requirements of dko to any reason with a signum

---

libr/core/config.c

I feel like nodejmps is a natural extension of the shortcuts used in graph mode and when they are not enabled it seems to me like there's something missing...
what about enabling it by default?

conf: enable graph.nodejmps by default

---

libr/core/cbin.c
libr/core/config.c

R2R's PR: https://github.com/radare/radare2-regressions/pull/571
In R2 flags come from symbols and classes, if a class also contains methods this symbol will be duplicate (from symbols and classes->methods). This affects Dalvik an ObjC, maybe more formats too.
In order to fix that we can add a "if (flag_exists (r->flags, sym->name))" to check if the flag is already defined.
I'm not sure if "flag_exists" function exists or if it should be defined elsewhere.
This fix seems to also fix https://github.com/radare/radare2/issues/5886.

fix flags duplication

---

libr/anal/p/anal_x86_cs.c

It seems that capstone based ESIL of `call word/dword ptr16:addr16/32` was broken, because it didn't update the CS segment, and it used the segment address as jump offset.

Fixing x86 16/32 bit LCALL

---

libr/anal/p/anal_x86_cs.c

x64 doesn't use second parameter in LCALL (segment registers does not exists).

Fixed LCALL for x64

---

binr/rax2/rax2.c
libr/core/cmd_help.c
libr/core/disasm.c
libr/include/r_util/r_num.h
libr/util/num.c

consists of 2 changes:
1. allow space in the original implementation as character
2. support escape sequences for nonprintable chars (uses currently hardcoded compile flag)
see #5896

added support for escape sequences in r_num_as_string

---

libr/anal/p/anal_avr.c

Implemented LDS, LDS (16bit), LPM opcodes, and support for st/ld operations on different memory spaces. Also added support to RAMPD register.

More memory AVR operations

---

libr/core/cmd_debug.c
libr/core/linux_heap_glibc.c
libr/include/r_heap_glibc.h

casting for PFMT64x formatted variables may have to be done dynamically in order to display the right size on particular structure elements depending on debugee's arquitecture.

NOT FOR MERGE, problems with 32bit ELF parsing in dmh-refactor

---

libr/asm/d/x86

`movsd` and `cmpsd` have different meanings depending on the context, see https://github.com/nologic/idaref/issues/6 for more details.

updated various opcode descriptions

---

libr/asm/p/asm_x86_nz.c

Check that register is not memory i.e. [eax] to generate correct opcode

Fix for issue #5976

---

libr/anal/esil.c
libr/anal/esil_stats.c
libr/anal/esil_trace.c
libr/anal/p/anal_8051.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/debug/esil.c
libr/include/r_anal.h

Modification on operation hook_reg_write() in RAnalEsilCallbacks struct, for supporting modification of the incoming value,
This PR supersedes the previous PR https://github.com/radare/radare2/pull/5950/commits/d5eb782a6cfd2af01e956fae4f24a81dcbf94336
I don't know how to rebase, squash, smash, unmerge, patch, drop, pop, push and strock with GIT, so I have created a new clean branch and applied my patches on it.

Support for modifying incoming value when writing on ESIL register

---

libr/asm/p/asm_x86_nz.c

Add support for segment registers with offset for `mov` command, and segment reg support for `pop` and `push` ops
Includes a number of fixes for 64bits ops too.
r2r pr accompanies this commit

Add segment reg support and numerous fixes FIX #5967

---

libr/anal/p/anal_avr.c

When doing analysis of avr opcodes, the opcode "type" attribute is an int.
**anal_avr.c**
```c
typedef struct _opcodes_tag_ {
const char *const name;
int mask;
int selector;
inst_handler_t handler;
int cycles;
int size;
int type;
} OPCODE_DESC;
```
But in the core RAnalOp struct, the type attribute is ut64.
**r_anal.h**
```c
typedef struct r_anal_op_t {
char *mnemonic; /* mnemonic */
ut64 addr;      /* address */
ut64 type;      /* type of opcode */
....
} RAnalOp;
```
One problem caused by this is that non-conditional jumps do not draw reflines. In **reflines.c**, op->type is compared to R_ANAL_OP_TYPE_CJMP in the switch statement. The comparison fails due to the type difference.
The file I'm using for this test is here:
https://raw.githubusercontent.com/Riscure/RHme-2015/master/binary/ct …

Fix integer size in avr opcode type attribute

---

libr/anal/p/anal_x86_cs.c

Reworked X86_INS_XADD because the former version generated not even ESIL code which was feedable to the "ae" command. After a part of the evaluation the ESIL stack was in conditions like: "rcx,=" which seems to be invalid.
So the reworked code in this patch is the code from X86_INS_XCHG followed by an addition of the two operands.

Rework of X86_INS_XADD. It is now basically an X86_INS_XCHG + add.

---

libr/anal/d/types

Is there a way to specify varargs?
Because the signature of `err` is: `void err(int eval, const char *fmt, ...)`

Add err lib function to osx and linux

---

libr/anal/anal.c
libr/anal/bb.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_reg.h
libr/reg/arena.c

This should fix https://github.com/radare/radare2/issues/4497
- pdr with recursive esil status inheritance, use an hash table to keep the parent's register arena values
- added the `last_disasm_reg` on `core->anal`, this holds the final status of the last disassembly command, can be used to chain emulation status between subsequent disasm sessions (could be useful also in graphs)
let's discuss this!

Fix for issue #4497

---

libr/asm/p/asm_x86_nz.c

Fix for #6042 
```
$ rasm2 -a x86 -b 64 'mov byte [rbp - 0x100], 2'
c68500ffffff02
```
Oddly this also compiles correctly before this patch with keystone installed. Not sure as to why yet.

Assemble 64bit byte mov correctly [FIX #6042]

---

libr/core/cmd_print.c

- arena is propagated only in foward jumps / fails
- because pdr evaulates blocks in order of address

Fix memleak in pdr on backward jumps

---

libr/core/cmd_print.c

- avoid overwriting a parent_reg_arena coming
from another parent

Fix another memleak in pdr

---

libr/core/cmd_print.c

- color causes extra ';' chars to break string matching in pds
An example of the problem is:
```
:> pds
0x10000a4a4 bl
0x10000a4cc str.cstr.32_bit
0x10000a4f8 str.cstr.64_bit
0x10000a504 bl
:> e scr.color=false
:> pds
0x10000a4a4 bl sym.imp.sysctl
0x10000a4cc str.cstr.32_bit
0x10000a4d4 b 0x10000a500
0x10000a4f8 str.cstr.64_bit
0x10000a504 bl sym.imp.objc_retain
0x10000a508 b 0x10000a538
:>
```

Disable color during pds string parsing

---

libr/anal/d/types
libr/anal/d/types-32
libr/anal/d/types-64
libr/core/disasm.c

- resolve function calls and arguments type
- add size_t for 32 / 64 bits
- change 'char *' to 'z' instead of '*z' to work with both
register and stack calling conventions
related to https://github.com/radare/radare2/issues/5759
current sample output is:
```
│           0x0804845b      lea eax, [ebp - local_18h]                 ; eax=0x177fe4
│           0x0804845e      mov dword [esp + local_4h], str.250382     ; [0x804858f:4]=0x33303532 LEA str.250382 ; "250382" @ 0x804858f
│           0x08048466      mov dword [esp], eax
│           0x08048469      call sym.imp.strcmp                        ; int strcmp(const char * s1 : (*0x177fe4)0x00177fb4 =, const char * s2 : (*0x804858f)0x00177fb8 = 250382);
```

(WIP) Use anal types sdb in emuwrite disasm hints

---

libr/core/disasm.c

- actually use arg_size to advance the stack pointer
- nice error display: unk_size, unk_format or unk_size_format

Fix issues in emuwrite call args in disasm

---

libr/core/disasm.c

Make function and args resolution work in mips too, by leveraging internal ESIL `$jt` register to get the proper function address.
```
│ 0x004b36a4      8f858030       lw a1, -0x7fd0(gp)                    ; [0x924390:4]=0x7f0000 "160.6.10" ; a1=0x7f0000 "160.6.10"
│ 0x004b36a8      8f991b0c       lw t9, 0x1b0c(gp)                     ; [0x92de6c:4]=0x7e1790 sym.imp.strncmp ; t9=0x7e1790 -> 0x10809900 sym.imp.strncmp
│ 0x004b36ac      8fa40254       lw a0, 0x254(sp)                      ; a0=0x0
│ 0x004b36b0      24a5d424       addiu a1, a1, -0x2bdc                 ; a1=0x7ed424 "5.4.8.1.160.1" str.5.4.8.1.160.1
│ 0x004b36b4      0200c821       move t9, s0                           ; t9=0x7e1790 -> 0x10809900 sym.imp.strncmp
│ 0x004b36b8      0320f809       jalr t9 …
```

Fix mips emu function resolution in disasm

---

libr/anal/p/anal_x86_cs.c

Patched ``getarg()`` function and removed ``return strdup()``/``return r_str_newf()`` from it.
Patched ``anop_esil()`` and ``anop()`` functions to make it work with patched ``getarg()``

fix #5940 in libr/anal/p/anal_x86_cs.c

---

libr/asm/arch/arm/armass.c

If label resolves to an offset of 0, assume instruction invalid
Test added via PR radare/radare2-regressions#611

Error on invalid b instruction FIX #5085

---

libr/core/graph.c

Trivial recursive esil state in graph basic blocks. This borrows from `pdr`, and actually there is duplicated logic. Should be nice to do a reusable iterator and use that in both places, i'm unsure where this could be placed or if this would be a proper generalization of this problem.
This, as in `pdr`, is not handling loops. The inherited state for a given block is the first one that occurs in order of visit (blocks are visited in order of address). In the long term this can be refined / refactored / rewritten using proper graph theory.
The main impact on the performances is the initial sorting of blocks, but it's mitigated by the fact that it happens only once per function.
related to https://github.com/radare/radare2/issues/5658

Recursive graph emu (wip)

---

libr/core/cmd_help.c

It was renamed by 5683e45cb2a7c60b422aa7943a049616ec1607d7, which just missed removing it from here.

cmd_help: Remove # [algo] [len] from main help (it's ph now)

---

libr/core/cmd.c
libr/core/cmd_hash.c

This whitelists #! and #? and considers every other line starting with #
as a command, handled at r_core_cmd_subst() instead of reaching
cmd_hash(), because if that happens, file redirections and other
modifiers may get processed too in lines that otherwise look like
comments.

Fix #6124 - ensure "#\t" doesn't get processed as a command

---

libr/debug/p/debug_native.c

Add suport for x64 fpu on windows, its needed check all this stuff and add to a reg profiles, at this moment the fpu regs never be print because exist a "showfpu" variable  setted to false by default.
With this change we removed the disgusting TODO message under winx64 debug sessions.

implemented basic fpu regs for winx64 debugger

---

libr/debug/p/native.mk

symbol r_cons_break_end dont is linked.

Fix error r_cons_break_end when build for windows

---

libr/asm/p/asm_z80.c

without these guards the linker complains:
p/asm_z80.o:(.data.rel+0x0): multiple definition of `radare_plugin'
p/asm_m68k_cs.o:(.data.rel+0x0): first defined here
collect2: error: ld returned 1 exit status

fix radare_plugin redundantly defined

---

libr/asm/p/asm_m68k_cs.c

radare_plugin should not be defined for builtin plugins.

asm_m68k_cs: Add missing CORELIB check

---

binr/preload/Makefile

I packaged 1.0.2 for debian using --with-libversion=1.0, as it should be ABI compatible. While this mostly worked, libr2.so has been generated with 1.0.2 as soname. This fixes the behaviour.

libr2.so: fix soname version

---

libr/anal/types.c

it was shitty typo, but it helped finding another bug where
r_anal_type_get_size never took arrays in concideration, not it should
work well.

FIX #59999

---

Makefile
libr/anal/anal.c
libr/anal/d/Makefile
libr/asm/d/Makefile
libr/core/cbin.c
libr/core/visual.c
libr/include/r_asm.h
libr/include/r_magic.h
libr/magic/d/Makefile
libr/syscall/d/Makefile
libr/syscall/syscall.c

Hi,
This moves all architecture independent data (ca. 2MB) from r2's LIBDIR to r2's DATADIR. This is interesting from a distribution's point of view, since for stuff in /usr/share one package is enough for all architectures. So instead of having 2MB of data in e.g. 10 different architecture-specific packages it's provided by one architecture-independent package saving ~20MB. It's also interesting for users installing the r2 libs for multiple architectures to save some memory & bandwidth.
-- Sebastian

Arch independent data in share

---

libr/asm/arch/arm/armass.c

Fix instructions mentioned in #6181 
Goes with r2r PR radare/radare2-regressions#627

Fix `add` and `sub` for arm thumb FIX #6181

---

libr/cons/output.c
libr/core/anal.c

- Fixed message 128 bits not implemented when anal try to read the gpr arena.
- Fixed isssues with visualmode in windows: The problem come when end line is processed, size of write dont is checked and can write invalid data.
- Fixed issues with visual mode when asm.emu is enabled, the variable "ll" dont its checked for values low to 0 and in some cases tell to the routine a print over the buffer.

Fix windows visualmode

---

libr/anal/p/anal_avr.c

The ``select`` field is wrong for the instruction ``sbci``.

Fix sbci instruction handling.

---

libr/anal/p/anal_xtensa.c

Fix https://github.com/radare/radare2/issues/6227
Immediate of **beqz.n** and **bnez.n** is unsigned. So, it can jump only forward.
>The target instruction address of the branch is given by the address of the BEQZ.N in-
struction, plus the zero-extended 6-bit imm6 field of the instruction plus four. Because
the offset is unsigned, this instruction can only be used to branch forward. If register as
is not equal to zero, execution continues with the next sequential instruction.

Fix for xtensa analysis of beqz.n and bnez.n  

---

libr/core/cconfig.c
libr/core/disasm.c

- emulate silently, to avoid skipping calculating values
which could be used in subsequent instructions
also made a test for this: https://github.com/radare/radare2-regressions/pull/612

asm.emu emulate also when meta is there

---

libr/anal/p/anal_arm_cs.c

The ARM Architecture Reference Manual states that the base address for a LDR literal instruction is the 4-byte aligned PC. 2-Byte aligned instructions can be found on Thumb, but literals are still word-aligned.
This caused a bad literal lookup wherein an instruction was referencing across word literal boundaries in a binary I was analyzing.
I couldn't figure out how to put together a concise testcase for radare-regressions, since this really just effects the ESIL interpretation of the instruction, and is dependent on file offsets. Happy to do it if you have suggestions on how to do so. :)

Ensure ARM LDR literal instruction base addresses are word-aligned

---

libr/anal/op.c
libr/anal/p/anal_arm_cs.c

Fix for #3486
Also fixes the flags in the register profile
r2r PR: radare/radare2-regressions#632

Add support for `it` thumb instruction in esil FIX #3486

---

libr/core/anal.c

Highlights the current block when using `aga` cmd too, using graph.current colour
Fix #6260

Colour current node when using aga Fix #6260

---

binr/radare2/radare2.c
libr/anal/anal.c
libr/bin/bin.c
libr/debug/debug.c
libr/debug/plugin.c
libr/io/io.c
libr/reg/reg.c

Running radare2 inside valgrind I obtained a series of memory leaks, these commits should fix every one of them.
Radare2 was executed without analysis, I just opened an executable with "valgrind r2 hello" and then closed immediately with a ^D. The [hello.zip](https://github.com/radare/radare2/files/622733/hello.zip) executable is attacked to this request.
I run my patches against the test suite and it produces exactly the same errors.
Let me know if there is any change that should be made or if there is something that is not clear.

Fix various memory leaks 

---

libr/debug/p/native/linux/linux_coredump.c

Fixes a regression introduced by commit f0f54ad1c614f7f1a449844a123fb8f9299ee497
elf_proc_note->n_threads = proc_data->per_process->num_threads;
This assignment was deleted, but elf_proc_note->n_threads is being checked later in build_note_section in order to dump NT_PRSTATUS/FPREGSET/SIGINFO/X86_XSTATE structures per thread.
Before:
$ readelf -n test.core 
Displaying notes found at file offset 0x00000270 with length 0x000002cc:
Owner                 Data size	Description
CORE                 0x00000088	NT_PRPSINFO (prpsinfo structure)
CORE                 0x00000130	NT_AUXV (auxiliary vector)
CORE                 0x000000d6	NT_FILE (mapped files)
After this patch:
$ readelf -n newcore
Displaying notes found at file offset 0x00000270 with length 0x00000a2c:
Owner                 Data size …

Fix: regression in commit f0f54ad1c614f7f1a449844a123fb8f9299ee497

---

libr/bin/pdb/pdb.c

`rabin2 -Pj` output resulted in invalid json due to missing commas.  Was missed in the refactoring during cf384484e8f5425b2016f6ccdfefe2ce912512dd.

fix pdb json output (branch was never taken due to wrong mode)

---

libr/bin/p/bin_mach0.c
libr/bin/p/bin_mach064.c

Both 64 an 32 bits works under latest macos.
Still didn't tested/ported to ARM, though.
related to https://github.com/radare/radare2/issues/5705

Fix (not so) tiny macho creation

---

libr/bin/format/bflt/bflt.c
libr/bin/format/bflt/bflt.h
libr/bin/p/Makefile
libr/bin/p/bflt.mk
libr/bin/p/bin_bflt.c
libr/include/r_bin.h
plugins.def.cfg

Once again, this times relocations are fixed:
```
$ file test2
test2: BFLT executable - version 4 ram
$ r2 -e io.cache=true ./test2
[0x00000044]> s 0x00000160
[0x00000160]> pd 10
0x00000160      14100be5       str r1, [fp, -0x14]
0x00000164      30309fe5       ldr r3, [0x0000019c]        ; [0x19c:4]=0xdeadbeef
0x00000168      08300be5       str r3, [fp, -8]
0x0000016c      2c009fe5       ldr r0, [0x000001a0]        ; [0x1a0:4]=0x4668 str.Hola
0x00000170      0d0000eb       bl 0x1ac
0x00000174      28309fe5       ldr r3, [0x000001a4]        ; [0x1a4:4]=0x4660 str.Adios
0x00000178      003093e5       ldr r3, [r3]
0x0000017c      0310a0e1       mov r1, r3
0x00000180      20009fe5       ldr r0, [0x000001a8]        ; [0x1a8:4]=0x4670 str._s_n
0x00000184      1a0000eb       bl 0x1f4 …
```

Add: Initial support for bFLT v4

---

mk/i686-w64-mingw32.static-gcc.mk
mk/x86_64-w64-mingw32.static-gcc.mk

Support for dockcross+mxe, which requires `.static` toolchain on mxe path:
https://github.com/mxe/mxe
https://github.com/dockcross/dockcross
Complements with PR: https://github.com/radare/radare2-release/pull/1

Add mxe+dockcross support for docker-windows builds

---

libr/socket/socket.c

- Fixed RAP in windows x64.
PD: I dont understand who made the exclusion of socket under win64 .... win32/64 share same API for sockets

fixed rap in win64

---

libr/asm/p/asm_x86_nz.c

For group 1 instructions with AL for op1 and a constant for op2, nz will now generate the shorter opcodes

group1 instructions generate short opcodes FIX #6377

---

libr/bin/p/bin_dex.c

R2R PR: https://github.com/radare/radare2-regressions/pull/646
Dex format is now parsing all data from HelloWord.dex. In r2r PR the broken status is removed. More tests will be added soon.

fix parse_debug_item in dex

---

libr/anal/p/anal_avr.c

Fixed SPM page size (it was expressed in bytes instead of bits).

Fixed SPM page size

---

libr/core/cmd_info.c

R2R PR: https://github.com/radare/radare2-regressions/pull/652
New output, now the second import is a export:
```
[0x1000011e0]> ia
havecode true
pic      true
canary   true
nx       false
crypto   false
va       true
intrp    /usr/lib/dyld
bintype  mach0
class    MACH064
lang     c
arch     x86
bits     64
machine  x86 64 all
os       osx
minopsz  1
maxopsz  16
pcalign  0
subsys   darwin
endian   little
stripped false
static   false
linenum  false
lsyms    false
relocs   false
binsz    38624
[Imports]
ordinal=000 plt=0x00000000 bind=NONE type=FUNC name=_DefaultRuneLocale
ordinal=001 plt=0x10000443e bind=NONE type=FUNC name=__assert_rtn
ordinal=002 plt=0x100004444 bind=NONE type=FUNC name=__bzero
ordinal=003 plt=0x10000444a bind=NONE type=FUNC name=__error
[....]
82 imports
[Exports] …
```

fix ia command for normal output

---

libr/debug/p/debug_native.c
libr/socket/run.c

Here are the first few fixes for issue #6394. Still missing is correct pty header include in run. c for kfreebsd and the int64 offset to pointer cast in cmd_zign.c.

Small fixes

---

libr/anal/esil.c
libr/anal/p/anal_avr.c
libr/include/r_endian.h
libr/util/mem.c

An initial support for 24 bit memory ops in esil (mov of 3 bytes, big and little endian).
AVR bugfixes.

Support for 24 bit esil memory ops and bugfixed AVR flags

---

libr/cons/cons.c

Defect reported by Coverity Scan

Call var_end in case of an early return

---

libr/socket/socket.c

Openssl 1.1.0 handles this initialization internally. Leaving the calls in
place causes "undefined reference" errors if openssl was built with
`--api=1.1.0`.
X-Gentoo-Bug: 604576
X-Gentoo-Bug-URL: https://bugs.gentoo.org/show_bug.cgi?id=604576

Disable deprecated initialization for openssl 1.1.0

---

libr/core/cmd_anal.c

Checking for '*' and ' ' only prevented the command agcj from working

Fix agcj not being executed

---

libr/anal/p/anal_arm_cs.c

this fixes #6387
For simplicity's sake, this ignores the overflow semantics of the add in the addressing, as I could not find any good documentation on them.

[anal] arm->esil: handle memindex register in ldr instruction

---

libr/anal/p/anal_avr.c

When adding numbers, factor order does not matter, but this patch will silence the warnings emitted by Coverity.

Coverititty is silly

---

libr/anal/d/cc-mips-32

Here is a small fix to a typo discovered while reading calling convention definitions.

mips-32 calling convention typo fixed

---

README.md

Apart examples with `install/update [package-name]` looks a bit clear for me. Should it be inlined instead?

Update README for r2pm usage

---

libr/asm/arch/arm/armass.c

Fix order of opcodes in comparison list to check against `ands` over `and`.
Adds assembly for `orrs`
Fixes #6436

ARM asm Fix #6436

---

shlr/sdb/src/cdb.c
shlr/sdb/src/sdb.c

Backported sdb fixes wrt multiple cdb_init calls (i.e. https://github.com/radare/sdb/commit/fe5c7938615062853a0c31f3216379aa9fb7f962, https://github.com/radare/sdb/commit/cafbe0cd88343fdd3414611720e32fd563804479, https://github.com/radare/sdb/commit/964f7e41c358c937e8d02950643668783354c6db).
Figured you'd be busy so I did it for you.

Allow multiple calls of cdb_init without leaking or failing

---

libr/core/cmd_flag.c

The command `fl` was wrongly passing `str` instead of `arg` to the flag lookup.
This caused the flag lookup to miss (as it gets passed both the flag name and the new value, prefixed with a space), and `fl` to always fail (silently) when changing the length of a flag.
This commit fixes that.

Fix setting flag length with fl command

---

libr/debug/p/debug_native.c

Gets rid of this:
p/debug_native.c: In function 'bsd_reg_read':
p/debug_native.c:674: warning: passing argument 3 of 'ptrace' from incompatible pointer type

Silence warning on OpenBSD by casting to caddr_t.

---

binr/rasm2/Makefile
binr/rasm2/rasm2.c
libr/asm/asm.c
libr/include/r_asm.h

Optionally run SPP over rasm2 assembly input with `-p`(reprocessor) argument
Adds a new function to ease the addition of the optional bool to the massemble function.
Removes SPP integration from rasm2

Move ssp integration to libr/asm.c [FIX #6356]

---

libr/core/p/core_java.c

For the description of "prototypes", Methods and Fields were listed twice.
Previously read:
```
prototypes <jaicmf>               show in JSON, or All,Imports,Class,Methods,Fields,Methods,Fields
```
Should now read
```
prototypes <jaicmf>               show in JSON, or All,Imports,Class,Methods,Fields
```

Fixed small typo

---

libr/anal/p/anal_arm_cs.c
libr/include/r_endian.h

Made STR significantly more functional (there's always more that can be done). Fixed the cpsr bit fields, but a strange problem occurred when cpsr was the last register, so there's a hack for now to add a ghost register. This seemed better than having it not work and breaking everything. Also, many conditionals in ARM ESIL were wrong, so I fixed those (some invalid ESIL [missing commas], some the logic incorrect such as != which takes one argument vs. ==, ! which does the "C" !=). Hopefully I can continue to improve the state of ESIL emulation for ARM.

Overhauled STR, fixed arm reg profile

---

libr/anal/meta.c
libr/anal/types.c
libr/core/cmd_meta.c
libr/core/cmd_type.c

This doesn't fix the metadata test that are currently broken but as far I am concerned I would update the test and go ahead. Isn't important to get metadata info in order of insertion. However, is convenience if the key just at beginning use the direction, in that case the output will be sorted by offsets and is "less" or "grep" friendly and help you to locate stuff more quickly. But it doesn't work quite well or I screwed it up. Will check with time
```
0x080496b4 CCu "[25] va=0x080496b4 pa=0x000006b4 sz=4 vsz=4 rwx=--rw- .bss"
0x08049690 data Cd 4
0x080496a0 data Cd 4
0x080496a4 data Cd 4
0x080496a8 data Cd 4
0x080484b0 string[13] "Hello_world_"
```
The other change while reading your changes @radare are memleaks that I hope won't break anything else but you never know.

Fix sdb update

---

shlr/gdb/src/core.c

When debugging a single-threaded application via GDB Serial protocol
some GDB servers (notably OpenOCD) do not support vCont command, so
neither step nor continue work. Even though current protocol
description deprecates plain "s" and "c" it does so only for
multi-threading cases.
Signed-off-by: Paul Fertser <fercerpav@gmail.com>

gdb: use simple packets instead of vCont for single-threaded

---

libr/core/file.c
libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_debug.c
libr/threads

Fixes bad behaviour with "doo" command.
```
$ r2 -d test
Process with PID 18765 started...
= attach 18765 18765
bin.baddr 0x00400000
USING 400000
Assuming filepath /home/oscar/lab/r2/6507/test
asm.bits 64
-- Your project name should contain an uppercase letter, 8 vowels, some numbers, and the first 5 numbers of your private bitcoin key.
[0x7f292fa9a190]> dc
Selecting and continuing: 18765
da da da
PTRACE_EVENT_EXIT pid=18765, status=0x0
[0x7f292f7a82e9]> doo popeyemarino
Wait event received by different pid 18765
Process with PID 18766 started...
File dbg:///home/oscar/lab/r2/6507/test  popeyemarino reopened in read-write mode
= attach 18766 18766
Assuming filepath /home/oscar/lab/r2/6507/test
[0x7f6b81f52190]> dc
Selecting and continuing: 18766
popeyemarino
PTRACE_EVENT_EXIT pid=18766, …
```

Fix: #6507

---

libr/util/num.c

Fix https://github.com/radare/radare2/issues/6528 - Display 1M as 1M instead of 1024k.
Also fix same issue for 1K and 1G.

Fix #6528 - Display 1M as 1M instead of 1024k.

---

libr/core/cmd.c

The code in libr/core/cmd.c removed character before '>' redirection operator
regardless of whether it was fd or H flag (for HTML) output.

Fix #6524 - Character before redirection operator '>' acknowledged

---

libr/core/anal_tp.c
libr/core/cmd_anal.c

Making type matching works on each basic block on its own thus
increasing code coverage.
Also reducing the verbosity level
~~Known issues:- still long list of 0x0 & 0x1 that I can find where do they come from~~ Fixed

enhancing aftm

---

libr/core/cmd.c

Made the redirection operator more bash-like.

Ammendmend to fix #6524 - Redirects of fd needs space before '>' (just like in bash)

---

libr/util/print.c

This fixes a typo in the hexdump view introduced in c176c48ffccd4d470add516c137a550dff241901.

Fix "commment" typo

---

libr/anal/p/anal_arm_cs.c

This should make afva recognise arm variables again
tests fixed here too 
https://github.com/radare/radare2-regressions/pull/677

reorganizing opcode for arm

---

libr/core/file.c
libr/debug/debug.c
libr/debug/p/native/linux/linux_debug.c

This commits adds internal breakpoints for **dlopen**, **dlmopen** and **dlclose**.
A proper return reason has been added in linux_dbg_wait , so when typing `di` we can see the reason.
Some things still have to be fixed:
* it prints twice the command stored in `bp->data`.
First it prints the first part of the string (before ";"), and when it does a rcons_flush it prints everything (this issue was already here but i'll take a look).
* To know which library was unloaded more work should be done. We should keep a list of libraries like:
struct library {
ut64 handler;
char *name;
};
The handler field would be the value returned from dlopen/dlmopen (value in rax). Once r2 detects a dbg.unlibs, it should compare all handlers we got so far with the one we're gonna close with dlclose (value …

Add: dbg.libs/unlibs for linux

---

doc/pdb/index.js
libr/core/cconfig.c

Update Microsoft symbol server URL to https://msdl.microsoft.com/download/symbols. This is the default sympath in WinDbg 10.0.14321.

Use HTTPS for Microsoft symbol server URL

---

libr/cons/cons.c
libr/core/disasm.c

The line wasn't resetted to white on windows, that resulted to have the last color on the new line.

Fixed newline color issue on windows

---

libr/core/cmd_debug.c

Fixed wrong commands if not `drp?` cmd

fixed arpi/arp./arpj/arps cmds

---

libr/core/cmd_project.c

That changes behavior of Ps such that if no argument specified, it uses the current project, so that the project is saved (instead of ignoring the command).
I vaguely remember that this used to be the behavior in the past? This tripped me up causing me to lose a few hours of progress :(

Use current project as default for Ps

---

libr/parse/p/parse_mips_pseudo.c

This should patch also https://github.com/radare/radare2/issues/6001

[MIPS] Patched nonspaced instructions (like syscall)

---

sys/install-su.sh

did work today :), I might add pfexec if some machine is given.
greetings to zlul :p

create sys/install.sh with su and correct quotes

---

mk/wasm.mk
sys/wasm.sh

Via dockcross/asmjs/emscripten one should be able to compile WASM almost right away, according to this short article:
https://hackernoon.com/how-to-get-a-performance-boost-using-webassembly-8844ec6dd665#.s5oa3sisk
Unfortunately the portable emsdk bundled with dockcross is not yet at the edge for this:
```
[romanvg:/work] $ emcc fibonacci.c -Os -s WASM=1 -s SIDE_MODULE=1 -o fibonacci.wasm
WARNING:root:output file "fibonacci.wasm" has a wasm suffix, but we cannot emit wasm by itself. specify an output file with suffix .js or .html, and a wasm file will be created on the side
[romanvg:/work] 1 $ emcc fibonacci.c -Os -s WASM=1 -s SIDE_MODULE=1 -o fibonacci.js  
ERROR:root:fibonacci.c: No such file or directory ("fibonacci.c" was expected to be an input file, based on the commandline arguments …
```

Introducing WebAssembly

---

libr/debug/p/debug_native.c
libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/linux/linux_debug.c
libr/include/r_debug.h
libr/include/r_io.h

I've cleaned up the code of linux_coredump.c, and I've added an offset field for `RDebugMap` structure.
I've also changed a little bit the code of `r_debug_native_map_get` function in order to get the offset and if a map is private/shared.
Since I need this info for generating a coredump, and since it might come in handy for some other things, I thought it's fine.

Add: coredump refactoring + RDebugMap offset field

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/p/debug_native.c
libr/debug/p/native/maps/windows.c
libr/include/r_debug.h

This PR is to pay for the pizza at r2con. Thanks pancake :)
Added new command on Windows:
`dce`: Continue execution (pass exception to program)
Fixed the following commands on Windows:
`.dmm*`
`dmm` (now reports sane paths)
`dmmj` (when used from e.g. r2pipe)
The `dce` command will instruct the debugged process to handle the raised exception (similar to `shift+F9` in OllyDbg). This is especially useful when debugging protected executables and malware that make use of anti-debugging techniques.
`dmm*` did not generate valid commands on Windows. I have found it extremely useful to quickly get the exports of all loaded DLLs by using `.dmm*`.
The `dmm` command worked but its output would include the name of the executable twice.
The `dmmj` command was problematic when scripting r2 from e.g. …

Windows debugger: Added dce command. Fixed dmm commands.

---

libr/core/cbin.c
libr/core/cmd_open.c

s/prioritize/switch to/
The bin object id was called "objid" in obj output, 'id' in `ob` output which already has another field named id, and was called "bin object number" in ?help description and `binobject` in the command example. 
Switched everything to use `objid`, like the json, which is kind of a public schema. 
Also `s/[fd #]/[fd]` and `s/[objid #]/[objid]` to keep things simple.
After:
```
|Usage: ob # List open binary files backed by fd
| ob                 List opened binary files and binobject numbers
| ob [fd # bobj #]   Switch to open binary file by fd number and binobject number
| obb [fd #]         Switch to open binfile by fd number
| ob- [fd #]         Delete binfile by fd
| obd [binobject #]  Delete binary file bu binobject number. Do nothing if only one loaded.
| obo …
```

Clean up o?/ob? and use consistent fieldname 'objid' for obj/ob/obo

---

libr/anal/p/anal_arm_gnu.c
libr/anal/p/anal_bf.c
libr/anal/p/anal_cr16.c
libr/anal/p/anal_ebc.c
libr/anal/p/anal_gb.c
libr/anal/p/anal_h8300.c
libr/anal/p/anal_i8080.c
libr/anal/p/anal_malbolge.c
libr/anal/p/anal_mips_gnu.c
libr/anal/p/anal_msp430.c
libr/anal/p/anal_nios2.c
libr/anal/p/anal_null.c
libr/anal/p/anal_pic18c.c
libr/anal/p/anal_ppc_gnu.c
libr/anal/p/anal_propeller.c
libr/anal/p/anal_riscv.c
libr/anal/p/anal_rsp.c
libr/anal/p/anal_sh.c
libr/anal/p/anal_snes.c
libr/anal/p/anal_tms320.c
libr/anal/p/anal_v810.c
libr/anal/p/anal_v850.c
libr/anal/p/anal_ws.c
libr/anal/p/anal_xap.c
libr/anal/p/anal_xtensa.c
libr/anal/p/anal_z80.c

Grep fail:
```
$ grep -R "struct r_anal_plugin_t" .        
./anal/p/anal_pic18c.c:struct r_anal_plugin_t r_anal_plugin_pic18c = {
./anal/p/anal_propeller.c:struct r_anal_plugin_t r_anal_plugin_propeller = {
./anal/p/anal_mips_gnu.c:struct r_anal_plugin_t r_anal_plugin_mips_gnu = {
./anal/p/anal_z80.c:struct r_anal_plugin_t r_anal_plugin_z80 = {
./anal/p/anal_ebc.c:struct r_anal_plugin_t r_anal_plugin_ebc = {
./anal/p/anal_arm_gnu.c:struct r_anal_plugin_t r_anal_plugin_arm_gnu = {
./anal/p/anal_msp430.c:struct r_anal_plugin_t r_anal_plugin_msp430 = {
./anal/p/anal_snes.c:struct r_anal_plugin_t r_anal_plugin_snes = {
./anal/p/anal_sh.c:struct r_anal_plugin_t r_anal_plugin_sh = {
./anal/p/anal_v810.c:struct r_anal_plugin_t r_anal_plugin_v810 = {
./anal/p/anal_i8080.c:struct r_anal_plugin_t …
```

s/struct r_anal_plugin_t/RAnalPlugin

---

libr/asm/p/asm_x86_nz.c

Fixes group 1 instructions with memory refs are operand 1
Fixes mov instruction to support register based offsets
Fix lea with large values as second operand
Add movsx and movzx ops
FIX #6689 
Regressions: radare/radare2-regressions#698

x86.nz fixes enhancements

---

libr/util/p_format.c

Before:
```
$ r2 - -qc 'Cf 32 2xx;'
0x00000000 [0] {
}
0x00000008 [1] {
}
0x00000020 [0] {
}
0x00000028 [1] {
}  
```
After
```
$ r2 - -qc 'Cf 32 2xx;'
```
Closes #6659

r_print_format should be silent in all cases if mode == 0

---

libr/asm/p/asm_x86_nz.c

Prevent infinite loop on visual assembler

---

libr/core/cmd_debug.c

My bad, wrong fix for uninit var warning.
closes https://github.com/radare/radare2/issues/6733
r2r:
https://github.com/radare/radare2-regressions/pull/701

Fix dcu regression

---

libr/bin/bin.c
libr/bin/format/elf/elf.c

Dent in https://github.com/radare/radare2/issues/6642.
- Keep memory ∝ |symbols|, not file size
- Fuse loops
- Don't do Realloc on (Almost) every iteration
- Realloc when finisihed to release extra mem
- Avoid an extra read of entire (1GB) file.
Still 100x too slow from practical and still takes 4x memory than is needed.
this remove allocation that is size of file that live only very short time, instead only allocate what is needed for symbol table parse.

Optimize ELF Symbol loading

---

libr/core/cmd_print.c
libr/util/str.c

Half of fix for #6659 
Other half is #6684. 
Merge together with https://github.com/radare/radare2/issues/6681
New regression tests for this syntax check:
https://github.com/radare/radare2-regressions/pull/696
Before:
```
$ r2 - -qc 'pf 16 16' # or 'pf 16 xx'
0x00000000 [0] {
}
0x00000000 [1] {
}
0x00000000 [2] {
}
0x00000000 [3] {
}
0x00000000 [4] {
}
0x00000000 [5] {
}
0x00000000 [6] {
}
0x00000000 [7] {
}
0x00000000 [8] {
}
0x00000000 [9] {
}
0x00000000 [10] {
}
0x00000000 [11] {
}
0x00000000 [12] {
}
0x00000000 [13] {
}
0x00000000 [14] {
}
0x00000000 [15] {
}
```
After
```
$ r2 - -qc 'pf 16 16'
Usage: pf [0|cnt][format-string]    
$ r2 - -qc 'pf 16 xx'
Usage: pf [0|cnt][format-string] 
```

Enforce pf syntax

---

libr/bin/bin.c
libr/include/r_util/r_buf.h
libr/util/buf.c

https://github.com/radare/radare2/issues/6642
https://github.com/radare/radare2/pull/6719
reduce peak maximum mem during load. This introduces R_API function. 
For 1GB file:
before
After
steal too copies too many...

Add r_buf_set_bytes_steal to eliminate copying

---

libr/cons/grep.c

e scr.html=true doesn't print spaces as &nbsp; and thus it looks messy because the maximum spaces sequence allowed in html is 1. 
Therefore we should change every space to &nbsp;. 
In addition, fixed a problem with <br /> printing. \n (a new line) was printed instead and it doesn't consider as line-break in the majority of editors. Therefore now it avoids printing new line and prints <br /> instead.

Add &nbsp; to html output and fix <br />

---

libr/core/Makefile
libr/core/cmd_project.c
libr/core/project.c

`Pnx` will parse the current project notes with SPP and execute any line starting with `:` interpreting them as r2 commands.

Add Pnx command for project notes

---

libr/asm/p/asm_x86_nz.c

x86.nz infer bits from register names

---

binr/ragg2/ragg2-cc

This might break OSX < Sierra. Works on MacOS 10.12.2, LLVM version 8.0.0 (clang-800.0.42.1) x86_64-apple-darwin16.3.0

Uses correct TEXT section name as of Sierra, fixes #6797

---

libr/bin/format/pe/pe.c
libr/core/cbin.c
libr/include/r_util/r_sys.h
libr/util/w32-sys.c

This pull request fixes #5348. Instead of looking for r2's `share` directory in the working directory, r2 will now _additionally_ look for its `share` directory in the directory where the r2 binary lives. This fix only applies to Windows, which does not honor POSIX path conventions.

Improve Windows search path for sdb

---

libr/anal/xrefs.c
libr/core/cmd_anal.c
libr/include/r_anal.h

Ref: #6795
The issue apparently was a strchr() in libr/core/cmd_anal.c which was making us skip past the supplied address.
Also needed to write a r_anal_refs_get() function in libr/anal/xrefs.c to get "refs" instead of "xrefs" for an address.

Probably fixed: ax- not working (#6795)

---

libr/bin/p/bin_avr.c

- If the initial instructions (interrupt vector) are not `rjmp` try with `jmp`. 
- some rhme2 challanges had data between the interrupt vector and the entry point, so IMHO it's better to avoid making assumptions about the instruction preceding the entry point.
Added also a test (to be merged after this PR: https://github.com/radare/radare2-regressions/pull/718)
This fixes https://github.com/radare/radare2/issues/6868

Fix #6868 - avr bin check_bytes

---

libr/core/cmd_anal.c

It used to run from current offset, leading to different results of `aaa` depending on "where" it is run. In this way is more seek-independent.

Fix aaa - let aac pass to run from $S

---

libr/core/cmd.c
libr/core/cmd_help.c
libr/core/cmd_print.c

Fixed some commands help #6766

---

libr/bin/format/pe/pe.c
libr/include/r_util/r_pkcs7.h
libr/include/r_util/r_x509.h
libr/util/r_pkcs7.c
libr/util/r_x509.c

@Maijin it fixes the `signature.exe` cms data `iC` output (and also any 4096 bits signatures)

Refactoring CMS/PKCS#7 and better use of the memory

---

libr/asm/p/asm_tricore.c

something was still wrong, but finally works.

Fixed tricore byte copy. (FIX #6882)

---

libr/parse/parse.c

Fix findNextNumber() in r_parse when scr.color=false

---

libr/core/cbin.c

sdb_fmt is limited to 256 chars, which produced invalid json (missing ")
with symbol names longer than 254 characters.

Fix irj output for long symbol names

---

libr/core/cmd_write.c

Or, possibly, writing to the wrong place. Who knows. All the other writes require an explicit seek before writing.
Also, r_core_block_read() is needed to reflect the written changes. I went ahead and added that to "wf -" which was missing it too.

cmd_write: fix w0 not doing anything

---

binr/radare2/radare2.c

This should do the trick. Also, I applied the r_file_is_regular function to the 2 firsts files as it is used a few lines below.

(Fix #6927) Added info about loaded config files when R_DEBUG is set

---

libr/anal/anal.c
libr/core/canal.c
libr/core/cmd_anal.c
libr/parse/parse.c

Work in progress, need comments.
With some work, this would fix #6402 and #6819.
Is this the right way to go though? Or should this check be inserted in another place?
Obvious issues/ caveats with the code right now -
1) Only supports x86 / x86_64
3) Output for bins/elf/redpill is currently as below. Will look into how r2 understands these are strings.
```
$ r2 redpill
[0x00000f40]> e anal.strings = true
[0x00000f40]> aa
[0x00000f40]> aae
...
[0x00000f40]> axt 0x00001d89
data 0x00001457 lea eax, [esi - 0x2277] in main
[0x00000f40]> axt 0x00001da0
data 0x0000148e lea eax, [esi - 0x2260] in main
...
```
4) Line 3421 in canal.c and the part before that. Using this temporary solution because values pushed on stack (like PC) during ESIL emulation are not really stored...

get_pc_from_stack for computed refs

---

libr/anal/fcn.c

This is a first attempt at fixing the referenced issue.
`afll` now shows the correct stack frame size instead of zero.

(Partially fix #6923) use op.stackptr instead of op.val for stack frame size guessing.

---

libr/include/r_util/r_asn1.h
libr/util/r_asn1.c
libr/util/r_pkcs7.c
libr/util/r_x509.c

Fixed bugs (#6908 #6909 #6911)
Here is the list of the binaries tested:
```
heap-buffer-overflow-2ce-030-5a6
heap-buffer-overflow-657-030-5a6
heap-buffer-overflow-657-26e-dc4
heap-buffer-overflow-ad2-d00-020
heap-buffer-overflow-fc3-0b5-0a6
heap-buffer-overflow-fc3-183-0a6
heap-buffer-overflow-fc3-220-6d2
heap-use-after-free-c05-e7c-e7c
SEGV-341-892-d00
SEGV-8f6-98a-f0e
SEGV-989-98a-f0e
SEGV-a94-0b5-0a6
SEGV-a94-220-6d2
SEGV-b7b-c17-f10
SEGV-b7b-c17-f10
SEGV-d26-f76-98a
SEGV-d8f-f76-98a
```

Fixed SIGSEGV, fixed heap buffer overflow, heap use after free

---

libr/asm/arch/arm/armass.c

I've re-implemented the `BL` opcode in Thumb mode according to this document here: [THUMB Instruction Set](https://ece.uwaterloo.ca/~ece222/ARM/ARM7-TDMI-manual-pt3.pdf) at section __5.19__ where it described the *long branch with link*.
Now if we do:
```
rasm2 -aarm -b16 "bl -0x2a"
```
We finally get `fff7e9ff` instead of `ffffd647`

Fix BL for arm thumb

---

libr/core/project.c

There was already a warning when opening the project directly from the command line but not when calling `Po`.

Added warning when loading project with different binary

---

libr/asm/arch/arm/armass64.c

Implements `orr` with registers (32 and 64) and immediates (not yet with rot values for registers)
FIX #6611

implement ORR for arm64 FIX #6611

---

libr/core/graph.c
libr/include/r_cons.h

This should fix problems shown [here](https://asciinema.org/a/1gdfbels3gy21kznsgjllcnrj). Mini nodes are handled (almost) in the same way either they were individually made mini with the 'y' key or the whole graph is made mini.

Fix mini nodes

---

libr/core/cmd_print.c

RAnalBlock::size has type `int` which usually isn't 64 bits in size.

Using %d instead of %PFMT64d for RAnalBlock::size in cmd_print

---

libr/core/disasm.c
libr/util/str.c

This improves the printing of strings in the disassembly that contain newlines in them and are not flags.  
While analysing 2 different ARM firmware images I found that important strings that contained newlines were not showing up in the disassembly. This code replaces the newline characters of a string that is not a flag with dots using the existing r_str_filter function. I chose to replicate the r_str_is_printable function in str.c (rather than modify it) with a further check for the newline characters and then filter them out in disasm.c. I felt this would have the smallest impact on the codebase for any potentially unexpected results. I have also written a regression test in the arm_16 test as that is where I had triggered this issue.
This also relates to an already merged pull …

Adds the ability to print filtered strings in the disassembly that are not flags and contain newlines

---

libr/anal/p/anal_x86_cs.c

`pop dword [eax]` produces esil like `esp,[4],eax,[4],=,4,esp,+=` on master, which isn't executable as it would have evaluated involving `num = num`.
It **should** produce `esp,[4],eax,=[4],4,esp,+=` when the destination is a mem operand.
This should be a solid fix, but I don't know if there are any tests to run and compare against. I didn't see an open issue for this either, so I figured just putting up a PR would be better :)

Fix incorrect assignment in esil for x86 pop /m

---

binr/radare2/radare2.c

- Fixed detach from debugger on windows when u tell to radare2 dont kill process on exit #7040
- Only work for process debugged via attaching pid (see comment at #7040)

fixed detach debugger on windows at radare2 exit

---

libr/core/cmd_debug.c
libr/core/cmd_print.c
libr/core/cmd_type.c

This simple PR fixes typos in help messages.
For the record, the following looks incorrect but I don't know how to fix it:
> afta  Setup memory and analyse do type matching analysis for all functions

Typos in help messages fixed

---

libr/bin/format/pe/pe.c
libr/bin/format/pe/pe.h
libr/bin/format/pe/pe64_write.c
libr/bin/format/pe/pe_write.c
libr/bin/p/bin_pe.c
libr/bin/p/bin_pe64.c
libr/bin/p/bin_write_pe.c
libr/bin/p/bin_write_pe64.c
libr/bin/p/pe.mk
libr/bin/p/pe64.mk

Hi,
I'm working on adding support for writing PE32(+) section permissions (see #921).
The patch works fine so far (it's mostly adapted from the ELF code), but I've seen that sections that do not have a name get one auto-assigned. `bins/pe/normal64.exe` is an example of this:
```
[Sections]
idx=00 vaddr=0x00401000 paddr=0x00000200 sz=512 vsz=4096 perm=m--wx name=sect_0
```
Here `sect_0` was autogenerated and is not actually in the file. This is a problem when trying to modify the section permissions, as the code checks the raw names from the binary and not the ones radare "sees". So to change the permissions one would have to invoke rabin2 like this: `rabin2 -O p//x normal64.exe` (i.e. with empty section name). It works, but it's not pretty and also fails when there are multiple unnamed …

Support writing PE32/PE32+ section permissions

---

Makefile
libr/core/cmd_seek.c
libr/core/visual.c

This patch introduces "silent seek" to seek at an address/register avoiding polluting the seek history.
It also uses "ssr" and "ss" in the visual mode, where there was a bug with undo/redo functionality because of the wrong seek history.

Silent seek

---

libr/core/cmd_print.c

Prefer references to `str.*` flags than naked strings when both are present, because the latter might have been guessed incorrectly from ascii-looking bytes in stored pointers.
This breaks few tests, fixed in https://github.com/radare/radare2-regressions/pull/764

Fix pds string references

---

libr/core/graph.c

- keep it true in summary mode, to avoid killing "pds" strings parsing
- restore it back to its original value

Fix cmtright handling in graphs

---

libr/anal/p/anal_6502.c
libr/anal/p/anal_snes.c
libr/asm/arch/6502/6502dis.c
libr/asm/arch/snes/snes_op_table.h
libr/asm/arch/snes/snesdis.c
libr/asm/p/asm_snes.c
libr/asm/p/asm_snes.h

This (admittedly very hacky) pull request tries to make sure the disassembler and analyzer handles X and M flags, which determine whether the X/Y registers and the accumulator are 8 or 16 bits long, properly.
Whenever either the disassembler or the analyzer sees a "rep" or "sep" instruction that would have modified the X and M flags on a real 65816 CPU, it sets an internal flag that makes sure the following instructions are processed with proper register length.
This is especially important when handling instructions that load data with immediate addressing (the value is specified in bytes following the opcode) or when comparing registers with an immediate value, as length of these instructions is influenced by the flags' values.

SNES: try to tell apart register lengths

---

libr/anal/p/anal_snes.c
libr/asm/p/asm_snes.c

Mark plugin functions and variables as static to avoid polluting the global space

Fix multiple definition of 'snesflags' in static build

---

libr/core/cmd_debug.c
libr/debug/Makefile
libr/debug/debug.c
libr/debug/dreg.c
libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h
libr/include/r_reg.h
libr/reg/arena.c
libr/reg/reg.c

Add new reverse single step command 'dsb'.
To execute it, firstly we need save trace session using 'dts+' command.
'dts' command manages trace sessions which have each register and memory state at the moment.
After that, 'dsb' command seeks program counter to backward. (i.e. reverse single step)
Internally, 'dsb' command finds previous trace session and restore all status and then, 
execute forward until desired point.
This implementation is same as that of mozilla's rr. ( https://mail.mozilla.org/pipermail/rr-dev/2017-March/000473.html )
future work
- More optimization
- Read session log that created by other tools
(but, qira has hard-coded address in log, and rr has no deterministic inputs in log. What should I do?)
- Page permission problem
(when dsb command execute to backward across …

Add reverse singlestep command 'dsb'

---

libr/asm/p/asm_x86_nz.c

For instructions with `rsp` reg as first operand
FIX #7137

Fix bad 64 bit assembly for group1 ops

---

libr/core/canal.c
libr/core/disasm.c
libr/parse/parse.c
libr/util/print.c

```
[0x08048320]> e anal.strings = true
[0x08048320]> aa
[0x08048320]> aae
[0x08048320]> pdf @ main
...
│           0x08048427      e824ffffff     call fcn.08048350
│           0x0804842c      81c3d41b0000   add ebx, 0x1bd4
│           0x08048432      8d83e0e4ffff   lea eax, str.Hello_PIC_     ; "Hello PIC!" @ 0x80484e0
...
```

Added display of strings in disassembly for PIC binaries

---

libr/parse/parse.c

Changes for fixing `ahi s` had introduced another bug which skipped past numbers in `[...]`. Fixed.

Fixed findNextNumber and filter

---

libr/asm/asm.c

buf_asm was redundantly allocated with malloc, then overwritten from a strbuf.

fix memory leak in r_asm_mdisassemble

---

binr/r2pm/r2pm

Fixes alias in radare2rc at r2pm packages like esilburner

Fix #7193 : R2PM_ETCD has an extra "radare2" path

---

libr/core/disasm.c

Fixed the agf segfault in #7125. This PR removes the ds->opstr checks of #7125 and #7140. Now flags are not repeated in comment if already in disasm even if asm.cmtright = false.

Always build ds->opstr before comment

---

libr/core/cmd_info.c

fixes issue #7185 in `i` and `ij`.
Itay

Fix #7185 : Show human size in i

---

libr/asm/p/asm_wasm.c
libr/include/r_util/r_uleb128.h
libr/util/uleb128.c

Added support for the whole instruction set according to version 0x1 (https://github.com/WebAssembly/design/blob/8e5ecc3614135a7da011cc4730e227fcb9021494/BinaryEncoding.md).
Bin support coming soon (see radare2/wasm_dev for current status).

Disasm support for WASM v0x1

---

libr/anal/diff.c
libr/core/canal.c
libr/util/diff.c

Appears to address #3614, reenables actual comparison for radiff2 -g. This appears to have been broken since May.

Radiff graph

---

libr/core/canal.c

JSON was producing an INT for fcn type. With this we get the actual string representation of the type.

json fcn type int to string

---

libr/asm/arch/arm/armass64.c

Also don't crash if too many operands are fed into it
[0x00000000]> e asm.arch=arm
[0x00000000]> pa mrc p15, 0, r0, c1, c0, 0
Only affects arm64
RE: https://github.com/radare/radare2/issues/7128#issuecomment-289209563

Don't segfault if too many operands

---

sys/mingw32.sh
sys/mingw64.sh

Users can use `cv2pdb` to get PDB symbols.
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/radare/radare2/7218)

include debug symbols in windows releases

---

README.md

Lua is not an acronym. Its spelling in README.md should be updated to reflect the official spelling.

Fix spelling of 'Lua' (from 'LUA')

---

libr/asm/arch/arm/armass64.c

It's not possible to assume what an immediate stands for based on its position alone. Just parse it out as a CONSTANT type and infer type within the operator function

Ignore position of immediates in arm64

---

libr/io/p/io_w32dbg.c

-Solved issue #7168
When IO for win32 dbg is created, the fd always is passed to -1, this can cause problems when reloadfile try to locate previous fd, and made wrong selection of pid via "dpa" command.

fixed issue #7168

---

libr/bin/bin.c
libr/bin/format/objc/mach0_classes.c
libr/bin/p/bin_dex.c
libr/core/cbin.c
libr/core/cmd_info.c
libr/core/vmenus.c
libr/include/r_bin.h
libr/include/r_core.h

- a superset of method flags is defined with R_BIN_METH_* constants
- a new field, RBinSymbol->method_flags holds them
- every parser can expose them
- they show up in `ic` commands and VB, either in compact form, JSON and r2 commands
- exposed them for objc and dex
This is meant to close https://github.com/radare/radare2/issues/5467
Added tests in https://github.com/radare/radare2-regressions/pull/796 (to be merged after this)
ObjC Example:
```
$ r2 bins/mach0/TestMethods
[0x100006af4]> icj ViewController~{}
{
"class": "ViewController",
"methods": [
{
"name": "viewDidLoad",
"flags": [
],
"vaddr": 4294993772
},
{
"name": "didReceiveMemoryWarning",
"flags": [
],
"vaddr": 4294993872
},
{
"name": "thisIsAClassMethod",
"flags": [
"class"
],
"vaddr": 4294993852
},
{
"name": "andAnotherOne", …
```

Expose class method's flags

---

libr/core/disasm.c

- fix a NULL dereference on `strstr` happening on `agf` under certain conditions

Bring back NULL checks for ds->opstr

---

libr/debug/p/native/drx.c

For issue #7269 this is the fix:
-Code to manage size=-1 as delete hw breakpoint added.
Previusly to remove hw bp  drx_set is called with -1 at param size. drx_set dont manage -1 sizes.

Fix #7269 - drx-0 not working

---

libr/core/linux_heap_glibc.c

The `free (cnk);` was in the wrong context.

[linux-heap-glibc] moved free to the ritght context

---

libr/core/linux_heap_glibc.c

Now we print the actual size of the malloc_chunk without the overhead.

[linux-heap-glibc] fixed malloc_chunk size

---

libr/debug/p/debug_native.c

Retrieve UID information from kvm interface, and pass it to
r_debug_pid_new() function.

Fix BSD build after 94d85cad32

---

libr/util/str.c

That function emits backslash escaped unicode sequences, so backslashes
should be escaped too. This fixes invalid json issues in /j
Fixes #7282 
Tests https://github.com/radare/radare2-regressions/pull/802

r_str_utf16_encode: escape backslash characters too

---

libr/cons/grep.c

For example, "ii~[2]" didn't filter anything at all because the first row only has one column

grep: Fix ~[x] with x higher than the total number of columns

---

libr/core/cbin.c
libr/core/cmd_info.c
libr/core/cmd_search.c
libr/util/str.c

- revert 5f1efc9d (which adds double escaping with r_str_escape),
- re-apply 1c6a3138 (my previous commit)
- fix the recent commits 69a7e122 and 04ad4dcf to use `r_str_utf16_encode` instead of `r_str_escape` since the former produces "\u0000" and the latter produces "\x00" which is not valid JSON
-----
See this comment for the full rationale https://github.com/radare/radare2/issues/7282#issuecomment-294408136
Behavior of /j with this PR (same as my previous PR, #7288):
```
[0x00000000]> wx 005c
[0x00000000]> /j \x00\\
[{"offset": 0,"id:":0,"data":"\u0000\\"}]
```
Behavior of /j without this PR (current master, wrong)
```
[0x00000000]> wx 005c
[0x00000000]> /j \x00\\
[{"offset": 0,"id:":0,"data":"\\u0000\\"}]
```
Detail on the "not valid JSON" comment above, using node 7.7.1:
```
> …
```

Fix escaping of JSON unicode literals

---

libr/core/cbin.c

Bug fix when printing exports.
If the first exported symbol occurs *after* a non-exported symbol (i.e. `exponly && !isAnExport (symbol)` returns `true`), then `iter->p` will be non-`NULL`. This causes a "," to be printed *before* the first element of the JSON list, which is not valid JSON.

Fix JSON printing of exports

---

Makefile

Delete libr/include/r_version.h in distclean mrproper target so it will
be generated again with the current data

Fix wrong version after sys/build.sh

---

libr/debug/p/debug_gdb.c

This should change nothing, just bring some consistency in
the codebase with others debug plugins.

Use the defined structure for r_debug_plugin_t

---

shlr/gdb/src/messages.c

See handle_vFile in ./gdb/gdbserver/hostio.c in gdb git, and the documentation
https://sourceware.org/gdb/onlinedocs/gdb/Host-I_002fO-Packets.html#Host-I_002fO-Packets
An empty response indicates that this operation is not recognized.
vFile:fstat is not supported by gdb 7.6.1, shipped on RHEL 7, for example.

Do not fail if vFile:fstat is not implemented on the remote side

---

libr/core/disasm.c
libr/util/print.c

`j` should stay put despite the `continue`.

Fixed what caused #7268

---

libr/core/disasm.c

In radare/radare2@d9d83914 the fix for "r_parse_filter output for pc relative addrs when color is involved" broke the ahi command in some contexts.
This (tries to) fix #7315

Fix ahi s regression

---

libr/parse/p/parse_ppc_pseudo.c

* MQ
* XER
* RTCU
* RTCL
* LR
* CTR
* DSISR
* DAR
* DEC
* SDR1
* SRR0
* SRR1
* VRSAVE
* TBRL
* TBRU
* SPRG0
* SPRG1
* SPRG2
* SPRG3
* EAR
* TBL
* TBU
* PVR
* SPEFSCR
* IBAT0U
* IBAT0L
* IBAT1U
* IBAT1L
* IBAT2U
* IBAT2L
* IBAT3U
* IBAT3L
* DBAT0U
* DBAT0L
* DBAT1U
* DBAT1L
* DBAT2U
* DBAT2L
* DBAT3U
* DBAT3L
* UMMCR0
* UMMCR1
* UPMC1
* UPMC2
* USIA
* UPMC3
* UPMC4
* MMCR0
* PMC1
* PMC2
* SIA
* MMCR1
* PMC3
* PMC4
* SDA
* DMISS
* DCMP
* HASH1
* HASH2
* IMISS
* ICMP
* RPA
* IABR
* DABR
* ICTC
* THRM1
* THRM2
* THRM3
* PIR

[PPC] added more standard special purpose registers to pseudo

---

libr/core/disasm.c

__r_core_disasm_pdi__ calls __r_parse_filter__ after __r_print_colorize_opcode__,
this produces incorrect output when we use **pdi** with ahi 2.
before pull:
```  
$ r2 malloc://16
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=64
[0x00000000]> wx 48b96e74646c6c2e646c
[0x00000000]> ahi 2
[0x00000000]> pi 1
movabs rcx, 'ld.lldtn'
[0x00000000]> pdi 1
0x00000000 48b96e74646c6c2e646c  movabs rcx, 0x6c642e6c6c64746e
```
after pull:
```
$ r2 malloc://16
[0x00000000]> e asm.arch=x86
[0x00000000]> e asm.bits=64
[0x00000000]> wx 48b96e74646c6c2e646c
[0x00000000]> ahi 2
[0x00000000]> pi 1
movabs rcx, 'ld.lldtn'
[0x00000000]> pdi 1
0x00000000 48b96e74646c6c2e646c  movabs rcx, 'ld.lldtn'
```
Second commit in pull with some refactoring for simplifying r_core_disasm_pdi.

fix for pdi with ahi 2

---

libr/config/config.c
libr/core/cconfig.c
libr/core/cmd_eval.c
libr/include/r_config.h

Added ev and evj command:
```
user@linuxdev radare2-dev $ ./binr/radare2/radare2 --
-- Find hexpairs with '/x a0 cc 33'
[0x00000000]> ev dbg.bta
dbg.btalgo = fuzzy ; Select backtrace algorithm [default, fuzzy, anal]
[0x00000000]> e dbg.btalgo=?
default
fuzzy
anal
[0x00000000]> evj dbg.bt
[{"name":"dbg.btalgo","value":"fuzzy","type":"str","desc":"Select backtrace algorithm","ro":false,"options":["default","fuzzy","anal"]},{"name":"dbg.btdepth","value":128,"type":"int","desc":"Depth of backtrace","ro":false}]
[0x00000000]> e?
|Usage: e [var[=value]]Evaluable vars
| e?asm.bytes     show description
| e??             list config vars with description
| e|ej            list config vars (in JSON)
| e-              reset config vars
| e*              dump config vars in r commands
| e!a …
```

Added ev and evj command

---

libr/anal/p/anal_mips_cs.c

Completes analysis for likely branches.
Old:
```
> e asm.arch=mips
> e cfg.bigendian=true
> pad 54c00005
bnezl a2, 0x18
> pae 54c00005
```
New:
```
> e asm.arch=mips
> e cfg.bigendian=true
> pad 54c00005
bnezl a2, 0x18
> pae 54c00005
0,$ds,>,?{,$$,1,TRAP,BREAK,},a2,zero,==,$z,!,?{,24,$jt,=,1,$ds,=,}
```

Add MIPS branch likely variants to MIPS CS analysis

---

libr/core/disasm.c

`flag_printed` not used anywhere else.

Don't repeat flag in comment if already in disasm (CALL/MOV)

---

libr/core/cconfig.c

Changed lots of config nodes to use new config options with SETOPTIONS. Like:
```
user@linuxdev radare2-dev $ ./binr/radare2/radare2 --
-- Wait a moment ...
[0x00000000]> e asm.emuskip=?
Skip metadata of given types in asm.emu:
d = data
c = code
s = string
f = format
m = magic
h = hide
C = comment
r = run
Concatenation of meta types encoded as characters.
Default is 'ds' to skip data and strings.
[0x00000000]> ev asm.emuskip
asm.emuskip = ds ; Skip metadata of given types in asm.emu [d = data, c = code, s = string, f = format, m = magic, h = hide, C = comment, r = run]
[0x00000000]> ev asm.arch
asm.arch = x86 ; Set the arch to be used by asm [6502, 8051, arc, arm.as, arm, arm.gnu, arm.winedbg, avr, bf, cr16, cris, dalvik, dcpu16, ebc, gb, h8300, hppa, i4004, i8080, java, lanai, lh5801, …
```

Followup changes in cconfig.c to utilize SETOPTIONS for config nodes

---

libr/bin/filter.c
libr/core/cbin.c
libr/include/r_bin.h

- the duplication count is stored in RBinSymbol and used when emitting flags
- for class method names this duplication count is ignored, since the flag generation already prepends the class name to account for uniqueness
- bring back the duplication count for obj. / loc. / sym. flags and in is*
- in all other places (lists, midflags, ic, etc) the "real" names are shown instead
Related test changes: https://github.com/radare/radare2-regressions/pull/831

Fix: avoid modifying symbol names in bin/filter

---

libr/anal/esil.c
libr/anal/p/anal_arm_cs.c

I did this because https://github.com/radare/radare2/commit/7c96bca8095ca380e9770b02b53ddbc3a5cddedd broke my `csel` test (https://github.com/radare/radare2-regressions/blob/master/t.esil/arm-64#L553) and it turns out the reason is `esil_sub` didn't set `esil->cur` and `esil->lastsz` properly.
/cc @XVilka

Add internal flags setting for esil_sub

---

libr/include/r_util.h

Since fa671b9a162cce32e13b0186066b709d7ce4734e the order of includes in `libr/includes/r_util.h` appears to break `--with-openssl` builds since `BIGNUM` is not already defined by the time it is used in `r_big.h`.
Edit: Not sure if build with OpenSSL is even useful or not, but PKGBUILD in ArchLinux AUR uses that flag.

Reorder includes to provide missing BIGNUM definition

---

libr/core/cmd_anal.c

minor bug fix, errant 'break' was causing documentation never to be printed for 'afi'

errant 'break' was causing documentation never to be printed for 'afi'

---

libr/bin/p/vsf.mk

There was an _unneeded message_ (literally, "FUCKOFF") in one of the makefiles. I don't think that it was intended for that line to be commited to the repo, so I've deleted it.

Removed unneeded message (profanity) from build system

---

libr/core/cmd_anal.c

Instead of staying silent (which can cause an error when using r2pipe and it is expecting JSON data) print an empty list when no cross references exist to/from an address.

Print an empty JSON list when there are no xrefs

---

README.md

According to the Lua website,[1] only the first letter of "Lua"
should be capitalized, so do the same here in README.md.
[1] https://www.lua.org/about.html

Fix capitalisation of "Lua" in the readme

---

libr/core/cmd_section.c

I find that this is useful when I am working with r2pipe. I couldn't decide if "S.j" or "Sj." was more appropriate, any thoughts? Likewise if you don't think this is useful, please let me know :)

Added command to print current section in JSON

---

libr/core/cmd_project.c
libr/core/project.c

Goes along with https://github.com/radare/radare2-regressions/pull/843
prj.name should be set before saving the project, so it will be correct in the project file.
The resetting if the save fails is not beatiful, but I don't really know a better way in this case.

Set prj.name before saving a project to save that value correctly

---

libr/core/linux_heap_glibc.c
libr/include/r_heap_glibc.h

Limit to 0x80 size at fastbin in 64 bits and 0x40 in 32 bits according variable max_global_fast

max_global_fast

---

libr/anal/p/anal_xtensa.c
libr/asm/arch/8051/8051_disas.h
libr/asm/arch/arm/winedbg/be_arm.h
libr/asm/arch/cr16/cr16_disas.h
libr/asm/arch/ebc/ebc_disas.h
libr/asm/arch/h8300/h8300_disas.h
libr/asm/arch/include/xtensa-isa.h
libr/asm/arch/msp430/msp430_disas.h
libr/asm/arch/tms320/c55x_plus/ins.h
libr/asm/arch/tms320/tms320_dasm.h
libr/asm/arch/v810/v810_disas.h
libr/asm/arch/v850/v850_disas.h
shlr/bochs/include/libbochs.h
shlr/bochs/src/libbochs.c
shlr/wind/iob_pipe.c

- Exposed some functions as R_API to can link ANAL vs ASM/p
- Fixed libbochs to always use multibyte structs.
- Fixed wind to alway use multybyte apis and include r_types.h to avoid set preprocessor directive __WINDOWS_

add changes to compile more plugins into msvc

---

libr/core/linux_heap_glibc.c
libr/include/r_heap_glibc.h

This PR implements the dynamic resolution of the `global_max_fast` symbol. This is needed because with `mallopt` is possible to configure the `malloc`/`free` to influence it's behaviour, for example configuring the `M_MXFAST` flag.

[linux_heap_glibc] Implemented dynamic global_max_fast resolution

---

libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h

This patch add new diff-style format of memory snapshot.
User can save current memory snapshot by 'dms' command as before.
But internally, **only different memory page** from previous snapshot is saved, instead of entire memory area. It makes all snapshots memory-efficient.
Implementation:
This diff-style format consists of two components, 'RDebugSnap' and 'RDebugSnapDiff'.
Snap diffs are differences from base snapshot 'RDebugSnap' that has entire memory dump.
When user saves memory snapshot, firstly check If base snapshot have been already existed.
If no, take entire memory dump and create base snapshot.
Otherwise, take only different pages from **previous snapshot** (It can be base snapshot or diff snapshot), and create new 'RDebugSnapDiff' and then,
chained to 'RDebugSnap->history'. …

Add diff-style memory snapshot

---

libr/parse/p/parse_x86_pseudo.c

see #7536 
refine varsub for att syntax and a little bit of refactoring to reduce code duplication.
Currently this only works on common case, but produce incorrect names when arguments like "0x16(%rbp)" and "-0x16(%rbp)" both exists. (intel syntax not affected)
So this still need further modifications, please don't merge yet.

refine asm.varsub for att syntax and code refactoring

---

binr/rabin2/rabin2.c

The list of flags to use to achieve the same result as using -g was out of date.

update equivalent flags for -g

---

libr/parse/p/parse_x86_pseudo.c

Sorry I only considered the case where a minus sign is before `oldstr`, actually this should be the correct way to handle that so arguments like `8(%rbp)` and `28(%rbp)` will work too.
Will send PR to r2r to adjust the test later.
EDIT: related to #7538

bug in varsub in att syntax

---

libr/bin/format/elf/elf.c

As described in #7554: WEAK symbols were reported as UNKNOWN. The attached patch fixes it. I only tested on Fedora 25, so I am not sure if this breaks anything else on other platforms.

fix binding reporting for WEAK symbols

---

binr/r2pm/r2pm
doc/fortunes.fun

Should be a bit nicer and more POSIX-y. Works for me!
Tested with FreeBSD `/bin/sh`.
- R2PM_BINDIR
- R2PM_PLUGDIR
- R2PM_GITDIR
- R2PM_DBDIR
- R2PM_USRDIR
Reason: Neatness, organization and multiple r2 installs not interfering with one another, given some env vars.
Motivation: `do it` - @condret

Clean up r2pm code; Allow setting of R2PM_{PLUG,BIN}DIR.

---

libr/core/cmd_debug.c
libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h

**About:**
Add new trace session format, that saved by 'dts+' command.
Trace session is now using new diff style memory snapshots ( #7537 ) 
**Implementation:**
When user try to save trace session, a new memory snapshot, RDebugSnapDiff is created and 
session->memlist points it.
We can also apply trace session at any time. 'r_debug_session_set' function must be used.
This function calls 'r_debug_diff_set' for each memlist to apply diff page to actual memory page.
In 'r_debug_diff_set', at first, we need to role back current memory pages, that have been changed
**after specified diff log**. To do that, we compare 'last_changes' table of the diff file and **latest diff file**.
After that, we apply specified diff file and previous diff files from it.
That's how, we can recover the previous …

Add new trace session format

---

binr/r2pm/r2pm
libr/bin/bin.c

This is my first pull request ever, so nothing special here, the changes should be quite self-explanatory. Feel free to whine about the stuff I broke and how I broke it, as I'm still learning my way around the code.

Fix a simple bug in r2pm; make r_bin_get_size() behavior more intuitive

---

libr/util/lib.c

in order not to block anyone, please find this PR which will make single plugin loading possible again.
this does not make multiple plugins loading possible yet. But at least avoids the seg fault.

temporarly only check handler when using it

---

libr/core/cmd_debug.c
libr/core/cmd_print.c

The cmd_print.c edits mainly help with weird "p-" boundaries appearing e.g. with this:
```shell
echo "o malloc://512\n p-" > script.r2; r2 -i script.r2 --
```
Explicit variable initialization helps with that. 
I also switched the `total` variable type to `RCoreAnalStatsItem` so that its members can be used instead of array indices.

fixes related to p- in cmd_print.c, trivial help msg edit in cmd_debug.c

---

libr/asm/arch/arm/aarch64/aarch64-dis.c

S initialized as unsigned int,
it can not be less than 0x00 but just occurs warning in llvm .

Remove unnecessary comparison

---

doc/bash_autocompletion.sh

Adding the following compatibility commands to this file enables this completion file to be loaded by zsh as well as bash.

Patch to enable zsh completion

---

libr/bin/format/elf/elf.c

Those whose offset are 0 are skipped to avoid overlapping

Fix #7573 - override shdr with phdr symbols

---

shlr/spp/p/spp.h

When `spp.h:20:fread (out + len, 1, 1023, fd)` will executed, segfault will be occurred, becuase `spp.h:15:char *out = (char *)calloc (4096, 0);` will not allocate any memory.

Fix Access of Unallocated Memory on spp.h

---

libr/asm/arch/arm/armass64.c

x is an array and seems [0] is missed,if so must be x[0]=='\0' for checking empty array.

Fix incorrect empty array compersion in armass64.c

---

libr/core/disasm.c

Fixes #5703. Only fixes the immediate issue of asm.leahints comments being in the middle of the disassembly, and does not touch on the comments' correctness.

asm.leahints cmts are now normal cmts

---

libr/core/rtr.c
shlr/gdb/include/gdbserver/core.h
shlr/gdb/include/libgdbr.h
shlr/gdb/include/utils.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/responses.c
shlr/gdb/src/gdbserver/core.c
shlr/gdb/src/utils.c

Added reading registers and memory. So `pd` etc. works.
```
~$ r2 -
[0x00000000]> =g 1234 /bin/ls
= attach 6 6
Process with PID 22868 started...
File dbg:///usr/bin/ls  reopened in read-write mode
= attach 22868 22868
gdbserver started on port: 1234, file: /bin/ls
```
```
~$ r2 -d gdb://localhost:1234
= attach 6 6
-- Charlie! We are here.
[0x7fb27ee07d80]> pd 5
;-- rip:
0x7fb27ee07d80      4889e7         mov rdi, rsp
0x7fb27ee07d83      e8e83d0000     call 0x7fb27ee0bb70
0x7fb27ee07d88      4989c4         mov r12, rax
0x7fb27ee07d8b      8b05c71e2200   mov eax, dword [0x7fb27f029c58] ;
[0x7fb27f029c58:4]=0
0x7fb27ee07d91      5a             pop rdx
[0x7fb27ee07d80]> 
```

Add read reg/mem to gdbserver

---

libr/core/cbin.c

when is json mode and output is empty, and `is_array` is 1, it outputs malformed json something like `{"classes":, "memory":}`. This patch should fixes the regression for "iaj Well-formed" because of https://github.com/radare/radare2/pull/7600. Before that patch the output is valid because `iaj` wasn't actually trying to output info for these three.

fixes format for izj, imj and icj when output is empty

---

libr/asm/p/asm_mips_cs.c

This is an ugly hack, but it's needed for mips64 to work on modern capstone. 
see https://github.com/aquynh/capstone/issues/938
fixes https://github.com/radare/radare2/issues/7611

Workaround capstone bug for mips64 disassembly

---

libr/debug/debug.c
libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h

Renewed dsb command logic for new trace session format. (#7579) 
User must save at least a one trace session by 'dts+' command before execution of 'dsb'.
When user tried to step one back using 'dsb', r2 internally saves latest trace session at that point, and then, 
find previous one, calculate difference between the previous one and latest one, and recover previous program state.

Renewed dsb command for new session format

---

binr/r2pm/r2pm

TARBALL was not set, resulting in saving file as "-c"

fix R2PM_TGZ

---

libr/anal/p/anal_mips_cs.c
libr/asm/p/asm_mips_cs.c

Hello,
the constant `CS_MODE_MIPS2` from the patch against capstone-next in 1c6ee8dd3a will probably not be available in capstone 3. This results in compilation errors:
```
$ ./configure --prefix=/usr --with-syscapstone --with-syszip --with-openssl
...
$ make
...
/home/user/git/radare2/libr/..//libr/anal/p/anal_mips_cs.c:598:12: error: ‘CS_MODE_MIPS2’ undeclared (first use in this function); did you mean ‘CS_MODE_MIPS32’?
mode |= CS_MODE_MIPS2;
^~~~~~~~~~~~~
CS_MODE_MIPS32
```
I added some guards for this case. This will not help if capstone-next is installed at system level and `--with-syscapstone` is used until the patch is merged upstream.

Fix regression with capstone 3

---

libr/core/canal.c

I'm not sure if this is intentional, but when when I try to generate a graph for a "loc" function radare currently returns an empty graph. This is despite commands like `v`, `pdf`, etc. working as expected.
In fact, is the function `type` check required at all? Can it just be removed? I'm not sure why there is this restriction for generating graphs for certain function types when other commands work fine. Please let me know your thoughts!

Make the "ag" command work with "loc" functions

---

libr/core/rtr.c
shlr/gdb/src/gdbserver/core.c

Server -
```
~$ r2 -
[0x00000000]> =g 8000 /bin/ls
= attach 6 6
Process with PID 23131 started...
File dbg:///usr/bin/ls  reopened in read-write mode
= attach 23131 23131
gdbserver started on port: 8000, file: /bin/ls
Breakpoint already set at this address.
Cannot set breakpoint at '0x7f4325bb8d88'
Selecting and continuing: 23131
hit breakpoint at: 7f4325bb8d88
```
Client
```
~$ r2 -e dbg.bpinmaps=false -d gdb://localhost:8000
= attach 6 6
[0x7f4325bb8d80]> pd 3
;-- rip:
0x7f4325bb8d80      4889e7         mov rdi, rsp
0x7f4325bb8d83      e8e83d0000     call 0x7f4325bbcb70
0x7f4325bb8d88      4989c4         mov r12, rax
[0x7f4325bb8d80]> db 0x7f4325bb8d88
[0x7f4325bb8d80]> ds
got signal...
[0x7f4325bb8d80]> pd 3
0x7f4325bb8d80      4889e7         mov rdi, rsp
;-- rip:
0x7f4325bb8d83 …
```

Initial breakpoints, step, and continue for gdbserver. Plus *started* talking to GDB

---

libr/bin/p/bin_mbn.c

aboot.mbn isn't recognized by r2 because the check is too strict,
valid values for load_index (aka image_id) start from 1, aboot.mbn is using 5.
Fixes #7681

mbn: fix image type check

---

binr/rafind2/rafind2.c
libr/core/cmd_anal.c
libr/core/cmd_debug.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/core/linux_heap_glibc.c
libr/core/yank.c
libr/include/r_print.h
libr/io/p/io_r2k_linux.c
libr/util/print.c

Add argument zoomsz to r_print_hexdump(). It allows to specify the real
size of each byte in the hexdump.

Fix hexdump offset in zoom mode

---

shlr/gdb/src/gdbserver/core.c

```
src/gdbserver/core.c:163:16: warning: using the result of an assignment as a condition without parentheses [-Wparentheses]
while (action = strtok (NULL, ";")) {
~~~~~~~^~~~~~~~~~~~~~~~~~~~
src/gdbserver/core.c:163:16: note: place parentheses around the assignment to silence this warning
while (action = strtok (NULL, ";")) {
^
(                          )
src/gdbserver/core.c:163:16: note: use '==' to turn this assignment into an equality comparison
while (action = strtok (NULL, ";")) {
^
==
1 warning generated.
```

fix an unimportant warning (gdbserver/core.c)

---

libr/parse/code.c

remove unused variable (ret) + change type of typename to const char.
```
code.c:36:9: warning: initializing 'char *' with an expression of type 'const char *' discards qualifiers [-Wincompatible-pointer-types-discards-qualifiers]
char *typename = k;
```

remove unused variable + change type of typename (/libr/parse/code.c)

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h

Previous trace session key must be found along with recently recorded sessions.

Changed finding logic of session key

---

libr/cons/cons.c

by keeping the ap argument read-only and use a copy instead, so both copies can be safely ended before returning

Fix CID 1368158

---

binr/radare2/radare2.c
libr/core/cmd_debug.c
libr/core/cmd_open.c
libr/core/rtr.c
libr/debug/debug.c
libr/debug/p/debug_gdb.c
libr/include/r_debug.h
shlr/gdb/include/arch.h
shlr/gdb/include/gdbserver/core.h
shlr/gdb/include/libgdbr.h
shlr/gdb/src/arch.c
shlr/gdb/src/gdbserver/core.c
shlr/gdb/src/libgdbr.c

GDB -
```
~$ gdb
...
(gdb) symbol-file /bin/radare2 
Reading symbols from /bin/radare2...done.
(gdb) set arch i386:x86-64:intel 
The target architecture is assumed to be i386:x86-64:intel
(gdb) target remote localhost:8000
Remote debugging using localhost:8000
warning: No executable has been specified and target does not support
determining executable automatically.  Try using the "file" command.
0x00007f8e637efd80 in ?? ()
(gdb) break main
Breakpoint 1 at 0x55dc32d47835: file radare2.c, line 375.
(gdb) c
Continuing.
Breakpoint 1, main (argc=2, argv=0x7ffe23d2eae8, envp=0x7ffe23d2eb00) at radare2.c:375
375		RThreadLock *lock = NULL;
(gdb) i r
rax            0x55dc32d47815	94404233951253
rbx            0x0	0
rcx            0x0	0
rdx            0x7ffe23d2eb00	140729499446016
rsi …
```

gdbserver rebasing symbols. gdb source-level debugging now works

---

libr/asm/p/asm_arm_cs.c

fix cs_open()-without-cs_close() memory leak in disassemble() by uncommenting //cs_close()

fix memory leak in disassemble()

---

libr/cons/cons.c
libr/util/sys.c
shlr/sdb/src/sdb.c

I don't know if it is "correct" to call malloc(1) but definitely `var = ""` is wrong, since sdb is calling free on it later.

Windows fixes

---

libr/core/core.c

This isn't a complete excision of `scr.echo`; it just removes the bit responsible for #7724.
I gather regression tests are desirable?

Nix forced echo on breakpoint commands (#7724)

---

libr/core/disasm.c

This is based on [C++11 string literals](http://en.cppreference.com/w/cpp/language/string_literal).

Add 'u' prefix to wide UTF-16 strings

---

libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c
shlr/gdb/include/gdbclient/commands.h
shlr/gdb/include/gdbclient/responses.h
shlr/gdb/include/libgdbr.h
shlr/gdb/include/utils.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/responses.c
shlr/gdb/src/libgdbr.c
shlr/gdb/src/packet.c
shlr/gdb/src/utils.c

```
~$ r2 -d gdb://localhost:8000
= attach 6 6
[0x7ffff7ddad80]> dm
sys  32K 0x0000555555554000 - 0x000055555555c000 s -r-x /home/.../radare2/binr/radare2/radare2 /home/.../radare2/binr/radare2/radare2
sys   8K 0x000055555575b000 - 0x000055555575d000 s -rw- /home/.../radare2/binr/radare2/radare2 /home/.../radare2/binr/radare2/radare2
sys 388K 0x000055555575d000 - 0x00005555557be000 s -rw- [heap] [heap]
sys 140K 0x00007ffff7dda000 * 0x00007ffff7dfd000 s -r-x /usr/lib/ld-2.25.so /usr/lib/ld-2.25.so
sys   8K 0x00007ffff7ff8000 - 0x00007ffff7ffa000 s -r-- [vvar] [vvar]
sys   8K 0x00007ffff7ffa000 - 0x00007ffff7ffc000 s -r-x [vdso] [vdso]
sys   8K 0x00007ffff7ffc000 - 0x00007ffff7ffe000 s -rw- /usr/lib/ld-2.25.so /usr/lib/ld-2.25.so
sys   4K 0x00007ffff7ffe000 - 0x00007ffff7fff000 s -rw- unk0 …
```

Support for dm commands in gdb

---

libr/egg/egg_lang.c

When the local variables assignment starts with bit operations, the ragg2 works wrong.
```
$ cat test.r
write@syscall(4);
main@global(128, 128) {
.var0 = 6 & 15 + 1;                 #7
write(1, "123456789abcdef", .var0); #1234567
}
```
```
$ ragg2 -b 32 -a x86 -F -o test test.r
$ ./test
1%
```
The right output should be __"1234567%"__
Fixed, and writing tests now.

Bug fix for rcc_mathop in egg_lang.c

---

libr/anal/p/anal_8051.c
libr/asm/arch/8051/8051_disas.c
libr/asm/arch/8051/8051_ops.h

Added logic in 8051 analyzer to set ptr and val in R_AnalOp structure.
Moved inline functions shared between 8051 anal and disas into include file
One behavior I can't figure out: when ptr itself is a valid ASCII character, pd outputs the character even though op->val is set to -1. Is there a way to suppress that output?
0x0000a2a1      f555           mov 0x55, a                 ; [0x55:1]=0 ; 'U'
[0x0000a2a1]> ao 1
address: 0xa2a1
opcode: mov 0x55, a
mnemonic: mov
prefix: 0
id: 0
bytes: f555
ptr: 0x00000055
refptr: 1
size: 2
type: mov
esil: A,0x10000,85,+,=[1],
stack: null
family: cpu

Set ptr and val to correct values in 8051 analyzer

---

libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c
shlr/gdb/include/gdbclient/commands.h
shlr/gdb/src/gdbclient/core.c

Small fix to [#7807](https://github.com/radare/radare2/pull/7807), and reg caching in gdb (invalidated upon step, continue, attach/detach and reg_write)

gdb reg caching

---

libr/debug/debug.c
libr/debug/session.c
libr/debug/snap.c

Putting end point trace session cause many bugs and confusing.
So end point should be created only time when applying new memory snapshots.

Removed end point trace session

---

libr/core/cmd_print.c

Issue #4903 is due by a transposition of the format and size characters, which is possible in gdb.
This PR extends the functionality of the `x/` command to check the format character and bring it closer to the functionality of the gdb `x/` command.
The behaviour of the count is different than other commands. In this `x/`, the count is a multiple for the size. In other commands (`pxh`, `pxw`, `pxq`, etc), the count is treated as the number of bytes to show. Trailing bytes that do not fit exactly to a multiple of the size are truncated:
`floor(<count> / <size>)`
`pxw 11` shows 2, 4 byte values and truncates the last 3.
**Before change:**
```
[0x00000000]> x/10x str.ABCDEFGHIJKLMNOPQRSTUVWXYZ
- offset -   0 1  2 3  4 5  6 7  8 9  A B  C D  E F  0123456789ABCDEF
0x004005d4  4142 4344 4546 …
```

Add size parsing for 'x/' command

---

libr/bin/p/bin_mach0.c

This fixes a NULL deference happening with the `iC` command.
(Reproduced with an iOS kernelcache.)

[bin_mach0] added NULL check to fix a segmentation fault

---

shlr/gdb/include/gdbclient/commands.h
shlr/gdb/include/libgdbr.h
shlr/gdb/src/gdbclient/core.c

Reporting support for multiprocess and not using vCont causes problems on latest gdbserver, atleast on Arch. This fixes it.

Check which vcont commands and use them if they are

---

libr/core/disasm.c

If `asm.esil` was configured to be true, r2 would add an additional(since esil is provided by default) `esil` key to the output causing json readers to bug out due to "duplicate key".

Removes additional 'esil' from pdj output

---

libr/anal/p/anal_avr.c

A typo of `__generic_sub_update_flags_rr` meant that the generated
code contained the immediate as a register, resulting in the flags
not being set correctly.
After switching this to `_rk` the format of the immediate values were
still incorrect because they were being output as hex without the `0x`
prefix. This was changed to output decimal instead, as that matches the
format of the result value when doing operations like `cpi`. For
example:
cpi r26, 0x2e
46,r26,-,r26,0x08,&,!,46,0x08,&...
The format for the `__generic_add_update_flags` was also fixed, but
as there is currently no `_rk` version it doesn't affect anything.

Fix generated ESIL for AVR flags.

---

libr/core/cconfig.c
libr/core/disasm.c
libr/include/r_util/r_str.h
libr/util/str.c

Useful if you know that there are no wide strings and you don't want false positives from `guess`.

asm.strenc (latin1)

---

libr/core/disasm.c

Fixes the (+) line below by changing it to the (-) line:

Remove | highlight with asm.cmtright=false and call statement

---

libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c

These eprintfs were causing a lot of debug messages, for instance when r2 reads at an invalid address during `pd` to check for refs. We probably shouldn't have so many debug messages for release.
The one for file is because `/proc/pid/maps` will only work for linux, so we shouldn't have that warning on others.

Cleaning up eprintf before release

---

libr/asm/arch/sh/gnu/sh-dis.c

for compilers that default to signed char, wrong values were generated by this cast
example:
```
$ # before
$ rasm2 -a sh -d 'ffc8'
tst 0xFFFFFFFF,r0
```
```
$ # after
$ rasm2 -a sh -d 'ffc8'
tst 0xFF,r0
```

SH disassembler: cast immediate values to unsigned char instead of char

---

libr/anal/p/anal_sh.c

Code comment says it all - since we operate on `pc`, a 64-bit variable (as opposed to the real hardware's 32-bit register), of course we need to sign-extend the extra 32 bits as well :)

properly sign-extend parameters to SH bt/f instructions in analysis

---

libr/cons/cons.c
libr/core/cconfig.c
libr/include/r_cons.h

`scr.breaklines=false`:
`scr.breaklines=true`:
No test since there doesn't seem to be a way to test for this.

scr.breaklines: Break lines in Visual mode instead of truncating them

---

libr/core/cmd_debug.c
libr/debug/session.c
libr/debug/snap.c
libr/include/r_debug.h

dtst saves all trace sessions to binary file. The format of binary file is simple serialized sessions.
dtsf restores all trace sessions from binary file.

Add dtst and dtsf commands for save and restore sessions.

---

libr/core/cmd_debug.c
libr/include/r_reg.h
libr/reg/profile.c

Fix: #4041 
Command is `drp gdb <file>`
`maintenance print register-groups` does not contain information like pc, sp etc.
For now, this takes reg-profile file like drp, but only dumps to stdout. Doesn't set internal reg profile

added drp sub-command to parse gdb reg profile and dump an r2 one

---

libr/core/disasm.c

Output for JSON commands can break when **handleMidFlags()** is called from **r_core_print_dsasm_json()**. **handleMidFlags()** should be called with third argument "false" so that **handleMidFlags()** doesn't print any output and break the JSON.

Fix r_core_print_disasm_json() output with mid flags

---

libr/core/cconfig.c
libr/core/disasm.c
libr/include/r_util/r_str.h
libr/util/str.c

Bringing back dots for unprintable characters. Useful if one deals with only ASCII strings, or to reduce clutter. A bit surprised this wasn't requested tbh.
WIll deal with the repeated `ds_print_str` code later.

asm.strenc (asciidot)

---

libr/anal/p/anal_arm_cs.c

- make the delta depend on the value of `thumb` parameter instead of the op size, because otherwise when 4-bytes-long instructions are present in thumb mode (e.g. `ldr.w`) that delta is computed wrong
The point is: the disassembler output it's still wrong (not only in capstone) but in this way at least the analysis (and ESIL) is correct and can find references
updated tests here: https://github.com/radare/radare2-regressions/pull/913
related to: https://github.com/radare/radare2/issues/7883

Fix pcdelta for arm thumb

---

libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c
shlr/gdb/include/gdbclient/commands.h
shlr/gdb/src/gdbclient/core.c

Haven't yet found how to extract information about a thread from gdb other than dead/not dead. (There is `qThreadExtraInfo` but it is OS specific and reply is not defined in the protocol)
Also in `gdbr_threads_list` I've done `r_list_foreach` at the end to check if thread is dead, instead of within the main loop. The gdb protocol says -
`-> qfThreadInfo` `<- list of threads`
then, repeated `-> qsThreadInfo` `<- next threads`
So thread info is stateful. But there is no explicit guarantee that the state will be preserved if there is another packet between `qsThreadInfo`.

gdb get exec file name, and threads list

---

libr/core/cmd_anal.c
libr/core/core.c

With this fix u can work with registers not flaged and alias register in aritmetic operations:
aer PC=PC+1
aer eip=PC+1
Before this fix u can work with this stuff if registers are flagged, but dont support register aliases.
And now test will be pass.
Also cmd_aea is modified to avoid change context of esil core, now have a own esil instance and save reg arena.

Fixed flag register and aea

---

libr/core/cmd_print.c

Add descriptions for pxx and pxX

---

libr/util/str.c

No test since no change of functionality.

Improve memory efficiency of r_str_escape_ if asciidot

---

libr/core/file.c
libr/debug/debug.c

- Modified r_debug_is_dead, to return true if dbg->reason.tpye is dead.
- Modified r_core_file_reopen, to set dbg->reason.type to NONE when reload a debug program.

fix for #7907

---

libr/debug/debug.c
libr/debug/p/native/w32.c
libr/util/file.c
libr/util/str.c

* Set pid to -1 when the reason is EXIT_PID
* Removed extra newline
* More verbose error message
* Added support to network files (debugger did not work when reopening a file which was remote)

Fixed windows network path (\\server\file.exe) and random err

---

binr/rabin2/rabin2.c
doc/zsh/_r2
doc/zsh/_rabin2
doc/zsh/_radiff2
doc/zsh/_rafind2
doc/zsh/_ragg2
doc/zsh/_ragg2-cc
doc/zsh/_rahash2
doc/zsh/_rasm2

Fix a benign missing fallthrough in rabin2.c
`sed -r` and regex escape sequence `\S` should be avoided as they are non-portable GNU extensions.

Add doc/zsh/{_rabin2,_ragg2,_ragg2-cc}, drop GNU sed dependency from zsh completion files

---

libr/core/disasm.c

Now it shows the string instead of the address, from Hello.dex:
```
{
"offset": 608,
"ptr": 890,
"esil": "0x37a,v1,=",
"refptr": false,
"fcn_addr": 0,
"fcn_last": 0,
"size": 4,
"opcode": "const-string v1, str.Findus",
"bytes": "1a010100",
"family": "cpu",
"type": "mov",
"type_num": 9,
"type2_num": 0
},
```
And that's from master:
```
{
"offset": 608,
"ptr": 890,
"esil": "0x37a,v1,=",
"refptr": false,
"fcn_addr": 0,
"fcn_last": 0,
"size": 4,
"opcode": "const-string v1, 0x37a",
"bytes": "1a010100",
"family": "cpu",
"type": "mov",
"type_num": 9,
"type2_num": 0
},
```
R2R PR: https://github.com/radare/radare2-regressions/pull/920

Fix pDj command in order to show strings

---

libr/core/cmd_print.c
libr/hash/entropy.c

Indent `p=`, fix r_hash_entryopy_fraction (multiplier 256 is changed to 255 to avoid ut8 overflow, avoid ERANGE when calculating log(0), scan data once instead of 256 times)

Fix help for `pi`, add comments to switch cases => case d: // "pid"

---

libr/core/graph.c

The prompt triggered by `|` and `cmd.gprompt` output do not use the default foreground color, which is fixed by this commit.

Fix color of cmd.gprompt

---

libr/include/r2naked.h
libr/include/r_cons.h
libr/include/r_sign.h
libr/include/r_util/r_json.h
libr/include/sdb/sdbht.h

This PR adds `void` in r2 includes. It aims at removing warning when compiling plugins with `-Wstrict-prototypes`.
There are ~50 others similar cases in r2 sources. I can fix them if you think that it is relevant.

Use void in prototypes

---

libr/include/r_util/r_sys.h
libr/util/sandbox.c

When binr/radare2/radare2 was running under a shell (e.g. `env.sh`), they were in the
same process group, pressing ^Z (SUSP) once just suspended radare2 itself, not
including the shell. The commit sends the signal to the whole process
group.

Send SIGTSTP to the process group of r2 when SUSP key is pressed.

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/snap.c
libr/include/r_debug.h

Add new command 'dcb' that can continue backward until hit breakpoint.
When executing 'dcb', at first, get the previous breakpoint, and then, continue until this point.

Add dcb (debug continue back) command

---

libr/include/r_lib.h
libr/util/lib.c

This is useful for dynamically created plugins (e.g. ` r2lang.plugin("asm", r2m2_ad_plugin)`)
`radare2-bindings/libr/lang/p/python/anal.c:Radare_plugin_asm` `strdup` fields for
RAnalPlugin and they are not freed upon `r_lib_close`.
This commit adds `free` to RLibStruct & RLibPlugin with which
plugins can set their custom destructors (to free those `strdup`
fields).

Add `free` to RLibStruct & RLibPlugin.

---

libr/anal/Makefile
libr/anal/meson.build
libr/anal/sign.c
libr/flag/flag.c
libr/include/r_flag.h
libr/include/r_skiplist.h
libr/util/meson.build
libr/util/skiplist.c

I measured the change in time for open + "aa" on the content of my /usr/bin/[a-f]* . Time for most of the executables taking more than 0.5s improved or didn't become worse.
[times.csv.txt](https://github.com/radare/radare2/files/1136856/times.csv.txt)

Speedup nearest flag lookup by using skiplist.

---

libr/anal/esil.c
libr/anal/p/anal_x86_cs.c
libr/anal/types.c
libr/bin/format/elf/elf.c
libr/core/anal_tp.c
libr/core/cmd_anal.c
libr/debug/trace.c

Fix memory leaks in libr/anal/types.c and libr/anal/p/anal_x86_cs.c
`libr/anal/p/anal_x86_cs.c`: use static variable for `op->{dst,src[0]}->reg` because they are not freed in `r_anal_op_fini`.
Also fix a trivial memset bug in `libr/bin/format/elf/elf.c`

Fix memory leaks in libr/anal

---

libr/bin/pdb/pdb.c
libr/bin/pdb/stream_file.c

This should fix https://github.com/radare/radare2/issues/6434
Here is (part of) the output now:
```
$ rabin2 -P ~/win/wdm_harvested.pdb | head                                                                                                                                                                         <pdbb>
Warning: stream_size (3) is 0
Warning: no stream pages. Skipping.
There is no global symbols in current PDB.
LIST_ENTRY64: size 0x10
0x0: Flink type:(member) unsigned long long
0x8: Blink type:(member) unsigned long long
LIST_ENTRY32: size 0x8
0x0: Flink type:(member) unsigned long
0x4: Blink type:(member) unsigned long
_LIST_ENTRY: size 0x10
0x0: Flink type:(member) pointer to struct _LIST_ENTRY
0x8: Blink type:(member) pointer to struct _LIST_ENTRY
_SINGLE_LIST_ENTRY: size …
```

Pdb parsing fixes + typos

---

libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/core.c
libr/include/r_cmd.h
libr/include/r_core.h

It organizes commands as a tree by their names and uses
`r_core_cmd_help (core, desc->help_msg);` currently to show command
candidates.
Type the following command and press `Tab`:
```
% r2 -e cmd.newcomplete=1 --
-- getdruid to get eclectic uid
|Usage: a[abdefFghoprxstc] [...]
| aa[?]            analyze all (fcns + bbs) (aa0 to avoid sub renaming)
| ab [hexpairs]    analyze bytes
| abb [len]        analyze N basic blocks in [len] (section.size by default)
| ac [cycles]      analyze which op could be executed in [cycles]
| ad[?]            analyze data trampoline (wip)
| ad [from] [to]   analyze data pointers to (from-to)
| ae[?] [expr]     analyze opcode eval expression (see ao)
| af[?]            analyze Functions
| aF               same as above, but using anal.depth=1
| ag[?] [options] …
```

Add RCmdDescriptor and cmd.newcomplete for new command completion.

---

shlr/gdb/include/gdbclient/responses.h
shlr/gdb/include/libgdbr.h
shlr/gdb/src/common.c
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/responses.c
shlr/gdb/src/libgdbr.c

Even though lldb-server is supposed to extend gdbserver packets, it actually doesn't handle some basic ones. Like reading registers using `g`.

lldb compatibility [#1] : read registers from lldb-server

---

libr/core/cmd.c
libr/core/cmd_print.c

Add DEFINE_CMD_DESCRIPTOR_SPECIAL to define RCmdDescriptor with special
characters.

`p` commands: move `const char help_msg_*[]` arrays to top.

---

libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/core.c

Fix #8023 
Rename cmd.comphint to cfg.newtab

Suppress warnings in cmd.c and remove unused functions in cmd_{anal,print}.c

---

libr/core/cmd_anal.c

Just a little bug fix which turn this:
Into this:
~cheers

Fix a little bug with log output

---

libr/core/cmd.c
libr/core/cmd_project.c

Press `P Tab`
```
% r2 -e cmd.comphint=1 --
|Usage: P[?osi] [file]Project management
| Pc [file]    show project script to console
| Pd [file]    delete project
| Pi [file]    show project information
| Pl           list all projects
| Pn[j]        show project notes (Pnj for json)
| Pn [base64]  set notes text
| Pn -         edit notes with cfg.editor
| Po [file]    open project
| Ps [file]    save project
| PS [file]    save script file
| P- [file]    delete project (alias for Pd)
| NOTE:        See 'e??prj.'
| NOTE:        project are stored in ~/.config/radare2/projects
[0x00000000]> P
```

`P` commands: move `help_msg_*[]` arrays to top

---

libr/core/cmd.c
libr/core/cmd_section.c

Press `S Tab`
```
% r2 -e cmd.comphint=1 --
|Usage: S[?-.*=adlr] [...]
| S                          list sections
| S off va sz vsz name mrwx  add new section (if(!vsz)vsz=sz)
| S.                         show current section name
| S.-*                       remove all sections in current offset
| S*                         list sections (in radare commands)
| S-[id]                     remove section identified by id
| S-.                        remove section at core->offset (can be changed with @)
| S=                         list sections (ascii-art bars) (io.va to display paddr or vaddr)
| Sa[-] [A] [B] [[off]]      Specify arch and bits for given section
| Sd[a] [file]               dump current (all) section to a file (see dmd)
| Sf [baddr]                 Alias for S 0 0 $s $s …
```

`S` commands: move `help_msg_*[]` arrays to top

---

libr/debug/p/debug_gdb.c
shlr/gdb/include/libgdbr.h
shlr/gdb/src/gdbclient/responses.c

gdbserver might send different stop reason on re-querying, after process dies. So this handles that case.

More fixes for when process dies

---

libr/core/cmd.c
libr/core/cmd_write.c

Follow-up of https://github.com/radare/radare2/pull/7969 and in preparation for #7967

`w` commands: move `const char help_msg_*[]` arrays to top.

---

libr/asm/arch/ppc/libvle/vle.h
libr/bin/format/pe/pe.c
libr/bin/pdb/pdb_downloader.h
libr/util/file.c

-Some bugs fixeds in this little function:
1) If no WINAPI is specified the call is made as cdecl this make a crash...
2) the api used the unicode version and then try to do a strdup from unicode string ... also no unicode string was defined the tmpdir is defined as TCHAR = char ....
-Fixed compilation error under windows for ppc arch, some functions from anal need be R_API.
-Fixed export issue #8044

fix a wrong definition to call GetLongPathName and fix for #8044

---

libr/include/r_socket.h
libr/include/r_types.h
libr/socket/run.c
man/rarun2.1

Or on linux:
```
xarkes:~$ rarun2 rundll=/lib/libc-2.25.so rundll.fcn=system arg1="ls /"
bin   dev         etc   lib    lost+found  opt   root  sbin  sys  usr
boot  EFI_backup  home  lib64  mnt         proc  run   srv   tmp  var
```
As you can see on the screenshot, I am using a tiny hack to pass NULL to the function. I think I should add a format to the getStr() function in run.c so we can pass integers to the functions.
Also I am not very satisfied with the argument functions, I just did 4 to show as an example, should I add more or is there any generic way to handle this ?

Added rundll to rarun2

---

libr/debug/p/debug_gdb.c

This was causing the `= attach <pid> 1` bug

return tid after continue

---

libr/anal/p/anal_v810.c
libr/anal/p/anal_v850.c
libr/asm/arch/v850/v850_disas.c
libr/asm/arch/v850/v850_disas.h

Initial support for ESIL. There are still many things to do for more precise emulation.
Supported instructions:
```
+ ADD
+  ADDI
+  AND
+  ANDI
Bcond
+  CLR1
+  CMP
+  DI
+  DIVH
+  EI
+  HALT
+  JARL
+  JMP
+  JR
LD
LDSR
+  MOV
+  MOVEA
MOVHI
MULH
MULHI
+  NOP
+  NOT
+  NOT1
+  OR
+  ORI
RETI
+  SAR
SATADD
SATSUB
SATSUBI
SATSUBR
SETF
SET1
+   SHL
+   SHR
SLD
SST
ST
STSR
+  SUB
+  SUBR
+  TRAP
+  TST
TST1
+  XOR
+  XORI
```
Will add tests accordingly after finishing support.

NEC V850 - Initial ESIL support

---

libr/anal/p/anal_ppc_cs.c

On a 32-bit x86 computer, examining a PowerPC ELF with the "aa" command caused a segfault in vsnprintf. 
The %llx  (PFMT64x) format attempts to get the next 64 bits from the stack. This will consume the cmask32 and ARG(0) values. The following "%s" will cause a segfault if the next 32 bits is not pointing to readable memory.
I doubt this is the best fix. Maybe libr/include/r_types.h should be changed? You guys know better.

fix segfault in vsnprintf on 32 bit systems examining a PPC ELF

---

libr/core/cconfig.c
libr/core/disasm.c

This appears equivalent to what is done in `string_scan_range` of `bin.c` except for the first-char utf8 check. Greatly reduces the false positive in #7755.

asm.strenc: tighten up guess for utf16le string

---

libr/anal/p/anal_arm_cs.c

Adds:
smmla, smmlar, umull, mls, mla, mvn, bfi, bfc
Fixes:
- ldm index displace
- crop 32 bit math results to 32 bits
- crop 32 bit addresses to 32 bits
related tests here: https://github.com/radare/radare2-regressions/pull/943

Add ESIL for few ARM instructions and fix minor issues

---

libr/bin/pdb/pdb_downloader.c
libr/core/cconfig.c
libr/core/core.c
libr/debug/p/debug_native.c
libr/include/r_bind.h

Supposed to fix this https://github.com/radare/radare2/issues/3128 but it does not work because o does not map the opened DLL at the same offset, so the flags are misplaced.

PDB Autoloading when debugging

---

libr/core/canal.c
libr/core/cmd_anal.c

This resolves radare/radare2#7774.
When saving a project, a dump of the output from the "afl*" command is
used to store all the function references in the project rc file. The
handler for "afl*" generates many afx[cCd] commands to add function
references. However, instead of using the actual reference from
address, the handler uses the function root address as the from
address for the afx[cCd] command. After loading a project, the
execution of the commands in the project rc file causes the invalid
function xrefs to be created, as described in radare/radare2#7774.
The fix does two things. First it changes the way the afx[cCd]
commands are generated by the "afl*" handler so it uses the actual
reference from address instead of the function root address for the
afx[cCd] from address. Second, …

Fix creation of invalid function refs when saving/loading a project.

---

Dockerfile

dockerfile: use node v8, better install npm

---

binr/rasm2/rasm2.c
libr/anal/fcn.c
libr/asm/asm.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_asm.h

To support cLEMENCy, no 9-bit specific code should be kept to make the code base clean. This commit enables an alternative disassembly solution:
- An IO plugin making "seek to vaddr i" correspond to "seek to file offset 2*i"
- In `disasm.c`, vaddr advances at a different pace (1 in the case of 16-bit padding of cLEMENCy) of how the file offset (various `ut8 *buf` arguments or local variables. 2 in the case). This is achieved by setting `e asm.addrbytes=2`.
There may be other variables depending on `len` that are not changed to `ds->addrbytes * len`. But it should cause no trouble to normal architectures.
With this commit, I'm able to disassemble cLEMENCy instructions (`buf_hex[]` does not reflect the correct length in the picture)

Add `asm.addrbytes` eval config var to make one vaddr unit use more than 1 bytes

---

libr/core/cmd_print.c
libr/core/disasm.c

It is tricky to support backward disasm and json disasm.

Support `pi` when asm.addrbytes > 1

---

libr/core/cmd_debug.c
libr/core/meson.build

The jemalloc pr break windows build, to avoid this only jemalloc is usable for non windows version of radare, i need check all the changes to can build under win

fixed meson compilation

---

libr/core/cmd_print.c
libr/core/disasm.c

Currently `pdi -N` is exactly the same as `pdi N`, which is incorrect.

Fix `pdi -N` and support `asm.addrbytes`

---

libr/anal/xrefs.c
libr/core/canal.c
libr/core/disasm.c

This PR (freeing `op`) is on top of #8152 .
When doing `r2 =true -c aaaa`, there is at least one other leak: some of bb created in `appendBasicBlock` are not listed in `r_core_fini`.
```
Indirect leak of 6 byte(s) in 1 object(s) allocated from:                                                                                                                 
#0 0x7fae8a8cda48 in __interceptor_calloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70                                                       
#1 0x7fae882f486c in r_anal_bb_new /home/ray/Dev/Bin/radare2/libr/anal/bb.c:24                                                                                        
#2 0x7fae882e687f in appendBasicBlock /home/ray/Dev/Bin/radare2/libr/anal/fcn.c:247 …
```

Fix leaks in canal.c

---

libr/core/cmd_write.c
libr/include/r_io.h
libr/include/r_types_base.h
libr/io/io.c

Before:
```
% ruby -e '9.times {|i| print i.chr}' > /tmp/9
% r2 -w /tmp/9 -qc 'wen 2'; xxd /tmp/9    
00000000: 0000 0000 0001 0203 0405 0600 00         .............
```
After (expected):
`0000 0000 0001 0203 0405 0607 08`

Fix `wen` and add comments to switch cases.

---

libr/core/cbin.c
libr/core/cmd_info.c
man/rabin2.1

The command ich has been changed to icc in order to be consistent with rabin2.
Rabin2 man page has been updated.

Move ich command to icc

---

libr/core/cconfig.c

make file.lastpath not polluted either after opening malloc:// files, similar to commit 608bfe6b5ba9b92251faaf545798b452d4cad01c

only set file.lastpath when cb_filepath will return true

---

libr/core/cmd_debug.c

In 8748d5eb5eb1908a72bbaacc42327cbed83d1f34 non-breaking spaces were (accidentally) used instead of ASCII spaces, which results in compilation errors:
```
cmd_debug.c: In function ‘do_debug_trace_calls’:
cmd_debug.c:3150:5: error: stray ‘\302’ in program
if (addr_in_range || shallow_trace) {
^
cmd_debug.c:3150:5: error: stray ‘\240’ in program
cmd_debug.c:3165:5: error: stray ‘\302’ in program
if (addr_in_range || shallow_trace) {
^
cmd_debug.c:3165:5: error: stray ‘\240’ in program
```
This should fix the build.

Replace non-breaking spaces with 0x20

---

libr/core/cbin.c
libr/core/disasm.c
libr/core/graph.c
libr/flag/flag.c

`hc` is double assigned.
`flag.c R_API int r_flag_unset(RFlag *f, RFlagItem *item)` is changed to free `item` as all call sites actually free `item`.

Fix a few leaks

---

libr/io/p/io_gdb.c
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/xml.c
shlr/gdb/src/libgdbr.c

- Load gdbr's register array from xml
- Load flags
There is a problem with eflags/rflags on x86_64. gdb deals with the 32-bit eflags even on x86_64. But r2 doesn't display 32-bit registers for x86_64 in normal register listing (there is a check with asm.bits in commands like `dr`). So eflags is not listed for eg. in visual mode.

Additions to gdb xml parsing

---

libr/core/cmd_anal.c

Commands like `asl 0` and `asc 0` are now working properly.

Syscall number can be 0

---

libr/io/cache.c
libr/util/buf.c

The correct way to check whether two half-closed intervals [a,b) [c,d) overlap is a < d && c < b.
The code actually used a < d && c <= b, which might report false positive overlapping and return 1.
I consider this snippet as one example where a sorted array should be superior to a list.

r_io_cache_read: fix number of bytes returned (1, should be 0) when c->to == addr

---

libr/core/cmd_anal.c

Add afCr command for showing register usage for the current function
```
[0x100000f60]> afC?
|Usage: afC[agl?]
| afC convention  Manually set calling convention for current function
| afC             Show Calling convention for the Current function
| afCr[j]         Show register usage for the current function
| afCa            Analyse function for finding the current calling convention
| afCl            List all available calling conventions
| afCo path       Open Calling Convention sdb profile from given path
```
```
[0x100000f60]> afCr
cc.amd64.ret: rax
cc.amd64.arg1: rdi
cc.amd64.arg2: rsi
cc.amd64.arg3: rdx
cc.amd64.arg4: rcx
cc.amd64.arg5: r8
cc.amd64.arg6: r9
cc.amd64.float_arg1: xmm0
cc.amd64.float_arg2: xmm1
cc.amd64.float_arg3: xmm2
cc.amd64.float_arg4: xmm3
cc.amd64.float_arg5: …
```

add afCr[j] command

---

libr/io/io.c

Write operations seek multiple times, and `r_io_seek` tries to translate seek
addr into maddr. When maddr and vaddr overlap this can cause that we end up
writing in a different address than intended, so we translate maddr into
vaddr always prior calling to `r_io_peek_at`.

Fix for r_io_write to use vaddr when peeking

---

libr/core/cmd_open.c
libr/core/file.c
libr/include/r_io.h
libr/io/desc.c
libr/io/io.c
libr/io/map.c
libr/io/p/io_default.c

This fix t.io/maps but it might introduce more regressions
Test from cmd_write is broken and is because `cp` is not copying at all but is independent from IO so kinda weird :S.

Bring onIterMap from siol

---

libr/core/cbin.c
libr/include/r_util/r_utf8.h
libr/util/utf8.c

As per https://github.com/radare/radare2/issues/7335#issuecomment-318070244 for iz and izz. Block list is not shown if string contains ASCII/Basic Latin chars only. The `blocks=` header is colored. The `r_utf_blocks` array is derived from [Blocks.txt](http://www.unicode.org/Public/UCD/latest/ucd/Blocks.txt) of the Unicode Character Database with copyright and permission notice as follows:
Copyright © 1991-2017 Unicode, Inc. All rights reserved.
Distributed under the Terms of Use in http://www.unicode.org/copyright.html.
Permission is hereby granted, free of charge, to any person obtaining
a copy of the Unicode data files and any associated documentation
(the "Data Files") or Unicode software and any associated documentation
(the "Software") to deal in the Data Files or Software
without …

iz/izz: show Unicode blocks

---

libr/include/r_io.h
libr/io/io.c
libr/io/map.c

Is there an operating system where 64-bit largest address 2^64-1 is supported and can be used in a memory mapping? `UT64_MAX` is used to indicate invalid address, thus I think it might not be realistic to support address wraparound. `static void onIterMap(SdbListIter* iter, RIO* io, ut64 vaddr, ut8* buf,`
On Linux x86_64 `ffffffffffe00000 - ffffffffffffffff (=2 MB) unused hole` this space can not be allocated. `-errno` is reserved for errno. If 2^64-1 was supported on some operating system, the overflow checking and the closed interval representation would be very cumbersome. Such high-end address space is also unlikely to be used for sections (likely to be stacks where we might not desire to map. 
If i read carefully, https://github.com/condret/siol/tree/master/lib/io used closed …

[siol fire] Fix off-by-1 in io.c

---

libr/include/r_list.h

Note, `r_list_append` does not append NULL `data`.
```c
R_API RListIter *r_list_append(RList *list, void *data) {
RListIter *item = NULL;
if (list && data) {
item = R_NEW (RListIter);
```
which is inconsistent with `r_list_prepend`.
This change should be safe, if not, the issue definitely comes from the call site.

`r_list_foreach` macros should not stop at an element whose data is NULL

---

libr/core/cmd_info.c

there was a double `"imports"` keyword ouputted by `iaj`

fixed double imports value in iaj output

---

libr/asm/p/asm_x86_nz.c

Only if operands differ in size
FIX #268

Refuse to assemble group 1 ops with dwords on 64bit

---

.travis.yml

See https://github.com/radare/radare2-regressions/pull/967

Fix travis cfg (node now in make -k all)

---

libr/debug/p/native/maps/windows.c

mod_list was not explicitly set to NULL so the r_list_free below fails and crashes.

Fix Windows memory error

---

libr/asm/p/asm_x86_nz.c

Assemble group1 ops with large offset for 64bits correctly

---

binr/rules.mk

This fixed:
```
LD rax2
/usr/x86_64-suse-linux/lib64/libpthread.so.0: undefined reference to `h_errno@GLIBC_PRIVATE'
collect2: error: ld returned 1 exit status
```
by moving -lpthread later.

Fixed a linker error on OpenSUSE

---

libr/io/section.c

otherwise analysis is likely to be broken, not crashing but broken

fix section order

---

libr/include/r_vector.h
libr/util/Makefile
libr/util/meson.build
libr/util/vector.c

Usually, modification to a data structure concentrates mainly on the creation stage, then they are relatively stable and used mostly for read-only purposes. An array is a much better replacement for `RList` for this kind of use cases.
* Random access
* Smaller memory footprint
* Cache friendly
* When dynamic append/pop are used, no need to maintain two separate variables `len` and `capacity`. Maintaining them is error prone.
* Debugging friendly
Examples:
```c
int my_cmp(const void *a, const void *b) {
return strcmp (a, b) < 0;
}
// TODO: move into t/vector.c
int main () {
ptrdiff_t i;
void **it;
RVector *v = r_vector_new ();
assert (*r_vector_push (v, (void *)1337) == (void *)1337);
for (i = 0; i < 10; i++) {
r_vector_push (v, (void *)i);
assert (v->len == i + 2);
}
assert …
```

Add `RVector` (array of void* objects) to r_util

---

libr/include/r_util/r_str_util.h
libr/util/str.c

As per https://github.com/radare/radare2/pull/7827#issuecomment-312195198. Sorry forgot about this. Semantics as per [the C language](http://en.cppreference.com/w/c/language/escape).

Add octal esc handling to r_str_unescape

---

libr/bin/p/bin_elf.c

This is basically what loader does and we should do it to reduce number
of maps and unnecessary overlaps with ELF

Avoid to load SHDR into IO just PHDR

---

libr/io/io.c

He confessed currently there are off-by-1 issues.
"condret | atm master does not read the last byte of a map, i want back to that state, bc it has worked, will watch yur patch after sleep"
A half-closed interval is what other 50+ call sites expect.
"pls don't break it anymore"
Drop unrealistic address wraparound because the current status is far from being able to support it.
You can always add `mapsplit` back with `from <= addr && (addr < to || !to)`. Please use half-closed intervals.
Please stop abusing `if (r_io_read_at (core->io, value, buf, sizeof (buf)))` with `bool r_io_read_at` nonsense. It's fine if the length is 4 or 8 or other small integer that full read is desired. Near the end of a map, mandating a full read is unrealistic.
I was insulted by your …

Fix onIterMap & (I dropped "switch back to half-closed interval again" in this PR b/c resisitance)

---

libr/include/r_binheap.h
libr/include/r_io.h
libr/include/r_vector.h
libr/io/map.c
libr/util/Makefile
libr/util/binheap.c
libr/util/vector.c

See comment at https://github.com/radare/radare2/pull/8279#issuecomment-325170198
`_calculate_skyline` is a scan line algorithm that finds all uncovered map parts (I refer it as "skyline") of maps. An interval is covered if there is another map of higher priority. By precomputing all uncovered parts of maps (they are also non-overlapping so binary search can be employed to locate an intersecting interval quickly), we can speed up `r_io_vread_at` when there are (say > 50) maps.
The algorithm creates two event point (`from` (+1) and `to` (-1)) for each map and sorts these event points. Next it sweeps from left to right, whenever a `from` endpoint is encountered, increases 1 to a counter, decreases 1 to the counter when a `to` endpoint is encountered.
The counter is sometimes positive and …

[siol] Add io->map_skyline as an RVector of uncovered map parts

---

libr/core/canal.c

The tests failed because `r_io_read_at` tried to read 1024 bytes (sizeof buf) from malloc://512 and returned false (partial read should be accepted)
It reduces broken tests from 44 to 6.
I am for `int/st64 r_io_read_at`

Bring back old read-4-byte hack in analysis

---

libr/core/cmd_search.c

May not be suitable, but t.anal/x86 broken reduces from 44 to 19
`R_IO_MAP` seems deprecated and is not set for maps.

Fix t.anal/x86/aap tests

---

libr/core/cmd_section.c

https://github.com/radare/radare2-regressions/blob/master/t.anal/arm/signext#L10
This test (currently broken since siol) seems to rely on the old behavior of [Memory Mirroring](https://wiki.nesdev.com/w/index.php/Mirroring#Memory_Mirroring)
ALso renamed `offset` to `paddr` because it is the argument name used in `r_io_section_add`.

cmd_section.c: add command name beside case labels

---

libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c
shlr/gdb/src/gdbclient/xml.c

Code in `native/bt.c` is independent of the rest of `native`, so I used it here. I wanted to do something like `debug/p/common/` and move stuff there from native, but maybe it's an unnecessarily big change.
Also a hack to add `SP` and `BP` to the profile, because even the XML doesn't clearly specify which is which.
@jpenalbae maybe this works for you

Added backtrace (dbt) to gdb

---

libr/anal/p/anal_arm_cs.c

analop64_esil lacked case ARM64_INS_SVC. This patch adds it and the
code to correctly print the esil representation for svc instruction.
This fixes issue #8370.

Fix svc esil code for aarch64

---

libr/debug/p/native/w32.c

CreateToolhelp32Snapshot function exists only in the kernel32.dll

FIX: Looking for CreateToolhelp32Snapshot function

---

libr/core/cmd_print.c

For #8166 with `pz+` -> `ps+` and constraints above. "Same-endian" means that the endian of examined std::string must be the same as the endian of the radare2 used. No sanity-checking is done.

ps+: print libc++ std::string (same-endian, 32bit, ascii, zero-terminated)

---

libr/core/cmd_print.c

Extend #8166 to 64-bit libc++ std::strings. No plans to extend further beyond 32-bit and 64-bit.

Extend ps+ to 64-bit libc++

---

libr/bin/p/bin_elf.c

Only ehdr is mapped without the change.

Fix ET_REL: load sections if there is no PHDR & fix a few x86_64 relocation types for non-PIC .o files

---

libr/anal/fcn.c
libr/anal/p/anal_java.c
libr/include/r_anal.h

Allows the "ib java class file" test of `t/cmd_i` to succeed.

Fix pdf function lines for Java methods

---

libr/bin/format/mach0/mach0.c
libr/util/str.c

Related issue: #8025
Meanwhile, fixed an out-of-bounds write in `disasm.c:2194`

Use r_str_ncpy (dst, src, sizeof dst) instead of `sizeof dst - 1`

---

libr/bin/bin_write.c
libr/include/r_bin.h

Since `r_file_dump` has been boolified.

Boolify r bin wr output

---

libr/core/cmd_open.c

`oa` no longer exists since siol.
Many `o` prefixed commands need reinspecting.

Remove `oa` from help & add `ob[j*]`

---

libr/anal/p/anal_x86_cs.c

=SN was set to AX for x86-16 mode but both BIOS and DOS only use AH
when multiple syscalls share a single software interrupt.  Using AX
caused SN to be shifted 8 bits which causes the SDB lookup to fail.

x86-16: Look in AH for syscall SN

---

libr/anal/fcn.c
libr/asm/asm.c
libr/core/asm.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_zign.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_asm.h
libr/include/r_io.h
libr/io/io.c

`RAsm::user` in rasm2.c does not point to `RCore`, thus I cannot access `core->io->addrbytes` in rasm2.c 
radare2.c should be good.

Move {RAsm,RAnal}::addrbytes to RIO::addrbytes, delete asm.addrbytes and make cLEMENCy work again

---

libr/core/rtr.c

```
r2 =true
=h
```
Another instance:
```
r2 -C http://localhost:9090/cmd/
?x
```

Fix oob read in rtr.c

---

binr/radare2/radare2.c
libr/core/Makefile
libr/core/cconfig.c
libr/core/cmd_flag.c
libr/core/fortune.c
libr/core/meson.build
libr/include/r_core.h

You can enumerate all fortunes by calling `r_core_fortune_list(core)`, however, currently there is no way to complete `CN_BOOL` typed config var.
https://github.com/radare/radare2/issues/8414

Move fortunes to libr/core/fortune.c

---

libr/include/r_util/r_addr_interval.h

`RAddrInterval` will be used to replace `ut64 from,to;` fields in `RAnalFunction RAnalRange RAnalMetaItem RFlagItem RFlagZoneItem RIOMap RAnalMetaItem` ...
https://hackmd.io/s/HJ_UfBmqZ

Add include/r_util/r_addr_interval.h

---

libr/anal/meta.c
libr/core/cmd_meta.c

For https://github.com/radare/radare2/issues/7335#issuecomment-324599402. One can use `Cz` if old behavior of `Cs` without arguments is wanted.

C[Chsdmf][*] without arguments now lists respective meta info

---

libr/cons/canvas_line.c
libr/core/graph.c
libr/include/r_cons.h

For a simple graph without any loop (backedges), it will not have any kind of node/edge overlapping to the best of my knowledge. Code is in its worst condition since I have not removed the part of the code that is not required anymore (need to review it before making it available for merge).
TODO:
If you test it out and find any issue, please let me know 😄 
EDIT:
- This will overlap/merge more than one branch of same type (true/false/unconditional edge) that have same destination node - but this will happen mainly just above the destination node and not anywhere in between.
- There might come a place where two different type of vertical edges overlap each other in a small part. Again this will only happen after/before edge crossing between two layers.

Fix node and edge overlapping issue in graph mode

---

libr/core/cmd_search.c
libr/include/r_search.h
libr/search/search.c

* fix r_search_mybinparse_update when locating `a+a+b` in `a+a+a+b` where len(a) > 1, e.g. locating `ababc` in `abababc`
* swap the order of the nested loop from
for (i = 0; i < len; i++)
r_list_foreach (s->kws, iter, kw)
to
r_list_foreach (s->kws, iter, kw)
for (i = 0; i < len; i++)
rationale:
+ searching for more needles is rare. the branches used in inner loop harms performance
+ it's cumbersome to bookkeep for each kw in advanced searching algorithms
Fixed tests:
```
[FX]  42  cmd_search: /x with bin mask
[FX]  43  cmd_search: /x with bin mask
```

Fix #8189 - refactor search.c

---

libr/core/cmd.c

Rationale:
`s 0-1` is already allowed, so should `@ 0-1`
r_num_math returns 0 on error, testing addr with UT64_MAX does not make sense
appease condret

Fix #8328, allow @ 0-1 (temporarily setting core->offset to UT64_MAX)

---

libr/parse/p/parse_x86_pseudo.c

fix pd for rip varsub of AT&T syntax

---

libr/core/cmd_search.c

Fix
```
[XX] t/va12
$ r2 -escr.utf8=0 -escr.color=0 -N -Q -i /tmp/tmp-2151517ME11duvBFX.tmp /home/travis/build/radare/radare2/radare2-regressions/bins/elf/analysis/x86-simple
e search.in=io.section
/x 5b
pi 1 @ hit0_0
0x08048065 hit0_0 5b
pop ebx
```

Fix search.in=io.section

---

libr/core/graph.c

There are other issues
https://github.com/radare/radare2/issues/8522
```
Direct leak of 72 byte(s) in 1 object(s) allocated from:
#0 0x7fd9a40f2ce1 in __interceptor_calloc /build/gcc-multilib/src/gcc/libsanitizer/asan/asan_malloc_linux.cc:70
#1 0x7fd9a398cc31 in r_agraph_add_node /home/ray/Dev/Bin/radare2/libr/core/graph.c:3156
#2 0x7fd9a397321e in create_dummy_nodes /home/ray/Dev/Bin/radare2/libr/core/graph.c:614
#3 0x7fd9a397e795 in set_layout /home/ray/Dev/Bin/radare2/libr/core/graph.c:1781
#4 0x7fd9a3984d1f in agraph_set_layout /home/ray/Dev/Bin/radare2/libr/core/graph.c:2449
#5 0x7fd9a398ac34 in check_changes /home/ray/Dev/Bin/radare2/libr/core/graph.c:2945
#6 0x7fd9a398b438 in agraph_print /home/ray/Dev/Bin/radare2/libr/core/graph.c:2985
#7 0x7fd9a398c180 in agraph_refresh …
```

Fix a mem leak in graph.c

---

libr/core/cconfig.c
libr/io/p/io_gdb.c
shlr/gdb/include/libgdbr.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/libgdbr.c

gdb protocol specifies that a target can return partial mem-reads. But for qemu, if a mem-read request even partially overlaps an unmapped page, qemu returns an error. That's why the sudden `0xff` that @jpenalbae reported. Hopefully this fixes it T_T

paged reading for gdb (otherwise it doesn't work on qemu)

---

libr/core/cmd_search.c
libr/include/r_search.h
libr/search/aes-find.c
libr/search/regexp.c
libr/search/rsa-find.c
libr/search/search.c
libr/search/strings.c
libr/search/xrefs.c

* fix out-of-bounds read in r_search_strings_update
* Remove static variables searchhits maplist maxhits first_hit in cmd_search.c
* Change semantics of r_search_hit_new (update kw->count s->nhits in it), return 2 if search.maxhits is reached and stop searching immediately
* honor search.maxhits in r_search_regexp_update
* Refactor _cb_hit, remove bckwrds/do_bckwrd_srch and static cmdhit
* Fix mem leak in regexp.c
* Add support for /d (delta) /bd (backward + delta) when crossing blocksize boundaries

Refactor search and support /d (delta) /bd (backward + delta) crossing blocksize boundaries

---

libr/anal/meta.c

This is same as what `izj` does.

Csj: encode strings in base64

---

libr/egg/egg.c
libr/egg/egg_lang.c
libr/egg/emit_x86.c
libr/include/r_egg.h

Fix pushing inmmediate args using the x64 arch
Added .rargX (a0, a1,...etc) directive.
Added r_egg_assemble_asm() function . 
Using the directive rargX, we can set a returned value from the called function to an aX register (a0, a1...etc). (the r_debug_execute function return value from the a0 register). 
For example:
```
sc@syscall(1);
@syscall() {
: mov eax, `.arg`
: int 0x80
}
main@naked() {
.rarg0 = sc (0x0102030405060708);
}
----------------
main:
mov rax, 0x0102030405060708
push rax
mov rdi, [rsp]
mov eax, 1
int 0x80
add rsp, 8
mov rdi, rax
```
With r_egg_assemble_asm()  you can force use an specific assembler.
For example:
> 
char *asm_list[] = {
"x86", "x86.as",
"x64", "x86.as",
NULL};
r_egg_assemble_asm (dbg->egg,  asm_list);

Egg Issues

---

libr/anal/meta.c
libr/core/disasm.c
libr/include/r_util/r_str.h
libr/util/str.c

For UTF/wide strings, Cs shows the individual UTF8 bytes. That will be fixed later.

Cs: show unfiltered strings

---

libr/core/disasm.c

This reads 8 bytes instead of 4 and then truncates the result to 4
bytes. On 32-bit big-endian architectures this is truncating the wrong 4
bytes. Since ds->analop.refptr already contains the number of bytes to
read let's just read that much.

Fix 32-bit big-endian relsub_addr reads

---

libr/bin/p/bin_elf.c

For some reason, OpenBSD use a different mechanism for
canary and stack protection, using a different functions
than others Unix based systems.

Add canary detection on OpenBSD

---

libr/core/cmd_info.c

Typing 'ibk' trigger the problem, which is caused by r_core_bin_reload
and o being a old pointer on the bin_cur_object.
Fix #8601

Fix segfault found by rafuzz2

---

libr/core/cmd_search.c

In the current version for multiple matches the first result inside the json string misses the needet ',' .

Fixes json result

---

libr/bin/format/elf/elf.c

The detection using needle seems to fail on a recent BSD
system, so using the elf header should be prefered.

Fix osabi detection for FreeBSD and Solaris

---

libr/cons/grep.c

Fix #8640 
I am not 100% sure that's the right fix, but it fix the 2 crashes here, and ~{foo wouldn't be a valid input anyway.

Do not crash on half formed json filter

---

libr/core/cconfig.c
libr/debug/p/debug_gdb.c
libr/io/p/io_gdb.c
shlr/gdb/include/libgdbr.h
shlr/gdb/include/packet.h
shlr/gdb/src/gdbclient/core.c
shlr/gdb/src/gdbclient/xml.c
shlr/gdb/src/gdbserver/core.c
shlr/gdb/src/libgdbr.c
shlr/gdb/src/packet.c

Reintroduced the infinite loop in `send_vcont`. Hopefully slightly better implemented so that you can break out of it.

The simulavr gdb fix 

---

libr/io/io.c

This allows plugins to know where exactly a shrink is happening, when the `r-` command is issued.

Fix side effect on offset in r_io_shift

---

libr/core/cmd_meta.c

Due to https://github.com/radare/radare2/issues/7335#issuecomment-324007261 and https://github.com/radare/radare2/pull/8625#issuecomment-334028572 and also because `Csg` is clearer (as a command) than `Cz` as to what it does.

Csg: add string (guess encoding)

---

libr/core/core.c
libr/include/r_core.h

See [the related bug](https://github.com/radare/radare2/issues/8656)
When user calls _dmh_ , `cmd_dbg_map_heap_glibc_64` is called. This function looks for the main arena by calling `r_resolve_main_arena_64`, which instanciates a new `r_core_t` struct in order to resolve symbols (`get_vaddr_symbol` function is very important).
```c
typedef struct r_core_t {
...
/* files */
RCons *cons;
RIO *io;
RCoreFile *file;
RList *files;
RNum *num;
...
} RCore;
```
When it instanciates a new `r_core_t`, `r_core_init` is called, and vars in the struct are initialized.
```c
R_API bool r_core_init(RCore *core) {
...
core->num = r_num_new (&num_callback, &str_callback, core); // <-- malloc of new num struct
...
/* initialize libraries */
core->cons = r_cons_new ();  // <--- create a new cons  ....
if …
```

Fix the use after free which causes a segv

---

libr/core/disasm.c

Related to https://github.com/radare/radare2/issues/7786#issuecomment-309718837.

disasm: printed strings can have utf16le byte order mark at front

---

libr/anal/fcn.c

After saving a project it was not possible to remove a function with 'af- <addr>' because the size was 0.

Fix deleting functions in projects

---

libr/core/cmd_meta.c

Possible solution for https://github.com/radare/radare2/pull/8669#discussion_r144066005. No test since this doesn't appear testable with current test framework.

Cs.: show <oom> if out of memory

---

libr/bin/p/bin_dex.c

This should fix #8679. Seems that strlen check doesn't work with UTF8 strings. I commented the check because I'd like to add a valid check.

Fix #8679 by changing the strlen check for utf8_strlen

---

libr/core/cmd_debug.c
libr/debug/debug.c
libr/debug/p/native/w32.c
libr/include/r_debug.h

Fill debug info (executable path and username)
Debug event STATUS_X86_SINGLE_STEP instead of EVENT_SINGLE_STEP when debug a x86 binary using radare 64 bits

W32 debug issues

---

libr/core/disasm.c

When the opcode entity has quotation marks in it, the old code wouldn't
escape them, causing unparseable JSON output. This fixes that, in a
manner similar to other JSON handling in the project.

Fix JSON graph output when opcode has quotes ('agj' command)

---

libr/core/anal_tp.c

Fix for the [issue #8709](https://github.com/radare/radare2/issues/8709#).

call r_cons_break_pop after r_cons_break_push in a loop, avoiding loop

---

libr/core/cmd_debug.c

Due to `help_msg[9]` being assigned twice, the offset was wrong and hence causing wrong helper output.

Fixes bug in helper message for arp

---

libr/anal/meta.c
libr/core/cmd_meta.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_util/r_str.h

Will consolidate `RAnalMetaItem` serialization/deserialization into `serialize()`/`deserialize()` later.

Fix Cs* output for Csa strings

---

libr/fs/p/fs_io.c

- fs_io_open: expects the io plugin to return the file size as an usigned int string
- fs_io_read: use name instead of path (because fs_io_open sets the name as absolute path) and require the io plugin to provide file contents as hex encoded string
- fs_io_dir: honor the type provided by the io plugin as a single char followed by a space in each line of the output
Not sure exactly what this is going to break, i.e. what io plugins out there already support fs_io? if any i should port them and maybe write tests too.

Tweak fs io (WIP)

---

sys/build.sh

Fix: build.sh doesn't correctly check capstone header.

bad checking in build.sh (capstone.h)

---

libr/bin/format/elf/elf.c
libr/bin/format/mdmp/mdmp.c
libr/bin/format/mdmp/mdmp_pe.c
libr/bin/format/pe/pe.c
libr/bin/p/bin_mdmp.c
libr/bin/p/bin_pe.c
libr/core/cbin.c
libr/core/cmd.c
libr/core/cmd_api.c
libr/core/disasm.c

Squashed some memory leaks relating to pe and mdmp file types. While hopefully not introducing any bugs!
Found what I believe to be the cause of the resolve error. It seems that r2 does not handle sections with duplicate vaddr/paddr properly. Thus changed `add` to false for overlapped sections.

mdmp|pe: squashed some memory leaks and fixed resolve error in mdmp

---

libr/anal/hint.c
libr/anal/p/anal_x86_cs.c
libr/anal/types.c
libr/core/cmd_type.c
libr/include/r_anal.h
libr/parse/parse.c

Please review - note I used RAnalOp src and dest as an information source about immediates/displacement values. If you have better ideas - please tell me how. 
First version also can handle only one level of recursivity, more will be added soon.
Classic method to check:
```
"td struct qwe { int a; char b; long d; void *p; };"
"td struct qwe2 { int a; char b; long d; void *p; int g; long long q; };"
tas 3
ta qwe.b
```
Where `tas 3` will list all possible combinations that match offset "3", `ta qwe.b` will choose the one `qwe.b` and change the immediate value of the current instruction to this string, if the offset is the same as an immediate value.

Initial support for structure offsets

---

libr/bin/p/bin_mz.c

See radare2-regressions/bin/mz/chkdisk.exe as an example of fixed file.

Fix parsing of DOS UPX 16bit exe

---

libr/debug/p/native/w32.c
libr/io/p/io_w32dbg.c

If we call CreateProcess function with DEBUG_ONLY_THIS_PROCESS flag then
fail DebugActiveProcess when execute the following radare command:
r2 -d test.exe
Removed verbose ouput :/

Fix Try to fix attaching issues for Windows #8770

---

libr/core/cconfig.c
libr/core/disasm.c
libr/include/r_util/r_str.h
libr/util/str.c

Now this works, before it wasn't at least there is a hidden functionality i am not aware of. I touched ds_print_ptr to handles this. I think we could close this https://github.com/radare/radare2/issues/5912
```
0x00000478      mov dword [rbp - 0x78], 0x736f6c43         ; 'Clos'
0x0000047f      mov dword [rbp - 0x74], 0x6e614865         ; 'eHan'
0x00000486      mov dword [rbp - 0x70], 0x656c64           ; 'dle'
```
Moreover i changed alignments in ds
Before 
```
0x00000464      call 0                                     ;[1] ; CALL: 0x0, 0x0, 0x0, 0x0
0x00000469      mov rcx, qword [rsp + 0x60]                ; [0x60:8]=0x4d00004550398141 ; '`'
```
After (extra space more pleasant to the eyes)
```
0x00000464      call 0                                     ; [1] ; CALL: 0x0, 0x0, 0x0, 0x0 …
```

Tiny improvements

---

doc/macos.md

SIP prevents debugging of Apple-signed binaries altogether (/bin/ls is signed by Apple).
The official name of Apple's Operating System from 10.12 onwards is macOS (10.0 - 10.7: Mac OS X; 10.8 - 10.11: OS X).
Corrected misspelling of certificate.

Add commentary about SIP and Apple-signed binaries

---

shlr/heap/include/r_jemalloc/internal/jemalloc_internal.h

radare2 currently fails to build from source on Debian/m68k because ```LG_QUANTUM``` is not defined for this architecture [1]:
```
gcc -c -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/radare2-2.0.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/radare2-2.0.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/radare2-2.0.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -MD  -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -g -Wall -D__UNIX__=1 -g -O2 -fdebug-prefix-map=/<<BUILDDIR>>/radare2-2.0.0+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -MD  -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -g -Wall -D__UNIX__=1 -g -O2 …
```

jemalloc: Add missing definition of LG_QUANTUM for m68k

---

shlr/tcc/libtcc.c
shlr/tcc/tcc.h
shlr/tcc/tccgen.c
shlr/tcc/tccpp.c
shlr/tcc/tcctok.h
sys/indent-whitelist.sh

Because int/short/long types have different length for different platforms, it makes more sense to use int8_t, int16_t, int32_t, int64_t everywhere. I'll improve other parts of tcc as well.

Introducing INTN_T types into tcc parser

---

libr/bin/format/elf/elf.c

There is an interesting case of the incorrect loading ELF files in Linux systems, starting from 2005 year.
Basically it uses phdr offset not from the original physical image offset, but in the loaded, already segmented image (after parsing phdr initially). Please review and discuss. Note, I don't know if other *nix systems do the same, it seems only Linux-specific behavior.

Fix phdr loading for linux binaries

---

binr/radare2/radare2.c

I guess there was a shift from `-R` to `-r` but somebody forgot to add it to `getopt`'s optstring.
`r2 -r myprof.r2 /bin/ls` was throwing error, `invalid option -- 'r'`

Fixed -r option to load rarun2 profile 

---

libr/core/cmd_help.c
libr/include/r_util/r_num.h
libr/util/unum.c

Related to issue #7892 
This command `?btw` takes 3 arguments a, b, c and returns 1 if a < b && b < c else returns 0.
If the command is failed, it prints its usage, and returns undefined value.
Each argument is required to be either number or "(" expr ")".
```
[0x00000000]> ?btw 1 2
Usage: ?btw num|(expr) num|(expr) num|(expr)
[0x00000000]> ?btw 1 2 3
[0x00000000]> ??
1
[0x00000000]> ?btw 1 2 (1 + 2)
[0x00000000]> ??
1
[0x00000000]> ?btw 3 2 1
[0x00000000]> ??
0
```

impl command R_BETWEEN

---

libr/bin/format/pe/pe.c

Hi, I had troubles to detect overlay in some files, like the ransomware BadRabbit (sample here https://www.hybrid-analysis.com/sample/630325cac09ac3fab908f903e3b00d0dadd5fdaa0875ed8496fcbb97a558d0da?environmentId=100)
Then I compared the code implemented with the pefile's source, based in pefile library, we must avoid IMAGE_DIRECTORY_ENTRY_SECURITY.

This fixes detection of overlay in PE files

---

libr/core/cmd_help.c
libr/util/unum.c

R_BETWEEN returns the value of `x <= y && y <= z` so `?btw` should return same value.

fix help message of ?btw

---

Makefile
binr/radare2/Makefile
doc/macos.md
libr/debug/p/native/xnu/xnu_debug.c
sys/build.sh

Change references from osx to macos based on the currently renamed document file: it is now called "doc/macos.md" rather than "doc/osx".

Change references from osx to macos

---

README.md

The r2pipe-python binding seems to be called now r2pipe-py.

r2pipe-python binding name change

---

doc/macos.md

Added to the r2 debugging code signing doc for macOS.

Add non-priv user to the Developer Tools group in macOS

---

libr/util/p_format.c

This bumps the arbitrary nesting limit to 5, needed for some of the MDMP structures.
It also fixes the issue where structnames cannot be found due to incorrect strings being sent during parsing and nesting. The approach is not pretty but as noted in the top of the file - this file is gross!

pf: missing structname fix and bumped the nesting limit to 5

---

libr/debug/p/debug_native.c

Hi,
FreeBSD 12.0 is coming soon, few changes breaks API. One of such change called ino64, here is link to news: https://www.phoronix.com/scan.php?page=news_item&px=FreeBSD-64-bit-Inodes-ino64
This patch allows to compile radare2 on pre-ino64 and post-ino64 freebsd platforms. 
Tested by several people, this patch is landed in freebsd ports: https://svnweb.freebsd.org/ports/head/devel/radare2/files/patch-libr_debug_p_debug__native.c?revision=454555&view=co
Thanks!

[FreeBSD] ino64 change on -head

---

libr/core/cmd.c

Fixes #8857.
A maximum of two @s was supported before and even then it was mostly broken. This fixes it for any number.
Also, resetting temporary evals was done in the order they were specified before, which would break if a variable was specified more than once:
```
e a=0
something @e:a=1,a=1
```
would result in a=1 afterwards.
Tests: https://github.com/radare/radare2-regressions/pull/1075

Fix multiple arrobas

---

doc/pdb/pdb_usage
libr/bin/pdb/pdb_downloader.c
libr/bin/pdb/pdb_downloader.h

The server error detection is more robust now. Works on DLLs listed in #8848. (Sorry for the second PR.)
Some whitespace changes are included. A few signedness issues are corrected.
It seems that MS staffs are serving the pdbs uncompressed, violating the docs. This method works anyway.

PDB downloader: workaround MS server bug

---

libr/core/canal.c

This error is always printed to stderr when `ag` or `agj` is called and there are no functions yet, which is kind of annoying for Cutter since it randomly shows up in its output.
I think it can be removed, because it is not really an error. The message "No functions to diff" doesn't make any sense here anyway, does it?

Remove error output from r_core_anal_graph()

---

libr/cons/dietline.c
libr/core/core.c

I fix the whitespace issue when you use tab completion for
paths in r2 cmd line mode: r2 put a whitespace in so you had to
backspace to remove the whitespace before tab completing again.
Now it works just fine. Anyway, when someone tab completes his entire
path and then insers an whitespace and afterwards presses tab again,
r2 suggest once again the entire path. I have no idea what the best
logic default behaviour should be. Maybe bash style?

I fixed the whitespace issue, i.e. whenever you tried to tab complete a

---

libr/asm/arch/ppc/libvle/vle.c

from 
```
r2:      70e8e00b e_lis r7 0xfffc00b
objdump: 70e8e00b e_lis r7,400b
```
to 
```
r2:      70e8e00b e_lis r7 0x400b
objdump: 70e8e00b e_lis r7,400b
```

[ppc:vle] Fixed wrong e_lis output

---

libr/egg/rlcc/mpc/mpc.c

fixed tiny memory leak in `mpcf_re_range`, moved `range` allocation to after possible `mpc_fail` returns

Fix small memory leak

---

libr/debug/p/debug_gdb.c
libr/debug/p/debug_native.c

Fix #8916 
Identical to the code in r_debug_native.
dmm depends on the logic for dm so it will only work on platforms for which dm has been implemented (currently only Linux).

add dmm to gdb

---

libr/core/cmd_anal.c

This is regarding this [issue](https://github.com/radare/radare2/issues/4363)
Now u can emulate instructions with just one command ```aexn [offset] [N] ```

Added ae subcommand to emulate N instructions starting at X offset

---

binr/rax2/rax2.c
libr/util/print.c

Added -L option which prints hex value from binary format ( [01]+ ).
We can use like follows,
```
$ rax2 -L 100100011010001010110011110001001000010101011110011011111
0x1234567890abcdf
```

Fix #2479 impl bin -> hex (bignum)

---

libr/core/cmd_help.c
libr/util/str.c
libr/util/unum.c

Related to the issue #4101,
There are three changes.
1. Support conversion for multiple values.
2. Add ternary value.
3. Add prefix for binary and ternary values
Output is following,
```
[0x00000000]> ? 1 2
1 0x1 01 1 0000:0001 1 "\x01" 0b00000001 1.0 1.000000f 1.000000 0t1
2 0x2 02 2 0000:0002 2 "\x02" 0b00000010 2.0 2.000000f 2.000000 0t2
```

Support numeric conversion like rax2

---

libr/core/cmd_help.c

I fixed output format of '? ' so as to pass the some regiression tests.

Fix cmd_help

---

libr/core/cconfig.c

Use null if no analysis plugin available

Use null if no analysis plugin available

---

libr/core/cmd_help.c

`iS` wasn't able to handle the first argument because it has **space** before it. Moreover, wasn't able to handle spaces after commas.
This is the current situation:
```
[0x000018d0]> iS entropy
[Sections]
idx=00 vaddr=0x00000000 paddr=0x00000000 sz=0 vsz=0 perm=----- name=
idx=01 vaddr=0x00000238 paddr=0x00000238 sz=28 vsz=28 perm=--r-- name=
. . .
. . .
[0x000018d0]> iS ,entropy
[Sections]
idx=00 vaddr=0x00000000 paddr=0x00000000 sz=0 vsz=0 perm=----- entropy=00000000 name=
idx=01 vaddr=0x00000238 paddr=0x00000238 sz=28 vsz=28 perm=--r-- entropy=03000000 name=.interp
. . .
. . .
[0x000018d0]> iS ,entropy, sha1
[Sections]
idx=00 vaddr=0x00000000 paddr=0x00000000 sz=0 vsz=0 perm=----- entropy=00000000 name=
idx=01 vaddr=0x00000238 paddr=0x00000238 sz=28 vsz=28 perm=--r-- entropy=03000000 …
```

 Fix `iS` with hash arguments

---

libr/asm/p/asm_x86_nz.c

Closes #8939.
When assembling a `mov` of an immediate value into a memory location with `bits = 64`, the result would be missing a REX prefix with set W bit (which indicates 64-bit operands).
CI will fail until the associated `radare2-regressions` PR is merged (https://github.com/radare/radare2-regressions/pull/1088).

Assemble REX.W prefix for 64-bit immediate mov to memory

---

libr/parse/p/parse_x86_pseudo.c

A short check reuses in the parse function the command definition from the replace function instead of extending the x86 command list in the replace function. imul is now supposed to work correctly if it
comes with only one operand.

Fixing imul pseudo code with single operand

---

libr/anal/p/anal_arm_cs.c

The ARMv8-A Architecture Reference Manual Issue B.b states that `cbz` is Compare and Branch on Zero. Don't have a setup to test this natively or under QEMU though.

Switch generated ESIL of arm64 cbz and cbnz

---

libr/util/hex.c

Related to the issue #2639 
It enables parse following code by `rax2 -F
```c
char *shellcode = "\x31\xc0\x50\x68\x2f\x2f\x73\x68\x68\x2f\x62\x69"
"\x6e\x89\xe3\x50\x53\x89\xe1\xb0\x0b\xcd\x80";
```
before this patch, the result is
```
31c050682f2f7368682f6269
```
after this patch,
```
31c050682f2f7368682f62696e89e3505389e1b00bcd80
```

rax2 Fix hex from c

---

libr/util/json_indent.c

Tiny fix for `~{}` for cases like this:
```
{
"test": "ping\"as"
}
```

Fix Escaped Quotes in r_print_json_indent()

---

libr/core/cmd_print.c

Related test: https://github.com/radare/radare2-regressions/pull/1095
Fails on previous commit with:
```
|   offset    | flags funcs cmts syms str  |
|-------------)----------------------------|
| 0x100001010 |    2    0    1    0    0   |
+| 0x100001018 |    1    0    0    0    0   |
+| 0x100001019 |    0    0 1610612736 1610612736 1514668189   |
+| 0x10000101a | 1094995319 1112033655 1365924471 1112821864 1094995252   |
+| 0x10000101b | 1865638759 1315857511 1736068409 1297371190 1246251316   |
+| 0x10000101c | 1094935924 1447384678 963398775 893605465 1379096678   |
+| 0x10000101d | 1256767872 1256770336 32736 32736    0   |
+| 0x10000101f |    0 1514668127 1610612736 1112821864 1096043828   |
+| 0x100001020 | 1112033655 1094995252 1112821864 1162104183 1096043895   |
+| 0x100001021 | …
```

Fix out of bounds access in 'p-'.

---

libr/core/disasm.c
libr/include/r_parse.h
libr/parse/p/parse_x86_pseudo.c

It translates to pseudocode now. However, the problem has comprised more than leave and ret. It touched every op code that consists of a single word like leave, return or nop.  I am not sure if you like the pseudo code.

 Fix leave and ret doesn't translate to pseudocode

---

libr/core/core.c

Hey this PR is regarding this issue [Analysis hangs with a specific library (shared object)](https://github.com/radare/radare2/issues/8969)
I have tested with this file [libmedia.zip](https://github.com/radare/radare2/files/1534666/libmedia.zip)
Before my fix : 
The analysis aav takes around 1- 1.5 hrs
After the fix : 
The analysis aav now takes a 1-2 min 
The issue was aav was considering addr 0x000000 to be a hit and was creating reference in so many area , hopefully this dosen't break anything !!!
But still this only optimize aav when we are searching in empty space , i am still working on implementing anal.in for a  complete fix !!

fix #8969 , optimize aav

---

libr/bp/bp.c

Hello,
I found a regression with int r_bp_size. (which breaks dcu)
It wasn't taking into account that a 0 bits value seemed to mean "whatever bits"
leading to a bad core->dbg->bpsize value.
see file libr/bp/p/bp_x86.c for my supposition about the "whatever bits"
```
static struct r_bp_arch_t r_bp_plugin_x86_bps[] = {         
{ 0, 1, 0, (const ut8*)"\xcc" }, // valid for 16, 32, 64
{ 0, 2, 0, (const ut8*)"\xcd\x03" },                    
{ 0, 0, 0, NULL },                                      
};                                                          
```
it appears setting a bp with the "db" command still worked because of a dirty hack in libr/debug/debug.c
```
static int get_bpsz_arch(RDebug *dbg) {                                     
#define CMP_ARCH(x) strncmp (dbg->arch, (x), …
```

take bits wildcard into account

---

libr/debug/debug.c

this PR tries to make r_debug_bp_add a little bit more arch agnostic.

Use standard r_bp_size in order to get breakpoint size

---

libr/parse/p/parse_x86_pseudo.c

Pseudo code for leave is omitted as well as for pop rbp. Instead, simply
return is printed.
See the screenshots

Small enhencments of pseudo code translation following maijin's suggestions

---

libr/cons/grep.c

JSON commands usually output a trailing newline. In combination with scr.html, this results in json with a `<br />` at the end and thus invalid json.
This fix simply does not print that if it is the last newline.
Not the perfect solution in general, because by design `scr.html` is applied to the final json. Also, some commands like `pdj` output two newlines for some reason, so there will still be a `<br />` for these commands.
Also, I hope this does not break anything because the change applies to all commands, not only json ones.

scr.html: do not print <br /> at the end

---

libr/core/cmd_print.c
libr/core/disasm.c
libr/include/r_core.h

What I described in https://github.com/radareorg/cutter/issues/177
I called it `pdJ` now, but of course we can still discuss the name.
Tests: https://github.com/radare/radare2-regressions/pull/1096

Add pdJ for formatted JSON disassembly

---

libr/core/rtr.c

1. Rap server have still scr.prompt and scr.interactive enabled.
That's why .-- will terminate a rap server loop and turn back
to an interactive mode.

Add workaround for .--

---

libr/core/cconfig.c
libr/core/cmd_anal.c

This PR is regarding this issue [Add anal.in, like the search.in thing](https://github.com/radare/radare2/issues/3608)
For now the commands that honor anal.in are
1)   aav
2)   aac
3)  aat
I would like to have some suggestions on what else anal commands that needs to honor anal.in

intial implementation of anal.in

---

libr/core/canal.c
libr/core/cmd_anal.c

The updated list for command that honors anal.in are : 
1) aav
2) aar  (now this command becomes a lil slower by default , but still we could maintain some uniformity coz i am analyzing over complete search range instead of curseek)
3) aac 
4) aae
5) aat 
This almost covers all the command that are covered by aaa and aaaa command
I think with this implemented we can now avoid depending on curseek , and look to anal.in

extend anal.in for few more command

---

libr/cons/grep.c
libr/core/cmd.c
libr/include/r_cons.h

Grep commands in radare2 are eaten by the first command to run after they are processed. This causes an issue when a user attempts to grep a command that runs its own r2 commands (such as in a Python plugin). This PR fixes this by separating the stripping and processing of a grep command so that nested commands will process their own grep before their parent processes its own. This allows plugins to safely use greps in their calls to r2lang.cmd() and in conjunction with a PR in radare2-bindings, it allows the user to safely grep the output of a Python plugin.

Fixes issue where grep is eaten by first command that executes

---

libr/anal/ref.c
libr/core/cmd_anal.c
libr/core/cmd_search.c
libr/include/r_anal.h

I also modified the API function r_anal_ref_to_string prototype according to the r_anal_fcn_to_string one (RAnal * not needed).

Fixed axtj/axfj extra null byte.

---

libr/core/cmd_anal.c

The aeim command sets the PC register, however flags are not updated. This creates an desynchronization between what it is displayed in the disassembled code and the value in the PC register. The following exemple shows the issue.
```
> aeim
┌ (fcn) sym.f 40                                                                                                
│   sym.f ();                                                                                                   
│           ; var int local_4h @ rbp-0x4                                                                        
│              ; CALL XREF from 0x00000695 (sym.main)                                                           
│           0x00000660      55             pushq %rbp …
```

Add a calling to .ar* in the aeim command

---

libr/parse/p/parse_arm_pseudo.c

- in thumb mode, PC is always 4 bytes ahead (even in 32-bit thumb2 instructions)
- the resulting pc value must be aligned to 4 bytes, by ignoring last 2 bits
if merging this, there are tests fixes: https://github.com/radare/radare2-regressions/pull/1106

Handle arm thumb/thumb2 pc-relative in relsub

---

libr/core/cmd_anal.c

This PR is regarding this issue [reanalyzing is slower than initial analyzing](https://github.com/radare/radare2/issues/8278)
Enabling io.cache in command afta  is causing the analysis to slow every time we run aaaa in same r2 session , now u get const run time output !
Before my fix : 
```
[0x004048c5]> ?t aaaa
[x] Type matching analysis for all functions (afta)
2.585129
[0x004048c5]> ?t aaaa
[x] Type matching analysis for all functions (afta)
3.185129 (and so on increase linearly .... )
```
After my fix : 
```
[0x004048c5]> ?t aaaa
....
[x] Type matching analysis for all functions (afta)
2.085129
[0x004048c5]> ?t aaaa
[x] Type matching analysis for all functions (afta)
2.003612
```
We will be needing io.cache only when we store and restore memory region like stack

Fix #8278 , fix issue in afta

---

libr/core/cmd_anal.c

This is a similar bug of [https://github.com/radare/radare2/pull/9046], where the flag rip is not updated after the execution of the command.

Add a calling to .ar* for the aec / aecu / aecue commands

---

libr/util/str.c

Let the following C code :
```
const char FOO[] = "...\"...";
int main()
{
return 0;
}
```
The psj command produces the following json on the FOO variable :
```
> psj 5 @ obj.FOO
{"string":"...".","offset":1784,"section":".rodata","length":5,"type":"ascii"}
```
The '"' is not escaped on the json data !
Thus following script will produce an error : 
```
import r2pipe
r2 = r2pipe.open('main')
r2.cmd('aaaa')
s = r2.cmdj('psj @ obj.FOO')
$ python script.py 
r2pipe.cmdj.Error: Expecting , delimiter: line 1 column 16 (char 15)
```
To solve the bug, I add an escape on the '"' in the r_str_utf16_encode()

Add on the double-quote in the r_str_utf16_encode() to be able to parse json

---

libr/anal/anal.c
libr/anal/p/anal_x86_cs.c

Related to the issue #7989,
Enable to detect noreturn by looking at the first instruction of callee function.
before
after

Fix #7989 impl noreturn_recurse

---

libr/core/disasm.c

Tests: https://github.com/radare/radare2-regressions/pull/1107
Please note my comments in https://github.com/radare/radare2/pull/8712#issuecomment-353780221

Fix escaping opcode in pdj and pdJ

---

libr/anal/p/anal_x86_cs.c

The following code performs a division with a byte as divisor :
```
$ cat main.S
.text
.global main
msg:
.string "0x%08x\n"
main:
movl $0xCAFE0000, %eax
mov $5, %ax
mov $2, %cl
div %cl
push %eax
push $msg
call printf
xor %eax, %eax
call exit
$ gcc -o main main.S -m32
$ ./main
0xcafe0102
```
With r2 the 'div %cl' is translated as
```
0x000005f5      f6f1           cl,rax,%,rdx,=,cl,rax,/,rax,=
```
and does not change the eax value. Indeed:
```
ar eax=0xcafe0005
ar cl=2
ae cl,rax,%,rdx,=,cl,rax,/,rax,=
ar eax
0xcafe0005
```
The associated code to the DIV in libr/anal/p/anal_x86_cs.c does not check the case where the width of operand is equal to 1. So I have added the following fix:
```
const char *r_quot = (width==1)?"al": (width==2)?"ax": (width==4)?"eax":"rax";
const char *r_rema = …
```

Fix div with byte divisor

---

libr/io/p/io_mach.c

Updating documentation file path/name printed when trying to debug on Mac without having r2 signed.

Updating documentation file path to point correctly

---

libr/asm/p/asm_x86_nz.c

The imul operator assembly code is invalid :   
```
"wa imul al; imul ax; imul eax; imul rax; imul byte [rax]; imul word [rax]; imul dword [rax]; imul qword [rax]"
pi 8
imulq %rax
imulq %rax
imulq %rax
imulq %rax
imulb 0(%rax)
imulq 0(%rax)
imulq 0(%rax)
imulq 0(%rax)
```
After applying the commit, r2 will display this:
```
"wa imul al; imul ax; imul eax; imul rax; imul byte [rax]; imul word [rax]; imul dword [rax]; imul qword [rax]"
pi 8
imulb %al
imulw %ax
imull %eax
imulq %rax
imulb 0(%rax)
imulw 0(%rax)
imull 0(%rax)
imulq 0(%rax)
```

Fix x86 assemble with imul operator

---

libr/bin/format/elf/elf.c

The previous way is using raw memory matching, which is working
for most cases, but a hack. The new code match using section header
notes instead.
This also add minix support

Add a less hacky detection for OS ABI

---

libr/asm/p/asm_x86_nz.c

This commit add the mul operator for the x86 assembly
Before commit:
```
"wa mul eax"
Cannot assemble 'mul eax' at line 3
```
After applying the commit:
```
"wa mul al; mul ax; mul eax; mul rax; mul byte [rax]; mul word [rax]; mul dword [rax]; mul qword [rax]"
pi 8
mulb %al
mulw %ax
mull %eax
mulq %rax
mulb 0(%rax)
mulw 0(%rax)
mull 0(%rax)
mulq 0(%rax)
```

Add mul operator for x86 assembler

---

libr/asm/p/asm_x86_nz.c

This commit add the div operator for the x86 assembly
Before commit:
```
"wa div eax"
Cannot assemble 'div eax' at line 3
```
After applying the commit:
```
"wa div al; div ax; div eax; div rax; div byte [rax]; div word [rax]; div dword [rax]; div qword [rax]"
pi 8
divb %al
divw %ax
divl %eax
divq %rax
divb 0(%rax)
divw 0(%rax)
divl 0(%rax)
divq 0(%rax)
```

Add div operator for x86 assembler

---

libr/asm/p/asm_x86_nz.c

This commit adds the idiv operator for the x86 assembly (signed divide).
Before commit:
```
"wa idiv eax"
Cannot assemble 'idiv eax' at line 3
```
After applying the commit:
```
"wa idiv al; idiv ax; idiv eax; idiv rax; idiv byte [rax]; idiv word [rax]; idiv dword [rax]; idiv qword [rax]"
pi 8
idivb %al
idivw %ax
idivl %eax
idivq %rax
idivb 0(%rax)
idivw 0(%rax)
idivl 0(%rax)
idivq 0(%rax)
```

Add idiv operator for x86 assembler (signed divide)

---

binr/ragg2/ragg2-cc

This commit is just setting the `-miphoneos-version-min` compiler parameter to `0.0` dummy value in order to get it working.
Please note that I don't use Xcode, I only noticed this while trying to compile a Linux shellcode. So there may be incompatibilities with older toolchains, etc.. I can't test for anything other than Xcode7.

Fix ragg2-cc compile error with Xcode 7

---

libr/egg/egg.c

In the file _egg_xor.c_ there is this allocation for the _buf_ variable
https://github.com/radare/radare2/blob/4bb5c15faab0edc8db3f32e80e303a8ceeff447e/libr/egg/p/egg_xor.c#L44
In the file _egg.c_ the _b_ variable is the return value of the _p->build_ function
```
b = p->build (egg);
r_buf_free (egg->bin);
egg->bin = b;
```
There is no checks for the _b_ variable.
I found that is possible to reproduce the sigsegv typing 3 times the command:
`ge xor`

NULL pointer dereference in the file egg.c

---

libr/core/cmd_egg.c

In the compile shellcode command `egg->bin` is not free between two command
Before
```
[0x00010314]> gi exec
022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368
[0x00010314]> gi exec
022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368
[0x00010314]> gi exec
022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2f62696e2f7368022042e01c308fe204308de508208de51302a0e10720c3e504308fe204108de20120c3e50b0b90ef2 …
```

Free the egg variable in the compile shellcode command

---

libr/include/r_list.h

Commit cfb03d37 implements this macro. That comment is outdated.

Delete `// TODO: implement r_list_foreach_prev` obsolete comment in r_list.h file

---

libr/anal/fcn.c

r_anal_fcn_add_bb tries to delete a non-existing node `fcn` and inserts
i into `anal->fcn_tree`, which makes the tree not reflect `anal->fcns`
any longer.

Fix infinite loop/segfault in aab

---

libr/core/cbin.c
libr/core/cmd_info.c

I propose an implementation for commands `iE.`, `iEj.`, `is.`, and `isj.`, which print the current symbol (if any).

iE., iEj., is. and isj. implementation

---

binr/radiff2/radiff2.c

This is a proposal for the support of the binary diff format [GDIFF](https://www.w3.org/TR/NOTE-gdiff-19970901).
Usage: with the `-B` option and the path for the patch file. Example:
```
radiff2 -B A.txt B.txt AB.patch
radiff2 A.txt B.txt -B AB.patch
```

Support of binary diff format (GDIFF) - radiff2

---

libr/core/cmd_egg.c
libr/core/core.c
libr/egg/egg.c
libr/egg/p/egg_exec.c

Fixed the shellcode generation, this was the issue
```
[0x00000000]> gs bind
48c7c0310000000f05ccc3
[0x00000000]> gs write
48c7c0310000000f05ccc3
```
the syscall number is the same for different syscall.
Added also some architecture checks.

Added checks and a fix for the gs command

---

binr/ragg2/ragg2.c
libr/egg/p/egg_xor.c

This is the issue
```
$ ragg2 -e xor -c key=16 -x
```
I just add a check in order to verify the presence of the shellcode.

Fix SIGSEGV in the encoder execution

---

libr/core/cmd_flag.c

Implemented JSON output for all the _fd*_ commands. I removed the line for the default case, because it overrides the `addr` variable so that _r_flag_get_at()_ would always return _x0_ as the flag.

Implemented JSON output for all fd* commands

---

libr/asm/arch/ppc/libps/libps.c
libr/asm/p/asm_ppc_cs.c

i've made a small mistake on the load/store asm for ppc.
i've also changed the cpu name to `ps`
> https://github.com/radare/radare2-regressions/pull/1134 tests

[ppc:ps] fixed bad load/store

---

libr/core/cmd_egg.c

A new proposal for the _gi/ge_ commands using _r_egg_option_set_ and _r_egg_option_get_
```
[0x00000000]> gi exec
[0x00000000]> g
31c048bbd19d9691d08c97ff48f7db53545f995257545eb03b0f05
[0x00000000]> gi exec
[0x00000000]> ge xor 10
[0x00000000]> g
6a1b596a0a5be8ffffffffc15e4883c60d301e48ffc6e2f93bca42b1db979c9bda869df542fdd1595e5593585d5e54ba31050f
```
If approved I will check the other options.

Proposal for the gi/ge commands

---

libr/core/cconfig.c
libr/core/disasm.c

This is because ranges are naturally specified using a hyphen aka the minus sign e.g. 0x00-0xff.

bin.strpurge: use ',' instead of '+' to separate args

---

.github/ISSUE_TEMPLATE.md

@Maijin imho we have to make providing binaries as mandatory, now people have started using template and they just fill out  only the  version info which has been marked mandatory !!!!

Make providing binary or link in issue_template  mandatory

---

libr/core/cconfig.c
libr/core/disasm.c

Substitutes targets of jmp, call and branch ops in disassembly based on jump target in RAnalOp structure. This should lead to more robust substitution with fewer false positives, even for addresses below 0x100. As per discussion in #9138 
Enable with "e asm.jmpsub = true" (default false)
Currently only implemented for pd command. I will add more after this approach is approved by @radare

substitute jmp, call, branch target based on analop

---

libr/core/cmd_egg.c
libr/include/r_egg.h

Added a show command in order to see the current status of the r_egg_option variables
```
[0x00000000]> gi exec
[0x00000000]> gc cmd=/bin/ls
[0x00000000]> ge xor 10
[0x00000000]> gS
shellcode: 'exec'
encoder: 'xor'
padding: '(null)'
Key: '10'
cmd: '/bin/ls'
suid: '(null)'
```

Added a show command, and some fixes

---

libr/anal/p/anal_8051.c

Fixing esil output for mov direct, direct, which was referencing arg1 as source and destination.
PS: In this special case for 8051, arg1 is source and arg2 is destination

8051: fix esil for mov direct,direct

---

libr/anal/p/anal_avr.c

The offset/not offset bit is the last bit of the first nibble, not the last
of the second nibble (see AVR instruction set manual).

fix(anal_avr): calculate offset of ldd/std correctly

---

libr/asm/arch/sh/gnu/sh-dis.c

The displacement field must be sign-extended and multiplied by 2, not
cast to an unsigned type.
This fixes #9235 . To be clear : issue is a regression caused by part of df82290  , but that commit was partly good. The test suite of https://github.com/radare/radare2-regressions/pull/1148/commits covers both issues.

sh: fix disassembly of branch opcodes

---

libr/anal/p/anal_8051.c

With this fix, DATA XREFs and data access comments will resolve to the correct address space for ops with direct and imm16 arguments. Reducing the false positives cluttering code below 0x100

Adding XRAM and IRAM base address to anal ptr 

---

libr/core/cmd_info.c

Reasons:
1. Consistency with other possible args such as ranges.
1. If one forgets the `@`, `iz-` doesn't accidentally purge the string at current seek.

iz-: accept addr as arg

---

libr/anal/p/anal_8051.c

Refactored macros to generate esil. Removed all uses of %N$, which should fix issue #3944
This is also in preparation for cpu specific IRAM and XRAM mapping, support for SFR, and other memory mapping quirks of the 8051.
8051 esil regressions tested successfully.

Refactoring 8051 esil macros

---

libr/io/p/io_zip.c

Opening IPA files using the io_zip throws a segmentation file for any IPA I've tried.
The command executed is:
```
r2 ipa://test.ipa 
Segmentation fault
```
The backtrace is clear, the r_str_newf function has two "%s" but only one argument after the format, this can be fixed just passing "bin_name" twice. 
```
(gdb) bt
#0  strlen () at ../sysdeps/x86_64/strlen.S:106
#1  0x00007ffff3727d78 in _IO_vfprintf_internal (s=s@entry=0x7fffffffd190, format=<optimized out>, format@entry=0x7ffff5bb27d2 "Payload/%s.app/%s", 
ap=ap@entry=0x7fffffffd318) at vfprintf.c:1637
#2  0x00007ffff374ee59 in _IO_vsnprintf (string=0x7fffffffd330 "Payload/Test.app/", maxlen=<optimized out>, 
format=0x7ffff5bb27d2 "Payload/%s.app/%s", args=0x7fffffffd318) at vsnprintf.c:114
#3  0x00007ffff3cdb17e in r_str_newf …
```

Fix Segmentation fault in io_zip for IPA files

---

libr/anal/p/anal_8051.c
libr/asm/p/asm_8051.c

- Replaced hard-coded mapping of address spaces with pseudo registers to configure emulation.
- Added support for asm.cpu to customize address mapping for different flavors of 8051
- Tested against existing 8051 esil regressions

8051: added configurable mapping of address spaces

---

libr/core/blaze.c

Hi,
I Could not compile in Debian 3.16.51-2 x86_64 due to this line and changing the makefile to be c99-compliant would just result in segfaults.
Let me know if I should do something else/amend my PR.
Ayowel

Removed c99 declaration in for loop

---

libr/core/disasm.c

Will otherwise sometimes produce invalid json with pdJ/agJ

Reset Color for asm.calls

---

libr/anal/p/anal_avr.c

This fixes some typos in the AVR anal plugin instruction decoding. See AVR instruction reference for correctness

Avr anal fixes

---

libr/parse/p/parse_x86_pseudo.c

imul is one of the few expressions that takes three arguments: `imul eax, eax, 0x16` is interpreted as `eax *= eax`, which is _wrong_. Also same case applies for `imul eax, ecx, 0x16` where it's supposed to be `eax = ecx * 0x16`
So as crowell said, imul should have **3** interpretations in total

Second interpretation of imul

---

libr/core/disasm.c

Bottom backslash would not be escaped otherwise.

Fix pdJ for asm.fcnlines

---

libr/bin/pdb/tpi.c
libr/bin/pdb/types.h

Addresses issue #9300 by supporting a few additional leaf types, values (qword, uqword, ushort and short as needed).
Also renamed the warning so it's less scary and critical.

Add (u)quadword and short types, clarify warning

---

libr/core/canal.c
libr/core/cbin.c

Fixes issue #5570 and these regression : 
[ radare/radare2-regressions@8ab8a95](https://github.com/radare/radare2-regressions/commit/8ab8a95841713e9646f450cea9fbb272e6874caa)
[radare/radare2-regressions@5e7f739](https://github.com/radare/radare2-regressions/commit/5e7f739a9fb73ac4c3dd98ccab280b8d5fea5ec6)

Fix #5570 , Add dword/qword and stop analyzing PE imports

---

sys/r2-docker.sh

If the docker binary isn't present on the system, the r2-docker script fails with the following error message (instead of displaying the proper warning message).
/usr/bin/r2-docker: 25: /usr/bin/r2-docker: [[: not found
/usr/bin/r2-docker: 37: /usr/bin/r2-docker: docker: not found
/usr/bin/r2-docker: 39: /usr/bin/r2-docker: docker: not found

Fix shell error if docker isn't present

---

libr/config/config.c
libr/core/cconfig.c
libr/core/disasm.c

See #9239 . ~**Note that no colors are printed, unlike what's proposed in the issue.**~
```
[0x00000410]> e asm.varsum 
true
[0x00000410]> pdf
;-- section..text:
;-- eip:
╭ (fcn) entry0 49
│ bp: 0 (vars 0, args 0)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
...
[0x00000410]> e asm.varsum=1
[0x00000410]> pdf
;-- section..text:
;-- eip:
╭ (fcn) entry0 49
│ bp: 0 (vars 0, args 0)
│ sp: 0 (vars 0, args 0)
│ rg: 0 (vars 0, args 0)
...
[0x00000410]> e asm.varsum=2
[0x00000410]> pdf
;-- section..text:
;-- eip:
╭ (fcn) entry0 49
│ vars: 0 0 0
│ args: 0 0 0
...
[0x00000410]> 
```
~[0x565d254d]> e asm.varsum.altern=true~
~[0x565d254d]> pdf|head -n6~
~╭ (fcn) sym.fn 30~
~│ vars: 1 0 0~
~│ args: 1 0 0~
~│           0x565d254d      55             push ebp~
~│           0x565d254e      89e5 …

Add alternative view for variables summary

---

libr/core/canal.c
libr/core/cmd_anal.c

See #7339.
This pull adds bounds of a function in json returned by aflj.
Should afllj be documented?
```
[0xf7ef2c60]> afl?
|Usage: afl List all functions
| afl    list functions
| aflc   count of functions
| aflj   list functions in json
| afll   list functions in verbose mode
| afllj  list functions in json (alias to aflj)
| aflq   list functions in quiet mode
| aflqj  list functions in json quiet mode
| afls   print sum of sizes of all functions
```
I've put the change of `help_msg_afl` in a separate commit. You should be able to cherry pick.

Add bounds of a function in json returned by aflj

---

libr/core/disasm.c

I did quite a lot of refactoring. `ds->pre` is now an enum instead of a string itself and only converted to the corresponding string when eventually getting printed.
This way, it is much better to maintain in my opinion.
Some tests are broken in the current state, because they actually rely on the broken indentation. See https://github.com/radare/radare2-regressions/pull/1167 for the fixes and two additional tests for the indentation.

Refactor Disassembly pre and fix indent (Fix #9316)

---

libr/core/core.c

autocomplete with tab does not work properly for 5 bytes keyword and it does with this.

autocomplete should work properly for agfl now.

---

libr/core/cbin.c

See #4216. Example of parsed output for version_std.exe,
~{~
~"versioninfo": [~
~{~
~"VS_FIXEDFILEINFO": {~
~"Signature": 4277077181,~
~"StrucVersion": 4294967295,~
~"FileVersion": "65535.65535.65535.65535",~
~"ProductVersion": "65535.65535.65535.65535",~
~"FileFlagsMask": 4294967295,~
~"FileFlags": 0,~
~"FileOS": 0,~
~"FileType": 0,~
~"FileSubType": 0~
~},~
~"StringTable": {~
~"FileDescription": "a PE with \"standard\" version info",~
~"FileVersion": "duplicates are authorized",~
~"LegalCopyright": "corkami.com",~
~"StringFileInfo": "",~
~"Comments": "",~
~"CompanyName": "",~
~"InternalName": "",~
~"LegalTrademarks": "",~
~"OriginalFilename": "",~
~"PrivateBuild": "",~
~"ProductName": "",~
~"ProductVersion": "",~
~"SpecialBuild": "",~
~"": "",~
~" ": "",~
~" ** EAT AT JOE\"S **": "best …

Implement rabin -Vj for PE files

---

libr/io/p/io_debug.c

This aims to fix #9302 
<pre>
$ pwd
/home/osalvador/lab/r2/test1 2
$ r2 -d ./test
Process with PID 15663 started...
= attach 15663 15663
bin.baddr 0x00400000
Using 0x400000
Unknown DW_FORM 0x06
asm.bits 64
-- Finnished a beer
[0x7f1ab197a1f0]> ood arg arg2
Wait event received by different pid 15663
Process with PID 15666 started...
File dbg:///home/osalvador/lab/r2/test1 2/test  arg arg2 reopened in read-write mode
= attach 15666 15666
Unknown DW_FORM 0x06
15666
[0x7f802224a1f0]> dc
argv[0]: /home/osalvador/lab/r2/test1 2/test
argv[1]: arg
argv[2]: arg2
[0x7f8021f604a9]>
</pre>
<pre>
$ r2 -d ~/lab/r2/test1\ 2/test
Process with PID 15694 started...
= attach 15694 15694
bin.baddr 0x00400000
Using 0x400000
Unknown DW_FORM 0x06
asm.bits 64
-- Disable these messages with 'e cfg.fortunes = …

fix ood whitespace (#9302)

---

libr/bin/p/bin_te.c

R_BIN_TE_SCN_IS_READABLE should result into R_BIN_SCN_READABLE, not
R_BIN_SCN_SHAREABLE.

Fix regression introduced on eeef82c2

---

libr/asm/arch/arm/armass64.c

See issue #9197.
Test case: https://github.com/radare/radare2-regressions/pull/1175

Fix #9197 - aarch64 `ldur` instruction was missing

---

libr/core/cmd_search.c

While trying to RE a firmware, I didn't realize that section
must be marked as 'executable' for aap to work, and the error message
didn't seems to imply that aap wasn't able to find anything.

Add a warning if no section is executable when using aap

---

libr/asm/arch/ppc/libvle/vle.c

```
[0x00000004]> pdx
0x00000004      55ebffbc       e_stw r15 0xffffffbc(r11)
0x00000008      560bffc0       e_stw r16 0xffffffc0(r11)
0x0000000c      562bffc4       e_stw r17 0xffffffc4(r11)
0x00000010      564bffc8       e_stw r18 0xffffffc8(r11)
0x00000014      566bffcc       e_stw r19 0xffffffcc(r11)
0x00000018      568bffd0       e_stw r20 0xffffffd0(r11)
0x0000001c      56abffd4       e_stw r21 0xffffffd4(r11)
0x00000020      56cbffd8       e_stw r22 0xffffffd8(r11)
0x00000024      56ebffdc       e_stw r23 0xffffffdc(r11)
0x00000028      570bffe0       e_stw r24 0xffffffe0(r11)
0x0000002c      572bffe4       e_stw r25 0xffffffe4(r11)
0x00000030      574bffe8       e_stw r26 0xffffffe8(r11)
0x00000034      576bffec       e_stw r27 0xffffffec(r11)
0x00000038      578bfff0       e_stw …
```

[PPC:VLE] various fixes from a libvle contributor

---

libr/core/cmd_debug.c

in previous contribution, i made autocomplete for db- work but still help message suggest 'db -' to use, yet other commands, for example dbh- and drx- have got no space between command and '-', so i guess it is pretty safe to modify help message for "remove breakpoints" to be "db-" from "db -", and that is where my intention lies in when i made the autocomplete work for it anyway.

the remove breakpoint command should be unified into db-

---

libr/parse/p/parse_x86_pseudo.c

I had to loosen  the contraction `*=`  to allow 3-operand imul to work with minor modifications. No SIMD(MMX,SSE*,...) or x87 floating-point instructions are tested.
Even if it's not written, bear in mind that `imul r32` stores the result in `edx:eax`, not only `eax`

Correct interpretation of imul and mul

---

libr/util/p_format.c

Before this patch, when you did:
pf.test xww v1 v2 v3
pf.test.v2=0x1
only the first byte was overwritten, leaving whatever was in the high
byte of v2 there.

util: when writing to a format value, overwrite all bytes

---

libr/bin/format/elf/elf.c

This fixes #9331 
Shared libraries don't contain a PT_INTERP segment, only the executables that use those libraries have it.
(they need in order to load those libraries).
So for shared libraries we need to check for PT_DYNAMIC as well.
From the ELF specs:
<pre>
PT_DYNAMIC
The array element specifies dynamic linking information.  See ‘‘Dynamic Section’’ below
for more information.
</pre>

Shared libraries don't contain a PT_INTERP segment (#9331)

---

libr/socket/run.c

See #9374. Tests: https://github.com/radare/radare2-regressions/pull/1178
```
$ r2 -R stdin='!python2 -c "print \"hi\""' -d ./main
Process with PID 9977 started...
= attach 9977 9977
bin.baddr 0x5569f48f4000
Using 0x5569f48f4000
Unknown DW_FORM 0x06
asm.bits 64
-- Pass '-j' to rabin2 to get the information of the binary in JSON format.
[0x7f8f98ab7f30]> dc
What's your name? Hello, hi
```

Fix #9374 - stdin=!program not working

---

libr/bin/pdb/pdb_downloader.c

Compressed pdbs were not getting extracted correctly into the symbol store (foo.pd_ -> foo.pd_ instead of foo.pdb)

Fix up pdb expansion target path

---

libr/bin/format/pe/pe.c

R2 currently assumes the CodeView structure contains only filename data, when it can also contain file path data, causing issues later in the program (e.g. when downloading PDBs, storing them in the symbol store, etc.)
This PR:
* Pulls base filename from paths (and filenames) passed in using `r_file_basename ` ([code](https://github.com/radare/radare2/compare/master...riverar:pdb_path_filename?expand=1#diff-15f63750bbf1cea750d78c8cfc33a916R2750))
* Reverts the previous attempt at tackling this issue

Ensure pdb path is stripped down to filename (fixes #9385)

---

libr/bin/pdb/pdb_downloader.c

1. Fixes #9385
2. Fixes regression introduced via 28c84c23efef44277ae9605a86f8dcec4c82f898 where uncompressed pdbs are stored as pd_

Fix linux pdb download regression

---

libr/util/str.c

how to reproduce the bug
1. go to V! mode
2. tab until reach to the stack pane
3. scroll down and you will see the screen completely gets stuck
it's caused by ansi_crop which didn't chop the string properly.
mainly the ansi part of codes in the string passed in the function never gets ripped off and stays in the new string created, so i made the function work properly.

fixed the bug where the stack pane in V! mode gets stuck when it scrolls down.

---

libr/core/cio.c
libr/core/cmd_write.c
libr/io/io.c

```
% ~/Dev/Bin/radare2/debug/binr/radare2/radare2 a
[0x00000000]> wa nop
Failed to write
^D
% ~/Dev/Bin/radare2/debug/binr/radare2/radare2 -w a
[0x00000000]> wa nop
Written 1 byte(s) (nop) = wx 90
[0x00000000]>
```
Before, it claimed to succeed disregarding `-w`

Report error if write fails.

---

libr/core/cmd_anal.c

What about
```
$ r2 ./radare2-regressions/bins/elf/bomb
[0x00400c90]> aea
A: ebp zf pf sf cf of rbp
R: ebp rbp
W: ebp zf pf sf cf of rbp
NW: 
[0x00400c90]> aea 10
A: ebp zf pf sf cf of rbp rdx r9 rsp rsi rax r8 rcx rdi
R: ebp rbp rdx rsp rax
W: ebp zf pf sf cf of rbp r9 rsi rsp rdx r8 rcx rdi
NW: rax
R0: 0x00000000
W0: 0xfffffffffffffff8
W1: 0xfffffffffffffff0
[0x00400c90]> aea?
|Examples: aea show regs used in a range
| aea [ops]   Show regs used in N instructions (all,read,{no,}written,memreads,memwrites)
| aea* [ops]  Create mem.* flags for memory accesses
| aeaf        Show regs used in current function
...
```
instead of current
```
$ r2 ./radare2-regressions/bins/elf/bomb 
[0x00400c90]> aea
A: ebp zf pf sf cf of rbp
R: ebp rbp
W: ebp zf pf sf cf of rbp
N: 
[0x00400c90]> aea 10
A: …
```

Make aea output less obscure

---

libr/core/cmd_print.c

- also fix restore of config vars when returning early from disasm_strings

Ensure asm.cmtright is true in `pds`

---

libr/bin/format/elf/elf.c

This is a workaround for programs that don't have a PT_PHDR and don't compute the kernel hack correctly.

Don't trigger linux kernel hack if we don't have PT_PHDR (#9420)

---

libr/core/disasm.c

- in ds_print_data_type
probably there are other places in which it could be useful to do the same.

Avoid printing references to flags below address `asm.minvalsub`

---

libr/anal/p/anal_arm_cs.c

See #9197.
Test: https://github.com/radare/radare2-regressions/pull/1186
Diff is messy. Actually, the change is small.

Fix #9197, wrong esil for aarch64 ldr

---

libr/core/disasm.c

When asm.jmpsub was enabled, local branches within functions were substituted with function name instead of label.

fix jump substitution within functions when asm.jmpsub=true

---

libr/anal/p/anal_x86_cs.c

This should fix #8929
Test: https://github.com/radare/radare2-regressions/pull/1188
It changes ESIL translation of `call [esp]` from
```
eip,4,esp,-=,esp,=[],esp,[4],eip,=
-------
```
to
```
esp,[4],eip,4,esp,-=,esp,=[],eip,=
+++++++
```
Otherwise, you're jumping into the just pushed return address. Note that this is good even when you're using other registers _not_ modified by the esil expression.

Fix ESIL expression for x86 "call [esp]"

---

libr/core/cmd_flag.c

running `while true; do r2 /bin/ls -q -c 'fdw 0xfffffffff' ; done` crashes sometimes due to uninitialized pointers lmatch and umatch in line 862.

fixed segfault due to uninitialized pointers

---

libr/core/Makefile
libr/core/carg.c
libr/core/cconfig.c
libr/core/cmd_anal.c
libr/core/disasm.c
libr/core/meson.build
libr/core/visual.c
libr/include/r_anal.h
libr/include/r_core.h

hey i have implemented an display for **arguments** to function call in visual mode , which imho could be useful instead of checking value in stack and register  every time  
* enable this config var ``` e dbg.funcarg = true```
* And step into call instr in visual mode (works both while debugging and emulation)
* Support display for arguments passed to function via syscall
* Improve function argument and type analysis

Intial implementation of display for arguments to function call

---

libr/bin/pdb/pdb.c

Fix segfault caused by NULL deref
```
mandlebro@machine:$ touch beef
mandlebro@machine:$ r2 - -c 'idp beef'
```
The offending line is 661 of `buf.c`
```c
660	R_API int r_buf_read_at(RBuffer *b, ut64 addr, ut8 *buf, int len) {
661		RIOBind *iob = b->iob;
```
where `b` is NULL.
This buffer comes from `pdb.c:1181`
```c
1181     	pdb->buf = r_buf_new_slurp (filename);
```
which is not checked for null deref.

fix segfault caused by NULL deref in pdb.c

---

libr/core/file.c

Fix segfault caused by NULL deref in `file.c`.
```
mandlebro@machine:$ r2 /bin/ls -c 'oom;io'
```
The offending line is 616 of file.c
```c
615     	if (r_config_get_i (r->config, "io.exec")) {
616     		desc->flags |= R_IO_EXEC;
617     	}
```
where the `desc` is NULL.

Fix segfault caused by NULL deref

---

libr/core/disasm.c
libr/include/r_print.h
libr/util/print.c

@radare It should fix #9469, but please test it with your own config file if you have a chance. It worked for me with asm.emu=true.

Do not overwrite row_offsets while printing disassembly

---

.travis.yml

This is useful when you want to reproduce builds.

Make travis script show used r2r HEAD

---

Dockerfile

I'm finding more binaries that require libraries that Debian Jessie just does not have (such as modern versions of glibc). Ticking the debian here up to 9.

Updating to Debian 9

---

Makefile

This should fix #9486
make tries to cd to a no longer-existent directory, using a never existed ./libr/sysregs/d/Makefile
Line was introduced at 18c633cb3626c887c31e7d1be88b7d464ed6106a, but `git log --all --full-history -- ./libr/sysregs/d/Makefile` doesn't return anything and the only reference to sysregs in a Makefile seems to be trying to copy files that are not found in sysregs/d
```
$ grep -Hrn '.*sysregs.*'|grep Makefile
.git/COMMIT_EDITMSG:4:using a never existed `./libr/sysregs/d/Makefile`
Makefile:131:	mkdir -p "${WINDIST}/share/radare2/${VERSION}/sysregs"
Makefile:132:	cp -f libr/sysregs/d/*.sdb "${WINDIST}/share/radare2/${VERSION}/sysregs"
```

Fix wrong `make uninstall` command

---

libr/core/core.c
libr/core/project.c

This PR adds autocompletion for the "Po" command, so you don't have to type out the entire project name.
This is my first PR here, and in order to reuse written code I changed a 'r_core_is_project' in libr/core/project.c from static to R_API. If this should be done differently let me know.

Autocomplete project open

---

Dockerfile

Looks like there's one dependency change missing for Debian 9. Added that and it builds fine locally.

Fixing Dockerfile dependency

---

libr/core/cmd_flag.c

```
[0x00000000]> fd??
|Usage: fd[d]  [offset|flag|expression] # Describe flags
| fd $$         # describe flag + delta for given offset
| fd. $$        # check flags in current address (no delta)
| fdd $$        # describe flag without space restrictions
| fdw [string]  # filter closest flag by string for current offset
[0x00000000]> pd 10
0x00000000      90             nop
0x00000001      90             nop
0x00000002      90             nop
0x00000003      90             nop
0x00000004      90             nop
;-- flag1:
;-- flag2:
;-- flag3:
0x00000005      90             nop
0x00000006      90             nop
0x00000007      90             nop
[0x00000000]> fd. 0x5
flag1
flag2
flag3
```

Fix #9470, fix fd. to print all flags at given offset

---

libr/core/cconfig.c
libr/core/rtr.c

1. Currently, tcp server binds any interface. The option
allows to restrict the binding to loopback interface only.
e tcp.islocal=true.

Add tcp.islocal to rtr

---

binr/radare2/radare2.c

Error introduced while trying to fix https://github.com/radare/radare2/issues/9410
`pid, tid` should be allowed to be zero too, afaik.

Fix kill of the debuggee

---

.travis.yml
CONTRIBUTING.md
doc/repo

This PR adds the support to test changes together with related changes in radare2-regressions.
In particular, instead of always using the master branch of https://github.com/radare/radare2-regressions.git, it uses the radare2-regressions repo of the user who created the PR, with the branch that has the same name as the branch in radare2. If not available, it uses the default repo/branch.

Test PRs with radare2-regressions PRs

---

libr/core/cconfig.c

If we work on baremetal binary the autodetection is not working.
In this case Po "project open" and "e asm.arch =.." set always to LE,
even if cfg.bigendian = true.
This patch should change the logic to fall back to cfg value.
Signed-off-by: Oleksij Rempel <linux@rempel-privat.de>

fall back to cfg.bigendian of bin autodetection is not working

---

libr/util/syscmd.c

Also make r_syscmd_mkdirp return a string, instead of printing output on stderr via `eprintf`. This will help testing.
As 1 level less of indentation is used, use `git diff -b` to better review changes.
Tests: https://github.com/radare/radare2-regressions/pull/1211
Fix #9521

Fix `mkdir -p` for r2 shell

---

libr/bin/format/elf/elf.c
libr/bin/p/bin_elf.c
libr/core/cbin.c

This PR does some things:
1. it does not add `Cd` metadata when the relocation is in an executable section
2. it fixes relocations that point to sections (before this patch indeed, sections were excluded by the symbol table)
3. it groups together relocs that have the same import function.

Relocation improvements

---

libr/bin/format/pe/pe.c

Fix for #9348 
Added another MSVC signature to find _main
```asm
push eax
push edi
push dword [esi]
call _main
```

Additional _main signature for MSVC #9348

---

binr/ragg2/ragg2.c
libr/core/cmd_write.c

Tests: https://github.com/radare/radare2-regressions/pull/1213

Make wopO stop when value isn't starting with 0x

---

libr/core/anal_vt.c

Should be merged before the release, because cutter calls `avj` automatically.

Fix out of bounds write in vtables

---

libr/core/cconfig.c
libr/core/cmd_print.c
libr/core/graph.c

1) The main problem was lying with asm.emu.str config var 
**Enabling asm.emu.str , also enabled asm.emu** (which is expected) : 
```
[0x100001058]> e asm.emu.str = true
[0x100001058]> e asm.emu.str
true
[0x100001058]> e asm.emu
true
```
**Disabling it , didin't restore asm.emu** : 
```
[0x100001058]> e asm.emu.str = false
[0x100001058]> e asm.emu.str
false
[0x100001058]> e asm.emu
false
```
2) The "O" command in graph was only supposed to toggle  asm.esil and asm.pseudo , but it was also toggling between summary mode (which in turn uses pds that uses asm.emu.str) , now i have remove that !!

Fix #9512, restore asm.emu in pds

---

libr/util/print.c

r_print_colorize_opcode() inserts ANSI codes twice into real-mode addresses. This causes the address to be parsed correctly when printing with scr.color.ops = true. Full description and test binary in #9572 
I'm not 100% sure this is the ideal fix but I'm happy to make other changes if you point me in the right direction.

Fix colorizing real-mode addresses twice #9572

---

libr/bin/format/mz/mz.c
libr/bin/p/bin_mz.c

Basic support for finding _main in MZ binaries.
Here's two sample binaries I tested the signature against.
[mzsamples.zip](https://github.com/radare/radare2/files/1779233/mzsamples.zip)

Find _main in MSVC-compiled MZ binaries

---

libr/core/cmd.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/include/r_core.h

Removes tmparch/tmpbits from command syntax because we have `@a` and `@b` now.
Moreover, it improves `@a`/`@b` usages, because it also correctly sets/restores anal hints.

Fix pd syntax (also aex and pa)

---

libr/anal/p/anal_avr.c

AVR instruction encoding is weird, we really need custom masking to get useful
zignatures.
This works best in combination with #9568

feat(anal_avr): implement opcode masking for improved zignatures

---

libr/core/cmd_anal.c

Replace return by break, fixing the infinite loop (input* wasn't consumed entirely)

Fixes #9318

---

libr/debug/p/native/linux/linux_coredump.c
libr/debug/p/native/linux/linux_coredump.h

Coredumps were not being generated correctly (something might have changed behind)

Fix coredump generation

---

libr/core/graph.c

Closes #9434.
Simple edges were broken when going around a node:
Now they're fixed:

Fix "simple edges" graph

---

libr/asm/p/asm_x86_nz.c

Remove compiler warnings from nz

---

libr/util/p_format.c

Fixed null pointer deref in the command 'pf E' when it didn't receive an argument.

Fixed null pointer deref in p_format.c

---

.gitignore

I personally use CLion + a small CMakeLists.txt wrapping around meson.
It would be convenient for me to add that to .gitignore.

Ignore files from CLion and CMake

---

libr/cons/dietline.c
libr/core/core.c
libr/core/graph.c
libr/core/visual.c
libr/include/r_cons.h
libr/include/r_core.h

Closes #6756.
When pressing the arrow keys while in "offset mode" (after pressing 'o' in visual) the history will only show seek commands, and truncate them to show only the offset.
Before: [asciinema](https://asciinema.org/a/DMbDWJBVLNN86ayrrhOMPeWvq)
After: [asciinema](https://asciinema.org/a/4HY5NXvXIPoi5v5Ew1RHpnrrd)
Inside `r_line_hist_up()`, to check if r2 is in offset mode, I used 
`if (strcmp(r_line_get_prompt(), "[offset]> ") == 0) {...}`
I know it's ugly, but it was just a test to see if it worked, as this is my first pull request here and I didn't want to change too much code without advice.
So, do you have any suggestions on how could I check more correctly if r2 is in "offset mode" or not? 
I was thinking about adding a flag like `offset_prompt` to struct `RLine`, and then …

Offset history

---

libr/util/str.c

Escape \v and \a in disasm

---

libr/anal/p/anal_x86_cs.c

Corrected imul and idiv operation when there is only 1 argument passed. Before, the default case was rax which is not correct for a X86 binary for example.

Switch cases for imul and idiv when there is only 1 argument

---

sys/static.sh

The CFLAGS and LDFLAGS were being overwritten and didn't allow
modification of such variables for adding other compiling and
linking options (e.g. compile with address sanitizer + coverage)

Honor CFLAGS and LDFLAGS in static build script

---

libr/core/cmd_search.c

The cmd /c/j was not printing any output before because json was not being set to true due to the check in line https://github.com/radare/radare2/blob/4ce73d2d44379e84e9dd1101ded88059c84ef2af/libr/core/cmd_search.c#L2523
was not met by this command

Fix cmd /c/j to print json

---

libr/bin/format/elf/elf.c

While testing #9606 on x86, I stumbled upon a problem reading the regstate from the coredump.
Although I think we need better code there (I'll try to fix it once #9606 is working on x86/x86_64), this fixes it.

Fix: grab regstate on i386

---

libr/core/cmd_open.c

While dealing with something else, I realized that <b>omn</b>'s help said that a name together with an <b>id</b> were expected, but this proved to be false when I looked at the code.
<b>omn</b> was ready to handle an addr since there was no <pre>r_io_map_resolve</pre> involved but a <pre>r_io_map_get</pre> (which looks for maps that contains certain addr).
So I added <b>omni</b> to handle the case where we want to specify an id:
<pre>
> r2 -
-- Follow the white rabbit
[0x00000000]> o elf.c 0x2000 r
4
[0x00000000]> o elf.c 0x8000 r
5
[0x00000000]> om
3 fd: 5 +0x00000000 0x00008000 - 0x00008351 -r-x 
2 fd: 4 +0x00000000 0x00002000 - 0x00002351 -r-x 
1 fd: 3 +0x00000000 0x00000000 - 0x000001ff -rwx 
[0x00000000]> omn 0x00002000 addr
[0x00000000]> omni 3 id
[0x00000000]> om
3 fd: 5 …

Fix: omn wasn't expecting an id

---

libr/anal/p/anal_x86_cs.c
libr/core/cconfig.c
libr/core/cmd_print.c
libr/core/core.c
libr/core/disasm.c
libr/include/r_anal.h
libr/include/r_asm.h
libr/include/r_print.h

Segments in x86 real mode have 16 byte granularity(4 address bits).
There are however systems (namely the Vautomation/ARC Turbo 186 cores) that use 256 byte(8 address bits) instead to allow access to 16MiB memory.
Unfortunately fixed granularity is hard coded in lots of places in r2.
Try to fix this up in as many places as possible.

Make segment granularity adjustable

---

libr/core/asm.c

Issue #9656
An evaluable var was not worth it, it's easier to compile the regex and by doing this we make sure it's a valid regular expresion

[Issue #9656] Add support for extended regex in asm search

---

libr/anal/p/anal_8051.c
libr/include/r_io.h
libr/io/io.c

- Update io map when address space registers change
- Assign name of 8051 address space to io map (invoking omni)
- Added callback to RIOBind to get list of maps for fd (required for invoking omni)
- Fixed leaked string (mstr)
Before:
```
[0x00000000]> om
4 fd: 6 +0x00000000 0x00000000 - 0x0000270f -rwx 
3 fd: 5 +0x00000000 0x20000000 - 0x2000ffff -rw- 
2 fd: 4 +0x00000000 0x10000180 - 0x100001ff -rw- 
1 fd: 3 +0x00000000 0x10000000 - 0x100000ff -rw- 
```
After:
```
[0x00000000]> om
4 fd: 6 +0x00000000 0x00000000 - 0x0000270f -rwx 
3 fd: 5 +0x00000000 0x20000000 - 0x2000ffff -rw- xdata
2 fd: 4 +0x00000000 0x10000180 - 0x100001ff -rw- sfr
1 fd: 3 +0x00000000 0x10000000 - 0x100000ff -rw- idata
```

Few improvements to 8051 memory mapping

---

libr/anal/fcn.c
libr/cons/input.c
libr/core/cmd_anal.c
libr/core/cmd_print.c
libr/core/cmd_write.c
shlr/tcc/tccgen.c

This should fix some of the reported issues in #9682 :
- axf.
- td B()17ecS? [
- woDwpsx@e:=oHf D and woDj01
- p==pv 1oom 6e
- ge;aespe
- 4< 
I could not reproduce <b>paadd [d,[,R,1d</b>

Some fixups for #9682

---

libr/core/cmd_debug.c
libr/debug/p/native/linux/linux_coredump.c

When dumping huge programs, it might be that <b>r_buf_append_bytes()</b> fails because <b>realloc()</b> is not able to get us more memory, and we end up with a "broken" coredump.
In order to workaround this, let's create the buf with <b>r_buf_new_file()</b>, so every time we call <b>r_buf_append_bytes()</b> the buffer will be written into the file instead of calling <b>realloc()</b> to expand it.
Coredumps can get really big:
<pre>
$ readelf -h firefox | grep "Number of program headers"
Number of program headers:         933
$ du -sh firefox
3.5G	firefox
$
</pre>

Fix: coredump generation for huge programs

---

libr/anal/rtti.c
libr/anal/rtti_msvc.c
libr/anal/vtable.c
libr/core/cbin.c
libr/core/cmd_anal.c
libr/include/r_anal.h

- anal.cpp.abi is set to msvc automatically for PE
- More commands and better help message
- av, avr and avra can be canceled with Ctrl+C
- Support for MSVC x86_64 which is a bit different compared to 32bit
#6851

Even More VTables and RTTI

---

libr/bin/format/elf/elf.c
libr/bin/obj.c
libr/bin/p/bin_elf.c
libr/bin/p/bin_elf64.c
libr/core/file.c
libr/include/r_bin.h

This aims to be the first part of #9606, which means:
1. Retrieve map's information and create the ones we find
2. Get regstate and load it
3. Change asm.arch and asm.bits depending on the information we find in the ELF file
All this allows us to see the reg/memory state the binary had at the moment it was dumped, so we can dig in its memory for instance.
So far it supports x86, x86_64 and aarch64 for ELF.
arm support is pretty trivial, but I cannot get a board right now (hopefully tomorrow).
<pre>
$ for i in `ls gcore*` ; do readelf -h $i | grep Machine ; done
Machine:                           AArch64
Machine:                           Intel 80386
Machine:                           Advanced Micro Devices X86-64
<b>[ARM64]</b>
> r2 gcore-aarch64
Setting up coredump: asm.arch <-> arm and …

Loading Core (x86, x86_64, aarch64) (first part, analysis)

---

libr/bin/format/elf/elf.c
libr/bin/obj.c
libr/bin/p/bin_elf.c

This adds support for loading arm32 regs.
Somehow NT_FILE is not being generated for arm32 and the name of the maps can't be grabbed (I'll try to find out why).
<pre>
$ r2 gcore-arm32
Cannot read more NOTES header from CORE
Could not retrieve the names of all maps from NT_FILE
Setting up coredump: asm.arch <-> arm and asm.bits <-> 32
Setting up coredump: Registers have been set
Setting up coredump: 14 maps have been found and created
-- Control the height of the terminal on serial consoles with e scr.height
[0x00000000]> ar
sb = 0x7fffffff
sl = 0xbea655a8
fp = 0xbea6551c
ip = 0x00000000
sp = 0xbea65518
lr = 0xb6ecdafc
pc = 0x00000000
r0 = 0xfffffffc
r1 = 0xbea656a8
r2 = 0x00000000
r3 = 0x00000008
r4 = 0x00000000
r5 = 0x00000078
r6 = 0xbea65628
r7 = 0x000000a2
r8 = 0xbea656a8
r9 = …

core-loading: Add support for arm32

---

libr/bin/format/elf/elf.c
libr/core/file.c

Added <b>r_bin_elf_map_free()</b> so we can free <b>map->file</b> as well and nothing gets leaked.

Add r_bin_elf_map_free to release elf's RBinMap correctly

---

libr/core/disasm.c

We should trust the data references, if someone puts a data ref on an
instruction then we should use it. Before this patch, the data ref was only used
if anal_op.ptr was set.

always show data refs when printing disasm, even if instr has no ptr

---

libr/anal/p/anal_x86_cs.c

Previous fix didn't take into account that IDIV, IMUL and MUL write in (E)DX as well. This pull request apply the same logic from DIV to IDIV, IMUL and MUL. MUL is the only operation correctly implemented. IDIV and IMUL are not yet signed (so partial fix for them in fact).

Corrected MUL + IMUL and IDIV write in EDX (but not yet signed operations)

---

libr/core/cconfig.c
libr/include/r_print.h
libr/util/print.c

Fix the hardcoded assumptions on segment granularity in r_print.
Signed-off-by: Dirk Eibach <dirk.eibach@gdsys.cc>

util: Fix harcoded segment granularity in r_print

---

shlr/heap/include/r_jemalloc/internal/tsd.h

Pull request #9429 introduced some whitespace errors into
shlr/heap/include/r_jemalloc/internal/tsd.h
This breaks building sys/mingw32.sh for me.
Signed-off-by: Dirk Eibach <dirk.eibach@gdsys.cc>

jemalloc: Fix whitespace errors

---

libr/core/canal.c

Jump hints created by ahc were only partially printed in ah ah* and ahj.

Print Jump Hint in ah ah* and ahj

---

libr/core/cmd_anal.c

Fix #9708
`ax` was used for xrefs so I changed it to `a8`.

Rename ab into a8

---

libr/core/disasm.c

In visual disassembly, add a shortcut ( ;[n]) on jump hints

Display Jump hint as shortcut

---

libr/core/cmd_mount.c
libr/fs/fs.c
libr/include/r_fs.h

Gives minimal dietline history support inside mount-shell. There is
still a need to implement autocompletion.

Implement dietline history on mount-shell (#8806).

---

libr/core/panels.c

procedure to reproduce the bug
go to V! and press H or L that tries resizing the canvas which I'd known there'd been no way that would work.
Now resizing works with this.

fixed glitches which happens when pushing H or L that resizes canvas.
