radareorg/radare2

shlr/sdb/Makefile
shlr/sdb/src/heap.c
shlr/sdb/src/journal.c
shlr/sdb/src/query.c

Update sdb once again for wasi and ppcle reasons

---

libr/core/canal.c
libr/core/cconfig.c
libr/core/core.c
libr/core/disasm.c
test/db/anal/arm
test/db/cmd/cmd_pdr
test/db/esil/mips_32

Add anal.fixed.* (move anal.gpfixed and add arch/bits ones) ##core

---

libr/core/cbin.c
libr/core/cmd.c
test/db/cmd/cmd_ie

Use callAt instead of cmdAt for section formats

---

libr/bin/format/objc/mach0_classes.c
libr/core/cbin.c
libr/core/cconfig.c

Return earlier when bin.classes is false ##bin

---

libr/anal/op.c
libr/arch/arch.c
libr/arch/arch_op.c
libr/arch/arch_session.c
libr/arch/arch_value.c
libr/asm/aop.c
libr/core/cmd_anal.inc.c
libr/include/r_anal/op.h

Optimize RAnalOp.setBytes with extra sauce for NEWABI ##analysis

---

doc/fortunes.fun
libr/cons/dietline.c

Fix move cursor right with arrow keys issue in dietline ##shell

---

libr/bin/bin.c
libr/core/cmd_anal.inc.c
test/db/cmd/r2pipe2

Refactor 'aaa' into a separate command

---

.github/workflows/build.yml
binr/rules.mk
mk/wasi.mk
sys/wasi-api.sh

Add WASI reactor build ##build

---

libr/anal/fcn.c
libr/anal/sign.c
libr/arch/p/sparc_cs/plugin.c
libr/core/cconfig.c
libr/include/r_anal.h
libr/include/r_bind.h
test/db/anal/loongarch
test/db/anal/mach0
test/db/anal/sparc
test/db/anal/v850
test/db/cmd/cmd_af
test/db/cmd/cmd_agf
test/db/esil/mips_32
test/db/perf/elf

Add anal.flagends to stop a functions when flags are found ##analysis

---

libr/core/canal.c
libr/core/cmd_flag.inc.c

Some cleanup and minor refactoring for the f commands

---

libr/core/canal.c
libr/include/r_core.h

Remove esil stop global for newabi

---

libr/bin/bin.c
libr/core/cmd_info.inc.c
libr/include/r_bin.h

Implement RBinPlugin Commands in the new abi via i: ##bin

---

libr/bin/bin.c
libr/include/r_bin.h
libr/util/str.c

Implement RBin.attr(str2bits) ##bin

---

libr/cons/cons.c
libr/core/visual.c

Fix bug in V;! not bringing back the mouse ##visual

---

libr/cons/editor.c
libr/core/visual.c

Few fixes for the line editor ##cons

---

libr/cons/editor.c
libr/core/cmd.c
libr/core/core.c
libr/core/visual.c
libr/include/r_list.h
libr/util/list.c
libr/util/str.c

Reimplement internal cfg.editor line editor ##cons

---

libr/cons/dietline.c
libr/core/cmd.c
libr/core/cmd_help.inc.c
libr/core/core.c
libr/debug/p/native/bsd/bsd_debug.c
libr/include/r_cons.h
libr/main/radare2.c

!! for session history, !. for history save ##shell

---

libr/core/pseudo.c
test/db/cmd/cmd_pdc

Fix unmatching brace in pdc output

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/arm/pseudo.c

Fix some cases where arm64 asm.var.sub was ignored ##disasm

---

.github/workflows/tcc.yml
Makefile
binr/r2pm/r2pm.c
libr/arch/p/v850/v850dis.c
libr/bin/bin.c
libr/main/r2pm.c
libr/util/sandbox.c
shlr/Makefile
shlr/meson.build

Fix 'r2pm -r false' because `exit(system("false"))` is a lie ##shell

---

libr/arch/p/arm/plugin.c
libr/arch/p/arm/pseudo.c

Pseudo for arm64 replacing xzr with zero ##decompiler

---

libr/util/sandbox.c

Fix windows and wasm builds

---

test/db/tools/r2pm

Add a test to verify exit code when command is executed with `r2pm -r`

Add r2pm exit status test

---

libr/anal/esil_cfg.c
libr/io/io_cache.c
libr/util/buf_cache.c

Fix io.cache

---

libr/arch/p/sparc_cs/plugin.c

Improve sparc.cs disasm replacing +- with - ##disasm

---

libr/arch/p/sparc_cs/plugin.c
test/db/anal/sparc

* This caused some bad analysis on capstone < v5.0.2
* Aka workaround for a third-party bug

Ignore NEVER bit in branch instructions on SPARC ##analysis

---

shlr/Makefile
shlr/meson.build

Update for capstone-5.0.2

---

binr/r2r/r2r.c

r2r: Display the correct number of jobs

---

sys/debian.sh

Add latest r2book info file to deb builds

Add r2book info files to deb builds

---

dist/plugins-cfg/plugins.android.cfg

Add ed25519 to Android plugin

---

dist/plugins-cfg/plugins.ios-store.cfg
dist/plugins-cfg/plugins.ios.cfg

Add ed25519 to ios plugins

---

libr/include/r_util/r_itv.h

Not sure if this is a good idea

Improve addr wrap support in r_itv

---

shlr/Makefile

Use the latest capstone 5.0.2

---

libr/search/tire.c

Fix oobread in /ck for search/tire ##search

---

libr/core/cconfig.c
libr/core/cmd_meta.inc.c
libr/search/search.c

Better bin.str.(min/max) defaults ##bin

---

libr/main/r2pm.c
test/db/tools/r2pm

Honor env variables in r2pm

---

libr/search/tire.c

Fix more bugs in /ck tire ##search

---

libr/core/cmd_search.inc.c
test/db/cmd/cmd_search_asm

Implement /azj and add a test ##search

---

libr/bin/format/mach0/mach0.c

Add the latest MACH0 platform values ##bin

---

libr/core/cmd.c

Implement -H command as an alias for r2 -H ##shell

---

libr/core/cmd_search.inc.c

Add comments (to replace flags) for asm strings ##search

---

libr/core/cmd_cmp.inc.c

Honor ~ in cat ##shell

---

libr/core/cmd_cmp.inc.c
libr/util/syscmd.c

Move the abspath logic from cmd to the syscmd api

---

libr/bin/bobj.c
libr/bin/mangling/swift-sd.c
test/db/formats/mach0/swift
test/db/formats/mangling/swift
test/db/tools/rabin2

* Improve demangling of some constructions previously unhandled

Append unmangled part of the swift symbol to avoid dupes ##bin

---

libr/core/cmd_search.inc.c

Find longer computed strings with /az ##search

---

libr/core/cmd_search.inc.c

Fix comment for asm.str

---

libr/arch/p/mcs96/mcs96.h
libr/arch/p/mcs96/plugin.c

mcs96 massaging

---

libr/arch/p/bpf/pseudo.c
libr/asm/meson.build
libr/asm/p/bpf_pseudo.mk
test/db/tools/rasm2

Move the bpf pseudo plugin logic

---

libr/core/canal.c

More checks for ranged canal on invalid memory ##analysis

---

libr/arch/arch.c
libr/asm/meson.build
libr/core/core.c

Fix segfault when deallocating arch plugins ##crash

---

libr/core/cmd_anal.inc.c
libr/core/cmd_search.inc.c
libr/core/vmenus.c

Fix the q; function signature bug in Vdf ##visual

---

libr/core/canal.c
libr/core/cmd_print.inc.c
libr/core/disasm.c
libr/include/r_core.h
test/db/cmd/cmd_pdu

This PR attempts to resolve issue #23012
Tests will fail, it is just a prove of concept.

WIP: Make json output consistent ##disasm ##json ##print

---

libr/anal/d/types-arm-ios-64.sdb.txt
libr/anal/sign.c
test/db/cmd/cmd_tc

Add type definition for CCCrypt import for ios-arm64 ##analysis

---

libr/core/cmd_anal.inc.c
libr/core/visual.c

Implement afsQ for better disasm scrolling ##visual

---

shlr/Makefile

Use the latest capstone 5.0.3 ##build

---

libr/core/disasm.c
test/db/anal/jmptbl
test/db/cmd/cmd_pd2
test/db/cmd/cmd_pd_str

* Honor anal.cc, reduce the amount of -1, depends on emu.str

Improved function argument emulation listing ##disasm

---

libr/anal/fcn.c
test/db/anal/jmptbl

Improve handling of jump tables on arm64 ##analysis

---

libr/core/cfile.c

Expose the bin.baddr via env var when running programs

---

libr/main/r2pm.c

Expose and honor the R2PM_GITURL envvar ##r2pm

---

libr/core/cconfig.c
libr/core/cmd_anal.inc.c
libr/core/disasm.c

Initial implementation of the ano command for annotations ##disasm

---

dist/plugins-cfg/plugins.def.cfg
libr/arch/p/tricore/pseudo.c
libr/arch/p/tricore/tricore.c
libr/asm/meson.build
libr/asm/p/tricore_pseudo.mk
libr/include/r_parse.h
test/db/anal/tricore
test/db/cmd/cmd_list

Improve tricore

---

libr/core/project.c

Save and restore annotations ##projects

---

libr/arch/p/stm8/gmtdisas/ins.inc.c
libr/arch/p/stm8/pseudo.c
libr/asm/d/stm8.sdb.txt

Improve the pseudo for stm8 ##decompiler

---

libr/include/r_util/r_str.h
libr/util/str.c

Implement r_str_lstr API for R2_600

---

libr/egg/egg_cfile.c

- [?] Mark this if you consider it ready to merge (if you are ok for now to not have the same done for clang, or llvm-gcc yeah.
When using ragg2 with an arm(32/64) arch it will still try to use the default compiler (in my case gcc) instead of using the cross one failing to compile succesfully.
I have no idea what's wrong with clang. `clang -target arm-linux-gnueabihf` works and creates arm binaries but when using the clang command generated by `ragg2` doesn't.
```
⋊> ~/s/example clang -target arm-linux-gnueabihf a.c                                                                                                                                   17:50:45
⋊> ~/s/example file a.out …
```

refactor: Fix ragg2 for arm targets by using the correct gcc

---

libr/arch/p/tricore/gnu/tricore-dis.c
libr/arch/p/tricore/tricore.c
libr/arch/p/tricore_cs/plugin.c
test/db/anal/tricore

Implement asm.cpu for tricore.cs ##arch

---

libr/arch/p/tricore/tricore.c
libr/arch/p/tricore_cs/plugin.c
test/db/anal/tricore

Improve cfg analysis for tricore and tricore.cs ##arch

---

binr/r2r/r2r.h
binr/r2r/run.c

Add NEWABI and OLDABI bool fields for the testsuite ##r2r

---

libr/core/cfile.c

Sync $R2_FILE with 'o.' output ##shell

---

shlr/sdb/config.mk
shlr/sdb/src/main.c
shlr/sdb/src/text.c

Update for sdb 2.0.1

---

libr/bin/bfile.c
libr/core/cmd_print.inc.c
libr/include/r_util/r_print.h
libr/include/r_util/r_str.h
libr/util/charset.c
libr/util/print.c
test/db/cmd/charset
test/db/cmd/cmd_print
test/db/io/write

`ps` command print only the string until the first non-printable character. Not yet implemented when the charset is changed for example with `e cfg.charset = ascii`.

print string until first non-printable character

---

libr/core/disasm.c

Implement asm.var.summary=3 ##disasm

---

libr/arch/p/tricore/tricore.c
libr/arch/p/tricore_cs/plugin.c

More ESIL for tricore.cs ##arch

---

libr/core/cmd_print.inc.c
test/db/anal/arm64-crypto
test/db/cmd/cmd_pd
test/db/cmd/print
test/db/esil/apple
test/db/formats/elf/elf-relarm
test/db/formats/elf/reloc-arm64

Handle multiline comments in pdsf ##print

---

libr/core/cfile.c

Also export scr.color via R2_COLOR env var ##shell

---

libr/core/cmd_search.inc.c

Implement the /xv[s] value array search command ##search

---

libr/anal/function.c
libr/core/canal.c

Sometimes functions end up asserting with empty names ##crash

---

libr/bin/format/elf/elf.c

Fix #23277 - invalid allocation on verdef struct for ELF ##crash

---

binr/r2r/run.c
libr/main/rasm2.c
man/rasm2.1
test/db/tools/rasm2
test/scripts/test-8051-reassembly.sh

Make rasm2 flags more coherent (-s,-S,-o,-O) ##tools

---

libr/util/uleb128.c

Fix UB in uleb128 left shift reported in #23278 ##crash

---

libr/bin/format/pe/pe.c

Fix multiplication overflow in PE as reported in #23278 ##crash

---

libr/bin/p/bin_elf.inc.c

Fix addition overflow in ELF relocs as reported in #23278 (bug4) ##crash

---

libr/util/uleb128.c

Fix another left shift UB in uleb aka bug5 from #23278 ##crash

---

libr/util/buf.c

Fix large left shift in buf.sleb as reported in bug7 from #23278 ##crash

---

libr/bin/format/pe/pe.c

Dont shift left signed types as reported in bug8 from #23278 ##crash

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/bpf_cs/plugin.c
libr/bin/p/bin_xtr_pemixed.c

Arm regnum

---

libr/arch/p/mips/plugin_cs.c

Make mips plugin cs6 compatible ##arch

---

shlr/Makefile
shlr/meson.build

Upgrade capstone 5 and 6

---

libr/core/cmd.c

Better error reporting for the dash command ##shell

---

libr/core/cmd_search.inc.c
test/db/archos/linux-x86_64/bug_6678

Implement /xn command to search for repeated patterns ##search

---

libr/core/libs.c

Use dir.plugins config var instead of hardcoded R2_LIBDIR in libs.c ##core

---

libr/core/disasm.c

Fix stm8 pseudo return ##decompiler

---

libr/arch/p/ppc_cs/plugin.c

Make ppc plugin cs6 compatible ##arch

---

libr/core/cmd_flag.inc.c

Add f-0x f-? and other flag removal missing commands ##shell

---

binr/radare2/radare2.c
libr/search/privkey.c

Fix a 1 byte overflow in r2cmd and improve logic checks ##crash

---

shlr/qjs/src/libbf.c

Fixed out-of-bound write in libbf.c

---

libr/bin/mangling/swift-sd.c
libr/main/rabin2.c

Improve swift demangler via cmd as well as handle bad sysenv ##bin

---

libr/flag/flag.c
libr/flag/tags.c
libr/flag/zones.c
libr/util/name.c

Slow flag check was not even compiling, remove the code

---

libr/core/cmd_search.inc.c

Honor quiet mode to not set noisy flags in /azs ##search

---

libr/include/r_util/r_graph.h
libr/util/graph.c

Minor optimization in r_graph ##util

---

libr/core/cmd_anal.inc.c
test/db/cmd/cmd_izzzzz
test/db/cmd/maps

Add test for 23313

---

libr/main/rasm2.c

Check if value for rasm2 -c asm.cpu is valid and warn the user ##tools

---

libr/main/rabin2.c

Use better demangling environment defaults in rabin2

---

libr/bin/mangling/swift-sd.c
test/db/formats/mangling/swift

Fix large swift symbol demangling issue ##bin

---

libr/arch/p/x86_nz/nzasm.c
sys/clang-format-diff.py
test/db/asm/x86_64

Handle sil/dil and r[0-9]b extended regs ##asm

---

libr/arch/p/x86_nz/nzasm.c
test/db/asm/x86_64

Remove some FIXME I added in #23333 .

Remove HACK and fix `call qword [reg64]` ##asm

---

libr/arch/p/x86_nz/nzasm.c
test/db/asm/x86_64

continuation of #23333
Fix #23328

Fix `and sil, <mem8>` and `and <reg16>, <reg16>` ##asm

---

libr/cons/cons.c

Use thread-safe ttyname_r API, which also fixes a memory leak from glibc

---

libr/lang/lang.c

Fix memory leak in RLangSession.fini ##leaks

---

libr/cons/cons.c
libr/cons/grep.c
libr/include/r_cons.h

Dynamically build the word grep list, breaking the ABI ##cons

---

libr/arch/p/arm/plugin_cs.c
test/db/esil/arm_64

Fix invalid esil for add+shift on arm64 ##esil

---

preconfigure.bat

Undevilize preconfigure.bat and add MSBuild 2022 Community support ##build

---

libr/core/cmd_type.inc.c

Implement test -s ##shell

---

libr/arch/p/arm/plugin_cs.c
test/db/cmd/cmd_pd_str
test/db/formats/elf/reloc-arm64

LOADs not LEAs for arm64 ##analysis

---

libr/core/canal.c

Assume x27 is a fixed global pointer for arm64 ##analysis

---

libr/bin/p/bin_elf.inc.c

Detect Dart ELFs ##bin

---

libr/core/disasm.c

* Breaks a little of the visual karma

Fix some emulated reference hints ##visual

---

libr/include/r_util/r_buf.h
libr/util/buf.c
libr/util/buf_bytes.c

Initial support to describe RBuffer instances ##util

---

libr/anal/block.c

Handle ^C in afr ##analysis

---

libr/core/visual.c

* Fixing the stuck bug in visual disasm

Don't line-scroll on new-abi builds when lots of vars ##visual

---

libr/debug/arg.c
libr/debug/p/debug_io.c

Fix bug when calling dr8 in the debug.io ##debug

---

libr/core/cmd.c
libr/core/cmd_flag.inc.c
libr/include/r_types.h
test/db/anal/path

Refactor and check numeric arguments when adding flags 'f' ##shell

---

libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/cmd_cmp.inc.c
libr/core/cmd_debug.inc.c
libr/core/cmd_egg.inc.c
libr/core/cmd_eval.inc.c
libr/core/cmd_flag.inc.c
libr/core/cmd_info.inc.c
libr/core/cmd_log.inc.c
libr/core/cmd_meta.inc.c
libr/core/cmd_mount.inc.c
libr/core/cmd_open.inc.c
libr/core/cmd_print.inc.c
libr/core/cmd_project.inc.c
libr/core/cmd_type.inc.c
libr/core/cmd_write.inc.c
libr/core/cmd_zign.inc.c
libr/include/r_core.h
libr/util/log.c
test/db/cmd/r2pipe2

Make the handling of invalid subcommands more consistent ##shell

---

libr/core/cmd.c

Accept '@ expressions that dont start with '0x' ##shell

---

libr/core/cmd_info.inc.c

Fix ic+ argument handling, no space needed

---

libr/core/disasm.c

Show comments associated to an esil emulated reference ##disasm

---

libr/arch/p/arm/v35/Makefile
libr/cons/dietline.c

Fix mingw build

---

libr/core/cmd_anal.inc.c

More a subcommand refactorings

---

libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/cmd_help.inc.c
test/db/cmd/cmd_repeats

Add @@F (alias for @@c:afla) inverse recursive function list  ##shell

---

libr/core/cconfig.c
test/db/cmd/cmd_pd_bugs

Enforce valid value for asm.offset.relto ##config

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/s390/plugin.c
shlr/Makefile
shlr/meson.build

Update cs5 and next pinned commits to the latest

---

binr/r2r/run.c
libr/core/cbin.c
libr/core/cmd.c
libr/core/cmd_help.inc.c
libr/core/patch.c
libr/core/project.c
test/db/archos/linux-x86_64/bug_6678
test/db/cmd/cmd_ic
test/db/cmd/cmd_tc

Fix ?t'. avoid the use of "" prefixes ##shell

---

shlr/qjs/src/cutils.c

Fix the mingw32 build of qjs

---

.github/workflows/ci.yml

up bubnuntu for mingw builds

---

libr/anal/fcn.c

One unnecessary r_anal_op_new ##analysis

---

libr/core/cmd_print.inc.c

Add pdfr and clarify pdfs/pdsf commands in help ##shell

---

libr/core/cmd.c

Fix .! multiline quoted scripts with the shouting dot ##shell

---

libr/core/cmd_anal.inc.c

Add afbrb to enumerate ending basic blocks + better help ##analysis

---

libr/core/cconfig.c
libr/main/radare2.c

Add -e cmd.exit to run commands before leaving ##shell

---

libr/core/cmd_eval.inc.c

Fix eco* and refactor theme loading logic ##cons

---

libr/arch/p/stm8/plugin.c

Fill the op.val for stm8 ref analysis ##analysis

---

libr/core/visual.c
libr/include/r_anal.h

Improve visualization of the visual xrefs view ##visual

---

libr/main/r2pm.c

Use depth=1 for r2pm git clones ##r2pm

---

libr/core/cmd.c
libr/core/cmd_anal.inc.c

Fix afb*? and add $? and ?$? to ?* ##shell

---

libr/core/cmd_print.inc.c
libr/core/cmd_write.inc.c
test/db/cmd/cmd_print

New commands `poE` and `poD` to print encryption or decryption of a block.

New commands `poE` and `poD` ##crypto

---

libr/core/cconfig.c
libr/core/cio.c
test/db/io/write

Add io.voidwrites

---

libr/core/cmd_print.inc.c
libr/core/cmd_write.inc.c

Should prevent some memory leaks in print and write commands.

Correct free in write and print commands

---

libr/core/agraph.c

Fix assert in some title-less graphs ##crash

---

libr/core/agraph.c

Minor graph performance improvements

---

libr/core/agraph.c

Handle ^C in the graph generation process for large ones ##graph

---

libr/core/cmd_help.inc.c

add ' related info to root help

---

libr/core/canal.c
libr/flag/flag.c

Check esil references on flags in 'aae' ##analysis

---

libr/core/cconfig.c
libr/core/disasm.c
test/db/cmd/charset

Fix #23273 - Honor scr.strconv in emustr, fncarg and add tests ##disasm

---

libr/core/cconfig.c

Use hwbp by default on mac-x64 (m1 fails) ##debug

---

libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/cmd_help.inc.c
test/db/archos/linux-x86_64/bug_6678
test/db/tools/r2

- [*] I've added tests (optional)
Related to [this issue](https://github.com/radareorg/radare2/issues/23451).
Also added '-' to ? help message

Fix #23451: add -A command

---

configure-plugins
sys/termux.sh

* configure-plugin: `cp` same file content
* termux install: touch flag input
Just saw them during installation and did the changes, please feel free to close it if it's unnecessary :)

minor changes

---

libr/core/cmd_anal.inc.c

Implement ano-* and support non base64 ano= ##disasm

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/mips/plugin_cs.c
libr/arch/p/ppc_cs/plugin.c
shlr/Makefile
shlr/meson.build

Use latest commit from cs-next, use CS_API_MAJOR for cs-next

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_i
test/db/formats/mach0/fatmach0
test/db/formats/pe/pe
test/db/json/cmd_i

Replace ia with iA, deprecated 'ia' ##bin

---

libr/bin/format/elf/elf_write.c

Fix rabin2 -O r/.rodata/666 foo64 for elf-write ##bin

---

libr/core/cconfig.c
libr/core/cmd_project.inc.c
libr/core/core.c

projects stuff

---

libr/core/cmd_print.inc.c
libr/include/r_util/r_num.h

Implement pdua.. for tail addressing ##disasm

---

libr/core/canal.c
libr/util/pj.c

Properly represent nan and inf in JSON

---

libr/bin/format/pe/pe.c

Remove a hack that breaks parsing sections in some PE ##bin

---

.github/workflows/tcc.yml

Break System Packages in the CI

---

libr/bin/format/pe/pe.c
test/db/formats/pe/65535sects

va2pa() fix removing a subtraction that doesn’t make sense.

fix on virtual address to offset conversion

---

libr/main/radare2.c

Honor custom seek when map address is set ##io

---

binr/r2r/run.c
libr/anal/diff.c
libr/anal/op.c
libr/anal/value.c

Fix few more covs

---

libr/util/xdg.c
libr/util/zip.c
sys/lint-assert.sh

Some more return asserts

---

libr/core/cconfig.c

Fix the default value for dir.cache

---

libr/util/x509.c
libr/util/x509.h

Check x509 API nullability - #23490

---

libr/main/radare2.c

Remove unnecessary newline from r2 -L

---

libr/util/buf.c
libr/util/buf_bytes.c

Minor optimizations in RBuffer.bytes

---

libr/core/cmd_help.inc.c

Fix "?E C.." bug in clippy ##shell

---

libr/include/r_util.h
libr/util/Makefile
libr/util/buf.c
libr/util/meson.build
libr/util/rlz4.c

Initial implementation of the new LZ4 implementation ##util

---

libr/core/cmd_meta.inc.c
libr/lang/p/poke.c
test/db/cmd/cmd_meta

Use more cmdCall in C commands and poke

---

Makefile
doc/fortunes.fun
libr/bin/dwarf.c
libr/core/cfile.c
meson.build

Install scripts ##build

---

libr/core/cmd_hash.inc.c

Fix lang e

---

.github/workflows/build.yml
configure.bat
shlr/qjs/Makefile
shlr/qjs/src/Makefile
shlr/qjs/src/cutils.c
shlr/qjs/src/cutils.h
shlr/qjs/src/libbf.c
shlr/qjs/src/quickjs.c
shlr/qjs/src/quickjs.h

Update to the latest quickjs-ng, so we dont need to ship custom patches

---

.github/workflows/build.yml

Define cstd for meson-w32 ##build

---

libr/arch/p/stm8/gmtdisas/asm.c
libr/arch/p/stm8/pseudo.c
libr/core/cmd_meta.inc.c
libr/core/p/core_prj.c

In stm8 use brackets for memory writes with mov ##arch

---

libr/arch/p/x86/plugin_cs.c

Fixed display of stack variables for comiss instructions

Fixed display of stack variables for comiss instructions #arch

---

libr/core/cmd_meta.inc.c

Remove globals in RCore.cmdMeta ##globals

---

libr/util/w32dw.c

Check w32dw APIs nullability for #23490

---

libr/bin/d/symclass.sdb.txt
libr/core/cmd_info.inc.c

Fix crash in 'iic' and add more import types ##bin

---

libr/bin/d/symclass.sdb.txt

Add more import classes

---

libr/lang/meson.build
shlr/qjs/Makefile

Fix qjs symbols visibility

---

libr/bin/mangling/cxx/cp-demangle.c

Fix #23529 - Stack exhaustion overflow in the c++ demangler ##crash

---

libr/core/cconfig.c
libr/core/disasm.c

Implement asm.cmt.pseudo config option ##disasm

---

libr/anal/fcn.c
libr/core/canal.c
libr/include/r_anal.h

* Fixes all the ram xrefs
* Must be configurable with newabi/r2-6

Disable indirect pointer references for stm8 ##analysis

---

libr/arch/p/stm8/plugin.c

Handle direction and support pointer RAM references for stm8 ##analysis

---

libr/core/pseudo.c

Fix infinite loop in pdc (pseudo decompilation) ##crash

---

libr/core/canal.c
libr/core/cmd_anal.inc.c

Add aflmu command to list function calls once ##analysis

---

libr/core/disasm.c

Fix false positive in op.ptr(char) reference ##disasm

---

libr/anal/anal.c
libr/anal/anplugs.c

Check anal && anplugs APIs nullability for #23490

---

libr/core/pseudo.c

Fix some broken gotos in pdc ##decompiler

---

sys/sanitize.sh

Fix qjs when using asan ##build

---

libr/anal/sign.c
libr/anal/xrefs.c
libr/bin/format/elf/elf.c
libr/main/r2pm.c
libr/main/radare2.c
man/radare2.1

* Inspired by @kazarmy's patch for rizin
* https://github.com/rizinorg/rizin/commit/5ee08f716b04ef94f870ed1c52c59bd76125af32

Add r2 -1 to redirect stderr into stdout ##tools

---

libr/anal/dwarf_process.c
libr/anal/type.c
test/db/cmd/cmd_tc

Fix #23557 - Ignore types with DW_AT_declaration in DWARF

---

binr/rarun2/rarun2.c
libr/include/r_socket.h
libr/main/rarun2.c
libr/socket/run.c
man/rarun2.1

Add 'stdouterr' directive in rarun2 ##tools

---

libr/core/cmd_anal.inc.c
libr/core/cmd_help.inc.c
libr/core/core.c
test/db/anal/emu
test/db/cmd/numvars

Refactor and extend few RNum $O->$$c|$$$c $b->$! ##shell

---

libr/core/cbin.c
libr/core/cmd_open.inc.c
test/db/formats/dwarf

Dont priorize null:// maps on macho binaries ##io

---

libr/core/core.c
libr/util/calc.c
test/db/cmd/numvars

Fix broken test exposing reentrant RNum.math glitch ##bug

---

libr/core/cmd_help.inc.c
libr/core/core.c
test/db/cmd/cmd_flags
test/db/cmd/numvars

Refactor and extend the numvars for flags ##shell

---

libr/core/canal.c
libr/core/cmd_help.inc.c

Fix recently introduced memleak and update latest numvars list

---

libr/core/cmd_debug.inc.c
libr/io/p/io_gprobe.c

Fix #23561 - report 'drq' as an invalid command ##shell

---

libr/crypto/hash/state.c

Repair OpenSSL imports. First step to repair `--with-ssl-crypto` build.

Correct OpenSSL imports

---

libr/core/cmd_anal.inc.c

Fix #23582 - abaj is back to life

---

libr/config.mk.tail
libr/crypto/hash/deps.mk
libr/include/r_hash.h

WIP: Fix openssl builds

---

libr/crypto/hash/sha2.c
libr/crypto/hash/sha2.h
libr/include/rvc.h
libr/util/rvc.c
libr/util/rvc_rvc.c

Aim to fix the duplicated sha symbols from rvc cyclic dep ##build

---

libr/anal/bb.c

Check bb APIs nullability for #23490

---

libr/anal/block.c

Check block APIs nullability for #23490

---

libr/arch/p/dalvik_ns/plugin.c
libr/lang/meson.build

More visibility fixes for the qjs

---

libr/core/cbin.c
test/db/cmd/cmd_is

Use raw symbol name in flatItem.realname instead of the flag name

---

libr/core/numvars.inc.c
libr/crypto/p/crypto_bech32.c

Fix recently introduced leaks spotted by coverity

---

libr/core/cconfig.c
libr/util/log.c

-e log.level accept strings too ##config

---

libr/util/asn1.c
test/db/cmd/cmd_pFa

Small upgrades + corrections from latest PR improving the ASN.1 printings

ASN.1 display corrections + fix tests

---

libr/core/cmd.c
libr/core/cmd_debug.inc.c

Fix dra? in debugger mode (exposed by ?*) ##debug

---

libr/core/cmd.c
libr/core/cmd_help.inc.c

Support @% for reading variables too ##shell

---

libr/bin/dwarf.c
test/db/formats/dwarf

Fix #23581 - DoS in DWARF parser ##crash

---

libr/util/asn1.c

Fix recently introduced leaks in the asn1 parser

---

libr/bin/dwarf.c

Lots of small improvements and bug fixes in the dwarf parser ##crash

---

libr/core/p/core_prj.c
libr/core/patch.c

Save/restore comments in the new projects ##projects

---

libr/core/cmd_info.inc.c

Handle table queries for imports and segments ##bin

---

libr/core/cmd_info.inc.c

Handle comma subcommand for "ic" ##shell

---

libr/core/numvars.inc.c

Fix $B numvars when not at the start of one of them

---

libr/anal/codemeta.c

Check codemeta APIs nullability for #23490

---

libr/anal/class.c

Check class APIs nullability for #23490

---

sys/lint.sh

If the developer has configured git to use a pager `sys/lint.sh` will open a pager requiring manually to close all the pagers when running linting.

Set pager to cat in sys/lint.sh ##test

---

scripts/il2cpp.r2.js

Use il.baddr in the il2cpp script

---

libr/io/io_bank.c

avoid needless double checks
avoid memset

Minor optimization in r_io_bank_locate ##io

---

.github/workflows/build.yml
libr/crypto/hash/deps.mk
libr/crypto/hash/sip_ssl.c
libr/crypto/hash/state.c

Start using OpenSSL functions for SipHash. Add SSL crypto build in CI.

Add SipHash SSL wrapper

---

sys/install.sh

Fix #23622 - Use USEMESON when builddir contain spaces ##build

---

libr/io/p/io_null.c
libr/io/p/io_r2web.c

Minor fixes in io ##io

---

libr/core/cmd_anal.inc.c

Fix 'aa' warning when no sections in binobj ##analysis

---

libr/anal/esil_cfg.c
libr/anal/esil_dfg.c

Check esil_cfg and esil_dfg APIs nullability for #23490

---

libr/arch/p/gb/plugin.c

Add esil custom ops for gb halt and stop, to be replaced by emulators

---

libr/anal/data.c

Check data APIs nullability for #23490

---

libr/cons/grep.c
test/db/cmd/cmd_CL
test/db/cmd/cons_grep

Fix #23588 - empty lines with pd~$foo ##cons

---

libr/core/cmd_eval.inc.c
libr/core/core.c

Fix #23639 - Implement e+ command to set config vars in r2rc ##core

---

libr/bin/dwarf.c

Fix #23581 - (again) another infinite loop in the dwarf parser ##crash

---

libr/bin/dwarf.c

* Should remove globals but we need to break abi

Cache sections in dwarf parser ##bin

---

libr/bin/dwarf.c

Fix #23581 - Infinite loop with unsupported dwarf command ##crash

---

libr/core/cmd_search.inc.c
libr/crypto/hash/hash.c
test/db/cmd/hash

Add plugin during hash search. Add progress bar and tag creation.

Add plugins in hash search ##crypto

---

libr/core/cbin.c
libr/core/cmd_info.inc.c
test/db/cmd/cmd_i
test/db/formats/dwarf

Fix #23538 - iS sha1,sha1/sort/inc table queries + entropy ##bin

---

libr/include/r_util/r_buf.h
libr/io/p/io_ihex.c
libr/util/buf.c
libr/util/buf_bytes.c
libr/util/buf_cache.c
libr/util/buf_file.c
libr/util/buf_io.c
libr/util/buf_mmap.c
libr/util/buf_ref.c
libr/util/buf_sparse.c

Deprivatize RBuffer

---

libr/anal/class.c
libr/include/r_util/r_event.h
libr/util/event.c
test/unit/test_event.c

R2_600 - Redesign proposal for REvent API

---

libr/arch/p/6502/pseudo.c
libr/arch/p/arm/pseudo.c
libr/arch/p/avr/pseudo.c
libr/arch/p/bpf/pseudo.c
libr/arch/p/chip8/pseudo.c
libr/arch/p/dalvik/pseudo.c
libr/arch/p/evm/pseudo.c
libr/arch/p/m68k_cs/pseudo.c
libr/arch/p/mips/pseudo.c
libr/arch/p/null/pseudo.c
libr/arch/p/pickle/pseudo.c
libr/arch/p/ppc/pseudo.c
libr/arch/p/riscv/pseudo.c
libr/arch/p/sh/pseudo.c
libr/arch/p/stm8/pseudo.c
libr/arch/p/tms320/pseudo.c
libr/arch/p/tricore/pseudo.c
libr/arch/p/v850/pseudo.c
libr/arch/p/wasm/pseudo.c
libr/arch/p/x86_nz/att2intel.c
libr/arch/p/x86_nz/pseudo.c
libr/arch/p/z80/pseudo.c
libr/asm/filter.c
libr/asm/parse.c
libr/core/cconfig.c
libr/include/r_parse.h
libr/lang/p/qjs/parse.c

Use RPluginMeta in RParse plugins ##refactor

---

libr/core/cmd_log.inc.c
libr/core/cmd_mount.inc.c
libr/include/r_lib.h
libr/util/lib.c

Unified function to jsonify the plugin meta + more fields ##api

---

libr/cons/cons.c
libr/cons/dietline.c
libr/cons/grep.c
libr/core/cmd.c
libr/include/r_cons.h
libr/util/str.c

Remove pending newabi stuff from RCons

---

libr/bin/dwarf.c

Mostly unroll the main loop, also fixes https://github.com/radareorg/radare2/issues/23581#issuecomment-2480909587

Refactor dwarf5 debug_line parsing

---

libr/arch/arch_op.c
libr/include/r_anal/op.h

Remove NEW_ABI for the local bytesbuf in RArchOp

---

libr/bin/format/pe/pe.c
libr/core/cmd_print.inc.c
libr/include/r_util/r_pkcs7.h
libr/include/r_util/r_x509.h
libr/util/pkcs7.c
libr/util/x509.c
libr/util/x509.h

Fix all pkcs/x509 api names

---

libr/core/cmd_search.inc.c
libr/core/cmd_write.inc.c
libr/include/r_search.h
libr/include/r_util/r_utf16.h
libr/main/rafind2.c
libr/search/keyword.c
libr/util/utf16.c

Support big endian utf16 strings write+search ##search

---

libr/anal/xrefs.c

Fix column names in the ax, output ##analysis

---

libr/core/cmd_print.inc.c
libr/include/r_io.h
libr/io/io.c
libr/util/print.c

UT64_MAX is a valid va address

Rewrite r_io_p2v ##io

---

libr/anal/esil_cfg.c
libr/include/r_anal.h
libr/include/r_esil.h

Move esil_cfg related typedefs back to anal

---

libr/core/canal.c
libr/core/cbin.c
libr/core/cconfig.c
libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/cmd_debug.inc.c
libr/core/cmd_eval.inc.c
libr/core/cmd_flag.inc.c
libr/core/cmd_info.inc.c
libr/core/cmd_open.inc.c
libr/core/cmd_print.inc.c
libr/core/cmd_zign.inc.c
libr/core/core.c
libr/core/dmh_windows.inc.c
libr/core/vmenus.c
libr/include/r_core.h
libr/include/r_util/r_table.h
libr/util/table.c
test/db/formats/dwarf

Add cfg.table.* options and implement wrap/maxcol ##print

---

libr/anal/meta.c
libr/anal/xrefs.c
libr/bin/bin.c
libr/core/Makefile
libr/core/clist.c
libr/core/cmd_anal.inc.c
libr/core/cmd_debug.inc.c
libr/core/cmd_eval.inc.c
libr/core/cmd_hash.inc.c
libr/core/cmd_info.inc.c
libr/core/cmd_log.inc.c
libr/core/cmd_meta.inc.c
libr/core/meson.build
libr/core/project.c
libr/debug/trace.c
libr/include/r_anal.h
libr/include/r_bin.h
libr/include/r_core.h
libr/include/r_debug.h
libr/include/r_lang.h
libr/lang/lang.c
libr/main/rabin2.c

Move RLang.list into RCore and use RCoreTableNew from debug/anal ##refactor

---

libr/include/r_util/r_idpool.h
libr/util/idpool.c

Add r_id_storage_{init/fini} ##util

---

libr/core/cmd_anal.inc.c

Honor scr.color and use red for invalid bits in aobv ##visual

---

libr/include/r_search.h
libr/search/bytepat.c
libr/search/search.c

Fix all XXX in RSearch APIs ##search

---

libr/anal/cond.c
libr/bin/bin.c
libr/core/cmd_search.inc.c
libr/include/r_util/r_buf.h
libr/util/base32.c
libr/util/buf.c
libr/util/rlz4.c

Fix latest covs and add the new RBuf.drain API

---

libr/search/search.c

Honor keyword-alignment restrictions ##search

---

libr/arch/p/x86/plugin_cs.c
libr/core/cconfig.c
libr/core/cmd_search.inc.c
libr/include/r_arch.h

Add RArchInfo.FuncAlign type and details for x64 ##analysis

---

libr/core/cmd_anal.inc.c
test/db/cmd/cmd_ax

Handle axt.. as a valid command ##shell

---

libr/esil/esil.c
libr/include/r_esil.h

Remove unused reil crap from esil

---

libr/include/r_types.h

Aim to fix include for native mingw ##build

---

libr/bin/bfilter.c
libr/include/r_bin.h
libr/include/r_core.h
libr/util/buf_bytes.c
libr/util/buf_cache.c
libr/util/table.c

Little fixes from bin to msvc warnings in rbuf

---

libr/anal/cond.c
libr/anal/flirt.c
libr/anal/function.c
libr/anal/hint.c

Some small assert checks

---

libr/arch/p/x86/plugin_cs.c
libr/core/cconfig.c

Optimize 64bit register from the 32bit one for x86 ##analysis

---

libr/util/strbuf.c

Optimize r_strbuf_init ##util

---

libr/core/libs.c
libr/io/io_plugin.c

Get rid of the CB_COPY macro

---

libr/bin/bin.c
libr/main/rasm2.c

Implement `rasm2 -L [arch]` to show detailed info of 1 plugin ##arch

---

libr/arch/p/arm/v35/Makefile
libr/main/radare2.c
preconfigure.bat

Update v35 armv7

---

libr/anal/fcn.c
libr/asm/asm.c
libr/asm/parse.c
libr/core/cmd_anal.inc.c
libr/core/disasm.c
libr/include/r_asm.h
libr/include/r_parse.h
libr/main/rasm2.c
man/rasm2.1
test/db/cmd/cmd_pd

Remove RAsm.inputFilter and sync with rasm2 -F ##tools

---

libr/esil/esil.c
libr/include/r_esil.h

Kill unused esil macro ops

---

binr/Makefile
binr/meson.build
binr/rapatch2/Makefile
binr/rapatch2/meson.build
binr/rapatch2/rapatch2.c
libr/core/cmd.c
libr/include/r_main.h
libr/main/Makefile
libr/main/main.c
libr/main/meson.build
libr/main/rapatch2.c
man/rapatch2.1

New tool: rapatch2

---

libr/asm/filter.c
libr/core/cmd_write.inc.c
libr/core/hack.c
libr/include/r_core.h

Implement wao* and waol ##write

---

libr/asm/asm.c
libr/asm/parse.c
libr/core/cmd_anal.inc.c
libr/core/disasm.c
libr/include/r_parse.h
test/db/cmd/cmd_pd

Deprecate RParse.parse, make RParse.instruction into RParse.pseudo

---

libr/asm/aop.c
libr/asm/filter.c
libr/core/cmd_anal.inc.c
libr/core/cmd_debug.inc.c
libr/core/cmd_search.inc.c
libr/core/core.c
libr/core/disasm.c
libr/core/vmenus.c
libr/include/r_asm.h
libr/main/rasm2.c

Deprecate r_asm_op_get_asm

---

libr/core/cmd_debug.inc.c

Fixes: https://github.com/radareorg/radare2/issues/19605.

Fix hanging `dc; dc; ood; dc` ##debug

---

libr/arch/p/avr/plugin.c

Make avr arch plugin much easier to read

---

libr/arch/p/avr/plugin.c

Fix avr DES esil generation

---

libr/arch/p/avr/plugin.c

Fix avr esil des customop

---

binr/r2r/run.c

Fix several bugs in r2r

---

libr/anal/Makefile
libr/core/core.c

Autocomplete argument for abp

---

libr/core/visual.c

Dont softscroll when var summary is set ##visual

---

libr/arch/p/8051/plugin.c

Start deobfuscating 8051 arch plugin

---

libr/arch/p/8051/plugin.c

Disable esil_cb for 8051 arch plugin

---

binr/r2r/run.c

Fix minor coverity issues spotted in r2r

---

libr/arch/p/avr/plugin.c

Fix regression in avr arch plugin

---

libr/arch/p/arm/plugin_cs.c
shlr/Makefile
shlr/meson.build

Update cs and add minor fix to arm/plugin_cs.c

---

libr/core/dmh_windows.inc.c
libr/debug/p/debug_native.c
libr/debug/p/native/windows/windows_debug.c
libr/debug/p/native/windows/windows_message.c

Fix Michaelsoft Binbows builds

---

libr/arch/p/arm/plugin_cs.c

Improve readability of arm_cs arch plugin

---

libr/core/core_esil.c
libr/include/r_core.h

Add r_core_esil_{load/unload}_arch ##core

---

libr/bin/p/bin_elf.inc.c

Hunting this took hours, i am tired

Fix some elf arm relative reloc shit

---

libr/core/core_esil.c

Add core_esil_op_interrupt to invoke cmd.esil.intr on core esil interrupts

---

libr/core/cconfig.c
libr/core/core_esil.c
libr/include/r_core.h

Add esil.traprevert config var

---

libr/arch/arch_op.c
libr/core/core_esil.c
libr/include/r_core.h

This probably doesn't work at this point as intended. There are still some minor changes in esil api and core config vars to do/

Add r_core_esil_single_step

---

.github/workflows/ci.yml
binr/rabin2/meson.build
libr/arch/p/dalvik_ns/plugin.c
libr/esil/meson.build
meson.build
subprojects/sdb.wrap

Fix sdb static linkage with meson

---

libr/cons/stiv.c
libr/core/cmd_print.inc.c
libr/include/r_cons.h

Add RGBA image renderer and improve pri help ##print

---

libr/core/core_esil.c
libr/include/r_util/r_strbuf.h
libr/util/strbuf.c
test/unit/test_strbuf.c

Simplify trap_revert voyeurs in core_esil

---

libr/core/cmd_open.inc.c
libr/include/r_io.h
libr/io/io_bank.c
libr/io/io_map.c

Add new omo command to show map overlay (relocs) diff

---

libr/asm/asm.c

Use mips.pseudo for the loongarch ##asm

---

libr/bin/p/bin_elf.inc.c

Assume loongarch relocs are the same as the mips ones ##bin

---

.gitignore
Makefile

update .gitignore and makefile

---

libr/arch/p/arm/plugin.c
libr/arch/p/ppc_cs/plugin.c
libr/core/canal.c
libr/include/r_anal/op.h
test/db/anal/arm64-search
test/db/anal/loongarch
test/db/anal/ppc
test/db/cmd/cmd_meta

* Thanks @astralia for spotting the bug

Fix string reference via emulation on powerpc ##analysis

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_ie

Fix #23759 - Implement entrypoint symbols command 'ies' ##bin

---

libr/core/cmd_open.inc.c
libr/io/io_bank.c

Minor optimization in r_io_bank_overlay_foreach ##io

---

libr/esil/esil.c

Kill iscommand bloat in esil/esil.c

---

libr/esil/esil.c
libr/include/r_esil.h

Add REsilVoyeurOp type ##esil

---

libr/core/cmd_open.inc.c

Add vsize parameter to on command ##cmd

---

libr/core/cmd_open.inc.c
libr/esil/esil.c
libr/esil/esil_stats.c
libr/include/r_esil.h

Prepare r_esil_stats for switch to new API ##esil

---

libr/arch/p/x86/plugin_cs.c
libr/core/cmd_anal.inc.c

Add new function prelude for x64 ##analysis

---

libr/arch/p/arm/pseudo.c
libr/arch/p/dalvik/pseudo.c
libr/arch/p/riscv/pseudo.c
libr/arch/p/stm8/pseudo.c
libr/arch/p/x86_nz/att2intel.c
libr/arch/p/x86_nz/pseudo.c
libr/util/str.c

Improve code and fix recent leaks in some asm.pseudo plugins

---

libr/bin/format/pdb/pdb_downloader.c
libr/core/cmd_cmp.inc.c
libr/core/cmd_write.inc.c
libr/core/corelog.c
libr/core/rtr.c
libr/core/rtr_http.inc.c
libr/core/rtr_shell.inc.c
libr/include/r_socket.h
libr/io/p/io_http.c
libr/io/p/io_r2web.c
libr/socket/socket_http.c
test/db/cmd/cmd_list

Add support for HTTP headers in the RSocket API ##socket

---

libr/core/cmd_open.inc.c

Refix uninitialized vsize in on command

---

libr/bin/bfile.c
libr/bin/bin.c
libr/bin/format/mach0/mach0.c
libr/bin/format/mach0/mach0.h
libr/bin/i/private.h
libr/bin/p/bin_dyldcache.c
libr/bin/p/bin_mach0.c
libr/bin/p/bin_xnu_kernelcache.c
libr/include/r_bin.h

Use more RBinFileOptions - wip refactoring

---

libr/main/radare2.c
test/db/esil/cmp

Run `aei` when no file is loaded, add a test just in case ##esil

---

libr/core/core.c
libr/esil/esil_trace.c
libr/include/r_esil.h
libr/include/r_reg.h
libr/reg/arena.c
libr/reg/double.c
libr/reg/profile.c
libr/reg/reg.c
libr/reg/rvalue.c
test/unit/test_reg.c

Remove r_arch dependency from r_reg

---

libr/util/thread.c

Fix #23810 - Fix compilation error on certain Windows 10 hosts by conforming with C99 style. 

---

doc/fortunes.fun
libr/core/cmd_open.inc.c
test/db/cmd/cmd_open

Fix regressions in the 'on' command ##shell

---

libr/core/cmd_anal.inc.c

Add axffq and axff* commands ##shell

---

libr/core/cmd_print.inc.c
test/db/formats/elf/reloc-arm64

Improve 'pdsfq', avoid some dupes and handle fn flags ##print

---

libr/core/cmd_anal.inc.c

Implement json output for aflaj command ##shell

---

libr/cons/grep.c
test/db/cmd/cmd_zignature
test/db/cmd/cons_grep
test/db/tools/rasm2

Fix ~$$? ~?$$ and add tests ##cons

---

binr/r2r/r2r.c
binr/r2r/r2r.h
binr/r2r/run.c
libr/include/r_util/r_sys.h
libr/util/sys.c
man/r2r.1

Initial implementation of the R2R_SHALLOW random test skip ##tests

---

libr/main/radiff2.c

Some improvements for the radiff2 cli ##tools

---

libr/core/cmd_cmp.inc.c
test/db/cmd/cmd_cw

Show odata/ndata in json and normal output from `cw` ##print

---

libr/bin/p/bin_io.c
libr/core/cbin.c
test/db/cmd/cmd_ih
test/db/formats/mach0/headers

Set Cd4/8 metadata from RBinFields via .ih* ##bin

---

libr/core/cmd_open.inc.c
test/db/io/banks

Handle invalid subcommands under om ##help

---

libr/core/cbin.c
libr/core/cconfig.c
libr/core/cfile.c
libr/include/r_bin.h
libr/include/r_io.h
test/db/cmd/cmd_i

Initial implementation of the bin.aslr ##bin

---

libr/core/cmd_search.inc.c

Add /B to find possible base addresses ##search

---

libr/core/cmd.c

Support internal files in @@. ##shell

---

libr/anal/esil_dfg.c
libr/arch/p/avr/plugin.c
libr/arch/p/gb/plugin.c
libr/arch/p/x86/plugin_cs.c
libr/core/cmd_anal.inc.c
libr/core/cmd_search.inc.c
libr/core/core_esil.c
libr/esil/esil.c
libr/esil/esil_ops.c
libr/esil/esil_toc.c
libr/esil/p/esil_dummy.c
libr/esil/p/esil_forth.c
libr/include/r_esil.h

Add REsil.opstr with 'ae???' command to list ops with description ##esil

---

libr/arch/p/pickle/pseudo.c

This will add python like psudocode to the pickle architecture. This is about half of all instructions.

Add some pseudo commands for pickle ##arch

---

libr/debug/dsession.c
libr/reg/reg.c

Honor Register aliases in RReg.get

---

libr/util/file.c

Fix RFile.new API

---

libr/core/cmd.c

Implement =lj to list sessions in json ##remote

---

libr/core/cmd_cmp.inc.c

Implement ccdf and improve help for ccd? ##diff

---

libr/core/cmd_cmp.inc.c

Honor asm.sub.var and asm.imm.trim in ccd ##diff

---

libr/cons/cons.c

Fix string assert on RCons

---

libr/io/p/io_ptrace.c

Fix amount of read bytes from ptrace ##io

---

libr/bin/format/mz/mz.c
libr/bin/format/mz/mz.h
libr/bin/format/mz/mz_specs.h
libr/bin/p/bin_mz.c
test/db/anal/x86_16
test/db/cmd/cmd_js
test/db/formats/mz/1byte
test/db/formats/mz/cblp0
test/db/formats/mz/unzip

Honor section/segment logic in MZ executables ##bin

---

Makefile
meson.build

Install the r2sdb executable in the bindir ##build

---

libr/core/cmd_search.inc.c
libr/esil/esil.c
libr/esil/esil_ops.c
test/db/esil/intreg

Fix #23839 - Deprecate $$ in esil and have it as a custom op for /E ##search

---

binr/r2r/r2r.c

Fix offroad leak in r2r

---

libr/core/cbin.c
test/db/formats/dwarf

Do not apply relocs in debugger mode ##debug

---

libr/core/cmd_debug.inc.c
libr/core/cmd_open.inc.c
libr/debug/dmap.c
libr/util/str.c
test/unit/test_str.c

Add dm** to iomap all debug maps ##debug

---

test/db/archos/linux-x86_64/cmd_cw

Add a test case for cw in debug mode
Requires: https://github.com/radareorg/radare2-testbins/pull/102

Add a test case for cw in debug mode

---

libr/core/vmenus.c

I use this feature quite a lot, would be nice if undo could work on this too.

Make visual HUD "_" seek undoable ##visual

---

libr/arch/p/rsp/plugin.c
libr/bin/format/pdb/tpi.c
libr/bin/format/pe/dotnet.c
libr/bin/format/pyc/marshal.c
libr/bin/mangling/microsoft.c
libr/bin/p/bin_elf.inc.c
libr/bin/p/bin_xtr_sep64.c
libr/core/cmd_anal.inc.c
libr/core/visual.c
libr/include/r_util/r_asn1.h
libr/io/undo.c
libr/socket/socket_http_server.c
libr/socket/socket_rap_server.c
libr/util/asn1.c
libr/util/asn1_str.c
libr/util/pkcs7.c
libr/util/str.c
libr/util/x509.c
shlr/gdb/src/gdbclient/xml.c
shlr/java/class.c

Fix latest leaks spotted by coverity and indent dotnet.c

---

libr/io/p/io_ar.c
libr/io/p/io_dsc.c
libr/io/p/io_self.c

Riodesc dsc

---

libr/core/cmd_print.inc.c

Fix shifting too much on signed pxkb ##print

---

libr/bin/dbginfo.c
libr/include/r_bin.h

Make r_bin_dbgitem_at api public

---

libr/bin/p/bin_elf.inc.c
libr/lang/lang.c

Fix huge leak when unloading an elf ##bin

---

libr/include/r_io.h

Rename RIOPlugin.widget to RIOPlugin.data ##abi

---

libr/util/lib.c

Try with LOCAL dlopen before global attempt ##core

---

.github/workflows/codeql-analysis.yml

Downgrade the codeql checks to please the ci

---

libr/core/cmd_search.inc.c

Search progressbar honors scr.progressbar and scr.interactive ##search

---

libr/core/cmd_search.inc.c

Don't clear line in search scan

---

test/db/archos/linux-x86_64/cmd_cw

Should work after: 555ed74b5bac3687fdf3e8fdb5f1ab9538439c63.

Enforce that cw debug mode test case prints nothing to stderr

---

libr/bin/bobj.c
libr/bin/p/bin_bflt.c

Fix recentrly introduced double free in the BFLT parser

---

libr/lang/p/qjs.c

Unlimited stack size to fix macos-asan maximum call stack exceed errors

---

libr/core/cmd_info.inc.c
test/db/cmd/cmd_ie

Fix help message for symbol entrypoints ##shell

---

libr/bp/bp_traptrace.c
libr/cons/dietline.c
libr/core/cmd.c
libr/core/gdiff.c
libr/include/r_bp.h
libr/include/r_cons.h
libr/include/r_core.h
libr/include/r_fs.h

R2600 return values

---

libr/bin/p/bin_dex.c

Use binary file instead of 'SourceFile' in dex debug info ##bin

---

libr/bin/p/bin_dex.c
libr/cons/cons.c

Attempt to workaround a false positive warning in gcc

---

libr/arch/meson.build
libr/arch/p/pickle/plugin.c
libr/bin/format/pyc/pyc_magic.c
libr/bin/meson.build
libr/meson.build
test/db/formats/pyc

Add separate user_plugins=python to compile pickle/py code ##build

---

subprojects/sdb.wrap

Install the SDB headers with meson

---

libr/lang/meson.build
subprojects/packagefiles/qjs/meson.build

Move visibility cflags from rlang to qjs

---

libr/core/cconfig.c
libr/core/cmd.c
libr/debug/plugin.c
libr/include/r_arch.h

Slightly better error checking for the debug/arch setup

---

libr/cons/grep.c
libr/include/r_cons.h
test/README.md
test/db/io/resize

R2600 struct mangling

---

libr/core/cconfig.c
libr/core/cio.c
libr/core/project.c

Do not turn off io.va with cfg.debug ##debugger

---

libr/main/r2pm.c
man/r2pm.1

Implement r2pm -R to reload plugins from radare2

---

libr/core/cmd_anal.inc.c
test/db/anal/s390
test/db/cmd/cmd_ao

Fix ao@jmp modifying ar~^pc ##analysis

---

libr/core/cmd_open.inc.c
libr/core/cmd_write.inc.c
libr/io/io.c
libr/main/radare2.c
test/db/anal/x86_32
test/db/cmd/cmd_open
test/db/io/maporder
test/db/io/maps
test/db/io/write

Rename lots of 'om' subcommands to simplify ##shell

---

libr/core/agraph.c
libr/core/canal.c
libr/core/cmd_anal.inc.c
libr/core/cmd_debug.inc.c
libr/core/disasm.c
libr/debug/trace.c
libr/include/r_debug.h
libr/include/r_util.h
libr/include/r_util/r_type.h
libr/meson.build

Draft: R2590 renaming

---

libr/bin/format/dex/dex.c
libr/bin/p/bin_dex.c

Implement DBG_FIRST_SPECIAL dex debug opcode ##bin

---

pkgcfg/r_core.pc.acr

Add -lpthread to the r_core pkgconfig ##build

---

libr/include/r_vec.h

Enforce vector alignment to address invalid accesses ##crash

---

libr/main/rasm2.c

* The behaviour is not the expected
* Requires a refactoring to address it
* At least its not segfaulting now

Fix #23953 - segfault when using `rasm2 -i 6 -E` ##crash

---

libr/anal/block.c
libr/anal/flirt.c
libr/anal/p/anal_a2f.c
libr/anal/var.c
libr/arch/p/x86/plugin_cs.c
libr/bin/dbginfo.c
libr/bin/p/bin_xnu_kernelcache.c
libr/cons/grep.c
libr/core/cmd_help.inc.c
libr/core/project.c
libr/core/visual.c
libr/flag/flag.c
libr/main/rabin2.c
libr/reg/profile.c
libr/search/uds.c
libr/util/graph.c
libr/util/hex.c
libr/util/list.c
libr/util/rvc_rvc.c
libr/util/udiff.c
shlr/ar/ar.c
shlr/zip/zip/zip_close.c
shlr/zip/zlib/gzwrite.c

Fix some issues found by scan-build ##crash

---

shlr/ar/ar.c
subprojects/sdb.wrap
sys/rebuild.sh

Use latest sdb-2.1.0

---

libr/bin/p/bin_dex.c

Extra uleb128 checks in the dex parser

---

libr/bin/bobj.c
libr/bin/dbginfo.c
libr/cons/pager.c
libr/core/corelog.c
libr/include/r_util/r_strpool.h
libr/util/Makefile
libr/util/meson.build
libr/util/strpool.c
libr/util/ustrpool.c

Initial implementation of the unique string pool api ##util

---

libr/anal/c2/kv.c

Implement support for 'typedef' in the new C parser ##types

---

libr/arch/p/bpf_cs/plugin.c
libr/arch/p/evm/plugin.c
libr/core/cmd_anal.inc.c

Honor anal.in value for aavr ##search

---

libr/bin/format/pdb/pdb.c

Handle eLF_MODIFIER in the PDB parser to solve some warnings ##bin

---

libr/magic/funcs.c

This PR fixes a security vulnerability in __magic_file_check_mem() that was cloned from file/file but did not receive the security patch. The original issue was reported and fixed under https://github.com/file/file/commit/6713ca45e7757297381f4b4cdb9cf5e624a9ad36.
This PR applies the same patch to eliminate the vulnerability.
**References**
https://nvd.nist.gov/vuln/detail/cve-2015-8865
https://github.com/file/file/commit/6713ca45e7757297381f4b4cdb9cf5e624a9ad36

Fix: Potential Vulnerability in magic Library

---

libr/core/patch.c
libr/include/r_core.h
libr/main/radare2.c
libr/main/rapatch2.c

ref https://github.com/rodarima/xpatch/
ref https://github.com/radareorg/radare2/issues/23379

Initial rewrite and support the unified rapatch format ##diff

---

libr/core/cmd_print.inc.c
libr/core/patch.c
libr/util/hex.c
test/unit/test_hex.c

Minor code improvements in util/hex.c

---

libr/debug/debug.c
libr/io/p/io_mach.c

WIP: Fixes for RDebug.execute on macOS

---

libr/core/Makefile
libr/core/meson.build
libr/core/patch.c
libr/core/xpatch.c

Refactoring of the xpatch code into a separate file ##diff

---

libr/debug/debug.c
libr/debug/dmap.c
libr/debug/p/debug_native.c
libr/include/r_debug.h

Boolify some debug apis

---

libr/debug/p/native/xnu/reg/darwin-arm64.h

Fix the register profile when using arm64 debugger ##debugger

---

libr/bin/bin.c
libr/core/canal.c
libr/core/cio.c
libr/core/cmd_anal.inc.c
libr/core/corelog.c

Use chunk reads in aae to reduce memory usage for esil emulation ##analysis

---

libr/arch/p/arm/plugin_cs.c
libr/core/canal.c

More micro optimizations for aae ##analysis

---

libr/core/panels.c
libr/core/visual.c
libr/core/visual_tabs.inc.c

Make r_core_visual_applyDisMode internal

---

libr/anal/hint.c

Heavily reduce allocations in RHint.get() ##analysis

---

libr/bin/addrline.c
libr/bin/bfile.c
libr/bin/dwarf.c
libr/core/cbin.c
libr/core/cmd_meta.inc.c
libr/core/disasm.c
libr/include/r_bin.h
libr/main/rabin2.c

Initial API renaming of the dbginfo into addrline

---

libr/flag/flag.c

Microoptimization checking if flag name is a function

---

libr/arch/p/arm/plugin_cs.c
libr/include/r_flag.h
libr/util/skiplist.c

Do not lock archstate inside the arm plugin

---

libr/include/r_io.h
libr/io/p/io_w32dbg.c
libr/io/p/io_windbg.c

Add missing fini callback for RIOPlugin ##io

---

libr/core/cio.c

Dont seek twice to the same location

---

libr/include/r_io.h
libr/io/p/io_windbg.c

* As discussed with condret, it's open/close the ones in charge to manage desc->data

Remove the init/fini callbacks from IO plugins ##io

---

libr/bin/blang.c

Fix #24010 - fix last Go binaries from symbols ##bin

---

libr/bin/mangling/swift-sd.c

When `trylib` is enabled, always call `swift_demangle()` on unmodified input.
Example. Before:
```
r2 SwiftAsynciOS
[0x100007504]> isq~0x100011328
0x100011328 0 ...sxIeAgHr_xs5Error_pIegHrzo_s8SendableRzs5NeverORs_r0_lTRyt_Tg5TATu
```
After:
```
[0x1000076cc]> isq~0x100011328
0x100011328 0 async function pointer to partial apply forwarder for generic specialization <()> of reabstraction thunk helper <A, B where A: Swift.Sendable, B == Swift.Never> from @escaping @isolated(any) @callee_guaranteed @async () -> (@out A) to @escaping @callee_guaranteed @async () -> (@out A, @error @owned Swift.Error)
```

Call swift_demangle on unmodified input ##bin

---

libr/core/cmd_flag.inc.c
libr/flag/flag.c
libr/include/r_flag.h
test/db/cmd/cmd_flags

Flag alias meta

---

libr/anal/global.c
libr/core/cmd_anal.inc.c
libr/core/cmd_flag.inc.c
libr/core/disasm.c
libr/flag/flag.c
libr/include/r_flag.h

Purge metaitems from the flag table if empty

---

libr/anal/c2/Makefile
libr/anal/c2/TODO
libr/anal/c2/kv.c
libr/anal/c2/t/typedef.h
libr/anal/c2/t/typedef.h.txt

Handle typedefs and void arg funcs like the old parser did ##analysis

---

libr/io/p/io_default.c

Cleanup of the main posix io plugin and add stdio:// ##io

---

libr/include/r_io.h
libr/io/p/io_default.c

Dont touch the global io.off from the default io plugin ##io

---

libr/io/io_memory.c
libr/io/p/io_bochs.c
libr/io/p/io_dsc.c
libr/io/p/io_gdb.c
libr/io/p/io_gzip.c
libr/io/p/io_mach.c
libr/io/p/io_procpid.c
libr/io/p/io_qnx.c
libr/io/p/io_r2k.c
libr/io/p/io_reg.c
libr/io/p/io_self.c
libr/io/p/io_sysgdb.c
libr/io/p/io_winedbg.c
libr/io/undo.c

Use io->Oxff instead of 0xff in all the io plugins ##io

---

binr/r2r/r2r.c

Narrowed output for r2r

---

meson.build

Install r2sdb shared library when using meson

---

libr/core/cmd.c
libr/core/cmd_debug.inc.c
test/db/cmd/shell

Fix escaping pipes with nested commands ##shell

---

libr/core/anal_tp.c

Initial refactoring of the type propagation code ##analysis

---

libr/core/anal_tp.c
libr/core/canal.c

Fix a recently introduced division by zero

---

libr/main/radiff2.c
man/radiff2.1

Initial support of xpatch format in radiff2 -X ##diff

---

libr/core/anal_tp.c

One less core reference for the type propagation loop ##analysis

---

libr/cons/grep.c

Fix null deref assert in sorted grep ##crash

---

libr/main/rabin2.c
libr/util/unum.c

Check invalid number in rabin2 -B ##tools

---

libr/bin/addrline.c
libr/bin/bfile.c
libr/bin/dwarf.c
libr/bin/format/mach0/coresymbolication.c
libr/bin/p/bin_dex.c
libr/bin/p/bin_p9.c
libr/core/cbin.c
libr/core/cmd_meta.inc.c
libr/include/r_bin.h
libr/include/r_bin_dwarf.h
test/unit/test_dwarf.c

Rename RBinDbgItem into RBinAddrline

---

libr/bin/addrline.c
libr/core/disasm.c
libr/include/r_bin.h

Deprecate the get_line() callback for plugins ##bin

---

preconfigure.bat

Aim to fix the syntax error in preconfigure.bat

---

libr/bin/addrline.c
libr/core/canal.c
libr/core/cmd_debug.inc.c
libr/core/cmd_meta.inc.c
libr/core/disasm.c
libr/include/r_bin.h

Deprecate r_bin_addr2line ##apibreak

---

meson.build

Don't run 'cp' on windows for #24054

---

libr/core/cconfig.c
libr/include/r_util/r_log.h
libr/util/log.c

Add RLogLevel.fromString() and use it from -e log.level=? ##apibreak

---

binr/r2r/r2r.c

Catch null deref in r2r spotted by the asan fuzz job

---

preconfigure.bat

Install latest meson release on Windows if not available

---

libr/arch/p/tms320/plugin.c

Implement support for big endian tms320 ##arch

---

subprojects/capstone-next.wrap
subprojects/capstone-v5.wrap

Update to the latest capstone v5 and v6

---

libr/anal/var.c
libr/core/cmd_anal.inc.c

Solve the null name issue in the an command ##shell

---

.github/workflows/ci.yml
Makefile
test/Makefile

This is a balance between not timing out nor hitting OOM.

Limit .*asan-fuzz to four jobs and 3/4 the test suite ##ci

---

preconfigure.bat

Fix preconfigure.bat regression related to local environment ##build

---

.github/workflows/ci.yml
binr/r2r/r2r.c
binr/r2r/r2r.h
test/Makefile

Fix R2R_SHALLOW

---

libr/core/cmd_anal.inc.c

Add axffQ and axffqq for addresses instead of names ##analysis

---

libr/include/r_util/r_sys.h

Fix cydia32 build ##ci

---

libr/core/cmd_anal.inc.c
test/db/anal/autoname

Fix command injection vulnerability in .afna ##crash

---

binr/r2r/run.c

Add some bin2strdup guards in r2r to fix an asan-fuzz assert

---

libr/anal/function.c
libr/anal/p/anal_a2f.c
libr/cons/pal.c
libr/core/blaze.c
libr/core/canal.c
libr/core/cmd_anal.inc.c
libr/core/cmd_flag.inc.c
test/db/cmd/cmd_af

Fix behaviour with an empty anal.fcnprefix ##analysis

---

libr/cons/cons.c
libr/core/cconfig.c
libr/include/r_cons.h

Add scr.limit to avoid writing too much data ##cons

---

libr/util/rlz4.c

Yeah I'm not very familiar with ASAN but these changes fix the failing test.
If there is a better way to go about it, let me know.

Fix the ASAN fuzz test related to r_lz4_decompress_block.

---

libr/socket/socket_http.c

Fix curl to return error response and proper code

---

libr/core/cconfig.c
libr/core/cmd_anal.inc.c

Add anal back

---

libr/anal/codemeta.c
libr/anal/meta.c
libr/bin/bobj.c
libr/core/canal.c
libr/core/cbin.c
libr/core/cmd.c
libr/core/cmd_anal.inc.c
libr/core/cmd_api.c
libr/core/cmd_flag.inc.c
libr/core/cmd_help.inc.c
libr/core/cmd_log.inc.c
libr/core/cmd_print.inc.c
libr/core/cmd_project.inc.c
libr/core/core.c
libr/core/corelog.c
libr/flag/flag.c
libr/fs/p/fs_io.c
libr/include/r_util/r_base64.h
libr/util/str.c
libr/util/ubase64.c
shlr/java/class.c
test/unit/test_base64.c

* Its like p6ds but without the trailing newline
* Fix the base64 function signatures
* More consistent with ?e subcommands

Add ?e: command to print base64 strings via rcons ##shell

---

libr/core/anal_tp.c

Remove some debug prints

---

libr/io/p/io_uf2.c

Sync `uf2families` defined in `io_uf2` plugin with [uf2families.json](https://github.com/microsoft/uf2/blob/master/utils/uf2families.json)

Update uf2families ##io

---

libr/core/cmd_flag.inc.c

Optimize fg: 10% faster ##shell

---

libr/cons/cons.c

Fix infinite loop in scr.limit ##crash

---

libr/core/cmd_info.inc.c
test/db/cmd/classes

Bring back icqq

---

libr/core/cmd_anal.inc.c

anal.symsort is not a boolean ##analysis

---

libr/cons/cons.c

Interrupt console activity when scr.limit is reached ##cons

---

libr/bin/p/bin_elf.inc.c
libr/util/regex/regcomp.c

Implement the R_AARCH64_MOVW_UABS_G* relocs for ELF ##bin

---

libr/bin/p/bin_elf.inc.c
libr/include/r_bin.h

Fix arm64 R_AARCH64_PREL64 relocation ##bin

---

libr/bin/format/elf/elf.c
libr/bin/format/elf/elf.h

Memoize section get by name in the elf parser ##bin

---

libr/bin/p/bin_elf.inc.c

Fix unreachable statements in the ELF parser

---

libr/core/cmd_anal.inc.c

Improve scr.analbar percentages in `aaaa` ##analysis

---

libr/cons/cons.c

Minor code dedup in cons.c

---

libr/cons/cons.c

More optimizations for the console writing ##cons

---

libr/core/cmd_print.inc.c

Implement 'pds*' command to add comments for emulated strings ##analysis

---

libr/core/canal.c
test/db/cmd/cmd_afl

inspired by https://bsky.app/profile/philofishal.bsky.social/post/3llqwnk6i3c2k

Implement aflmc to work like uniq but counting ##analysis

---

dist/plugins-cfg/plugins.def.cfg
libr/arch/p/ppc/plugin_gnu.c
libr/arch/p/tms320/gnu/Makefile
libr/arch/p/tms320/gnu/tic30-dis.c
libr/arch/p/tms320/gnu/tic30.h
libr/arch/p/tms320/gnu/tic4x-dis.c
libr/arch/p/tms320/gnu/tic4x.h
libr/arch/p/tms320/gnu/tic54x-dis.c
libr/arch/p/tms320/gnu/tic54x-opc.c
libr/arch/p/tms320/gnu/tic54x.h
libr/arch/p/tms320/gnu/tic6x-control-registers.h
libr/arch/p/tms320/gnu/tic6x-dis.c
libr/arch/p/tms320/gnu/tic6x-insn-formats.h
libr/arch/p/tms320/gnu/tic6x-opcode-table.h
libr/arch/p/tms320/gnu/tic6x.h
libr/arch/p/tms320/plugin.c
libr/arch/p/tms320/plugin_gnu.c
libr/arch/p/tms320_gnu.mk
libr/include/r_arch.h

* C6X is missing because of macro hell, no analop yet

Initial import of the TMS320 gnu disassemblers ##arch

---

libr/core/cconfig.c

Remove function that is suposed to do nothing

---

libr/cons/grep.c
test/db/archos/linux-x86_64/dbg_step
test/db/cmd/cons_grep

Remove max buffer size in grep logic ##cons

---

.clang-format
sys/indent.py

* This one was ripped from r2ai, and r2mcp

Import latest indent tool, aim to replace all the previous

---

libr/bin/p/bin_any.c
libr/include/r_bin.h

Minor code cleanup in the RBin.any plugin

---

libr/include/r_anal.h

Reudce RAnalMetaItem size (48 bits less) ##optimization

---

libr/core/disasm.c
libr/core/visual.c
test/db/cmd/cmd_pd2
test/db/cmd/metadata

Make large data regions to be scrollable in disasm ##visual

---

libr/bin/mangling/swift-sd.c
test/db/anal/jmptbl
test/db/formats/mach0/swift
test/db/formats/mangling/swift
test/db/tools/rabin2

Better demangle some more swift symbols ##bin

---

libr/core/cmd_print.inc.c
libr/util/print.c

Implement 24bit hexdump mode ##print

---

libr/core/cconfig.c
libr/core/cmd_print.inc.c
test/db/cmd/cmd_print
test/db/cmd/cmd_px

Rename hex.offset into hex.addr ##config

---

libr/cons/cons.c
libr/cons/grep.c
libr/cons/pal.c
libr/core/cconfig.c

Reduce the calls to RCons.palUpdate and getctx in cons

---

libr/arch/p/riscv/plugin.c
test/db/anal/riscv

Fix #24153 - jmp/call refs for riscv code ##analysis

---

libr/cons/dietline.c
libr/cons/output.c

Pack all globals from dietline into a single struct and boolify them

---

binr/r2r/r2r.c

Fix null deref in r2r

---

libr/socket/socket.c

Send with no signals ##socket

---

libr/core/cmd.c

Implement @@Fi as an alias for @@i ##shell

---

libr/cons/cons.c
libr/cons/kons.inc.c
libr/core/disasm.c
libr/include/r_cons.h

Use the new RKons api in disasm.c

---

libr/cons/dietline.c

Ignore CSI fixterms and handle shift+return as plain return ##cons

---

libr/cons/cons.c
libr/cons/html.c
libr/cons/pixel.c
libr/core/cmd_anal.inc.c
libr/include/r_cons.h

Do not gotoxy when rendering html ##cons

---

libr/core/cmd_info.inc.c

Fix regression in ie~?

---

libr/core/cmd_anal.inc.c
libr/include/r_types_null.h
libr/util/utype.c

Fix call to r_type_func_args_count ##analysis

---

libr/core/cmd_info.inc.c

Implement iesj to list symbol entrypoints in json format

---

libr/cons/dietline.c
libr/core/cconfig.c
libr/core/cmd_quit.inc.c
libr/include/r_cons.h
libr/main/radare2.c

q!! not saving the history as stated in the help ##shell

---

binr/r2r/run.c
binr/rafind2/Makefile
libr/cons/2048.c
libr/cons/hud.c
libr/cons/input.c
libr/core/agraph.c
libr/core/cmd_anal.inc.c
libr/core/cmd_help.inc.c
libr/core/core.c
libr/core/panels.c
libr/core/rtr_shell.inc.c
libr/core/vasm.c
libr/core/visual.c
libr/core/vmarks.c
libr/core/vmenus.c
libr/core/vmenus_graph.c
libr/core/vmenus_zigns.c
libr/core/vslides.c
libr/debug/debug.c
libr/debug/dmap.c
libr/debug/trace.c
libr/include/r_cons.h
libr/include/r_core.h
libr/include/r_io.h
libr/io/p/io_r2pipe.c
libr/io/p/io_windbg.c
sys/wasi-api.sh
sys/wasi-env.sh
sys/wasi.sh

More radikal cons refactorings

---

.github/workflows/build.yml
sys/static.sh

Static builds for arm64 and i386 ##ci

---

libr/anal/vtable.c
libr/cons/canvas.c
libr/cons/cons.c
libr/core/agraph.c
libr/core/cmd_anal.inc.c
libr/core/cmd_print.inc.c
libr/core/core.c
libr/core/dmh_glibc.inc.c
libr/core/p/core_agD.c
libr/core/panels.c
libr/include/r_agraph.h
libr/include/r_anal.h
libr/include/r_cons.h
test/db/cmd/cmd_ag

RConsCanvas no longer depends on the ConsSingleton

---

libr/util/print.c

Fix #24192 - Fix reg/imm colors in AT&T syntax ##disasm

---

libr/core/disasm.c

Honor user comment colors in multiline wrapped comments ##disasm

---

libr/core/cmd_print.inc.c

Honor endian settings in the pxb output ##print

---

libr/core/cmd_print.inc.c

Clarify inconsistencies in the 'p?' help message ##shell

---

libr/core/cmd_write.inc.c
test/db/cmd/cmd_w

Fix #24209 - p8 <=> w8, old w8 is now wi8 ##shell

---

libr/cons/cons.c
libr/core/agraph.c
libr/core/cmd.c
libr/core/cmd_cmp.inc.c
libr/core/cmd_help.inc.c
libr/core/cmd_mount.inc.c
libr/core/cmd_print.inc.c
libr/core/core.c
libr/core/disasm.c
libr/core/panels.c
libr/include/r_cons.h
libr/include/r_util/r_print.h
libr/util/print.c

Refactoring RPrint and reducing calls to the old cons

---

libr/core/cmd_open.inc.c
libr/core/libs.c
libr/include/r_lib.h
libr/main/rabin2.c
libr/main/ragg2.c
libr/main/rasm2.c
libr/util/lib.c

Boolify the RLib API

---

libr/config/config.c

Fix ej for bool values ##core

---

libr/core/cmd_quit.inc.c

Fix q!/q!! to not save the command history ##shell

---

libr/bin/bobj.c

fix potential memleak in function r_bin_object_new

---

libr/arch/meson.build
libr/arch/p/arc/gnu/arc-dis.c
libr/arch/p/arc/gnu/arc-ext.c
libr/arch/p/arc/gnu/arc-opc.c
libr/arch/p/arc/gnu/arcompact-dis.c
libr/arch/p/arc/plugin.c
libr/meson.build

Make arc plugin build with meson ##build

---

libr/bin/format/mach0/mach0.c

Fix memleak in function _load_relocations

---

libr/lang/p/qjs.c
libr/util/file.c

Add r2.{fdump,fload} apis ##r2js

---

libr/bin/p/bin_pef.c

Fix integer overflow in PEF parser

---

libr/anal/block.c

Fix underflow index access in bb vector - cov1587630

---

libr/bin/d/symclass.sdb.txt

Add strcpy-chk for iic

---

libr/anal/var.c
libr/core/cmd_anal.inc.c

Implement afv*/afvd* and fix afv[srb]? help messages ##analysis

---

libr/cons/canvas.c
libr/core/agraph.c
libr/core/canal.c
libr/core/cmd_anal.inc.c
libr/core/cmd_print.inc.c
libr/core/core.c
libr/core/disasm.c
libr/core/dmh_glibc.inc.c
libr/core/p/core_agD.c
libr/core/panels.c
libr/include/r_agraph.h
libr/include/r_cons.h
libr/include/r_core.h
libr/main/radare2.c
test/unit/test_agraph.c

More RKons refactorings for disasm and graph

---

libr/config/config.c
libr/core/cconfig.c
libr/core/cmd_eval.inc.c
libr/core/project.c
libr/include/r_config.h
libr/include/r_cons.h
libr/main/radare2.c
libr/main/radiff2.c

Remove cb_printf from RConfig

---

libr/core/canal.c
libr/core/cmd_anal.inc.c

Honor RCons instance in the function listing apis

---

libr/anal/class.c
libr/core/cmd_anal.inc.c
libr/include/r_anal.h
libr/io/io.c
test/db/cmd/cmd_ac

AnalClass.list return a string instead of printing it

---

libr/util/str.c
libr/util/table.c
test/unit/test_str.c

Fix the nth limit to split string into a list

---

libr/core/cbin.c
libr/core/dmh_glibc.inc.c
libr/core/dmh_macos.inc.c
libr/core/p/core_a2f.c
libr/core/vmenus.c
libr/core/vslides.c
libr/core/zdiff.c

More RKons refactorings

---

libr/bin/format/mach0/mach0_specs.h
libr/bin/p/bin_dyldcache.c

- add support for global images
- detect stubs islands by checking the map flags if possible
- avoid shifting 32-bit offsets to avoid int overflow on big caches
apart from the first point, it's mostly fixing old issues 😅

Prepare for iOS 26 dyld caches ##bin

---

libr/include/r_util/r_sys.h
libr/main/rarun2.c
libr/socket/run.c
libr/util/sys.c

* Handled from setenv in rarun2

Add RSys.setEnv2() for values with null bytes ##debug

---

libr/core/panels.c

Add system-wide path for default panel layouts ##visual

---

dist/plugins-cfg/plugins.def.cfg
libr/arch/p/sparc/pseudo.c
libr/asm/meson.build
libr/asm/p/sparc.mk
libr/include/r_asm.h
test/db/cmd/cmd_list

Sparc.pseudo

---

libr/anal/function.c
libr/include/r_anal.h

Store timestamp on each registered function for project sync purposes

---

libr/bin/format/elf/elf.c

Initial wip reporting of the ELF debuglink files ##bin

---

libr/main/radare2.c
libr/util/str.c

Fix display of R_SYS_BITS in r2 -v ##shell

---

libr/core/cmd_anal.inc.c

Add ano=: to set function anotation with command output ##disasm

---

dist/plugins-cfg/plugins.def.cfg
libr/core/p/core_writedwarf.c
libr/core/p/java.mk
libr/core/p/writedwarf.mk
libr/include/r_core.h

Initial implementation of the writedwarf core plugin ##bin

---

Makefile
libr/core/panels.c

Fix installing and listing saved layouts ##panels

---

libr/io/p/io_default.c
libr/util/file.c

Inform the user when creating new files ##io

---

libr/cons/cons.c
libr/cons/line.c
libr/include/r_lib.h

Lining freee

---

libr/core/p/core_prj.c
libr/include/r_util/r_buf.h
libr/util/buf.c
libr/util/str.c
libr/util/x509.c
libr/util/x509.h

Some less R2_600 comments

---

libr/include/r_util/r_asn1.h
libr/util/asn1.c

Dont compute asn1 length all the time

---

libr/arch/p/arm/plugin_cs.c
libr/arch/p/evm/plugin.c
libr/arch/p/java/plugin.c
libr/arch/p/x86/plugin_cs.c
libr/core/cmd.c
libr/fs/d/Makefile
libr/fs/d/dospart.sdb.txt

Enable sdb-r for fs/d

---

libr/asm/d/Makefile

Use sdb -r in libr/asm/d

---

libr/main/r2pm.c

Support python virtual environments ##r2pm

---

libr/syscall/d/meson.build

syscalkf jdl

---

libr/core/pseudo.c

Fix overflow bug in pseudo.c

---

libr/core/cconfig.c
libr/core/rtr.c

Reuse http.bind for tcp.islocal ##remote

---

libr/bin/format/elf/elf.c
libr/cons/cons.c
libr/cons/line.c
libr/core/cplugin.c
libr/lang/p/qjs/core.c

Fix few memory leaks in RCons

---

libr/anal/cc.c
libr/core/cio.c
libr/util/buf.c
libr/util/buf_bytes.c
libr/util/file.c
sys/counters.sh

Fix null deref with corrupted types and other code quality fixes for buf

---

libr/core/cmd_write.inc.c
libr/include/r_lib.h
libr/include/r_util/r_buf.h
libr/include/r_util/r_file.h
libr/include/r_util/r_mem.h
libr/io/p/io_default.c
libr/io/p/io_mmap.c
libr/io/p/io_rbuf.c
libr/util/buf.c
libr/util/buf_bytes.c
libr/util/buf_io.c
libr/util/buf_mmap.c
libr/util/file.c
libr/util/mem.c
test/db/anal/wasm
test/unit/test_buf.c

* Kudos to @astralia for spotting the awful bug

Fix oobread when using mmap baked files ##crash

---

libr/util/buf_mmap.inc.c
libr/util/mmap.c
test/db/anal/wasm

Use the safe and atomic mmap read api ##io

---

libr/anal/c2/kv.c

Enum iota is now 64bit

---

Makefile

Add `r2sdb` to list of bin files in the Makefile. Otherwise it will not be removed by a `make purge`.

Add r2sdb to list of bin files

---

libr/core/core.c

Improves autocomplete for r2frida

Parse file and  flag on autocomplete

---

libr/main/radiff2.c
man/radiff2.1

Add radiff2 -o and -l to specify offsets and lengths ##diff

---

dist/plugins-cfg/plugins.def.cfg
libr/anal/cparse.c
libr/anal/p/anal_tcc.c
libr/anal/p/tcc.mk
libr/core/cconfig.c
libr/include/r_anal.h
test/db/cmd/types

Move the tinycc code as a plugin ##types

---

libr/include/r_lib.h
libr/include/r_util/r_json.h
libr/util/json_parser.c

Add the RJSON.get(str|num) apis from r2mcp

---

libr/core/cmd_write.inc.c

Remove filename length limitations in wt subcommands ##shell

---

libr/core/cmd_info.inc.c

Make iO commands print thru RCons ##bin

---

libr/arch/arch_session.c
libr/arch/p/wasm/plugin.c
libr/core/core.c
libr/include/r_arch.h

Add RArch.user with a pointer to RCore*

---

libr/core/cmd.c

Fix -e? ##shell

---

libr/cons/cons.c
libr/cons/grep.c
libr/cons/pal.c
libr/core/pseudo.c
libr/include/r_cons.h
libr/include/r_lib.h
libr/include/r_util/r_print.h
libr/util/print_code.c

Honor RConsColors when highlighting code via pdc or ~:)) ##cons

---

libr/io/p/io_malloc.c
test/db/io/hex

Implement hexfile:// uri handler ##io

---

libr/core/cmd.c
libr/core/cmd_help.inc.c
test/db/io/hex

Implement @xc: and @xf: temporary block modifiers ##shell

---

libr/core/cmd.c
libr/include/r_util/r_xml.h
libr/util/Makefile
libr/util/meson.build
libr/util/rxml.c
libr/util/rxmldom.c

Initial implementation of the RXML DOM API

---

libr/core/core.c
libr/core/rtr.c
libr/core/rtr_http.inc.c
libr/include/r_core.h
libr/include/r_core_priv.h

Fix #24445  - Few less globals and fix libuv build

---

libr/bin/format/elf/elf.c

Implement support for R_AARCH64_RELATIVE for ELF imports ##bin

---

libr/util/mmap.c

Fix the flock regression on Android ##io

---

libr/util/buf.c
libr/util/buf_cache.inc.c
libr/util/buf_io.inc.c
libr/util/mmap.c

Some less mmap crap

---

libr/core/cconfig.c
libr/main/radare2.c

Fix xdg config path ~/.config/radare2/rc and rc.d ##tools

---

libr/core/cfile.c
libr/io/io_desc.c
test/db/cmd/cmd_io

Avoid having files twice after binparsing with uri ##bin

---

man/radare2.1

Changed man page -N option using config paths explained in commit 0205fc03e1

Updated man page with info on configuration files ##doc

---

libr/core/cbin.c
test/db/cmd/cmd_ic

Method len

---

dist/brew/radare2.rb

Add brew recipe in dist/brew ##build

---

libr/main/r2agent.c
man/r2agent.1

Add r2agent -L to list current sessions

---

libr/cons/dietline.c

Fix the invalid key.f15 error when pressing control+return ##cons

---

configure.bat
make.bat
preconfigure.bat
sys/create_r2.bat

Solve the problems encountered in the process of compiling radare2.

Unable to execute `.\preconfigure.bat` ##build

---

libr/util/utype.c

Use RStrBuf and RStr.startsWith in utype

---

libr/core/cbin.c
libr/include/r_bin.h
libr/include/r_lib.h

Add RBinClass instance size and type name fields ##bin

---

libr/anal/codemeta.c
libr/core/p/core_writedwarf.c
libr/util/utype.c

Do not use RCons.singleton() in UType

---

libr/anal/codemeta.c
libr/core/cbin.c
libr/include/r_bin.h
libr/include/r_codemeta.h
libr/include/r_lib.h

Use RStrBuf in RCodeMeta (faster r2ghidra) requires abi breaking

---

libr/bin/p/bin_mbn.c
libr/bin/p/bin_mclf.c

Remove global state in the RBin.mbn plugin ##bin

---

libr/bin/p/bin_ninds.c

Remove global variable from the ninds plugin ##bin

---

libr/core/anal_objc.c

Index __objc_msgrefs xrefs and parse last ss_selrefs ##analysis

---

configure
subprojects/binaryninja.mk
subprojects/capstone-next.mk
subprojects/capstone-v4.mk
subprojects/capstone-v5.mk
subprojects/qjs.mk
subprojects/sdb.mk

Fix #22956 - Update acr to adjust the macppc triplet ##build

---

libr/arch/p/arm/armass64.c

Use RStr.startsWith instead of the manual strncmp

---

libr/util/sys.c

Fix #24523 - Variable 'env' not defined

---

libr/bin/p/bin_xnu_kernelcache.c

Fix #24530 - division by zero in the kernelcache bin parser

---

libr/anal/anal.c
libr/anal/function.c
libr/anal/p/anal_a2f.c
libr/core/blaze.c
libr/core/canal.c
libr/core/cconfig.c
libr/core/cmd_anal.inc.c
libr/include/r_anal.h
test/db/anal/sparc
test/db/anal/x86_32

Pave the road to support dynamic function prefixes ##analysis

---

libr/flag/flag.c
libr/include/r_flag.h

Implement the r_flag_closest_with_prefix api ##flags

---

libr/core/core.c
libr/include/r_bind.h
libr/include/r_lib.h

Add ConfigGetBool callback in RCoreBind

---

dist/plugins-cfg/plugins.android.cfg
dist/plugins-cfg/plugins.def.cfg
libr/include/r_io.h
libr/io/p/io_pvm.c
libr/io/p/pvm.mk

Initial import of the process_vm IO plugin ##io

---

libr/util/file.c

Always fallback to the default "/tmp". Fixes bug in WSL

---

libr/cons/canvas.c
libr/core/Makefile
libr/core/meson.build
libr/core/visual.c
libr/core/vmatrix.c
libr/include/r_core.h

Initial import of the vmatrix mode ##visual

---

libr/core/panels.c
libr/core/vmatrix.c
libr/core/vmenus.c

Fix latest covs in visual modes

---

libr/anal/fcn.c
libr/bin/format/elf/elf_specs.h
libr/bin/format/objc/mach0_classes.c
libr/core/cbin.c
test/db/formats/dwarf

Enlarge symbol name limits aligned to flag sizes

---

libr/include/r_util/r_str.h
libr/util/str.c

Implement r_str_pad2 to avoid using the tls ##util

---

libr/egg/meson.build
libr/egg/p/egg_bind.c
libr/egg/p/sc/Makefile
libr/egg/p/sc/scmangle.py
sys/lint.sh

Initial work towards shellcode mangling

---

libr/socket/socket.c
man/3/r_anal.3
man/3/r_arch.3
man/3/r_asm.3
man/3/r_bin.3
man/3/r_bp.3
man/3/r_config.3
man/3/r_cons.3
man/3/r_core.3
man/3/r_debug.3
man/3/r_egg.3
man/3/r_esil.3
man/3/r_flag.3
man/3/r_fs.3
man/3/r_hash.3
man/3/r_io.3
man/3/r_lang.3
man/3/r_magic.3
man/3/r_muta.3
man/3/r_reg.3
man/3/r_search.3
man/3/r_socket.3
man/3/r_syscall.3
man/3/r_util.3

Autogenerate manpages for all the libraries

---

libr/arch/p/x86_nz/nzasm.c
test/db/asm/x86_64

Fix #7366 - Implement support for shlr/shrx/sarx for x86-64 ##arch

---

libr/egg/p/sc/Makefile
libr/egg/p/sc/scmangle.py
test/db/archos/linux-x86_64/dbg_dmi

Python is an optional dependency again for scmangle

---

libr/core/cbin.c
test/db/formats/dwarf

Fix recent UAF when modifying rawname ##crash

---

libr/util/name.c
test/db/anal/x86_64
test/db/cmd/cmd_ic
test/db/cmd/cmd_is
test/db/cmd/dwarf
test/db/formats/elf/reloc
test/db/formats/mangling/bin
test/db/perf/dex

Consider ~ a char to be replaced with "_" ##flags

---

libr/arch/p/sbpf_cs/plugin.c

Workaround SBPF capstone delta disasm in the arch plugin ##arch

---

libr/core/core.c

Fix code injection bug in TAB from help ##crash

---

libr/core/cmd_print.inc.c

Add help for the ps subcommands ##shell

---

libr/asm/asm.c

Use bpf instructions descriptions for sbpf ##asm

---

libr/io/io_cache.c

Fix io_cache truncation bug

---

libr/core/cmd_mount.inc.c
libr/fs/fs.c
libr/include/r_fs.h
libr/include/r_lib.h

RFSPlugins expose the cmd interface for `m:` ##fs

---

binr/r2r/r2r.c
man/r2r.1

Add r2r -q for quiet testing ##tests

---

libr/core/cmd_anal.inc.c

Fix #24639 - restore subreladdr after calling `ao`

---

libr/core/cmd.c
libr/core/cmd_flag.inc.c
libr/flag/zones.c
libr/include/r_flag.h

Revamped flagzone commands after 9 years ##shell

---

.clang-format
libr/core/clippy.inc.c
libr/core/libs.c
sys/radare2-format

Introduce the new radare2-format script

---

libr/search/search.c
libr/search/strings.c

Use 1024 as maximum valid string ##search
