radareorg/radare2

libr/core/cmd_anal.c, libr/debug/debug.c, libr/debug/dreg.c, libr/include/r_debug.h
This aims to be an enhancement of the command <b>ar=</b>. (#9710)
<b>dr=</b> will come shortly, but it needs more refactoring so that is why I did not manage to take it here yet (short of time).
<pre>
$ r2 gcore.11190 
Setting up coredump: asm.arch <-> x86 and asm.bits <-> 64
Setting up coredump: Registers have been set
Setting up coredump: 14 maps have been found and created
-- Change the registers of the child process in this way: 'dr eax=0x333'
[0x00000000]> ar?
|Usage: ar # Analysis Registers
...
...
| ar=([size])(:[regs])  Show register values in columns
...
...
[0x00000000]> ar=32
eax 0xfffffdfc           ebx 0xffffff80           ecx 0xd4019f11
edx 0x00000000           esi 0x7ede3610           edi 0x7ede3610
r8d 0x00000000           r9d 0x00000000          r10d 0x0000075b
r11d …
=> Enhancement of ar= command

libr/core/cmd.c
When using @b @a @e or any other local modifier that do not work on their own temporary block, the temporary seek (@0x...) was not seek to.
```
[0x00000000]> pd 8 @ 0x0
0x00000000      0000a0e1       mov r0, r0
0x00000004      010000eb       bl 0x10
`-> 0x00000008      feffffea       b 8
0x0000000c      01207047       ldrbmi r2, [r0, -r1]!
0x00000010      00c09fe5       ldr ip, [pc]                ; [0x18:4]=13 ; 24
0x00000014      1cff2fe1       bx ip
0x00000018      0d000000       andeq r0, r0, sp
0x0000001c      ffffffff       invalid
[0x00000000]> pd 4 @b:32 @ 0xc
0x0000000c      0000a0e1       mov r0, r0
0x00000010      010000eb       bl 0x1c
`-> 0x00000014      feffffea       b 0x14
0x00000018      01207047       ldrbmi r2, [r0, -r1]!
```
=> Fix temporary modifiers

libr/anal/meson.build, libr/asm/meson.build, libr/bin/meson.build, libr/bp/meson.build, libr/config/meson.build, libr/cons/meson.build, libr/core/meson.build, libr/crypto/meson.build, libr/debug/meson.build, libr/egg/meson.build, libr/flag/meson.build, libr/fs/meson.build, libr/hash/meson.build, libr/io/meson.build, libr/lang/meson.build, libr/magic/meson.build, libr/parse/meson.build, libr/reg/meson.build, libr/search/meson.build, libr/socket/meson.build, libr/syscall/meson.build, libr/util/meson.build
Related issue: https://github.com/radare/radare2/issues/9636
Name example for Windows: `r_util-2.5.0-git.dll`
Name&Soname example for Linux:
```sh
objdump -x build2/libr/asm/libr_asm.so.2.5.0-git | grep SONAME
SONAME               libr_asm.so.2.5.0-git
```
Meson on Linux also generates relative symlink `libr_blah.so` to `libr_blah.so.XXX` which is installed together with lib.
=> Meson: Add version info for shared libs

libr/include/r_core.h
this is not used anywhere else. i just happened to find this.
=> removed a garbage.

libr/core/cio.c, libr/core/cmd.c, libr/core/disasm.c, libr/include/r_core.h
Fix for  #9750 and #9751 
Adding a flag in RCore to keep track of temporary bit/arch set by @a and @b directives
=> Force @b @a over hints

libr/core/cmd_help.c, libr/core/graph.c
Move scroll to agraph_set_zoom, and check if at max zoom before redrawing the graph.
Zooming out at the max (-10%) zoom always updated the graph and scrolled the screen, despite being impossible to zoom out further. This lagged heavily for complex functions.
=> Fix zoom in visual graph

libr/cons/d/Makefile
Fixing issue in radare2 and Cutter showing 'meson.build' in the list of available colour theme.
=> Exclude meson.build from the list of color schemes

libr/debug/debug.c
Before the patch
1) dsb command was restoring the session and replaying it once to just get the previous instr addr 
2) then it again restores session and replay it until prev instr
After the patch
1) now we restore and replay only once and calculate previous instr addr using opcode length
=> Fix #8198, Avoid restoring and replaying session twice in dsb command

libr/anal/p/anal_v850.c
in the code `word1` is the higher 16 bits and `word2` is the lower 16 bits.
```
ADDI imm16, reg1, reg2
GR [reg2] <- GR [reg1] + sign-extend (imm16) 
+------------------+------------------+
| rrrrr110000RRRRR | iiiiiiiiiiiiiiii |
+------------------+------------------+
rrrrr = reg2
RRRRR = reg1
iiiiiiiiiiiiiiii = imm16
```
Page 66 -> https://www.renesas.com/en-eu/doc/products/mpumcu/doc/v850/r01us0037ej0100_v850e2.pdf
=> [v850] V850_ADD_IMM5 fix #8308

libr/core/cmd_search.c
This is a first attempt to store rop gadgets in a sdb, not a real PR but more a PRFC (a pull request for comments :-)
Gadgets are stored in the following way : 
key: addr_of_instruct_1
value: addr_of_instruct_1(len_op_code_instruct_1)addr_of_instruct_2(len_op_code_instruct_2)...
I started to change the portion of code that calls r_core_search_rop, because the idea would be to call this function only one time, and simply use the sdb to print gadgets once it has been called (and not do the whole search again).
There is quite a few things still to change : 
- Recreate a hitlist from the sdb elements in order to call print_rop with it (or reimplement print_rop to work directly with sdb ?)
- Reimplement the grep functionnality with the sdb (but it sounds a bit weird to do with the way I stored …
=> Rop gadgets are now stored in sdb

libr/anal/p/anal_v850.c
The %lld format expects a long long, but an int was provided on the
stack, so the snprintf was accessing a wrong memory to print %s. Convert
the first argument to long long to solve the issue.
Fixes #9697
=> anal: fix long vs int size issue on 32bit machines

doc/gprobe.md, libr/io/p/io_gprobe.c
The DDC2Bi3 wrapper is used for both DDC2Bi3 and I2C
communication channels, for example HDMI DDC or
I2C Host Interface.
Using this wrapper you can communicate with displays
that are based on Genesis chipsets like the Dell U2410.
Signed-off-by: Dirk Eibach <dirk.eibach@gdsys.cc>
=> io: Add DDC2Bi3 protocol wrapper to gprobe plugin

libr/cons/input.c, libr/core/panels.c, libr/include/r_cons.h
currently panels blink all the time when you scroll them down. try V! and scroll.
it is caused by tcsetattr tries to manipulate terminal when the panels are refreshed up, so just turned it off by adding some code.
=> fixed panels blinking all the time when scrolling

libr/bin/p/bin_smd.c
Changed the endianness of the header symbols `rom_start`, `rom_end`, `ram_start`, and `ram_end` to big endian. This was causing the auto-generated symbol table to show incorrect addresses for those four symbols. The vtable addresses were already correctly interpreted as big endian.
Also changed section and entry addresses to be relative to rom_start rather than ram_start. This was having an effect on the entry point.
=> Changed the endianness of the header symbols

libr/io/p/io_gprobe.c
it built fine without it on OpenBSD
=> OpenBSD doesn't have stropts.h

libr/anal/types.c, libr/core/cmd_type.c, libr/util/p_format.c
After this fix u get 
```
[0x00000000]> to ./pcap.h
[0x00000000]> ts
pcap_pktrec_tcp
pcap_file_hdr
pcap_pktrec_ether
pcak_pktrec_hdr
pcap_pktrec_ipv6
pcap_pktrec_ipv4 
[0x00000000]> tss pcap_file_hdr
24
```
pfs output : 
```
[0x00000000]> .ts*pcap_file_hdr
[0x00000000]> pfs.pcap_file_hdr
24
```
=> Fix #9870 , fix r_anal_type_get_size and handle enum type

libr/bp/bp.c, libr/core/cmd_debug.c, libr/include/r_bp.h
This first attempt will not change functionality. This will add support for toggling a breakpoint for [count] hits. The commands to do this will be db[i](d|e) <addr> [count]. Count is assigned to bp->togglehits, which will be used to determine whether to stop or not. Each time a breakpoint is hit, decrement togglehits. Once togglehits reaches 0, toggle the bp. If togglehits is initially 0, the bp isn't affected.
The next step will be to implement the toggle behavior. I'm still new to the code, but I see a few potential areas I could implement this:
- in r_debug_bp_hit, r_debug_recoil, and/or r_debug_continue_kill -- might not be a good way, since from what I understand, execution is already expected to stop 
- let the breakpoint plugins handle it
Let me know any feedback or how it should …
=> Add initial temp breakpoint support

libr/anal/p/anal_arm_cs.c
- arm/thumb: added REV, REV16, REVSH
- arm64: added REV16, tweaked REV to support any reg size
it's part of https://github.com/radare/radare2/issues/9885
related tests added: https://github.com/radare/radare2-regressions/pull/1276
=> Add more arm/arm64 REV variants

libr/anal/fcn.c
`try_walkthrough_jmptbl` was already working pretty well but wasn't actually propagating the info through xrefs/comments.
I think I fixed some issues where the jump table would be detected as bigger than it should be, see `if (jmpptr == 0)` check with comment. I am not sure why the double dereference is even a thing.
The information now looks like this:
Possible improvements:
- ~~also add flags, not sure which format to use though (see cmd_print.c `_pointer_table`)~~
- ~~references are currently added as null/unknown. Should probably change it to code~~
=> Jmptable fixes + information propagation

libr/io/p/io_r2k_linux.c, libr/socket/run.c
gcc/clang and MSVC have different behavior when defined(...) is generated as a macro replacement. Here the issue is benign but it does not hurt to fix it.
```c
#define FOO
#define BAR defined(FOO)
#if BAR
// gcc, clang
int foo() {return 3;}
#else
// MSVC
int bar() {return 4;}
#endif
```
=> Fix -Wexpansion-to-defined and -Wunused-variable

sys/user.sh
The slash does not cause any bugs but may looks ugly when displaying output.
Example:
```bash
ln -fs "/home/user/radare2-2.5.0/doc/hud" "/home/user/bin/prefix/radare2//share/radare2/2.5.0/hud/main"
mkdir -p "/home/user/bin/prefix/radare2//share/radare2/2.5.0/"
```
=> Remove end slash in ROOT

libr/cons/d/Makefile
Otherwise there will be Makefile and meson.build in /usr/local/share/radare2/.../cons or whatever when using install instead of symstall.
=> Exclude Makefile and meson.build in libr/cons/d in install

libr/util/hex.c, libr/util/lib.c
Otherwise the plugin can't be loaded because of this:
dlerror(~/.config/radare2/plugins/lang_python2.dylib):
dlopen(~/.config/radare2/plugins/lang_python2.dylib, 6):
Symbol not found: _PyUnicode_1BYTE_DATA
Referenced from: ~/.config/radare2/plugins/lang_python2.dylib
Expected in: flat namespace
in ~/.config/radare2/plugins/lang_python2.dylib
=> Fix loading of lang-python plugin

libr/core/cmd_debug.c, libr/include/r_util/r_num.h, libr/util/calc.c, libr/util/unum.c
Can prevent accidental termination of program due to missing `sym.` prefix.
=> Prevent dcu to unknown address

libr/core/project.c
'notes.txt' in the project folder was not deleted when ```Pd project```.
=> Fix 'notes.txt' not deleted when a project is deleted.

doc/macos.md
The [original doc](https://github.com/radare/radare2/blob/master/doc/macos.md#code-signing) isn't particularly readable. I formatted it so it looks like [this](https://github.com/chrihala/radare2/blob/master/doc/macos.md#code-signing). 
I think this is more readable now.
=> Fix markdown formatting to show a list instead of a blob of text.

libr/core/cconfig.c, libr/core/cmd_debug.c, libr/debug/debug.c, libr/debug/p/native/bt.c, libr/include/r_debug.h
- Needed because some code manipulate the stack pointer in unnatural ways (e.g. glibc ELF i386 loader)
- Only for 32-bit x86 (for now)
- Somewhat slow
Screenshot:
=> dbg.btalgo=trace: trace calls for backtrace

libr/core/cbin.c
```idx``` in ```verneed->entries``` of ```iVj``` had invalid json values, thus the resulting json document was invalid. This fix it.
=> Fix iVj invalid json

binr/radiff2/radiff2.c, libr/core/canal.c, libr/core/gdiff.c, libr/include/r_core.h, libr/include/r_diff.h, libr/util/diff.c, libr/util/sys.c
$ radiff2 -g sym._call -A  b c | dot -Tpng > a.png
- we need disasmdiff native in r2, as well as more inter-core commands
=> Use system diff in graphdiff nodes if possible and improve graphviz style

meson.build, sys/meson.py
R2_INCDIR: include\libr -> include
R2_WWWROOT': share\radare2\{R2_VERSION}\www -> share\www
R2_SDB': share\radare2\{R2_VERSION} -> share
R2_ZIGNS': share\radare2\{R2_VERSION}\zigns -> share\zigns
R2_THEMES': share\radare2\{R2_VERSION}\cons -> share\cons
R2_FORTUNES': share\doc\radare2 -> share\doc
R2_HUD': share\radare2\{R2_VERSION}\hud -> share\hud
=> Reduce r2 default subdirs paths for Windows

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h
This is a step towards avoiding unnecessary copies of the buffer, not ready yet to be used instead of `MACH0_(new_buf)` everywhere because of `r_buf_fcpy_at not supported yet for r_buf_new_file` is still an issue when used with an io buffer directly.
Also fixed a couple of reads which assumed all the buffer is loaded in memory.
I'm experimenting with this here: https://github.com/mrmacete/r2-ios-kernelcache
but will be useful in near future for dyld cache too.
=> Add MACH0_(new_buf_steal)

libr/core/cmd.c
Commit ec75785 (Highlight seek line using different background color
(#9853)) makes command `pdf @ ...` not restore the offset. This is
because when executing the `pdf` command, r_core_cmd_subst is called
twice, and core->prompt_offset will at last be the temporary seek
offset.
=> Use a local orig_offset in r_core_cmd_subst

libr/core/hack.c
- near jumps bytes are between 0x80 and 0x90 [(ref)](https://c9x.me/x86/html/file_module_x86_id_146.html)
=> Fixed byte range for near jmps reversing in hack.c

binr/rax2/rax2.c
I would have loved to use r_print_code, but for some reason it's not visible from rax2.c
=> Fix #9986, implemented rax2 -i functionality, to mimic xxd -i

libr/bin/bin.c
I think this is useless now with the new IO.
It prevents me from loading a 150MB+ minidump file into radare2.
=> Remove useless memcheck

binr/rax2/rax2.c, libr/asm/p/asm_x86_nz.c
I found some unreachable code for rax2 -P.
The code was converting some python string/array into hex.
This functionality is already provided by rax2 -F.
Updated the manual to show it.
=> Removal of dead code for rax2 -P

libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_core.h
Now agf supports the following outputs:
```
- non interactive ascii-> agf 
- interactive ascii    -> agfv     
- tiny ascii           -> agft
- graphviz dot         -> agfd  
- graphviz w/ metadata -> agfdm 
- json                 -> agfj 
- json w/ disassembly  -> agfJ  
- gml                  -> agfg  
- SDB key-value        -> agfk 
- r2 commands          -> agf*  
- web/png              -> agfw  
```
Note: this pr doesn't break any existing commands. It only adds new ones. 
Also, I know nested switches are ugly, but I prefer to do code polishing when I'm done with the other types of graphs (agg, agc...) so that I can see better which parts of the code can be generalized.
But please if you have an idea on how this could be improved / written more elegantly don't hesistate to tell me.
=> Support every output format for the bb graph (agf)

libr/anal/xrefs.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/graph.c
* uniform xref output (CODE,CALL,DATA,STRING)
* avoid confusion in `ax` command (e.g. arrows direction)
* introduce `axs`
* remove `afxX` commands. Keep only `afx` to list function references, but remove afx-, afxC, afxc, etc. because there are no "function references" anymore. There are just references in the whole binary, not per-function.
=> [WIP] Xrefs fixes

libr/anal/fcn.c, libr/anal/types.c, libr/anal/var.c, libr/core/anal_tp.c, libr/core/cmd_type.c, libr/core/disasm.c, libr/include/r_anal.h
Fixes #9544 
```
$ r2 ./abdb (bin from issue #9544)
[0x00404d88]> aaa
[0x00404d88]> ?t afta
84.954996
$ r2 ./vim
[0x00055a40]> aaa
[0x00055a40]> ?t afta
150.363169
```
```
$ r2 ./abdb
[0x00404d88]> aaa
[0x00404d88]> ?t afta
5.308898
$r2 ./vim
[0x00055a40]> aaa
[0x00055a40]> ?t afta
13.387865
```
* Refacored the code by spliiting functions and cleanning it up
* Optimized the code by avoiding whole function emulation rather by emulating prev N instr to call
* Avoid creating dupe vars
* Honored ^C , so now it could be stopped :D
=> Refactor and optimize afta

libr/include/r_util/r_buf.h, libr/util/buf.c
Returns a new buffer which is a "slice" of the given one, while sharing its memory. The idea is to be similar to this semantic: https://nodejs.org/api/buffer.html#buffer_buf_slice_start_end
With the following limitations (for now):
- this doesn't work with sparse buffers
- a sliced buffer is `ro`, in the sense it can be written to but not resized (or any other operation which reallocs its bytes) because the underlying memory layout must remain the same (shared with `parent` buffer)
plus:
- fix vaddr / paddr translations (and make them meaningful on slices)
- fix r_buf_fcpy_at to work with slices and with file-backed buffers (at least for reading)
This feature is super useful when dealing with sub-binaries and in general it relaxes the need to make copies of big buffers.
=> Add r_buf_new_slice

libr/core/disasm.c
Better than #10057 in fixing radareorg/cutter#482 since it interacts correctly with asm.strenc and is [cleaner](https://github.com/radare/radare2/commit/e4f2f3311ac35af7107fda820f683016db08ba25) too.
=> Always escape backslashes for pdJ json (take 2)

binr/rax2/rax2.c, libr/util/hex.c
Rax2 -F now autodetects and transforms a js byte array into an hex string.
The expected input format is the one of 'pcJ' in r2, with some degree of flexibility
=> Fix #2639, added support for javascript byte arrays in rax2 -F

libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/include/r_core.h
Support for the following output formats for `agg` custom graph:
```
- non interactive ascii-> blank 
- interactive ascii    -> v     
- tiny ascii           -> t
- graphviz dot         -> d  
- json                 -> j 
- gml                  -> g  
- SDB key-value        -> k 
- r2 commands          -> *  
- web/png              -> w  
```
*NOTE*: this pr will change the behaviour of the **`aggv`** command: now it is renamed to `aggw`. (this is because "v" format is for interactive ascii).
I also added some fixes to my previous pr (for the agf output format support), mostly to remove `\t` tabs in the terminal output.
=> add every output support for agg graph + some agf fixes

libr/anal/d/types.sdb.txt, libr/core/carg.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/include/r_core.h
Fixes : #8785 
```
[0x000036a0]> afcf sym.imp.ioctl
int ioctl(int fd, unsigned long request)
[0x000036a0]> afcf @ 0x000036a0
char *getenv(const char *name)
```
Also removed some dupes and incorrect type from type-sdb
=> Add command afcf to print "return type function(arg1, arg2...)"

shlr/www/index.html
This is reflected when the web service is used.
I have added an input filter for the invalid characters in the names of the files to analyze, using the encodeHtmlEntity() function, applied in the variable x[0].uri
=> radare2_fix_xss

libr/core/cmd_anal.c, libr/core/graph.c
Added the new command `agx` which displays the graph of all the references to the address given. For now it shows only hex offsets, but I was thinking on adding maybe more information in the body of the nodes (e.g. the disasm of the instruction or the which function the referencing instruction is in) in another pr.
Fixed also some bugs with `aggv` and `agfv`, in  particular the mouse wheel was broken (printed garbage) when exiting from them.
=> Support every output format for the xrefs graph (agx)

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h, libr/bin/format/mach0/mach0_specs.h, libr/bin/format/objc/mach0_classes.c, libr/bin/format/objc/mach0_classes.h, libr/bin/mangling/swift-sd.c, libr/bin/obj.c, libr/bin/p/bin_dyldcache.c, libr/bin/p/bin_mach0.c
- still supports only 64-bit caches (but now in theory it's possible to port it to 32-bit too)
- use MACH0_ functions
- parse symbols, sections and classes
- use R_DYLDCACHE_FILTER env variable to symbolicate only a subset of the cache
- rebase unslid caches on-the-fly, properly slide slid caches symbols
Usage: `r2 -e bin.usextr=false path/to/dyldcache/file`
Without tricks it can be very slow to parse all the stuff, but usually the result is worth the waiting.
To speedup things it's possible to avoid loading strings `-e bin.strings=false` if they're not needed.
Otherwise when knowing what to look for, the `R_DYLDCACHE_FILTER` env variable is useful to symbolicate only one sub bin **plus all its direct dependencies**, example:
```
R_DYLDCACHE_FILTER=libsystem_network.dylib r2 -e …
```
=> Improve dyldcache

libr/anal/fcn.c, libr/anal/var.c, libr/core/anal_tp.c, libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/core/vmenus.c, libr/include/r_anal.h
Fixes #6970
```
(fcn) loc.good_arg_anal 12
|   loc.good_arg_anal ();
|           ; arg int arg_8h @ esp+0x8
|           ; CALL XREF from 0x08048066 (entry0)
|           0x08048071      55             push ebp
|           0x08048072      89e5           mov ebp, esp
|           0x08048074      8b442408       mov eax, dword [esp + arg_8h] ; [0x8:4]=0
|           0x08048078      6a00           push 0
|           0x0804807a      58             pop eax
|           0x0804807b      5d             pop ebp
\           0x0804807c      c3             ret
/ (fcn) loc.bad_arg_anal 15
|   loc.bad_arg_anal ();
|           ; var int local_8h @ esp+0x8
|           ; CALL XREF from 0x0804806b (entry0)
|           0x0804807d      55             push ebp
|           0x0804807e      89e5           mov ebp, esp …
```
=> Fix fcn maxstack issue in variable recovery

libr/bin/format/elf/elf.c, libr/bin/format/mach0/mach0.c, libr/bin/p/bin_elf.c
#9599 
- Harmonize ```ihj``` and ```ih``` ELF
- Fix ```ih``` ELF 32 bits (offsets were wrong)
- Change ```ihj``` mach0 (ex: hdr.magic now Magic)
Example ELF 32bits:
```
[0x0804938c]> ih
0x00000000  ELF MAGIC   0x464c457f
0x00000010  Type        0x0002
0x00000012  Machine     0x0003
0x00000014  Version     0x00000001
0x00000018  Entrypoint  0x0804938c
0x0000001c  PhOff       0x00000034
0x00000020  ShOff       0x00013504
[0x0804938c]> ihj~{}
[
{
"name": "ELF",
"vaddr": 0,
"paddr": 0,
"comment": "0x464c457f",
"format": "x"
},
{
"name": "Type",
"vaddr": 16,
"paddr": 16,
"comment": "0x00000002",
"format": "x"
},
{
"name": "Machine",
"vaddr": 18,
"paddr": 18,
"comment": "0x00000003",
"format": "x"
},
{
"name": "Version",
"vaddr": 20,
"paddr": 20,
"comment": "0x00000001",
"format": "x"
},
{ …
```
=> Fix ihj ELF

libr/anal/xrefs.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/core.c, libr/include/r_anal.h
I was bothered that output of xrefs in the disassembly was not sorted. 
Instead of adding yet another "get_*_sorted" variant to xrefs.c, I think generally returning sorted lists will lead to more consistent behavior across r2.
=> Always return sorted xref/ref lists

libr/core/cconfig.c, libr/core/cmd_anal.c, libr/include/r_core.h
Added `graph.extension` which sets with which extension graph commands with the `w` format like `agfw` or `aggw`.
It supports all formats supported by the "dot" (or "xdot") program, that is png, jpg, svg, pdf, ps...
This should fix #9199 
Also added `agw` which is just an alias for `agfw`.
=> Add jpg, svg, pdf.... extensions for 'w' graph output format

libr/bin/p/bin_elf.c, libr/bin/p/bin_pe.c
Issue #9599
- Harmonize ihj and ih for PE
- Delete one useless line in static RList* fields for ELF format (from my last commit)
Example:
```
[0x00407134]> ihj~{}
[
{
"name": "Signature",
"vaddr": 128,
"paddr": 128,
"comment": "0x00004550",
"format": "x"
},
{
"name": "Machine",
"vaddr": 132,
"paddr": 132,
"comment": "0x0000014c",
"format": "x"
},
{
"name": "NumberOfSections",
"vaddr": 134,
"paddr": 134,
"comment": "0x00000004",
"format": "x"
},
{
"name": "TimeDateStamp",
"vaddr": 136,
"paddr": 136,
"comment": "0x5a6de570",
"format": "x"
},
{
"name": "PointerToSymbolTable",
"vaddr": 140,
"paddr": 140,
"comment": "0x00000000",
"format": "x"
},
{
"name": "NumberOfSymbols ",
"vaddr": 144,
"paddr": 144,
"comment": "0x00000000",
"format": "x"
},
{
"name": "SizeOfOptionalHeader",
"vaddr": 148, …
```
=> Fix ihj PE

libr/core/graph.c, libr/core/visual.c
Fixes #6220 
Also fixed the fact that on many visual modes like offset mode (`o`), comment mode (`;`) etc... there was no cursor. Now the mouse is disabled and the cursor is visible.
=> Fix #6220 garbage print when clicking on graph

binr/radiff2/radiff2.c
When diffing two files with `radiff2 -x` bytes are compared beyond the filesize when the filesize is not a multiple of the output width.
For example when comparing two identical files each containing 50 times 0x61, the output of `radiff2 -x` (used master for the test) reads:
```
offset     0 1 2 3 4 5 6 7 8 9 A B C D E F 0123456789ABCDEF    0 1 2 3 4 5 6 7 8 9 A B C D E F 0123456789ABCDEF
0x00000000  61616161616161616161616161616161 aaaaaaaaaaaaaaaa   61616161616161616161616161616161 aaaaaaaaaaaaaaaa
0x00000010  61616161616161616161616161616161 aaaaaaaaaaaaaaaa   61616161616161616161616161616161 aaaaaaaaaaaaaaaa
...
0x00000030! 61610a00000000004100000000000000 aa......A.......   61610a00000000003181010000000000 aa......1.......
```
With this pull request files are only compared up to the …
=> Fix hexdump output of radiff2

libr/anal/diff.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/gdiff.c, libr/include/r_core.h
Now the command `aga` (which before was a dupe of `ags`) represents the data graph, which is basically a refs graph to data sections.
Also, I thought a lot about `agd`, but only graphviz and png formats can be supported because they are the only one that can show nodes background color. I'll return to agd in the future when I'll have implemented node backgrounds in ascii graphs.
Finally, I found out that `agd` was unfinished, and I tried to fix it myself... but after some hours I found out that's a rabbit hole much deeper than I expected, and I only fixed a small bug related to the fingerprinting of the bb nodes before diffing and added some more verbose error handling. 
My doubts on `agd` are:
- Right now it does the diff between the function in the current offset and the function given …
=> Added data graph (aga) + partial support for diff graph (agd) output formats

Makefile, binr/blob/Makefile, libr/cons/d/Makefile
when using `cp`, avoid `-a` and replace it by the most similar arguments: `-PRp`
according to ubuntu man page:
* `-a` : same as `-dR --preserve=all`
* `-d` : --no-dereference --preserve=links
* `--no-dereference` is `-P` (never follow symbolic links in SOURCE)
and `--preserve=all` covers mode,ownership,timestamps,context,links,xattr. POSIX `-p` argument doesn't cover all of that, but I assume it is ok.
=> avoid cp -a: it isn't POSIX defined and doesn't exist on openbsd

libr/Makefile
required since `Bring back libr.* targets in libr even without BUILD_MERGED` efda76cc1
=> run objcopy --localize-hidden on BSD too

libr/core/cmd_print.c, libr/core/cmd_type.c, libr/core/core.c, libr/include/r_print.h, libr/include/r_util/r_ctypes.h, libr/util/p_format.c, libr/util/r_ctypes.c, shlr/tcc/tccgen.c
Fixes #6479 
Changes made : 
```diff
Foo=enum
- Foo.0x1=COW
- Foo.0x2=BAR
- Foo.BAR=0x2
- Foo.COW=0x1
+ enum.Foo=COW,BAR
+ enum.Foo.0x1=COW
+ enum.Foo.0x2=BAR
+ enum.Foo.BAR=0x2
+ enum.Foo.COW=0x1
```
* Moved cmd `tb` under `teb`
* Now `te foo` list all values of foo
```
[0x00000000]> "td enum Foo {COW=1,BAR=2};"
[0x00000000]> te Foo
COW = 0x1
BAR = 0x2
```
Added tests in r2r [#1316](https://github.com/radare/radare2-regressions/pull/1316)
=> Manage types enum more properly

libr/core/canal.c, libr/core/cconfig.c, libr/core/disasm.c, libr/core/graph.c, libr/core/pseudo.c
As suggested in https://github.com/radare/radare2/issues/9798 this PR changes `asm.fcnlines` in `asm.lines.fcn`
=> asm.fcnlines > asm.lines.fcn

libr/core/cmd_search.c
The output should like this : 
```
> /V4 0x2000050 0x20000f0
hits: 1
0x14ca6: 0x20000be
> f ~ hit
0x020000be 4 hit.value.0x020000be
0x00014ca6 4 hit.offset.0x00014ca6
> pd 1 @ 0x00014ca6
;-- hit.offset.0x00014ca6:
0x00014ca6      be00000200     mov esi, 0x20000
> pd 1 @ 0x020000be
;-- hit.value.0x020000be:
0x020000be      ff             invalid
[0x00005600]>
```
=> Fix #9886, Add flag at both offset and value for /V

libr/Makefile
when configure with '--with-syscapstone' option, should link with 'CAPSTONE_LDFLAGS'
=> fix for build with '--with-syscapstone'

libr/core/canal.c, libr/core/cmd_anal.c, libr/core/graph.c, libr/include/r_util/r_str.h, libr/util/str.c
Added global versions of the references graph and of the data graph.
The other kind of graphs (except the callgraph, which was already made) do not need a global version imho, so now I'll focus on finishing correct argument handling.
Also updated the `ag?` help for the new commands.
=> Added 'agR' and 'agA' global references and data references graphs

libr/asm/p/asm_x86_nz.c
The current struct does not allow for [r<8-15>+immediate] addressing because the `reg` and `offset` fields of the union would overlap on the same number, making it impossible to distinguish.
Don't know if the problem applies to other parts of the union. 
Checking if the fix does not break any test
=> Fixed operand struct

libr/asm/p/asm_x86_nz.c
When parsing an instruction like `mov [ebp+eax*4-0x200], N`, the sign of the offset would be parsed as '+' instead of '-' because it's the first sign it encounters.
=> Fixed the parsing of the operand sign

libr/asm/p/asm_x86_nz.c
At the moment, x86_nz parser assigns the exact same attributes to RIP and R8.
This makes it impossible for the assembling function to distinguish them.
Checking if the fix doesn't break anything.
=> Fixed parser ambiguity between RIP and R8

libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/graph.c, libr/core/visual.c
Fixes #8385 and fixes #9716 
Now ag* commands correctly support arguments (there are some exceptions, like for example the import graph, but the ag? help specifies which commands don't take any arguments).
Also, agj and other commands won't print all the functions of the file when provided with the 0 argument: now the special address is `UT64_MAX` (`0xffffffffffffffff` or `-1`) that was already used by `agC` global callgraph
Also, global graphs now work only in the `[graph.from, graph.to]` range.
=> Ag argument handling + fix agj @ 0

libr/core/cmd_anal.c, libr/core/graph.c
This should close #9962 
Now `agft`, and other commands which print tiny graphs to stdout (not interactive) won't print tiny graph edges.
Also refactored some code to use `r_core_cmdf` which is a lot more cleaner than constructing strings and then passing them to `r_core_cmd0`
=> Remove agft tiny graph edges on by default

libr/asm/p/asm_x86_nz.c
Fixed many cases in which x86.nz would assemble `mov [reg], imm` instructions in a wrong way.
This fixes #10129 and #9933.
I also added a lot of tests @ radare2-regressions
=> Rewrite of assembler logic for mov indirect, added many tests

libr/anal/op.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_x86_cs.c, libr/core/cmd_type.c, libr/include/r_anal.h
Fixes #9078 
Currently fixed for archs : 
* X86
* ARM 64/32
* MIPS
* GB (it was already fully implemented)
* Add support for more archs
* Include this for more op type if needed
* Add test for different arch 
* Currently the `R_ANAL_OP_MASK_ALL` used in many place , have to clean that and change to appropriate mask
```
$ git grep "R_ANAL_OP_MASK_ALL" | wc -l
88
```
=> [WIP]  Support RAnalop.dst/src in all archs 

libr/Makefile
libr will have been compiled with openssl support if it was requested, so it also needs to use the openssl LDFLAGS. Otherwise it'll complain at link time about not being able to find the referenced libssl symbols.
Fixes #10154.
=> libr: use openssl LDFLAGS at link time

libr/cons/cons.c, libr/core/disasm.c, libr/include/r_cons.h, libr/util/str.c
`ds_align_comment()` is a bottleneck in disassembly printing. The difference with this is not huge, but it's measurable.
I also removed the "rgb:" check we talked about on Telegram. As far as I can tell, it was used for a different kind of ansi escape sequence for colors that is not used anywhere in r2 anymore, so this check is now unnecessary.
=> Optimize ds_align_comment()

libr/core/panels.c, libr/core/visual.c
how to reproduce the bug
1. get this ctf question binary https://github.com/ctfs/write-ups-2016/tree/master/su-ctf-2016/reverse/serial-150
2. go r2 with r2 -dAA ./serial
3. dcu main
4. e io.cache=true
5. go to either Vpp(doesn't matter how many p in fact) or V!
6. after you enter the mode then you immediately switch to VV from the mode you are in
7. then go back to the original mode by q
8. then proceed step over debugging with S or go back to CLI and keep doing "dso;.dr*"
9. there are no 'hit the breakpoint at' and you will get an user prompt of std::cin at the inappropriate offset
according to my debugging, io.cache had been doing something back there and i fixed the problem by turning off io.cache temporarily when the step over happens then getting the original status back to it …
=> fixed a small yet kinda significant bug

libr/core/cmd_print.c
from:
```
[0x00000000]> pa?
|Usage: pa[ed] [hex|asm]  assemble (pa) disasm (pad) esil (pae) from hexpairs
```
to:
```
[0x00000000]> pa?
|Usage: pa[edD] [asm|hex]  assemble (pa), disasm (pa[dD]), esil (pae) from hexpairs
```
=> Fixed the help of pa? to include paD

libr/bin/pdb/pdb_downloader.c
It appears m$ moved some files and broke our curls...
=> Add -L flag to curl to follow redirects in pdb downloader

libr/core/rtr.c
Before:
```
[0x00000000]> =+ rap://127.0.0.1:1234//bin/ls
Connected to 127.0.0.1 at port 1234
waiting... ok
[0x00000000]> =
6 - rap://127:1234//bin/ls
```
After:
```
[0x00000000]> =+ rap://127.0.0.1:1234//bin/ls
Connected to 127.0.0.1 at port 1234
waiting... ok
[0x00000000]> =
6 - rap://127.0.0.1:1234//bin/ls
```
=> rap: list open connections with full host

libr/core/cmd_anal.c, libr/core/core.c, libr/core/graph.c, libr/include/r_cons.h
1. Added autocompletion for all commands starting with ag*
2. Renamed command "agt" to "abt" (this command found paths in the bb graph, and was decided to be renamed in the ag* pad)
3. Removed graph shortcuts when it's not interactive
=> Added ag autocompletion + final ag* fixes

libr/bin/format/mach0/mach0.c
- it can be 16-bytes long, in that case isn’t NUL-terminated
- so don’t kill the 16th char
- add terminator when needed
For example, in iOS kernel caches there's the `__PLK_DATA_CONST` segment which uses the full 16-bytes for the name
=> Fix mach0 segment name size

libr/core/cmd_print.c
JSON outputted wasn't correctly build due to this condition not correctly checked.
=> Corrected a condition on the first op

libr/core/cmd_print.c
`pxr 0x40 @ rsp` differed from `pxrj 0x40 @ rsp`:
```
$ r2 -d /bin/ls
[0x7f796814fc30]> pxr 0x20 @ rsp
0x7fffd270fe50  0x0000000000000001   ........ @rsp
0x7fffd270fe58  0x00007fffd2710c8e   ..q..... stack R W 0x736c2f6e69622f (/bin/ls) -->  ascii
0x7fffd270fe60  0x0000000000000000   ........ rbp
0x7fffd270fe68  0x00007fffd2710c96   ..q..... stack R W 0x524e54565f474458 (XDG_VTNR=7) -->  ascii
[0x7f796814fc30]> pxrj 0x20 @ rsp~{}
[
{
"addr": 140736724008528,
"value": 1
},
{
"addr": 140736724008544,
"value": 0,
"ref": "rbp"
}
]
```
=> Fix increment in pxrj command (cmd_print.c)

libr/io/section.c
reproduce:
sys/asan.sh
1. r2 debug mode
2. e dbg.trace = true
3. dcu main
4. ood
5. dcu main
then crash
occurred by ood carrying out io_section_cleanup that cleans up all sections, yet the weird RIOSection cache working in some API does not know that and eventually use-after-free happens. 
Actually the caching wasn't that effective in there anyway so I just ripped it off instead of coming up the new way to cache it (i actually came up some but they did not do much so i just totally ripped it off)
=> fixed a problem concerned with dbg.trace and ood  and dcu

libr/anal/xrefs.c
Fix ```axj``` #10179 double quotes bug.
=> fix axj #10179

libr/core/cconfig.c, libr/core/disasm.c
Closes https://github.com/radare/radare2/issues/10165. Split up `asm.maxrefs` into `asm.xrefs.fold` and `asm.xrefs.max`.
`asm.xrefs.fold`: controls how much xrefs can be displayed before folding them in a table like manner (just like how asm.maxrefs did)
`asm.xrefs.max`: controls how much xrefs can be displayed before displaying only the `XREFS (n)` counter.
Also limited the max number of columns in the table like folding to 5 in order to avoid having graph nodes too large (see first screen in https://github.com/radare/radare2/issues/10165)
=> Fix #10165 compact cross references

libr/core/cmd_open.c
`from` is always 0 like in the original function, probably that should be changed but idk where to get that information.
```
[0x00000000]> aeim
[0x00000000]> oj~{}
[
{
"raised": true,
"fd": 3,
"uri": "malloc://512",
"from": 0,
"writable": true,
"size": 512
},
{
"raised": false,
"fd": 4,
"uri": "malloc://983040",
"from": 0,
"writable": true,
"size": 983040
}
]
```
=> `oj` command now shows the correct info, fix #10174

libr/core/disasm.c
There is a flaw in the way pdfj prints the json object. 
For example, if you have an array of N elements, in some cases, you can have a trailing coma due to the fact that the element N-1 printed correctly with r_core_print_disasm_json and added a coma but element N hadn't printed something with r_core_print_disasm_json. So you end up basically with an array like this [{"foo":"bar"},] which is broken.
The solution here is to print an object even if it's empty in order to avoid this issue.
=> disasm.c: r_core_print_disasm_json prints a void object if it has not printed something else before

libr/core/visual.c
Closes #9847 
__EDIT__: 
Remade this pr, now press # to toggle bytes when in disasm view. 
No more turning on by default when switching to cursor.
-----
__OLD_PR__:
When toggling the cursor, `asm.bytes` goes on and off.
However, if the user had specified before that `e asm.bytes = true`, then bytes are kept being shown even when exiting cursor mode.
This is done in a little hackish way:
`asm.bytes = asm.bytes + 1` when switching to cursor mode
`asm.bytes = asm.bytes - 1` when switching off cursor mode
(this means that `asm.bytes = 2` when it was set by the user and then switched to cursor mode),
but doing like this avoids adding another config variable.
Tell me if it's too confusing.
=> Fixed asm.bytes on by default in cursor mode

libr/anal/fcn.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_x86_cs.c
Fixes #10122 
```
|   sym.main ();
|           ; var int local_78h @ ebp-0x78
|           ; var int local_4h @ esp+0x4
|           0x08048540      55             push ebp
|           ...
|           0x08048577      8d4588         lea eax, [local_78h]
|           0x0804857a      89442404       mov dword [local_4h], eax
|           0x0804857e      c70424b28604.  mov dword [esp], 0x80486b2
|           ...
|           0x0804858a      8d4588         lea eax, [local_78h]
|           0x0804858d      890424         mov dword [esp], eax
[0x08048540]> afvR
local_78h  0x8048577,0x804858a
local_4h  0x0804857a
[0x08048540]> afvW
local_78h  
local_4h 
```
```
[0x08048540]> afvR
local_78h  0x8048577,0x804858a
local_4h
[0x08048540]> afvW
local_78h  
local_4h  0x804857a
```
Added test in r2r …
=> Fix afvR and afvW by using RAnalOp.direction 

libr/anal/hint.c, libr/core/blaze.c, libr/core/canal.c, libr/core/carg.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/cmd_print.c, libr/core/cmd_type.c, libr/core/disasm.c, libr/core/p/core_anal.c, libr/core/visual.c, libr/core/vmenus.c, libr/include/r_anal.h, libr/include/r_core.h
Fixes #10248 
* Calculate stacksize till pc addr instead of using fcn->maxstack 
* Implemented a new command `ahr` to set hint for return value of a function  (usefull in cases like malloc , where emulating it is atm not possible)
* And use the hint to propgate struct offset 
Added test in r2r [#1343](https://github.com/radare/radare2-regressions/pull/1343)
=> Use return value hint for struct offset propgation

libr/asm/p/asm_x86_nz.c
Was be fixed #10303 problem with SIB part at which base part is incorrectly defined.
```
1819 if (op->operands[1].scale[0] > 2) {
1820	base = 5;
1821 }
```
In case when second operand define as `[reg * 2 + disp]`, `scale = 2 => base = 0` what is wrong. `base` must be equal is `101` i.e. `5`
=> Incorrectly defined base of SIB part

libr/anal/var.c, libr/core/cmd_type.c, libr/core/core.c, libr/include/r_anal.h
Now u can use `tp` like this : 
```
[0x00000560]> "td struct Books {char  title[50];char  author[50]; char  subject[100];};"
[0x00000560]> tp Books local_e0h
title : 0x00177f18 = Radare2
author : 0x00177f4a = pancake
subject : 0x00177f7c = Reversing
``` 
Added test in r2r [#1346](https://github.com/radare/radare2-regressions/pull/1346)
=>  Support for using variable name in tp 

libr/core/vmenus.c
I added the possibility to rename a variable in Visual mode even without the need of selecting it through the cursor (which is what `dn` does already).
For example, in order to change `local_378h`:
```
[0x00402a02 8% 290 /bin/ls]> pd $r @ main+2 # 0x402a02                                                                                                                     
|           0x00402a02      4156           push r14                                                                                                                        
|           0x00402a04      4155           push r13                                                                                                                        
|           0x00402a06      4154           push r12 …
```
=> Added ability to rename variables far from cursor

libr/include/r_types.h
Fixes regression issue #10313
Not sure why it was removed in the first place? make tests seems to pass so I think its safe to put back.
=> Add r_userconf.h back to include/r_types.h

libr/core/cbin.c
It was using signed integer, which caused the offset to become negative.
Might fix https://github.com/radareorg/cutter/issues/516
=> Fixed wrong int output format in izzj

libr/core/cmd_anal.c, libr/core/graph.c, libr/include/r_cons.h
Closes https://github.com/radare/radare2/issues/10277 and closes https://github.com/radare/radare2/issues/10275 .
r2r pr: https://github.com/radare/radare2-regressions/pull/1348
=> Graph edges improvements

libr/cons/canvas.c, libr/core/panels.c, libr/include/r_cons.h
Rewritten how canvas.c works to handle wide utf8 chars without breaking the panels or graph ASCII layout.
Now canvas, instead of having a single long buffer for the contents of the screen, works with a 2d matrix of variable length rows, which are are enlarged or shortened based on how many "hidden" UTF-8 bytes are printed to screen.
Here's a screen of panels view with utf8 lines and some comments in arabic and braille:
**NOTE**: some languages (e.g., russian) have some bytes that interfere with the old runes system. If this pr works (and won't break any tests) I'll  disable the runes system to use only UTF-8 in a later pr and have global support.
=> UTF-8 support in canvas (panels, graph)

libr/cons/canvas.c, libr/core/panels.c, libr/util/str.c
Closes https://github.com/radare/radare2/issues/10329
also fix a buffer overflow in `r_canvas_gotoxy()`
=> Fix heap overflow in canvas.c + fix utf8 wrong crop in panels

libr/anal/fcn.c, libr/anal/p/anal_x86_cs.c, libr/core/cmd_anal.c
Thanks @rlaemmert for providing test case
- This PR also improves the analysis of MOV instructions on X86
- And extends output of 'ao' to show ireg, scale, ...
=> Add support for x86-32 gcc "mov r,[r*s+d];jmp r" jumptables

libr/include/r_util/r_mem.h, libr/util/mem.c
we usually do not consider the destination buffer as such.
=> Change of r_mem_memzero signature. In a memory clearance context,

libr/core/cmd_type.c, libr/include/r_util/r_ctypes.h, libr/util/ctype.c
* Added `tu name` and `tu*` command
* Initial work on linking union using `tl` (It's not accurate due to some issue which i have commented here [#10032](https://github.com/radare/radare2/issues/10032))
```
[0x000006aa]> "td union Books {char  title[50];char  author[50]; char  subject[100];};"
[0x000006aa]> tl Books = 0x00177f88
[0x000006aa]> pdf
|   sym.main ();
|           ; var union Books @ rbp-0x70
|           ; var int local_8h @ rbp-0x8
|           0x000006aa      55             push rbp
|           0x000006ab      4889e5         mov rbp, rsp
|           0x000006ae      4883ec70       sub rsp, 0x70               ; 'p'
|           0x000006b2      64488b042528.  mov rax, qword fs:[0x28]    ; [0x28:8]=0x1958 ; '('
|           0x000006bb      488945f8       mov qword [local_8h], rax
| …
```
=>  Intial work for union support 

libr/asm/p/asm_x86_nz.c
Removed condition `op->operands[0].scale[0] > 2` for solution problem #10346
=> Was be fixed #10346

libr/cons/canvas.c, libr/util/str.c
This should close #10339 
Also fixes some coverity issues in canvas.c:
if the realloc() inside `expand_line` fails, instead of freeing the entire canvas, just abort the write, or else all future writes will fail (and from what I understand there were many defects just for this problem)
Before considering merging, I would like to wait to check if #10339 is really fixed (I was only able to reproduce it in a virtual machine)
=> Fix panels horizontal scroll glitch + fix some coverity defects

libr/core/graph.c, libr/core/panels.c, libr/include/r_cons.h, libr/include/r_core.h
refactoring included.
g should call the graph on any panel.
d should call the disassembly on any panel.
also about a few fixes for graph,
1. i obviously deleted the not-used parameter passed to API
2. download binary of the ctf question "serial" https://github.com/ctfs/write-ups-2016/tree/master/su-ctf-2016/reverse/serial-150 and r2 -dNAA ./serial then dcu main then agf and you'll see the right side of the graph is cut. so i added extra 2 to the size of width when the api is called with interactive flag being false.
=> the integration between panel and graph has got heaps better now. 

libr/core/cmd_debug.c, libr/debug/map.c, libr/include/r_debug.h
Resolve issue https://github.com/radare/radare2/issues/10323
`dm=.` and `dm.*` weren't added like discussed in that issue. I don't see any other currentaddr+r2 output modifier commands and implementing them would be hacky.
=> Make dm. output like dm and add dmq.

Makefile
Right now only a `make mrproper` will delete the libr/include/r_version.h.
If you're doing a `make clean` everything has to re-build anyway so might as well update the compiled in commit version and all that with it.
=> Add rm r_version.h to make clean

libr/cons/canvas.c, libr/core/panels.c
Fixed some color bugs in canvas.c 
This is a dump of the canvas output before:
Notice how many useless color attr were there that slowed down things (most of the time there was an attr for every char in output).
After:
Now it's a bit better but not perfect. Panels with color are still very slow and laggy, there is still a lot to do.
Fixed a crash when pressing `C` to disable color. Fixed also the 4 new coverity bugs in panels.c
=> Fix color bugs in panels + other coverity issues in panels.c

libr/core/rtr.c, libr/socket/socket.c
Adds a 1sec timeout for accept() to fix the hang on exit when using `=H&`.
=> Add timeout for accept in HTTP Server

libr/core/cmd_debug.c
Tested only on Linux and Windows.
=> dcu: check for dead debugger before continue

libr/debug/debug.c, libr/include/r_debug.h
This is fundamentally a workaround for the fact that radare doesn't distinguish between user defined breakpoints and breakpoints set up as part of the recoil code.
Without this code, r2 will loop indefinitely in some cases when encountering a breakpoint at an instruction with the same length as the breakpoint op.
=> Fixed breakpoint infinite loop error

libr/cons/canvas.c, libr/core/cconfig.c, libr/core/graph.c, libr/include/r_cons.h
Closes #10400 
Added option that reverts to old method of positioning edges. This option is on by default, since old edges were better in most cases. I will continue and try to finish the new edges before release.
This is better than reverting my last graph edges pr since it fixed other small things too (like enlarging of nodes with many edges, and some improvements on vertical layout)
I had changed a test in that pr, so here is that test reverted: https://github.com/radare/radare2-regressions/pull/1364
ALSO I included a typo fix in canvas.c that I forgot in my last pr
=> Revert to old graph edges positioning (added an option)

libr/bin/format/elf/elf.c, libr/core/cbin.c
When SHDR missing failed to load symbols only existing in PHDR.
=> Fix reloc symbols not loaded correctly

libr/core/cmd_debug.c, libr/debug/p/native/linux/linux_debug.c, libr/include/r_debug.h
Add the stop address field to the "di" command
```
[0x7fca80368c30]> dc
child stopped with signal 11
[+] SIGNAL 11 errno=0 addr=0x00b4f000 code=2 ret=0
[0x00b4f000]> di
type=segfault
signal=SIGSEGV
signum=11
sigpid=2730
addr=0x0
bp_addr=0x0
inbp=false
baddr=0x400000
pid=2730
tid=2730
stopaddr=0xb4f000
```
=> Add stop address info to the "di" command

libr/core/anal_tp.c, libr/core/disasm.c
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
void main() {
int length, length2;
char *final;
char *s1 = "Hello";
char *s2 = "World";
length = strlen (s1);
length2 = strlen (s2);
if (length == length2) {
...
}
....
}
```
```
/ (fcn) sym.main 157
|   sym.main ();
|           ; var size_t local_20h @ rbp-0x20
|           ; var size_t size @ rbp-0x1c
|           ; var char *src @ rbp-0x18
|           ; var char *s2 @ rbp-0x10
|           ; var char *dest @ rbp-0x8
|           0x000007aa      55             push rbp
|           0x000007ab      4889e5         mov rbp, rsp
|           0x000007ae      4883ec20       sub rsp, 0x20
|           0x000007b2      488d051b0100.  lea rax, str.Hello          ; 0x8d4 ; "Hello"
|           0x000007b9      488945e8       mov qword [src], …
```
=> Intial work on type propgation

libr/bin/format/pe/pe.c
Changed the `return "UNKNOWN"` to `"UNKNOWN (%d)", type`.
Now, whenever the resource type is UNKNOWN, there will still be the type in parentheses.
=> Added unknown type for rsrc

libr/parse/parse.c
on Darwin and with debug symbols, feat_grep test crashes.
on OpenBSD in non debug mode, feat_grep crashes so
we make the last chunk copy consistent.
=> asm parse fixes.

libr/core/anal_tp.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/util/ctype.c
* Fixed few warnings caused due to `"..."` name with null type params in function  like `fscanf` etc .
* Changed `io.pcache` to `io.cache` only for afta, because some type where not infered due to this !
=> Few fixes for type propagation

libr/bin/file.c
5 seems a bit too generous while 3 breaks tests.
=> R_STRING_MAX_UNI_BLOCKS: 5 -> 4

libr/bin/dwarf.c
=> Fix #10465 - Avoid string on low addresses (workaround) for corrupted dwarfs

libr/anal/p/anal_x86_cs.c, libr/util/str.c
Fixes the non-detection issue in #10473.
=> x86_cs MOV family: set val to 2nd operand if imm and if 1st operand is reg

libr/core/task.c, libr/include/r_core.h
This is better than joining the thread, because pthread_join only allows a thread to be joined by one other thread.
=> Join Tasks using Lock

libr/anal/fcn.c, libr/core/disasm.c
Closes #10474 
It confronts the address of the switch instruction, so it should work even if multiple switches point to the same instruction.
Before:
After:
=> Fold switch cases pointing to the same instruction

libr/core/core.c, libr/core/task.c, libr/include/r_core.h
for #10506 
Reducing the overhead in `task_wakeup()` is not that easy unfortunately, but that one is only called once when starting a task or leaving sleep mode, so it is far less critical than in `r_core_task_schedule()`.
=> Add tasks_running to RCore to reduce tasks overhead

libr/core/cmd_debug.c, libr/debug/p/native/linux/linux_debug.c, libr/include/r_debug.h
Added stopaddr dbg info to dij command
```
[0x00400551]> dij
{"type":"segfault","signal":"SIGSEGV","signum":11,"sigpid":10386,"addr":0,"inbp":false,"baddr":4194304,"stopaddr":0,"pid":10386,"tid":10386,"uid":0,"gid":0,"exe":"/home/invictus1306/Documents/r2conf/init_test/mytests/test1","cmdline":"/home/invictus1306/Documents/r2conf/init_test/mytests/test1","cwd":"/home/invictus1306/Documents/r2conf/init_test/mytests","stopreason":2}
```
=> Added stopaddr dbg info to dij

libr/anal/cc.c, libr/anal/fcn.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_m68k_cs.c, libr/anal/p/anal_mips_cs.c, libr/anal/p/anal_ppc_cs.c, libr/anal/p/anal_sparc_cs.c, libr/anal/p/anal_x86_cs.c, libr/anal/var.c, libr/core/anal_tp.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_type.c, libr/core/disasm.c, libr/include/r_anal.h, libr/include/r_core.h, libr/parse/p/parse_arm_pseudo.c, libr/parse/p/parse_x86_pseudo.c
Fix #10483 
```c
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
/* A simple Hello World program :) */
void funcarg(char *s1 ,char *s2, int c, int d) {
char *final;
final = malloc (c + d);
if (final) {
strcpy (final, s1);
strcat (final, s2);
printf ("%s\n", final);
free (final);
}
}
void main (int argc, char *argv) {
char *s1 = "Hello";
char *s2 = " r2-folks";
funcarg (s1, s2, strlen (s1), strlen (s2));
}
```
```
[0x0000081e]> s sym.funcarg 
[0x000007aa]> pdf
/ (fcn) sym.funcarg 116
|   sym.funcarg ();
|           ; var int local_28h @ rbp-0x28
|           ; var int local_24h @ rbp-0x24
|           ; var int local_20h @ rbp-0x20
|           ; var int local_18h @ rbp-0x18
|           ; var int local_8h @ rbp-0x8
|           ; CALL XREF from 0x0000086d (sym.main)
| …
```
=> Intial support for register base args 

libr/cons/canvas.c, libr/include/r_util/r_str.h, libr/util/str.c
R2 doesn't support fullwidth characters (chars that take up two cells of the terminal), this can be reproduced easily by creating a comment like `CC 逆向工程
` and going to either visual disasm, graph or panels view. 
Sometimes the line right below gets duplicated, or the panels and graph layout break down:
This is because those characters occupy two cells instead of one, thus messing up all layout calculations:
This pr is intended to fix those kind of things. Please, test it if you can, as there are a lot of corner cases. I fixed all of the things I could see, but I'm not sure I've got them all.
=> Support for fullwidth characters of the CJK charset (Chinese, Japanese, Korean).

libr/core/panels.c
resizing in V! used to work like 
1. you resize
2. go back to default layout
which was totally not vim-like (and vim should be ALWAYS ANYONE'S ideal obviously), so fixed and made it work like the way vim does.
=> resizing properly works with split screen

libr/core/visual.c
Issue: https://github.com/radare/radare2/issues/10397
Note: This ended up being a messier solution leveraging a strpool to allocate and store the final string to feed to the less function. This is because we need to pass the entire colorized argument list to the less function. If anyone has a prettier/more efficient way of doing this I'm happy to update.
Before:
After:
Tested on Debian Linux & macOS.
=> Add Colors to Visual Help

libr/anal/op.c, libr/core/anal_tp.c, libr/core/cmd_anal.c
As u could see from above pic that there is no type information available for argument **`s1`** in function **`funcarg`** , but we infer that by propgating type from **`main`**
Also added few test in r2r [#1387](https://github.com/radare/radare2-regressions/pull/1387)
=> Add type propgation for args from caller to callee function

travis-extract-var.sh
* this is a long comment (just for test on travis)
=> travis-extrat-var: correctly escape variables

libr/core/cbin.c
Prints `{"strings":}` otherwise.
=> Fix Invalid JSON when using izzj with no file opened

libr/cons/dietline.c
Dietline supports `backward_kill_word` (M-DEL) but not the forward equivalent, which I use very frequently in emacs/bash, so I've implemented it.
More information on the expected behavior is documented in the [bash manual.](https://www.gnu.org/software/bash/manual/html_node/Commands-For-Killing.html)
=> Add support for M-d (kill_word)

libr/core/cconfig.c, libr/core/graph.c, libr/include/r_cons.h, libr/util/graph.c
So, this is my second try at improving jump tables edges. Here are the main changes:
1. If a node has more than 2 edges, than those edges are centered in the middle of the node
2. If a node has more than 2 edges, those edges are sorted based on the x coordinate of their destination. This way they won't overlap when "bending". You can test this by moving the switch block with H and L and see how the bendpoints change accordingly.
3. Edges with the same origin and destination are merged, so that we have only one edge for multiple cases in one node, resulting in much more clear screen when there is a jumptable.
4. Killed the graph.altedgepos variable that I introduced in my last pr.
This is before:
This is after:
I tried to test it a lot, there are still a few minor things to fix but this …
=> Improve jmptbl edges, second try

libr/core/cmd_debug.c, libr/core/linux_heap_glibc.c, libr/include/r_heap_glibc.h
fix heap dmh for tcache in 32bits (debian9 testing 32bits)
fix hash calculation of libc-dbg file (debian9 32bits)
=> two fixes for working with heap in 32bits

libr/core/graph.c
Closes #10558
Here are a few screens of the result:
=> Add shortcuts in mini graph + colorize shortcuts

libr/cons/dietline.c
In my comment on #10656 I mentioned that `kill_word` should move the killed region into the kill ring (emacs terminology, it's called "clipboard" in the code). I implemented this behavior for both `kill_word` and `kill_backwards_word`, as well as making the actual yanking more compliant (yanks to the current index, rather than to the end of the line).
Expect more tomorrow, as I'm planning to do more work to make Dietline more compliant with the readline conventions.
=>  Make yanking more compliant with bash conventions 

libr/cons/dietline.c, libr/core/core.c, libr/core/panels.c, libr/core/visual.c, libr/include/r_cons.h
Closes #10671
includes a bit of refactoring, from `line->offset_index` to `line->offset_hist_index`
=> File completion in V! > open file + file history for up/down arrow keys

libr/core/cmd.c, libr/core/core.c, libr/core/graph.c, libr/core/panels.c, libr/core/task.c, libr/core/visual.c, libr/core/vmenus.c, libr/include/r_core.h, libr/include/r_util/r_signal.h, libr/util/signal.c, libr/util/thread.c
The idea is to enqueue mini-tasks (so-called oneshots) for the stuff that should be done on a signal. These oneshots are much lighter than real tasks, because they are not run in an own thread, but they also cannot be scheduled, they simply run until they are done.
I had to block signals around locking core->tasks_lock to prevent deadlocks when a signal handler is called while it is still locked.
=> Fix Segfaults when resize signals occur with running background tasks

libr/core/cmd_cmp.c, libr/core/core.c, libr/include/r_core.h
Fixes #10710
This function can be used to explicitly re-connect a core to cons. I also removed the old_num in core, because this is handled by the function as well.
=> Add r_core_bind_cons()

libr/core/graph.c, libr/util/graph.c
Closes #10719 
Basically the fix was letting r2 set up duplicate edges AT FIRST, 
then deleting them after r2 set up backedges.
Not allowing dup edges was interfering with backedges or edges drawing in general, in particular cases (where there was a backedge from a direct neighbour).
=> Fix #10719 line graph not correctly

libr/core/disasm.c, libr/core/graph.c
Closes #10690 
Before:
After:
Also, there were some errors in the delete_dup_edges function I introduced in my last pr:
1. ASAN gave a use after free, which was fixed by using r_list_foreach_safe and a bit of iterator pointer juggling
2. It made more than half of useless checks. Now it takes at least half the time (however I didn't measure how much it impacted overall performance)
=> Fix #10690 + fix delete_dup_edges 

libr/core/disasm.c
=> Compact xrefs

binr/rabin2/rabin2.c
So that rabin2's json output can be tested via non-base64 tests.
=> End rabin2 json output with newline

binr/rabin2/rabin2.c
Revert #10742 since the reason given is false.
=> Revert #10742 "End rabin2 json output with newline"

libr/cons/d/bold, libr/cons/d/consonance, libr/cons/d/cutter, libr/cons/d/dark, libr/cons/d/darkda, libr/cons/d/defragger, libr/cons/d/focus, libr/cons/d/lima, libr/cons/d/matrix, libr/cons/d/monokai, libr/cons/d/ogray, libr/cons/d/pink, libr/cons/d/rasta, libr/cons/d/sepia, libr/cons/d/smyck, libr/cons/d/solarized, libr/cons/d/tango, libr/cons/d/twilight, libr/cons/d/white, libr/cons/d/zenburn, libr/core/vmenus.c
Closes https://github.com/radare/radare2/issues/10047 and closes https://github.com/radare/radare2/issues/9966
The problem with the coloring in pxr was not the code, but the missing of ai.* colors in most colorschemes. I added them manually, trying my best to respect each scheme's own style. If you find any any inconsistencies, report them!
pxr example:
Visual types:
=> Colorize pxr + use color palette for visual types menu

libr/anal/p/anal_arm_cs.c
This fixes the esil to correctly set the carry flag for ARM Thumb emulation.
This in reference to issue #10577
=> Fix ARM_INS_CMP ESIL to correctly set carry bit

libr/anal/anal.c, libr/anal/d/Makefile, libr/anal/d/meson.build, libr/anal/d/spec.sdb.txt, libr/core/anal_tp.c, libr/core/cbin.c, libr/core/cconfig.c, libr/include/r_anal.h
```c
printf ("fmt : %s , %u , %d", ...)
```
We now parse format string to infer types like `const char *`, `unsigned int` , this would be helpful when we don't have any function signature to infer type from .
Fixes #10574 
Added test in r2r [#1402](https://github.com/radare/radare2-regressions/pull/1402)
=> Add type propagation via format string parsing

libr/core/vasm.c
Thanks to @Maijin that reported it!
This fixes the following segfault:
To reproduce: If you go to visual assemble and type:
`jmp $$; jmp $$; jmp $$; ...`
at the 1100th character typed or so you'll get a buffer overflow and a segfault
=> Fixed nasty segfault in vasm.c

libr/cons/canvas.c, libr/cons/canvas_line.c, libr/core/cconfig.c, libr/include/r_cons.h
Closes #204 
Added new config var: `graph.dotted`, default to False. 
Fixed a bunch of bugs utf8 related in canvas too.
=> Dotted lines for conditional jumps in graph

libr/cons/dietline.c, libr/core/cmd.c, libr/include/r_cons.h
Closes #7649 
Since I couldn't reuse RLineHistory, I added a simple list to RLine to keep last sdbshell commands. 
I also check that a duplicate command is not inserted more than once (like dietline does)
=> Separate command history for sdb shell "ks"

libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_x86_cs.c
The only two uses of the `REPEAT` ESIL instruction were for ARM64 `REV` and x86 `SAR`, so I rewrote the ESIL for those two instructions without `REPEAT`. This was one of the things that required using capstone in radeco (radareorg/radeco-lib#188).
I also added ESIL for ARM64 `REV32` while I was at it.
=> Remove uses of `REPEAT`

libr/cons/dietline.c
Current master branch segfaults when you type `o` in visual mode.
=> Fixed segfault with Vo

binr/rax2/rax2.c
If the user's input ends in a 'f' character, rax2 will interpreted it as a float. This is problematic when the input is in hexadecimal format because 'f' is within the hexadecimal alphabet. 
```
$ rax2 -ke 0xdeadbeef
Fx4f5eadbf
```
This PR verifies that the input is not in hexadecimal format before converting it to a float. This will produce the expected output.
```
$ rax2 -ke 0xdeadbeef
0xefbeadde
```
=> Verify input is not in hex before interpreting as float

libr/cons/canvas_line.c, libr/core/cconfig.c, libr/core/graph.c, libr/include/r_cons.h
1. Bring back `t` and `f` hints in graph. Governed by variable `graph.hints`. Defaults to True.
Added command `#` to toggle hints while in graph view.
2. Use a different style for backedges. 
I tried using braille characters, but the result was not good (braille points are a 2x4 table, unfortunately all even numbers, lines were decentered and the visual effect was worse than normal hyphens (`-`)).
So I ended up using **dashed** lines for backedges. I think it is the most clear way to differentiate them from both normal edges and conditional edges. Take a look in this screens:
On a different terminal with different font, a conditional backedge:
=> Restyling graph backedges + bring back 't' and 'f' hints

libr/bin/format/pe/pe.c
- SectionAlignment in some EFI files is smaller than 4K (#9929)
- Give a warning if section vaddr is not aligned
=> PE: section alignment can be smaller than 4K

libr/egg/egg_Cfile.c
Apparently both gcc and clang enable stack protection by default. This makes shellcode compilation fail with a linker error.
=> Add -fno-stack-protector to ragg2 CFLAGS

libr/bin/format/mdmp/mdmp_pe.c, libr/bin/format/pe/pe.c, libr/bin/format/pe/pe.h, libr/bin/p/bin_pe.c
This lets `rabin2 -i` show the import things in some PE files in which vsize is zero in their section headers.
I think the PE section code is a mess. The PE_(r_bin_pe_get_sections) function overrides bin->num_sections which originally means the number of sections in the section header, but I still don't know how to rewrite it as other code uses bin->num_sections.
=> refactor and fix something about section vaddr in PE

libr/core/visual.c
Closes https://github.com/radare/radare2/issues/10886
=> Fix arrow keys not working in visual refs mode

libr/anal/meta.c, libr/core/cmd_meta.c, libr/core/disasm.c, libr/include/r_util/r_str.h, libr/util/str.c
Color in comments created some problems in cutter:
Reported by @fcasal (thanks!)
This does not fix _100%_ of the cases, but _99%_ of them. (e.g. some ascii escapes will still be seen if a user sets a special vartype comment with `Ct` containing UTF8 chars in it, but that's pretty rare, and required more major changes, if needed I'll do it in another pr)
=> Fix: color ascii escapes in json output

libr/core/core.c
Since commit 9620ffab1607219f11a151aea32b9a15a43c97fd, `cfg.newtab=1` has been broken. This PR reinstates the behavior: print command descriptions instead of just simple command listing.
=> Print help if cfg.newtab=true

libr/anal/var.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_type.c, libr/core/core.c, libr/include/r_core.h
This should close #10857 
Command syntax for ag* commands slightly changes:
1. No more [fcn addr] argument; this was useless, now it only uses core->offset. If you want to draw graph of a function with an offset different from the current one, just do `agfv @ other_offset`. The only exception is `agd` command, because you must provide the offset of the function to diff against.
2. Now the `w` (image) format provides an argument, which is the file path to save the image to. If no path is provided, the image is displayed immediately (like before). Slight refactoring of r_core_graph_cmd().
3. Updated ag? help accordingly to this changes. Sent a pr https://github.com/radare/radare2book/pull/139 to r2book too.
4. Comments like ";arg1" will be of the same color of the declaration of arguments, …
=> Add "save to file" to ag*w commands + colorize comments like ";arg1"

libr/core/disasm.c, libr/util/str.c
So I don't know how I managed to miss it but I didn't push my last commit in the previous pr https://github.com/radare/radare2/pull/10898 and there were still ascii escapes in the json output :(
Also it wasn't working with asm.cmt.right=0, now it is fixed there too
=> Fix color ascii escapes in json output, again

libr/asm/arch/hexagon/hexagon.c
The name is so common that it can interpose or be interposed by other modules.
224:ut32 constant_extender = 1;
is also bad. Please fix it
=> Move global `tmp` to function-scope

libr/core/anal_tp.c
Fixes #10925 
```
|           ; var int canary @ rbp-0x8
|           0x0000081a      55             push rbp
|           0x0000081b      4889e5         mov rbp, rsp
|           0x0000081e      4883ec30       sub rsp, 0x30               ; '0'
|           0x00000822      64488b042528.  mov rax, qword fs:[0x28]    ; [0x28:8]=0x1a60 ; '('
|           0x0000082b      488945f8       mov qword [canary], rax
....
|       `-> 0x000008da      90             nop
|           0x000008db      488b45f8       mov rax, qword [canary]
|           0x000008df      644833042528.  xor rax, qword fs:[0x28]
|       ,=< 0x000008e8      7405           je 0x8ef
|       |   0x000008ea      e8e1fdffff     call sym.imp.__stack_chk_fail ; void __stack_chk_fail(void)
|       |   ; CODE XREF from main (0x8e8)
|       `-> …
```
=> A simple detection and auto-renaming of stack canary

libr/cons/cons.c, libr/cons/dietline.c, libr/cons/pal.c, libr/cons/rgb.c, libr/core/core.c, libr/core/graph.c, libr/include/r_cons.h
This is my attempt to address issue #8476
It is still a proof of concept, since for now it only works in visual offset prompt. But it works everywhere you can call the offset prompt (in visual mode, in panels mode, and in graph mode).
The idea is to make it as general as possible, so it can also be used elsewhere. 
The major change here is not only in the visual representation of autocompletion, but also the fact that this offers autocompletion as-you-type.
Here's a gif of how it looks:
The keybindings are more or less equal to vim's: up/down arrow keys or Ctrl-n/Ctrl-p to move selection, Enter to select item. Tab to invoke the autocompletion window 
**Feedbacks and code reviews are more than welcome!** I tried to make the code as clean as possible and tried my best to avoid overly …
=> Vim-like autocompletion in visual offset prompt

libr/cons/less.c
Closes #10926 
Also added 'N' alias of 'p' to jump to previous match (to stay consistent with vim keybindings)
=> Fix highlight in visual help mode

libr/util/format.c, libr/util/uleb128.c
What it did before:
```
[0x00000000]> pf [3]u
0x00000000 = [ 0, 0, 0 ]
[0x00000000]> pf [3]ub
0x00000000 = [ 0, 0, 0 ]
0x00000000 = 0x00
[0x00000000]> pf uu
0x00000000 = 0
0x00000000 = 0
^D
```
Now:
```
% ni -C debug
ninja: Entering directory `debug'
[3/55] Generating symbol file 'libr...ha/libr_util.so.2.8.0-git.symbols'.
% ~/Dev/Bin/radare2/debug/binr/radare2/radare2 -
[0x00000000]> pf uu
0x00000000 = 0
0x00000001 = 0
[0x00000000]> pf uuub
0x00000000 = 0
0x00000001 = 0
0x00000002 = 0
0x00000003 = 0x00
[0x00000000]> pf [3]ub
0x00000000 = [ 0, 0, 0 ]
0x00000003 = 0x00
[0x00000000]>
```
=> Fix uleb128 decoding `pf u`

libr/cons/dietline.c, libr/core/core.c, libr/core/disasm.c
The vartype comments did not reset the background color correctly. Included a small fix for multiline comments too.
Also now you can scroll the autocompletion widget with pag up/pag down and home/end keys.
Renamed `draw_selection_widget` to `selection_widget_draw` to be consistent with the naming of the other methods
=> Fix vartype comments background color + add pag up/down and home/end keys in autocompletion widget

libr/bin/p/bin_bootimg.c
Actually, I'm not sure this is a good fix. It just prevents the division by 0, but the binary does not seem to be valid, so there should be some error/warnings some where.
Shall we prevent this binary from being loaded? Not sure.
@radare ?
=> bin/p/bin_bootimg: do not divide by 0

meson.build, shlr/meson.build
we need to handle sdb meson.build file with subprojects. For now I'm
extracting most of its current content here, so that it will be easier
to update sdb later.
=> meson: copy most of the stuff out of sdb dir

libr/include/r_types.h
It cannot be portably implemented in standard C. The null pointer dereference is a common implementation but actually an undefined behavior which asan will report runtime error: member access within null pointer of type ...
Just use `<stddef.h>`
=> r_offsetof: use offsetof

binr/r2pm/meson.build
On Exherbo (and probably other distributions) `/usr/x86_64-pc-linux-gnu/bin/` is where binaries are stored, not `/usr/bin/`
=> r2pm: install r2pm in bindir instead of $PREFIX/bin

libr/core/anal_tp.c
when calling get_src_regname on an invalid or unaligned address, r_core_anal_op returns a null pointer, which must be checked in get_src_regname.
=> fix segfault in get_src_regname

shlr/meson.build
The old versions of affs.c btrfs.c have warnings.
=> meson: disable unused grub fs/*.c files

libr/core/cmd_print.c
This also makes `x 2 @x:90` (len > temp blocksize) honor the temporary block.
Ideally `l` (lines) and `len` (bytes) should be unified. `pxl` has already used multiplication so no special handling here.
=> Simplify length handling of `p` commands

libr/anal/d/types.sdb.txt, libr/anal/var.c, libr/core/anal_tp.c, libr/core/disasm.c
Fixes #10850 
```
/ (fcn) main 646
|   main (int argc, char **argv, char **envp);
|           ; var int local_8h @ rsp+0x8
|           ; var int local_10h @ rsp+0x10
|           ; var int local_28h @ rsp+0x28
|           ; var int local_30h @ rsp+0x30
|           ; arg int argc @ rdi
|           ; arg char **argv @ rsi
|           ; DATA XREF from entry0 (0x561d)
|           0x00003d40      4157           push r15                    ; [14] -r-x section size 72505 named .text
|           0x00003d42      4156           push r14
|           0x00003d44      4155           push r13
|           0x00003d46      4154           push r12
|           0x00003d48      55             push rbp
|           0x00003d49      53             push rbx
|           0x00003d4a      89fd           mov ebp, edi …
```
=> Rename and retype arguments as argc and argv in main function

libr/core/cmd_anal.c
Breakpoints were not being hit after analyzing with the aaa command.
=> Quick fix to prevent afta messing up with the debugger

libr/core/cbin.c
`bin.baddr` is a config var and is not read-only.
=> Add baddr to iI

libr/core/cmd_anal.c
It seems that all analyses except java only set `switch_op->addr` and `case_op->addr/jump`.
=> Add switch_op output to "afbj"

libr/core/disasm.c
There's no logic in keeping `asm.tabs.off` whenever there's no offset (`asm.offset = false`).
This is a little UI fix, will look better on Cutter as well.
=> Remove extra tabs when there's no offsets

libr/core/cmd_anal.c
Make `graph.offset` independent on `asm.offset` in the `agJ` (`agfJ`) command.
If `graph.offset` is set to true or false - show offset in graph regardless of the value in `asm.offset`. This will give the users of Cutter (which uses `agJ`) more flexibility.
=> Quick improvement for graph.offset (mainly for Cutter)

libr/asm/p/asm_x86_nz.c
Only for 32 bits. Broken for 64 bits.
=> Fix #10987 - Drop bracket requirement for LEA if constant operand

libr/core/cmd_search.c, libr/include/r_reg.h, libr/reg/reg.c
```
0x01057924      b806000002     mov eax, 0x2000006
0x01057929      0f05           syscall
```
After @radare 's PR, there was bunch syscall missing due to the rax and eax miss-match issue in 64 bits bins, the PR tries to fix that issue!
=> Improve syscall search

shlr/tcc/tccpp.c
R_SYS_DIR is either "\" or "/" if on Windows or non-Windows respectively. We replace a hard-coded path separator with R_SYS_DIR[0] to ensure compatibility with all platforms.
This doesn't take into account that Windows supports both path separators but we'll cross that bridge when we get to it.
=> Ensure we use correct platform path sep (fixes #11063)

libr/core/cbin.c
*i* command deletes all custom defined types because **bin_info** calls **r_core_anal_type_init** that resets _sdb_types_
```
$ r2 ./binary
> to header.h
> ts
type1
type2
type3
...
> i
...
>ts
>
```
=> WIP: Fix core->anal->sdb_types reset after i cmd

libr/core/disasm.c
The pointer to the hint of the decompiler state is sometimes copied and used as `core->parser->hint`. When the `ds` is freed, the hint is also freed, leading to a use after free if `core->parser->hint` is ever used again (like in `filter()` in parse.c)
=> fix ds->hint use after free

libr/anal/p/anal_wasm.c, libr/bin/format/wasm/wasm.c, libr/bin/p/bin_wasm.c
Before the patch
```
$ r2 bins/wasm/expr-if.wasm
[0x00000000]> s sym.fnc.0
[0x00000032]> aa
[0x00000032]> pdf
/ (fcn) sym.fnc.0 28
|   sym.fnc.0 ();
|           0x00000032      2000           get_local 0
|           0x00000034      4100           i32.const 0
|           0x00000036      46             i32.eq
|           0x00000037      047f           if (result i32)
|           0x00000039      4101           i32.const 1
|           0x0000003b      05             else
|           0x0000003c      4102           i32.const 2
|           0x0000003e      0b             end
|           0x0000003f      0b             end
|           0x00000040      06             invalid
|           0x00000041      00             trap
|           ;-- fnc.1:
|           0x00000042      4100           i32.const 0
| …
```
=> Wasm analisys

libr/anal/anal.c
"Invalidating" the esil state is a bad idea here, because it is still referenced in other parts of core struct.
=> fix anal->esil use after free

libr/core/cmd.c
It is generally a bad idea to execute HTML source code. To reproduce:
- open any binary
- enter the following commands:
```
e scr.html=1
.dr*32
```
This will execute the HTML resulting from `dr*32`, as shell commands (due to the `&nbsp;`).
The fix is to save and restore the is_html setting of the context.
=> fix command interpret when scr.html is on

shlr/java/class.c
When attributes are not read from Java class, there
is a risk of pointer dereference when freeing
afterwards.
=> Fix #11102 Attempt.

libr/core/cmd_debug.c
I couldn't find any implementation of the `dco` command, I stopped searching at commit 34d41b897f8d8c3e69ba7cfe7216ad160d98ecc5 (2012).
=> cmd_debug: remove dco command help

libr/bin/format/dex/dex.h
These structs are defined in the way that no #pragma pack is needed.
=> Remove #pragma pack to suppress -Wpragma-pack-suspicious-include

libr/core/cmd_print.c
```
"The variable 'l' is being used without being initialized."
00 r_core!failwithmessage+0x234
01 r_core!_RTC_UninitUse+0xa4
02 r_core!cmd_print_blocks+0x4f2 [c:\sources\cutter\radare2\libr\core\cmd_print.c @ 2366] 
03 r_core!cmd_print+0x976 [c:\sources\cutter\radare2\libr\core\cmd_print.c @ 3847] 
04 r_core!r_cmd_call+0x249 [c:\sources\cutter\radare2\libr\core\cmd_api.c @ 237] 
05 r_core!r_core_cmd_subst_i+0x3037 [c:\sources\cutter\radare2\libr\core\cmd.c @ 2904] 
06 r_core!r_core_cmd_subst+0x4df [c:\sources\cutter\radare2\libr\core\cmd.c @ 1933] 
07 r_core!r_core_cmd+0x42e [c:\sources\cutter\radare2\libr\core\cmd.c @ 3608] 
08 r_core!r_core_cmd_str+0x5e [c:\sources\cutter\radare2\libr\core\cmd.c @ 3857] 
09 cutter!CutterCore::cmdj+0x73 [c:\sources\cutter\src\cutter.cpp @ 188] 
```
=> Fix uninitialized local causing rtc failures

libr/core/core.c
Added some error handling to fix that.
```
r2 /bin/ls
[0x00005430]> aa
[0x00005430]> s=
0x54f0
[0x00005430]> ss main
[0x00003bb0]> s=
0x54f0
[0x00003bb0]> s [
[0x10102464c457f]> s=
0x54f0 > 0x3bb0
```
More info here https://github.com/radare/radare2/issues/11145
=> Fix #11145. Additional error handling

libr/core/cmd_seek.c
Same error as described in https://github.com/radare/radare2/pull/11160 but appears only when -escr.interactive=0
Shouldn't actually seek on error
```
$ r2 -escr.interactive=0 /bin/ls 
[0x00005430]> s ]
[0x00000000]> 
```
I will add r2-regression tests for this cmd_seek bug when this pull will be merged .
=> Fix superfluous seek on error while -escr.interactive=0

binr/r2pm/r2pm
align package names across all packages.
linux, freebsd and mac should all have column. otherwise ignored.
=> r2pm OCD fixes, search list aligned with column

libr/bin/p/bin_dex.c
Blindfix in the sense that I know very little about the dex format.
=> Fix #11126 - fix clusterfuzz dex crash

libr/anal/meta.c, shlr/sdb/src/array.c
https://github.com/radare/sdb/pull/156/files
```
% time (repeat 10 ~/Dev/Bin/radare2/release/binr/radare2/radare2 -p t1 -c '' -Q a.out)
( repeat 10; do; ~/Dev/Bin/radare2/release/binr/radare2/radare2 -p t1 -c '' -)  1.21s user 0.05s system 98% cpu 1.277 total
% time (repeat 10 ~/Dev/Bin/radare2/release/binr/radare2/radare2 -p t1 -c '' -Q a.out)
( repeat 10; do; ~/Dev/Bin/radare2/release/binr/radare2/radare2 -p t1 -c '' -)  0.62s user 0.08s system 96% cpu 0.729 total
```
sdb can be optimized a lot and become more readable if you use some coverage tool (with radare2-regressions tests) and remove redundant code (it might be risky to remove the check here).
=> Optimize sdb_array_add_num: always use SDB_NUM_BASE and don't check for decimal

libr/cons/canvas.c
Inserting an element into a sorted array does not need full insertion sort.
Fixes #11164
=> Replace sort_attrs (insertion sort) with a single insertion

libr/anal/rtti.c, libr/anal/rtti_msvc.c, libr/core/cmd_anal.c, libr/include/r_anal.h
I am aware that there is already msvc demangling in bin and it would intuitively make sense to reuse that here. However while the class name format in rtti looks very similar to the one used for symbols normally, it is different.
Since msvc mangling is not officially documented and I wasn't able to find any other place where this kind of class name mangling was used by msvc other than rtti, I decided to add it to the rtti code.
Tests: https://github.com/radare/radare2-regressions/pull/1446
=> MSVC RTTI class name demangling

libr/core/disasm.c
`ds_print_meta_infos` igored the `len` argument for its `buf` argument and blindly trusts the `sdb`, which in some cases is longer than the buffer. This leads to out of index access to this buffer and incorrect data in the disassembly. To actually fix this however it is necessary to rewrite larger parts of the code.
=> provisional fix for buffer out of range in ds_print_meta_infos

libr/core/core.c
fix type confusion in r_core_anal_hasrefs_to_depth (libr/core/core.c)
The newest version of radare2 will crash with command "v!" on my laptop, which leads me to a type confusion in vfprintf parameters. Since I have tried to fixed it locally, I just submit my commit as well.
I have viewed the guideline but this is a minor change and I don't think it deserves a new branch anyway
=> fix type confusion

libr/asm/arch/msp430/msp430_disas.c
General cleanup of opcode selection and invalid opcode handling. Also
fixes the bug of two-operand instructions being decoded as six-bytes
long instead of four bytes long (#11000). Also fixes some out of bounds
reads.
Fixes #11000
=> msp430 disassembly: clean up and bug fix

libr/anal/bb.c, libr/anal/fcn.c, libr/anal/p/anal_arm_cs.c, libr/include/r_anal.h
This is my attempt to fix arm jump table issue #11099 and fix my problem at https://github.com/radare/radare2/issues/3201#issuecomment-411599449. This below is arm binary uses for testing.
[switch_table.zip](https://github.com/radare/radare2/files/2305747/switch_table.zip)
To reproduce switch_table binary.
```
% r2 ./callback.elf
-- Remember to maintain your ~/.radare_history
[0x000103cc]> s sym.input_handler2
[0x000105b0]> af
[0x000105b0]> pdf
```
[ctfzone_mobilebank.zip](https://github.com/radare/radare2/files/2305754/ctfzone_mobilebank.zip)
To reproduce using mobile_bank binary.
```
% r2 ./mobile_bank.45115ff5f655d94fc26cb5244928b3fc
-- THIS IS NOT A BUG
[0x0001082c]> s 0x11284 
[0x00011284]> af
[0x00011284]> pdf
```
Now arm switch case is displayed in visual graph.
=> Fix arm jump table issue #11099

libr/core/cmd_anal.c
Seems to do it
```
[0x0001ece0]> k
aeim.fd=7
[0x0001ece0]> aeim-
[0x0001ece0]> k
[0x0001ece0]> om=
00  0xe0000000 |----------------------------------------------------------------------------------------------------#| 0xe0100000 rw- 11 cortex
01  0x50000000 |------------------------------------#----------------------------------------------------------------| 0x50080000 rw- 10 gpio
02  0x40000000 |----------------------------#------------------------------------------------------------------------| 0x40080000 rw- 9 io
03  0x20007560 |--------------#--------------------------------------------------------------------------------------| 0x20008000 rw- 8 stack_dummy
04  0x20000000 |--------------#--------------------------------------------------------------------------------------| …
```
=> Fix #11223 -aeim.fd use sdb instead of flagspace as database

libr/anal/p/anal_msp430.c
This fixes the bug with moves to PC register not being recognized as
jumps.
=> msp430 analysis: support emulated branch instr

libr/io/io.c
ubsan reports this when calling
r_core_esil_step (core, UT64_MAX, NULL, NULL);
in anal_tp.c:r_core_anal_type_match. This does not matter in reality, but silent it anyway.
=> Fix minor -fsanitize=pointer-overflow when addr=0 && vaddr=UT64_MAX

libr/core/cmd_write.c, libr/include/r_list.h, libr/io/cache.c
Fix the handling of [to] in wc- [from] [to]
=> Make wc- invalidate all (fully or partially) overlapping cache

binr/radare2/radare2.c, libr/core/cconfig.c, libr/core/linux_heap_glibc.c, libr/include/r_heap_glibc.h
the tcache parsing is controlled by glibc.tcache
Created some more options : 
dbg.glibc.fc_offset: First chunk offset from brk_start
dbg.glibc.ma_offset: Main_arena offset from his symbol
dbg.glibc.tcache: Set glib tcache parsing
Now its possible to relocate offsets to main_arena and first chunk if needed
This flags only affects if tcache parsing is enabled
=> glibc tcache parsing checked by a config flag, no more preprocessor

libr/bin/format/pe/pe.c, libr/util/ctype.c
Before this patch, a function automatically renamed to "sub.strlen_123"
was identified as a call to strlen, thus the strlen signature was added
as a comment next to a call to that function. This patch prevents that
behaviour.
=> util: try to guess function name only when it contains "dll_"

libr/lang/p/pipe.c
I am having issues in Cutter, where this waitpid call never returns. Specifying WNOHANG here fixes the issue.
It would makes sense to me since the child process could have already quit when waitpid is called, can't it?
=> Use waitpid with WNOHANG in lang_pipe_run()

binr/r2agent/r2agent.c, libr/io/p/io_mach.c, libr/io/p/io_self.c, libr/socket/proc.c
Changes 9 with SIGKILL as 'kill' operand.
=> Do not hardcode 9 for SIGKILL

libr/util/regex/regcomp.c
Fixes a segmentation fault when running this command: `"/c/ ; ;"`
=> Added NULL check in r_regex_comp func

libr/anal/p/anal_wasm.c, libr/asm/op.c, libr/core/canal.c
with the given use case there was an overflow
above the upper end of the stack.
=> fix #11275 attempt.

libr/util/sys.c
Do not call sigaction or sigaddset with SIGKILL, as SIGKILL can not be
caught or blocked.
Put all signals in the mask for blocking before installing signal
handlers.
Also block SIGINT.
=> libr/util: Fix signal mask setting and handler installation

sys/shellcheck.sh
shellcheck.sh update
removed hardcoded list of scripts
disabled shellcheck xml format
The plan is to have the list of scripts generated (on first use) instead of trying to maintain list.
Added simple checkbashisms example and  do we really need the xml report  from checkscript?
=> WIP: Remove hardcoded list of scripts

libr/anal/fcn.c
Based on:
```
anal.bb.align: Possible space between basic blocks
```
the check `!(bb->addr & (anal->opt.bbs_alignment - 1))` is wrong and should be removed.
=> Fix #11337 - Fix function that is missing a basic block

sys/user.sh
1. If `$0` doesn't have a path component, then `dirname` is going to return "`.`" which is the same as `$PWD`. So `dirname($0)` and `dirname($PWD/$0)` are equivalent here.
1. If `$0` is an absolute pathname, then `$PWD/$0` causes breakage. Thus this pr.
=> sys/user.sh: use dirname($0) instead of dirname($PWD/$0)

binr/radare2/radare2.c, libr/core/cfile.c, libr/core/cmd_anal.c, libr/core/cmd_open.c, libr/core/core.c, libr/core/disasm.c, libr/include/r_io.h, libr/io/io.c, libr/io/io_private.h, libr/io/ioutils.c, libr/io/map.c, libr/io/section.c
cc @MaskRay 
All the "batch" operations which for performance reasons  are done without updating the skyline on every add_map, open_at, etc. were actually inside the `r_io` library. So we should just make them private to the module to avoid confusion to users of r_io. This will also make easier to change implementation details in the future.
=> WIP: remove skyline from public API

binr/radare2/radare2.c, libr/cons/cons.c, libr/cons/input.c
Fixes async-signal-safety and changing errno within the signal handler
for SIGWINCH, which can cause crashes and maybe security issues.
For async-signal-safety make the signal handler just set a flag, which
is checked for while waiting for input (pselect).
=> libr/cons: Do proper signal handling, use pselect

libr/anal/p/anal_arm_cs.c
writeback('!' in ldr) for ldr instruction was not implemented.
i added writeback for ldr with imm.
for example ldr ip, [r3, 4]! should do 
ip  = r3 + 4
r3 += 4
probably should also add this not only for imm.
test:
`r2 -a arm -b 32 -c 'wx 04c0b3e51111111122222222' -qc 'dr r3=4;ar r3,ip;aes;ar r3,ip' -`
=> fix arm ldr esil write back.

libr/core/visual.c
=> Fix garbage printed when vspliting with large output

libr/cons/cons.c, libr/core/cmd_help.c
- avoid the ugly lack of space between the command and its description in the usage lines.
- avoid the confusing sections (cf. 'i?')
- prettier general help (cf. '?') -> use r_core_cmd_help instead of
r_cons_printf (#7967)
with help and advices from jeisonwi <3
=> several inline documentation enhancements

libr/cons/d/xvilka
I don't know if it's only for me, but I already have solarized theme on my terminal, and `xvilka` theme looks really great, apart from the nops which become almost invisible. I guess making them less visible was done on purpose, but I think it still makes sense to see them, even if less compared to other instructions.
=> cons/d/xvilka: make nops a bit more visible

libr/core/panels.c
=> Fixed "placing a breakpoint by F2 does not refresh the Panel"

libr/search/rsa-find.c
Fixes crash in `r2 -c '@x:909192;/Cr;' -`
=> Fixes one crash of #11407

libr/core/cmd_help.c
The "l" command is currently missing in the help.
=> Mention "l" command in help text

libr/anal/p/anal_arm_cs.c
While writing an r2wars bot at r2con, I found these missing emulated str pre/postindex.
This is only mildly tested, but should work.
=> r2con: ESIL: fix arm64 emulation for str pre/post index

libr/core/cmd_open.c
condret made me fix this, this PR is a fix related to his talk.
=> cmd_open: Make 'on' use r_io_open_at.

libr/core/cmd_eval.c
- Adding a command ('ecoc') to print current color theme (c->current).
- Documenting the available themes JSON listing.
- defining a specific 'eco?' for themes related commands.
- Adding a cute little arrow to point current theme when listing themes.
- Replacing nextpal() with r_core_list_themes(), for the list, so the
code is less confusing (it's still used elsewhere ('ecp', 'ecn'), didn't remove it)
- Correcting several typos in eval docs
=> Several themes related changes [r2con]

libr/core/disasm.c
Closes #11419 
Also removed unused function r_core_print_fcn_disasm (I guess it is deprecated, since now disasm is printed by r_core_print_disasm)
=> Removed duplicate refline on local labels

libr/anal/meta.c, libr/core/cmd_meta.c
This is a fix for the `Ct` command functionality causing https://github.com/radare/radare2/pull/11465.  It ensures the proper behavior in the CLI (it's supposed to be more like `CC` than the ones handled by `cmd_meta_others`.)  It also fixes the `Ct` output lines in the `rc` project files from the `Ps` command, since they seemed to be wildly outdated or otherwise incorrect (it was `Ct size @ addr # comment` whereas the correct syntax, according to the help, is `Ct[?] [-] [comment-text] [@addr]`, identical to `CC`.)
=> Fix #11464, reinstate Ct functionality

libr/core/cfile.c
In 764a3cc, the code got moved upper, but one case got forgotten,
since it did depend on va to be updated before, which wasn't moved.
Fix #11454
=> Evaluate va before applying workaround for raw binaries

libr/include/r_io.h, libr/io/io.c, libr/io/ioutils.c
There were introduced in siol but it is apparent that nobody uses the
API in the year. They make up a significant unused part of IO that distract readers enough and would hamper further IO cleanups.
Their introduction was probably an instance of XY problem. They were supposed to facilitate analysis, esil and debugging io but how they could benefit the features is never clearly justified.
Usually, you not only need raw bytes but also metadata attached to them.
You would have to add a layer on top of RIOAccessLog anyway, render them not so useful.
These stuff are still in git histories. They can be revived anytime when their values are clearly testified.
=> Remove RIOAccessLog

libr/anal/d/types-linux.sdb.txt
[This hlt instruction on line 128](https://sourceware.org/git/?p=glibc.git;a=blob;f=sysdeps/i386/start.S;hb=688903eb3ef01301d239ab753d309d45720610a7#l128) shows that the glibc developers do not assume 100% that `__libc_start_main` will not return, so neither should we.
=> __libc_start_main might return

libr/core/cmd_print.c
This fixes a crash when running `pd` when `asm.decoff` is enabled.
The `off` argument in the sprintf statement should be removed as it is redundant and doesn't match the format string.
=> Fix #11480 Fix crash when asm.decoff is enabled

libr/util/unum.c
There is no reason for the list returned by r_num_str_split_list
to have a link with a variable called 'free', and this cause crash with
ASAN, as seen on https://github.com/radare/radare2/issues/11407
=> Fix r2 -c '?btw 1 1 1' /bin/ls

libr/util/hex.c
r_hex_str_is_valid is called only once from r_reg_arena_set_bytes,
to find the size of the hexadecimal string. However, it stop
at the first space, while the method used for the conversion
r_hex_str2bin is skipping space and continue to convert.
So with a long enough string passed to drw and arw, it is possible
to crash r2, as reported in https://github.com/radare/radare2/issues/11407
=> Fix r_hex_str_is_valid to handle space like r_hex_str2bin

libr/cons/input.c
Fixes two bugs; puts pselect in a loop to enable resizing window more
than once before there is any input, and reset sigwinchFlag to zero when
resizing window.
=> libr/cons: Fix SIGWINCH logic

libr/core/cmd_print.c
Since bb->size is a int, we should use %i, not %lld, as this cause
a error with linters (lgtm.com in this case).
=> Fix format string for dsb

libr/core/vmenus.c
Since we are using the name addr all around, lgtm.com complain
about it (and likely other linters). Looking at the issue, it seems
that we do not need a global variable, since addr is reset each time
at the start of r_core_visual_anal, and seems to be unused by others
functions.
=> Remove global for addr since that's uneeded

binr/radare2/radare2.c, libr/core/cconfig.c, libr/core/cfile.c
Motivation for this is that I'm trying to run `tk func.__libc_start_main.noreturn=false` in my `~/.radare2rc` but can't because the type sdb files are loaded after `~/.radare2rc` is processed and thus the change above is overwritten.
=> cmd.load: Run when binary is loaded

libr/core/cbin.c
Added column headers when viewing strings, sections, imports, exports or symbols in a binary, which makes it easier to understand information given from the i command.
Also added a [Strings] message when printing strings with iz to improve consistency with other i commands.
=> Info headers (r2con)

libr/core/cbin.c
Fix https://github.com/radare/radare2/issues/11348
=> Kill the _end section flags and fix flag size

libr/core/panels.c
Currently, the '.' command in visual panels mode will not to seek to the PC register, unless "cfg.debug" is set to true. This is conflicting with the visual mode, where the '.' command seeks to the PC register regardless of "cfg.debug" state.
=> Make the '.' command more consistent between visual and visual panels modes

sys/build.sh
Building radare2 with default parameters crashes on the Raspberry pi because there are too many parallel jobs.
This commit adds as suggestion to run the build with a different parameter reducing the build load on tiny targets.
=> Make compilation on Raspberry Pi more user friendly

libr/util/calc.c
Since str is a fixed array of R_NUMCALC_STRSZ, str[i] will crash
with ASAN if i == R_NUMCALC_STRSZ, as it happen with the loop
and 'i++'
Fix another issue reported on https://github.com/radare/radare2/issues/11407
=> Do not crash if a string with a size of R_NUMCALC_STRSZ is passed

libr/core/cmd.c
Subtraction of unsigned numbers always yields a positive number. Adds
casts to st64 to give the intended result.
=> libr/core/cmd.c: Fix related to unsigned numbers

libr/bin/p/bin_wasm.c
This PR addresses the following problems in handling of WASM binaries:
- **Fix issue #11399: use-after-free in symbols():**
Commit 7e083b57f introduced the issue #11399. The list referenced by
`codes` in `entries()`, is the same list that `bf->g_codes` is pointing at.
By freeing it, we introduce a use-after-free in a subsequent call within
`symbols()`, where we try to iterate over the list that `bf->g_codes` is
supposed to be referencing.
- **Fix memleak during loading of WASM binaries:**
A memory leak is reported by ASAN when handling WASM binaries. It is
caused by multiple allocations of `RBinInfo` structure. First, `RBinInfo`
is allocated within a call to `size()` from `r_bin_object_set_items()`. Then
there is another, explicit allocation of a `RBinInfo` structure through
a call to the …
=> Fix a use-after-free and a memory leak in handling of WASM binaries 

libr/core/core.c, libr/core/panels.c, libr/include/r_core.h
1. save/layouts are gone (functionally) so got that right back.
2. panels load the saved layouts at first so that user doesn't need go all the way to "Load" menu
3. panels keep the same layout in the same session unless user changes that.
=> Save/Load layouts are somehow accidentally gone so got that back, and more

libr/util/buf.c
Subtraction of unsigned numbers always yields a positive number, thus
R_MAX (0, b->length - b->offset) is always b->length - b->offset,
instead of the intended.
=> libr/util/buf.c: Fix related to unsigned numbers

binr/radare2/radare2.c, libr/core/cconfig.c, libr/core/linux_heap_glibc.c, libr/include/r_heap_glibc.h
accept @addr at dmhm & dmhb & dmh & dmhj
fix dmhb x:not_arena infinite loop
fix chunk free/alloc threaded arenas
split r_resolve_main_arena from update_main_arena
add function is_arena
remove unncessari *initial_brk parameter
merge print_heap_segment & print_heap_mmaped & print_mmap_graph & print_heap_graph
dmhj supports tcache in threaded arenas
general use of r_num_get
print status at dmhg
chunk sizes calculated without flags
=> linux_heap_glibc: refactor

libr/anal/var.c, libr/include/r_types.h, libr/include/r_types_base.h, libr/include/r_util/r_ctypes.h, libr/util/ctype.c, shlr/gdb/include/gdbclient/commands.h, shlr/gdb/src/gdbclient/core.c, sys/r2api.sh
- Helps to identify some bugs at compile time
- Useful for git grep and understand the usage of the functions
- Improve readability
- Fix memleak introduced in previous anal/var pr
- Help to find unnecessary null checks and start to use r_assert
- Deprecate R_TRUFAE R_TRUE R_FALSE and R_ERROR
=> Introduce new R_* macros to define direction, null, defaults, etc in function signatures

README.md
The Repology image was distorted because its height is specified in HTML but its original height can change over time. By not setting a fixed height, this makes sure it doesn't become distorted as new distributions are added.
=> Fix Repology image aspect ratio in the README

libr/bin/format/mdmp/mdmp.c
MDMP format store permissions of the memory in a specific stream,
but it seems to be absent by default. So we should at least assume
that the memory is readable unless explicitely specified otherwise
by the dump.
Fix #10992
=> Set mdmp sections as readable by default

libr/core/core.c
The heap space allocated by `core->cons->pager` within `cb_pager()` is not
properly released, resulting in ASAN complaining about the memory leak.
**Reproduction:**
```
$ r2 -A /bin/ls
[x] Analyze function calls (aac)
[x] Analyze len bytes of instructions for references (aar)
[x] Constructing a function name for fcn.* and sym.func.* functions (aan)
[x] Type matching analysis for all functions (afta)
[x] Use -AA or aaaa to perform additional experimental analysis.
-- Use radare2! Lemons included!
[0x00005850]> q
=================================================================
==19512==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 1 byte(s) in 1 object(s) allocated from:
#0 0x7f5232675538 in strdup …
```
=> Fix minor memleak in cb_pager()

libr/core/canal.c, libr/core/cmd_anal.c, libr/core/cmd_print.c, libr/include/r_core.h
Comments on the api usage are welcome, not sure if there is a better way than doing r_io_nread_at and then r_read_le32
=> Add 'aang' to recover function names from stripped golang binaries

libr/anal/xrefs.c, libr/util/asn1.c, libr/util/x509.h
`ax` output
```
segment.LOAD0 0x8048000 ->      CODE -> 0x8048047 segment.PHDR+19
section..dynstr+8 0x8048278 ->      CODE -> 0x80482ee section..gnu.version_r+10
section..dynstr+11 0x804827b ->      CODE -> 0x80482f1 section..gnu.version_r+13
section..dynstr+21 0x8048285 ->      CODE -> 0x80482f6 section..gnu.version_r+18
section..dynstr+50 0x80482a2 ->      CODE -> 0x8048308 section..rel.dyn+4
section..dynstr+70 0x80482b6 ->      CODE -> 0x804832c section..rel.plt+32
section..init+6 0x8048342 ->      CALL -> 0x80483f4 fcn.080483f4
section..init+11 0x8048347 ->      CALL -> 0x8048450 sym.frame_dummy
section..init+16 0x804834c ->      CALL -> 0x8048620 sym.__do_global_ctors_aux
section..plt+6 0x804835a ->      CODE -> 0x8049ffc section..got.plt+8
sym.imp.__libc_start_main 0x8048364 -> …
```
=> Make axj outputting the same data as ax

libr/asm/arch/include/disas-asm.h, libr/asm/p/asm_arc.c, libr/asm/p/asm_arm_gnu.c, libr/asm/p/asm_cris_gnu.c, libr/asm/p/asm_hexagon_gnu.c, libr/asm/p/asm_hppa_gnu.c, libr/asm/p/asm_lanai_gnu.c, libr/asm/p/asm_mips_gnu.c, libr/asm/p/asm_nios2.c, libr/asm/p/asm_ppc_gnu.c, libr/asm/p/asm_sh.c, libr/asm/p/asm_sparc_gnu.c, libr/asm/p/asm_tricore.c, libr/asm/p/asm_vax.c, libr/asm/p/asm_xtensa.c
Yeah looks ugly but it is better than to have 14 different implementations of the same function. The best way is to implement `generic_fprintf()` and `generic_print_address()` functions but they requires address of `RStrBuf`. Can we reuse `stream` field of `disassemble_info` struct too access it (see example below)? Now `stream` value is set to `stdout` but it seems that is not used anywhere.
```c
int generic_fprintf(void *stream, const char *format, ...) {
...
ret = r_strbuf_vappendf ( (RStrBuf *)stream, format, ap);
...
}
void generic_print_address(bfd_vma address, struct disassemble_info *info) {
...
r_strbuf_appendf ((RStrBuf *)info->stream, "0x%08"PFMT64x, (ut64)address);
}
static int disassemble(RAsm *a, RAsmOp *op, const ut8 *buf, int len) {
struct disassemble_info disasm_obj;
... …
```
=> Fix GNU-based RAsm plugins to use RStrBuf API properly

libr/bin/format/mdmp/mdmp.c, libr/bin/format/mdmp/mdmp.h, libr/bin/format/mdmp/mdmp_specs.h
While token stream is not documented on MSDN at the moment (or I didn't found it), the headers of Visual Studio and various projects do have the structure ( for example, mimikatz: https://github.com/gentilkiwi/mimikatz/blob/master/inc/DbgHelp.h#L4204 ), and from there, basic usage can be inferred.
=> Add support for token information from minidump

libr/core/linux_heap_glibc.c, libr/include/r_heap_glibc.h
and avoid using symbols for global_max_fast assuming max size for the arch
fix r_malloc_state_64
=> linux_heap_glibc: debug heap at core file 

libr/debug/dreg.c
This fixes #11637 
new behavior:
~~~
Process with PID 12760 started...
= attach 12760 12760
bin.baddr 0x5654becb0000
Using 0x5654becb0000
asm.bits 64
0x00000000 ->0xfffffa8004cc6b30
{"rax":18446738026476104496,"rbx":0,"rcx":0,"rdx":0,"r8":0,"r9":0,"r10":0,"r11":0,"r12":0,"r13":0,"r14":0,"r15":0,"rsi":0,"rdi":0,"rsp":140734553100096,"rbp":0,"rip":140251687882896,"rflags":512,"orax":59}
~~~
=> drj cmd: change value format to llu instead of lld

libr/debug/debug.c
avoid polluting stdout when using r2pipe and cmdj.
I have a case here where i'm trying to create a Python script with r2pipe over a debug plugin.
The following part of the script fails:
~~~Python
while not interrupted:
r2.cmd('dc')
registers = r2.cmdj('drj')
object_attributes_addr = registers['r8']
~~~ 
Like this (I added debug output in r2pipe)
~~~
r2pipe.cmdj.Error: Expecting value: line 1 column 1 (char 0)
"hit breakpoint at: fffff8000299424c", len 35
Traceback (most recent call last):
File "examples/watch_syscall.py", line 100, in <module>
ret = main(args)
File "examples/watch_syscall.py", line 90, in main
object_attributes_addr = registers['r8']
~~~
I think it's best to keep writing on stderr otherwise `r2.cmdj()` parses the previous command output, and fails.
=> print hit breakpoint message on stderr

libr/anal/d/types-linux.sdb.txt, libr/util/ctype.c
Fixes #11647 
* After fix , we can detect function arguments for func with prefix __GI_ and __libc_
```
|           0x00018824      3c300be5       str r3, [ptr]
|           0x00018828      80301be5       ldr r3, [nbytes]
|           0x0001882c      0100a0e3       mov r0, 1       ; int fd
|           0x00018830      3c101be5       ldr r1, [ptr]   ; void *ptr
|           0x00018834      0320a0e1       mov r2, r3      ; size_t nbytes
|           0x00018838      3d2300eb       bl sym.__GI_write      ; ssize_t write(int fd, void *ptr, size_t nbytes)
```
=>  Detect function prefixed with __libc_ and __GI_ 

libr/core/panels.c
choosing an item in analyze menu does nothing now (well, apparently. like until you move to the Disassembly panel to refresh that), and that should be fixed with this.
=> Fixed Analyze Menu

libr/anal/p/anal_x86_cs.c
Original code uses both normal constant number and internal constant number to update flag register for x86. It makes difficulty for some analysis based on ESIL. This is a quick fix to standardize the usage.
=> Use internal constant to update flag register for x86

libr/anal/anal.c
Fixes #11672 
@Maijin i have found out that , this issue was not specific to `__GI_` prefixed function,  there were other cases were analysis failed to stop after no return function (it was present for long time), see the bin from r2r below
* Before
```
[0x00008150]> pdf
;-- section..text:
;-- $a:
;-- _start:
;-- pc:
;-- r15:
/ (fcn) entry0 56
|   entry0 ();
|           0x00008150      24c09fe5       ldr ip, loc._d_2            ; [0x817c:4]=0x8b00 sym.__libc_csu_fini ; [03] -r-x section size 381864 named .text
|           0x00008154      00b0a0e3       mov fp, 0
|           0x00008158      04109de4       pop {r1}
|           0x0000815c      0d20a0e1       mov r2, sp
|           0x00008160      04202de5       str r2, [sp, -4]!
|           0x00008164      04002de5       str r0, [sp, -4]!
| …
```
=> Stop analysis after no-return function

.clang-format, libr/bin/demangle.c, libr/bin/format/elf/elf.c
That function should check if an address is in the file "side" of the
phdr, so it should check for filesz and not memsz
=> format/elf: fix is_in_pphdr function (fix #11377)

libr/core/panels.c, libr/include/r_cons.h, libr/include/r_util/r_panels.h
It's been very annoying to see people using tabs too many times to move around the panels.
Users are allowed to split screens but not being able to move around them comfortably? No way.
So I implemented something called "Window mode" which allows users to use hjkl to move around the panels.
You can activate the mode by pressing "w" and get back to the default mode by "q", per usual. Enter for the Zoom mode.
=> Window mode is supported so that user can move around the panels by hjkl, not only by too many Tabs

libr/core/cmd_print.c, libr/debug/p/debug_native.c
In FreeBSD 11.2 (stable) radare2 has issues with debugging - it does not disable/enable breakpoints correctly leading to wrong analysis and also to unusable debugging. This patch fixes this issue.
=> Fix debugging in FreeBSD 11.2

libr/util/buf.c
This got broken at some point, but unfortunately we have no r2r coverage for this yet. AFAIK the `r_buf_new_slice` feature is used only in the kernelcache plugin.
=> Fix false positive on rbuf OOB check when offset is there

doc/fortunes.tips
Fix #11736 
Removed the following entry:
For a full list of commands see `strings /dev/urandom`
=> Fix #11736 doc/fortunes.tips - improper entry

libr/bin/format/mdmp/mdmp.c
FIxes the performance issue raised in https://github.com/radare/radare2-regressions/pull/1488#issuecomment-426253880.
=> Prevent MDMP directory entry reads from running out of binary

libr/core/disasm.c
Use dashed line from the same Unicode block as other line drawing
characters.  This ensures that they all are present in the same font,
are the same width and align perfectly.
Re-opening #11727 according to guidelines.
=> Make up lines even more beautiful

libr/core/graph.c
=> Avoid centering graph nodes too big for the current terminal size

libr/core/disasm.c, libr/parse/parse.c
```
$ r2 bins/elf/analysis/arm_32_flags0
-- Most of commands accept '?' as a suffix. Use it to understand how they work :)
[0x000102c8]> e asm.bytes=false; pd 1 @ 0x000102e0; pd 1 @ 0x000102e8
```
Before:
```
0x000102e0 ldr ip, loc._d_2            ; [0x102f8:4]=0x10494 sym.__libc_csu_fini
0x000102e8 ldr r0, sym.main            ; [0x102fc:4]=0x10408 sym.main
```
After:
```
0x000102e0 ldr ip, sym.__libc_csu_fini ; [loc._d_2 0x102f8:4]=0x10494 sym.__libc_csu_fini
0x000102e8 ldr r0, sym.main            ; [0x102fc:4]=0x10408 sym.main
```
=> Fix arm relsub when both pointer addr and pointed-to addr have flags

libr/bin/format/mach0/mach0.h, libr/bin/p/bin_elf.inc, libr/bin/p/bin_mach0.c
Apple toolchain and LLVM provides closure extension for C/C++,
using as possible the most reliable identifier rather than
functions owners where names can appear too generics.
=> Support of Apple/LLVM blocks extension

libr/bin/bin.c
Ref #11692. I did put a conditional in this free since at line 459 it gets freed and not necessarily recreated:
```
459                         R_FREE (buf_bytes);
460                         if (tfd < 0) {
461                             tfd = iob->fd_open (io, fname, R_PERM_R, 0);
462                         }
463                         sz = iob->fd_size (io, tfd);
464                         if (sz != UT64_MAX) {
465                             buf_bytes = calloc (1, sz + 1);
466                             if (buf_bytes) {
467                                 (void) iob->fd_read_at (io, tfd, 0, buf_bytes, sz);
468                             }
469                         }
```
Does radare have a conditional free? Similar to R_FREE but only frees if the value is non-null?
=> Catching leaked mem

libr/core/cmd_type.c
This would benefit from https://github.com/radare/sdb/pull/166, so I can remove the code in cmd_type.c
r2r PR: https://github.com/radare/radare2-regressions/pull/1517
=> cmd_type: refactoring code to print type structs/enums/etc.

libr/bin/format/pe/pe.h
`GUIDSTR_LEN` is currently set to 34, which gives 32 characters for the PDB GUID, 1 character for the PDB age (which is tacked on the end), and the null terminator. However, PDB ages are stored as a uint32, and can thus have a maximum value of 0xFFFFFFFF, which requires up to 8 characters. PDB ages over 15 can easily be reached by automatic build processes using incremental linking.
I'm afraid I haven't built or tested this locally as I'm not currently setup for it, I ran into this issue while using `radare2` for the first time for some static analysis work. A cursory glance through and it seems that `GUIDSTR_LEN` is used consistently, so it doesn't look like any other buffers will have trouble with this.
A binary with a PDB age of 119 (0x77) can be download from here: …
=> Support PDB ages higher than 15

libr/core/disasm.c
Relevant to the realignment problem shown in https://github.com/radare/radare2/issues/4007#issuecomment-175016985.
Commands:
```
$ r2 bins/pe/3ba51ca4-d4ca-11e5-906b-78db8180b654.png
e asm.bytes=false
e asm.comments=false
s 0x560e67
af
pdf
```
Before:
```
|     ::    0x00560e67      push esi
|    ,====< 0x00560e68      jmp 0x560e7d
..
|    ,====< 0x00560e80      jmp 0x560e96
..
|   | ::    0x00560e9a      add byte [eax], al
|   | ::    0x00560e9c      add byte [eax + 0x6452dc36], ch
..
|   ||::    0x00560eb2      pop eax
```
After
```
|     ::    0x00560e67      push esi
|    ,====< 0x00560e68      jmp 0x560e7d
..
|    `----> 0x00560e7d      pop esi
|     ::    0x00560e7e      push eax
|     ::    0x00560e7f      push edx
|    ,====< 0x00560e80      jmp 0x560e96
..
|   |`----> 0x00560e96 …
```
=> disasm.c: Realign after sparse to start of basic block if needed

libr/core/disasm.c
closes #11062 
Now if offset is disabled and marks are enabled, mark space will be printed on flags too.
This avoid ugly alignment like this:
```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|           ; var int local_8h @ ebp-0x8
|           ; var int local_4h @ ebp-0x4
|                push ebp
|                mov  ebp, esp
|                sub  esp, 8
|                nop
|                mov  eax, 0x402000
|                mov  dword [local_4h], eax
```
and substitutes with this
```
/ (fcn) fcn.00401000 31
|   fcn.00401000 ();
|               ; var int local_8h @ ebp-0x8
|               ; var int local_4h @ ebp-0x4
|                push ebp
|                mov  ebp, esp
|                sub  esp, 8
|                nop
|                mov  eax, 0x402000
|                mov  dword …
```
=> Print marks on flags  if asm.offset=false

libr/include/r_util/r_sys.h
On some architectures it is not valid to dereference a void * (I'm
getting this error when trying to compile on ppc64le and s390x), so
let's switch to char *, which is valid.
=> r_util: use char * instead of void *

libr/include/r_util/r_sys.h
Appears only from 11.1 release.
=> Fix #11834 clock_nanosleep/FreeBSD.

libr/core/disasm.c
Fix for the following problem:
specifically [line 4331](https://github.com/radare/radare2/compare/master...kazarmy:VV-esil-func-cmt-no_nl-fix?expand=1#diff-7b45b46dd8a84a924b91f34c2b1e6309R4331) should move `blx sym.imp.close` to a new line.
=> Fix VV esil function comment no-newline

libr/include/r_io.h
musl libc doesn't use `enum __ptrace_request`. This causes two problems when trying to compile for it:
`libr/include/r_io.h` defaults to `__enum ptrace_request`, inverting the logic and only using the enum when building for glibc fixes this.
`shlr/ptrace_wrap` uses `enum __ptrace_request`. I see no option to disable `ptrace_wrap` at configure time without patching the meson or configure files. Using the same `typedef` as in `libr/include/r_io.h` fixes `ptrace_wrap` for musl.
=> Fix ptrace musl compability

libr/anal/bb.c, libr/anal/fcn.c, libr/core/canal.c, libr/core/cmd_anal.c
* Add asserts and checks to ensure the graph is correct before analysis
* Use correct E-N+2P formulae
* Run afbe right after af to get the jmptbl info loaded asap
=> Fix cyclomatic complexity computation when jump tables are involved ##anal

libr/core/anal_tp.c
I saw this message during analysis that wasn't using proper English
> Stack isn't initiatized.
The correct word is initialized. Not sure if this was a typo or a mistake by a non-native speaker. It doesn't really matter. Here's a quick fix.
=> Fix typo initiatized -> initialized

libr/cons/less.c
Uses ^C to quit less paging.
Fix #11892
=> cons/less.c: handle ^C

libr/bin/bin.c
The "iI" (and consequently "ia") commands were failing on assert because
of that.
Fixes #11881
=> bin/bin.c: check if o->libs is NULL before calling r_list_length

libr/core/panels.c
Future plan would be to support some options that splits the screen of disassembly in two, one for before xref-jump and the other for after xref-jump.
=> First stage of supporting xrefs in Panels Disassembly.

libr/bin/bin.c
=> bin.c: check if RBinObject is NULL in r_bin_get_baddr

libr/core/panels.c, libr/include/r_cons.h
For Debug, Registers and Stack panels are shown.
For static analysis, Functions and FcnInfo are shown instead.
Also, Pseudo is shown as default if there is a function, because simply I like the feature :P
=> Change the default panels to be shown depending on the analysis

binr/r2agent/r2agent.c
Since it s based on reference counting, it is safe to make sure the
context is initialised.
=> Fix r2agent segfault.

libr/core/cmd_print.c
This PR stops recursive disassembly with pdR when encountering a ret op-code. This prevents disassembly of unrelated code.
=> Stop pdR when encountering a ret

libr/util/uleb128.c
Associated clusterfuzz bin is already in r2r. I think I did the fix for #11126 before I discovered the joys of ASAN builds.
=> Fix #11919 - r_sleb128() checks for end

libr/core/cconfig.c, libr/core/disasm.c
Fixes the problem shown in https://github.com/radare/radare2/issues/4007#issuecomment-175016985. Currently for disasm only. Not sure whether defaulting it to true is ok performance-wise.
=> asm.bb.middle: Realign disasm on bb start

libr/anal/p/anal_arm_cs.c
before the patch:
0x00026186      7944           add r1, pc
after the patch:
0x0002618e      7944           add r1, pc   ; "sqlite3_backup_finish"
This will help to find more xref in arm binaries
=> WIP: ARM/ESIL: Add and fix emulation of addw, add, adr

libr/core/cmd_search.c
before it was searching for an invalid `magic` value, but instead it should be searching for a bitmasked magic
=> /Cd search x509 certs

libr/core/disasm.c
Related to radareorg/cutter#803
=> Fixed BOF on heap when get long asm line (issue about crash with DEX)

libr/core/canal.c, libr/core/disasm.c, libr/include/r_anal.h
Changes:
* hardcoded calling convention is now R_ANAL_CC_TYPE_FASTCALL since the stack based one seems to always provide incorrect values on 32 bits elfs anyway.
* uses function name or its address in case there is no name yet
* uses correct number of arguments computed with `r_anal_var_count` since fcn->nargs was never updated
Before
```asm
$ r2 tailcall
-- Starting bitcoin miner in background...
[0x00401060]> s main; pd 10
;-- main:
0x00401168           push rbp
0x00401169           mov rbp, rsp
0x0040116c           sub rsp, 0x10
0x00401170           mov esi, 1
0x00401175           mov edi, 5
0x0040117a           call sym.factorial; CALL: 0xffffffff, 0xffffffff, 0xffffffff, 0xffffffff
0x0040117f           mov dword [rbp - 8], eax
0x00401182           mov eax, dword [rbp - 8]
0x00401185 …
```
=> Fix emustr info

libr/anal/bb.c, libr/anal/fcn.c, libr/core/cconfig.c, libr/include/r_anal.h
Partial fix for #10420. Currently anal.jmpmid defaults to false since WIP.
=> anal.jmpmid: Continue analysis after jump to middle of instruction (x86, no loops only)

libr/util/ctype.c
This fixes the issue reported by @Maijin 
* Before 
* After
=> Improve function param detection by removing func-number from function name

libr/cons/input.c
Since radare2 does not use termcap to process special keys, running it on different terminal emulators might break some key shortcuts.
This PR fixes shift+arrow shortcuts for st and rxvt-unicode terminal emulators.
=> fix shift-arrows for st and rxvt-unicode terms

libr/core/cmd_open.c, libr/include/r_util/r_str.h, libr/io/p/io_debug.c, libr/util/str.c
e973deadca3c6c417825bcb04b02e2a38202f143 is useless after 41cb6ef0d2f39469cd30961fe81b6f7836dd504b, because the file path we get with `fd_get_name` is already an absolute path:
https://github.com/radare/radare2/blob/7b01b96f9070bbce45407f16b6382924c64ec479/libr/bin/bin.c#L217
What has been done in #9353 is totally wrong. It's impossible to separate unescaped args in a string. We should escape args before, separate and unescape them when we need them.
I think the Linux part of #11075 has been fixed.
By the way, I'm curious that is it proper to use the absolute path when we use `ood` to debug bins, even if we use relative path when we debug it in the first time? At least `argv[0]` has been changed and it may have an effect on running.
=> Fix args escape and unescape bugs when debug

libr/bin/blang.c, libr/bin/demangle.c
- fix language type detection logic when handling variables
unknownType, is{Macho, isElf, isPe}
- set language as msvc when an import library that has "msvcp" is
found
- demangle symbols that have a dll name such as sym.imp.*.dll_*
=> improve MSVC demangling

shlr/capstone.sh
- Use $( ... ) instead of legacy \` ... \`
- Use git rev-parse instead of grepping and parsing git branch
- Prefer [ p ] && [ q ] as [ p -a q ] is not well defined
- Clone until our needed TIP commit
=> capstone.sh: Fix shellcheck warning

libr/anal/p/anal_riscv.c, libr/asm/p/asm_x86_nz.c, libr/bin/format/pe/pe.c, libr/bin/mangling/microsoft_demangle.c, libr/core/cmd.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/disasm.c, libr/core/rtr.c, libr/debug/dreg.c, libr/debug/p/native/linux/linux_coredump.c, libr/hash/hash.c, libr/io/p/io_gdb.c, libr/parse/p/parse_mips_pseudo.c, libr/parse/p/parse_x86_pseudo.c, libr/reg/profile.c, libr/util/hex.c, libr/util/print.c, libr/util/regex/engine.c, libr/util/regex/regex2.h, libr/util/unum.c
The behavior of the `<ctype.h>` functions is undefined for negative
arguments (other than `EOF`). In such a situation, the argument should
be cast to `unsiged char` for safety.
References:
- C Programming: A Modern Approach, 2nd Edition: page 612, chapter 23.5
=> Change argument type to ut8 before passing to ctype.h function

libr/debug/p/debug_native.c, libr/include/r_types.h, libr/io/p/io_gprobe.c, libr/socket/run.c, libr/util/Makefile, libr/util/sys.c
including backtrace support. the manpage mentions FreeBSD 10 release
and DragonflyBSD has different versioning, and radare not into
their port tree yet anyway, it might safe enough.
=> DragonflyBSD build fix.

libr/anal/p/anal_sparc_cs.c
Fixes the Capstone back-end to have branch delay slots and to handle the aliased form of the return instruction (#12078).
I'm not super familiar with SPARC, it just came up in a project I was working on today. I think SPARC has a delay slot for all instructions that update PC, but I could be wrong. I'm also not too clear on when Capstone returns the ```SPARC_INS_RETL``` alias, but I think it is equivalent to ```SPARC_INS_RETT```, or at least also should be treated as an unconditional return.
These changes are only for the Capstone back-end. The GNU version (```sparc.gnu```) I left alone.
=> SPARC Fixes

libr/asm/arch/mips/gnu/mips-dis.c, libr/magic/apprentice.c, libr/magic/softmagic.c
simplifies some for loops and removes a redundant `continue;`. this is consistent with other parts of the code that don't have the `continue;` (e.g., [here](https://github.com/radare/radare2/blob/master/libr/core/cmd_flag.c#L216) and [here](https://github.com/radare/radare2/blob/master/shlr/sdb/src/util.c#L172))
=> refactor: remove redundant continue in for loops

libr/anal/var.c, libr/bin/p/bin_nes.c
some archs do not even have a default calling convention, so let's just
skip them for now and print a log. It means we probably need to
implement other things to make arguments analysis work on those archs.
=> anal: cannot extract reg args if no calling convention is present

libr/include/r_crypto.h
Hopefully fixes the build for https://github.com/radareorg/cutter/pull/917: https://ci.appveyor.com/project/radare/cutter/builds/20209111/job/pw4nd210ia2p4dhr
=> Use quoted includes in r_crypto.h

libr/bin/filter.c, libr/bin/obj.c, libr/include/r_bin.h
Directly reallocate strings when filtering them, because it is very hard for
the caller to know before hand the correct size of the string otherwise. The
patch uses r_str_ APIs to makes this easy.
This fixes an ASAN detected overflow : https://travis-ci.org/radare/radare2/jobs/453150808#L1039 .
=> bin/filter: correctly allocate strings when filtering them

shlr/grub/fs/minix.c
Using wrapper instead, and might be safe anyway
in case allocators impl change.
=> Fix grub minix plugin build.

libr/core/task.c
The tasks are already freed by the reference counting.
=> Fix use after free in core.

binr/radare2/radare2.c
Defer project loading until after plugins have been loaded. Also addresses FIXME regarding loss of -e flags from getopt loop.
=> Open radare2 project after loading plugins and don't lose -e flags

binr/rax2/rax2.c, libr/cons/cons.c, libr/core/cbin.c, libr/core/cmd.c, libr/core/cmd_help.c, libr/core/cmd_info.c, libr/core/linux_heap_glibc.c, libr/debug/map.c, libr/include/r_util/r_num.h, libr/util/unum.c
r_num_abs:
- Make r_num_abs static inline
- Use unsigned long long type when defining TB macro
- Use st64 instead of long long
r_num_units:
- Add len argument for buf in r_num_units
- Add PB and EB for r_num_units
- Always display one number after decimal point
* This change simplifies the code
- Use long double type as assigning from ut64 to double cause data loss
r_num_tail_base:
- Use isxdigit (fast) instead of isHexDigit (slower)
- Rename nth to get_nth_nibble
Update all functions to use with new r_num_units:
- Remove side effect when using in other functions like cb_printf
=> Rewrite r_num_abs as function (fix #12060) and r_num_units

libr/core/canal.c
The only fact that there is no paddr, means the symbol is not present in
the file, so there's nothing to analyze (at least statically)
=> Do not check vaddr for isValidSymbol

libr/core/cfile.c, libr/core/cmd_open.c
It seems that if the binary hasn't been loaded, `r_bin_reload` won't be called when `ood`.
So it's better for us to retrieve e973deadca3c6c417825bcb04b02e2a38202f143.
The `perm` only ranges in 0~7,  so we shouldn't print it with `0x%04x`.
=> Make ood use absolute path

libr/cons/input.c
In standard C, `fflush` works only with output/update stream, not input stream.
=> libr: Fix fflush (stdin) (fix #12053)

libr/core/cmd_anal.c, libr/core/cmd_help.c, libr/core/cmd_print.c, libr/core/cmd_search.c, libr/core/cmd_zign.c
From the git commit comment:
An empty list is different than a NULL return value. The caller has to
call r_list_free anyway on the returned list, so there's no real
advantage in returning NULL, it just makes the caller's life harder
because it cannot understand if NULL is returned because the list was
empty (e.g. there are no IO maps, etc.) or because there were some
errors.
=> Fix another assert when printing blocks

libr/include/r_types.h, libr/include/r_util/r_sys.h, mk/emscripten.mk, sys/emscripten.sh
This commit also includes changes in the jemalloc include files aiming to make non-linux targets compile with jemalloc. Still wip, but unrelated to this issue because i end up adding the --without-jemalloc
=> Improvements for emscripten (wasm/asm.js) ##port

libr/core/cmd_anal.c
=> Implement aeab command to get input and output regs of the basic block

libr/debug/p/native/bt.c, libr/include/r_debug.h, libr/include/r_io.h, libr/io/io.c, shlr/Makefile, shlr/ptrace-wrap/README.md, shlr/ptrace-wrap/include/ptrace_wrap.h, shlr/ptrace-wrap/src/ptrace_wrap.c
Fix #12022
The idea is to not push every single ptrace call separately to the ptrace-wrap thread and wait for it, but to execute a whole, bigger function on the ptrace-wrap thread, so synchronization only happens once at the begin and the end.
=> Use ptrace_wrap_func() for backtrace ##debug 

libr/parse/parse.c
Closes #11889 
The `findNextNumber` function in parse.c did not parse correctly ascii escapes that began with `\x1b[1;...`, 
now we just skip everything until we hit a `m`, `J` or `H` like in `r_str_ansi_filter`
=> Fixed bad varsub with bold font 

libr/core/cbin.c, libr/core/cmd_info.c, libr/core/disasm.c, libr/include/r_util/r_str.h, libr/util/str.c
Fix #11395
I added the function `r_str_escape_utf8_to_json()`, which can be used to explicitly escape a utf-8 string for json.
`r_str_utf16_encode()` looks very wrong to me. All it does is go through the string byte by byte and print non-printable bytes as `\u00xx`, which is nonsense, because it corresponds to no real encoding and especially not to utf-16.
=> Replace r_str_utf16_encode() for escaping strings for json

libr/core/cmd_open.c
the `oba` help message is confusing and should be fixed.
=> fix help message of oba command

libr/core/cmd_open.c
the command `oba` with a filename was erasing the original fd:
This is fixed by this PR.
=> restore fd when loading symbols from file with oba

binr/rabin2/rabin2.c, binr/ragg2/ragg2.c, libr/bin/bin.c, libr/bin/p/bin_cgc.c, libr/bin/p/bin_elf.c, libr/bin/p/bin_elf64.c, libr/bin/p/bin_mach0.c, libr/bin/p/bin_mach064.c, libr/bin/p/bin_menuet.c, libr/bin/p/bin_p9.c, libr/bin/p/bin_pe.c, libr/bin/p/bin_wasm.c, libr/include/r_bin.h
For now I put the RBinArchOptions in r_bin.h. It can be easily moved if it needs to be used elsewhere in the future. The reasons I did that is because I'm not sure we will be able to easily extend this structure and use it everywhere... Some places do require `os`, others don't. Some places do require `cpu`, others do not, etc... So I think the best thing is to keep it as simple as possible for now and choose in the future when we have a better view.
=> Add RBinArchOptions type

libr/core/cconfig.c, libr/core/graph.c
Fix #12046
Added `graph.bytes` option to show opcode bytes in graph view. 
With that enables, it is possible to see the effect of `asm.flags.inbytes`.
=> Fix asm.flags.inbytes not showing in graph

libr/core/visual.c
Fix #11427
Now the text in the first column is cropped with `r_str_ansi_crop`, if visual split is enabled (like we do in panels)
=> Fix comments in visual split mode overflowing over the split column

libr/core/visual.c
Commit cc9d361dd317d3679d6af7ff0809744c8d82c945 only partially solved
the issue. The same should have been done for \n, \r, ' '. This patch
refactors the code to be sure both cases do the same thing.
=> Fix cursor when following refs/xrefs with \n in visual mode

libr/fs/shell.c, libr/util/file.c
This fixes double free crashes on the `cat` and `get` commands on the mount shell and the `ed` command on Windows (`awb` is an invalid file open mode)
=> Fix mount shell and ed commands

libr/core/cmd_type.c, libr/util/ctype.c
Not all pointers to structs start at the beginning, thanks Microsoft for your implementation of list entries (LIST_ENTRY). Thus I have tweaked `ta` so that it can now take an additional argument `offset`. So for example we can now do the following: `ta _LDR_DATA_TABLE_ENTRY.DllBase 0x10`, as we are pointing not at the start of the structure but actually at offset 0x10 (the InInitializationOrderLinks field).
I have also extended the r_type_get_struct_memb function so that it will now parse inline structs rather than incorrectly bailing out. So below we can see that BaseDllName (UNICODE_STRING) is correctly resolved to the inlined structure.
Example of new improvements:
NOTE: Annoyingly cmd_type.c is formatted badly so there are lots of additions due to linting!
=> Types: some minor improvements to `ta`

libr/cons/cons.c, libr/debug/p/debug_io.c, libr/util/unum.c
Why global when these variables are only used in one function.
=> Change unneeded global static vars to local static

libr/core/panels.c, libr/include/r_util/r_panels.h
Removed the "refresh" parameter from Panel so that all the panels will be refreshed all the time. 
The core offset was not set right in some places, now they are fixed.
Some fixes and refactoring are additional.
=> Set the core offset right and update the panels correctly when scrolling disassembly##panels

libr/core/disasm.c
Fix #12294 
if the `flagstr` is too long (longer than ds->nb - 1, which is the number of cells available for opcode bytes, that depends on asm.nbytes), cut it with a `\0`
=> Cut flags inbytes string if too long

libr/asm/p/asm_x86_nz.c
0 ,0,[bP-bL-bP-bL-bL-r-bL-bP-bL-bL-
mov ,0,[ax+Bx-ax+Bx-ax+ax+Bx-ax+Bx--
leA ,0,[bP-bL-bL-bP-bL-bP-bL-60@bL-
leA ,0,[bP-bL-r-bP-bL-bP-bL-60@bL-
mov ,0,[ax+Bx-ax+Bx-ax+ax+Bx-ax+Bx--
=> Fix #12372 and #12373 - Crash in x86 assembler

libr/bin/format/nxo/nxo.c, libr/bin/obj.c
Those are -Wformat, -Wincompatible-pointer-types, and -Wunused-variable.
=> Fix clang warnings

sys/user.sh
Users may want to install radare2 to a different directory than `~/bin`.
Parse `--install-path` in `sys/user.sh` to allow for users to do so.
=> sys/user.sh: Allow setting an install path

libr/bin/dwarf.c
The use of memset to set the rest of the newly realloc'd buffer in
various `r_bin_dwarf_expand_*` functions was overwriting portions of
the buffer that had previously been written to.
The functions including said error were the following:
- r_bin_dwarf_expand_die
- r_bin_dwarf_expand_cu
- r_bin_dwarf_expand_abbrev_decl
- r_bin_dwarf_expand_debug_abbrev
```
Breakpoint 1, r_bin_dwarf_expand_abbrev_decl (ad=0x61c000014080) at dwarf.c:947
947             if (!ad || !ad->capacity || ad->capacity != ad->length) {
(gdb) print ad->capacity
$1 = 8
(gdb) x/2ugx ad->specs
0x60c00005a880: 0x0000000000000025      0x000000000000000e
(gdb) next 7
962             return 0;
(gdb) x/2ugx ad->specs
0x61100001b480: 0x0000000000000025      0x0000000000000000
```
=> r_bin_dwarf_expand_*: fix memory error

libr/core/panels.c
The new panel should be focused when they are created with n/N command or M command.
=> Minor fix when opening a new panel ##panels

libr/bin/format/wasm/wasm.c, libr/bin/format/wasm/wasm.h, libr/bin/p/bin_wasm.c
exports now are used also to fill symbols
=> fixed #12409 - wasm function ids

libr/core/cmd_anal.c
It was assumed all the values were functions but that might not be
true and then wrong hints would be set.
This should be handled by ESIL which is the only one it will know whether
a call is gonna be made with the data under analysis.
The issue #12340 shows how data is wrongly interpreted.
const int a = 0x000103c9;
```
int main()
{
int b;
b = 2;
b = b + a;
return 0;
}
```
It gets translated to
```
┌ (fcn) main 56
│   main (int argc, char **argv, char **envp);
│           ; UNKNOWN XREF from entry0 (+0x34)
│           0x000103c8      04b02de5       str fp, [sp, -4]!
│           0x000103cc      00b08de2       add fp, sp, 0
│           0x000103d0      0cd04de2       sub sp, sp, 0xc
│           0x000103d4      0230a0e3       mov r3, 2
│           0x000103d8      08300be5       str r3, …
```
=> Remove logic from _CbInRangeAav when arch equal to arm/thumb

libr/core/cbin.c
`entry0.init` looks too much like `init` is a member of `entry0`.
=> Use entry.init0 instead of entry0.init

libr/core/disasm.c
This PR adds relocation lookups for `e asm.jmpsub=true` to give better disassembly using relocations.
While disassembling Pwnable.KR's softmmu kernel module (http://pwnable.kr/bin/softmmu
), the disassembly of `sym.mmuinit` previously failed to substitute in `printk` instead for improperly decoded calls.
=> Add relocation search in disassembly jump substituion.

libr/anal/p/anal_x86_cs.c
At  the end of the following code $cf=1. But 0x10-0x1=0x9 should not cause a borrow!
```
mov ebx, 0x10
mov eax, 1
sub ebx, eax
```
The esil code corresponding to `sub` is:
```eax,ebx,-=,$o,of,=,$s,sf,=,$z,zf,=,$p,pf,=,$b4,cf,=```
Note that borrow is set on the 4th bit instead of the 32th one.
=> Fix borrow flag handling for SUB/SBB on x86

libr/core/cmd_anal.c, libr/core/cmd_type.c
I renamed old calling convention commands into `afc` as in "Analysis Function Calling convention", and `tc` is now outputs the types in C format.
=> Fix `tc` and `afc` commands ##types

binr/radare2/Makefile, libr/anal/p/wasm.mk, plugins.emscripten.cfg
Emscripten v1.37.24 excludes `cwrap` from default exports and requires setting EXTRA_EXPORTED_RUNTIME_METHODS to put it back. Also, it seemed like `malloc` crashed when trying to do `e asm.arch=x86`, so I gave it some more memory (which worked). 33554432 is the least power of 2 that is greater than the default (16777216).
The third commit was because r2 emits the following (kinda ugly) warning every time the core gets created:
> var r2core = require('./radare2.js');
> var r2i = r2core._r2_asmjs_new();
r_config_get: variable 'asm.arch' not found
anal.arch: cannot find 'wasm'
asm.arch: cannot find (wasm)
e asm.bits: Cannot set value, no plugins defined yet
e asm.bits: Cannot set value, no plugins defined yet
asm.arch: cannot find (wasm)
> r2i != 0  // the instance does get successfully …
=> Support r2core.js for Emscripten >=v1.37.24

libr/anal/hint.c, libr/core/cmd_anal.c, libr/core/vmenus.c, libr/include/r_anal.h, libr/parse/parse.c
- ahi0 == ahi
- any digit from 0 to 9 is valid
- This breaks some behaviour in visual mode that needs to be fixed in Vdi
$ r2 -qcq - << EOF
wx c7458843c6ff00
pd 1
ahi 10
pd 1
ahi-
ahi1 10
pd 1
EOF
mov dword [rbp - 0x78], 0xffc643
mov dword [rbp - 120], 0xffc643
mov dword [rbp - 0x78], 16762435
=> Implement support for nword in ahi ##anal

libr/core/canal.c, libr/core/cmd_anal.c
Hi there,
when trying to analyze some binaries (in my case the program ls) somehow the behaviour of agfv and agfj differs.
Questions | Answers
-- | --
OS/arch/bits (mandatory) |  Manjaro x86 64
File format of the file you reverse (mandatory) | ELF
Architecture/bits of the file (mandatory) | amd64
r2 -v full output, not truncated (mandatory) | radare2 3.2.0-git 20447 @ linux-x86-64 git.3.1.3-98-gd2133cbdf commit: d2133cbdf843cef278f7a22e763b9c6485c2b55a build: 2018-12-18__02:41:14
**Expected Behaviour**
> $r2 /usr/bin/ls
[0x00005ae0]> aaa
...
[0x00005ae0]> agfv
(shows graph of entry0)
[0x00005ae0]> agfj
(returns json containing instructions of entry0)
[0x00005ae0]> sf main
[0x00004070]> agfv
(shows graph of main)
[0x00005ae0]> agfj
(returns json containing instructions of main)
**Observed …
=> Fix different behaviour of agfv and agfj

libr/core/disasm.c
Fixes issue #12507 with duplicate output of CODE XREFS for local labels.
Before:
```
0x00400710      eb0f           jmp 0x400721                ; main.exit
0x00400712      bf41084000     mov edi, str.Invalid_Password
0x00400717      e84cfeffff     call sym.imp.puts
0x0040071c      b801000000     mov eax, 1
; CODE XREF from main (0x400710)
.exit:
; CODE XREF from main (0x400710)
0x00400721      c9             leave
0x00400722      c3             ret
```
After:
```
0x00400710      eb0f           jmp 0x400721                ; main.exit
0x00400712      bf41084000     mov edi, str.Invalid_Password
0x00400717      e84cfeffff     call sym.imp.puts
0x0040071c      b801000000     mov eax, 1
; CODE XREF from main (0x400710)
.exit:
0x00400721      c9             leave
0x00400722      c3 …
```
=> fix issue #12507

libr/core/visual.c
Otherwise it happened in some cases the block size became ridiculously big, leading to unnecessary performance issues (especially with already performance-challenging binaries like dyld library caches).
Not sure if hardcoding 16K it's a good idea, though.
=> Limit the blocksize in visual mode

libr/core/cmd_print.c
Hi there,
after analyzing a binary (i.e. the program ls) with the current offset set to the entry point the pdf command will show the content of main instead of entry0. This seems to be related to https://github.com/radare/radare2/pull/12512
Questions | Answers
-- | --
OS/arch/bits (mandatory) | Manjaro x86 64
File format of the file you reverse (mandatory) | ELF
Architecture/bits of the file (mandatory) | amd64
r2 -v full output, not truncated (mandatory) | radare2 3.2.0-git 20447 @ linux-x86-64 git.3.1.3-98-gd2133cbdf commit: d2133cbdf843cef278f7a22e763b9c6485c2b55a build: 2018-12-18__02:41:14
**Expected Behaviour**
> $r2 /usr/bin/ls
> [0x00005ae0]> aaa
> ...
> [0x00005ae0]> pdf
> (prints instructions of entry0)
**Observed Behaviour**
> $r2 /usr/bin/ls
> [0x00005ae0]> aaa
> ...
> …
=> Fix odd behaviour of pdf (with regards to agfv and agfj)

libr/cons/cons.c, libr/core/disasm.c, libr/include/r_cons.h, libr/include/r_util/r_str.h, libr/util/str.c
`ds_align_comment()` is currently the bottleneck for `agJ`. The idea here is to save the position in the cons buffer of the start of the current line and calculate the line length starting from there, excluding ansi escape sequences and respecting utf-8.
Before:
```
[florian@florian-desktop radare2]$ time r2 /bin/ls -qc "s main;af;agJ" > /dev/null
real	0m0,440s
user	0m0,428s
sys	0m0,012s
```
After:
```
[florian@florian-desktop radare2]$ time r2 /bin/ls -qc "s main;af;agJ" > /dev/null
real	0m0,153s
user	0m0,139s
sys	0m0,013s
```
Here is the comparison of a seek in cutter from outside a function to inside a function, which causes a call to `agJ`:
Before:
After:
=> Optimize ds_align_comment() ##disasm

libr/bin/format/elf/elf.c
Hi there,
when analyzing shared libraries some of the exported symbols get "lost".  This happens if multiple symbols point to the same location. This patch aims to fix this behaviour. Tests will be added soonish.
Questions | Answers
-- | --
OS/arch/bits (mandatory) | Manjaro x86 64
File format of the file you reverse (mandatory) | ELF
Architecture/bits of the file (mandatory) | x86/64
r2 -v full output, not truncated (mandatory) | radare2 3.2.0-git 20508 @ linux-x86-64 git.3.1.3-139-ge7451c6a0 commit: e7451c6a0b074a4a1602f3ffcac1cc58ed25ecf3 build: 2018-12-24__16:44:50
```
$ r2 /usr/lib/libc.so.6
[0x00023af0]> is~getpid
3577 0x000c9420 0x000c9420  LOCAL   FUNC   12 __GI___getpid
3807 0x000c9420 0x000c9420  LOCAL   FUNC   12 __GI_getpid
6267 0x000c9420 0x000c9420   WEAK   FUNC   12 getpid …
```
=> Fix missing exported symbols

libr/core/cmd_print.c
j had a modifier that ignored the one from v, instead use only the one from v. #12528
=> Fix #12528 - Removed suffix modifier for 'j' in cmd_print.c

libr/anal/meson.build, libr/asm/meson.build, libr/bin/meson.build, libr/bp/meson.build, libr/config/meson.build, libr/cons/meson.build, libr/crypto/meson.build, libr/debug/meson.build, libr/egg/meson.build, libr/flag/meson.build, libr/fs/meson.build, libr/hash/meson.build, libr/io/meson.build, libr/lang/meson.build, libr/magic/meson.build, libr/meson.build, libr/parse/meson.build, libr/reg/meson.build, libr/search/meson.build, libr/socket/meson.build, libr/syscall/meson.build, libr/util/meson.build, meson.build
**Note**: This PR should be merge after updating the sdb vendor (After merging radare/sdb#181). 
Fix deprecated warnings in Meson 0.49.0, examples:
```
libr/socket/meson.build:30: DEPRECATION: Library r_socket was passed to the "libraries" keyword argument of a previous call to generate() method instead of first positional argument. Adding r_socket to "Requires" field, but this is a deprecated behaviour that will change in a future version of Meson. Please report the issue if this warning cannot be avoided in your case.
```
=>  meson: Do not use glob with meson

libr/core/cmd_search.c
Make sure that the help message states that the key in question is "expanded in memory" (whatever that means).
Related to https://github.com/radare/radare2book/pull/168
=> Clarify aes /Ca help message

libr/anal/p/anal_xtensa.c
=> Fix #12534 - xtensa split fields are now being decoded for ESIL

libr/core/cconfig.c, libr/core/cmd_print.c, libr/core/core.c, libr/core/visual.c, libr/debug/dreg.c, libr/include/r_util/r_print.h, libr/util/print.c
=> Add scr.wideoff to make offsets and reg values depend on asm.bits ##visual

libr/core/canal.c
Hi there,
after analyzing libc.so with aa the function `sym.abort` is analyzed correctly. However, analyzing it with aac shows a different result (as shown in the pictures below). This is imho caused the wrong assumption that the function has overlapping blocks. And due to that the function is split. This patch aims to fix this misbehaviour.
[libc.so.6.zip](https://github.com/radare/radare2/files/2719632/libc.so.6.zip)
| OS/arch/bits (mandatory)                             | Manjaro X86 64
| Architecture/bits of the file (mandatory)            | 86/64
| r2 -v full output, **not truncated** …
=> Fix wrong splitting of functions in aac

libr/core/cbin.c, libr/util/str.c
For https://github.com/radare/radare2/pull/12259#issuecomment-441052701. Follows [RFC 8259](https://tools.ietf.org/html/rfc8259).
=> Do spec-following r_str_escape_utf8_for_json()

libr/anal/p/anal_avr.c
=> Add the missing fail arc for SBRx instruction

libr/bin/format/pe/pe.c
Pointer size was checked (*wrong*) instead of `struct Pe_image_resource_data_entry` size
=> Fixed wrong bounds check while PE file resources is being parsed

libr/core/anal_tp.c
Fix #11505 
* Before 
* After 
Hopefully this should fix the issue , without making tarvis angry :) , @Maijin pls verify !
=> Disable dbg.follow in aaft to prevent seek changes

libr/core/disasm.c
Hi there,
r2 is missing the resolution of some reloc symbols in agfj. This patch aims to fix this.
| OS/arch/bits (mandatory)                             | Manjaro X86 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.2.0-git 20627 @ linux-x86-64 git.3.1.3-217-g399fcc24a commit: 399fcc24aad065fe08fefc6d74bebdbc53e0181a build: 2019-01-04__23:00:04
```
$ r2 /usr/bin/ls        
[0x00005ae0]> aa;aac
...
[0x00005ae0]> sf loc.0000f190
[0x0000f190]> agfj~{}
[
{
...
"blocks" : [
...,
{
"offset": 61857,
"ptr": …
```
=> Fix missing reloc symbols in agfj

libr/core/visual.c
For example, s 0 -> Vg nor VG works so fixed.
=> More fix for Vg and VG ##visual

libr/asm/p/asm_arm_gnu.c
p/asm_arm_gnu.c: In function ‘disassemble’:
p/asm_arm_gnu.c:157:4: erreur: ‘for’ loop initial declarations are only allowed in C99 mode
for (int i = 0; i < (sizeof(arm_cpucodes) / sizeof(arm_cpucodes[0])); i++) {
=> Fix build on older (RHEL 7) compiler

libr/asm/arch/arm/armass64.c
When resolving unconditional branch to current address ("b ."), the code dose not resolve n == addr condition correctly.
=> Fix ARM aarch64 assemble "b ." ("b 0x0") to wrong result(00000017).

libr/anal/var.c, libr/core/carg.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/include/r_anal.h, libr/util/pj.c
Please don't squash. I think the commits are clean enough.
Example:
```
[0x00005ae0]> s main
[0x00004070]> af
[0x00004070]> pd 1
┌ (fcn) main 4886
│   main (int argc, char **argv, char **envp);
│           ; arg int arg_5h @ rbp+0x5
│           ; var int local_8h @ rsp+0x8
│           ; var int local_17h @ rsp+0x17
│           ; var int local_28h @ rsp+0x28
│           ; var int local_30h @ rsp+0x30
│           ; var int local_32h @ rsp+0x32
│           ; var int local_38h @ rsp+0x38
│           ; var int local_45h @ rsp+0x45
│           ; var int local_46h @ rsp+0x46
│           ; var int local_47h @ rsp+0x47
│           ; var int local_48h @ rsp+0x48
│           ; arg int argc @ rdi
│           ; arg char **argv @ rsi
│           ; DATA XREF from main (0x5b01)
│           0x00004070 …
```
=> Make afcf also print args from vars (unified with disasm)

meson.build
I noticed when releasing 3.2.0 on Fedora that the libraries did not have any version (e.g. r_anal_version, r_core_version, etc.) because gittap was empty. This patch falls back to r2_version if gittap is not set (e.g. a release tarball does not have any gittap)
=> Set gittap even in release tarball

libr/core/cmd_meta.c
| OS/arch/bits (mandatory)                             | Manjaro X86 86
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20640 @ linux-x86-64 git.3.1.3-278-g7ed7a5bae commit: 7ed7a5baee2a469e68d542a3377c15145a92cac5 build: 2019-01-10__14:02:54
Tested with valgrind
```
valgrind r2 bins/elf/analysis/x86-helloworld-gcc
==11786== Memcheck, a memory error detector
==11786== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==11786== Using Valgrind-3.14.0 and LibVEX; rerun with -h for …
```
=> Fix invalid read in cmd_meta

libr/core/visual.c
... caused by holding down a movement key. Tested on Linux only.
=> Prevent runaway scrolling in Visual mode ##visual

libr/core/visual.c
Partially fixes the runaway scrolling issue but shouldn't disable any key/mouse input.
=> Flush Visual stdin only if printable, \t or \n

libr/anal/anal.c
Hi there,
when analyzing a binary the current implementation of r2 does not handle noreturn of reloc-functions corrently. This patch aims to fix this.
| OS/arch/bits (mandatory)                             | Manjaro x86 64
| Architecture/bits of the file (mandatory)            | x86/64 
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20744 @ linux-x86-64 git.3.1.3-325-g82b6496a2 commit: 82b6496a274bdc9687fe45cfc1be66c31b28540a build: 2019-01-14__20:19:36
```
$ r2 /usr/bin/ls
[0x00005ae0]> aaa
[0x00005ae0]> s sub.__printf_chk_80b0
[0x000080b0]> agv
```
Taken from …
=> Fix noreturn handling of reloc functions

libr/core/linux_heap_glibc.c
This will fix #12789, but introduces the bug disclaimed in #12789.
=> change brk_end calculation back

libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_core.h
The following pull request fixes the broken `afns`. 
`afns` is being used to print all the strings referenced in a function. Previously, when executed `afns` it used to print a single flag, which wasn't necessarily a string. This was because the `break;` keyword prevents the loop to iterate over the referenced flags. This PR fixes it.
Moreover, it implements a proper JSON support for `afnsj`.
```
[0x00001347]> afns
0x00001356 0x00002004 str..::_Megabeets_::.
0x00001362 0x00002019 str.Think_you_can_make_it
0x0000138b 0x00002030 str.Success
0x00001399 0x0000203a str.Nop__Wrong_argument.
[0x00001347]> afnsj~{}
[
{
"addr": 4950,
"ref": 8196,
"flag": "str..::_Megabeets_::."
},
{
"addr": 4962,
"ref": 8217,
"flag": "str.Think_you_can_make_it"
},
{
"addr": 5003,
"ref": 8240,
"flag": "str.Success" …
```
=> Fix afns and add JSON support

libr/bin/bin.c
Trying to load a 2.4G core file do result into error message like:
Cannot allocate -17240000 bytes
Since opt->sz is unsigned, casting it to sized int is problematic.
=> Use unsigned int for size when loading binary file

libr/core/cmd.c
Before:
```
[0x00001060]> fd @@@F
[0x00001060  entry0
entry0
[0x00001090  sym.deregister_tm_clones
sym.deregister_tm_clones
[0x000010c0  sym.register_tm_clones
sym.register_tm_clones
[0x00001100  sym.__do_global_dtors_aux
entry.fini0
[0x00001150  entry.init0
entry.init0
[0x00001420  sym.__libc_csu_fini
sym.__libc_csu_fini
...
...
```
After:
```
[0x00001060]> fd @@@F
entry0
sym.deregister_tm_clones
sym.register_tm_clones
entry.fini0
entry.init0
sym.__libc_csu_fini
...
...
```
=> remove extra print in @@@F

libr/core/cmd.c
As mentioned on telegram, this will cause unsynchronized access to sandbox, but the current sandbox implementation can never properly work with multiple tasks anyway.
Fix #12793
=> Make ! command sleep around system() (Fix #12793)

libr/core/cmd_anal.c
Make reference type more clear and add JSON support using the new pj API
```
[0x00001060]> axffj~{}
[
{
"type": "DATA",
"at": 4211,
"ref": 5152,
"name": "sym.__libc_csu_fini"
},
{
"type": "DATA",
"at": 4218,
"ref": 5040,
"name": "sym.__libc_csu_init"
},
{
"type": "DATA",
"at": 4225,
"ref": 4935,
"name": "main"
},
{
"type": "CALL",
"at": 4232,
"ref": 16352,
"name": "reloc.__libc_start_main"
}
]
```
=> Fix axff and add JSON support

libr/core/canal.c
Now it would be more readable for humans:
```
...
"codexrefs": [
{
"addr": 4898,
"type": "CALL",
"at": 4441
},
{
"addr": 4811,
"type": "CODE",
"at": 4472
},
{
"addr": 4490,
"type": "CODE",
"at": 4553
},
...
```
=> Make afij ref-types more readable for human animals

libr/bin/p/bin_bios.c
=> Fix #12781 - Add check for MZ magic in bin_bios.c

libr/core/cmd_anal.c
Hi there,
when executing aef on a function currently only the first instruction of each basic block will get emulated (over and over again). This is because the buffer pointer is not incremented. This patch aims to fix this.
| OS/arch/bits (mandatory)                             | Manjaro X86 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20775 @ linux-x86-64 git.3.1.3-354-gc3bf8d161 commit: c3bf8d161b4835e59d7923aafe6d44de3b5234d0 build: 2019-01-17__23:24:22
```
r2 /usr/lib/libc.so.6 …
```
=> Fix addressing of instructions in aef

libr/config/config.c, libr/cons/canvas_line.c, libr/cons/cons.c, libr/cons/dietline.c, libr/cons/grep.c, libr/cons/hud.c, libr/cons/input.c, libr/cons/pal.c, libr/cons/rgb.c, libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/cmd_debug.c, libr/core/cmd_eval.c, libr/core/cmd_print.c, libr/core/cmd_search.c, libr/core/core.c, libr/core/disasm.c, libr/core/graph.c, libr/core/panels.c, libr/core/task.c, libr/core/visual.c, libr/core/vmenus.c, libr/include/r_config.h, libr/include/r_cons.h, libr/include/r_core.h, libr/util/print.c
TODO:
- Copy palette instead of initializing default when creating a new context, so a new task inherits the palette from the one it is started from
- Kill the global `curtheme` (and maybe `getNext`) in cmd_eval.c and move it to RConsContext
fixes #12644
=> Move Palette to RConsContext

libr/bin/mangling/cxx.c, libr/core/cbin.c
Hi there,
in some occasions relocs and exported symbols are not demangled. This patch aims to fix this.
| OS/arch/bits (mandatory)                             | Manjaro X86 64
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.3.0-git 20852 @ linux-x86-64 git.3.2.1-152-g21cde44c7 commit: 21cde44c7d70dbd27e4622af90e53664d8723e3d build: 2019-01-22__22:39:06
```
$ r2 /usr/lib/libstdc++.so.6
[0x00089020]> iE
...
5533 0x000bbe70 0x000bbe70 GLOBAL   FUNC    5 std::_V2::error_category::~error_category()
5541 …
```
=> Fix demangling of relocs and exported symbols

libr/core/canal.c, libr/core/cmd_print.c, libr/include/r_core.h
This command will print all the `CALLS` from a given function. The API is now also used by `aflm` which was introduced last week and was adapted in this PR. 
While `aflm` will print all the calls from all the functions, the new `pifc` command would do that only for a specific function.
```
[0x00001347]> pifc
0x0000135d call sym.imp.puts
0x00001369 call sym.imp.puts
0x00001382 call sym.beet
0x00001392 call sym.imp.puts
0x000013a0 call sym.imp.puts
```
and in a JSON format:
```
[0x00001347]> pifcj~{}
[
{
"dest": "sym.imp.puts",
"addr": 4160,
"at": 4957
},
{
"dest": "sym.imp.puts",
"addr": 4160,
"at": 4969
},
{
"dest": "sym.beet",
"addr": 4822,
"at": 4994
},
{
"dest": "sym.imp.puts",
"addr": 4160,
"at": 5010
},
{
"dest": "sym.imp.puts",
"addr": 4160,
"at": 5024
}
]
```
Screenshot:
=> Add new command: pifc and pifcj

libr/core/cmd_anal.c
Should close #12852. Also why `aeafj` output is different from `aeaf` ?
=> update aea? (#12849) and display @{R,W} in aeaj

libr/core/cmd_open.c
This is more than just wrong. Sleep should only be used when absolutely no global stuff is accessed while active. And what is done here is the exact opposite of that.
Maybe something inside `r_core_file_open()` or `r_core_bin_load()` could be wrapped in sleep, but definitely not the whole functions.
=> Remove invalid sleep from cmd_open()

libr/bin/mangling/microsoft_demangle.c
The issue can be triggered by long (over 1033 bytes) symbol names in _pdb_ file. Usually default allocation can handle the copied string, but when it is large `strcpy` overruns destination buffer, since `str_for_copy_len` holds value of `copy_len` while the string itself is way longer.
=> Fix buffer overrun on pdb file read

libr/core/cmd_flag.c, libr/flag/flag.c
Introduce fnj command which behaves similar to fj, except for the fact that demangled names are used instead.
```
r2 bins/elf/demangle-test-cpp
[0x000010d0]> fnj~{245}
{"name":"reloc.operatordelete(void*)","size":8,"offset":16432}
[0x000010d0]> fj~{245}
{"name":"reloc._ZdlPv","size":8,"offset":16432}
```
=> Introduce fnj command

libr/anal/vtable.c
Hi,
when executing `avj` in cases where no virtual tables are present nothing is returned. This is not "broken" per se, but differs from the behavior of other output-in-json-commands. For instance when using r2pipe in python NoneType is returned in such a case. In other cases (i.e. `dmj`) an empty list is returned if there is nothing to show. This patch aims to fix this.
Please note that removing that check has no impact on the behavior of the function, except that it prints `[]` in the case described above, because each further action is covered by a `r_list_foreach`-statement which does nothing in case the given list is a nullptr. 
| OS/arch/bits …
=> Fix avj - in case of no vtables [] shall be returned

libr/bin/format/pe/pe.c
=> PE parsing: Fix the call to parse_symbol_table to correctly append the COFF symbols

libr/core/cmd_print.c
Before, w could be 0 in special cases at line 2667, therefore crashing at line 2690 due to a division by 0. Now it gets rid of all spaces in between commands. 
*Note that code line numbers have changed, I am referring to old code line numbers*
=> Fixed issue 12934

libr/core/disasm.c
This PR is adding an indicator for each instruction, saying whether it is in the relocation table.
This will be shown to the user in `pdj`, `pij` etc
=> Add reloc indicator to json disassembly to explain wheter an address is relocated

libr/util/print.c
The dots are somewhat distracting.
=> io.unalloc=true: print space in ascii hexdump if unmapped

libr/asm/arch/arm/armass.c, libr/asm/p/asm_x86_nz.c
This fixes all failing assembler tests for Windows (I think).
=> Fix assembler for Windows

libr/cons/grep.c, libr/util/sys.c, libr/util/w32-sys.c
This will hopefully fix some tests that are failing for Windows.
=> Fix env. vars. not being parsed in !! in Windows

libr/util/file.c
Before, if you set for example:
`e dir.projects = myprojects/`
It would result in an invalid path when creating a file:
`C:\path\to\myprojects/\file`
=> Fix Windows path with / in the last position

libr/anal/anal.c, libr/core/core.c, libr/flag/flag.c, libr/include/r_util/r_event.h, libr/include/r_vector.h, libr/util/event.c
Unit tests for REvent: https://github.com/radare/radare2-regressions/pull/1677
After these changes, the ht uses RVector<REventCallbackHook> as the key instead of RPVector. Also, hooked callbacks are referred by a unique handle.
=> Add user * to REvent Hooking

libr/core/cmd_cmp.c, libr/util/file.c
This uses the native Windows API to do the parsing.
Fixes the problems it had with `../example` paths and `folder/file`
+Fix for copy command
=> Better fix for abspath for Windows

libr/bin/format/pe/pe.c
I don't fully understand the function `_parse_resource_directory` : I hope this patch don't break anything.
I didn't find a better way to fix that, without refactoring the function code...But any suggestions are welcome.
=> Fix: issue #13035

meson.build
acr+make does work because it does not set any lib version on darwin. This patch
will adjust the version used in libraries when radare2 is installed through meson.
=> OS X does not seem to accept X.Y.Z-git as lib version

libr/core/visual.c
Fixing the visual mode toggle for emu.str.
This was broken in this commit: https://github.com/radare/radare2/commit/5234164ab2a227a83e32dbf96fe9a2a52980572e
Currently '(' and ')' toggle snow. This PR restores ')' to toggle emu.str
=> Fix toggle emu.str in visual mode

libr/core/canal.c
Hi there,
i discovered that agfj produces invalid json in some circumstances. If a function, for what ever reason, contains a basic block with negative size the json will not be valid. Although this does not fix the root cause of the problem, i still think i better to at least get a valid json output. The main problem with invalid json for me is, that it fails silently when using r2pipe (in python).
| OS/arch/bits (mandatory)                             | Manjaro x86 64
| r2 -v full output, **not truncated** (mandatory)     | …
=> Fix agfj -- invalid json

libr/core/canal.c, libr/core/cmd_print.c, libr/core/core.c, libr/core/disasm.c, libr/include/r_core.h, libr/include/r_util/pj.h, libr/util/pj.c
As requested in PR https://github.com/radare/radare2/pull/13051 a port of agfj (and other commands) to pj.
The change is quite large, so you maybe want to make sure that i didn't mix up the types of  the variables that are put into the json
=> Use pj for agfj (and others)

libr/core/cmd_anal.c
For issue #12690.
The code produced the output:
The outputs of `axt` and `axf` along with their subcommands are not similar at all. This is the simplest implementation that I could think of without rewriting the same code under `ax.`. Please tell me if I could have done something better or any changes that I should make.
=> Implemented ax. command

binr/radare2/radare2.c
Paths in windows contain '\\', escaping breaks things.
=> Do not escape path to Windows file

configure, configure.acr
First, this requires radare/acr#20, so that we can auto-generate a configure that can recognize 'wsl'
=> Disable ptrace-wrap for WSL

libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c
=> Fix #11759 - aac now names import trampolines

libr/core/cmd_anal.c, libr/core/graph.c, libr/include/r_cons.h, libr/include/r_util/pj.h
For axgj command the prev json was `{"34897234":{"refs":[{"2342355":{"type":"fcn...` The address field was displayed as a string. 
Now after refactoring it shows `{4294971308:{"refs":[{4294971215:{"type":"fcn","fcn_addr":4294971200,"name":"entry0","refs":[]}}]}}`  
Should I make it string or keep it as it is?
Edit: I'll just keep it as string
=> Refactored cmd_anal.c to use PJ.c 

libr/anal/p/anal_dalvik.c, libr/asm/p/asm_dalvik.c
I tried to add bound checks to avoid #13072. 
I don't really know if they are well placed. And the check in `dalvik_op` is to avoid a read out-of bounds, but I don't know if it's correct.
=> Try a fix for #13072

libr/core/cmd_type.c, libr/include/r_core.h, libr/util/ctype.c
1. Improved `tsj` and `tuj`.
2. Modified function to calculate size of unions along with structs.
Before:
After:
=> Improved json for tsj/tuj and completed size calculator for struct/union

doc/fortunes.fun
I've noticed that this fun one-liner looks very much like Clojure code, but doesn't actually work, so I took the liberty to fix it. It also works in ClojureScript as tested with lumo.
=> Make Lisp fortune work with Clojure(Script)

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0.h, libr/bin/format/objc/mach0_classes.c, libr/bin/format/objc/mach0_classes.h, libr/bin/p/bin_dyldcache.c, libr/bin/p/bin_mach0.c
ObjC categories are now parsed as regular classes, their name is `TargetClass(CategoryName)`. They're handled correctly even if the target class in a reloc, even without symbol table present. Categories are parsed also in the dyld library cache.
Additional fixes in parsing relocs:
- correctly manage lazy and weak bindings
- reduce memory usage by using a dynamic list
- retain the symbol name from the dyld opcodes when no symtab is there
Example output:
```
[0x00000000]> ic~ class | grep ')$'
0x1b1b4df40 [0x180d9343c - 0x180ebc158] (sz 1215772) class 0 NSObject(NSObject)
0x1b1b4e0a8 [0x180db4c20 - 0x180ebc1d4] (sz 1078708) class 0 NSObject(NSKindOfAdditions)
0x1b1b4e448 [0x180dadfe0 - 0x180dadfe0] (sz 0) class 0 NSObject(__NSCFType)
0x1b1ca1100 [0x18151d930 - 0x18151d968] (sz 56) class 0 …
```
=> Parse ObjC categories

shlr/Makefile
If the user already provides a capstone tarball, the buildsystem should not try
to download it again.
=> Fix offline build w.r.t. capstone

libr/core/canal.c
Data references analyzer assumes that each function reference maps
to a certain section, but this is not the case for raw binary files
like shellcodes/firmware images/etc.
This bug was introduced in #10117.
=> Fix NULL pointer dereference in data references analyzer

libr/anal/p/anal_chip8.c
- Default to unknown type
- Detect RET
- Remove fail from always succeeding jump/call
- Move keypad commentary to LD Vx, K
- Annotate skips correctly
- Annotate more instructions
One thing I'm not sure about is the "JP V0, nnn" instruction. It jumps to the value of the embedded address, incremented by the contents of register `V0`. Therefore it's incorrect to annotate it to jump to `nnn` because the address might be anywhere between `nnn` and `nnn + V0`. Maybe it's better to not annotate it at all? Or is there support for annotating ranges?
=> Improve CHIP-8 analysis

libr/bin/p/bin_avr.c
`RLibStruct` and `R_LIB_TYPE_BIN` are used in `bin_avr.c` but the header `r_lib.h` was not included and so was giving an error.
=> Added missing header file in bin_avr.c

libr/bin/p/bin_mz.c
=> Added missing include of r_lib

libr/anal/fcn.c
Fixes the XREF XX tests in #13193.
=> recurseAt: Also update size in fcn rbtree

libr/anal/p/anal_x86_cs.c
BSF: https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf#G5.925704
BSR: https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf#G5.21931
=> x86: generate ESIL code for BSF/BSR instructions

libr/anal/fcn.c, libr/anal/flirt.c, libr/anal/p/anal_java.c, libr/core/canal.c, libr/core/gdiff.c, libr/include/r_anal.h, libr/include/r_sign.h
For #13193 and also for greater flexibility in implementing the fcn rbtree.
=> Pass RAnal instead of rbtree to fcn rbtree api

binr/rafind2/rafind2.c
`rafind2 -x f.f.` doesn't behave like `/x f.f.` in r2. This patch adjusts this behavior unless a mask is provided.
Please let me know if you consider this change to warrant mention in the manual or usage help.
=> Make -x behave like /x unless mask is provided

libr/core/cconfig.c, libr/core/disasm.c
Add eval for refptr and disable it by default, should reduce the volume of output in disassembly while leaving the user able to show this information back
```
Default Before:
0x100001237      c7058f420000.  mov dword [0x1000054d0], 0x50    ; 'P' ; section.10.__DATA.__data ; [0x1000054d0:4]=80 ; U"P."
Default After:
0x100001237      c7058f420000.  mov dword [0x1000054d0], 0x50    ; 'P' ; section.10.__DATA.__data ; U"P."
```
=> Add eval for refptr #asm

libr/core/cbin.c
deleted the "sz" from classlisting.
=> Fix #13190 - remove sz from classlisting

libr/asm/p/asm_chip8.c
See also https://github.com/radare/radare2-regressions/pull/1736
=> Remove extraneous space for scd instruction

libr/bin/bfile.c
It seems this loop is an unnecessary leftover from the past when `string_scan_range` didn't initialize string's `vaddr` field.
This improves performance dramatically, especially when there are thousands of sections (like for kernelcache and dyld cache).
=> Remove redundant section lookup in get_strings_range

libr/bin/format/bflt/bflt.c, libr/bin/format/mach0/mach0.c, libr/bin/p/bin_any.c, libr/bin/p/bin_art.c, libr/bin/p/bin_avr.c, libr/bin/p/bin_bf.c, libr/bin/p/bin_bflt.c, libr/bin/p/bin_bios.c, libr/include/r_bin.h, libr/include/r_util/r_buf.h, libr/util/buf.c
Some of the bin plugins in https://github.com/radare/radare2/issues/13349
=> Implement load_buffer/check_buffer in RBinPlugins

libr/core/cmd_open.c
Fixes https://github.com/radare/radare2/issues/13361
=> Fix crash when executing `om`

libr/bin/p/bin_art.c
ao->kv's ownership is moved to RBin through the get_sdb method of
RBinPlugin, thus the plugins should not free it themselves.
=> bin_art: avoid double free

libr/core/linux_heap_glibc.c
The 'display' routine of the malloc_chunk should display each field of
flag field as bits.
So prior to this proposal, `dmhc` could yield following information:
```
struct malloc_chunk @ 0x7f5462ed4000 {
prev_size = 0x0,
size = 0x1112000,
flags: |N:4 |M:2 |P:1,
```
The flags should be displayed as: `flags: |N:1 |M:1 |P:1`
=> Displaying chunk flags as bits

libr/io/map.c
When two maps start at the same address, it's important to consider the
initial priority of the maps, which is given by the `id` field.
r2r PR: https://github.com/radare/radare2-regressions/pull/1745
=> Consider the map sorting when two map_events are the same.

libr/anal/esil.c
esil's handling of negative numbers isn't perfect, but when subtraction is involved, it's basically non-existant.
For example, `ae 3,-4,+` results in `0xffffffffffffffff` (since esil treats all numbers as `ut64`, and it's tricky to know when to treat it as signed/unsigned). So, a bummer, but at least it works.
However, `ae 3,-4,-` returns nothing (as opposed to the expected `0xfffffffffffffff9`). Reason: the current implementation of `esil_sub` reads the parameters directly, and validates that they are numbers only by checking for digits (instead of using the more generic `r_anal_esil_get_parm`, used in `esil_add`, `esil_mul`, and `esil_div`, that supports negative numbers as well).
This PR fixes the issue - the code for `esil_sub` is copied from `esil_add`, with the actual operation, `s …
=> Fix esil negative numbers

libr/include/r_parse.h, libr/meson.build, libr/parse/meson.build, libr/parse/p/Makefile, libr/parse/p/chip8_pseudo.mk, libr/parse/p/parse_chip8_pseudo.c, plugins.def.cfg, plugins.static.cfg
I have a few questions:
- Any preferences for the copyright line?
- How exactly is memory management done here? I've compared with other parse functions and found a lot of heap-allocated memory that is neither used nor freed afterwards...
- Any other files I need to edit to include the plugin properly?
- How can this kind of plugin be tested?
- Does the logic look good to you? If yes, the same kind of changes can be done to the other parse plugins as well.
=> Add chip8 pseudo support

libr/anal/p/anal_m68k_cs.c, libr/asm/p/asm_m68k_cs.c
- Fill op->jump and op->fail for all branch and jump instructions
- Handle short and word variants of BSR (BSR.S and BSR.W)
- DBxx instructions treated as conditional branches
- Handle PC relative variant of JMP & JSR
- Bugfix for the decoding of long instructions (code in asm_m68k_cs.c assumed a maximum of 8 bytes, but maximum is 10 bytes)
=> m68k analysis fixes:

libr/anal/bb.c, libr/anal/fcn.c, libr/anal/p/anal_arm_cs.c, libr/include/r_anal.h
- store cmpval and cmpreg in every basic block
- lookup cmpval from predecessors considering TBH’s index register
test here: https://github.com/radare/radare2-regressions/pull/1750
=> Improve arm TBH jump table ##anal

libr/debug/p/native/linux/linux_coredump.c
ARM_VFPREGS_SIZE is defined in asm/ptrace.h
=> fix arm-musl compatibility

libr/anal/var.c, libr/core/anal_tp.c
I don't like the whole type renaming code, but that will require more changes, so let's do it later.
=> Fix #13000

shlr/sdb/config.mk
`OS`  can have already be set to other values on user machines, `OS=` fits better here.
=> Improve Makefile on macOS

libr/bin/format/wasm/wasm.c
I was doing another refactoring for RBuf and this wasm code was using it sooo much, so I ended up simplifying it a bit to avoid duplicated code.
=> Simplify WASM code by avoiding duplications

libr/include/r_util/r_sys.h, libr/util/sys.c, libr/util/w32-sys.c
- pipe data is being treated as a string instead of binary data so first \0 truncates it
Fixes the following bug from regression tests:
```
[00:08:39] [XX] db\tools\radiff2 radiff2 -B (GDIFF support) #1  788
[00:08:39] $ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i C:\Users\appveyor\AppData\Local\Temp\1\tmp-2356IRggMMYPaNOb.tmp -
[00:08:39] !!radiff2 -B ../bins/other/radiff2/radiff2_c_1 ../bins/other/radiff2/radiff2_c_2 | rax2 -S
[00:08:39] 
[00:08:39] -d1ffd1ff04019000
[00:08:39] +d1ffd1ff040190
[00:08:39] 
[00:08:39] EXPECT=<<RUN
[00:08:39] d1ffd1ff040190
```
Related to #13441
=> Fixes pipes implementation on windows

libr/bin/bfile.c, libr/bin/bin.c, libr/core/cbin.c, libr/core/cconfig.c, libr/core/cmd_info.c, libr/include/r_bin.h, libr/main/radare2.c, libr/util/pj.c
- changed the output json keys, now there will be `md5` and `sha1` instead of `values`
- small refactoring on hashes storage
- removed obsolete `file.sha1` usage
Related to radareorg/cutter#1179
=> Fixes #1179 - `itj` hashes calculation command has fixed

libr/asm/asm.c, libr/core/cmd_print.c, libr/include/r_asm.h
WIP because actually using this in an ASan build triggers crashes. This can be reproduced using any of these, showing that it's not the fault of the newly added chip8-parse plugin.  The `ASAN_OPTIONS` setting is to supress false positives for memory leaks.
```
ASAN_OPTIONS=detect_leaks=0 r2 -a x86 -b 32 -e asm.pseudo=1 -q -c 'pad 7400' -
ASAN_OPTIONS=detect_leaks=0 r2 -a chip8 -q -e asm.pseudo=1 -c 'pad c97f' -
```
See also https://github.com/radare/radare2/issues/13429
=> WIP: Support asm.pseudo=1 in pad command

libr/core/cbin.c
Hey, first contribution here. Very small one. 
When using the command `iI` in radare2 or `-I` in rabin2, `sanitiz` was before `class` and it seems that alphabetical order was intended, so I changed its position.
Thank you.
=> Change 'sanitiz' position from bininfo to be according alphabetical order

libr/flag/tags.c, libr/util/str.c
- chash fixed when tag is not found (on Windows)
- memory leak fixed (`words`)
The crash reason is because the following line of code can return NULL when tag is not found:
```c
char *words = sdb_get (f->tags, k, NULL);
```
then this NULL will go to `r_str_split_list`  which uses `strtok` (unsafe func) and passes NULL as first argument on the **first**  iteration so this forces strtok algorithm to utilize static variable which caches tokenizing status, which can be NULL or already freed memory.
=> Fix `ft` command crash on Windows

shlr/heap/include/r_jemalloc/internal/jemalloc_internal.h
On gcc 9.x, `__riscv__` is no longer defined but `__riscv` is.
This is documented under C/C++ preprocessor definitions on
https://github.com/riscv/riscv-toolchain-conventions
edit: Might be that this needs to be sent to `jemalloc` upstream, but I wasn't able to find where
=> Fix build on newer RISC-V compilers

libr/core/cmd_write.c
`wcr` command fixed. Now it will preserves cache permissions
**Before:**
**After:**
=> Fixes `wcr` command

libr/anal/p/anal_m68k_cs.c, libr/asm/p/asm_m68k_cs.c
* m68k architecture is always 32 bits and big endian
* SP was declared as 'sp' in the register profile which doesn't exist. Stack pointer is a7.
* Most C compilers for m68k (e.g. LatticeC) use a6 as stack frame pointer via LINK and UNLK instructions, declare a6 as BP
=> m68k register fixes

libr/core/cmd_print.c, libr/core/core.c, libr/core/visual.c, libr/include/r_core.h
=> Vpp"c now properly rotates

libr/debug/map.c
eco twilight
Before:
After (**w/x** mem regions [execstack]):
After: (**no w/x** mem regions/desired state):
=> dm= now honors theme (eco) settings + wx sections are highlighted ##cons

libr/cons/pipe.c, libr/core/cmd.c, libr/core/cmd_api.c, libr/core/cmd_help.c
pd 10 > $foo  # save the output of pd 10 into $foo
$foo          # print the contents of $foo (the output)
$*            # values are now printed in base64
$foo=base64:  # is now supported
=> Initial implementation of alias files ##core

libr/util/utf8.c
Reduces time spent in r_isprint from ~30% to ~2% in my tests.
Measured with valgrind cachegrind.
Appears to have minor real-world performance improvements (2% less time spent with a long r2pipe script).
=> added an early-out optimization for r_isprint. 

libr/main/radare2.c
When using debugger the file assumed path for the auxillary script
was dbg://...binary path.r2, without debugger it's just ...binary path.r2.
This patch cuts out the 'dbg://' prefix, if found, before looking for the
auxillary script.
Fix for https://github.com/radare/radare2/issues/13363
=> [13363] Remove URI handler before looking for auxillary script

libr/core/cmd_anal.c, libr/core/cmd_mount.c
* Do not take as valid hits the words found inside a function (considered code)
* Honor anal.arch.align
* Call it after aac in aaa
=> Improve aav ##anal

libr/bin/format/mach0/mach064_is_kernelcache.c, libr/bin/p/bin_mach064.c, libr/bin/p/bin_xnu_kernelcache.c
Parse load commands to extract 3 metrics (kudos to @Siguza for suggesting):
- use of LC_UNIXTHREAD
- absence of any library linked against
- addresses in the upper half of the address space
If those are met, then it’s a kernelcache. This just needs to parse all load commands types and vmaddr from LC_SEGMENT_64 (but nothing more) from the bytes.
Plus: no big endian kernelcaches so far.
=> Rewrite kernelcache check_bytes

libr/bin/p/bin_dex.c
clusterfuzz-testcase-minimized-ia_fuzz-5651766995058688.dms
=> Fix integer overflow that leads to a crash in the DEX parser ##bin

libr/bin/format/mach0/mach064_is_kernelcache.c
Since for now only arm64 kernels are supported.
=> Fail kernelcache check for non-arm64 kernels

libr/core/patch.c
For example, this line 'OFFSET : nop;nop;nop' (provided in the example patchfile at binr/rabin2/patch.txt) now actually works
=> Add support to multiline assembly patching

libr/core/disasm.c
about this #13259
but still not thoroughly done probably and so much room to improve so you'd better keep this issue open just yet.
=> asm.var.summary should be on if the screen is too small ##visual

libr/core/cmd_anal.c, libr/core/cmd_search.c, libr/include/r_core.h
=> Include aap in aaa

libr/include/r_types.h
Make sure that `asm.arch` and `anal.arch` is set correctly when starting radare on RISC-V.
(tested on SiFive Unleashed board w/ `gcc 9.0.1`)
=> Build arch detection for RISC-V

libr/include/r_core.h
the function doesn't exist anymore as of #13558
=> Remove dead r_core_save_parsed_type() declaration

libr/anal/p/anal_riscv.c
Add `get_reg_profile` call for RISC-V. In this profile, include the integer and floating point registers. Use the ABI register naming instead of the architectural one as this was chosen in the disassembler.
This is straightforward as the user-level ISA only specifies these registers. In RV-I there are no flags, and only a few read-only counter CSRs are accessible from user mode which (I think) don't need to
be in this structure. In RV-F/D there is one 32-bit CSR containing a few flags.
This addition is not quite enough to get analysis or debugging working, but can be a step towards that, and prevents warnings about being unable to import the register profile from isil during launch on RISC-V.
Also update bits to `32|64` instead of `16|32`—there is no 16-bit RISC-V.
=> anal_riscv: Implement get_reg_profile

libr/core/cmd_flag.c, libr/flag/flag.c
`fC` (and `f`) command now accepts base64 encoded strings prefixed with `base64:` similar to `CC`. In addition, `f*` now automatically armors the comment string with base64 before printing.
This PR also fixes the issue of optional comment in `f` being ignored when the command executes.
=> Make flag comments base64-compatible

libr/core/canal.c, libr/core/cmd_anal.c, libr/core/vmenus.c
* aflsa, aflsb, aflsn, aflss - sort by addr, bbs, name or size
=> Add more function sorting methods and reduce unnecessary resorts ##anal

libr/core/cmd_search.c
https://asciinema.org/a/0LnnzCR0ohoZdCnG17E34vcDI
search->data is only allocated on the first time it is used... aap will do a search, allocate it to fit 4 bytes of search data, and then never R_FREE it. The next time a search is done, it wont re-allocate, and wont have enough size for the search string.
see r_search_mybinparse_update() for more info.
All the other searches (that i can tell) use r_search_kw_reset to properly free seach->data when they are done with it.
=> added a call to r_search_kw_reset in r_search_prelude to fix arbitrary heap oob write

libr/core/disasm.c
```
$ r2 -A ~/dev/karta/pngrutil.o 
[0x0800132c]> pdfs
0x0800132c call reloc.png_crc_read_45
0x0800133b call reloc.png_get_uint_32_60
0x08001352 call reloc.png_crc_read_83
0x08001361 call reloc.png_get_uint_32_98
0x0800138d:
0x08001398 call 0x8001399
0x080013a8 call reloc.png_crc_finish_169
0x080013b5:
0x080013cd call reloc.png_crc_read_206
0x080013dc call reloc.png_get_uint_32_221
0x080013f3 call reloc.png_crc_read_244
0x08001402 call reloc.png_get_uint_32_3
0x08001427 call 0x8001428
0x08001437 call reloc.png_crc_finish_56
0x08001444:
0x0800145c call reloc.png_crc_read_93
```
```
$ r2 -A ~/dev/karta/pngrutil.o 
[0x0800132c]> pdfs
0x0800132c call png_crc_read
0x0800133b call png_get_uint_32
0x08001352 call png_crc_read
0x08001361 call png_get_uint_32
0x0800138d:
0x08001398 call …
```
=> Call to same relocs must have same name instead of appending number

libr/core/canal.c
=> Make agj work in any offset inside a function, not just the first instruction ##anal

libr/core/meson.build
Description of the warning:
```meson
libr/core/meson.build:118: DEPRECATION: Library r_core was passed to the "libraries" keyword argument of a previous call to generate() method instead of first positional a
rgument. Adding r_core to "Requires" field, but this is a deprecated behaviour that will change in a future version of Meson. Please report the issue if this warning canno
t be avoided in your case.
```
=> meson: Fix deprecation warning in libcore

meson.build
To be able to use completion with zsh, completion script must be in
the `fpath` variable. On Ubuntu, these paths are:
```console
% print -ln $fpath
/usr/local/share/zsh/site-functions
/usr/share/zsh/vendor-functions
/usr/share/zsh/vendor-completions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/<.. redacted ..>                               
```
On Arch Linux, these paths are:
```console
% print -ln $fpath
/usr/local/share/zsh/site-functions
/usr/share/zsh/site-functions
/usr/share/zsh/functions/Calendar
/usr/share/zsh/functions/Chpwd
/usr/share/zsh/functions/<.. redacted ..>              
```
So if r2 users install radare2 with `prefix=/usr/local`, completion will **not work** 
on both Ubuntu and Arch Linux. In this case, users have to [edit …
=> meson: Change completions installation directory

libr/core/cconfig.c
This PR wishes to enable `asm.jmpsub` by default. This is as a continue to the conversation on Telegram and on PR #13524.
Please notice the calls in these two outputs:
=> Enable asm.jmpsub by default

libr/anal/p/anal_arm_cs.c, libr/bin/format/elf/elf.c
My goal was to add a new glibc signature (so "s main" would work), and I ended up fixing other issues as well.
[gcc-linaro-arm-linux-gnueabi-2012.01-20120125_linux](https://releases.linaro.org/archive/12.01/components/toolchain/binaries/gcc-linaro-arm-linux-gnueabi-2012.01-20120125_linux.tar.xz) (GCC 4.6.3, glibc 2.13) produces binaries with the following entry point that require the new signature:
```
[0x000082bc]> pd20
;-- entry0:
;-- section..text:
;-- pc:
;-- r15:
0x000082bc      4ff0000b       mov.w fp, 0                 ; [13] -r-x section size 220 named .text
0x000082c0      4ff0000e       mov.w lr, 0
0x000082c4      5df8041b       ldr r1, [sp], 4
0x000082c8      6a46           mov r2, sp
0x000082ca      4df8042d       str r2, [sp, -0x4]!
0x000082ce      4df8040d       str r0, [sp, …
```
=> arm improvements/refactoring

libr/core/canal.c, libr/core/cbin.c, libr/core/cmd_anal.c, libr/core/cmd_open.c, libr/core/visual.c, libr/include/r_core.h
Closes #13596
* One obvious blunder is the location of the code, I know it's wrong the place but I kept it there until the table API is written.
* I will add more fields for afb= or afl= as per direction, right now they have very less number
Screenshots after the change:
=> Fix #13596 - Implement afb= and afl= and and refactor

libr/core/disasm.c
This to continue the PR by @sivaramaaa https://github.com/radare/radare2/pull/13524.
Before:
```
[0x08000034]> pdj 1 @ 0x0800132c ~{}
[
{
"offset": 134222636,
...
"opcode": "call 0x800132d",
"disasm": "call reloc.png_crc_read_45",
"bytes": "e8fcffffff",
"family": "cpu",
...
```
After ("_45" is removed from "disasm"):
```
[0x08000034]> pdj 1 @ 0x0800132c ~{}
[
{
"offset": 134222636,
...
...
"opcode": "call 0x800132d",
"disasm": "call png_crc_read",
"bytes": "e8fcffffff",
"family": "cpu",
...
...
=> Honor asm.jmpsub in pdj output

libr/bin/format/mdmp/mdmp.c, libr/bin/format/mdmp/mdmp_specs.h
The elements are directly after the headers, there is no pointer
involved.
Also, use r_buf_read_at instead of r_buf_get_at in mdmp.
=> Replace pointer with an array of variable size

libr/anal/anal.c, libr/anal/op.c, libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_x86_cs.c, libr/core/cmd_search.c, libr/include/r_anal.h
* /am is like /c but only search for instructions and uses R_ANAL_MASK_DISASM
* Added new op family: R_ANAL_OP_FAMILY_PAC; (see /af)
=> Implement /am and add initial support for PAC instructions ##anal

libr/core/panels.c
Ideally, a panel should be rotatable so that you can rotate entropy->entropy fire in a panel i think.
=> Entropy fire added in the menu ##panels

libr/core/cmd_cmp.c, libr/core/core.c, libr/util/print.c
I'm considering #defining _r_cons_singleton()->context->pal.x_ in _r_core.h_ , to not obscure the code further with such long statements, and do refactor for this piece of code and the previous changes.
If it does make sense for you, then I will propose the change via subsequent PR
=> Added missing c2 command + theme support for comparison commands ##cons

libr/util/format.c
Saves a JSON field, and more consistent with other pf formats regarding the meaning of `value`.
=> Put pfj z string in value field

libr/core/graph.c
fbe251a759a767f2ac3206dfd7edeb748bf6da56 changed the function of the Z key in visual graph mode but did not update the help text. This commit fixes the help text.
=> Fixed help text for 'Z' in visual graph mode

libr/core/visual.c
da6ec135dca8bc6b2b783c63c8ffc772aa9b4028 changed the key for seek in visual mode from 'o' to 'g' but didn't change the help text. This commit fixes the help text.
=> Fixed help text for visual seek ('o' ->'g')

libr/core/cmd.c, libr/core/cmd_print.c, libr/io/map.c
```
@@@           # foreach offset+size iterator command:
x @@@=       [addr] [size] ([addr] [size] ...)
x @@@b       basic blocks of current function
x @@@c:cmd   Same as @@@=`cmd`, without the backticks
x @@@C:cmd   comments matching
x @@@i       imports
x @@@r       registers
x @@@s       symbols
x @@@S       sections
x @@@m       io.maps
x @@@M       dbg.maps (See ?$?~size)
x @@@f       flags
x @@@f:hit*  flags matching glob expression
x @@@F       functions (set fcn size which may be incorrect if not linear)
x @@@F:glob  functions matching glob expression
x @@@t       threads
x @@@r       regs
```
=> Implement the missing bits in the triple-at ##core

libr/core/cconfig.c, libr/core/disasm.c, libr/core/visual.c
=> Fixes #13713: vr rotates between JMP, CALL and DATA reference hints

libr/core/cfile.c, libr/main/radare2.c
Before ESIL would overwrite the PC to be on the entry0
=> Fix coredump PC not being considered

libr/core/cmd_type.c
fix   #13640 
I have added this feature under command `toe`  aka "type open and edit" :D
UPDATE  :
=> Added a command to edit types using cmd.editor ##types

libr/core/cmd_anal.c, libr/core/cmd_search.c, libr/core/disasm.c, libr/include/r_anal.h, libr/include/r_parse.h, libr/parse/parse.c
It's a miracle this didn't show up breaking everything before.
Disassembly code was setting `core->parse->hint` to an instance it allocated itself, then freed this instance, but never reset `core->parse->hint`, which led to uaf or in my case use of completely unrelated data allocated by Qt. Best solution was to just kill this scary global state.
=> Remove RParse.hint to fix Segfaults ##parse

libr/core/panels.c, libr/core/visual.c, libr/core/visual_tabs.inc, libr/include/r_cons.h, libr/include/r_core.h, libr/include/r_util/r_panels.h
Initial support for tab key, but just not tab key, 't' instead, because people already got used to using tab key as a key to move around tabs, so.
=> t key instead of tab key is supported in Disassembly panel ##panels

libr/debug/p/native/linux/linux_coredump.c
Coredump generation no longer works for me on very recent kernel. The PR just changes `linux_coredump.c` to use `r_debug_ptrace ()` instead of `ptrace ()` directly what seems to fix the issue for me.
| OS/arch/bits (mandatory)                             | Arch Linux 5.0.7-arch1-1-ARCH
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.5.0-git 21932 @ linux-x86-64 git.3.4.1-189-g83b62183d
commit: 83b62183d917e69ef7979932d57491f3d7f74dc7 build: 2019-04-19__19:16:23
`> r2 -dq /bin/true -c dg
Process with PID 698 …
=> fix dg on recent linux kernels

libr/core/cmd.c
$ r2 -c '"w hello # world"' -qcps -
=> Fix bug when quoting a comment ##core

libr/core/cconfig.c, libr/include/r_util/r_print.h, libr/util/print.c
the reason to not use the bg is beacuse it conflicts with Cons_INVERT if we want to highlight a row and also because it will look bad in panels.
before:
after:
=> Make p= bars dont use the background color ##cons

libr/core/disasm.c
`asm.var.summary` must equal -1 for the values to be displayed
=> Fix #13672: Display variables value in the disasm view

libr/core/cmd_anal.c
Fix for comment at https://github.com/radare/radare2/issues/13825#issuecomment-485068356.
Previously, the method `is_unknown_file` used to return `false` if `core->bin->cur` or `core->bin->cur->o` are null. By changing that assumption this works for r2 -n as well.
=> Assume filetype is unknown if `core->bin->cur` is null

libr/core/panels.c
I personally love this feature. 
people, including me, can use panels mode with the help msg being active all the time if they call it, and they can of course kill it anytime like any other panel.
=> A panel will be allocated for each help msg when it is called ##panels

libr/magic/d/default/java
Android magics for the following formats:  OAT, VDEX, CDEX, ART
```c
[0x00914000]> i~format,arch,dex
file     base.odex
format   elf
arch     arm
[0x00914000]> /m
0x00000000 1 ELF 32-bit LSB shared object, ARM, version 1
0x00001000 1 Android OAT file version 079
0x00001904 1 Android DEX file version 035
```
```c
[0x00000000]> /m
0x795fc000 1 Android ART file version 029
```
=> Android magic numbers until Android 9.x

libr/anal/sign.c
Avoiding creating an entry if the type is not known (at the moment).
=> Sign hash, possible mem leak fix.

libr/cons/dietline.c
For me the nice reverse-i-search feature was broken (it did only find the last occurrence of the command in search). Also I think it's nice to be able to just press CTRL+R again to continue searching in history so I don't have to reach the arrow keys.
=> Fix reverse i search

libr/core/cmd_print.c
=> Fix prc text color

libr/core/panels.c
...and fix a few potential bugs
=> Refactoring

libr/core/cmd_help.c
The non-JSON version of the command still differentiates between inputs greater/less than 32 bits and includes only the appropriate output.
=> Add unsigned decimal output to ? command

libr/core/panels.c
tab number starts off 1 to n
and also fixed a bug with which r2 will crash if you push 0 when selecting nth tab
=> Fixed a few things

sys/meson.py
So that one just needs to type in r-2 instead of r-a-d-a-r-e-2 on Windows.
=> sys/meson.py: Create r2.bat as alias to radare2.exe on Windows

libr/bin/p/bin_dyldcache.c
So pointers get rebased transparently during buffer reads. This makes objc class parsing work again.
=> Restore io buffer creation in dyldcache ##bin

libr/core/canal.c
Reason: https://stackoverflow.com/questions/1372480/c-redefinition-header-files-winsock2-h.
Fixes the AppVeyor build.
=> #include sdb/ht_uu.h after r_types.h

libr/anal/anal_ex.c, libr/anal/fcn.c, libr/anal/p/anal_java.c, libr/bin/p/bin_java.c, libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c, libr/core/disasm.c, libr/core/p/core_java.c, libr/include/r_anal.h, shlr/java/class.c, shlr/java/code.c, sys/rebuild.sh
* Current java implementation of the analysis is not working well
* RBin parser now puts the right section sizes
* Added anal.ex option to use extensions or not
* More to go
=> Code cleanup for anal.ex, make java work without it.

libr/anal/p/anal_arm_cs.c, libr/anal/p/anal_x86_cs.c, libr/anal/var.c
Filled op->src[0] and op->dst for LOAD, STORE, ADD and SUB in ARM. Some tests may not be passed, but I suppose the behaviour is correct (although I'm not an expert with ARM, so I would ask you to verify that), except 'db/cmd/types jni and SoP' where I'm not sure.
One more important thing: since ADD and SUB are working differently on different architectures (in x86 sub rax, rbx uses values of both registers, but on ARM SUB usually just overwrites destination without using its value), I had to add new `if `to rargs detection switch, and it checks for architecture used. If you have any better idea how to solve this problem, please share it. :) 
fix #13970
=> R anal op var for arm

libr/core/cmd_flag.c, libr/core/visual.c, libr/core/vmarks.c, libr/include/r_core.h
I'm not sure if you like this, but i thought it would make visual mark more usable this way, so...
=> Improve visual mark  ##visual

libr/core/cmd_anal.c
When renaming a function fails because no such function exists
at the given address, don't include the new name in the error message
as it is unrelated to the cause of the error.
=> Improve error messages used by afn and afr.

libr/core/cmd_anal.c
We now skip leading whitespace when looking for the first argument
to these commands (the function's name). Previously, the following
command
af  fcn.foo @ 0x000affe
would try to define a function with an empty name at offset
"fcn.foo @ 0x000affe".
=> Improve argument parsing in af, afr and afn.

libr/core/canal.c
When using afu on code with jumps and calls, this error message is triggered. May be related to the fact, that afu does not iterate down into the referenced functions, which is as intended in my situation.
=> remove err dp error message, which is triggered for no reason by afu

libr/core/cmd.c, libr/core/cmd_print.c, libr/core/cmd_type.c, libr/include/r_parse.h, libr/parse/code.c, shlr/tcc/libtcc.c, shlr/tcc/libtcc.h, shlr/tcc/tcc.h, shlr/tcc/tccgen.c, shlr/tcc/tccpp.c
Fixes https://github.com/radare/radare2/issues/14031
=> Fix includes from to ignoring dir.types ##types

libr/anal/fcn.c, libr/anal/op.c, libr/anal/p/anal_x86_cs.c, libr/core/cmd_print.c, libr/include/r_anal.h, libr/util/print.c
Somewhat fixes #13845 .
This only works if the previous instruction before push is a reg mov / lea. A more generic solution would be tracking registers inside the RAnal struct, but I think ESIL should handle that.
Also, sorry for the long absence... real life is a bitch sometimes.
=> Track pushed register (note: immediately after lea/mov) to resolve push-ret

libr/asm/p/asm_x86_nz.c
Fixes #13835  for the asm_x86_nz assembler. 
Btw my system nasm (2.14.02) also has this bug, `lea rdi, [rip + 0x1011]` is assembled to `488db811100000`
=> Fix for rip-relative lea

libr/debug/p/debug_gdb.c, libr/io/p/io_gdb.c
Two separate desc pointers (one in libr/debug/p/debug_gdb.c and one in libr/io/p/io_gdb.c) would result in a UAF during doo, because the debug_gdb.c one would never be nulled.
This is a band_aid fix for this. Please make it less of a kludge.
This issue can be replicated by attaching to any gdbserver session and running doo.
=> initial band-aid fix for a UAF with two seperate desc pointers

shlr/gdb/src/common.c, shlr/gdb/src/gdbclient/core.c, shlr/gdb/src/libgdbr.c
=> [GDB] Longer timeout and better failure handling for response to qSupported packet

libr/cons/output.c
=> Fix bg esc handling in r_cons_w32_print

libr/cons/output.c
=> Fix inverse video esc handling in r_cons_w32_print

libr/include/r_util/r_buf.h
It should be enough to define struct r_buf_t, since the typedef to
RBuffer is already specified.
=> Do not double define typedef RBuffer

libr/util/buf_io.c
=> Do not close IO when RBuffer is freed

libr/core/canal.c, libr/core/cmd_anal.c
* Removed Code Duplication between `cb()` and `r_core_anal_hint_print()`
* Using pj instead of directly printing
* jump, fail and ptr are now directly printed as integers in json
* Fixed `ahj [addr]`
Tests: https://github.com/radare/radare2-regressions/pull/1836
=> Refactor and Complete Anal Hint Printing

libr/cons/cons.c, libr/cons/line.c, libr/include/r_cons.h
Detection of Windows version is done [via registry keys](https://blog.yaakov.online/finding-operating-system-version/). Windows 10 Creators Update [introduced 24-bit color support in cmd.exe](https://devblogs.microsoft.com/commandline/windows-10-creators-update-whats-new-in-bashwsl-windows-console/). Its release id [is 1703](https://pureinfotech.com/what-windows-10-creators-update/).
=> Set scr.ansicon=1 if running under Windows 10 Creators Update or later

libr/anal/reflines.c, libr/core/disasm.c, libr/include/r_anal.h
=> Dfferent color for up and down reflines

libr/anal/sign.c, libr/core/cconfig.c, libr/core/cmd_zign.c, libr/include/r_sign.h, libr/include/r_util/r_num.h
- it will match zignatures which similarity is >= the given threshold
- different thresholds for bytes and graph
- by default thresholds are 1.0, which means it matches only if it’s the exact same
- zign.diff.gthresh and zign.diff.bthresh are the new eval configs to control that
- the output of zc[n!] now contains the similarity value as well
Example:
```
[0x00000000]> . ./zignatures-CoreText-11.2.6-big
[0x00000000]> . ./zignatures-CoreText-11.2.5-big
[0x00000000]> zcn! CoreText1126~ G
Diff by name 3198 3196 (not maching)
0x184c507e8 0x187ad0818 0.95742 G CoreText1125:sym.sec.JapaneseCompositionRules::GetCharacterClass_unsigned_int
0x184c18138 0x187a98108 0.99996 G CoreText1125:sym.sec.TCFBase_TRubyAnnotation_::ClassDestruct_void_const
0x184c55ac8 0x187ad5af8 0.82722 G …
```
=> Make zignature comparison fuzzy ##signature

libr/bin/obj.c, libr/bin/p/bin_fs.c, libr/bin/p/bin_mbn.c, libr/bin/p/bin_mdmp.c, libr/bin/p/bin_menuet.c, libr/bin/p/bin_nin3ds.c, libr/bin/p/bin_ninds.c, libr/bin/p/bin_ningb.c, libr/bin/p/bin_ningba.c, libr/bin/p/bin_nro.c, libr/bin/p/bin_omf.c, libr/bin/p/bin_pe.c, libr/bin/p/bin_pe.inc, libr/bin/p/bin_pe64.c, libr/bin/p/bin_pebble.c, libr/bin/p/bin_sms.c, libr/bin/p/bin_te.c, libr/bin/p/bin_wasm.c, libr/bin/p/bin_z64.c, libr/bin/p/bin_zimg.c, libr/include/r_bin.h
I guess the time has come to remove load/load_bytes from RBinPlugin :)
Hopefully this will allow to clean even further the `r_bin_object_new` function and others as well in the future.
=> Remove last load/load_bytes methods

libr/core/cmd_anal.c
Copies the cross refs pointing to ADDR to also point to curseek/AT.
Useful for dealing with wrapper functions.
Help text:
"axm addr [at]   copy data/code references pointing to addr to also point to curseek (or at)"
=> Adds axm command

libr/include/r_util/r_sys.h, libr/lang/p/pipe.c, libr/util/sys.c
Using `exit()` here leads to atexit functions and C++ destructors to be called in the child process, which is incorrect and in Cutter ultimately makes the forked child processes to be stuck forever even after exiting Cutter.
Maybe `r_sys_exit_immediately()` will need some ifdefs since `_exit()` is not part of C standard, but right now I don't know a platform we support that doesn't have it.
Also maybe it is necessary to flush some streams before the call, as `man _exit` says:
```
Open stdio(3) streams are not flushed.
```
But perhaps someone else here can say more about whether this is necessary here.
=> Use _exit() in pipe child

libr/cons/cons.c, libr/core/cmd_debug.c, libr/core/meson.build, libr/core/windows_heap.c, libr/debug/meson.build, libr/debug/p/debug_native.c, libr/debug/p/native/maps/windows_maps.c, libr/debug/p/native/maps/windows_maps.h, libr/debug/p/native/w32.c, libr/debug/p/native/w32.h, libr/include/r_util/r_sys.h, libr/util/sys.c, libr/util/w32-sys.c, shlr/heap/include/r_windows/windows_heap.h
Only tested on Windows 10 x64, but at least the basics should work on every version.
Also please review
=> Initial implementation of heap parsing for Windows

libr/cons/pal.c
The problem is, under `scr.color=3` the bold esc seq can be taken literally (xfce4-terminal):
... (hard to see the difference) ...
or not at all (cmd.exe):
=> Use bright colors instead of bold in default palette

libr/core/disasm.c, libr/parse/parse.c
test
```
$ cat /tmp/distest.r2
s 0x100001232
pd 1
f fin.dustrial=0x1000054d0
pd 1
s0x100001211
pd 1
```
[ls.zip](https://github.com/radare/radare2/files/3259702/ls.zip)
=> Fix asm.varsub in a hacky way to fix the disasm output ##disasm

libr/cons/d/bright
For those who prefer the original bright colors on `e scr.color=3` @astuder
=> Fix #14254 - Add eco bright (r2 default palette but with bright colors for all)

libr/util/hex.c
* Symptom: Search often failes when hexpairs are separated by spaces, e.g. "01 02 03" vs. "010203".
* Affected: radare2 and rafind2 at least
* Description: While parse-function r_hex_str2bin handles whitespace, auto-generated binmask
(function r_hex_str2binmask, called when no mask is provided) does not, creates oversized mask,
increases byte count, finally causing search for additional undefined bytes.
=> fix hexpairs search containing whitespace

libr/anal/p/anal_arm_cs.c, libr/anal/sign.c, libr/core/cmd_zign.c
- avoid emitting malformed r2 commands in z*, by adding the `n` type for the realname field
- use bytes:mask format instead of combining the mask with bytes, to support sub-nibble masks
- fix and improve anal_mask() for arm64
- add `z/f` command to match signatures against already analysed functions instead of the whole binary
tests fixed here: https://github.com/radare/radare2-regressions/pull/1847
=> Improve zignatures ##signatures

libr/cons/pal.c
Added bold according to https://github.com/radare/radare2/pull/14232/files. This is done because there are Ansi16 color schemes that have poor color separation between normal and bright colors.
=> Add also bold to default palette items that are bright

libr/core/cconfig.c, libr/core/cmd_anal.c
Hey @trufae,
Here's a really dumb/super basic hack for the problem we discussed with aesu/aecu etc running for too much time. Not sure if you want to do something more intelligent but it works. 
Essentially, we offer the user to configure `esil.timeout` in the variables and if this value is >0 then we start a timer and each time we loop we check if the timeout has passed.
This isn't perfect because we could be in the middle of evaluating an expression as the timeout passed. Ideally it would be handled in a thread but this gets more complex.
Is this alright, i noticed you do timeouts differently here:
https://github.com/radare/radare2/blob/master/libr/cons/cons.c#L385-L395
Do we want to use `r_sys_now()` instead of `clock()`?
=> WIP: Really basic implementation of esil.timeout.

libr/core/canal.c
This fixes cases where saving and loading a project of a mixed-mode
binary (e.g. ARM with Thumb parts) reverted functions back to only one
of the modes.
=> Fix afl* not saving function bits

libr/core/cmd_debug.c
Printing `dtd` output faster, but not in color and without opcodes (just address + mnemonic). May be worth considering to enable that only when printing to a file (assuming that, when the output is huge, user will redirect it) and leave current behaviour while not redirecting, so it will be slow, but will not be used with huge outputs.
=> Faster dtd

libr/egg/egg_lang.c
This fix is probably not good, but we should add a test for it, and at some point rework on the ragg2 api cleanup with some refactorings
=> Fix #14296 - Segfault in ragg2

libr/include/r_cons.h
Before (cmd.exe with `asm.highlight=$$` and `scr.color=3`):
After:
=> Reset inverse video first before anything else

libr/cons/pal.c, libr/cons/rgb.c, libr/include/r_cons.h
Probably will use different approach to map to 256-color table.
=> Use id16 instead of id256 for color id

libr/core/cmd_debug.c
In last PR I forgot to call r_anal_op_free after getting pointer to a new RAnalOp, so I'm fixing it now.
=> call r_anal_op_free after acquiring RAnalOp pointer

libr/core/cmd_type.c
It somehow broke when meson released v0.51
=> Fix Appveyor

libr/core/cmd.c, libr/core/core.c
- autocomplete `afn`
- `!!!$eval` says (null)
- autocomplete when there's a space between the eval var and the `=` char.
=> Autocompletion fixes

libr/core/cmd_print.c
As asked for in issue [#14361](https://github.com/radare/radare2/issues/14361)
> sometimes its anoying to add a space to do pd 20 or px 64.. it will be good to make pd.20 or pd20 to work
Both ways implemented
=> Added support for pd and px without space

libr/core/casm.c, libr/core/cmd_search.c
This pull request introduces `/cc` to search for instruction while ignoring **C**ase. (`/ci` is occupied but searching immediate value).
This PR will help fixing https://github.com/radareorg/cutter/issues/1594
```
$ r2 -n /bin/true
[0x00000000]> /c jmp rsp
0x00004d0b   # 2: jmp rsp
0x00004d5b   # 2: jmp rsp
[0x00000000]>
[0x00000000]>
[0x00000000]> /c JMP RSP
[0x00000000]>
[0x00000000]>
[0x00000000]> /c jmp rsp
0x00004d0b   # 2: jmp rsp
0x00004d5b   # 2: jmp rsp
[0x00000000]>
[0x00000000]>
[0x00000000]> /cc JMP RSP
0x00004d0b   # 2: jmp rsp
0x00004d5b   # 2: jmp rsp
[0x00000000]>
[0x00000000]>
[0x00000000]> /cc jmP rSP
0x00004d0b   # 2: jmp rsp
0x00004d5b   # 2: jmp rsp
[0x00000000]>
[0x00000000]>
[0x00000000]> /cc jmp r
0x00001425   # 2: jmp rax
0x00001473   # 2: jmp rax
0x00004d0b   # …
```
=> Introducing /cc for case insensitive instruction search

.appveyor.yml, libr/core/cconfig.c, libr/include/r_util/r_sys.h, libr/util/sys.c, libr/util/w32-sys.c, sys/meson.py
#10613
better #14315
Fixes types and etc not being loaded if radare2 is spawned outside of install dir
=> Dinamically find radare2 install dir on Windows

libr/io/p/io_self.c
Calculation must be done before getting the aligned data, most likely missing few
entries...
=> Fix io/self vm mapping late calculations.

shlr/meson.build
Python 3.5 (the lowest version that meson supports) has no f-String
but only old %-formatting and str.format().
cc @pelijah
=> mesonbuild: Backport to python 3.5

libr/fs/file.c, libr/fs/p/fs_io.c, libr/fs/shell.c, libr/include/r_fs.h
- add `r_fs_file_copy_abs_path` to get the absolute path of a RFSFile, centralizing edge case handling
- use that in `fs_io_read`
- add missing `free (file->path)` in RFSFile destructor
- fix `handlePipes` for fs shell `cat` use case
=> Improve fs io

libr/cons/output.c
Fixes the following problem:
(In Visual mode)
(After quitting Visual mode ... the eip highlight isn't cleared)
=> Clear also attributes on screen clear under scr.ansicon=0

libr/core/visual.c
Fixes #11138 (`a` command in visual mode).
=> Quote wa command generated in visual mode (#11138)

libr/asm/asm.c
In line 694 a buffer of size (sizeof(char*)*32) is allocated. Later on,
this buffer is realloced to 64. This decreases the size of the allocated
buffer instead of increase. This may lead to memory corruption.
| OS/arch/bits (mandatory)                             |  Manjaro X86_64
| File format of the file you reverse (mandatory)      | asm
| Architecture/bits of the file (mandatory)            | x86/32
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22339 @ linux-x86-64 git.3.6.0-86-g4232ac176 commit: 4232ac1763fb533e5a1088732c01fa5394814cd7 build: 2019-07-05__22:40:52
```
$ rasm2 -a x86 -b 32 -f test.txt …
```
=> Fix wrong realloc in r_asm_massemble

libr/core/visual.c
the issue was `core->print->ocur` was not updated properly for JK. After moving the method above, it started working.
=> Fixes #14416: selections in disarm fixed

libr/core/cmd_info.c
As described in issue #14478 
> isq. Should do the same is.q
Tests were implemented and are awating approval; see PR [#1878](https://github.com/radare/radare2-regressions/pull/1878) of radare2-regressions
=> Fix isq. should do the same as is.q

libr/anal/xrefs.c
Fix #14494 
Still kind of slow, but this makes it at least about 10 times faster. The remaining bottlenecks may not be as easy to fix or at least not without removing info.
after these changes:
=> Reduce xrefs sorting for aflj perf ##anal

libr/asm/p/asm_x86_nz.c
Hey there
when assembling a jump relative to the esp register the opcode that is produced by rasm2 is missing an opcode. This patch aims to fix this.
| OS/arch/bits (mandatory)                             | Manjaro X86_64
| File format of the file you reverse (mandatory)      | asm
| Architecture/bits of the file (mandatory)            | x86/32.
| r2 -v full output, **not truncated** (mandatory)     | radare2 3.7.0-git 22315 @ linux-x86-64 git.3.1.3-1935-g56cdeee66 commit: 56cdeee6668ce92f476eb2de85e17d7b9960cc88 build: 2019-07-07__21:04:20
```
$ rasm2 -a x86 -b 32 "jmp [esp+16]"               
ff642410
$ r2 -
[0x00000000]> wx 0xff642410 …
```
=> Fix wrong assembly of jumps relative to the ESP register

libr/cons/dietline.c
Other fixes:
* Warnings due to vi mode
* reused the code for diw/ciw
* Removed unneeded prompt_printing 
* #14521: Add missing dietline binding ^y with ^w.
=> Fixes #14524: vi delete command is now 3dw

libr/anal/meta.c, libr/core/Makefile, libr/core/casm.c, libr/core/citem.c, libr/core/cmd_info.c, libr/core/disasm.c, libr/core/meson.build, libr/include/r_core.h
```
[0x1000011e8]> i.~{}
{
"type": "code",
"perm": "r-x",
"size": 1,
"addr": 4294971880,
"next": 4294971881,
"prev": 4294971875,
"sectname": "0.__TEXT.__text",
"data": "push rbp"
}
[0x1000011e8]> Cd 4
[0x1000011e8]> CC hello world
[0x1000011e8]> i.~{}
{
"type": "data",
"perm": "r-x",
"size": 4,
"addr": 4294971880,
"next": 4294971884,
"prev": 4294971875,
"sectname": "0.__TEXT.__text",
"comment": "hello world",
"data": ".dword 0x56415741"
}
```
=> Fix #14530 - Implementation of i.~{} aka RCoreItem ##anal

libr/core/disasm.c
This PR adds "arrow" information to the `pdJ` command.
The purpose is that even if `asm.lines` is false, the information of the refline is still present in the json.
I'm not totally satisfied with this solution, but that's the more clean approach I found.
=> WIP: Added arrow info to pdJ

libr/bin/format/mach0/mach0.c
Also remove a wrong consistency check, as nodes with linking info which also have children are allowed.
=> Avoid loops in Mach-O export trie walking ##bin

libr/bin/format/mach0/mach0.c, libr/bin/format/mach0/mach0_defines.h
- skip reexports and “stub and resolver” exports for now, the semantics are different and need to be treated in a different way
- but advance the pointer accordingly, to avoid loosing sync while walking the trie (especially in dyld cache)
=> Handle the export flags to avoid de-syncing ##bin

libr/cons/canvas.c, libr/include/r_cons.h
This should improve performace as you don't need to shift elements of
the sorted array when you need to insert a new one.
Fixes #14553
Please do test the PR before merging. I've already tested on linux on my /bin/ls, but another run would not hurt :)
=> Use HtUP to store canvas attributes instead of a sorted array

libr/core/disasm.c
#14277
This only works for call and jmp instructions
=> Show relocs as flags in disassembly for call and jmp instr.

libr/cons/cons.c
Tests: https://github.com/radare/radare2-regressions/pull/1895
Regression introduced by https://github.com/radare/radare2/pull/14563, though the pr itself is good.
You would get unwanted newlines before the output, which was especially annoying in Cutter's console where every command is run in a task.
=> Fix grep in tasks ##cons

libr/io/cache.c
commenting out the line fixes https://github.com/radare/radare2/issues/14484
what was the old behavior ?
=> [rio] fix r_io_cache_commit to commit all lines

libr/bin/format/objc/mach0_classes.c, libr/bin/format/objc/mach0_classes.h, libr/bin/p/bin_dyldcache.c, libr/core/cbin.c
Plus:
- use it in `icc`
- improve `icc` for Objective-C to print more methods (the return type display can be improved, but at least all methods are there)
tweaked tests: https://github.com/radare/radare2-regressions/pull/1900
=> Parse Objetive-C superclass name

libr/bin/format/elf/elf.c, libr/bin/format/elf/elf_specs.h, libr/bin/format/elf/glibc_elf.h
I've run into a few cases in which rabin2 didn't recognize the e_machine value in an elf header, this PR adds a bunch from http://www.sco.com/developers/gabi/latest/ch4.eheader.html, which was the most complete source I could find.
=> Add e_machine values

libr/include/r_parse.h, libr/parse/ctype.c
Now also supported: `struct something`, `union something` and `enum something`
Test: https://github.com/radare/radare2-regressions/pull/1903
=> Support struct/enum/union before name in ctypes parse

libr/core/cmd_debug.c
Hey there :)
I've noticed a small bug where the `addroflib` function returns the wrong lib address. Consider the following example:
Working:
```
r2  -c "dcu main; dmi libc~system"  -d /bin/ls
[...]
1421 0x00047850 0x7fa986cc1850   WEAK   FUNC   45 system
[...]
``` 
**Not** working:
```
r2  -c "dcu main; dmi libc~system"  -d /tmp/libc/ls
--> Nothing found
``` 
This happens because `addroflib` matches the search query `libc` using `strstr` on the full library path, hence the `/tmp/libc/ls` gets picked over the actual libc path. This causes `dmi` to be executed on `/tmp/libc/ls` instead of the `libc.so` file.
In my opinion this should match on the library *name* instead of the full path, as suggested by:
```
[0x00000000]> dmi?
Usage: dmi    # List/Load Symbols
| dmi[libname] [symname]  List …
```
=> cmd_debug.c: Make addroflib use basenames

libr/debug/p/debug_windbg.c, libr/io/p/io_windbg.c, shlr/windbg/windbg.c, shlr/windbg/windbg.h
* Fix #10505
* Fix wrong register profile being picked
* Fix use-after free(s) and null derefs
=> Some fixes for windbg

libr/cons/dietline.c, libr/cons/line.c, libr/include/r_cons.h
=> WIP: emacs keybindings

libr/core/cconfig.c
Otherwise calls to really-long symbol names would go off the screen in Visual mode and this might upset people who are not aware of this config var.
=> Default scr.breaklines to true

libr/cons/dietline.c, libr/cons/hud.c
Fixes: 
* up/down are inverted correctly
* it is possible to not possible to scroll beyond the end with page up
* Mouse is disabled in hud mode
* change the ^p/^n behavior to go to prev/next line.
=> Fixes #14652: Fixes visual hud regressions

libr/bin/d/macho, libr/bin/format/mach0/mach0.c, libr/util/format.c
Plus:
- improve macho format definitions
- allow enums and bitfields with arbitrary size
- avoid modifying the format string argument inside r_print_format()
tweaked tests: https://github.com/radare/radare2-regressions/pull/1905
Samples:
```
$ r2 ~/shit/ls
-- r2 is a great OS, but a terrible hex editor
[0x1000011e0]> iH
pf.mach0_header @ 0x100000000
0x100000000  Magic       0xfeedfacf
0x100000004  CpuType     0x1000007
0x100000008  CpuSubType  0x80000003
0x10000000c  FileType    0x2
0x100000010  nCmds       18
0x100000014  sizeOfCmds  1800
0x100000018  Flags       0x200085
pf.mach0_segment64 @ 0x100000020
0x100000020  cmd       0 0x19 LC_SEGMENT_64
0x100000024  cmdsize     72
0x100000028  name        __PAGEZERO
pf.mach0_segment64 @ 0x100000068
0x100000068  cmd       1 0x19 LC_SEGMENT_64 …
```
=> Improve Mach-O header fields ##bin

libr/anal/meta.c, libr/config/config.c, libr/cons/grep.c, libr/core/canal.c, libr/core/cconfig.c, libr/core/cmd_anal.c
Before PR when opening and closing Cutter with basic executable:
`SUMMARY: AddressSanitizer: 811129 byte(s) leaked in 16725 allocation(s).`
After changes:
`SUMMARY: AddressSanitizer: 588035 byte(s) leaked in 15023 allocation(s).`
=> Fix some leaks found by ASAN.

libr/bin/format/mach0/mach0.c, libr/util/format.c
- they’re now aligned with libr/bin/d/macho
- also tweaked r_print_format_struct_size to work with referenced format names
tweaked tests: https://github.com/radare/radare2-regressions/pull/1907
Samples:
```
$ r2 -nn ~/shit/ls
-- If you're not satisfied by our product, we'll be happy to refund you.
[0x00000000]> pd1@@mach0_cmd*
;-- mach0_cmd_0:
;-- mach0_segment64_0:
0x00000020 pf mach0_segment64 # size=72
cmd : 0x00000020 = cmd (enum mach0_load_command_type) = 0x19 ; LC_SEGMENT_64
cmdsize : 0x00000024 = 72
segname : 0x00000028 = "__PAGEZERO"
vmaddr : 0x00000038 = (qword)0x0000000000000000
vmsize : 0x00000040 = (qword)0x0000000100000000
fileoff : 0x00000048 = (qword)0x0000000000000000
filesize : 0x00000050 = (qword)0x0000000000000000
maxprot : 0x00000058 = (octal)  000000000
initprot : …
```
=> Update Mach-O hardcoded format definitions ##bin

libr/core/cbin.c
Hello there. Since @blenk92  and me looked at potential issues for the PwnDebian challenge, we are proposing a fix regarding quoting for the `is` / `is*` commands.
This fixes the output, so that
```
f sym.imp.__sprintf_chk 16 0x00000000
```
becomes
```
"f sym.imp.__sprintf_chk 16 0x5562473eb000"
```
when executing `is*`.
Greetings
=> bin_symbols: Add quoting

binr/r2pm/r2pm, man/r2pm.1
The r2pm shell script had a few oddities:
- the manpage and help text said that info on the repository and installed packages could be shown with `-i` or `info`; however, neither of those did anything except `-i` which is already the flag for r2pm_install
- R2PM_Info was being called when arguments were missing to r2pm_install() and r2pm_uninstall(), as if it was the help function, but the call from r2pm_install() was in the wrong place
These are now (hopefully) resolved. Fixes radare/radare2-pm#86.
=> r2pm: handle info and install arguments properly

libr/include/r_cmd.h, libr/include/r_parse.h, libr/include/r_util/pj.h, libr/include/r_util/r_sys.h
Small PR that fixes -Wstrict-prototypes warnings.
=> Use void in function prototypes

libr/core/cmd_type.c
Adds missing JSON output for `tl` and `tll` type link commands.
=> add tlj and tllj

libr/bin/mangling/microsoft_demangle.c
* Fix #12911 - Fix types starting with 'void' not being considered
* Fix abbreviated names being lost
=> Fixes for msvc demangling

libr/core/disasm.c
=> Add fcn name in Visual mode if necessary when asm.filter=false and asm.jmpsub=false

libr/bin/filter.c, libr/bin/format/elf/elf.c, libr/cons/pal.c, libr/core/cbin.c, libr/core/cconfig.c, libr/core/cmd_print.c, libr/core/cmd_search.c, libr/core/disasm.c, libr/core/vmenus.c, libr/main/rasm2.c
SUMMARY: AddressSanitizer: 255295 byte(s) leaked in 6418 allocation(s).
=> Fix memory leaks part 2

libr/anal/p/anal_x86_cs.c
In the future it should be isolated into the function.
=> Fix #12750 - support type propagation for SUB, ADD

libr/core/cmd_debug.c, libr/debug/map.c, libr/debug/p/debug_native.c, libr/include/r_debug.h, libr/include/r_util/r_sys.h, libr/util/sys.c
Providing new 'dmL' debugger sub command.
This is the only system having THP feature, others are more into
direct huge tlb equivalent ...
The system ought to be set in madvise mode and disabled on Android,
would not do any good in this environment if this is ever supported.
Once the syscall succeed, the address range ought to get the
little 'hg' VmFlags.
=> Linux debug plugin, page promotion feature proposal.

shlr/capstone.mk
Without this build with `--with-syscapstone` will fail. It also affects latest release (3.7.0).
=> Fix build with system capstone (--with-syscapstone)

libr/core/cmd.c
Docs and internal help claims that grep help available via `~??` command, but in fact it's available via `~?`. This change makes grep help available via both `~?` (for backward compatibility) and `~??`.
=> Fix `~??` command (grep help)

libr/core/cbin.c
After https://github.com/radare/radare2/pull/14690 it is still possible to do injection through is* using a symbol name containing a `"`.
For example: [ls.gz](https://github.com/radare/radare2/files/3496619/ls.gz) execute `.is*` or `ood` on this bin, cc @ps1337 
This patch makes the names in is* more consistent with the actual flag names and also fixes a leak.
The diff looks a bit wild because of indentation changes, the significant changes are around the `construct_symbol_flagname()` calls.
=> Refactor is* and fix Injection harder

libr/anal/fcn.c, libr/core/canal.c, libr/core/cmd_anal.c, libr/include/r_anal.h, libr/include/r_core.h
this patch allow for detection of noreturn functions.
before:
```
┌──────────────────────────────────────────────────┐ 
│ [0x40113f]                                       │ 
│ (fcn) main 45                                    │ 
│   int main (int argc, char **argv, char **envp); │ 
│ ; var char **var_10h @ rbp-0x10                  │ 
│ ; var signed int var_4h @ rbp-0x4                │ 
│ ; arg signed int argc @ rdi                      │ 
│ ; arg char **argv @ rsi                          │ 
│ ; DATA XREF from entry0 @ 0x401071               │ 
│ push rbp                                         │ 
│ mov rbp, rsp                                     │ 
│ sub rsp, 0x10                                    │ 
│ ; argc                                           │ 
│ mov dword [rbp - var_4h], edi …
```
=> Propagate noreturn information

libr/cons/dietline.c, libr/core/core.c
* Accept both '\\' and '/' as path separators
* Accept paths starting with '\\' or '/' as meaning root of cwd
* Other fixes
=> Fixes for path autocompletion on Windows

libr/include/r_util/r_print.h, libr/util/print.c
=> Fix r_print_color_op_type param type mismatch

.builds/freebsd.yml, .builds/openbsd.yml
SourceHut allows to setup FreeBSD and OpenBSD CI right now, and NetBSD should be available soon.
=> Add *BSD SourceHut builds

libr/core/agraph.c
* Does not print the function name
* Basic blocks are already represented by ##
=> Fixes #14267: Stop printing the function name for agft

libr/core/cmd_search.c
This improves performance a bit, but for some archs r_anal_op doesn't provide mnemonics, so we have to call r_asm_disassemble
=> Avoid disassembling the same instruction twice on rop search

libr/core/cio.c
Consider the architecture endianness when performing the bytewise block operations. 
The provided ___endian_swap_ function may be used to provide a representation of the whole memory buffer with the correct endianness for each word as it would be when loaded from memory. In practice the byte order change that results from reading and writing back to memory has the same effect as changing the byte order of the literal used in the operation. Therefore I just change the byte order for the literal in the PR.
=> Consider endiannes when performing block write operations

libr/search/keyword.c, libr/util/regex/regcomp.c
Fix #14202
I followed coding the style of regcomp.c, should I change?
=> Fix #14202 - Add support to '\d', '\w', etc. in regex

libr/anal/fcn.c, libr/anal/op.c, libr/anal/p/anal_x86_cs.c, libr/core/disasm.c
Following #14773 (more specifically https://github.com/radare/radare2/pull/14773/files#diff-7f6f82199b572cdbe767aa7a1ba9b436L2391).
=> Use op->disp instead of op->ptr for disp of x86 MOV (and others)

libr/debug/debug.c, libr/debug/p/debug_native.c, libr/debug/p/native/drx.c, libr/include/r_debug.h, libr/include/r_drx.h
When the debugger hits an hardware breakpoint it does not notify the user, for example, by printing to the screen that a breakpoint was hit. This makes debugging code using hardware break points cumbersome and difficult to follow, as it is hard to tell what caused the debugger to stop. This pull request prints a line to the console whenever an hardware break point is hit - the line contains the breakpoint number and its location.
example:
[0x7fb4ada16100]> drx 0 main 1 e
[0x7fb4ada16100]> dc
hit hardware breakpoint 0 at: 55e241008060
=> notify user on hardware breakpoint hit

libr/anal/esil.c
=> Hide the shift overflow warnings under esil.verbose

libr/anal/fcn.c, libr/anal/p/anal_x86_cs.c, libr/core/anal_tp.c, libr/core/disasm.c
=> Use op->disp instead of op->ptr for disp of x86 CMP (and ACMP)

libr/cons/cons.c, libr/core/cconfig.c, libr/core/cmd.c, libr/core/core.c, libr/core/task.c, libr/include/r_cons.h, libr/include/r_core.h
Racy otherwise (depths from different tasks will "add up")
=> Make cmd_depth task-local

libr/core/agraph.c, libr/core/cmd_anal.c
When in aggi mode, when pressed enter. The core->offset is not updated, thus forcing the update of the current seek
=> Fixes #14859: Enter used to update seek in interactive graphs

libr/core/disasm.c
This makes reading iOS apps much simpler by removing lot of false positive strings
=> Do not try to resolve strings pointed by adrp instructions on arm64 #disasm

libr/anal/d/Makefile, libr/anal/d/cc-hexagon-32.sdb.txt, libr/asm/arch/hexagon/hexagon_disas.c
Changes have been:
- Signed values get now printed as decimal (and therefore with sign): https://github.com/radare/radare2/issues/14849
- Immediate extensions now expand also duplex containers + missing non-duplex extensions added: https://github.com/radareorg/r2hexagon/pull/7
- Calling convention added
=> Syncing with r2hexagon

libr/util/print.c
We have only two bg based colors in the palette :]
=> Fixes #14911: Use theme colors for p= and p==

libr/core/cio.c, libr/core/cmd_print.c, libr/include/r_core.h
This adds the functionality from #14758. 
The code mostly borrows from `wo` but there are several options in `wo` that I decided not to include because the command doesn't really depend on the data block (i.e. `e`, `p`, `R`, `w`). I haven't (yet) implemented encryption and decryption.
=> Add po[..] set of commands

libr/anal/p/anal_avr.c
Lack of BP alias causes assertion fail in `libr/anal/esil.c:internal_esil_reg_write_no_null(...)` 
`WARNING: internal_esil_reg_write_no_null: assertion 'pc && sp && bp' failed (line 409)`
=> Add frame pointer to AVR register profile

libr/core/cmd_help.c
This does not show only dec and hex
```
? 0x32-0x14
int32   30
uint32  30
hex     0x1e
octal   036
unit    30
segment 0000:001e
string  "\x1e"
fvalue: 30.0
float:  0.000000f
double: 0.000000
binary  0b00011110
trits   0t1010
```
=> fix help message of ?

libr/anal/esil.c
I am not sure if I did it right. Waiting for your feedback.
=> Fix #14939: Replace assertions about missing RReg profile registers with warnings

libr/anal/esil.c, libr/anal/p/anal_arm_cs.c
Fixed esil implementation of =[*] to properly process constructs like `32,sp,-=,r1,r2,r3,r4,r5,r6,r7,lr,8,sp,=[*]`
Fixes #10631, also related to issue #10632
=> fixing esil =[*] (poke multiple regs/values)

libr/asm/arch/ebc/ebc_disas.c
Previously, if no immediate data was specified, the operand was not displayed.
=> Display operand of EBC push/pop instructions

libr/core/cio.c
This fixes  #14937
```
$ build/binr/radare2/radare2 -
[0x00000000]> b 8
[0x00000000]> wx 0102030405060708
[0x00000000]> wo2
[0x00000000]> p8
0201040306050807
[0x00000000]> wx 1020304000000000
[0x00000000]> p8 4
10203040
[0x00000000]> wo2
[0x00000000]> p8 4
20104030
[0x00000000]> p8 8
2010403000000000
[0x00000000]> wx 10203040
[0x00000000]> wo4
[0x00000000]> p8 8
4030201000000000
```
=> Fixed logic in 2-byte endian swap used by "wo2"

libr/anal/p/anal_arm_cs.c
ESIL for ARM thumb was not setting NF (sign flag) for arithmetic instructions.
=> add nf flag in ESIL generated for ARM thumb

libr/include/r_endian.h, libr/include/r_types.h, libr/include/r_util/r_buf.h
These lines lead to tons of warnigs when compiling Cutter (example: https://ci.appveyor.com/project/radare/cutter/branch/master/job/iec7gsa697rdrv9i#L3134)
=> Fix MSVC warnings

libr/util/thread.c
as it is 6.6 soon it is safe to go.
=> OpenBSD supports thread name feature since 6.5

libr/io/p/io_ihex.c
It seems like every other io plugin updates io->off when seeking and forces all reads to be from io->off, but ihex only does the latter, which seems to be breaking most high level read_at functions.
I noticed this when disassembling a hex file that used a lot of PC relative data loads -- the helpful comments at the end of the line to show the actual data being loaded were all just showing the opcode of the instruction that I started the disassembly on.
=> Update io->off when seeking in intel hex

libr/anal/type.c
When re-loading multiple types in a single file, only one was deleted before loading the new ones, here is an example: https://github.com/radare/radare2-regressions/pull/1945
=> R2CON2019 Fix Deleting old Types before Load

libr/cons/dietline.c
heap buffer overflow existed in dietline autocomplete, this fixes the issue.
detected by ASAN
=> R2CON2019: fix heap buffer overflow in dietline autocomplete

libr/anal/anal.c, libr/anal/esil.c, libr/anal/fcn.c, libr/anal/meta.c, libr/anal/reflines.c, libr/core/blaze.c, libr/core/canal.c, libr/core/citem.c, libr/core/cmd_anal.c, libr/core/cmd_meta.c, libr/core/cmd_print.c, libr/core/disasm.c, libr/core/visual.c, shlr/sdb/src/sdb.c
Before: SUMMARY: AddressSanitizer: 717346 byte(s) leaked in 18522 allocation(s).
After: SUMMARY: AddressSanitizer: 100800 byte(s) leaked in 1853 allocation(s).
=> Fix memory leaks and other problems found by ASAN.

libr/anal/p/anal_arm_cs.c
At r2con I had an idea for an r2wars bot but it wasn't supported in ESIL. Implement it !
There are other modes that could be supported (stmib, stmda, stmdb), but
that should do for now.
=> esil: fix arm32 stmia post-increment

README.md
Better yet, fork https://github.com/0ki/r2lrn and make r2lrn and r2golf a (part of the) official repo.
=>  R2CON2019 Link to r2lrn and r2golf in the readme

libr/core/disasm.c
`asm.bb.line` without analysis info can be misleading.
=> Remove code for no-anal asm.bb.line

libr/core/cmd_anal.c
=> Fixed a typo in "afj" help

binr/r2pm/r2pm
It is confusing that `r2pm update` only updates the database and the packages are not updated. Information about how to update a specific package is missing.
When the user searches for information how to update a particular package, e.g. using `r2pm -h`, the help provides information only how to install a package. This commit adds info that `r2pm -i` is also used for pkg update.
=> Add info that r2pm -i is also used for pkg update

libr/core/cmd_print.c
Since `pd 5 arm 16 @ 0xaddr` is no longer supported and `pd 5 @0xaddr@a:arm@b:16` is the preferred way of doing this, removing leftover instructions in `pd?`.
Renamed `[sz]` to `[len]` to be consistent with other hints in `p?`.
Before:
```
[0x00000000]> pd?
Usage: p[dD][ajbrfils] [sz] [arch] [bits]   # Print Disassembly
```
After:
```
[0x00000000]> pd?
Usage: p[dD][ajbrfils] [len]   # Print Disassembly
```
=> Hotfix pd arch bits

libr/debug/p/debug_gdb.c
This PR is in regards to issue #14987 
Basically, if new architectures are added via plugins (or even integrated directly into radare2, come to think of it), the `debug_gdb` backend won't connect correctly, as the supported architectures are hardcoded.
This PR can be used to discuss how to solve this issue elegantly. Here are my thoughts:
The easy solution - we just add more architectures to the list. However, does it not defeat the purpose of this list, if the mainline version of radare2's `debug_gdb` backend indicates support for obscure architectures that aren't integrated into the core, and require additional plugins?
The "correct" solution - use a custom debug plugin that mirrors the original `debug_gdb` functionality. That sounds like a terrible idea to me, as it's a maintenance …
=> Added ba2 so that the gdbserver backend connects correctly

libr/bin/bfile.c
Before:
`SUMMARY: AddressSanitizer: 44126 byte(s) leaked in 465 allocation(s).`
Now:
`SUMMARY: AddressSanitizer: 19393 byte(s) leaked in 7 allocation(s).`
=> Fix memleak when closing bin file

libr/debug/p/debug_gdb.c, libr/debug/p/gdb.mk, shlr/gdb/src/gdbclient/core.c
Two fixes:
1. Byte order of the written value is target-defined. Use `cfg.bigendian` for now. Possibly get it from target later?
2. Register number in write command (`P`) should be hexadecimal.
Hope it doesn't ruin other archs - but it complies with the definitions of the protocol (https://sourceware.org/gdb/onlinedocs/gdb/Packets.html#Packets), so should actually fix existing problems that nobody reported.
=> Fix gdb reg write byte order

libr/anal/p/anal_avr.c
Fix wrong opcode values in `opcodes[]` table in `libr/anal/p/anal_avr.c` for `sbis` and `sbic` instructions. Also add `op->fail` for proper branching handling.
Before change:
After change:
=> Fix AVR SBIx instruction analysis

libr/include/r_types.h
Also tested with `sys/user.sh`, works fine.
=> Fix R2_PREFIX for Meson non-Windows builds with custom prefix

libr/cons/dietline.c
Before changes it was possible to scroll past the end of list in hud and impossible to scroll back.
=> Fix bound check for hud scrolling with arrow keys.

libr/core/cmd.c
```
[0x00000000]> $v=1337
[0x00000000]> $v?; ?e lol
1337
lol
[0x00000000]> $v?n; ?e lol
1337lol
[0x00000000]>
```
=> Add a way to print an aliased without a trailing new line

sys/ldconfig.sh
It seems that commit 7e5f1f5851ea41f615bf956c54d4f48abfcf46ad attempted to prevent /etc/ld.so.conf.d/radare.conf from being added and ldconfig from being necessary when the user installs into /usr instead of /usr/local. This patch achieves that behaviour.
=> Don't run ldconfig when installing into /usr

libr/anal/p/anal_i4004.c, libr/asm/arch/i4004/i4004dis.c
Radare is not handling jump instructions of the Intel 4004 architecture according to the specs. For additional details see [here](http://datasheets.chipdb.org/Intel/MCS-4/datashts/MCS4_Data_Sheet_Nov71.pdf) and [here](http://bitsavers.informatik.uni-stuttgart.de/components/intel/MCS4/MCS-4_Assembly_Language_Programming_Manual_Dec73.pdf).
=> Fixed i4004 arch to be according to spec

libr/asm/p/asm_x86_nz.c
Fixes some missing/wrong operand size prefixes
and a corrects a typo in handling 64-bit offsets.
=> Fix x86 assembler output for some memory loads

libr/util/lib.c
for https://github.com/radareorg/r2ghidra-dec/issues/38
This prevents constructors, for example doing C++ static initialization, from being executed twice.
=> Move Lib already loaded check before dlopen Call

libr/parse/ctype.c
=> Fix double typedef of RParseCType (Fix #15085)

libr/anal/sign.c, libr/core/cconfig.c, libr/core/cmd_zign.c, libr/include/r_sign.h
Integrated types in the most significant 'z' commands.
By the way, is the "vars" field implemented into the commands? 
When I  `git grep "r_sign_match_vars"`, can only see the definition and the implementation, but not even a single use for this fcn.
=> Integrate types field in zignature operations ##signatures

sys/debian.sh, sys/debian/arch.mk, sys/debian/deb_hand.mak, sys/debian/radare2-dev/CONFIG, sys/debian/radare2/CONFIG
Hi guys. My ex wife (ohcanada) begged me to ask you to consider this pull request that addresses issues with the debian package scripts in sys/
This is tested by myself also and works fine thus far.
The first issue is the md5sums file in the debian control dir, which is corrected to have 2 spaces between sum and filename. The net result is that the dpkg -V radare2 (for verify) completes successfully.
Also fixed is stripping the executables and libraries, and finally using xz instead of gz in the tar process, which is part of the manual build. The net result of that is a huge reduction in package and installed sizes.
=> Debian package scripts fixes

libr/util/str.c
1) Don't use `strlen()` to calc the tail len
2) Use `memmove()` instead of `strdup() + memcpy() + free()`
3) Use `realloc` only if `vlen != klen`
=> Some optimization for r_str_replace() and r_str_replace_icase()

libr/include/r_socket.h, libr/socket/proc.c, libr/socket/socket.c
On Windows SOCKET is unsigned int so compiler optimize some checks out.
=> Add R_INVALID_SOCKET macro

libr/core/carg.c
Otherwise Vvjjjjj crashes with strdup null deref.
Fixes #15093
=> Check return of r_anal_cc_func

libr/cons/cons.c, libr/core/vmenus.c, libr/include/r_cons.h
After change:
Actual function name: sym.android_app_Activity.onCreateOptionsMenu (as seen as fcn in disasm)
=> Fix #14919: truncate long function names in Vv

libr/cons/stiv.c
Removed cause for warning of misleading indentation of 'if' clauses.
=> Update stiv.c to remove warning

libr/anal/esil.c
=> libr/anal/esil: make esil_{o,s}f use arguments

libr/core/agraph.c
`sdb_set_owned()` should be used instead of `sdb_set()` since value is constructed via `r_str_newf()`
=> Fix memleak in libr/core/agraph.c

libr/asm/p/asm_x86_nz.c
Added tests in https://github.com/radareorg/radare2-regressions/pull/1966
=> Fix parsing of floating point instructions in x86_64 assembler

libr/util/date.c
Before:
```
$ valgrind rax2 -t 1234567890
==25880== Memcheck, a memory error detector
==25880== Copyright (C) 2002-2017, and GNU GPL'd, by Julian Seward et al.
==25880== Using Valgrind-3.14.0 and LibVEX; rerun with -h for copyright info
==25880== Command: rax2 -t 1234567890
==25880== 
Sat Feb 14 00:31:30 2009
==25880== 
==25880== HEAP SUMMARY:
==25880==     in use at exit: 26 bytes in 1 blocks
==25880==   total heap usage: 19 allocs, 18 frees, 21,070 bytes allocated
==25880== 
==25880== LEAK SUMMARY:
==25880==    definitely lost: 26 bytes in 1 blocks
==25880==    indirectly lost: 0 bytes in 0 blocks
==25880==      possibly lost: 0 bytes in 0 blocks
==25880==    still reachable: 0 bytes in 0 blocks
==25880==         suppressed: 0 bytes in 0 blocks
==25880== Rerun with --leak-check=full to …
```
=> Fix memleak in r_print_date_unix

libr/main/rax2.c
The following test kept failing on my machine over and over because of timezone issues. 
```
[XX] db/tools/rax2 rax2 -t 1234567890  166
$ r2 -escr.utf8=0 -escr.color=0 -escr.interactive=0 -N -Q -i /tmp/tmp-10988viBOBuJrS7XP -
!rax2 -t 1234567890 | cut -d " " -f 1,2
-Fri Feb
+Sat Feb
EXPECT=<<RUN
Sat Feb
```
This was annoying me for quite some time now. This PR adds the possibility to specify the timezone with the timestamp. I thought this might be also useful in other situations. Examples:
```
$ rax2 -t "1234567890"         
Sat Feb 14 00:31:30 2009
$ rax2 -t "1234567890 GMT0"  
Sat Feb 14 00:31:30 2009
$ rax2 -t "1234567890 GMT-1" 
Fri Feb 13 23:31:30 2009
$ rax2 -t 1234567890GMT-1
Fri Feb 13 23:31:30 2009
$ rax2 -t "1234567890 GMT+10" 
Sat Feb 14 10:31:30 2009
```
I also opened a PR …
=> Add possibility to specify time zone with rax2 -t

libr/asm/arch/8051/8051_ass.c, libr/asm/arch/8051/8051_ass.h, libr/asm/asm.c, libr/asm/meson.build, libr/asm/p/8051.mk, libr/asm/p/asm_8051.c
written from scratch, so it's entirely dependent on rasm2 to do the heavy
lifting, and perhaps lacking in features?
8051 syntax didn't make things easy; ampersand and pound signs caused
integration problems, requiring the rasm and regressiontest code to be patched.
=> add 8051 assembler plugin

libr/anal/bb.c
`r_anal_get_fcn_at` seems to return a function iff the current seek is at the entry point of the function. I think `r_anal_get_fcn_in_bounds` is what should be used?
See issue 15181.
=> fix for VV going to V (issue 15181)

libr/asm/arch/tricore/gnu/tricore-dis.c
* Fixes #15150
* Allow precompiler var RESOLVE_SFR_NAMES to be set
=> WIP: Initial tricore disassembler print address instead of register

libr/parse/p/parse_x86_pseudo.c
There's no particular reason to make the sub variables
uppercase when asm.ucase is enabled. Plus the color parser
does not recognize uppercase subvariables, so now everything
is properly colorized.
Will fix https://github.com/radareorg/cutter/issues/1749
=> Removed uppercase sub variables

libr/bin/format/elf/elf.c, libr/bin/p/bin_pe64.c
I got a C99 compile error on one machine:
```
/libr/bin/p/bin_pe64.c:371:3: error: ‘for’ loop initial declarations are only allowed in C99 or C11 mode
for (int i = 0; i < tbl.Count; i++) {
^
```
this PR fixes it. Not sure why I can compile without error on another machine.
Sorry, I am still a git n00b. I see a previous commit might cause trouble with this one, but I am unsure how to put my fork in the correct state. Help or recommended reading would be appreciated.
=> Fix C99 Compile errors

libr/asm/arch/arm/armass.c
Tests: https://github.com/radareorg/radare2/issues/10651#issuecomment-538160017
```
0:	e24dda01 	sub	sp, sp, #4096	; 0x1000
4:	e24ddb01 	sub	sp, sp, #1024	; 0x400
8:	e21ddb01 	ands	sp, sp, #1024	; 0x400
c:	e24ddb01 	sub	sp, sp, #1024	; 0x400
10:	e24dda01 	sub	sp, sp, #4096	; 0x1000
14:	e24dd901 	sub	sp, sp, #16384	; 0x4000
18:	e24dd401 	sub	sp, sp, #16777216	; 0x1000000
1c:	e24dd201 	sub	sp, sp, #268435456	; 0x10000000
20:	e24dd00a 	sub	sp, sp, #10
```
=> Fix #10651 - ARM assembler for 'sub sp, sp, 0x1000' ##asm

libr/core/visual.c
This is an attempt to clean how visual mode cycle through the different printing formats.
this is far from perfect:
- when cycling between different print mode the format index is not updated
- the format cycling in debug print mode is a bit funky, if cursor mode is enabled the print mode index is displayed instead of the format index when cycling through print modes.
=> visual: Refactor print format

libr/core/cmd_debug.c, libr/debug/p/native/linux/linux_debug.c
`drf` was messed up because of missing quotes at linebreaks
=> Fix `drf` output formatting

libr/anal/p/anal_x86_cs.c
hm, not sure, but to me this looks like cf is always "zf,!,cf,:=" at the end, so maybe that would be a bit faster and produce slightly shorter esil, but not completly sure about this atm ... anyway, this pr should fix the #15250
I didn't update my own r2r repo, so expect red travis. I havent got time to update that now
=> anal_x86_cs fix esil expr for neg instruction

libr/core/cmd_debug.c, libr/debug/pid.c, libr/include/r_debug.h
dpt handled 'j' by getting it from the pid field in "dpt ", this wasn't intuitive(or documented) and it wasn't viable in case an actual pid was provided.
[0x7fcefa5a7090]> dptj
[{"pid":5928,"status":"s","path":"ls"}]
[0x7fcefa5a7090]> dptj 1
[{"pid":1,"status":"S","path":"systemd"}]
=> JSON output for dpt

libr/anal/fcn.c
https://github.com/radareorg/radare2-regressions/commit/d8a299bdfe2da3a970598fe7be56894db30bb183
=> Add jumptable support for main() in bins/elf/analysis/ls-alxchk

libr/debug/pid.c
While fixing JSON support for dpt I didn't notice that the JSON packing implementation was missing a field that was [available](https://github.com/radareorg/radare2/blob/82bff79820abc796c43cf46de6359f4eed3e5b9b/libr/debug/pid.c#L56) in the printed version. This small patch takes care of it.
=> Add current thread field to dptj

libr/core/cmd_debug.c
Drr/Drrj([r_core_debug_rr](https://github.com/radareorg/radare2/blob/master/libr/core/cmd_debug.c#L1998)) calls [r_core_anal_hasrefs](https://github.com/radareorg/radare2/blob/master/libr/core/core.c#L2053) which may fail due to an invalid value in a register with the following message:
[WARNING: r_core_anal_hasrefs_to_depth: assertion 'core && value != UT64_MAX' failed (line 2063)](https://github.com/radareorg/radare2/blob/master/libr/core/core.c#L2063)
The execution of r_core_debug_rr continues regardless of the failure and the value is taken from r_reg_get_bvalue later on. 
While value and reg are printed/populated in the JSON, ["ref" is skipped](https://github.com/radareorg/radare2/blob/master/libr/core/cmd_debug.c#L2079), breaking the JSON format from that point onwards and messing …
=> Fix incomplete drr/drrj formatting of registers with invalid values

libr/bin/format/elf/elf.c
I was trying r2 out on a very large binary (5.6G) [debug symbols take up a lot of space!] and noticed that rabin2 was unable to parse most of the symbol table.
This fixed the issue for me and looks sane enough. I couldn't track the blame on the 32-bit cast far enough to find a reason not to get rid of it. Let me know if that sounds Wrong and Bad.
=> (elf) avoid truncating binary length to 32 bits

libr/cons/cons.c, libr/cons/dietline.c, libr/cons/utf8.c, libr/core/cconfig.c, libr/include/r_cons.h
This should fix tests on Appveyor
=> Move UTF-8 setting logic to scr.utf8 config callback on Windows
